import type { Metadata } from 'next';
import ScrollReveal from '@/components/public/scroll-reveal';

export const metadata: Metadata = {
  title: 'Terms of Service — Zonga',
  description: 'Terms and conditions for using the Zonga music platform.',
};

export default function TermsPage() {
  return (
    <main className="min-h-screen">
      <section className="relative py-32 bg-navy overflow-hidden">
        <div className="absolute inset-0 bg-mesh opacity-40" />
        <div className="relative z-10 max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <ScrollReveal>
            <h1 className="text-4xl md:text-5xl font-bold text-white mb-4">Terms of Service</h1>
            <p className="text-gray-400">Last updated: March 20, 2026</p>
          </ScrollReveal>
        </div>
      </section>

      <section className="py-16 bg-white">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 prose prose-gray prose-headings:text-navy">
          <ScrollReveal>
            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing or using the Zonga platform, you agree to be bound by these Terms of Service. If you do not agree, do not use the platform. These terms apply to all users — artists, labels, listeners, and event organizers.
            </p>

            <h2>2. Account Registration</h2>
            <p>
              You must provide accurate information when creating an account. You are responsible for maintaining the security of your credentials and for all activity under your account. Accounts are managed through Clerk authentication.
            </p>

            <h2>3. Content Ownership</h2>
            <p>
              You retain full ownership of all content you upload to Zonga. By uploading, you grant Zonga a non-exclusive, worldwide license to distribute, stream, and display your content on the platform. You may remove your content at any time, which terminates this license (subject to existing contractual obligations).
            </p>

            <h2>4. Revenue & Payouts</h2>
            <p>
              Zonga operates on an 85/15 revenue model — creators retain 85% of net revenue generated by their content. Payouts are processed according to the schedule described in your account settings. The minimum payout threshold is $5 USD equivalent. Zonga reserves the right to withhold payouts pending fraud or compliance investigations.
            </p>

            <h2>5. Prohibited Conduct</h2>
            <p>You may not:</p>
            <ul>
              <li>Upload content you do not have the rights to distribute</li>
              <li>Engage in stream manipulation, bot activity, or artificial inflation of metrics</li>
              <li>Circumvent audio fingerprinting or integrity verification systems</li>
              <li>Use the platform for any unlawful purpose</li>
              <li>Attempt to gain unauthorized access to other accounts or platform systems</li>
            </ul>

            <h2>6. Moderation & Enforcement</h2>
            <p>
              Zonga reserves the right to remove content, suspend accounts, or take other action for violations of these terms. Our moderation process includes automated integrity signals and manual review. Disputes may be appealed through the platform&apos;s dispute resolution workflow.
            </p>

            <h2>7. Events & Ticketing</h2>
            <p>
              Event organizers are responsible for the accuracy of event details and fulfillment of ticket purchases. Zonga charges a 5% platform fee on ticket sales. Refund policies are set by event organizers and must comply with applicable consumer protection laws.
            </p>

            <h2>8. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Zonga is not liable for indirect, incidental, or consequential damages arising from your use of the platform. Our total liability is limited to the fees paid by you in the twelve months preceding the claim.
            </p>

            <h2>9. Termination</h2>
            <p>
              Either party may terminate this agreement at any time. Upon termination, your right to use the platform ceases. Outstanding payouts will be processed within 30 days, subject to any pending investigations.
            </p>

            <h2>10. Governing Law</h2>
            <p>
              These terms are governed by the laws of the Province of Quebec, Canada, without regard to conflict of law principles.
            </p>

            <h2>11. Contact</h2>
            <p>
              For questions about these terms, contact us at <a href="mailto:legal@zonga.app">legal@zonga.app</a>.
            </p>
          </ScrollReveal>
        </div>
      </section>
    </main>
  );
}
