# Generated by Django 5.2.17 on 2026-09-22 18:12
# Rebased against PLATFORM_SQL 0006 (documents runtime columns).
#
# Columns already created by
# apps/union-eyes/db/migrations-platform/0006_documents_runtime_columns.sql
# are recorded in Django state and re-applied only as ADD COLUMN IF NOT EXISTS
# with the platform types (file_size is bigint, not integer). The remaining
# business columns are still Django AddField — 0006 does not create them.
# Reverse of the overlap is a no-op so unapplying this migration cannot drop
# columns the platform lineage owns.

import django.contrib.postgres.fields
from django.db import migrations, models


PLATFORM_SQL_0006_OVERLAP = [
    "ALTER TABLE documents ADD COLUMN IF NOT EXISTS name text",
    "ALTER TABLE documents ADD COLUMN IF NOT EXISTS file_url text",
    "ALTER TABLE documents ADD COLUMN IF NOT EXISTS uploaded_by text",
    "ALTER TABLE documents ADD COLUMN IF NOT EXISTS deleted_at timestamptz",
    "ALTER TABLE documents ADD COLUMN IF NOT EXISTS metadata jsonb",
    "ALTER TABLE documents ADD COLUMN IF NOT EXISTS mime_type text",
    "ALTER TABLE documents ADD COLUMN IF NOT EXISTS file_size bigint",
    "ALTER TABLE documents ADD COLUMN IF NOT EXISTS description text",
]


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_pilotapplications_commercial_terms"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="documents",
                    name="deleted_at",
                    field=models.DateTimeField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="documents",
                    name="description",
                    field=models.TextField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="documents",
                    name="file_size",
                    field=models.BigIntegerField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="documents",
                    name="file_url",
                    field=models.TextField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="documents",
                    name="metadata",
                    field=models.JSONField(blank=True, default=dict, null=True),
                ),
                migrations.AddField(
                    model_name="documents",
                    name="mime_type",
                    field=models.TextField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="documents",
                    name="name",
                    field=models.TextField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="documents",
                    name="uploaded_by",
                    field=models.TextField(blank=True, null=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(sql=sql, reverse_sql=migrations.RunSQL.noop)
                for sql in PLATFORM_SQL_0006_OVERLAP
            ],
        ),
        migrations.AddField(
            model_name="documents",
            name="access_level",
            field=models.CharField(default="standard", max_length=50),
        ),
        migrations.AddField(
            model_name="documents",
            name="blob_container",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documents",
            name="blob_path",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documents",
            name="category",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documents",
            name="contains_legal_privilege",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="documents",
            name="contains_medical_sensitive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="documents",
            name="contains_pii",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="documents",
            name="content_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documents",
            name="content_type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documents",
            name="disciplinary_sensitive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="documents",
            name="document_type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documents",
            name="file_type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documents",
            name="filename",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documents",
            name="folder_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documents",
            name="is_confidential",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="documents",
            name="medical_sensitive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="documents",
            name="member_pii",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="documents",
            name="privacy_label",
            field=models.CharField(default="team_confidential", max_length=32),
        ),
        migrations.AddField(
            model_name="documents",
            name="sha256",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documents",
            name="size_bytes",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documents",
            name="status",
            field=models.CharField(default="active", max_length=20),
        ),
        migrations.AddField(
            model_name="documents",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="documents",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documents",
            name="uploaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
