"""
Admin configuration for compliance app.
Auto-generated by Nzila Code Generator — 2026-02-17
"""
from django.contrib import admin
from .models import (RiskScoreHistory, OrganizationRiskHistory, EvidenceBundles, EvidenceBundleComponents, EvidenceBundlePolicyMappings, EvidenceBundleTimeline)


@admin.register(RiskScoreHistory)
class RiskScoreHistoryAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    search_fields = ['department', 'location']
    ordering = ['-created_at']


@admin.register(OrganizationRiskHistory)
class OrganizationRiskHistoryAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    ordering = ['-created_at']


@admin.register(EvidenceBundles)
class EvidenceBundlesAdmin(admin.ModelAdmin):
    list_display = ['id', 'status', 'created_at']
    list_filter = ['status']
    search_fields = ['bundle_name', 'bundle_type', 'description', 'tags']
    ordering = ['-created_at']


@admin.register(EvidenceBundleComponents)
class EvidenceBundleComponentsAdmin(admin.ModelAdmin):
    list_display = ['id']
    search_fields = ['component_type', 'component_id', 'component_title']
    ordering = ['-created_at']


@admin.register(EvidenceBundlePolicyMappings)
class EvidenceBundlePolicyMappingsAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    list_filter = ['compliance_status']
    search_fields = ['tribunal_case_id', 'tribunal_case_title', 'related_training_id', 'related_training_title']
    ordering = ['-created_at']


@admin.register(EvidenceBundleTimeline)
class EvidenceBundleTimelineAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    search_fields = ['event_type', 'event_title', 'event_description', 'related_component_id']
    ordering = ['-created_at']
