"""
DRF serializers for compliance app.
Auto-generated by Nzila Code Generator — 2026-02-17
"""
from rest_framework import serializers
from .models import (RiskScoreHistory, OrganizationRiskHistory, EvidenceBundles, EvidenceBundleComponents, EvidenceBundlePolicyMappings, EvidenceBundleTimeline)


class RiskScoreHistorySerializer(serializers.ModelSerializer):
    class Meta:
        model = RiskScoreHistory
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class OrganizationRiskHistorySerializer(serializers.ModelSerializer):
    class Meta:
        model = OrganizationRiskHistory
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class EvidenceBundlesSerializer(serializers.ModelSerializer):
    class Meta:
        model = EvidenceBundles
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class EvidenceBundleComponentsSerializer(serializers.ModelSerializer):
    class Meta:
        model = EvidenceBundleComponents
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class EvidenceBundlePolicyMappingsSerializer(serializers.ModelSerializer):
    class Meta:
        model = EvidenceBundlePolicyMappings
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class EvidenceBundleTimelineSerializer(serializers.ModelSerializer):
    class Meta:
        model = EvidenceBundleTimeline
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']
