"""
Django models for core app.
Auto-generated by Nzila Code Generator — 2026-02-17

DO NOT EDIT manually unless you know what you're doing.
Re-run the generator to overwrite.
"""

import uuid

from django.contrib.postgres.fields import ArrayField
from django.contrib.postgres.search import SearchVectorField
from django.db import models

try:
    from pgvector.django import VectorField
except ImportError:
    VectorField = None  # pgvector not installed


class BaseModel(models.Model):
    """Abstract base with standard audit fields."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class OrganizationModel(BaseModel):
    """Abstract base for multi-organization models."""

    organization = models.ForeignKey(
        "auth_core.Organizations", on_delete=models.CASCADE, related_name="%(class)ss"
    )

    class Meta:
        abstract = True


class AlertRules(BaseModel):
    """Migrated from drizzle: alerting-automation-schema.ts"""

    organization = models.ForeignKey(
        "auth_core.Organizations",
        on_delete=models.CASCADE,
        related_name="alert_rules_organization_set",
    )

    class Meta:
        db_table = "alert_rules"
        verbose_name = "AlertRules"


class AlertConditions(BaseModel):
    """Migrated from drizzle: alerting-automation-schema.ts"""

    alert_rule = models.ForeignKey(
        "AlertRules",
        on_delete=models.CASCADE,
        related_name="alert_conditions_alert_rule_set",
    )

    class Meta:
        db_table = "alert_conditions"
        verbose_name = "AlertConditions"


class AlertActions(BaseModel):
    """Migrated from drizzle: alerting-automation-schema.ts"""

    alert_rule = models.ForeignKey(
        "AlertRules",
        on_delete=models.CASCADE,
        related_name="alert_actions_alert_rule_set",
    )

    class Meta:
        db_table = "alert_actions"
        verbose_name = "AlertActions"


class AlertEscalations(BaseModel):
    """Migrated from drizzle: alerting-automation-schema.ts"""

    organization = models.ForeignKey(
        "auth_core.Organizations",
        on_delete=models.CASCADE,
        related_name="alert_escalations_organization_set",
    )

    class Meta:
        db_table = "alert_escalations"
        verbose_name = "AlertEscalations"


class AlertExecutions(BaseModel):
    """Migrated from drizzle: alerting-automation-schema.ts"""

    alert_rule = models.ForeignKey(
        "AlertRules",
        on_delete=models.CASCADE,
        related_name="alert_executions_alert_rule_set",
    )

    class Meta:
        db_table = "alert_executions"
        verbose_name = "AlertExecutions"


class WorkflowDefinitions(BaseModel):
    """Migrated from drizzle: alerting-automation-schema.ts"""

    organization = models.ForeignKey(
        "auth_core.Organizations",
        on_delete=models.CASCADE,
        related_name="workflow_definitions_organization_set",
    )

    class Meta:
        db_table = "workflow_definitions"
        verbose_name = "WorkflowDefinitions"


class WorkflowExecutions(BaseModel):
    """Migrated from drizzle: alerting-automation-schema.ts"""

    workflow_definition = models.ForeignKey(
        "WorkflowDefinitions",
        on_delete=models.CASCADE,
        related_name="workflow_executions_workflow_definition_set",
    )

    class Meta:
        db_table = "workflow_executions"
        verbose_name = "WorkflowExecutions"


class AlertRecipients(BaseModel):
    """Migrated from drizzle: alerting-automation-schema.ts"""

    alert_rule = models.ForeignKey(
        "AlertRules",
        on_delete=models.CASCADE,
        related_name="alert_recipients_alert_rule_set",
    )

    class Meta:
        db_table = "alert_recipients"
        verbose_name = "AlertRecipients"


class AuditLogs(BaseModel):
    """Tamper-evident audit log with SHA-256 hash chain.

    Every write MUST compute content_hash before saving.
    Chain: SHA-256(action|resource_type|resource_id|user_id|correlation_id|details|previous_hash)
    A broken chain indicates tampering — NzilaOS audit invariant.
    """

    audit_id = models.UUIDField(default=uuid.uuid4, unique=True)
    organization = models.ForeignKey(
        "auth_core.Organizations",
        on_delete=models.CASCADE,
        related_name="audit_logs_organization_set",
        null=True,
        blank=True,
    )
    action = models.CharField(
        max_length=100,
        null=True,
        blank=True,
        help_text="Verb: create, update, delete, initiate, cancel ...",
    )
    resource_type = models.CharField(max_length=255, null=True, blank=True)
    resource_id = models.CharField(max_length=255, null=True, blank=True)
    user_id = models.CharField(max_length=255, null=True, blank=True)
    ip_address = models.GenericIPAddressField(null=True, blank=True)
    user_agent = models.TextField(null=True, blank=True)
    correlation_id = models.UUIDField(null=True, blank=True)
    details = models.JSONField(default=dict, null=True, blank=True)
    changes = models.JSONField(default=dict, null=True, blank=True)
    # — Hash chain —
    content_hash = models.CharField(max_length=64, null=True, blank=True)
    previous_hash = models.CharField(max_length=64, null=True, blank=True)

    class Meta:
        db_table = "audit_logs"
        verbose_name = "AuditLogs"
        indexes = [
            models.Index(
                fields=["organization_id", "created_at"],
                name="idx_ue_audit_logs_org_created",
            ),
            models.Index(
                fields=["correlation_id"], name="idx_ue_audit_logs_correlation"
            ),
        ]


class SecurityEvents(BaseModel):
    """Migrated from drizzle: audit-security-schema.ts"""

    event_id = models.UUIDField(default=uuid.uuid4, unique=True)
    organization = models.ForeignKey(
        "auth_core.Organizations",
        on_delete=models.CASCADE,
        related_name="security_events_organization_set",
        null=True,
        blank=True,
    )
    user_id = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        db_table = "security_events"
        verbose_name = "SecurityEvents"


class FailedLoginAttempts(BaseModel):
    """Migrated from drizzle: audit-security-schema.ts"""

    attempt_id = models.UUIDField(default=uuid.uuid4, unique=True)
    email = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        db_table = "failed_login_attempts"
        verbose_name = "FailedLoginAttempts"

    def __str__(self):
        return str(self.email)


class RateLimitEvents(BaseModel):
    """Migrated from drizzle: audit-security-schema.ts"""

    event_id = models.UUIDField(default=uuid.uuid4, unique=True)
    identifier = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        db_table = "rate_limit_events"
        verbose_name = "RateLimitEvents"


class AutomationRules(BaseModel):
    """Migrated from drizzle: automation-rules-schema.ts"""

    name = models.CharField(max_length=255, null=True, blank=True)
    organization_id = models.CharField(max_length=255)

    class Meta:
        db_table = "automation_rules"
        verbose_name = "AutomationRules"

    def __str__(self):
        return str(self.name)


class AutomationExecutionLog(BaseModel):
    """Migrated from drizzle: automation-rules-schema.ts"""

    rule = models.ForeignKey(
        "AutomationRules",
        on_delete=models.CASCADE,
        related_name="automation_execution_log_rule_set",
    )
    triggered_by = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        db_table = "automation_execution_log"
        verbose_name = "AutomationExecutionLog"


class AutomationSchedules(BaseModel):
    """Migrated from drizzle: automation-rules-schema.ts"""

    rule = models.ForeignKey(
        "AutomationRules",
        on_delete=models.CASCADE,
        related_name="automation_schedules_rule_set",
    )
    schedule_type = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        db_table = "automation_schedules"
        verbose_name = "AutomationSchedules"


class ExternalInvoices(BaseModel):
    """Migrated from drizzle: accounting.ts"""

    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = "external_invoices"
        verbose_name = "ExternalInvoices"


class ExternalPayments(BaseModel):
    """Migrated from drizzle: accounting.ts"""

    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = "external_payments"
        verbose_name = "ExternalPayments"


class ExternalCustomers(BaseModel):
    """Migrated from drizzle: accounting.ts"""

    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = "external_customers"
        verbose_name = "ExternalCustomers"


class ExternalAccounts(BaseModel):
    """Migrated from drizzle: accounting.ts"""

    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = "external_accounts"
        verbose_name = "ExternalAccounts"


class ExternalCommunicationChannels(BaseModel):
    """Migrated from drizzle: communication.ts"""

    org_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = "external_communication_channels"
        verbose_name = "ExternalCommunicationChannels"


class ExternalCommunicationMessages(BaseModel):
    """Migrated from drizzle: communication.ts"""

    org_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = "external_communication_messages"
        verbose_name = "ExternalCommunicationMessages"


class ExternalCommunicationUsers(BaseModel):
    """Migrated from drizzle: communication.ts"""

    org_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = "external_communication_users"
        verbose_name = "ExternalCommunicationUsers"


class ExternalCommunicationFiles(BaseModel):
    """Migrated from drizzle: communication.ts"""

    org_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = "external_communication_files"
        verbose_name = "ExternalCommunicationFiles"


class ExternalDocumentSites(BaseModel):
    """Migrated from drizzle: documents.ts"""

    org_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = "external_document_sites"
        verbose_name = "ExternalDocumentSites"


class ExternalDocumentLibraries(BaseModel):
    """Migrated from drizzle: documents.ts"""

    org_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = "external_document_libraries"
        verbose_name = "ExternalDocumentLibraries"


class ExternalDocumentFiles(BaseModel):
    """Migrated from drizzle: documents.ts"""

    org_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = "external_document_files"
        verbose_name = "ExternalDocumentFiles"


class ExternalDocumentPermissions(BaseModel):
    """Migrated from drizzle: documents.ts"""

    org_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = "external_document_permissions"
        verbose_name = "ExternalDocumentPermissions"


class ExternalEmployees(BaseModel):
    """Migrated from drizzle: hris.ts"""

    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = "external_employees"
        verbose_name = "ExternalEmployees"


class ExternalPositions(BaseModel):
    """Migrated from drizzle: hris.ts"""

    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = "external_positions"
        verbose_name = "ExternalPositions"


class ExternalDepartments(BaseModel):
    """Migrated from drizzle: hris.ts"""

    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = "external_departments"
        verbose_name = "ExternalDepartments"


class ExternalBenefitPlans(BaseModel):
    """Migrated from drizzle: insurance.ts"""

    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = "external_benefit_plans"
        verbose_name = "ExternalBenefitPlans"


class ExternalBenefitEnrollments(BaseModel):
    """Migrated from drizzle: insurance.ts"""

    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = "external_benefit_enrollments"
        verbose_name = "ExternalBenefitEnrollments"


class ExternalBenefitDependents(BaseModel):
    """Migrated from drizzle: insurance.ts"""

    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = "external_benefit_dependents"
        verbose_name = "ExternalBenefitDependents"


class ExternalBenefitCoverage(BaseModel):
    """Migrated from drizzle: insurance.ts"""

    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = "external_benefit_coverage"
        verbose_name = "ExternalBenefitCoverage"


class ExternalInsuranceClaims(BaseModel):
    """Migrated from drizzle: insurance.ts"""

    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = "external_insurance_claims"
        verbose_name = "ExternalInsuranceClaims"


class ExternalInsurancePolicies(BaseModel):
    """Migrated from drizzle: insurance.ts"""

    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = "external_insurance_policies"
        verbose_name = "ExternalInsurancePolicies"


class ExternalInsuranceBeneficiaries(BaseModel):
    """Migrated from drizzle: insurance.ts"""

    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = "external_insurance_beneficiaries"
        verbose_name = "ExternalInsuranceBeneficiaries"


class ExternalBenefitUtilization(BaseModel):
    """Migrated from drizzle: insurance.ts"""

    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = "external_benefit_utilization"
        verbose_name = "ExternalBenefitUtilization"


class ExternalLmsCourses(BaseModel):
    """Migrated from drizzle: lms.ts"""

    org_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = "external_lms_courses"
        verbose_name = "ExternalLmsCourses"


class ExternalLmsEnrollments(BaseModel):
    """Migrated from drizzle: lms.ts"""

    org_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = "external_lms_enrollments"
        verbose_name = "ExternalLmsEnrollments"


class ExternalLmsProgress(BaseModel):
    """Migrated from drizzle: lms.ts"""

    org_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = "external_lms_progress"
        verbose_name = "ExternalLmsProgress"


class ExternalLmsCompletions(BaseModel):
    """Migrated from drizzle: lms.ts"""

    org_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = "external_lms_completions"
        verbose_name = "ExternalLmsCompletions"


class ExternalLmsLearners(BaseModel):
    """Migrated from drizzle: lms.ts"""

    org_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = "external_lms_learners"
        verbose_name = "ExternalLmsLearners"


class IntegrationConfigs(BaseModel):
    """Migrated from drizzle: integrations.ts"""

    organization = models.ForeignKey(
        "auth_core.Organizations",
        on_delete=models.CASCADE,
        related_name="integration_configs_organization_set",
    )

    class Meta:
        db_table = "integration_configs"
        verbose_name = "IntegrationConfigs"


class IntegrationSyncLog(BaseModel):
    """Migrated from drizzle: integrations.ts"""

    organization = models.ForeignKey(
        "auth_core.Organizations",
        on_delete=models.CASCADE,
        related_name="integration_sync_log_organization_set",
    )

    class Meta:
        db_table = "integration_sync_log"
        verbose_name = "IntegrationSyncLog"


class WebhookEvents(BaseModel):
    """Migrated from drizzle: integrations.ts"""

    organization = models.ForeignKey(
        "auth_core.Organizations",
        on_delete=models.CASCADE,
        related_name="webhook_events_organization_set",
    )

    class Meta:
        db_table = "webhook_events"
        verbose_name = "WebhookEvents"


class IntegrationSyncSchedules(BaseModel):
    """Migrated from drizzle: integrations.ts"""

    organization = models.ForeignKey(
        "auth_core.Organizations",
        on_delete=models.CASCADE,
        related_name="integration_sync_schedules_organization_set",
    )

    class Meta:
        db_table = "integration_sync_schedules"
        verbose_name = "IntegrationSyncSchedules"


class IntegrationApiKeys(BaseModel):
    """Migrated from drizzle: integrations.ts"""

    organization = models.ForeignKey(
        "auth_core.Organizations",
        on_delete=models.CASCADE,
        related_name="integration_api_keys_organization_set",
        null=True,
        blank=True,
    )

    class Meta:
        db_table = "integration_api_keys"
        verbose_name = "IntegrationApiKeys"


class IntegrationWebhooks(BaseModel):
    """Migrated from drizzle: integrations.ts"""

    organization = models.ForeignKey(
        "auth_core.Organizations",
        on_delete=models.CASCADE,
        related_name="integration_webhooks_organization_set",
        null=True,
        blank=True,
    )

    class Meta:
        db_table = "integration_webhooks"
        verbose_name = "IntegrationWebhooks"


class WebhookDeliveries(BaseModel):
    """Migrated from drizzle: integrations.ts"""

    webhook = models.ForeignKey(
        "IntegrationWebhooks",
        on_delete=models.CASCADE,
        related_name="webhook_deliveries_webhook_set",
    )

    class Meta:
        db_table = "webhook_deliveries"
        verbose_name = "WebhookDeliveries"


class SupportTickets(BaseModel):
    """Migrated from drizzle: support.ts"""

    ticket_number = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        db_table = "support_tickets"
        verbose_name = "SupportTickets"


class TicketComments(BaseModel):
    """Migrated from drizzle: support.ts"""

    ticket = models.ForeignKey(
        "SupportTickets",
        on_delete=models.CASCADE,
        related_name="ticket_comments_ticket_set",
    )

    class Meta:
        db_table = "ticket_comments"
        verbose_name = "TicketComments"


class TicketHistory(BaseModel):
    """Migrated from drizzle: support.ts"""

    ticket = models.ForeignKey(
        "SupportTickets",
        on_delete=models.CASCADE,
        related_name="ticket_history_ticket_set",
    )

    class Meta:
        db_table = "ticket_history"
        verbose_name = "TicketHistory"


class SlaPolicies(BaseModel):
    """Migrated from drizzle: support.ts"""

    name = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        db_table = "sla_policies"
        verbose_name = "SlaPolicies"

    def __str__(self):
        return str(self.name)


class KnowledgeBaseArticles(BaseModel):
    """Migrated from drizzle: support.ts"""

    title = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        db_table = "knowledge_base_articles"
        verbose_name = "KnowledgeBaseArticles"

    def __str__(self):
        return str(self.title)


class WebhookSubscriptions(BaseModel):
    """Migrated from drizzle: integration-schema.ts"""

    organization = models.ForeignKey(
        "auth_core.Organizations",
        on_delete=models.CASCADE,
        related_name="webhook_subscriptions_organization_set",
    )

    class Meta:
        db_table = "webhook_subscriptions"
        verbose_name = "WebhookSubscriptions"


class ApiIntegrations(BaseModel):
    """Migrated from drizzle: integration-schema.ts"""

    organization = models.ForeignKey(
        "auth_core.Organizations",
        on_delete=models.CASCADE,
        related_name="api_integrations_organization_set",
    )

    class Meta:
        db_table = "api_integrations"
        verbose_name = "ApiIntegrations"


class IntegrationSyncLogs(BaseModel):
    """Migrated from drizzle: integration-schema.ts"""

    integration = models.ForeignKey(
        "ApiIntegrations",
        on_delete=models.CASCADE,
        related_name="integration_sync_logs_integration_set",
    )

    class Meta:
        db_table = "integration_sync_logs"
        verbose_name = "IntegrationSyncLogs"


class ApiAccessTokens(BaseModel):
    """Migrated from drizzle: integration-schema.ts"""

    organization = models.ForeignKey(
        "auth_core.Organizations",
        on_delete=models.CASCADE,
        related_name="api_access_tokens_organization_set",
    )

    class Meta:
        db_table = "api_access_tokens"
        verbose_name = "ApiAccessTokens"
