# Generated by Django 6.0.3 on 2026-03-29 23:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_name', models.TextField()),
                ('jurisdiction', models.CharField(blank=True, max_length=255, null=True)),
                ('incorporation_number', models.TextField(blank=True, null=True)),
                ('registered_office_address', models.JSONField(blank=True, null=True)),
                ('fiscal_year_end', models.CharField(blank=True, max_length=10, null=True)),
                ('policy_config', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('archived', 'Archived')], default='active', max_length=20)),
                ('clerk_org_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'orgs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrgMembers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org_id', models.UUIDField(db_column='org_id')),
                ('clerk_user_id', models.TextField(db_column='clerk_user_id')),
                ('role', models.CharField(choices=[('org_admin', 'Admin'), ('org_secretary', 'Secretary'), ('org_viewer', 'Viewer')], default='org_viewer', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('removed', 'Removed')], default='active', max_length=20)),
            ],
            options={
                'verbose_name': 'Org Member',
                'verbose_name_plural': 'Org Members',
                'db_table': 'org_members',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.TextField(help_text='Clerk user ID')),
                ('role', models.CharField(choices=[('org_admin', 'Admin'), ('org_secretary', 'Secretary'), ('org_viewer', 'Viewer')], default='org_viewer', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('is_primary', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='auth_core.organizations')),
            ],
            options={
                'verbose_name': 'Organization Member',
                'verbose_name_plural': 'Organization Members',
                'db_table': 'zonga_organization_members',
                'unique_together': {('organization', 'user_id')},
            },
        ),
    ]
