import { defineConfig } from 'vitest/config'

export default defineConfig({
  test: {
    projects: [
      // Apps
      'apps/abr',
      'apps/cfo',
      'apps/console',
      'apps/orchestrator-api',
      'apps/partners',
      'apps/union-eyes',
      'apps/shop-quoter',
      'apps/web',
      'apps/nacp-exams',
      'apps/zonga',
      // Packages
      'packages/ai-core',
      'packages/ai-sdk',
      'packages/blob',
      'packages/db',
      'packages/ml-core',
      'packages/ml-sdk',
      'packages/commerce-core',
      'packages/pricing-engine',
      'packages/commerce-state',
      'packages/commerce-audit',
      'packages/commerce-db',
      'packages/commerce-events',
      'packages/commerce-evidence',
      'packages/commerce-governance',
      'packages/commerce-services',
      'packages/commerce-integration-tests',
      'packages/commerce-observability',
      'packages/nacp-core',
      'packages/zonga-core',
      'packages/shop-quoter',
      'packages/os-core',
      'packages/payments-stripe',
      'packages/platform-export',
      'packages/platform-metrics',
      'packages/platform-performance',
      'packages/platform-isolation',
      'packages/platform-proof',
      'packages/qbo',
      'packages/fx',
      'packages/tax',
      'packages/tools-runtime',
      'packages/ui',
      // Integration platform
      'packages/integrations-core',
      'packages/integrations-db',
      'packages/integrations-runtime',
      'packages/comms-email',
      'packages/comms-sms',
      'packages/comms-push',
      'packages/chatops-slack',
      'packages/chatops-teams',
      'packages/crm-hubspot',
      'packages/webhooks',
      // Contract tests (architectural invariants)
      'tooling/contract-tests',
    ],
  },
})
