#!/usr/bin/env tsx
/**
 * dr:drill:report — Generate a markdown evidence report from the latest
 *   restore-drill JSON artifact.
 *
 * Reads the most recent `reports/db/restore-drill-YYYY-MM.json` produced by
 * `pnpm db:restore-drill` and writes a human-readable markdown report to
 * `reports/dr/restore-drill-YYYY-MM-DD.md` and a summary JSON to
 * `reports/dr/restore-drill-YYYY-MM-DD.json`.
 *
 * Usage:
 *   pnpm dr:drill:report
 *   pnpm dr:drill:report --input reports/db/restore-drill-2026-04.json
 *
 * Output:
 *   reports/dr/restore-drill-YYYY-MM-DD.md
 *   reports/dr/restore-drill-YYYY-MM-DD.json
 *   Prints summary to stdout.
 */

import * as fs from 'node:fs'
import * as path from 'node:path'

const ROOT = path.resolve(__dirname, '..', '..')
const DB_REPORTS_DIR = path.join(ROOT, 'reports', 'db')
const DR_REPORTS_DIR = path.join(ROOT, 'reports', 'dr')

// ── Types ─────────────────────────────────────────────────────────────────────

interface DrillEvidence {
  drillId: string
  timestamp: string
  mode: string
  environment: string
  backupSources: Array<{ type: string; location: string; exists: boolean; lastModified?: string; sizeMB?: number }>
  checks: Array<{ check: string; status: string; message: string; durationMs?: number }>
  timing: { totalDurationMs: number; restoreDurationMs: number | null; healthCheckDurationMs: number }
  overallStatus: string
  rtoTarget: string
  rtoActual: string | null
  rpoTarget: string
  operator: string
  migrationCount: number
  schemaVersion: number
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function parseArg(name: string): string | undefined {
  const idx = process.argv.indexOf(name)
  if (idx >= 0 && process.argv[idx + 1]) return process.argv[idx + 1]
  return undefined
}

function latestDrillFile(): string | null {
  if (!fs.existsSync(DB_REPORTS_DIR)) return null
  const files = fs.readdirSync(DB_REPORTS_DIR)
    .filter((f) => f.startsWith('restore-drill-') && f.endsWith('.json'))
    .sort()
    .reverse()
  return files[0] ? path.join(DB_REPORTS_DIR, files[0]) : null
}

function statusIcon(s: string): string {
  if (s === 'pass') return '✅'
  if (s === 'fail') return '❌'
  return '⏭️'
}

function toDateString(iso: string): string {
  return iso.slice(0, 10)
}

// ── Main ──────────────────────────────────────────────────────────────────────

function main(): void {
  const inputPath = parseArg('--input') ?? latestDrillFile()

  if (!inputPath || !fs.existsSync(inputPath)) {
    process.stderr.write('No restore-drill JSON found. Run pnpm db:restore-drill first.\n')
    process.exit(1)
  }

  const raw = JSON.parse(fs.readFileSync(inputPath, 'utf-8')) as DrillEvidence
  const dateStr = toDateString(raw.timestamp)
  const passCount = raw.checks.filter((c) => c.status === 'pass').length
  const failCount = raw.checks.filter((c) => c.status === 'fail').length
  const skipCount = raw.checks.filter((c) => c.status === 'skip').length

  // ── Markdown report ──────────────────────────────────────────────────────

  const md = `# Union Eyes — DR Restore Drill Evidence Report

> **Drill ID:** \`${raw.drillId}\`  
> **Date:** ${dateStr}  
> **Mode:** ${raw.mode}  
> **Environment:** ${raw.environment}  
> **Operator:** ${raw.operator}  
> **Generated by:** \`pnpm dr:drill:report\`

---

## 1. Summary

| Check | Result |
|-------|--------|
| Overall status | **${raw.overallStatus.toUpperCase()}** |
| Passed | ${passCount} |
| Failed | ${failCount} |
| Skipped | ${skipCount} |
| RTO target | ${raw.rtoTarget} |
| RTO actual | ${raw.rtoActual ?? '**Not measured** — pending live staging execution'} |
| RPO target | ${raw.rpoTarget} |
| Migration files | ${raw.migrationCount} |
| Drill duration | ${raw.timing.totalDurationMs}ms |
| Readiness state | ${raw.rtoActual ? 'Live RTO measured' : 'Ready for live drill'} |

---

## 2. Backup Sources

| Type | Location | Available |
|------|---------|---------|
${raw.backupSources.map((b) => `| ${b.type} | ${b.location} | ${b.exists ? '✅' : '❌'} |`).join('\n')}

---

## 3. Check Results

| Check | Status | Message |
|-------|--------|---------|
${raw.checks.map((c) => `| \`${c.check}\` | ${statusIcon(c.status)} ${c.status} | ${c.message}${c.durationMs != null ? ` (${c.durationMs}ms)` : ''} |`).join('\n')}

---

## 4. Timing

| Metric | Value |
|--------|-------|
| Total drill duration | ${raw.timing.totalDurationMs}ms |
| Restore duration | ${raw.timing.restoreDurationMs != null ? `${raw.timing.restoreDurationMs}ms` : 'Not executed (requires --execute mode)'} |
| Health check duration | ${raw.timing.healthCheckDurationMs}ms |

---

## 5. Next Steps

${raw.rtoActual == null ? `- **Execute live staging restore** to measure actual RTO: \`pnpm db:restore-drill:execute\`\n- Record measured timing in next drill report.` : `- RTO measured: ${raw.rtoActual}. Update maturity.json with actual value.`}

---

## 6. Sign-Off

| Role | Name | Date | Status |
|------|------|------|--------|
| SRE Operator | — | — | ⬜ Pending |
| Platform Engineering | — | — | ⬜ Pending |
| CISO | — | — | ⬜ Pending |
| CTO | — | — | ⬜ Pending |

---

_Report generated from: \`${path.relative(ROOT, inputPath)}\`_
`

  // ── Summary JSON ────────────────────────────────────────────────────────

  const summary = {
    reportVersion: '1.0',
    reportId: `ue-dr-${dateStr}`,
    drillId: raw.drillId,
    timestamp: raw.timestamp,
    generatedAt: new Date().toISOString(),
    app: 'union-eyes',
    mode: raw.mode,
    environment: raw.environment,
    operator: raw.operator,
    rtoTarget: raw.rtoTarget,
    rtoActual: raw.rtoActual,
    rpoTarget: raw.rpoTarget,
    overallStatus: raw.overallStatus,
    passCount,
    failCount,
    skipCount,
    migrationCount: raw.migrationCount,
    readinessState: raw.rtoActual ? 'live-rto-measured' : 'ready-for-live-drill',
    evidenceArtifacts: [
      path.relative(ROOT, inputPath),
      `reports/dr/restore-drill-${dateStr}.md`,
      `reports/dr/restore-drill-${dateStr}.json`,
    ],
    schemaVersion: 1,
  }

  // ── Write outputs ────────────────────────────────────────────────────────

  fs.mkdirSync(DR_REPORTS_DIR, { recursive: true })

  const mdPath = path.join(DR_REPORTS_DIR, `restore-drill-${dateStr}.md`)
  const jsonPath = path.join(DR_REPORTS_DIR, `restore-drill-${dateStr}.json`)

  fs.writeFileSync(mdPath, md, 'utf-8')
  fs.writeFileSync(jsonPath, JSON.stringify(summary, null, 2), 'utf-8')

  // ── Stdout summary ───────────────────────────────────────────────────────

  process.stdout.write(`\n── DR Drill Report ─────────────────────────────────\n`)
  process.stdout.write(`  Drill ID:   ${raw.drillId}\n`)
  process.stdout.write(`  Date:       ${dateStr}\n`)
  process.stdout.write(`  Status:     ${raw.overallStatus}\n`)
  process.stdout.write(`  RTO actual: ${raw.rtoActual ?? 'pending live execution'}\n`)
  process.stdout.write(`\n  Reports written:\n`)
  process.stdout.write(`    ${path.relative(ROOT, mdPath)}\n`)
  process.stdout.write(`    ${path.relative(ROOT, jsonPath)}\n\n`)
}

main()
