"""
DRF viewsets for bargaining app.
Auto-generated by Nzila Code Generator — 2026-02-17
"""
from rest_framework import viewsets, permissions, filters
from django_filters.rest_framework import DjangoFilterBackend
from .models import (ArbitrationPrecedents, PrecedentTags, PrecedentCitations, Negotiations, BargainingProposals, TentativeAgreements, NegotiationSessions, BargainingTeamMembers, CbaClauses, ClauseComparisons, WageProgressions, BenefitComparisons, ArbitrationDecisions, ArbitratorProfiles, BargainingNotes, CbaFootnotes, CollectiveAgreements, CbaVersionHistory, CbaContacts, SharedClauseLibrary, ClauseLibraryTags, ClauseComparisonsHistory)
from .serializers import (ArbitrationPrecedentsSerializer, PrecedentTagsSerializer, PrecedentCitationsSerializer, NegotiationsSerializer, BargainingProposalsSerializer, TentativeAgreementsSerializer, NegotiationSessionsSerializer, BargainingTeamMembersSerializer, CbaClausesSerializer, ClauseComparisonsSerializer, WageProgressionsSerializer, BenefitComparisonsSerializer, ArbitrationDecisionsSerializer, ArbitratorProfilesSerializer, BargainingNotesSerializer, CbaFootnotesSerializer, CollectiveAgreementsSerializer, CbaVersionHistorySerializer, CbaContactsSerializer, SharedClauseLibrarySerializer, ClauseLibraryTagsSerializer, ClauseComparisonsHistorySerializer)


class DenyAllPermission(permissions.BasePermission):
    """Round 40: no legitimate Django consumer exists for contained generated ViewSets."""

    def has_permission(self, request, view):
        return False

    def has_object_permission(self, request, view, obj):
        return False


class ArbitrationPrecedentsViewSet(viewsets.ModelViewSet):
    """API endpoint for ArbitrationPrecedents operations."""
    queryset = ArbitrationPrecedents.objects.all()
    serializer_class = ArbitrationPrecedentsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class PrecedentTagsViewSet(viewsets.ModelViewSet):
    """API endpoint for PrecedentTags operations."""
    queryset = PrecedentTags.objects.all()
    serializer_class = PrecedentTagsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class PrecedentCitationsViewSet(viewsets.ModelViewSet):
    """API endpoint for PrecedentCitations operations."""
    queryset = PrecedentCitations.objects.all()
    serializer_class = PrecedentCitationsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class NegotiationsViewSet(viewsets.ModelViewSet):
    """API endpoint for Negotiations operations."""
    queryset = Negotiations.objects.all()
    serializer_class = NegotiationsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['expiring_cba_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class BargainingProposalsViewSet(viewsets.ModelViewSet):
    """API endpoint for BargainingProposals operations."""
    queryset = BargainingProposals.objects.all()
    serializer_class = BargainingProposalsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['negotiation_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class TentativeAgreementsViewSet(viewsets.ModelViewSet):
    """API endpoint for TentativeAgreements operations."""
    queryset = TentativeAgreements.objects.all()
    serializer_class = TentativeAgreementsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['negotiation_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class NegotiationSessionsViewSet(viewsets.ModelViewSet):
    """API endpoint for NegotiationSessions operations."""
    queryset = NegotiationSessions.objects.all()
    serializer_class = NegotiationSessionsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['negotiation_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class BargainingTeamMembersViewSet(viewsets.ModelViewSet):
    """API endpoint for BargainingTeamMembers operations."""
    queryset = BargainingTeamMembers.objects.all()
    serializer_class = BargainingTeamMembersSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['negotiation_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class CbaClausesViewSet(viewsets.ModelViewSet):
    """API endpoint for CbaClauses operations."""
    queryset = CbaClauses.objects.all()
    serializer_class = CbaClausesSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['cba_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class ClauseComparisonsViewSet(viewsets.ModelViewSet):
    """API endpoint for ClauseComparisons operations."""
    queryset = ClauseComparisons.objects.all()
    serializer_class = ClauseComparisonsSerializer
    permission_classes = [DenyAllPermission]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['comparison_name']
    search_fields = ['comparison_name']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class WageProgressionsViewSet(viewsets.ModelViewSet):
    """API endpoint for WageProgressions operations."""
    queryset = WageProgressions.objects.all()
    serializer_class = WageProgressionsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['cba_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class BenefitComparisonsViewSet(viewsets.ModelViewSet):
    """API endpoint for BenefitComparisons operations."""
    queryset = BenefitComparisons.objects.all()
    serializer_class = BenefitComparisonsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['cba_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class ArbitrationDecisionsViewSet(viewsets.ModelViewSet):
    """API endpoint for ArbitrationDecisions operations."""
    queryset = ArbitrationDecisions.objects.all()
    serializer_class = ArbitrationDecisionsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['case_number']
    search_fields = ['case_number']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class ArbitratorProfilesViewSet(viewsets.ModelViewSet):
    """API endpoint for ArbitratorProfiles operations."""
    queryset = ArbitratorProfiles.objects.all()
    serializer_class = ArbitratorProfilesSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['name']
    search_fields = ['name']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class BargainingNotesViewSet(viewsets.ModelViewSet):
    """API endpoint for BargainingNotes operations."""
    queryset = BargainingNotes.objects.all()
    serializer_class = BargainingNotesSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['cba_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class CbaFootnotesViewSet(viewsets.ModelViewSet):
    """API endpoint for CbaFootnotes operations."""
    queryset = CbaFootnotes.objects.all()
    serializer_class = CbaFootnotesSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['source_clause_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class CollectiveAgreementsViewSet(viewsets.ModelViewSet):
    """API endpoint for CollectiveAgreements operations."""
    queryset = CollectiveAgreements.objects.all()
    serializer_class = CollectiveAgreementsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['cba_number']
    search_fields = ['cba_number']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class CbaVersionHistoryViewSet(viewsets.ModelViewSet):
    """API endpoint for CbaVersionHistory operations."""
    queryset = CbaVersionHistory.objects.all()
    serializer_class = CbaVersionHistorySerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['cba_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class CbaContactsViewSet(viewsets.ModelViewSet):
    """API endpoint for CbaContacts operations."""
    queryset = CbaContacts.objects.all()
    serializer_class = CbaContactsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['cba_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class SharedClauseLibraryViewSet(viewsets.ModelViewSet):
    """API endpoint for SharedClauseLibrary operations."""
    queryset = SharedClauseLibrary.objects.all()
    serializer_class = SharedClauseLibrarySerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class ClauseLibraryTagsViewSet(viewsets.ModelViewSet):
    """API endpoint for ClauseLibraryTags operations."""
    queryset = ClauseLibraryTags.objects.all()
    serializer_class = ClauseLibraryTagsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class ClauseComparisonsHistoryViewSet(viewsets.ModelViewSet):
    """API endpoint for ClauseComparisonsHistory operations."""
    queryset = ClauseComparisonsHistory.objects.all()
    serializer_class = ClauseComparisonsHistorySerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['user_id']
    search_fields = ['user_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']
