import PDFDocument from 'pdfkit/js/pdfkit.js'

export interface ProposalPdfInput {
  proposalId: string
  title: string
  customerName: string
  summary: string
  total: number
  depositRequired: number
  locale: 'en-CA' | 'fr-CA'
}

export async function renderProposalPdf(input: ProposalPdfInput): Promise<Buffer> {
  const doc = new PDFDocument({ margin: 48 })
  const chunks: Buffer[] = []

  return await new Promise<Buffer>((resolve, reject) => {
    doc.on('data', (chunk) => chunks.push(Buffer.from(chunk)))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', (error) => reject(error))

    doc.fontSize(20).text(input.locale === 'fr-CA' ? 'Proposition commerciale' : 'Commercial Proposal')
    doc.moveDown(0.5)
    doc.fontSize(11).fillColor('#5b6370').text(`ID: ${input.proposalId}`)
    doc.text(`${input.locale === 'fr-CA' ? 'Client' : 'Customer'}: ${input.customerName}`)
    doc.text(`${input.locale === 'fr-CA' ? 'Titre' : 'Title'}: ${input.title}`)
    doc.text(`${input.locale === 'fr-CA' ? 'Genere le' : 'Generated'}: ${new Date().toISOString()}`)

    doc.moveDown(1)
    doc.fillColor('#111111').fontSize(12).text(input.summary)

    doc.moveDown(1)
    doc.fontSize(14).text(input.locale === 'fr-CA' ? 'Conditions financieres' : 'Financial terms')
    doc.fontSize(11)
    doc.text(`${input.locale === 'fr-CA' ? 'Total' : 'Total'}: ${input.total.toFixed(2)} CAD`)
    doc.text(`${input.locale === 'fr-CA' ? 'Depot requis' : 'Deposit required'}: ${input.depositRequired.toFixed(2)} CAD`)

    doc.moveDown(1)
    doc.fillColor('#5b6370').fontSize(10).text(
      input.locale === 'fr-CA'
        ? 'Ce document est genere par Maestria et peut etre partage avec le client final.'
        : 'This document is generated by Maestria and is ready to be shared with the final client.',
    )

    doc.end()
  })
}
