import { auth } from '@nzila/platform-auth/entra/server'
import { redirect } from 'next/navigation'
import { UserButton } from '@nzila/platform-auth/entra/client'
import Link from 'next/link'

export const dynamic = 'force-dynamic'

import { ArrowTopRightOnSquareIcon } from '@heroicons/react/24/outline'
import { ExecutiveModeWrapper } from './executive-mode'
import { SidebarNav, type NavGroup } from '@/components/sidebar-nav'
import { CommandSectionGuide } from '@/components/command-section-guide'

const navGroups: NavGroup[] = [
  // ── Zone 1: TODAY — CEO Daily Pulse ────────────────────────────────────────
  {
    label: 'Command',
    defaultOpen: true,
    items: [
      { name: 'CEO One-Screen', href: '/ceo', icon: 'EyeIcon', badge: 'board', description: 'Compressed boardroom summary for founder, partner, or investor conversations.' },
      { name: 'Intelligence', href: '/intelligence', icon: 'SparklesIcon', badge: 'deep', description: 'Cross-domain research surface for funding, deals, partners, products, and strategic signals.' },
      { name: 'Today', href: '/today', icon: 'HomeIcon', badge: 'daily', description: 'Best first stop every morning for immediate cash, pipeline, pilot, and approval signals.' },
      { name: 'Autopilot', href: '/autopilot', icon: 'BoltIcon', badge: 'assist', description: 'High-confidence actions generated by the system that still require human approval.' },
      { name: 'Briefing', href: '/briefing', icon: 'ClipboardDocumentCheckIcon', badge: 'weekly', description: 'Decision-oriented memo for leadership review and weekly founder planning.' },
      { name: 'Focus', href: '/focus', icon: 'ClockIcon', badge: 'weekly', description: 'Founder time allocation and capacity page for deciding what gets real attention this week.' },
      { name: 'Portfolio', href: '/portfolio', icon: 'BuildingOffice2Icon', badge: 'alloc', description: 'Portfolio allocation view showing which ventures deserve build, sell, hold, or maintenance effort.' },
      { name: 'Command Center', href: '/command-center', icon: 'CommandLineIcon', badge: 'ops', description: 'Operating snapshot across clients, renewals, support load, team pressure, and founder priorities.' },
      { name: 'Weekly Review', href: '/weekly-review', icon: 'CalendarDaysIcon', badge: 'cadence', description: 'Same operating review across daily, weekly, and monthly rhythms without changing context.' },
    ],
  },
  // ── Zone 2: REVENUE — Sales Command Center ─────────────────────────────────
  {
    label: 'Revenue',
    defaultOpen: true,
    items: [
      { name: 'Pipeline', href: '/revenue', icon: 'ArrowTrendingUpIcon', description: 'Sales command center showing quotes, active pilots, prospect pipeline, and revenue playbooks by account.' },
      { name: 'UE Revenue Cockpit', href: '/ue-revenue-cockpit', icon: 'RocketLaunchIcon', description: 'Union Eyes revenue agent surface tracking commerce opportunities, growth signals, and deal velocity.' },
      { name: 'FAIRCASE Funnel', href: '/revenue/faircase', icon: 'ChartBarIcon', description: 'FAIRCASE-specific funnel view tracking leads through meetings, demos, proposals, pilots to close.' },
      { name: 'Pilot Export', href: '/pilot/export', icon: 'DocumentArrowDownIcon', description: 'Export active pilots and revenue events for cross-venture analysis and reporting.' },
    ],
  },
  // ── Zone 3: CAPITAL — Cash · Burn · Runway ─────────────────────────────────
  {
    label: 'Capital',
    defaultOpen: true,
    items: [
      { name: 'Burn & Runway', href: '/capital', icon: 'BanknotesIcon', description: 'Cash position, burn rate, and runway visibility across all ventures with path-to-sustainability tracking.' },
      { name: 'Runway', href: '/runway', icon: 'ArrowTrendingUpIcon', description: 'Detailed runway analysis by venture showing months of operating capital and funding milestones.' },
      { name: 'Forecast', href: '/forecast', icon: 'ChartBarIcon', description: 'Financial projections and forecasting model for portfolio-wide cash planning.' },
      { name: 'Cost Dashboard', href: '/cost', icon: 'CurrencyDollarIcon', description: 'Cloud and infrastructure cost visibility with optimization recommendations and budget alerts.' },
      { name: 'Economics', href: '/platform-economics', icon: 'ChartBarIcon', description: 'Shared platform economics and cost allocation across ventures.' },
      { name: 'Finance Ops', href: '/business/finance', icon: 'DocumentTextIcon', description: 'Finance operations, invoicing, and transaction records.' },
    ],
  },
  // ── Zone 4: EXECUTION — Initiatives · Owners · Blockers ───────────────────
  {
    label: 'Execution',
    items: [
      { name: 'Initiatives', href: '/execution', icon: 'BoltIcon', description: 'Active strategic initiatives with owners, deadlines, and execution progress tracking.' },
      { name: 'Accountability', href: '/accountability', icon: 'CheckCircleIcon', description: 'OKR and accountability tracking with status updates and blocker resolution.' },
      { name: 'Operator Mode', href: '/operator', icon: 'WrenchScrewdriverIcon', description: 'Tactical operations control and real-time coordination for the operating team.' },
      { name: 'Decision Scoreback', href: '/decision-scoreback', icon: 'ChartBarSquareIcon', description: 'Track decisions made, outcomes achieved, and lessons learned from leadership decisions.' },
      { name: 'Approvals', href: '/business/approvals', icon: 'ClipboardDocumentCheckIcon', description: 'Approval workflows and signature tracking for business decisions and commitments.' },
      { name: 'Queues', href: '/business/queues', icon: 'CircleStackIcon', description: 'Work queue management and task prioritization across the organization.' },
      { name: 'Signatures', href: '/business/signatures', icon: 'FingerPrintIcon', description: 'Digital signature collection and document signing workflow.' },
    ],
  },
  // ── Zone 5: RISK — Business · Platform · Financial Threats ────────────────
  {
    label: 'Risk',
    items: [
      { name: 'Risk Register', href: '/risk', icon: 'ExclamationTriangleIcon', description: 'Central registry of business, technical, and financial risks with mitigation plans.' },
      { name: 'Ops Score', href: '/ops-score', icon: 'ShieldExclamationIcon', description: 'Real-time operations health score showing system reliability and incident risk.' },
      { name: 'Audit Insights', href: '/audit-insights', icon: 'EyeIcon', description: 'Audit findings and compliance gaps with remediation tracking.' },
      { name: 'Trend Detection', href: '/trend-detection', icon: 'ChartBarSquareIcon', description: 'AI-powered anomaly and trend detection across portfolio metrics.' },
    ],
  },
  // ── Zone 6: GOVERNANCE — GRC · Evidence · Corporate Gov ───────────────────
  {
    label: 'Governance',
    items: [
      { name: 'Governance', href: '/governance', icon: 'ShieldCheckIcon', description: 'Governance framework, policies, and compliance documentation.' },
      { name: 'Board Pack', href: '/board', icon: 'DocumentTextIcon', description: 'Monthly board package with metrics, decisions, and strategic updates.' },
      { name: 'Corporate Gov', href: '/business/governance', icon: 'EyeIcon', description: 'Corporate governance structure and board meeting management.' },
      { name: 'Equity & Cap Table', href: '/business/equity', icon: 'DocumentDuplicateIcon', description: 'Equity tracking, cap table, and share distribution across ventures.' },
      { name: 'Evidence Packs', href: '/evidence-packs', icon: 'DocumentArrowDownIcon', description: 'Compliance evidence and audit documentation for regulatory requirements.' },
      { name: 'Proof Center', href: '/proof-center', icon: 'FingerPrintIcon', description: 'Cryptographic proof and attestation center for audit trail.' },
      { name: 'Compliance', href: '/compliance-snapshots', icon: 'ClipboardDocumentCheckIcon', description: 'Compliance status snapshots and regulatory requirement tracking.' },
    ],
  },
  // ── Internal Tools (collapsed by default) ─────────────────────────────────
  {
    label: 'Ops Toolkit',
    items: [
      { name: 'System Health', href: '/system-health', icon: 'ServerIcon', description: 'Platform infrastructure and service health dashboard.' },
      { name: 'Ops', href: '/ops', icon: 'ShieldExclamationIcon', description: 'Operations control center and incident management.' },
      { name: 'Performance', href: '/performance', icon: 'BoltIcon', description: 'Application performance monitoring and optimization insights.' },
      { name: 'Integrations', href: '/integrations', icon: 'PuzzlePieceIcon', description: 'Third-party integrations and API management.' },
      { name: 'Control Plane', href: '/integrations-control-plane', icon: 'WrenchScrewdriverIcon', description: 'Advanced integration control and routing configuration.' },
    ],
  },
  // ── Service Operations Layer ───────────────────────────────────────────────
  {
    label: 'Service Operations',
    items: [
      { name: 'Ops Dashboard', href: '/itsm/dashboard', icon: 'ChartBarSquareIcon', description: 'Service operations metrics and KPI dashboard.' },
      { name: 'Support Desk', href: '/itsm/queue', icon: 'CircleStackIcon', description: 'Ticket queue and support request management.' },
      { name: 'Client Accounts', href: '/itsm/clients', icon: 'UsersIcon', description: 'Client account management and relationship tracking.' },
      { name: 'Incidents', href: '/itsm/incidents', icon: 'ExclamationTriangleIcon', description: 'Incident tracking and resolution workflow.' },
      { name: 'Change Log', href: '/itsm/changes', icon: 'CalendarIcon', description: 'Change management and deployment tracking.' },
      { name: 'Knowledge Base', href: '/itsm/kb', icon: 'BookOpenIcon', description: 'Support documentation and FAQ knowledge base.' },
      { name: 'Assets & Vendors', href: '/itsm/assets', icon: 'ServerIcon', description: 'IT assets, vendor contracts, and service tracking.' },
    ],
  },
  // ── Admin (minimal) ────────────────────────────────────────────────────────
  {
    label: 'Admin',
    items: [
      { name: 'Organizations', href: '/orgs', icon: 'UsersIcon', description: 'Multi-tenant organization and workspace management.' },
      { name: 'Docs', href: '/docs', icon: 'DocumentTextIcon', description: 'Internal documentation and knowledge base.' },
      { name: 'Settings', href: '/settings', icon: 'Cog6ToothIcon', description: 'System settings, preferences, and configuration.' },
    ],
  },
]

// External app URLs — configurable via NEXT_PUBLIC_* env vars
const appLinks = [
  { name: 'Public Web', href: process.env.NEXT_PUBLIC_WEB_URL, badge: '3000' },
  { name: 'Partner Portal', href: process.env.NEXT_PUBLIC_PARTNERS_URL, badge: '3002' },
  { name: 'Union Eyes', href: process.env.NEXT_PUBLIC_UNION_EYES_URL, badge: '3003' },
  { name: 'FAIRCASE', href: process.env.NEXT_PUBLIC_ABR_URL, badge: '3004' },
]

export default async function ConsoleLayout({ children }: { children: React.ReactNode }) {
  // Server-side auth gate — runs on Node.js (not Edge) so crypto.subtle works.
  // Middleware only sets up auth context; this layout enforces authentication.
  const { userId } = await auth()
  if (!userId) redirect('/sign-in')

  const sidebar = (
    <aside className="w-64 border-r border-gray-200 bg-white flex flex-col">
      <div className="p-4 border-b border-gray-100">
        <Link href="/console" className="text-xl font-bold text-blue-600">
          Nzila Console
        </Link>
      </div>
      <SidebarNav groups={navGroups} />

      {/* App Launcher */}
      <div className="px-3 pb-2 border-t border-gray-100 pt-3">
        <p className="px-3 text-xs font-semibold text-gray-400 uppercase tracking-widest mb-1">Launch App</p>
        {appLinks.map((app) => (
          app.href ? (
            <a
              key={app.name}
              href={app.href}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center justify-between px-3 py-2 text-sm font-medium text-gray-600 rounded-lg hover:bg-gray-50 hover:text-gray-900 transition"
            >
              <span className="flex items-center gap-2">
                <ArrowTopRightOnSquareIcon className="h-4 w-4 text-gray-400" />
                {app.name}
              </span>
              <span className="text-xs text-gray-400 font-mono">{app.badge}</span>
            </a>
          ) : (
            <div key={app.name} className="flex items-center justify-between px-3 py-2 text-sm text-amber-700 rounded-lg bg-amber-50">
              <span>{app.name}</span>
              <span className="text-xs">Not configured</span>
            </div>
          )
        ))}
      </div>
      <div className="p-4 border-t border-gray-100 flex items-center gap-3">
        <UserButton />
        <span className="text-sm text-gray-500">Account</span>
      </div>
    </aside>
  )

  return (
    <ExecutiveModeWrapper sidebar={sidebar}>
      <>
        <CommandSectionGuide />
        {children}
      </>
    </ExecutiveModeWrapper>
  )
}
