# Generated by Django 5.2.17 on 2026-09-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_enterprise_hardening"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="integrationidempotencykey",
            name="uq_idempkey_hash_org",
        ),
        migrations.AlterField(
            model_name="event",
            name="org_id",
            field=models.UUIDField(db_index=True, help_text="Organization ID"),
        ),
        migrations.AlterField(
            model_name="integrationregistry",
            name="org_id",
            field=models.UUIDField(db_index=True, help_text="Organization ID"),
        ),
        migrations.AddConstraint(
            model_name="integrationidempotencykey",
            constraint=models.UniqueConstraint(
                fields=("request_hash", "org_id"), name="uq_idempkey_hash_org"
            ),
        ),
    ]
