/**
 * @nzila/platform-shell — Default Module Definitions
 *
 * Canonical registration of all Nzila OS apps.
 * Aligned with platform/registry/platform-registry.json.
 */
import type { ModuleRegistration } from '@nzila/platform-contracts/module-registry';

export const DEFAULT_MODULES: ModuleRegistration[] = [
  // ── Core products ────────────────────────────────────────────────────────
  {
    id: 'union-eyes',
    name: 'Union Eyes',
    description: 'Labor union management — grievances, collective bargaining, pension',
    basePath: '/union-eyes',
    iconToken: 'shield',
    tier: 'PRODUCTION',
    enabledByDefault: true,
    requiredRoles: [],
    requiredEntitlements: [],
    showInNav: true,
    navOrder: 10,
    requiresOrgScope: true,
    packageName: '@nzila/union-eyes',
    devPort: 3001,
    owner: 'union-eyes-team',
  },
  {
    id: 'flow',
    name: 'Flow',
    description: 'Workflow orchestration and process automation',
    basePath: '/flow',
    iconToken: 'workflow',
    tier: 'PRODUCTION',
    enabledByDefault: true,
    requiredRoles: [],
    requiredEntitlements: [],
    showInNav: true,
    navOrder: 20,
    requiresOrgScope: true,
    packageName: '@nzila/flow',
    devPort: 3004,
    owner: 'flow-team',
  },
  {
    id: 'cfo',
    name: 'CFO',
    description: 'Financial management — budgeting, forecasting, audit',
    basePath: '/cfo',
    iconToken: 'wallet',
    tier: 'PRODUCTION',
    enabledByDefault: false,
    requiredRoles: [],
    requiredEntitlements: ['advanced_analytics'],
    showInNav: true,
    navOrder: 30,
    requiresOrgScope: true,
    packageName: '@nzila/cfo',
    devPort: 3005,
    owner: 'finance-team',
  },
  {
    id: 'trade',
    name: 'Trade',
    description: 'Cross-border trade and compliance',
    basePath: '/trade',
    iconToken: 'globe',
    tier: 'PRODUCTION',
    enabledByDefault: false,
    requiredRoles: [],
    requiredEntitlements: [],
    showInNav: true,
    navOrder: 40,
    requiresOrgScope: true,
    packageName: '@nzila/trade',
    devPort: 3012,
    owner: 'trade-team',
  },
  {
    id: 'agrimo',
    name: 'Agrimo',
    description: 'Agri-commerce — cooperatives, harvest, marketplace',
    basePath: '/agrimo',
    iconToken: 'sprout',
    tier: 'PRODUCTION',
    enabledByDefault: false,
    requiredRoles: [],
    requiredEntitlements: [],
    showInNav: true,
    navOrder: 50,
    requiresOrgScope: true,
    packageName: '@nzila/agrimo',
    devPort: 3003,
    owner: 'agri-team',
  },
  {
    id: 'cora',
    name: 'Cora',
    description: 'AI assistant and decision support',
    basePath: '/cora',
    iconToken: 'brain',
    tier: 'PILOT',
    enabledByDefault: false,
    requiredRoles: [],
    requiredEntitlements: ['api_access'],
    showInNav: true,
    navOrder: 60,
    requiresOrgScope: true,
    packageName: '@nzila/cora',
    devPort: 3006,
    owner: 'ai-team',
  },
  {
    id: 'abr',
    name: 'ABR',
    description: 'Business registry and company registration',
    basePath: '/abr',
    iconToken: 'building',
    tier: 'PRODUCTION',
    enabledByDefault: false,
    requiredRoles: [],
    requiredEntitlements: [],
    showInNav: true,
    navOrder: 70,
    requiresOrgScope: true,
    packageName: '@nzila/abr',
    devPort: 3002,
    owner: 'registry-team',
  },
  {
    id: 'zonga',
    name: 'Zonga',
    description: 'Supply chain management',
    basePath: '/zonga',
    iconToken: 'truck',
    tier: 'INCUBATING',
    enabledByDefault: false,
    requiredRoles: [],
    requiredEntitlements: [],
    showInNav: true,
    navOrder: 80,
    requiresOrgScope: true,
    packageName: '@nzila/zonga',
    devPort: 3014,
    owner: 'logistics-team',
  },
  {
    id: 'nacp-exams',
    name: 'NACP Exams',
    description: 'National certification and professional examinations',
    basePath: '/nacp-exams',
    iconToken: 'graduation-cap',
    tier: 'PILOT',
    enabledByDefault: false,
    requiredRoles: [],
    requiredEntitlements: [],
    showInNav: true,
    navOrder: 90,
    requiresOrgScope: true,
    packageName: '@nzila/nacp-exams',
    devPort: 3011,
    owner: 'exams-team',
  },
  {
    id: 'mobility',
    name: 'Mobility',
    description: 'Transport and mobility management',
    basePath: '/mobility',
    iconToken: 'car',
    tier: 'INCUBATING',
    enabledByDefault: false,
    requiredRoles: [],
    requiredEntitlements: [],
    showInNav: true,
    navOrder: 100,
    requiresOrgScope: true,
    packageName: '@nzila/mobility',
    devPort: 3009,
    owner: 'mobility-team',
  },

  // ── Platform surfaces ────────────────────────────────────────────────────
  {
    id: 'console',
    name: 'Console',
    description: 'Org administration console',
    basePath: '/console',
    iconToken: 'settings',
    tier: 'PRODUCTION',
    enabledByDefault: true,
    requiredRoles: ['org_admin'],
    requiredEntitlements: [],
    showInNav: true,
    navOrder: 200,
    requiresOrgScope: true,
    packageName: '@nzila/console',
    devPort: 3007,
    owner: 'platform-team',
  },
  {
    id: 'control-plane',
    name: 'Control Plane',
    description: 'Platform-wide operations and health',
    basePath: '/control-plane',
    iconToken: 'activity',
    tier: 'PRODUCTION',
    enabledByDefault: true,
    requiredRoles: ['platform_admin'],
    requiredEntitlements: [],
    showInNav: true,
    navOrder: 210,
    requiresOrgScope: false,
    packageName: '@nzila/control-plane',
    devPort: 3008,
    owner: 'platform-team',
  },
  {
    id: 'platform-admin',
    name: 'Platform Admin',
    description: 'Super-admin operations',
    basePath: '/platform-admin',
    iconToken: 'shield-check',
    tier: 'PRODUCTION',
    enabledByDefault: true,
    requiredRoles: ['platform_admin'],
    requiredEntitlements: [],
    showInNav: true,
    navOrder: 220,
    requiresOrgScope: false,
    packageName: '@nzila/platform-admin',
    devPort: 3015,
    owner: 'platform-team',
  },
  {
    id: 'partners',
    name: 'Partners',
    description: 'Partner portal and ecosystem',
    basePath: '/partners',
    iconToken: 'handshake',
    tier: 'PRODUCTION',
    enabledByDefault: false,
    requiredRoles: [],
    requiredEntitlements: [],
    showInNav: true,
    navOrder: 230,
    requiresOrgScope: true,
    packageName: '@nzila/partners',
    devPort: 3010,
    owner: 'partnerships-team',
  },

  // ── Public surfaces (no nav) ─────────────────────────────────────────────
  {
    id: 'web',
    name: 'Web',
    description: 'Public-facing marketing and landing pages',
    basePath: '/',
    iconToken: 'globe',
    tier: 'PRODUCTION',
    enabledByDefault: true,
    requiredRoles: [],
    requiredEntitlements: [],
    showInNav: false,
    navOrder: 999,
    requiresOrgScope: false,
    packageName: '@nzila/web',
    devPort: 3000,
    owner: 'marketing-team',
  },
  {
    id: 'mobility-client-portal',
    name: 'Mobility Client Portal',
    description: 'Self-service portal for mobility clients',
    basePath: '/mobility-portal',
    iconToken: 'user',
    tier: 'INCUBATING',
    enabledByDefault: false,
    requiredRoles: [],
    requiredEntitlements: [],
    showInNav: false,
    navOrder: 999,
    requiresOrgScope: true,
    packageName: '@nzila/mobility-client-portal',
    devPort: 3016,
    owner: 'mobility-team',
  },

  // ── Backend services (no nav) ────────────────────────────────────────────
  {
    id: 'orchestrator-api',
    name: 'Orchestrator API',
    description: 'Backend orchestration service (Fastify)',
    basePath: '/api/orchestrator',
    iconToken: 'server',
    tier: 'PRODUCTION',
    enabledByDefault: true,
    requiredRoles: [],
    requiredEntitlements: [],
    showInNav: false,
    navOrder: 999,
    requiresOrgScope: true,
    packageName: '@nzila/orchestrator-api',
    devPort: 4000,
    owner: 'platform-team',
  },
];
