# Generated by Django 5.1.15 on 2026-03-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grievances", "0003_expand_grievances_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="claimdeadlines",
            name="alert_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="claimdeadlines",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="claimdeadlines",
            name="completed_by",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="claimdeadlines",
            name="completion_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="claimdeadlines",
            name="days_overdue",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="claimdeadlines",
            name="days_until_due",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="claimdeadlines",
            name="deadline_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="claimdeadlines",
            name="deadline_rule_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="claimdeadlines",
            name="deadline_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="claimdeadlines",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="claimdeadlines",
            name="escalated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="claimdeadlines",
            name="escalated_to",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="claimdeadlines",
            name="event_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="claimdeadlines",
            name="extension_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="claimdeadlines",
            name="is_overdue",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="claimdeadlines",
            name="last_alert_sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="claimdeadlines",
            name="last_extension_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="claimdeadlines",
            name="last_extension_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="claimdeadlines",
            name="original_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="claimdeadlines",
            name="priority",
            field=models.CharField(default="medium", max_length=20),
        ),
        migrations.AddField(
            model_name="claimdeadlines",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.AddField(
            model_name="claimdeadlines",
            name="total_extension_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="deadlinerules",
            name="allows_extension",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deadlinerules",
            name="business_days_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deadlinerules",
            name="claim_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="deadlinerules",
            name="created_by",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deadlinerules",
            name="days_from_event",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deadlinerules",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deadlinerules",
            name="escalate_to_role",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="deadlinerules",
            name="escalation_delay_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="deadlinerules",
            name="event_type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="deadlinerules",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deadlinerules",
            name="is_system_rule",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deadlinerules",
            name="max_extension_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="deadlinerules",
            name="priority_level",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="deadlinerules",
            name="requires_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deadlinerules",
            name="rule_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="deadlinerules",
            name="rule_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="deadlinerules",
            name="step_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="claimdeadlines",
            index=models.Index(
                fields=["organization_id"], name="idx_claim_deadlines_org"
            ),
        ),
        migrations.AddIndex(
            model_name="claimdeadlines",
            index=models.Index(fields=["status"], name="idx_claim_deadlines_status"),
        ),
    ]
