# Generated by Django 5.2.17 on 2026-09-22 18:12
#
# Not covered by PLATFORM_SQL 0005/0006/0007. 0007 adds claim_updates columns
# only. claims.idempotency_hash remains a Django-owned additive column.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grievances", "0004_expand_deadline_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="claims",
            name="idempotency_hash",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
