# Generated by Django 5.2.17 on 2026-09-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grievances", "0004_expand_deadline_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="claims",
            name="idempotency_hash",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
