"""
DRF viewsets for content app.
Auto-generated by Nzila Code Generator — 2026-02-17
"""
from rest_framework import viewsets, permissions, filters
from django_filters.rest_framework import DjangoFilterBackend
from .models import (BoardPackets, BoardPacketSections, BoardPacketDistributions, BoardPacketTemplates, CmsTemplates, CmsPages, CmsBlocks, CmsNavigationMenus, CmsMediaLibrary, PublicEvents, EventRegistrations, EventCheckIns, JobPostings, JobApplications, JobSaved, WebsiteSettings, DocumentFolders, Documents, PublicContent, MemberDocuments, SignatureDocuments, DocumentSigners, SignatureAuditTrail, SignatureTemplates, SignatureWebhooksLog, SignatureWorkflows, Signers, SignatureAuditLog, SignatureVerification, ShopifyConfig, WebhookReceipts, SocialAccounts, SocialPosts, SocialCampaigns, SocialAnalytics, SocialFeeds, SocialEngagement, ImpactMetrics, CaseStudies, Testimonials, PilotApplications, PilotMetrics, OrganizerImpacts, DataAggregationConsent, MovementTrends)
from .serializers import (BoardPacketsSerializer, BoardPacketSectionsSerializer, BoardPacketDistributionsSerializer, BoardPacketTemplatesSerializer, CmsTemplatesSerializer, CmsPagesSerializer, CmsBlocksSerializer, CmsNavigationMenusSerializer, CmsMediaLibrarySerializer, PublicEventsSerializer, EventRegistrationsSerializer, EventCheckInsSerializer, JobPostingsSerializer, JobApplicationsSerializer, JobSavedSerializer, WebsiteSettingsSerializer, DocumentFoldersSerializer, DocumentsSerializer, PublicContentSerializer, MemberDocumentsSerializer, SignatureDocumentsSerializer, DocumentSignersSerializer, SignatureAuditTrailSerializer, SignatureTemplatesSerializer, SignatureWebhooksLogSerializer, SignatureWorkflowsSerializer, SignersSerializer, SignatureAuditLogSerializer, SignatureVerificationSerializer, ShopifyConfigSerializer, WebhookReceiptsSerializer, SocialAccountsSerializer, SocialPostsSerializer, SocialCampaignsSerializer, SocialAnalyticsSerializer, SocialFeedsSerializer, SocialEngagementSerializer, ImpactMetricsSerializer, CaseStudiesSerializer, TestimonialsSerializer, PilotApplicationsSerializer, PilotMetricsSerializer, OrganizerImpactsSerializer, DataAggregationConsentSerializer, MovementTrendsSerializer)


class BoardPacketsViewSet(viewsets.ModelViewSet):
    """API endpoint for BoardPackets operations."""
    queryset = BoardPackets.objects.all()
    serializer_class = BoardPacketsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['title']
    search_fields = ['title']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class BoardPacketSectionsViewSet(viewsets.ModelViewSet):
    """API endpoint for BoardPacketSections operations."""
    queryset = BoardPacketSections.objects.all()
    serializer_class = BoardPacketSectionsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['packet_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class BoardPacketDistributionsViewSet(viewsets.ModelViewSet):
    """API endpoint for BoardPacketDistributions operations."""
    queryset = BoardPacketDistributions.objects.all()
    serializer_class = BoardPacketDistributionsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['packet_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class BoardPacketTemplatesViewSet(viewsets.ModelViewSet):
    """API endpoint for BoardPacketTemplates operations."""
    queryset = BoardPacketTemplates.objects.all()
    serializer_class = BoardPacketTemplatesSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['name']
    search_fields = ['name']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class CmsTemplatesViewSet(viewsets.ModelViewSet):
    """API endpoint for CmsTemplates operations."""
    queryset = CmsTemplates.objects.all()
    serializer_class = CmsTemplatesSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['organization_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class CmsPagesViewSet(viewsets.ModelViewSet):
    """API endpoint for CmsPages operations."""
    queryset = CmsPages.objects.all()
    serializer_class = CmsPagesSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['organization_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class CmsBlocksViewSet(viewsets.ModelViewSet):
    """API endpoint for CmsBlocks operations."""
    queryset = CmsBlocks.objects.all()
    serializer_class = CmsBlocksSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['organization_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class CmsNavigationMenusViewSet(viewsets.ModelViewSet):
    """API endpoint for CmsNavigationMenus operations."""
    queryset = CmsNavigationMenus.objects.all()
    serializer_class = CmsNavigationMenusSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['organization_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class CmsMediaLibraryViewSet(viewsets.ModelViewSet):
    """API endpoint for CmsMediaLibrary operations."""
    queryset = CmsMediaLibrary.objects.all()
    serializer_class = CmsMediaLibrarySerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['organization_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class PublicEventsViewSet(viewsets.ModelViewSet):
    """API endpoint for PublicEvents operations."""
    queryset = PublicEvents.objects.all()
    serializer_class = PublicEventsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['organization_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class EventRegistrationsViewSet(viewsets.ModelViewSet):
    """API endpoint for EventRegistrations operations."""
    queryset = EventRegistrations.objects.all()
    serializer_class = EventRegistrationsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['organization_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class EventCheckInsViewSet(viewsets.ModelViewSet):
    """API endpoint for EventCheckIns operations."""
    queryset = EventCheckIns.objects.all()
    serializer_class = EventCheckInsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['organization_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class JobPostingsViewSet(viewsets.ModelViewSet):
    """API endpoint for JobPostings operations."""
    queryset = JobPostings.objects.all()
    serializer_class = JobPostingsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['organization_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class JobApplicationsViewSet(viewsets.ModelViewSet):
    """API endpoint for JobApplications operations."""
    queryset = JobApplications.objects.all()
    serializer_class = JobApplicationsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['organization_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class JobSavedViewSet(viewsets.ModelViewSet):
    """API endpoint for JobSaved operations."""
    queryset = JobSaved.objects.all()
    serializer_class = JobSavedSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['organization_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class WebsiteSettingsViewSet(viewsets.ModelViewSet):
    """API endpoint for WebsiteSettings operations."""
    queryset = WebsiteSettings.objects.all()
    serializer_class = WebsiteSettingsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['organization_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class DocumentFoldersViewSet(viewsets.ModelViewSet):
    """API endpoint for DocumentFolders operations."""
    queryset = DocumentFolders.objects.all()
    serializer_class = DocumentFoldersSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class DocumentsViewSet(viewsets.ModelViewSet):
    """API endpoint for Documents operations."""
    queryset = Documents.objects.all()
    serializer_class = DocumentsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class PublicContentViewSet(viewsets.ModelViewSet):
    """API endpoint for PublicContent operations."""
    queryset = PublicContent.objects.all()
    serializer_class = PublicContentSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['organization_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class MemberDocumentsViewSet(viewsets.ModelViewSet):
    """API endpoint for MemberDocuments operations."""
    queryset = MemberDocuments.objects.all()
    serializer_class = MemberDocumentsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    search_fields = ['user_id', 'file_name', 'file_url', 'file_type', 'category']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class SignatureDocumentsViewSet(viewsets.ModelViewSet):
    """API endpoint for SignatureDocuments operations."""
    queryset = SignatureDocuments.objects.all()
    serializer_class = SignatureDocumentsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class DocumentSignersViewSet(viewsets.ModelViewSet):
    """API endpoint for DocumentSigners operations."""
    queryset = DocumentSigners.objects.all()
    serializer_class = DocumentSignersSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class SignatureAuditTrailViewSet(viewsets.ModelViewSet):
    """API endpoint for SignatureAuditTrail operations."""
    queryset = SignatureAuditTrail.objects.all()
    serializer_class = SignatureAuditTrailSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class SignatureTemplatesViewSet(viewsets.ModelViewSet):
    """API endpoint for SignatureTemplates operations."""
    queryset = SignatureTemplates.objects.all()
    serializer_class = SignatureTemplatesSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class SignatureWebhooksLogViewSet(viewsets.ModelViewSet):
    """API endpoint for SignatureWebhooksLog operations."""
    queryset = SignatureWebhooksLog.objects.all()
    serializer_class = SignatureWebhooksLogSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['document_id']
    search_fields = ['provider', 'event_type']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class SignatureWorkflowsViewSet(viewsets.ModelViewSet):
    """API endpoint for SignatureWorkflows operations."""
    queryset = SignatureWorkflows.objects.all()
    serializer_class = SignatureWorkflowsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class SignersViewSet(viewsets.ModelViewSet):
    """API endpoint for Signers operations."""
    queryset = Signers.objects.all()
    serializer_class = SignersSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class SignatureAuditLogViewSet(viewsets.ModelViewSet):
    """API endpoint for SignatureAuditLog operations."""
    queryset = SignatureAuditLog.objects.all()
    serializer_class = SignatureAuditLogSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class SignatureVerificationViewSet(viewsets.ModelViewSet):
    """API endpoint for SignatureVerification operations."""
    queryset = SignatureVerification.objects.all()
    serializer_class = SignatureVerificationSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class ShopifyConfigViewSet(viewsets.ModelViewSet):
    """API endpoint for ShopifyConfig operations."""
    queryset = ShopifyConfig.objects.all()
    serializer_class = ShopifyConfigSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class WebhookReceiptsViewSet(viewsets.ModelViewSet):
    """API endpoint for WebhookReceipts operations."""
    queryset = WebhookReceipts.objects.all()
    serializer_class = WebhookReceiptsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['webhook_id']
    search_fields = ['provider', 'webhook_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class DenyAllPermission(permissions.BasePermission):
    """Round 37: no legitimate Django consumer of SocialAccountsViewSet exists.

    The generated model only maps `organization` (not the canonical access_token/
    refresh_token/platform fields), but Django DELETE/UPDATE still operate on the
    real physical `social_accounts` row \u2014 an authenticated user of any org could
    reassign `organization_id` (org-takeover of another org's OAuth-connected
    account) or delete it, with no queryset scoping (`IsAuthenticated` only,
    `organization_id` merely query-filterable). Deny unconditionally until a real
    consumer with proven tenant isolation exists.
    """

    def has_permission(self, request, view):
        return False

    def has_object_permission(self, request, view, obj):
        return False


class SocialAccountsViewSet(viewsets.ModelViewSet):
    """API endpoint for SocialAccounts operations."""
    queryset = SocialAccounts.objects.all()
    serializer_class = SocialAccountsSerializer
    permission_classes = [DenyAllPermission]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['organization_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class SocialPostsViewSet(viewsets.ModelViewSet):
    """API endpoint for SocialPosts operations."""
    queryset = SocialPosts.objects.all()
    serializer_class = SocialPostsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['organization_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class SocialCampaignsViewSet(viewsets.ModelViewSet):
    """API endpoint for SocialCampaigns operations."""
    queryset = SocialCampaigns.objects.all()
    serializer_class = SocialCampaignsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['organization_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class SocialAnalyticsViewSet(viewsets.ModelViewSet):
    """API endpoint for SocialAnalytics operations."""
    queryset = SocialAnalytics.objects.all()
    serializer_class = SocialAnalyticsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['organization_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class SocialFeedsViewSet(viewsets.ModelViewSet):
    """API endpoint for SocialFeeds operations."""
    queryset = SocialFeeds.objects.all()
    serializer_class = SocialFeedsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['organization_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class SocialEngagementViewSet(viewsets.ModelViewSet):
    """API endpoint for SocialEngagement operations."""
    queryset = SocialEngagement.objects.all()
    serializer_class = SocialEngagementSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['organization_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class ImpactMetricsViewSet(viewsets.ModelViewSet):
    """API endpoint for ImpactMetrics operations."""
    queryset = ImpactMetrics.objects.all()
    serializer_class = ImpactMetricsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class CaseStudiesViewSet(viewsets.ModelViewSet):
    """API endpoint for CaseStudies operations."""
    queryset = CaseStudies.objects.all()
    serializer_class = CaseStudiesSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['organization_id']
    search_fields = ['slug', 'title']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class TestimonialsViewSet(viewsets.ModelViewSet):
    """API endpoint for Testimonials operations."""
    queryset = Testimonials.objects.all()
    serializer_class = TestimonialsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['featured']
    search_fields = ['type', 'quote', 'author', 'role', 'organization']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class PilotApplicationsViewSet(viewsets.ModelViewSet):
    """API endpoint for PilotApplications operations."""
    queryset = PilotApplications.objects.all()
    serializer_class = PilotApplicationsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    search_fields = ['organization_name', 'organization_type', 'contact_name', 'contact_email', 'contact_phone']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class PilotMetricsViewSet(viewsets.ModelViewSet):
    """API endpoint for PilotMetrics operations."""
    queryset = PilotMetrics.objects.all()
    serializer_class = PilotMetricsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class OrganizerImpactsViewSet(viewsets.ModelViewSet):
    """API endpoint for OrganizerImpacts operations."""
    queryset = OrganizerImpacts.objects.all()
    serializer_class = OrganizerImpactsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class DataAggregationConsentViewSet(viewsets.ModelViewSet):
    """API endpoint for DataAggregationConsent operations."""
    queryset = DataAggregationConsent.objects.all()
    serializer_class = DataAggregationConsentSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class MovementTrendsViewSet(viewsets.ModelViewSet):
    """API endpoint for MovementTrends operations."""
    queryset = MovementTrends.objects.all()
    serializer_class = MovementTrendsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['legislative_brief_relevance', 'emerging_pattern']
    search_fields = ['category', 'dimension', 'timeframe', 'insights', 'confidence_level']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']
