/**
 * Phase 0C.2 §BR-7 — auth reconciliation regression guard.
 *
 * Static-analysis guard on `apps/union-eyes/e2e/helpers/auth.ts` `loginAsRole`
 * confirming that the §11(b) reconciliation contract remains intact.
 *
 * ── Context ──────────────────────────────────────────────────────────────
 *
 * §8 introduced 5 persona Playwright projects (member, steward, staff,
 * executive, admin) that each load a real `nzila_session` cookie via
 * `storageState: playwright/.auth/<role>.json`, generated by §7's
 * `scripts/lifecycle/generate-auth-states.ts` (via /api/auth/password/sign-in
 * with UA `playwright-e2e-auth`). Those cookies are backed by real PG rows
 * in `auth_user_sessions`.
 *
 * §8 also left an inline TODO(phase-0c2-§11) in `loginAsRole` documenting
 * that the pre-existing PLAYWRIGHT_TEST_AUTH=true branch injected a
 * synthetic `nzila_session=ue-seed-session-<userId>` cookie which, when
 * combined with a persona storageState, would **overwrite the real cookie
 * with garbage**. Every downstream test that relies on the real persona
 * (dashboard renders, RBAC checks, organization_members lookups against
 * `auth().userId`) would then fail with "session not found" or
 * fixture-role drift.
 *
 * §11(b) resolved that TODO in-place by making the synthetic branch
 * detect a pre-existing valid session cookie and short-circuit:
 *
 *   if PLAYWRIGHT_TEST_AUTH=true:
 *     if `nzila_session` already present with non-empty value:
 *       → apply ONLY org-context cookies (never overwrite session)
 *       → return
 *     else:
 *       → keep legacy synthetic-cookie behaviour (specs that don't opt
 *         into storageState still work — public, security, bilingual,
 *         accessibility projects)
 *
 * §BR-7 (this file) makes that contract statically verifiable so future
 * refactors cannot silently regress it. The guard is text-level (regex
 * on the source), matching the pattern used by §12 (e2e-helpers-timeout),
 * §13 (bilingual-smoke), §14 (a11y-smoke), and §BR-6 (lifecycle-project-
 * filter) — no runtime Playwright invocation, no browser boot, no I/O.
 *
 * ── References ───────────────────────────────────────────────────────────
 *
 *   - apps/union-eyes/e2e/helpers/auth.ts § `loginAsRole`
 *   - apps/union-eyes/playwright.config.ts § `PLAYWRIGHT_PROJECT_MANIFEST`
 *     (setup, member, steward, staff, executive, admin persona projects)
 *   - apps/union-eyes/scripts/lifecycle/generate-auth-states.ts
 *   - reports/audits/cupe-national-phase-0/phase-0c/
 *     phase-0c2-baseline-remediation-auth-reconciliation.md
 */
import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import path from 'node:path'

const AUTH_HELPER_PATH = path.resolve(
  __dirname,
  '..',
  'e2e',
  'helpers',
  'auth.ts',
)

function readAuthHelper(): string {
  return readFileSync(AUTH_HELPER_PATH, 'utf8')
}

describe('Phase 0C.2 §BR-7 — loginAsRole reconciliation contract', () => {
  const source = readAuthHelper()

  it('imports Page/APIRequestContext types from @playwright/test', () => {
    expect(source).toMatch(
      /import\s+type\s+\{[^}]*Page[^}]*\}\s+from\s+['"]@playwright\/test['"]/,
    )
    expect(source).toMatch(
      /import\s+type\s+\{[^}]*APIRequestContext[^}]*\}\s+from\s+['"]@playwright\/test['"]/,
    )
  })

  it('exports async loginAsRole(page, role) with StakeholderRole', () => {
    expect(source).toMatch(
      /export\s+async\s+function\s+loginAsRole\s*\(\s*page\s*:\s*Page\s*,\s*role\s*:\s*StakeholderRole\s*\)\s*:\s*Promise<void>/,
    )
  })

  it('reads PLAYWRIGHT_TEST_AUTH from process.env and lowercases it before comparing to "true"', () => {
    // Loose regex — allows either ?? or || nullish, single/double quotes,
    // and whitespace variance — but pins the essential semantics.
    expect(source).toMatch(
      /process\.env\.PLAYWRIGHT_TEST_AUTH[\s\S]{0,40}\.toLowerCase\(\)\s*===\s*['"]true['"]/,
    )
  })

  it('inspects existing context cookies via page.context().cookies(cookieUrl)', () => {
    expect(source).toMatch(
      /await\s+page\.context\(\)\.cookies\(\s*cookieUrl\s*\)/,
    )
  })

  it('detects a real session by name === "nzila_session" AND non-empty value', () => {
    // The exact filter that decides "did storageState provide a real
    // session?". If someone changes this to name-only, an empty-value
    // cookie (e.g. from a corrupted state file) would silently be
    // treated as "real" and the fallback path would never run.
    expect(source).toMatch(
      /c\.name\s*===\s*['"]nzila_session['"][\s\S]{0,40}c\.value\.length\s*>\s*0/,
    )
  })

  it('short-circuits with org-context cookies ONLY when a real session is present', () => {
    // Must return immediately after adding org-context cookies, without
    // falling through into the synthetic-cookie block. Regex checks that
    // inside the `if (hasRealSession)` branch we call addCookies then
    // return.
    expect(source).toMatch(
      /if\s*\(\s*hasRealSession\s*\)\s*\{[\s\S]{0,200}addCookies\s*\(\s*orgContextCookies\s*\)[\s\S]{0,60}return\s*;/,
    )
  })

  it('still adds three org-selection cookies (selected_org_id / selected_organization_id / selected_tenant_id)', () => {
    expect(source).toMatch(/name:\s*['"]selected_org_id['"]/)
    expect(source).toMatch(/name:\s*['"]selected_organization_id['"]/)
    expect(source).toMatch(/name:\s*['"]selected_tenant_id['"]/)
  })

  it('always clears active-organization (expires: 0) to force fresh resolution', () => {
    // The active-organization cookie must be evicted; otherwise a stale
    // value could survive between persona switches.
    expect(source).toMatch(
      /name:\s*['"]active-organization['"][\s\S]{0,120}expires:\s*0/,
    )
  })

  it('preserves the synthetic ue-seed-session fallback for the else branch (no real cookie present)', () => {
    // Legacy specs that never opt into storageState (public, security,
    // bilingual, accessibility projects) rely on the synthetic cookie so
    // the auth-service bypass has SOMETHING to match. The fallback must
    // stay in place.
    expect(source).toMatch(
      /name:\s*['"]nzila_session['"][\s\S]{0,80}value:\s*`ue-seed-session-\$\{fixture\.userId\}`/,
    )
  })

  it('marks the synthetic session as httpOnly and Lax SameSite', () => {
    // Mirror the real session cookie's flags so browser behaviour stays
    // consistent between synthetic and real paths.
    expect(source).toMatch(
      /value:\s*`ue-seed-session-\$\{fixture\.userId\}`[\s\S]{0,200}httpOnly:\s*true[\s\S]{0,80}sameSite:\s*['"]Lax['"]/,
    )
  })

  it('uses HTTP login (loginAsTestUser) when PLAYWRIGHT_TEST_AUTH is not "true"', () => {
    // Default production-realistic path: real /api/auth/password/sign-in
    // against Argon2id + real session write. This branch must remain
    // present regardless of the bypass code.
    expect(source).toMatch(
      /await\s+loginAsTestUser\s*\(\s*page\.request\s*,\s*fixture\.email\s*\)/,
    )
  })

  it('adds org-context cookies AFTER HTTP login in the non-bypass path', () => {
    // Ordering matters: the HTTP login writes nzila_session; we then
    // stamp org selection on top. Use lastIndexOf because
    // addCookies(orgContextCookies) also appears in the earlier
    // hasRealSession short-circuit branch.
    const idxLogin = source.indexOf('loginAsTestUser(page.request')
    const idxAddCookies = source.lastIndexOf('addCookies(orgContextCookies)')
    expect(idxLogin).toBeGreaterThan(0)
    expect(idxAddCookies).toBeGreaterThan(idxLogin)
  })

  it('references §11 rationale so the intent survives future edits', () => {
    // Belt-and-braces: if someone rewrites the block without reading the
    // §11 comment, the regex above still guards behaviour. But the
    // comment is intended to lower the chance of that rewrite happening
    // at all.
    expect(source).toMatch(/Phase 0C\.2 §11/)
    expect(source).toMatch(/synthetic/i)
    expect(source).toMatch(/storageState/i)
  })

  it('sources baseUrl via getBaseUrl() helper, not a hardcoded URL', () => {
    // Ensures the port/host follow the governed lifecycle's dynamic
    // allocation (§10 uses port 3002 by default, but preflight can
    // reassign).
    expect(source).toMatch(/new URL\(\s*getBaseUrl\(\)\s*\)/)
  })
})
