"""
Admin configuration for content app.
Auto-generated by Nzila Code Generator — 2026-02-17
"""
from django.contrib import admin
from .models import (ContentCategories, Courses, Lessons, Quizzes, TribunalCases, Enrollments, LessonProgress, QuizAttempts, Achievements, UserAchievements, UserPoints, LearningStreaks, Bookmarks, CourseReviews, Testimonials)


@admin.register(ContentCategories)
class ContentCategoriesAdmin(admin.ModelAdmin):
    list_display = ['id', 'name', 'slug', 'created_at']
    search_fields = ['name', 'slug', 'description', 'icon']
    ordering = ['-created_at']


@admin.register(Courses)
class CoursesAdmin(admin.ModelAdmin):
    list_display = ['id', 'slug', 'created_at']
    list_filter = ['is_featured', 'required_tier']
    search_fields = ['slug', 'description', 'thumbnail_url', 'cover_image_url']
    ordering = ['-created_at']


@admin.register(Lessons)
class LessonsAdmin(admin.ModelAdmin):
    list_display = ['id', 'slug', 'created_at']
    list_filter = ['is_preview']
    search_fields = ['slug', 'description', 'content_url', 'article']
    ordering = ['-created_at']


@admin.register(Quizzes)
class QuizzesAdmin(admin.ModelAdmin):
    list_display = ['id']
    list_filter = ['randomize_questions', 'show_correct_answers']
    search_fields = ['description']
    ordering = ['-created_at']


@admin.register(TribunalCases)
class TribunalCasesAdmin(admin.ModelAdmin):
    list_display = ['id']
    list_filter = ['language']
    search_fields = ['case_title', 'citation', 'tribunal_province', 'respondent']
    ordering = ['-created_at']


@admin.register(Enrollments)
class EnrollmentsAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    ordering = ['-created_at']


@admin.register(LessonProgress)
class LessonProgressAdmin(admin.ModelAdmin):
    list_display = ['id']
    ordering = ['-created_at']


@admin.register(QuizAttempts)
class QuizAttemptsAdmin(admin.ModelAdmin):
    list_display = ['id', 'status']
    list_filter = ['status', 'passed']
    search_fields = ['status']
    ordering = ['-created_at']


@admin.register(Achievements)
class AchievementsAdmin(admin.ModelAdmin):
    list_display = ['id', 'slug']
    list_filter = ['is_active']
    search_fields = ['slug', 'description', 'icon_url', 'badge_image_url']
    ordering = ['-created_at']


@admin.register(UserAchievements)
class UserAchievementsAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    ordering = ['-created_at']


@admin.register(UserPoints)
class UserPointsAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    search_fields = ['bonus_reason']
    ordering = ['-created_at']


@admin.register(LearningStreaks)
class LearningStreaksAdmin(admin.ModelAdmin):
    list_display = ['id']
    ordering = ['-created_at']


@admin.register(Bookmarks)
class BookmarksAdmin(admin.ModelAdmin):
    list_display = ['id']
    search_fields = ['notes']
    ordering = ['-created_at']


@admin.register(CourseReviews)
class CourseReviewsAdmin(admin.ModelAdmin):
    list_display = ['id', 'title']
    list_filter = ['is_verified_purchase']
    search_fields = ['title', 'review_text', 'moderation_notes']
    ordering = ['-created_at']


@admin.register(Testimonials)
class TestimonialsAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    list_filter = ['active']
    search_fields = ['role', 'organization', 'content', 'linkedin_url']
    ordering = ['-created_at']
