"""
URL configuration for content app.
Auto-generated by Nzila Code Generator — 2026-02-17
"""
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

router = DefaultRouter()
router.register(r'content-categories', views.ContentCategoriesViewSet)
router.register(r'courses', views.CoursesViewSet)
router.register(r'lessons', views.LessonsViewSet)
router.register(r'quizzes', views.QuizzesViewSet)
router.register(r'tribunal-cases', views.TribunalCasesViewSet)
router.register(r'enrollments', views.EnrollmentsViewSet)
router.register(r'lesson-progress', views.LessonProgressViewSet)
router.register(r'quiz-attempts', views.QuizAttemptsViewSet)
router.register(r'achievements', views.AchievementsViewSet)
router.register(r'user-achievements', views.UserAchievementsViewSet)
router.register(r'user-points', views.UserPointsViewSet)
router.register(r'learning-streaks', views.LearningStreaksViewSet)
router.register(r'bookmarks', views.BookmarksViewSet)
router.register(r'course-reviews', views.CourseReviewsViewSet)
router.register(r'testimonials', views.TestimonialsViewSet)

app_name = 'content'

urlpatterns = [
    path('', include(router.urls)),
]