# Generated by Django 5.1.4 on 2026-02-18 02:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrganizationSubscriptions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
                ("stripe_customer_id", models.TextField(blank=True, null=True)),
                ("tier", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("seats_used", models.IntegerField(blank=True, null=True)),
                (
                    "billing_address",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("currency", models.TextField(blank=True, null=True)),
                ("billing_interval", models.TextField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("trial_start", models.DateTimeField(blank=True, null=True)),
                ("trial_end", models.DateTimeField(blank=True, null=True)),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "OrganizationSubscriptions",
                "db_table": "organization_subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SeatAllocations",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subscription_id", models.UUIDField(blank=True, null=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("role_in_org", models.TextField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "SeatAllocations",
                "db_table": "seat_allocations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionInvoices",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subscription_id", models.UUIDField(blank=True, null=True)),
                ("stripe_charge_id", models.TextField(blank=True, null=True)),
                ("amount_paid", models.IntegerField(blank=True, null=True)),
                ("currency", models.TextField(blank=True, null=True)),
                ("tax_amount", models.IntegerField(blank=True, null=True)),
                (
                    "tax_breakdown",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "SubscriptionInvoices",
                "db_table": "subscription_invoices",
                "ordering": ["-created_at"],
            },
        ),
    ]
