# Generated by Django 5.2.17 on 2026-09-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_automation_rules_organization_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlogs",
            name="action",
            field=models.CharField(
                blank=True,
                help_text="Verb: create, update, delete, initiate, cancel ...",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="auditlogs",
            name="correlation_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
