/**
 * API Documentation Page
 * 
 * Route: /api-docs
 *
 * NOTE: Interactive Swagger UI was previously rendered via `swagger-ui-react`,
 * but its transitive dep `swagger-client` uses a default import from
 * `js-yaml`, whose v4 ESM entry has no default export. Turbopack (Next 16
 * default builder) refuses to bundle it and the app-scoped
 * `turbopack.resolveAlias` in next.config.ts is only honored by the dev
 * server, not by `next build`. CSP forbids loading swagger-ui from a public
 * CDN. Until the upstream chain ships an ESM-clean default export, this
 * page links to the raw OpenAPI JSON, which any external Swagger Editor /
 * Redoc / Stoplight can consume.
 */

'use client';

export const dynamic = 'force-dynamic';
import Link from 'next/link';
import { useTranslations } from "next-intl";

export default function ApiDocsPage() {
  const t = useTranslations("apiDocs");
  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <div className="border-b bg-card">
        <div className="container mx-auto px-4 py-6">
          <h1 className="text-3xl font-bold">{t("title")}</h1>
          <p className="text-muted-foreground mt-2">
            {t("subtitle")}
          </p>
          <div className="mt-4 flex gap-4 text-sm text-muted-foreground">
            <div>
              <span className="font-semibold">{t("endpoints")}:</span> 462
            </div>
            <div>
              <span className="font-semibold">{t("coverage")}:</span> 100%
            </div>
            <div>
              <span className="font-semibold">{t("version")}:</span> 2.0.0
            </div>
          </div>
        </div>
      </div>

      {/* OpenAPI JSON link */}
      <div className="container mx-auto px-4 py-8 space-y-4">
        <p>
          The OpenAPI schema is served at:{' '}
          <Link href="/api/docs" className="text-primary underline">
            /api/docs
          </Link>
        </p>
        <p className="text-sm text-muted-foreground">
          Load this URL in Swagger Editor, Redoc, Postman, or any OpenAPI
          viewer for interactive exploration.
        </p>
      </div>

      {/* Footer Notice */}
      <div className="border-t bg-muted/50 py-8 mt-12">
        <div className="container mx-auto px-4 text-center text-sm text-muted-foreground">
          <p>
            📝 {t("autoGenerated")}
          </p>
          <p className="mt-2">
            {t("toRegenerate")} <code className="px-2 py-1 bg-background rounded">pnpm run openapi:generate</code>
          </p>
          <p className="mt-4">
            <a 
              href="https://github.com/unioneyes/api-docs" 
              className="text-primary hover:underline"
              target="_blank"
              rel="noopener noreferrer"
            >
              {t("viewOnGitHub")}
            </a>
            {' • '}
            <Link href="/docs/API_DOCUMENTATION_SCHEMA_CONSOLIDATION_GUIDE.md"
              className="text-primary hover:underline"
            >
              {t("documentationGuide")}
            </Link>
          </p>
        </div>
      </div>
    </div>
  );
}
