/**
 * Canadian Labour Standards — Statutory Holidays by Jurisdiction
 *
 * Province/territory-specific paid public holidays that employers
 * must observe. Includes variable dates (e.g. "3rd Monday of February").
 *
 * @module canadian-labour-standards/statutory-holidays
 */

import type { StatutoryHoliday, CanadianJurisdiction } from './types';

export const STATUTORY_HOLIDAYS: Record<CanadianJurisdiction, StatutoryHoliday[]> = {
  federal: [
    { name: "New Year's Day", date: '01-01' },
    { name: 'Good Friday', date: 'variable' },
    { name: 'Victoria Day', date: 'variable', notes: 'Monday before May 25' },
    { name: 'Canada Day', date: '07-01' },
    { name: 'Labour Day', date: 'variable', notes: '1st Monday of September' },
    { name: 'National Day for Truth and Reconciliation', date: '09-30' },
    { name: 'Thanksgiving Day', date: 'variable', notes: '2nd Monday of October' },
    { name: 'Remembrance Day', date: '11-11' },
    { name: 'Christmas Day', date: '12-25' },
    { name: 'Boxing Day', date: '12-26' },
  ],
  ON: [
    { name: "New Year's Day", date: '01-01' },
    { name: 'Family Day', date: 'variable', notes: '3rd Monday of February' },
    { name: 'Good Friday', date: 'variable' },
    { name: 'Victoria Day', date: 'variable', notes: 'Monday before May 25' },
    { name: 'Canada Day', date: '07-01' },
    { name: 'Labour Day', date: 'variable', notes: '1st Monday of September' },
    { name: 'Thanksgiving Day', date: 'variable', notes: '2nd Monday of October' },
    { name: 'Christmas Day', date: '12-25' },
    { name: 'Boxing Day', date: '12-26' },
  ],
  BC: [
    { name: "New Year's Day", date: '01-01' },
    { name: 'Family Day', date: 'variable', notes: '3rd Monday of February' },
    { name: 'Good Friday', date: 'variable' },
    { name: 'Victoria Day', date: 'variable', notes: 'Monday before May 25' },
    { name: 'Canada Day', date: '07-01' },
    { name: 'British Columbia Day', date: 'variable', notes: '1st Monday of August' },
    { name: 'Labour Day', date: 'variable', notes: '1st Monday of September' },
    { name: 'National Day for Truth and Reconciliation', date: '09-30' },
    { name: 'Thanksgiving Day', date: 'variable', notes: '2nd Monday of October' },
    { name: 'Remembrance Day', date: '11-11' },
    { name: 'Christmas Day', date: '12-25' },
  ],
  AB: [
    { name: "New Year's Day", date: '01-01' },
    { name: 'Family Day', date: 'variable', notes: '3rd Monday of February' },
    { name: 'Good Friday', date: 'variable' },
    { name: 'Victoria Day', date: 'variable', notes: 'Monday before May 25' },
    { name: 'Canada Day', date: '07-01' },
    { name: 'Heritage Day', date: 'variable', notes: '1st Monday of August' },
    { name: 'Labour Day', date: 'variable', notes: '1st Monday of September' },
    { name: 'Thanksgiving Day', date: 'variable', notes: '2nd Monday of October' },
    { name: 'Christmas Day', date: '12-25' },
  ],
  SK: [
    { name: "New Year's Day", date: '01-01' },
    { name: 'Family Day', date: 'variable', notes: '3rd Monday of February' },
    { name: 'Good Friday', date: 'variable' },
    { name: 'Victoria Day', date: 'variable', notes: 'Monday before May 25' },
    { name: 'Canada Day', date: '07-01' },
    { name: 'Saskatchewan Day', date: 'variable', notes: '1st Monday of August' },
    { name: 'Labour Day', date: 'variable', notes: '1st Monday of September' },
    { name: 'National Day for Truth and Reconciliation', date: '09-30' },
    { name: 'Thanksgiving Day', date: 'variable', notes: '2nd Monday of October' },
    { name: 'Remembrance Day', date: '11-11' },
    { name: 'Christmas Day', date: '12-25' },
  ],
  MB: [
    { name: "New Year's Day", date: '01-01' },
    { name: 'Louis Riel Day', date: 'variable', notes: '3rd Monday of February' },
    { name: 'Good Friday', date: 'variable' },
    { name: 'Victoria Day', date: 'variable', notes: 'Monday before May 25' },
    { name: 'Canada Day', date: '07-01' },
    { name: 'Terry Fox Day', date: 'variable', notes: '1st Monday of August (not paid)' },
    { name: 'Labour Day', date: 'variable', notes: '1st Monday of September' },
    { name: 'Thanksgiving Day', date: 'variable', notes: '2nd Monday of October' },
    { name: 'Christmas Day', date: '12-25' },
  ],
  NB: [
    { name: "New Year's Day", date: '01-01' },
    { name: 'Family Day', date: 'variable', notes: '3rd Monday of February' },
    { name: 'Good Friday', date: 'variable' },
    { name: 'Canada Day', date: '07-01' },
    { name: 'New Brunswick Day', date: 'variable', notes: '1st Monday of August' },
    { name: 'Labour Day', date: 'variable', notes: '1st Monday of September' },
    { name: 'Thanksgiving Day', date: 'variable', notes: '2nd Monday of October' },
    { name: 'Remembrance Day', date: '11-11' },
    { name: 'Christmas Day', date: '12-25' },
  ],
  NS: [
    { name: "New Year's Day", date: '01-01' },
    { name: 'Heritage Day', date: 'variable', notes: '3rd Monday of February' },
    { name: 'Good Friday', date: 'variable' },
    { name: 'Canada Day', date: '07-01' },
    { name: 'Labour Day', date: 'variable', notes: '1st Monday of September' },
    { name: 'Remembrance Day', date: '11-11' },
    { name: 'Christmas Day', date: '12-25' },
  ],
  PE: [
    { name: "New Year's Day", date: '01-01' },
    { name: 'Islander Day', date: 'variable', notes: '3rd Monday of February' },
    { name: 'Good Friday', date: 'variable' },
    { name: 'Canada Day', date: '07-01' },
    { name: 'Gold Cup Parade Day', date: 'variable', notes: '3rd Friday of August (Charlottetown area)' },
    { name: 'Labour Day', date: 'variable', notes: '1st Monday of September' },
    { name: 'Remembrance Day', date: '11-11' },
    { name: 'Christmas Day', date: '12-25' },
  ],
  NL: [
    { name: "New Year's Day", date: '01-01' },
    { name: 'Good Friday', date: 'variable' },
    { name: 'Canada Day / Memorial Day', date: '07-01' },
    { name: 'Labour Day', date: 'variable', notes: '1st Monday of September' },
    { name: 'Thanksgiving Day', date: 'variable', notes: '2nd Monday of October (optional)' },
    { name: 'Remembrance Day', date: '11-11' },
    { name: 'Christmas Day', date: '12-25' },
  ],
  QC: [
    { name: "Jour de l'An / New Year's Day", date: '01-01' },
    { name: 'Vendredi saint / Good Friday', date: 'variable', notes: 'Or Easter Monday at employer choice' },
    { name: 'Journée nationale des patriotes / Victoria Day', date: 'variable', notes: 'Monday before May 25' },
    { name: 'Fête nationale du Québec / St-Jean-Baptiste Day', date: '06-24' },
    { name: 'Fête du Canada / Canada Day', date: '07-01' },
    { name: 'Fête du Travail / Labour Day', date: 'variable', notes: '1st Monday of September' },
    { name: "Action de grâce / Thanksgiving", date: 'variable', notes: '2nd Monday of October' },
    { name: 'Noël / Christmas Day', date: '12-25' },
  ],
  YT: [
    { name: "New Year's Day", date: '01-01' },
    { name: 'Heritage Day', date: 'variable', notes: 'Friday before last Sunday in February' },
    { name: 'Good Friday', date: 'variable' },
    { name: 'Easter Monday', date: 'variable' },
    { name: 'Victoria Day', date: 'variable', notes: 'Monday before May 25' },
    { name: 'Canada Day', date: '07-01' },
    { name: 'Discovery Day', date: 'variable', notes: '3rd Monday of August' },
    { name: 'Labour Day', date: 'variable', notes: '1st Monday of September' },
    { name: 'Thanksgiving Day', date: 'variable', notes: '2nd Monday of October' },
    { name: 'Remembrance Day', date: '11-11' },
    { name: 'Christmas Day', date: '12-25' },
  ],
  NT: [
    { name: "New Year's Day", date: '01-01' },
    { name: 'Good Friday', date: 'variable' },
    { name: 'Victoria Day', date: 'variable', notes: 'Monday before May 25' },
    { name: 'National Indigenous Peoples Day', date: '06-21' },
    { name: 'Canada Day', date: '07-01' },
    { name: 'Civic Holiday', date: 'variable', notes: '1st Monday of August' },
    { name: 'Labour Day', date: 'variable', notes: '1st Monday of September' },
    { name: 'National Day for Truth and Reconciliation', date: '09-30' },
    { name: 'Thanksgiving Day', date: 'variable', notes: '2nd Monday of October' },
    { name: 'Remembrance Day', date: '11-11' },
    { name: 'Christmas Day', date: '12-25' },
  ],
  NU: [
    { name: "New Year's Day", date: '01-01' },
    { name: 'Good Friday', date: 'variable' },
    { name: 'Victoria Day', date: 'variable', notes: 'Monday before May 25' },
    { name: 'Canada Day', date: '07-01' },
    { name: 'Nunavut Day', date: '07-09' },
    { name: 'Civic Holiday', date: 'variable', notes: '1st Monday of August' },
    { name: 'Labour Day', date: 'variable', notes: '1st Monday of September' },
    { name: 'National Day for Truth and Reconciliation', date: '09-30' },
    { name: 'Thanksgiving Day', date: 'variable', notes: '2nd Monday of October' },
    { name: 'Remembrance Day', date: '11-11' },
    { name: 'Christmas Day', date: '12-25' },
  ],
};

/**
 * Get the number of statutory holidays for a jurisdiction.
 */
export function getStatutoryHolidayCount(jurisdiction: CanadianJurisdiction): number {
  return STATUTORY_HOLIDAYS[jurisdiction].length;
}
