# Generated by Django 5.1.4 on 2026-02-18 02:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Achievements",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("slug", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("icon_url", models.TextField(blank=True, null=True)),
                ("badge_image_url", models.TextField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Achievements",
                "db_table": "achievements",
            },
        ),
        migrations.CreateModel(
            name="ContentCategories",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("icon", models.CharField(blank=True, max_length=100, null=True)),
                ("parent_id", models.UUIDField(blank=True, null=True)),
                ("sort_order", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ContentCategories",
                "db_table": "content_categories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("thumbnail_url", models.TextField(blank=True, null=True)),
                ("cover_image_url", models.TextField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=dict, null=True)),
                ("instructor_id", models.UUIDField(blank=True, null=True)),
                (
                    "estimated_duration_minutes",
                    models.IntegerField(blank=True, null=True),
                ),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "required_tier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("free", "Free"),
                            ("professional", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("completion_badge_id", models.UUIDField(blank=True, null=True)),
                ("meta_description", models.TextField(blank=True, null=True)),
                ("completions_count", models.IntegerField(blank=True, null=True)),
                (
                    "average_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("total_reviews", models.IntegerField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Courses",
                "db_table": "courses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LearningStreaks",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("current_streak_start_date", models.DateField(blank=True, null=True)),
                ("last_activity_date", models.DateField(blank=True, null=True)),
                ("longest_streak_start_date", models.DateField(blank=True, null=True)),
                ("longest_streak_end_date", models.DateField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "LearningStreaks",
                "db_table": "learning_streaks",
            },
        ),
        migrations.CreateModel(
            name="QuizAttempts",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("quiz_id", models.UUIDField(blank=True, null=True)),
                ("enrollment_id", models.UUIDField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="in_progress",
                        max_length=50,
                    ),
                ),
                ("total_questions", models.IntegerField(blank=True, null=True)),
                ("correct_answers", models.IntegerField(blank=True, null=True)),
                ("passed", models.BooleanField(default=False)),
                ("time_spent_seconds", models.IntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "QuizAttempts",
                "db_table": "quiz_attempts",
            },
        ),
        migrations.CreateModel(
            name="Quizzes",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("lesson_id", models.UUIDField(blank=True, null=True)),
                ("course_id", models.UUIDField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("time_limit_minutes", models.IntegerField(blank=True, null=True)),
                ("max_attempts", models.IntegerField(blank=True, null=True)),
                ("randomize_questions", models.BooleanField(default=False)),
                ("show_correct_answers", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Quizzes",
                "db_table": "quizzes",
            },
        ),
        migrations.CreateModel(
            name="Testimonials",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role", models.CharField(max_length=100)),
                ("organization", models.CharField(max_length=150)),
                ("content", models.TextField(blank=True, null=True)),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("active", models.BooleanField(default=False)),
                ("display_order", models.IntegerField(blank=True, null=True)),
                ("linkedin_url", models.TextField(blank=True, null=True)),
                ("case_study_url", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Testimonials",
                "db_table": "testimonials",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TribunalCases",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("case_title", models.TextField(blank=True, null=True)),
                ("citation", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "tribunal_province",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("decision_date", models.DateField(blank=True, null=True)),
                ("filing_date", models.DateField(blank=True, null=True)),
                ("respondent", models.TextField(blank=True, null=True)),
                ("full_text", models.TextField(blank=True, null=True)),
                ("decision", models.TextField(blank=True, null=True)),
                (
                    "subcategories",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("key_issues", models.JSONField(blank=True, default=dict, null=True)),
                ("remedies", models.JSONField(blank=True, default=dict, null=True)),
                ("outcomes", models.JSONField(blank=True, default=dict, null=True)),
                ("cases_cited", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "ai_key_phrases",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "ai_sentiment",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("pdf_url", models.TextField(blank=True, null=True)),
                (
                    "document_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[("en", "En"), ("fr", "Fr")],
                        default="en",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=dict, null=True)),
                ("bookmarks_count", models.IntegerField(blank=True, null=True)),
                ("last_scraped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "scraper_version",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "TribunalCases",
                "db_table": "tribunal_cases",
            },
        ),
        migrations.CreateModel(
            name="UserPoints",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
                (
                    "bonus_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "UserPoints",
                "db_table": "user_points",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Bookmarks",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resource_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("resource_id", models.UUIDField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=dict, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Bookmarks",
                "db_table": "bookmarks",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_id", "resource_type", "resource_id"),
                        name="unique_bookmarks_user_id_resource_type_resource_id",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CourseReviews",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("course_id", models.UUIDField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("review_text", models.TextField(blank=True, null=True)),
                ("is_verified_purchase", models.BooleanField(default=False)),
                ("moderated_by", models.UUIDField(blank=True, null=True)),
                ("moderation_notes", models.TextField(blank=True, null=True)),
                ("unhelpful_count", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "CourseReviews",
                "db_table": "course_reviews",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_id", "course_id"),
                        name="unique_course_reviews_user_id_course_id",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Enrollments",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("course_id", models.UUIDField(blank=True, null=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
                (
                    "progress_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("completion_time_minutes", models.IntegerField(blank=True, null=True)),
                ("certificate_issued_at", models.DateTimeField(blank=True, null=True)),
                ("current_lesson_id", models.UUIDField(blank=True, null=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Enrollments",
                "db_table": "enrollments",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_id", "course_id"),
                        name="unique_enrollments_user_id_course_id",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("lesson_id", models.UUIDField(blank=True, null=True)),
                ("course_id", models.UUIDField(blank=True, null=True)),
                ("enrollment_id", models.UUIDField(blank=True, null=True)),
                (
                    "progress_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "video_watched_duration_seconds",
                    models.IntegerField(blank=True, null=True),
                ),
                ("time_spent_seconds", models.IntegerField(blank=True, null=True)),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
                ("access_count", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "LessonProgress",
                "db_table": "lesson_progress",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_id", "lesson_id"),
                        name="unique_lesson_progress_user_id_lesson_id",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Lessons",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("course_id", models.UUIDField(blank=True, null=True)),
                ("slug", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("content_url", models.TextField(blank=True, null=True)),
                ("article", models.TextField(blank=True, null=True)),
                (
                    "video_provider",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("thumbnail_url", models.TextField(blank=True, null=True)),
                (
                    "estimated_read_time_minutes",
                    models.IntegerField(blank=True, null=True),
                ),
                ("lesson_number", models.IntegerField(blank=True, null=True)),
                ("sort_order", models.IntegerField(blank=True, null=True)),
                ("is_preview", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Lessons",
                "db_table": "lessons",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("course_id", "slug"),
                        name="unique_lessons_course_id_slug",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserAchievements",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("achievement_id", models.UUIDField(blank=True, null=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
                ("points_awarded", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "UserAchievements",
                "db_table": "user_achievements",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_id", "achievement_id"),
                        name="unique_user_achievements_user_id_achievement_id",
                    )
                ],
            },
        ),
    ]
