# Generated by Django 5.1.4 on 2026-02-18 02:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AutomatedTrainingConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_enabled", models.BooleanField(default=False)),
                ("schedule_day_of_week", models.IntegerField(blank=True, null=True)),
                ("schedule_hour", models.IntegerField(blank=True, null=True)),
                (
                    "hyperparameters",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "min_validation_accuracy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=0.85,
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_run_job_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "AutomatedTrainingConfig",
                "db_table": "automated_training_config",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseEmbeddings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("case_id", models.UUIDField(blank=True, null=True)),
                ("embedding_type", models.CharField(max_length=50)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "CaseEmbeddings",
                "db_table": "case_embeddings",
            },
        ),
        migrations.CreateModel(
            name="ClassificationFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("case_title", models.TextField(blank=True, null=True)),
                ("case_text_excerpt", models.TextField(blank=True, null=True)),
                ("reviewed_by", models.UUIDField(blank=True, null=True)),
                ("reviewed_date", models.DateTimeField(blank=True, null=True)),
                ("training_batch_id", models.UUIDField(blank=True, null=True)),
                ("but", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ClassificationFeedback",
                "db_table": "classification_feedback",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseEmbeddings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("course_id", models.UUIDField(blank=True, null=True)),
                ("embedding_type", models.CharField(max_length=50)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "CourseEmbeddings",
                "db_table": "course_embeddings",
            },
        ),
        migrations.CreateModel(
            name="EmbeddingJobs",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed_items", models.IntegerField(blank=True, null=True)),
                ("failed_items", models.IntegerField(blank=True, null=True)),
                ("batch_size", models.IntegerField(blank=True, null=True)),
                ("metrics", models.JSONField(blank=True, default=dict, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "EmbeddingJobs",
                "db_table": "embedding_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingJobs",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.TextField(blank=True, null=True)),
                ("provider_job_id", models.TextField(blank=True, null=True)),
                ("fine_tuned_model", models.TextField(blank=True, null=True)),
                ("feedback_ids", models.UUIDField()),
                ("training_data_url", models.TextField(blank=True, null=True)),
                ("validation_data_url", models.TextField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("training_log", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "validation_metrics",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("deployed_at", models.DateTimeField(blank=True, null=True)),
                ("deployed_by", models.UUIDField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "TrainingJobs",
                "db_table": "training_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LessonEmbeddings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("lesson_id", models.UUIDField(blank=True, null=True)),
                ("embedding_type", models.CharField(max_length=50)),
                ("token_count", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "LessonEmbeddings",
                "db_table": "lesson_embeddings",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("lesson_id", "embedding_type"),
                        name="unique_lesson_embeddings_lesson_id_embedding_type",
                    )
                ],
            },
        ),
    ]
