#!/usr/bin/env node
/**
 * Cognition Engine Scaffolder
 *
 * Generates a governance-safe, explainability-first engine skeleton on top
 * of @nzila/institutional-cognition-core. Prevents future cognition drift
 * by making the canonical pattern the path of least resistance.
 *
 * Usage:
 *   pnpm tsx tooling/scripts/scaffold-cognition-engine.ts \
 *     --id my-engine \
 *     --domain governance \
 *     --app apps/union-eyes \
 *     --description "Surfaces governance momentum signals."
 */

import { mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { join, resolve } from 'node:path';
import {
  COGNITION_DOMAINS,
  type CognitionDomain,
} from '../../packages/institutional-cognition-core/src/ontology/index.js';

interface Args {
  id: string;
  domain: CognitionDomain;
  app: string;
  description: string;
}

function parseArgs(): Args {
  const argv = process.argv.slice(2);
  const get = (k: string): string | undefined => {
    const m = argv.find((a) => a.startsWith(`--${k}=`));
    if (m) return m.replace(`--${k}=`, '');
    const idx = argv.indexOf(`--${k}`);
    return idx >= 0 ? argv[idx + 1] : undefined;
  };
  const id = get('id');
  const domain = get('domain') as CognitionDomain | undefined;
  const app = get('app') ?? 'apps/union-eyes';
  const description = get('description') ?? 'Cognition engine scaffold.';
  if (!id || !/^[a-z][a-z0-9-]*$/.test(id)) {
    fail('--id is required and must be kebab-case.');
  }
  if (!domain || !(COGNITION_DOMAINS as readonly string[]).includes(domain)) {
    fail(
      `--domain is required and must be one of: ${COGNITION_DOMAINS.join(', ')}`,
    );
  }
  return { id: id!, domain: domain!, app, description };
}

function fail(msg: string): never {
  console.error(`[scaffold-cognition-engine] ${msg}`);
  process.exit(2);
}

function pascal(id: string): string {
  return id
    .split('-')
    .map((p) => p[0]!.toUpperCase() + p.slice(1))
    .join('');
}

function camel(id: string): string {
  const p = pascal(id);
  return p[0]!.toLowerCase() + p.slice(1);
}

function main(): void {
  const args = parseArgs();
  const appRoot = resolve(process.cwd(), args.app);
  if (!existsSync(appRoot)) fail(`app not found: ${appRoot}`);

  const enginesDir = join(appRoot, 'lib', 'cognition-engines');
  mkdirSync(enginesDir, { recursive: true });
  const enginePath = join(enginesDir, `${args.id}.ts`);
  if (existsSync(enginePath)) fail(`engine already exists: ${enginePath}`);

  const fnName = camel(args.id) + 'Engine';
  const className = pascal(args.id);

  const engineSrc = `/**
 * ${className} Cognition Engine
 *
 * ${args.description}
 *
 * Generated by tooling/scripts/scaffold-cognition-engine.ts.
 * Built on @nzila/institutional-cognition-core — the canonical institutional
 * cognition substrate. NEVER bypass the kernel; NEVER redeclare envelopes.
 */

import {
  COGNITION_CONTRACT_VERSION,
  defineCognitionEngine,
  type EvidenceItem,
  type ReasoningStep,
  type ContinuityAssumption,
  type GovernanceImplication,
  type InstitutionalExplainabilityEnvelope,
} from '@nzila/institutional-cognition-core';

export interface ${className}Payload {
  // Domain-specific cognition output. Replace the placeholder fields.
  summary: string;
  signalCount: number;
}

export const ${fnName}: (
  organizationId: string,
) => Promise<InstitutionalExplainabilityEnvelope<${className}Payload>> = defineCognitionEngine<${className}Payload>({
  engineId: '${args.id}',
  engineVersion: '0.1.0',
  domain: '${args.domain}',
  async compute(organizationId: string) {
    // TODO: replace with real cognition. Read organizationally-scoped data
    // ONLY (no individual-level observation). Build evidence + reasoning.
    const evidence: EvidenceItem[] = [];
    const reasoning: ReasoningStep[] = [];
    const assumptions: ContinuityAssumption[] = [];
    const governanceImplications: GovernanceImplication[] = [];

    return {
      payload: {
        summary: \`No signals computed yet for organization \${organizationId}.\`,
        signalCount: 0,
      },
      confidenceScore: 0,
      evidence,
      reasoning,
      assumptions,
      governanceImplications,
      interpretationGuidance:
        '${className} engine scaffold. Replace compute() with real cognition before relying on this envelope.',
    };
  },
});
`;

  writeFileSync(enginePath, engineSrc);

  const next = [
    `1. Edit ${enginePath} and implement compute().`,
    `2. Register the engine in the appropriate kernel-bridge file (apps/union-eyes/lib/institutional-operating-intelligence/kernel-bridge*.ts).`,
    `3. (Optional) Expose it via a route by writing: export const GET = cognitionRoute(${fnName});`,
    `4. Run: pnpm --filter @nzila/union-eyes typecheck`,
    `5. Run: pnpm tsx tooling/governance/cognition-governance-ci.ts`,
  ].join('\n   ');

  console.log(`[scaffold-cognition-engine] created ${enginePath}`);
  console.log(`   ${next}`);
}

main();
