import type { Metadata } from 'next';
import ScrollReveal from '@/components/public/scroll-reveal';

export const metadata: Metadata = {
  title: 'Royalty Policy — Zonga',
  description: 'How royalties are calculated, split, and paid out on the Zonga platform.',
};

export default function RoyaltyPolicyPage() {
  return (
    <main className="min-h-screen">
      <section className="relative py-32 bg-navy overflow-hidden">
        <div className="absolute inset-0 bg-mesh opacity-40" />
        <div className="relative z-10 max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <ScrollReveal>
            <h1 className="text-4xl md:text-5xl font-bold text-white mb-4">Royalty Policy</h1>
            <p className="text-gray-400">Last updated: March 20, 2026</p>
          </ScrollReveal>
        </div>
      </section>

      <section className="py-16 bg-white">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 prose prose-gray prose-headings:text-navy">
          <ScrollReveal>
            <h2>1. Revenue Model</h2>
            <p>
              Zonga operates on an <strong>85/15 revenue share</strong> — creators and rights holders receive 85% of net revenue generated by their content. Zonga retains 15% as a platform fee to cover infrastructure, support, and development costs.
            </p>

            <h2>2. Revenue Sources</h2>
            <p>Revenue is generated through the following channels:</p>
            <ul>
              <li><strong>Streams</strong> — per-play royalties based on platform-wide revenue pools</li>
              <li><strong>Downloads</strong> — direct purchase revenue for downloadable content</li>
              <li><strong>Tips</strong> — voluntary contributions from listeners to creators</li>
              <li><strong>Subscription Share</strong> — proportional allocation from subscriber revenue</li>
              <li><strong>Ticket Sales</strong> — event ticket revenue (5% platform fee on ticket sales)</li>
              <li><strong>Sync Licensing</strong> — revenue from licensed use of content in media</li>
            </ul>

            <h2>3. Royalty Splits</h2>
            <p>
              Releases with multiple contributors support configurable royalty splits. Each collaborator&apos;s share is defined as a percentage at the release level. Splits must total 100%. All parties can view the split configuration in their dashboard.
            </p>

            <h2>4. Calculation & Reporting</h2>
            <p>
              Revenue events are recorded in real-time in an append-only ledger. Each event captures the source, amount, currency, and associated asset. Creators can view detailed revenue breakdowns in the Revenue dashboard, including per-track and per-source reporting.
            </p>

            <h2>5. Payout Schedule</h2>
            <p>
              Payouts are processed on a monthly cycle. The payout period covers the previous calendar month. Previews are generated before payout execution, allowing creators to review amounts before disbursement.
            </p>

            <h2>6. Minimum Payout</h2>
            <p>
              The minimum payout threshold is <strong>$5 USD equivalent</strong>. Balances below this threshold roll over to the next payout cycle. There is no cap on maximum payout amounts.
            </p>

            <h2>7. Currency & Payment Rails</h2>
            <p>
              Revenue is tracked in the original transaction currency with USD as the base reporting currency. Payouts can be configured in the creator&apos;s preferred currency. Supported payment rails include bank transfer, mobile money, and integrated payment platforms.
            </p>

            <h2>8. Disputes & Adjustments</h2>
            <p>
              If you believe a royalty calculation is incorrect, you may raise a dispute through the platform. Disputed amounts are held pending review. Adjustments are applied retroactively with full audit trail visibility in the wallet ledger.
            </p>

            <h2>9. Contact</h2>
            <p>
              For royalty-related questions, contact us at <a href="mailto:royalties@zonga.app">royalties@zonga.app</a>.
            </p>
          </ScrollReveal>
        </div>
      </section>
    </main>
  );
}
