import type { HealthcareSurveyTemplate } from '../types'

const now = new Date().toISOString()

export const UNIT_SCHEDULING_TEMPLATE: HealthcareSurveyTemplate = {
  id: 'template-unit-scheduling-experience-v1',
  key: 'unit-scheduling',
  title: 'Unit Scheduling Experience Survey',
  description:
    'Understand scheduling clarity, communication friction, documentation gaps, and the safest first workflow to explore on one unit.',
  intendedUse:
    'Capture unit-level scheduling pain, workflow friction, evidence gaps, adoption concerns, and pilot appetite before a workflow pilot.',
  estimatedMinutes: 5,
  category: 'healthcare-discovery',
  introText:
    'Thank you for taking a few minutes to complete this short survey.\n\nThe purpose of this survey is to better understand how nurses on this unit experience scheduling, schedule changes, open shifts, shift exchanges, communication, and documentation.\n\nThis is early discovery only. It is not a grievance form, not an employer audit, and not intended to collect patient information or confidential case details.\n\nPlease do not include patient names, employee names, manager names, or identifying details in your responses.\n\nYour feedback will help identify whether there are small, practical ways to improve scheduling clarity, transparency, and documentation support on this unit.',
  questions: [
    {
      id: 'q1',
      text: 'Overall, how clear is the current scheduling process on your unit?',
      type: 'rating_1_5',
      required: true,
      options: ['Very unclear', 'Somewhat unclear', 'Neutral', 'Somewhat clear', 'Very clear'],
      displayOrder: 1,
      mapsToWorkflow: 'scheduling_clarity',
      riskLevel: 'low',
      avoidIdentifyingDetails: true,
    },
    {
      id: 'q2',
      text: 'How confident are you that scheduling decisions are applied consistently?',
      type: 'rating_1_5',
      required: true,
      options: ['Not confident', 'Slightly confident', 'Neutral', 'Somewhat confident', 'Very confident'],
      displayOrder: 2,
      mapsToWorkflow: 'consistency_confidence',
      riskLevel: 'low',
      avoidIdentifyingDetails: true,
    },
    {
      id: 'q3',
      text: 'Which scheduling situations create the most confusion or friction on your unit? Select up to 5.',
      type: 'multiple_choice',
      required: true,
      maxSelections: 5,
      options: [
        'Short-notice schedule changes',
        'Open shift offers',
        'Skill mix / specialized coverage concerns',
        'Shift exchanges or swaps',
        'Communication delays',
        'Difficulty reconstructing what happened later',
        'Rest between shifts',
        'Night-to-day transitions',
        'Consecutive shifts',
        'Overtime distribution',
        'Unclear reasons for scheduling decisions',
        'Schedule changes after posting',
        'Seniority / order of offers',
        'Time-off requests',
        'Vacation scheduling',
        'Weekend distribution',
        'Lack of documentation',
        'Difficulty proving what happened later',
        'Other',
      ],
      displayOrder: 3,
      mapsToWorkflow: 'friction_areas',
      riskLevel: 'low',
      avoidIdentifyingDetails: true,
    },
    {
      id: 'q4',
      text: 'When a scheduling issue happens, what is usually hardest? Select up to 3.',
      type: 'multiple_choice',
      required: true,
      maxSelections: 3,
      options: [
        'Knowing what changed',
        'Knowing why it changed',
        'Knowing when it changed',
        'Knowing who was offered a shift',
        'Knowing whether the process was followed',
        'Finding written proof',
        'Understanding whether it should be reviewed',
        'Knowing who to contact',
        'Reconstructing the timeline later',
        'Other',
      ],
      displayOrder: 4,
      mapsToWorkflow: 'evidence_gap',
      riskLevel: 'low',
      avoidIdentifyingDetails: true,
    },
    {
      id: 'q5',
      text: 'How easy is it to reconstruct what happened after a scheduling issue?',
      type: 'rating_1_5',
      required: true,
      options: ['Very difficult', 'Somewhat difficult', 'Neutral', 'Somewhat easy', 'Very easy'],
      displayOrder: 5,
      mapsToWorkflow: 'reconstruction_difficulty',
      riskLevel: 'low',
      avoidIdentifyingDetails: true,
    },
    {
      id: 'q6',
      text: 'How do you usually keep track of scheduling issues or changes?',
      type: 'multiple_choice',
      required: true,
      options: [
        'I do not usually track them',
        'Screenshot',
        'Email',
        'Text message',
        'Paper notes',
        'Calendar notes',
        'Personal notes app',
        'Ask a coworker',
        'Contact local rep / UNA',
        'Other',
      ],
      displayOrder: 6,
      mapsToWorkflow: 'current_tracking_methods',
      riskLevel: 'low',
      avoidIdentifyingDetails: true,
    },
    {
      id: 'q7',
      text: 'How useful would it be to have a clearer before/after record when a posted schedule changes?',
      helperText:
        'Example: original shift, changed shift, date changed, notice window, and reason.',
      type: 'rating_1_5',
      required: true,
      displayOrder: 7,
      mapsToWorkflow: 'schedule_change_tracking',
      riskLevel: 'low',
      avoidIdentifyingDetails: true,
    },
    {
      id: 'q8',
      text: 'How useful would it be to have a clearer record of how open shifts are offered?',
      helperText:
        'Example: when the shift opened, who was eligible, who was offered, who accepted/declined, and when the shift was filled.',
      type: 'rating_1_5',
      required: true,
      displayOrder: 8,
      mapsToWorkflow: 'open_shift_transparency',
      riskLevel: 'low',
      avoidIdentifyingDetails: true,
    },
    {
      id: 'q9',
      text: 'How useful would it be to have a simple checklist for shift exchanges or swaps?',
      helperText:
        'Example: written agreement, approval, cost/overtime impact, orientation/qualification concerns, and rest-day impact.',
      type: 'rating_1_5',
      required: true,
      displayOrder: 9,
      mapsToWorkflow: 'shift_exchange_clarity',
      riskLevel: 'low',
      avoidIdentifyingDetails: true,
    },
    {
      id: 'q10',
      text: 'How useful would it be to receive a "review prompt" when a scheduling situation may need closer attention?',
      helperText:
        'Example: short-notice change, rest-period concern, consecutive shifts, missing schedule information, or unclear offer sequence.',
      type: 'rating_1_5',
      required: true,
      displayOrder: 10,
      mapsToWorkflow: 'agreement_review_prompts',
      riskLevel: 'low',
      avoidIdentifyingDetails: true,
    },
    {
      id: 'q11',
      text: 'How useful would it be to have a timeline of scheduling events if a question or concern came up later?',
      helperText:
        'Example: schedule posted, change made, open shift created, offer sent, response received, notes added, review requested.',
      type: 'rating_1_5',
      required: true,
      displayOrder: 11,
      mapsToWorkflow: 'evidence_timeline',
      riskLevel: 'low',
      avoidIdentifyingDetails: true,
    },
    {
      id: 'q12',
      text: 'If a scheduling concern needed to be reviewed, how useful would it be to have the related information gathered in one place?',
      helperText:
        'Example: timeline, original schedule, changed schedule, offer history, notes, and supporting documents.',
      type: 'rating_1_5',
      required: true,
      displayOrder: 12,
      mapsToWorkflow: 'evidence_packet',
      riskLevel: 'low',
      avoidIdentifyingDetails: true,
    },
    {
      id: 'q13',
      text: 'If only one scheduling area could be improved first on this unit, which should it be?',
      type: 'single_choice',
      required: true,
      options: [
        'Schedule change tracking',
        'Open shift offer transparency',
        'Shift exchange / swap process',
        'Time-off request visibility',
        'Review prompts for possible scheduling issues',
        'Timeline of scheduling events',
        'Gathering evidence for review',
        'Other',
      ],
      displayOrder: 13,
      mapsToWorkflow: 'first_pilot_wedge',
      riskLevel: 'low',
      avoidIdentifyingDetails: true,
    },
    {
      id: 'q14',
      text: 'Which two areas would be most useful together?',
      type: 'multiple_choice',
      required: true,
      maxSelections: 2,
      options: [
        'Schedule change tracking',
        'Open shift offer transparency',
        'Shift exchange / swap process',
        'Time-off request visibility',
        'Review prompts for possible scheduling issues',
        'Timeline of scheduling events',
        'Gathering evidence for review',
      ],
      displayOrder: 14,
      mapsToWorkflow: 'paired_workflow_signal',
      riskLevel: 'low',
      avoidIdentifyingDetails: true,
    },
    {
      id: 'q15',
      text: 'What concerns would you have about a scheduling-support tool or process? Select all that apply.',
      type: 'multiple_choice',
      required: true,
      options: [
        'Privacy',
        'Being identified',
        'Employer access',
        'Data accuracy',
        'Misinterpretation of the collective agreement',
        'Tool being used for discipline',
        'Extra workload',
        'Not enough trust in the data',
        'It may not reflect real unit complexity',
        'No concerns',
        'Other',
      ],
      displayOrder: 15,
      mapsToWorkflow: 'adoption_concerns',
      riskLevel: 'medium',
      avoidIdentifyingDetails: true,
    },
    {
      id: 'q16',
      text: 'What would make scheduling support actually useful for nurses on this unit?',
      type: 'free_text',
      required: false,
      displayOrder: 16,
      mapsToWorkflow: 'qualitative_feedback',
      riskLevel: 'medium',
      warningText:
        'Please do not include names, patient details, manager names, grievance details, or identifying details.',
      avoidIdentifyingDetails: true,
    },
    {
      id: 'q17',
      text:
        'Are there any scheduling situations specific to a short-stay cardiology environment that create extra difficulty?',
      type: 'free_text',
      required: false,
      displayOrder: 17,
      mapsToWorkflow: 'unit_specific_context',
      riskLevel: 'medium',
      warningText:
        'Please do not include patient details, employee names, manager names, or identifying details.',
      avoidIdentifyingDetails: true,
    },
  ],
  createdAt: now,
  updatedAt: now,
}
