"""
Django models for grievances app.
Auto-generated by Nzila Code Generator — 2026-02-17

DO NOT EDIT manually unless you know what you're doing.
Re-run the generator to overwrite.
"""

import uuid

from django.contrib.postgres.fields import ArrayField
from django.contrib.postgres.search import SearchVectorField
from django.db import models

try:
    from pgvector.django import VectorField
except ImportError:
    VectorField = None  # pgvector not installed


class BaseModel(models.Model):
    """Abstract base with standard audit fields."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class OrganizationModel(BaseModel):
    """Abstract base for multi-organization models."""

    organization = models.ForeignKey(
        "auth_core.Organizations", on_delete=models.CASCADE, related_name="%(class)ss"
    )

    class Meta:
        abstract = True


class ClaimPrecedentAnalysis(BaseModel):
    """Migrated from drizzle: cba-intelligence-schema.ts"""

    claim_id = models.UUIDField()
    precedent_matches = models.JSONField(default=dict, null=True, blank=True)
    success_probability = models.DecimalField(
        max_digits=19, decimal_places=2, null=True, blank=True
    )

    class Meta:
        db_table = "claim_precedent_analysis"
        verbose_name = "ClaimPrecedentAnalysis"


class Claims(BaseModel):
    """Migrated from drizzle: claims-schema.ts — full field set"""

    CLAIM_STATUS_CHOICES = [
        ("submitted", "Submitted"),
        ("under_review", "Under Review"),
        ("assigned", "Assigned"),
        ("investigation", "Investigation"),
        ("pending_documentation", "Pending Documentation"),
        ("resolved", "Resolved"),
        ("rejected", "Rejected"),
        ("closed", "Closed"),
    ]

    CLAIM_PRIORITY_CHOICES = [
        ("low", "Low"),
        ("medium", "Medium"),
        ("high", "High"),
        ("critical", "Critical"),
    ]

    CLAIM_TYPE_CHOICES = [
        ("grievance_discipline", "Grievance — Discipline"),
        ("grievance_schedule", "Grievance — Schedule"),
        ("grievance_pay", "Grievance — Pay"),
        ("workplace_safety", "Workplace Safety"),
        ("discrimination_age", "Discrimination — Age"),
        ("discrimination_gender", "Discrimination — Gender"),
        ("discrimination_race", "Discrimination — Race"),
        ("discrimination_disability", "Discrimination — Disability"),
        ("discrimination_other", "Discrimination — Other"),
        ("harassment_sexual", "Harassment — Sexual"),
        ("harassment_workplace", "Harassment — Workplace"),
        ("harassment_verbal", "Harassment — Verbal"),
        ("harassment_physical", "Harassment — Physical"),
        ("wage_dispute", "Wage Dispute"),
        ("contract_dispute", "Contract Dispute"),
        ("retaliation", "Retaliation"),
        ("wrongful_termination", "Wrongful Termination"),
        ("other", "Other"),
    ]

    # Identity (legacy PK migrated to unique field)
    claim_id = models.UUIDField(default=uuid.uuid4, unique=True)
    claim_number = models.CharField(max_length=50, null=True, blank=True, unique=True)

    # Ownership
    organization_id = models.UUIDField(null=True, blank=True)
    member_id = models.TextField(null=True, blank=True)  # Clerk user ID
    is_anonymous = models.BooleanField(default=True)

    # Type & State
    claim_type = models.CharField(
        max_length=50, choices=CLAIM_TYPE_CHOICES, null=True, blank=True
    )
    status = models.CharField(
        max_length=30, choices=CLAIM_STATUS_CHOICES, default="submitted"
    )
    priority = models.CharField(
        max_length=10, choices=CLAIM_PRIORITY_CHOICES, default="medium"
    )

    # Incident
    incident_date = models.DateTimeField(null=True, blank=True)
    location = models.TextField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    desired_outcome = models.TextField(null=True, blank=True)

    # Witnesses / Prior Reports
    witnesses_present = models.BooleanField(default=False)
    witness_details = models.TextField(null=True, blank=True)
    previously_reported = models.BooleanField(default=False)
    previous_report_details = models.TextField(null=True, blank=True)

    # Assignment
    assigned_to = models.CharField(max_length=255, null=True, blank=True)
    assigned_at = models.DateTimeField(null=True, blank=True)

    # AI Analysis
    ai_score = models.IntegerField(null=True, blank=True)
    ai_analysis = models.JSONField(default=dict, null=True, blank=True)
    merit_confidence = models.IntegerField(null=True, blank=True)
    precedent_match = models.IntegerField(null=True, blank=True)
    complexity_score = models.IntegerField(null=True, blank=True)

    # Progress
    progress = models.IntegerField(default=0)

    # Financials
    claim_amount = models.CharField(max_length=20, null=True, blank=True)
    settlement_amount = models.CharField(max_length=20, null=True, blank=True)
    legal_costs = models.CharField(max_length=20, null=True, blank=True)
    court_costs = models.CharField(max_length=20, null=True, blank=True)

    # Resolution
    resolution_outcome = models.CharField(max_length=100, null=True, blank=True)
    filed_date = models.DateTimeField(null=True, blank=True)
    resolved_at = models.DateTimeField(null=True, blank=True)
    closed_at = models.DateTimeField(null=True, blank=True)

    # Attachments / Voice
    attachments = models.JSONField(default=list, null=True, blank=True)
    voice_transcriptions = models.JSONField(default=list, null=True, blank=True)

    # Metadata
    metadata = models.JSONField(default=dict, null=True, blank=True)

    class Meta:
        db_table = "claims"
        verbose_name = "Claims"
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["organization_id"], name="idx_claims_org"),
            models.Index(fields=["member_id"], name="idx_claims_member"),
            models.Index(fields=["status"], name="idx_claims_status"),
        ]

    def __str__(self):
        return str(self.claim_number)


class ClaimUpdates(BaseModel):
    """Migrated from drizzle: claims-schema.ts"""

    update_id = models.UUIDField(default=uuid.uuid4, unique=True)
    claim = models.ForeignKey(
        "Claims", on_delete=models.CASCADE, related_name="claim_updates_claim_set"
    )

    class Meta:
        db_table = "claim_updates"
        verbose_name = "ClaimUpdates"


class DeadlineRules(BaseModel):
    """Canonical model for deadline_rules table.
    Defines grievance-processing deadline templates per org."""

    organization_id = models.UUIDField(null=True, blank=True)
    rule_name = models.CharField(max_length=255, null=True, blank=True)
    rule_code = models.CharField(max_length=100, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    claim_type = models.CharField(max_length=100, null=True, blank=True)
    priority_level = models.CharField(max_length=50, null=True, blank=True)
    step_number = models.IntegerField(null=True, blank=True)
    days_from_event = models.IntegerField(null=True, blank=True)
    event_type = models.CharField(max_length=100, default="", blank=True)
    business_days_only = models.BooleanField(default=False)
    allows_extension = models.BooleanField(default=False)
    max_extension_days = models.IntegerField(default=0)
    requires_approval = models.BooleanField(default=False)
    escalate_to_role = models.CharField(max_length=255, null=True, blank=True)
    escalation_delay_days = models.IntegerField(default=0)
    is_active = models.BooleanField(default=False)
    is_system_rule = models.BooleanField(default=False)
    created_by = models.TextField(null=True, blank=True)

    class Meta:
        db_table = "deadline_rules"
        verbose_name = "DeadlineRules"


class ClaimDeadlines(BaseModel):
    """Canonical model for claim_deadlines table.
    Tracks individual deadline instances linked to claims."""

    claim_id = models.UUIDField()
    organization_id = models.UUIDField(null=True, blank=True)
    deadline_rule_id = models.UUIDField(null=True, blank=True)
    deadline_name = models.CharField(max_length=255, null=True, blank=True)
    deadline_type = models.CharField(max_length=100, null=True, blank=True)
    event_date = models.DateTimeField(null=True, blank=True)
    original_deadline = models.DateTimeField(null=True, blank=True)
    due_date = models.DateTimeField(null=True, blank=True)
    completed_at = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=20, default="pending")
    priority = models.CharField(max_length=20, default="medium")
    extension_count = models.IntegerField(default=0)
    total_extension_days = models.IntegerField(default=0)
    last_extension_date = models.DateTimeField(null=True, blank=True)
    last_extension_reason = models.TextField(null=True, blank=True)
    completed_by = models.CharField(max_length=255, null=True, blank=True)
    completion_notes = models.TextField(null=True, blank=True)
    is_overdue = models.BooleanField(default=False)
    days_until_due = models.IntegerField(null=True, blank=True)
    days_overdue = models.IntegerField(default=0)
    escalated_at = models.DateTimeField(null=True, blank=True)
    escalated_to = models.CharField(max_length=255, null=True, blank=True)
    alert_count = models.IntegerField(default=0)
    last_alert_sent = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = "claim_deadlines"
        verbose_name = "ClaimDeadlines"
        indexes = [
            models.Index(fields=["organization_id"], name="idx_claim_deadlines_org"),
            models.Index(fields=["status"], name="idx_claim_deadlines_status"),
        ]


class DeadlineExtensions(BaseModel):
    """Migrated from drizzle: deadlines-schema.ts"""

    deadline_id = models.UUIDField()
    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = "deadline_extensions"
        verbose_name = "DeadlineExtensions"


class DeadlineAlerts(BaseModel):
    """Migrated from drizzle: deadlines-schema.ts"""

    deadline_id = models.UUIDField()
    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = "deadline_alerts"
        verbose_name = "DeadlineAlerts"


class DefensibilityPacks(BaseModel):
    """Migrated from drizzle: defensibility-packs-schema.ts"""

    pack_id = models.UUIDField(default=uuid.uuid4, unique=True)
    case_id = models.UUIDField()
    case_number = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        db_table = "defensibility_packs"
        verbose_name = "DefensibilityPacks"


class PackDownloadLog(BaseModel):
    """Migrated from drizzle: defensibility-packs-schema.ts"""

    log_id = models.UUIDField(default=uuid.uuid4, unique=True)
    pack_id = models.UUIDField()
    case_number = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        db_table = "pack_download_log"
        verbose_name = "PackDownloadLog"


class PackVerificationLog(BaseModel):
    """Migrated from drizzle: defensibility-packs-schema.ts"""

    verification_id = models.UUIDField(default=uuid.uuid4, unique=True)
    pack_id = models.UUIDField()
    case_number = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        db_table = "pack_verification_log"
        verbose_name = "PackVerificationLog"


class Grievances(BaseModel):
    """Migrated from drizzle: grievance-schema.ts — full field set"""

    GRIEVANCE_TYPE_CHOICES = [
        ("individual", "Individual"),
        ("group", "Group"),
        ("policy", "Policy"),
        ("contract", "Contract"),
        ("harassment", "Harassment"),
        ("discrimination", "Discrimination"),
        ("safety", "Safety"),
        ("seniority", "Seniority"),
        ("discipline", "Discipline"),
        ("termination", "Termination"),
        ("other", "Other"),
    ]

    GRIEVANCE_STATUS_CHOICES = [
        ("draft", "Draft"),
        ("filed", "Filed"),
        ("acknowledged", "Acknowledged"),
        ("investigating", "Investigating"),
        ("response_due", "Response Due"),
        ("response_received", "Response Received"),
        ("escalated", "Escalated"),
        ("mediation", "Mediation"),
        ("arbitration", "Arbitration"),
        ("settled", "Settled"),
        ("withdrawn", "Withdrawn"),
        ("denied", "Denied"),
        ("closed", "Closed"),
    ]

    GRIEVANCE_PRIORITY_CHOICES = [
        ("low", "Low"),
        ("medium", "Medium"),
        ("high", "High"),
        ("urgent", "Urgent"),
    ]

    GRIEVANCE_STEP_CHOICES = [
        ("step_1", "Step 1"),
        ("step_2", "Step 2"),
        ("step_3", "Step 3"),
        ("final", "Final"),
        ("arbitration", "Arbitration"),
    ]

    # Identity
    grievance_number = models.CharField(
        max_length=50, null=True, blank=True, unique=True
    )

    # Classification
    type = models.CharField(
        max_length=20, choices=GRIEVANCE_TYPE_CHOICES, null=True, blank=True
    )
    status = models.CharField(
        max_length=20, choices=GRIEVANCE_STATUS_CHOICES, default="draft"
    )
    priority = models.CharField(
        max_length=10, choices=GRIEVANCE_PRIORITY_CHOICES, default="medium"
    )
    step = models.CharField(
        max_length=15, choices=GRIEVANCE_STEP_CHOICES, null=True, blank=True
    )

    # Parties
    grievant_id = models.UUIDField(null=True, blank=True)
    grievant_name = models.CharField(max_length=255, null=True, blank=True)
    grievant_email = models.CharField(max_length=255, null=True, blank=True)
    union_rep_id = models.UUIDField(null=True, blank=True)
    employer_rep_id = models.CharField(max_length=255, null=True, blank=True)

    # Employer/Organization
    employer_id = models.UUIDField(null=True, blank=True)
    employer_name = models.CharField(max_length=255, null=True, blank=True)
    workplace_id = models.UUIDField(null=True, blank=True)
    workplace_name = models.CharField(max_length=255, null=True, blank=True)

    # CBA Reference
    cba_id = models.UUIDField(null=True, blank=True)
    cba_article = models.CharField(max_length=100, null=True, blank=True)
    cba_section = models.CharField(max_length=100, null=True, blank=True)

    # Details
    title = models.CharField(max_length=500, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    background = models.TextField(null=True, blank=True)
    desired_outcome = models.TextField(null=True, blank=True)

    # Dates
    incident_date = models.DateTimeField(null=True, blank=True)
    filed_date = models.DateTimeField(null=True, blank=True)
    response_deadline = models.DateTimeField(null=True, blank=True)
    meeting_date = models.DateTimeField(null=True, blank=True)
    escalated_at = models.DateTimeField(null=True, blank=True)
    resolved_at = models.DateTimeField(null=True, blank=True)
    closed_at = models.DateTimeField(null=True, blank=True)

    # Timeline & Attachments (JSON)
    timeline = models.JSONField(default=list, null=True, blank=True)
    attachments = models.JSONField(default=list, null=True, blank=True)

    # Related Records
    group_grievance_id = models.UUIDField(null=True, blank=True)
    related_grievance_ids = models.JSONField(default=list, null=True, blank=True)

    # Flags
    is_group_grievance = models.BooleanField(default=False)
    is_arbitration_eligible = models.BooleanField(default=False)
    has_legal_implications = models.BooleanField(default=False)
    is_confidential = models.BooleanField(default=False)

    # Ownership
    organization_id = models.UUIDField(null=True, blank=True)
    created_by = models.UUIDField(null=True, blank=True)
    last_updated_by = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = "grievances"
        verbose_name = "Grievances"
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["organization_id"], name="idx_grievances_org"),
            models.Index(fields=["status"], name="idx_grievances_status"),
            models.Index(fields=["grievant_id"], name="idx_grievances_grievant"),
            models.Index(fields=["response_deadline"], name="idx_grievances_deadline"),
        ]

    def __str__(self):
        return str(self.grievance_number)


class GrievanceResponses(BaseModel):
    """Migrated from drizzle: grievances.ts"""

    grievance = models.ForeignKey(
        "Grievances",
        on_delete=models.CASCADE,
        related_name="grievance_responses_grievance_set",
    )
    response_number = models.IntegerField()
    responding_party = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        db_table = "grievance_responses"
        verbose_name = "GrievanceResponses"


class Arbitrations(BaseModel):
    """Migrated from drizzle: grievances.ts"""

    grievance = models.ForeignKey(
        "Grievances",
        on_delete=models.CASCADE,
        related_name="arbitrations_grievance_set",
    )
    arbitration_number = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        db_table = "arbitrations"
        verbose_name = "Arbitrations"


class Settlements(BaseModel):
    """Migrated from drizzle: grievances.ts"""

    SETTLEMENT_TYPE_CHOICES = [
        ("monetary", "Monetary"),
        ("non_monetary", "Non Monetary"),
        ("policy_change", "Policy Change"),
        (" reinstatement", " Reinstatement"),
        ("apology", "Apology"),
        ("training", "Training"),
        ("other", "Other"),
    ]

    grievance = models.ForeignKey(
        "Grievances", on_delete=models.CASCADE, related_name="settlements_grievance_set"
    )
    arbitration = models.ForeignKey(
        "Arbitrations",
        on_delete=models.CASCADE,
        related_name="settlements_arbitration_set",
        null=True,
        blank=True,
    )
    settlement_type = models.CharField(choices=SETTLEMENT_TYPE_CHOICES, max_length=24)
    status = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        db_table = "settlements"
        verbose_name = "Settlements"


class GrievanceTimeline(BaseModel):
    """Migrated from drizzle: grievances.ts"""

    grievance = models.ForeignKey(
        "Grievances",
        on_delete=models.CASCADE,
        related_name="grievance_timeline_grievance_set",
    )
    event_type = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        db_table = "grievance_timeline"
        verbose_name = "GrievanceTimeline"


class GrievanceDeadlines(BaseModel):
    """Migrated from drizzle: grievances.ts"""

    grievance = models.ForeignKey(
        "Grievances",
        on_delete=models.CASCADE,
        related_name="grievance_deadlines_grievance_set",
    )
    deadline_type = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        db_table = "grievance_deadlines"
        verbose_name = "GrievanceDeadlines"


class GrievanceWorkflows(BaseModel):
    """Migrated from drizzle: workflows.ts"""

    organization_id = models.UUIDField()
    name = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        db_table = "grievance_workflows"
        verbose_name = "GrievanceWorkflows"

    def __str__(self):
        return str(self.name)


class GrievanceStages(BaseModel):
    """Migrated from drizzle: workflows.ts"""

    organization_id = models.UUIDField()
    workflow = models.ForeignKey(
        "GrievanceWorkflows",
        on_delete=models.CASCADE,
        related_name="grievance_stages_workflow_set",
        null=True,
        blank=True,
    )

    class Meta:
        db_table = "grievance_stages"
        verbose_name = "GrievanceStages"


class GrievanceTransitions(BaseModel):
    """Migrated from drizzle: workflows.ts"""

    organization_id = models.UUIDField()
    claim = models.ForeignKey(
        "Claims",
        on_delete=models.CASCADE,
        related_name="grievance_transitions_claim_set",
    )
    from_stage = models.ForeignKey(
        "GrievanceStages",
        on_delete=models.CASCADE,
        related_name="grievance_transitions_from_stage_set",
        null=True,
        blank=True,
    )
    to_stage = models.ForeignKey(
        "GrievanceStages",
        on_delete=models.CASCADE,
        related_name="grievance_transitions_to_stage_set",
    )
    trigger_type = models.TextField()
    reason = models.TextField(null=True, blank=True)
    notes = models.TextField(null=True, blank=True)
    transitioned_by = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        db_table = "grievance_transitions"
        verbose_name = "GrievanceTransitions"


class GrievanceAssignments(BaseModel):
    """Migrated from drizzle: workflows.ts"""

    organization_id = models.UUIDField()
    claim = models.ForeignKey(
        "Claims",
        on_delete=models.CASCADE,
        related_name="grievance_assignments_claim_set",
    )
    assigned_to = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        db_table = "grievance_assignments"
        verbose_name = "GrievanceAssignments"


class GrievanceDocuments(BaseModel):
    """Migrated from drizzle: workflows.ts"""

    organization_id = models.UUIDField()
    claim = models.ForeignKey(
        "Claims", on_delete=models.CASCADE, related_name="grievance_documents_claim_set"
    )
    document_name = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        db_table = "grievance_documents"
        verbose_name = "GrievanceDocuments"


class GrievanceSettlements(BaseModel):
    """Migrated from drizzle: workflows.ts"""

    organization_id = models.UUIDField()
    claim = models.ForeignKey(
        "Claims",
        on_delete=models.CASCADE,
        related_name="grievance_settlements_claim_set",
    )
    settlement_type = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        db_table = "grievance_settlements"
        verbose_name = "GrievanceSettlements"


class GrievanceCommunications(BaseModel):
    """Migrated from drizzle: workflows.ts"""

    organization_id = models.UUIDField()
    claim = models.ForeignKey(
        "Claims",
        on_delete=models.CASCADE,
        related_name="grievance_communications_claim_set",
    )
    communication_type = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        db_table = "grievance_communications"
        verbose_name = "GrievanceCommunications"


class GrievanceApprovals(BaseModel):
    """Migrated from drizzle: workflows.ts"""

    organization_id = models.UUIDField()
    transition = models.ForeignKey(
        "GrievanceTransitions",
        on_delete=models.CASCADE,
        related_name="grievance_approvals_transition_set",
    )

    class Meta:
        db_table = "grievance_approvals"
        verbose_name = "GrievanceApprovals"
