import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

type CloudflareIpResponse = {
  success: boolean;
  errors: Array<{ code: number; message: string }>;
  result: {
    ipv4_cidrs: string[];
    ipv6_cidrs: string[];
    etag?: string;
  };
};

function buildFirewallScript(ipv4: string[], ipv6: string[]): string {
  const lines: string[] = [];

  lines.push('#!/usr/bin/env bash');
  lines.push('set -euo pipefail');
  lines.push('');
  lines.push('# Generated by scripts/dns/cloudflare-ips.ts');
  lines.push('# Allows Cloudflare proxy ranges to reach HTTP/HTTPS and drops other public traffic.');
  lines.push('# Review before applying in production, especially if you have trusted partner source ranges.');
  lines.push('');

  for (const cidr of ipv4) {
    lines.push(`iptables -I INPUT -p tcp -m multiport --dports http,https -s ${cidr} -j ACCEPT`);
  }

  for (const cidr of ipv6) {
    lines.push(`ip6tables -I INPUT -p tcp -m multiport --dports http,https -s ${cidr} -j ACCEPT`);
  }

  lines.push('');
  lines.push('# Optional hardening: drop all other HTTP/HTTPS sources after allow rules are in place.');
  lines.push('iptables -A INPUT -p tcp -m multiport --dports http,https -j DROP');
  lines.push('ip6tables -A INPUT -p tcp -m multiport --dports http,https -j DROP');

  return `${lines.join('\n')}\n`;
}

async function main() {
  const response = await fetch('https://api.cloudflare.com/client/v4/ips', {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
    },
  });

  if (!response.ok) {
    throw new Error(`Cloudflare IP API request failed: HTTP ${response.status}`);
  }

  const payload = (await response.json()) as CloudflareIpResponse;

  if (!payload.success) {
    const message = payload.errors.map((error) => `${error.code}:${error.message}`).join(', ');
    throw new Error(`Cloudflare IP API returned unsuccessful payload: ${message}`);
  }

  const reportDir = join(process.cwd(), 'reports', 'ops');
  mkdirSync(reportDir, { recursive: true });

  const reportPath = join(reportDir, 'cloudflare-ips.json');
  const scriptPath = join(reportDir, 'cloudflare-origin-firewall.sh');

  const report = {
    generatedAt: new Date().toISOString(),
    source: 'https://api.cloudflare.com/client/v4/ips',
    ipv4Cidrs: payload.result.ipv4_cidrs,
    ipv6Cidrs: payload.result.ipv6_cidrs,
    count: {
      ipv4: payload.result.ipv4_cidrs.length,
      ipv6: payload.result.ipv6_cidrs.length,
      total: payload.result.ipv4_cidrs.length + payload.result.ipv6_cidrs.length,
    },
  };

  writeFileSync(reportPath, `${JSON.stringify(report, null, 2)}\n`, 'utf8');
  writeFileSync(
    scriptPath,
    buildFirewallScript(payload.result.ipv4_cidrs, payload.result.ipv6_cidrs),
    'utf8',
  );

  console.log(`Wrote ${reportPath}`);
  console.log(`Wrote ${scriptPath}`);
  console.log(JSON.stringify(report, null, 2));
}

main().catch((error) => {
  const message = error instanceof Error ? error.message : String(error);
  console.error(JSON.stringify({ ok: false, error: message }, null, 2));
  process.exit(1);
});
