# Generated by Django 5.1.4 on 2026-02-18 02:15

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLogs",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
                ("changes", models.JSONField(blank=True, default=dict, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("request_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "AuditLogs",
                "db_table": "audit_logs",
            },
        ),
        migrations.CreateModel(
            name="Permissions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.CharField(max_length=100, unique=True)),
                ("resource", models.CharField(max_length=100)),
                ("is_system", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Permissions",
                "db_table": "permissions",
            },
        ),
        migrations.CreateModel(
            name="Profiles",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("avatar_url", models.TextField(blank=True, null=True)),
                ("department", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "employee_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("timezone", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "notification_preferences",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("email_verified", models.BooleanField(default=False)),
                ("onboarding_step", models.IntegerField(blank=True, null=True)),
                ("last_activity_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Profiles",
                "db_table": "profiles",
            },
        ),
        migrations.CreateModel(
            name="Roles",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("level", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Roles",
                "db_table": "roles",
            },
        ),
        migrations.CreateModel(
            name="Organizations",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("slug", models.TextField(unique=True)),
                ("display_name", models.TextField(blank=True, null=True)),
                ("short_name", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("domain", models.CharField(blank=True, max_length=255, null=True)),
                ("logo_url", models.TextField(blank=True, null=True)),
                (
                    "organization_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("congress", "Congress"),
                            ("federation", "Federation"),
                            ("union", "Union"),
                            ("local", "Local"),
                            ("region", "Region"),
                            ("district", "District"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "hierarchy_path",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        help_text="Array of ancestor organization IDs from root to this node",
                        size=None,
                    ),
                ),
                (
                    "hierarchy_level",
                    models.IntegerField(
                        default=0,
                        help_text="Distance from root (0 = root organization)",
                    ),
                ),
                ("province_territory", models.TextField(blank=True, null=True)),
                (
                    "sectors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("healthcare", "Healthcare"),
                                ("education", "Education"),
                                ("public_service", "Public Service"),
                                ("trades", "Trades"),
                                ("manufacturing", "Manufacturing"),
                                ("transportation", "Transportation"),
                                ("retail", "Retail"),
                                ("hospitality", "Hospitality"),
                                ("technology", "Technology"),
                                ("construction", "Construction"),
                                ("utilities", "Utilities"),
                                ("telecommunications", "Telecommunications"),
                                ("financial_services", "Financial Services"),
                                ("agriculture", "Agriculture"),
                                ("arts_culture", "Arts and Culture"),
                                ("other", "Other"),
                            ],
                            max_length=30,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("email", models.TextField(blank=True, null=True)),
                ("phone", models.TextField(blank=True, null=True)),
                ("website", models.TextField(blank=True, null=True)),
                (
                    "address",
                    models.JSONField(
                        blank=True,
                        help_text="Format: {street, unit, city, province, postal_code, country}",
                        null=True,
                    ),
                ),
                (
                    "clc_affiliated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether affiliated with Canadian Labour Congress",
                    ),
                ),
                ("affiliation_date", models.DateField(blank=True, null=True)),
                ("charter_number", models.TextField(blank=True, null=True)),
                ("member_count", models.IntegerField(default=0)),
                ("active_member_count", models.IntegerField(default=0)),
                (
                    "last_member_count_update",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("subscription_tier", models.TextField(blank=True, null=True)),
                (
                    "subscription_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("past_due", "Past Due"),
                            ("suspended", "Suspended"),
                            ("trialing", "Trialing"),
                        ],
                        default="active",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "subscription_start_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("subscription_end_date", models.DateTimeField(blank=True, null=True)),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "billing_email",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("billing_contact_id", models.UUIDField(blank=True, null=True)),
                ("storage_limit_gb", models.IntegerField(blank=True, null=True)),
                (
                    "settings",
                    models.JSONField(
                        default=dict,
                        help_text="Flexible config: {perCapitaRate, remittanceDay, fiscalYearEnd, customFields}",
                    ),
                ),
                (
                    "features_enabled",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                (
                    "legacy_tenant_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Original tenant_id from legacy system",
                        null=True,
                    ),
                ),
                (
                    "clc_affiliate_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "per_capita_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Default per-capita rate for remittances",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "remittance_day",
                    models.IntegerField(
                        blank=True,
                        default=15,
                        help_text="Day of month for remittances (1-31)",
                        null=True,
                    ),
                ),
                ("last_remittance_date", models.DateTimeField(blank=True, null=True)),
                (
                    "fiscal_year_end",
                    models.DateField(blank=True, help_text="e.g., March 31", null=True),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_id",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="children",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "db_table": "organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationRelationships",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("affiliate", "Affiliate"),
                            ("federation", "Federation"),
                            ("local", "Local"),
                            ("chapter", "Chapter"),
                            ("region", "Region"),
                            ("district", "District"),
                            ("joint_council", "Joint Council"),
                            ("merged_from", "Merged From"),
                            ("split_from", "Split From"),
                        ],
                        max_length=20,
                    ),
                ),
                ("effective_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                (
                    "child_org",
                    models.ForeignKey(
                        db_column="child_org_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_relationships",
                        to="auth_core.organizations",
                    ),
                ),
                (
                    "parent_org",
                    models.ForeignKey(
                        db_column="parent_org_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_relationships",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Relationship",
                "verbose_name_plural": "Organization Relationships",
                "db_table": "organization_relationships",
            },
        ),
        migrations.CreateModel(
            name="RolePermissions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role_id", models.UUIDField(blank=True, null=True)),
                ("permission_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "RolePermissions",
                "db_table": "role_permissions",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("role_id", "permission_id"),
                        name="unique_role_permissions_role_id_permission_id",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserRoles",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("scope_type", models.CharField(blank=True, max_length=100, null=True)),
                ("scope_id", models.UUIDField(blank=True, null=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("role_id", models.UUIDField(blank=True, null=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "UserRoles",
                "db_table": "user_roles",
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "user_id",
                            "role_id",
                            "organization_id",
                            "scope_type",
                            "scope_id",
                        ),
                        name="unique_user_roles_user_id_role_id_organization_id_scope_type_scope_id",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="organizations",
            index=models.Index(fields=["parent"], name="idx_organizations_parent"),
        ),
        migrations.AddIndex(
            model_name="organizations",
            index=models.Index(
                fields=["organization_type"], name="idx_organizations_type"
            ),
        ),
        migrations.AddIndex(
            model_name="organizations",
            index=models.Index(fields=["slug"], name="idx_organizations_slug"),
        ),
        migrations.AddIndex(
            model_name="organizations",
            index=models.Index(fields=["hierarchy_level"], name="idx_org_hier_level"),
        ),
        migrations.AddIndex(
            model_name="organizations",
            index=models.Index(fields=["status"], name="idx_organizations_status"),
        ),
        migrations.AddIndex(
            model_name="organizations",
            index=models.Index(
                fields=["clc_affiliated"], name="idx_org_clc_affiliated"
            ),
        ),
        migrations.AddIndex(
            model_name="organizations",
            index=models.Index(
                fields=["legacy_tenant_id"], name="idx_org_legacy_tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationrelationships",
            index=models.Index(
                fields=["parent_org"], name="idx_org_relationships_parent"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationrelationships",
            index=models.Index(
                fields=["child_org"], name="idx_org_relationships_child"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationrelationships",
            index=models.Index(
                fields=["relationship_type"], name="idx_org_relationships_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationrelationships",
            constraint=models.UniqueConstraint(
                fields=(
                    "parent_org",
                    "child_org",
                    "relationship_type",
                    "effective_date",
                ),
                name="unique_org_relationship",
            ),
        ),
    ]
