/**
 * ICRA — Canonical Copy
 *
 * One source of truth for institutional, calm, anti-surveillance language.
 * No marketing claims. No hype. No urgency. No surveillance vocabulary.
 *
 * If a phrase is added here, it has been considered against doctrine.
 */
export const DOCTRINE_VERSION = '1.0.0';

export const COPY = {
  brand: {
    productName: 'Institutional Continuity Risk Assessment',
    shortName: 'Continuity Assessment',
  },
  hero: {
    eyebrow: 'Institutional Continuity Risk Assessment',
    headline:
      'Your institution should not fall apart when key people leave.',
    sub:
      'A calm, structured way to examine the operational memory, governance visibility, and transition readiness that hold institutions together over time.',
    primaryCta: 'Begin the assessment',
    secondaryCta: 'Read what this is, and what it is not',
  },
  positionStatement: {
    title: 'Our position on human dignity and governance',
    body: [
      'This assessment is not employee surveillance.',
      'It is not productivity monitoring.',
      'It is not hidden behavioural analytics.',
      'It is not punitive workforce scoring.',
      'It is a structured examination of institutional continuity: the operational memory, governance visibility, and transition readiness that allow an institution to outlast any individual within it.',
      'We treat institutional continuity as governance infrastructure, not as workforce control.',
    ],
  },
  overview: {
    title: 'What this assessment looks at',
    bullets: [
      'Operational dependency — where institutional function relies on specific people rather than institutional procedure.',
      'Governance visibility — whether governance bodies can see operational reality without heroic reporting.',
      'Institutional memory — whether decisions and precedent outlast the individuals who shaped them.',
      'Transition readiness — whether the institution can absorb role and leadership change without disruption.',
      'Explainability and trust — whether decisions can be explained from evidence.',
      'Sovereignty and governance control — whether the institution controls its own institutional data and direction.',
    ],
    duration: 'Most institutions complete the assessment in 15 to 25 minutes.',
    privacy: [
      'Responses are stored with a pseudonymous assessment identifier.',
      'No personally-identifying information is required to complete the assessment.',
      'Data is used to generate your continuity profile, and, in aggregated and anonymized form, to inform our continuity benchmark research.',
      'You may request deletion of your assessment at any time.',
    ],
  },
  consent: {
    title: 'Before you begin',
    items: [
      {
        id: 'antiSurveillance',
        label:
          'I understand this assessment is governance-focused and does not collect surveillance or productivity data about individuals.',
      },
      {
        id: 'dataHandling',
        label:
          'I understand my responses will be stored under a pseudonymous assessment identifier and may be aggregated, in anonymized form, into continuity benchmark research.',
      },
      {
        id: 'explainability',
        label:
          'I understand the resulting profile is generated by an explainable scoring procedure, not by an opaque model, and can be reviewed and explained on request.',
      },
    ],
    proceed: 'Acknowledge and begin',
    decline: 'Return to overview',
  },
  intake: {
    saveNoticeTitle: 'Your progress is saved locally',
    saveNoticeBody:
      'You can leave and return to this assessment on the same device. Closing the browser does not lose your progress.',
    sectionEyebrow: 'Section',
    next: 'Continue',
    back: 'Back',
    submit: 'Generate continuity profile',
    optionalNote: 'Optional context (will not affect scoring)',
    likertHelp: 'Select the option that best reflects your honest assessment.',
  },
  results: {
    title: 'Institutional Continuity Profile',
    profileSub:
      'A calm, structured view of your institution’s continuity posture. This profile is generated deterministically from your responses; nothing here is produced by an opaque model.',
    bandLabel: 'Maturity band',
    compositeLabel: 'Composite continuity indicator',
    dimensionsTitle: 'Continuity dimensions',
    sectionsTitle: 'Section observations',
    observationsTitle: 'Continuity observations',
    recommendationsTitle: 'Suggested next steps',
    privacyFooter:
      'This profile is yours. We retain a pseudonymous record for benchmark research and may delete it on request. We do not contact you unless you ask us to.',
    explainabilityNote:
      'Each indicator above is the deterministic result of your weighted responses. We can show you exactly which questions contributed to each dimension on request.',
  },
  governance: {
    auditableNote:
      'This intake is governed by Nzila OS continuity doctrine. Every captured answer is reproducible against the question version active at the time of capture.',
  },
} as const;

export type CopyShape = typeof COPY;
