/**
 * Nzila OS — GA Gate v2 Report Formatters
 *
 * Converts GaCheckReport to:
 *   - stdout human-readable table (ANSI)
 *   - JSON file (governance/ga/ga-check.json)
 *   - Markdown file (governance/ga/GA_CHECK_REPORT.md)
 */

import type { GaCheckReport, GateResult } from './types'

// ── Human-readable stdout ───────────────────────────────────────────────────

export function formatHumanReport(report: GaCheckReport): string {
  const lines: string[] = []

  lines.push('═══════════════════════════════════════════════════════════════')
  lines.push('  NZILA OS — GA GATE v2')
  lines.push('  No bypass flags. No skip options. All checks mandatory.')
  lines.push('═══════════════════════════════════════════════════════════════')
  lines.push('')
  lines.push(`  Commit:    ${report.commitSha}`)
  lines.push(`  Timestamp: ${report.timestamp}`)
  lines.push(`  CI:        ${report.environment.ci ? 'yes' : 'no'}`)
  lines.push('')

  for (const gate of report.gates) {
    const icon = gate.status === 'PASS' ? '✅' : '❌'
    lines.push(`  ${icon}  ${gate.name}`)
    if (gate.status === 'FAIL') {
      lines.push(`      → ${gate.details}`)
      if (gate.violations && gate.violations.length > 0) {
        for (const v of gate.violations.slice(0, 10)) {
          lines.push(`        • ${v}`)
        }
        if (gate.violations.length > 10) {
          lines.push(`        ... and ${gate.violations.length - 10} more`)
        }
      }
    }
  }

  lines.push('')
  lines.push('───────────────────────────────────────────────────────────────')
  lines.push(`  PASSED: ${report.summary.passed}/${report.summary.total}`)
  lines.push(`  FAILED: ${report.summary.failed}/${report.summary.total}`)
  lines.push(`  Duration: ${report.totalDurationMs}ms`)
  lines.push('')

  if (report.overall === 'FAIL') {
    lines.push('  ❌❌❌  GA GATE FAILED — DEPLOYMENT BLOCKED  ❌❌❌')
    lines.push('')
    lines.push('  Failed checks:')
    for (const r of report.gates.filter((r) => r.status === 'FAIL')) {
      lines.push(`    • ${r.name}: ${r.details}`)
    }
  } else {
    lines.push('  ✅✅✅  GA GATE PASSED — DEPLOYMENT AUTHORIZED  ✅✅✅')
  }

  lines.push('')
  return lines.join('\n')
}

// ── Markdown report ─────────────────────────────────────────────────────────

export function formatMarkdownReport(report: GaCheckReport): string {
  const lines: string[] = []

  lines.push('# GA Gate v2 — Check Report')
  lines.push('')
  lines.push(`**Overall**: ${report.overall === 'PASS' ? '✅ PASS' : '❌ FAIL'}`)
  lines.push(`**Commit**: \`${report.commitSha}\``)
  lines.push(`**Timestamp**: ${report.timestamp}`)
  lines.push(`**Duration**: ${report.totalDurationMs}ms`)
  lines.push(`**CI**: ${report.environment.ci ? 'Yes' : 'No'}`)
  lines.push('')
  lines.push('## Summary')
  lines.push('')
  lines.push(
    `| Metric | Value |`,
  )
  lines.push('|--------|-------|')
  lines.push(`| Total checks | ${report.summary.total} |`)
  lines.push(`| Passed | ${report.summary.passed} |`)
  lines.push(`| Failed | ${report.summary.failed} |`)
  lines.push('')
  lines.push('## Gate Results')
  lines.push('')
  lines.push('| Status | Gate | Details | Duration |')
  lines.push('|--------|------|---------|----------|')

  for (const gate of report.gates) {
    const icon = gate.status === 'PASS' ? '✅' : '❌'
    const details = gate.details.replace(/\|/g, '\\|')
    lines.push(`| ${icon} | ${gate.name} | ${details} | ${gate.durationMs}ms |`)
  }

  // Add violations section if any
  const failures = report.gates.filter((g) => g.status === 'FAIL' && g.violations && g.violations.length > 0)
  if (failures.length > 0) {
    lines.push('')
    lines.push('## Violations')
    lines.push('')
    for (const gate of failures) {
      lines.push(`### ${gate.name}`)
      lines.push('')
      for (const v of gate.violations!) {
        lines.push(`- ${v}`)
      }
      lines.push('')
    }
  }

  lines.push('')
  lines.push('## Environment')
  lines.push('')
  lines.push(`- **Node**: ${report.environment.nodeVersion}`)
  lines.push(`- **Platform**: ${report.environment.platform}`)
  lines.push(`- **CWD**: ${report.environment.cwd}`)
  lines.push('')
  lines.push('---')
  lines.push('*Generated by `pnpm ga-check` — Nzila OS GA Gate v2*')
  lines.push('')

  return lines.join('\n')
}

// ── JSON report ─────────────────────────────────────────────────────────────

export function formatJsonReport(report: GaCheckReport): string {
  return JSON.stringify(report, null, 2)
}

// ── Helpers ─────────────────────────────────────────────────────────────────

export function gateResultRow(gate: GateResult): string {
  const icon = gate.status === 'PASS' ? '✅' : '❌'
  return `  ${icon}  ${gate.name} (${gate.durationMs}ms)`
}
