"""
URL configuration for analytics app.
Auto-generated by Nzila Code Generator — 2026-02-17
"""
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

router = DefaultRouter()
router.register(r'saved-searches', views.SavedSearchesViewSet)
router.register(r'case-alerts', views.CaseAlertsViewSet)
router.register(r'case-digests', views.CaseDigestsViewSet)

app_name = 'analytics'

urlpatterns = [
    path('', include(router.urls)),
]