"""
DRF viewsets for analytics app.
Auto-generated by Nzila Code Generator — 2026-02-17
"""
from rest_framework import viewsets, permissions, filters
from django_filters.rest_framework import DjangoFilterBackend
from .models import (SavedSearches, CaseAlerts, CaseDigests)
from .serializers import (SavedSearchesSerializer, CaseAlertsSerializer, CaseDigestsSerializer)


class SavedSearchesViewSet(viewsets.ModelViewSet):
    """API endpoint for SavedSearches operations."""
    queryset = SavedSearches.objects.all()
    serializer_class = SavedSearchesSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['alert_enabled', 'alert_frequency']
    search_fields = ['search_name', 'search_query', 'alert_frequency', 'alert_channels']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class CaseAlertsViewSet(viewsets.ModelViewSet):
    """API endpoint for CaseAlerts operations."""
    queryset = CaseAlerts.objects.all()
    serializer_class = CaseAlertsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['read']
    search_fields = ['alert_type', 'alert_title', 'alert_summary', 'case_title']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class CaseDigestsViewSet(viewsets.ModelViewSet):
    """API endpoint for CaseDigests operations."""
    queryset = CaseDigests.objects.all()
    serializer_class = CaseDigestsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    search_fields = ['key_findings', 'summary']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']
