# Generated by Django 5.2.17 on 2026-09-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_core", "0004_remove_organizations_idx_org_legacy_tenant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmembers",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationmembers",
            name="department",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationmembers",
            name="email",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationmembers",
            name="hire_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationmembers",
            name="joined_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationmembers",
            name="location",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationmembers",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationmembers",
            name="name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationmembers",
            name="phone",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationmembers",
            name="position",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationmembers",
            name="seniority",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationmembers",
            name="union_join_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
