# Generated by Django 5.2.17 on 2026-09-22 18:12
# Rebased against PLATFORM_SQL 0005 (organization_members runtime columns).
#
# Physical DDL for these columns is already authoritative in
# apps/union-eyes/db/migrations-platform/0005_organization_members_deleted_at.sql
# (ADD COLUMN IF NOT EXISTS). This migration keeps Django model state in sync
# and repeats the same idempotent DDL so a Django-first fresh build still
# converges. It does not emit bare AddField, which fails once 0005 has landed
# and would otherwise create a second, conflicting column definition.
# Reverse is a no-op: dropping the columns would undo the platform lineage.

from django.db import migrations, models


# One statement per RunSQL. psycopg2 accepts a batch, but a single statement
# stays valid if the backend later rejects multiple commands per execute.
PLATFORM_SQL_0005 = [
    "ALTER TABLE organization_members ADD COLUMN IF NOT EXISTS deleted_at timestamptz",
    "ALTER TABLE organization_members ADD COLUMN IF NOT EXISTS name text",
    "ALTER TABLE organization_members ADD COLUMN IF NOT EXISTS email text",
    "ALTER TABLE organization_members ADD COLUMN IF NOT EXISTS phone text",
    "ALTER TABLE organization_members ADD COLUMN IF NOT EXISTS department text",
    "ALTER TABLE organization_members ADD COLUMN IF NOT EXISTS position text",
    "ALTER TABLE organization_members ADD COLUMN IF NOT EXISTS hire_date timestamptz",
    "ALTER TABLE organization_members ADD COLUMN IF NOT EXISTS seniority integer",
    "ALTER TABLE organization_members ADD COLUMN IF NOT EXISTS union_join_date timestamptz",
    "ALTER TABLE organization_members ADD COLUMN IF NOT EXISTS metadata jsonb",
    "ALTER TABLE organization_members ADD COLUMN IF NOT EXISTS joined_at timestamptz DEFAULT now()",
    "ALTER TABLE organization_members ADD COLUMN IF NOT EXISTS location text",
]


class Migration(migrations.Migration):

    dependencies = [
        ("auth_core", "0004_remove_organizations_idx_org_legacy_tenant_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="organizationmembers",
                    name="deleted_at",
                    field=models.DateTimeField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="organizationmembers",
                    name="department",
                    field=models.TextField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="organizationmembers",
                    name="email",
                    field=models.TextField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="organizationmembers",
                    name="hire_date",
                    field=models.DateTimeField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="organizationmembers",
                    name="joined_at",
                    field=models.DateTimeField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="organizationmembers",
                    name="location",
                    field=models.TextField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="organizationmembers",
                    name="metadata",
                    field=models.JSONField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="organizationmembers",
                    name="name",
                    field=models.TextField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="organizationmembers",
                    name="phone",
                    field=models.TextField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="organizationmembers",
                    name="position",
                    field=models.TextField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="organizationmembers",
                    name="seniority",
                    field=models.IntegerField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="organizationmembers",
                    name="union_join_date",
                    field=models.DateTimeField(blank=True, null=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(sql=sql, reverse_sql=migrations.RunSQL.noop)
                for sql in PLATFORM_SQL_0005
            ],
        ),
    ]
