/**
 * @nzila/ai-core — Member-facing AI disclosure utility
 *
 * Provides standardised disclosure text that must be surfaced to members
 * whenever an AI-generated output influences a decision about them
 * (e.g. grievance triage priority, clause suggestions, chatbot advice).
 *
 * Regulatory basis:
 *  - Québec Law 25 / Bill 64 (Art. 12.1 — automated decision notification)
 *  - GDPR Art. 22 — right to explanation for automated individual decisions
 *  - PIPEDA — meaningful consent for AI-driven processing
 *
 * NZ-RISK-023 — Undisclosed automated decision-making to members.
 *
 * @module disclosure
 */

// ── Notice contexts ──────────────────────────────────────────────────────────

export type AiDisclosureContext =
  | 'grievance_triage'
  | 'clause_reasoning'
  | 'chatbot'
  | 'document_extract'
  | 'generic'

// ── Structured disclosure payload ────────────────────────────────────────────

export interface AiDisclosureNotice {
  /** Short headline (suitable for tooltip or banner heading). */
  headline: string
  /** Full disclosure text for display to the member or steward. */
  body: string
  /**
   * True when Law 25 / GDPR Art. 22 applies — i.e. the AI output may
   * influence a decision that produces legal or similarly significant effects
   * on an individual member.
   */
  regulatoryScope: boolean
  /** Link to the full DPIA / Privacy Impact Assessment document (if published). */
  dpiaUrl: string | null
  /** ISO 8601 date the notice was last reviewed by the privacy team. */
  lastReviewedAt: string
}

// ── Disclosure registry ──────────────────────────────────────────────────────

const NOTICES: Record<AiDisclosureContext, AiDisclosureNotice> = {
  grievance_triage: {
    headline: 'AI-assisted triage — human review required',
    body:
      'The priority, category, and next-step recommendation for this grievance were generated by an AI ' +
      'system. This output is advisory only and has not been accepted or acted upon until a steward ' +
      'explicitly reviews and approves it. You have the right to request a human review of any AI-generated ' +
      'assessment that affects your grievance. Contact your steward or union representative to exercise this right.',
    regulatoryScope: true,
    dpiaUrl: null,
    lastReviewedAt: '2025-03-01',
  },
  clause_reasoning: {
    headline: 'AI suggested these CBA clauses',
    body:
      'The collective agreement clauses shown here were suggested by an AI system based on the grievance details. ' +
      'These suggestions do not constitute legal advice and have not been verified by a labour relations officer. ' +
      'A qualified steward must review and confirm applicable clauses before citing them in any proceeding.',
    regulatoryScope: true,
    dpiaUrl: null,
    lastReviewedAt: '2025-03-01',
  },
  chatbot: {
    headline: 'AI-powered assistant',
    body:
      'This response was generated by an AI assistant. It is for informational purposes only and does not ' +
      'constitute legal advice, an official union position, or a commitment by the union. Always consult ' +
      'your steward or union representative for guidance on your specific situation.',
    regulatoryScope: false,
    dpiaUrl: null,
    lastReviewedAt: '2025-03-01',
  },
  document_extract: {
    headline: 'AI-extracted information',
    body:
      'The information below was extracted from uploaded documents by an AI system. Accuracy cannot be ' +
      'guaranteed. Please verify extracted data against the original source document before relying on it.',
    regulatoryScope: false,
    dpiaUrl: null,
    lastReviewedAt: '2025-03-01',
  },
  generic: {
    headline: 'AI-generated content',
    body:
      'This output was generated by an AI system. It is advisory only and does not constitute a binding ' +
      'decision. A human must review and approve any action before it takes effect.',
    regulatoryScope: false,
    dpiaUrl: null,
    lastReviewedAt: '2025-03-01',
  },
}

// ── Public API ───────────────────────────────────────────────────────────────

/**
 * Get the standardised AI disclosure notice for a given context.
 *
 * @example
 * const notice = getAiDisclosureNotice('grievance_triage')
 * // Render notice.headline and notice.body in the UI
 */
export function getAiDisclosureNotice(
  context: AiDisclosureContext = 'generic',
): AiDisclosureNotice {
  return NOTICES[context] ?? NOTICES['generic']
}

/**
 * Get just the disclaimer string (compatible with existing `AiResponseEnvelope.disclaimer`).
 */
export function getAiDisclaimerText(context: AiDisclosureContext = 'generic'): string {
  return getAiDisclosureNotice(context).body
}
