/**
 * @nzila/ue-cognition/schema — Phase-2 Drizzle schema declarations.
 *
 * NOT YET RUN AS A MIGRATION. Phase-1 storage is file-backed JSON under
 * `ops/ue-cognition/`. These tables describe the eventual move to Postgres
 * so the schema is reviewable + testable today and the file→DB swap is a
 * single store-adapter change.
 *
 * Phase 0B — Identifier type contract (see
 * reports/audits/cupe-national-phase-0/organization-model-decision.md § 4):
 *   Every snapshot / audit row here has its id generated by
 *   `makeId(<prefix>)` in the engine modules (case-risk, workload,
 *   engagement, precedents, kpis, audit). That helper emits strings of the
 *   form `<prefix>_<base36 ts>_<12 hex>` (e.g. `kpi_lz3f2a_9b71c2ae4f10`),
 *   which are NOT valid UUIDs. Declaring `id` as `uuid` would raise
 *   SQLSTATE 22P02 (`invalid input syntax for type uuid`) at every insert.
 *   Therefore every `id` column below is `text` — the app owns id
 *   generation, and the vestigial `gen_random_uuid()` DB default has been
 *   removed to prevent orphaned insert paths silently producing UUIDs
 *   that don't match the makeId contract.
 */
import {
  boolean,
  doublePrecision,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uuid,
} from 'drizzle-orm/pg-core'

export const ueCaseRiskSnapshots = pgTable('ue_case_risk_snapshots', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').notNull(),
  orgId: uuid('org_id').notNull(),
  caseId: text('case_id').notNull(),
  caseKind: text('case_kind').notNull(),
  riskScore: integer('risk_score').notNull(),
  riskProbability: doublePrecision('risk_probability').notNull(),
  riskTier: text('risk_tier').notNull(),
  confidence: doublePrecision('confidence').notNull(),
  recommendedAction: text('recommended_action').notNull(),
  rationale: text('rationale').notNull(),
  topFactors: jsonb('top_factors').notNull(),
  factors: jsonb('factors').notNull(),
  trajectory: jsonb('trajectory').notNull(),
  modelVersion: text('model_version').notNull(),
  snapshotAt: timestamp('snapshot_at', { withTimezone: true }).notNull().defaultNow(),
})

export const ueWorkloadSnapshots = pgTable('ue_workload_snapshots', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').notNull(),
  orgId: uuid('org_id').notNull(),
  stewardId: text('steward_id').notNull(),
  currentCaseload: integer('current_caseload').notNull(),
  maxCaseload: integer('max_caseload').notNull(),
  utilizationRatio: doublePrecision('utilization_ratio').notNull(),
  atRiskCaseCount: integer('at_risk_case_count').notNull(),
  avgResponseDays: doublePrecision('avg_response_days'),
  status: text('status').notNull(),
  slaRiskScore: doublePrecision('sla_risk_score').notNull(),
  burnoutSignal: doublePrecision('burnout_signal').notNull(),
  recommendedReassignments: jsonb('recommended_reassignments').notNull(),
  snapshotAt: timestamp('snapshot_at', { withTimezone: true }).notNull().defaultNow(),
})

export const ueEngagementSnapshots = pgTable('ue_engagement_snapshots', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').notNull(),
  orgId: uuid('org_id').notNull(),
  memberId: text('member_id').notNull(),
  engagementScore: integer('engagement_score').notNull(),
  disengagementProbability: doublePrecision('disengagement_probability').notNull(),
  tier: text('tier').notNull(),
  daysSinceLastActivity: doublePrecision('days_since_last_activity').notNull(),
  recentSignals: jsonb('recent_signals').notNull(),
  recommendedChannel: text('recommended_channel').notNull(),
  recommendedTimingHours: doublePrecision('recommended_timing_hours').notNull(),
  modelVersion: text('model_version').notNull(),
  snapshotAt: timestamp('snapshot_at', { withTimezone: true }).notNull().defaultNow(),
})

export const uePrecedentMatches = pgTable('ue_precedent_matches', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').notNull(),
  orgId: uuid('org_id').notNull(),
  forCaseId: text('for_case_id').notNull(),
  matches: jsonb('matches').notNull(),
  typicalDaysToResolve: doublePrecision('typical_days_to_resolve'),
  typicalSettlementAmount: doublePrecision('typical_settlement_amount'),
  successRate: doublePrecision('success_rate').notNull(),
  retrievedAt: timestamp('retrieved_at', { withTimezone: true }).notNull().defaultNow(),
})

export const ueKpiSnapshots = pgTable('ue_kpi_snapshots', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').notNull(),
  orgId: uuid('org_id').notNull(),
  windowDays: integer('window_days').notNull(),
  windowStart: timestamp('window_start', { withTimezone: true }).notNull(),
  windowEnd: timestamp('window_end', { withTimezone: true }).notNull(),
  payload: jsonb('payload').notNull(),
  modelVersion: text('model_version').notNull(),
  computedAt: timestamp('computed_at', { withTimezone: true }).notNull().defaultNow(),
})

export const ueCognitionAudits = pgTable('ue_cognition_audits', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').notNull(),
  orgId: uuid('org_id').notNull(),
  resource: text('resource').notNull(),
  action: text('action').notNull(),
  actorId: text('actor_id'),
  resourceId: text('resource_id').notNull(),
  details: jsonb('details').notNull(),
  occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull().defaultNow(),
})

/** Convenience flag for tooling that wants to confirm Phase-2 fan-out. */
export const UE_COGNITION_TABLES = [
  ueCaseRiskSnapshots,
  ueWorkloadSnapshots,
  ueEngagementSnapshots,
  uePrecedentMatches,
  ueKpiSnapshots,
  ueCognitionAudits,
] as const

void boolean
