# Generated by Django 5.1.4 on 2026-02-18 02:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CaseAlerts",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("saved_search_id", models.UUIDField(blank=True, null=True)),
                ("tribunal_case_id", models.UUIDField(blank=True, null=True)),
                ("alert_type", models.TextField(blank=True, null=True)),
                ("alert_title", models.TextField(blank=True, null=True)),
                ("alert_summary", models.TextField(blank=True, null=True)),
                ("case_title", models.TextField(blank=True, null=True)),
                ("decision_date", models.DateField(blank=True, null=True)),
                (
                    "relevance_score",
                    models.DecimalField(decimal_places=2, max_digits=3),
                ),
                ("read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "CaseAlerts",
                "db_table": "case_alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedSearches",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
                ("search_name", models.TextField(blank=True, null=True)),
                ("search_query", models.TextField(blank=True, null=True)),
                (
                    "search_filters",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("alert_enabled", models.BooleanField(default=False)),
                (
                    "alert_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("instant", "Instant"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=17,
                        null=True,
                    ),
                ),
                ("alert_channels", models.TextField()),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "SavedSearches",
                "db_table": "saved_searches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseDigests",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
                ("digest_period_start", models.DateTimeField(blank=True, null=True)),
                ("digest_period_end", models.DateTimeField(blank=True, null=True)),
                ("total_cases", models.IntegerField(blank=True, null=True)),
                ("high_priority_cases", models.IntegerField(blank=True, null=True)),
                (
                    "cases_by_category",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("key_findings", models.TextField()),
                ("summary", models.TextField(blank=True, null=True)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "CaseDigests",
                "db_table": "case_digests",
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "organization_id",
                            "digest_period_start",
                            "digest_period_end",
                        ),
                        name="unique_case_digests_organization_id_digest_period_start_digest_period_end",
                    )
                ],
            },
        ),
    ]
