/**
 * Console primary navigation — typed config.
 *
 * This file is the single source of truth for the dashboard sidebar.
 * Extracted from `app/(dashboard)/layout.tsx` so:
 *   - structure is reviewable in isolation
 *   - it can be filtered by role / feature flag / search at the call site
 *   - tests can assert routing invariants (every href maps to a real page)
 *
 * Conventions:
 *   - `icon` is a string key into `iconMap` in `components/sidebar-nav.tsx`
 *   - `requiredRole` (optional) is enforced by the layout before render
 *   - `featureFlag` (optional) is read from env or remote flag service
 *   - Groups render top-to-bottom; `defaultOpen` opens that group on first paint
 */
import type { NavGroup } from '@/components/sidebar-nav'

export interface NavItemConfig {
  name: string
  href: string
  icon: string
  description?: string
  badge?: string
  /** Roles that may see this item. Empty/undefined → visible to all authenticated users. */
  requiredRoles?: string[]
  /** If set, item is hidden unless the named flag is enabled. */
  featureFlag?: string
}

export interface NavGroupConfig extends Omit<NavGroup, 'items'> {
  label: string
  defaultOpen?: boolean
  items: NavItemConfig[]
}

/** External app launcher entries (not part of dashboard routing). */
export interface AppLinkConfig {
  name: string
  /** Resolved at module-load from `process.env.NEXT_PUBLIC_*` */
  href: string | undefined
  badge: string
}

export const navGroups: NavGroupConfig[] = [
  // ── Workspace — the six-workspace doctrine surface (front door) ─────────────
  // docs/doctrine/NZILA_CONSOLE_WORKSPACE_DOCTRINE.md — Console v1 is exactly six
  // workspaces + Settings. These are the primary navigation; the groups below are
  // legacy direct routes, progressively subordinated under these workspaces.
  {
    label: 'Workspace',
    defaultOpen: true,
    items: [
      { name: 'Overview', href: '/workspace/overview', icon: 'HomeIcon', badge: 'home', description: 'Portfolio health at a glance — the morning screen. Is the portfolio healthy this morning?' },
      { name: 'Portfolio', href: '/workspace/portfolio', icon: 'BuildingOffice2Icon', description: 'What exists, what stage it is in, what is healthy or blocked. Overview · Ventures · Pipeline · Funding.' },
      { name: 'Observatory', href: '/workspace/observatory', icon: 'ChartBarSquareIcon', description: 'What the market-validation engine is telling us. Cohorts · Assessments · Route Decisions · Reassessments · Benchmark Readiness.' },
      { name: 'Sales', href: '/workspace/sales', icon: 'ArrowTrendingUpIcon', description: 'Unified GTM: leads → opportunities → proposals → pilots → conversions.' },
      { name: 'Ventures', href: '/workspace/ventures', icon: 'RocketLaunchIcon', description: 'Per-venture maturity, roadmap, revenue, customers, and blockers.' },
      { name: 'Operations', href: '/workspace/operations', icon: 'WrenchScrewdriverIcon', description: 'Founder cockpit: tasks, risks, decisions, governance, documentation.' },
      { name: 'Settings', href: '/workspace/settings', icon: 'Cog6ToothIcon', description: 'Account and workspace configuration.' },
    ],
  },
]

/**
 * Legacy direct routes — NOT rendered in the sidebar.
 *
 * Per the Workspace Doctrine (docs/doctrine/NZILA_CONSOLE_WORKSPACE_DOCTRINE.md)
 * the sidebar is exactly the six workspaces + Settings. These ~60 routes remain
 * fully reachable by URL and through the command palette (⌘K), and are
 * progressively subordinated under workspace sub-tabs (e.g. Operations).
 * They are intentionally kept out of the primary navigation tree.
 */
export const legacyNavGroups: NavGroupConfig[] = [
  // Zone 1: TODAY — CEO Daily Pulse
  {
    label: 'Command',
    defaultOpen: false,
    items: [
      { name: 'CEO One-Screen', href: '/ceo', icon: 'EyeIcon', badge: 'board', description: 'Compressed boardroom summary for founder, partner, or investor conversations.' },
      { name: 'Intelligence', href: '/intelligence', icon: 'SparklesIcon', badge: 'deep', description: 'Cross-domain research surface for funding, deals, partners, products, and strategic signals.' },
      { name: 'Today', href: '/today', icon: 'HomeIcon', badge: 'daily', description: 'Best first stop every morning for immediate cash, pipeline, pilot, and approval signals.' },
      { name: 'Autopilot', href: '/autopilot', icon: 'BoltIcon', badge: 'assist', description: 'High-confidence actions generated by the system that still require human approval.' },
      { name: 'Briefing', href: '/briefing', icon: 'ClipboardDocumentCheckIcon', badge: 'weekly', description: 'Decision-oriented memo for leadership review and weekly founder planning.' },
      { name: 'Focus', href: '/focus', icon: 'ClockIcon', badge: 'weekly', description: 'Founder time allocation and capacity page for deciding what gets real attention this week.' },
      { name: 'Portfolio', href: '/portfolio', icon: 'BuildingOffice2Icon', badge: 'alloc', description: 'Portfolio allocation view showing which ventures deserve build, sell, hold, or maintenance effort.' },
      { name: 'Command Center', href: '/command-center', icon: 'CommandLineIcon', badge: 'ops', description: 'Operating snapshot across clients, renewals, support load, team pressure, and founder priorities.' },
      { name: 'Weekly Review', href: '/weekly-review', icon: 'CalendarDaysIcon', badge: 'cadence', description: 'Same operating review across daily, weekly, and monthly rhythms without changing context.' },
      { name: 'Intelligence · Focus', href: '/intelligence/focus', icon: 'ClockIcon', description: 'Focused intelligence view on the highest-signal opportunities and risks right now.' },
    ],
  },
  // ── Zone 2: REVENUE — Sales Command Center ─────────────────────────────────
  {
    label: 'Revenue',
    defaultOpen: false,
    items: [
      { name: 'Pipeline', href: '/revenue', icon: 'ArrowTrendingUpIcon', description: 'Sales command center showing quotes, active pilots, prospect pipeline, and revenue playbooks by account.' },
      { name: 'UE Revenue Cockpit', href: '/ue-revenue-cockpit', icon: 'RocketLaunchIcon', description: 'Union Eyes revenue agent surface tracking commerce opportunities, growth signals, and deal velocity.' },
      { name: 'FAIRCASE Funnel', href: '/revenue/faircase', icon: 'ChartBarIcon', description: 'FAIRCASE-specific funnel view tracking leads through meetings, demos, proposals, pilots to close.' },
      { name: 'Pilot Export', href: '/pilot/export', icon: 'DocumentArrowDownIcon', description: 'Export active pilots and revenue events for cross-venture analysis and reporting.' },
    ],
  },
  // ── Zone 3: CAPITAL — Cash · Burn · Runway ─────────────────────────────────
  {
    label: 'Capital',
    defaultOpen: false,
    items: [
      { name: 'Burn & Runway', href: '/capital', icon: 'BanknotesIcon', description: 'Cash position, burn rate, and runway visibility across all ventures with path-to-sustainability tracking.' },
      { name: 'Runway', href: '/runway', icon: 'ArrowTrendingUpIcon', description: 'Detailed runway analysis by venture showing months of operating capital and funding milestones.' },
      { name: 'Forecast', href: '/forecast', icon: 'ChartBarIcon', description: 'Financial projections and forecasting model for portfolio-wide cash planning.' },
      { name: 'Cost Dashboard', href: '/cost', icon: 'CurrencyDollarIcon', description: 'Cloud and infrastructure cost visibility with optimization recommendations and budget alerts.' },
      { name: 'Economics', href: '/platform-economics', icon: 'ChartBarIcon', description: 'Shared platform economics and cost allocation across ventures.' },
      { name: 'Finance Ops', href: '/business/finance', icon: 'DocumentTextIcon', description: 'Finance operations, invoicing, and transaction records.' },
      { name: 'Business Compliance', href: '/business/compliance', icon: 'ClipboardDocumentCheckIcon', description: 'Corporate compliance posture, filings, and regulatory obligations.' },
      { name: 'Year-End Pack', href: '/business/finance/year-end-pack', icon: 'DocumentArrowDownIcon', description: 'Year-end financial close package and accountant-ready export.' },
      { name: 'Year-End Close', href: '/business/yearend', icon: 'CalendarDaysIcon', description: 'Annual close checklist and fiscal year wrap-up workflow.' },
    ],
  },
  // ── Zone 4: EXECUTION — Initiatives · Owners · Blockers ───────────────────
  {
    label: 'Execution',
    items: [
      { name: 'Initiatives', href: '/execution', icon: 'BoltIcon', description: 'Active strategic initiatives with owners, deadlines, and execution progress tracking.' },
      { name: 'Accountability', href: '/accountability', icon: 'CheckCircleIcon', description: 'OKR and accountability tracking with status updates and blocker resolution.' },
      { name: 'Operator Mode', href: '/operator', icon: 'WrenchScrewdriverIcon', description: 'Tactical operations control and real-time coordination for the operating team.' },
      { name: 'Decision Scoreback', href: '/decision-scoreback', icon: 'ChartBarSquareIcon', description: 'Track decisions made, outcomes achieved, and lessons learned from leadership decisions.' },
      { name: 'Approvals', href: '/business/approvals', icon: 'ClipboardDocumentCheckIcon', description: 'Approval workflows and signature tracking for business decisions and commitments.' },
      { name: 'Queues', href: '/business/queues', icon: 'CircleStackIcon', description: 'Work queue management and task prioritization across the organization.' },
      { name: 'Signatures', href: '/business/signatures', icon: 'FingerPrintIcon', description: 'Digital signature collection and document signing workflow.' },
    ],
  },
  {
    label: 'Healthcare Discovery',
    items: [
      {
        name: 'Surveys',
        href: '/healthcare/discovery/surveys',
        icon: 'ClipboardDocumentCheckIcon',
        description:
          'Run short privacy-conscious unit surveys before selecting one tiny healthcare workflow wedge.',
      },
      {
        name: 'Pilot Readiness',
        href: '/healthcare/discovery/pilot-readiness',
        icon: 'ChartBarSquareIcon',
        description:
          'Discovery-to-pilot framing for selecting one governed first workflow.',
      },
    ],
  },
  // ── Zone 5: RISK — Business · Platform · Financial Threats ────────────────
  {
    label: 'Risk',
    items: [
      { name: 'Risk Register', href: '/risk', icon: 'ExclamationTriangleIcon', description: 'Central registry of business, technical, and financial risks with mitigation plans.' },
      { name: 'Ops Score', href: '/ops-score', icon: 'ShieldExclamationIcon', description: 'Real-time operations health score showing system reliability and incident risk.' },
      { name: 'Audit Insights', href: '/audit-insights', icon: 'EyeIcon', description: 'Audit findings and compliance gaps with remediation tracking.' },
      { name: 'Trend Detection', href: '/trend-detection', icon: 'ChartBarSquareIcon', description: 'AI-powered anomaly and trend detection across portfolio metrics.' },
    ],
  },
  // ── Zone 6: GOVERNANCE — GRC · Evidence · Corporate Gov ───────────────────
  {
    label: 'Governance',
    items: [
      { name: 'Governance', href: '/governance', icon: 'ShieldCheckIcon', description: 'Governance framework, policies, and compliance documentation.' },
      { name: 'Board Pack', href: '/board', icon: 'DocumentTextIcon', description: 'Monthly board package with metrics, decisions, and strategic updates.' },
      { name: 'Corporate Gov', href: '/business/governance', icon: 'EyeIcon', description: 'Corporate governance structure and board meeting management.' },
      { name: 'Equity & Cap Table', href: '/business/equity', icon: 'DocumentDuplicateIcon', description: 'Equity tracking, cap table, and share distribution across ventures.' },
      { name: 'Evidence Packs', href: '/evidence-packs', icon: 'DocumentArrowDownIcon', description: 'Compliance evidence and audit documentation for regulatory requirements.' },
      { name: 'Governance Experience', href: '/governance-experience', icon: 'ShieldCheckIcon', description: 'End-to-end governance experience surface across policies, evidence, and attestations.' },
      { name: 'Decision Audit', href: '/audit', icon: 'ClipboardDocumentCheckIcon', description: 'Signed decision ledger and verification/export entry points.' },
      { name: 'Decision Intelligence', href: '/intelligence?section=decision-intelligence', icon: 'ChartBarSquareIcon', description: 'Decision analytics, policy drift, and benchmark intelligence monetized by tier.' },
      { name: 'Proof Center', href: '/proof-center', icon: 'FingerPrintIcon', description: 'Cryptographic proof and attestation center for audit trail.' },
      { name: 'Compliance', href: '/compliance-snapshots', icon: 'ClipboardDocumentCheckIcon', description: 'Compliance status snapshots and regulatory requirement tracking.' },
    ],
  },
  // ── Internal Tools (collapsed by default) ─────────────────────────────────
  {
    label: 'Ops Toolkit',
    items: [
      { name: 'System Health', href: '/system-health', icon: 'ServerIcon', description: 'Platform infrastructure and service health dashboard.' },
      { name: 'Ops', href: '/ops', icon: 'ShieldExclamationIcon', description: 'Operations control center and incident management.' },
      { name: 'UX Performance', href: '/ops/performance', icon: 'BoltIcon', description: 'Web Vitals, server route timings, and failed-action telemetry for the Console itself.' },
      { name: 'Performance', href: '/performance', icon: 'BoltIcon', description: 'Application performance monitoring and optimization insights.' },
      { name: 'Integrations', href: '/integrations', icon: 'PuzzlePieceIcon', description: 'Third-party integrations and API management.' },
      { name: 'Integration Chaos', href: '/integrations/chaos', icon: 'BoltIcon', description: 'Chaos and fault-injection testing for integration resilience.' },
      { name: 'Control Plane', href: '/integrations-control-plane', icon: 'WrenchScrewdriverIcon', description: 'Advanced integration control and routing configuration.' },
      { name: 'Automation', href: '/automation', icon: 'BoltIcon', description: 'Automation runs, schedules, and operational workflow orchestration.' },
      { name: 'Perf Regressions', href: '/performance/regressions', icon: 'BoltIcon', description: 'Detected performance regressions across routes and releases.' },
    ],
  },
  // ── Service Operations Layer ───────────────────────────────────────────────
  {
    label: 'Service Operations',
    items: [
      { name: 'Ops Dashboard', href: '/itsm/dashboard', icon: 'ChartBarSquareIcon', description: 'Service operations metrics and KPI dashboard.' },
      { name: 'Support Desk', href: '/itsm/queue', icon: 'CircleStackIcon', description: 'Ticket queue and support request management.' },
      { name: 'Client Accounts', href: '/itsm/clients', icon: 'UsersIcon', description: 'Client account management and relationship tracking.' },
      { name: 'Incidents', href: '/itsm/incidents', icon: 'ExclamationTriangleIcon', description: 'Incident tracking and resolution workflow.' },
      { name: 'Change Log', href: '/itsm/changes', icon: 'CalendarIcon', description: 'Change management and deployment tracking.' },
      { name: 'Knowledge Base', href: '/itsm/kb', icon: 'BookOpenIcon', description: 'Support documentation and FAQ knowledge base.' },
      { name: 'Assets & Vendors', href: '/itsm/assets', icon: 'ServerIcon', description: 'IT assets, vendor contracts, and service tracking.' },
      { name: 'Contracts', href: '/itsm/contracts', icon: 'DocumentTextIcon', description: 'Service contracts, SLAs, and renewal tracking for client accounts.' },
      { name: 'Problems', href: '/itsm/problems', icon: 'ExclamationTriangleIcon', description: 'Problem management — root-cause analysis behind recurring incidents.' },
    ],
  },
  // ── Admin (minimal) ────────────────────────────────────────────────────────
  {
    label: 'Admin',
    items: [
      { name: 'Organizations', href: '/orgs', icon: 'UsersIcon', description: 'Client organization registry and workspace management.' },
      { name: 'Docs', href: '/docs', icon: 'DocumentTextIcon', description: 'Internal documentation and knowledge base.' },
      { name: 'Settings', href: '/settings', icon: 'Cog6ToothIcon', description: 'System settings, preferences, and configuration.' },
      { name: 'Profile', href: '/settings/profile', icon: 'Cog6ToothIcon', description: 'Personal profile, identity, and notification preferences.' },
      { name: 'Organisation', href: '/settings/organisation', icon: 'BuildingOffice2Icon', description: 'Organisation-level settings, branding, and workspace defaults.' },
      { name: 'Integration Settings', href: '/settings/integrations', icon: 'PuzzlePieceIcon', description: 'Connect and configure third-party integrations for this workspace.' },
    ],
  },
  // ── Analytics & Growth ─────────────────────────────────────────────────────
  {
    label: 'Analytics & Growth',
    items: [
      { name: 'Analytics', href: '/analytics', icon: 'ChartBarIcon', description: 'Cross-portfolio analytics, cohort trends, and performance breakdowns.' },
      { name: 'Growth', href: '/growth', icon: 'ArrowTrendingUpIcon', description: 'Growth experiments, funnel metrics, and acquisition signals.' },
      { name: 'Audit Graph', href: '/audit-graph', icon: 'ChartBarSquareIcon', description: 'Visual graph of audit events, lineage, and decision provenance.' },
    ],
  },
  // ── Proving & Readiness — operational proving and go/no-go evidence ─────────
  {
    label: 'Proving & Readiness',
    items: [
      { name: 'Assurance', href: '/assurance', icon: 'ShieldCheckIcon', description: 'Assurance posture across reliability, security, and operational controls.' },
      { name: 'Proof Pack', href: '/proof-pack', icon: 'FingerPrintIcon', description: 'Compiled cryptographic proof pack for external attestation.' },
      { name: 'Operational Proving', href: '/operational-proving-summary', icon: 'ClipboardDocumentCheckIcon', description: 'Summary of operational proving runs and readiness evidence.' },
      { name: 'Rollout Readiness', href: '/rollout-readiness', icon: 'CheckCircleIcon', description: 'Go/no-go readiness checklist for staged rollouts.' },
      { name: 'Scale Simulation', href: '/scale-simulation', icon: 'BeakerIcon', description: 'Load and scale simulation results for capacity planning.' },
      { name: 'Failure Simulation', href: '/failure-simulation', icon: 'BeakerIcon', description: 'Failure-mode simulation and resilience validation runs.' },
      { name: 'Deployment Profile', href: '/deployment-profile', icon: 'ServerIcon', description: 'Deployment topology, environment profile, and release configuration.' },
      { name: 'Final Go Briefing', href: '/final-go-briefing', icon: 'ClipboardDocumentCheckIcon', description: 'Final go-live briefing pack with sign-off checklist.' },
      { name: 'Field Operations Briefing', href: '/field-operations-briefing', icon: 'ClipboardDocumentCheckIcon', description: 'Field operations readiness briefing for launch teams.' },
      { name: 'NACP Integrity', href: '/nacp-integrity', icon: 'ShieldExclamationIcon', description: 'NACP data integrity verification and exam pipeline checks.' },
      { name: 'Isolation Certification', href: '/isolation-certification', icon: 'LockClosedIcon', description: 'Client-org isolation certification evidence and controls.' },
    ],
  },
  // ── Executive Cockpits — platform & portfolio leadership surfaces ──────────
  {
    label: 'Executive Cockpits',
    items: [
      { name: 'Platform Cockpit', href: '/platform', icon: 'ServerIcon', description: 'Platform leadership cockpit across reliability, security, and FinOps.' },
      { name: 'Hiring Cockpit', href: '/portfolio/executive/hiring', icon: 'UsersIcon', description: 'Portfolio-wide hiring plan, open roles, and headcount allocation.' },
    ],
  },
  // ── Platform Admin Console — internal AI/ML & billing admin ────────────────
  {
    label: 'Platform Admin Console',
    items: [
      { name: 'Admin Console', href: '/console', icon: 'CommandLineIcon', description: 'Internal platform administration home.' },
      { name: 'Retention Admin', href: '/console/admin/retention', icon: 'CircleStackIcon', description: 'Data retention policy administration and purge controls.' },
      { name: 'ML Overview', href: '/console/ml/overview', icon: 'CpuChipIcon', description: 'Machine-learning platform overview and model fleet health.' },
      { name: 'ML Models', href: '/console/ml/models', icon: 'CpuChipIcon', description: 'Registered ML models, versions, and deployment status.' },
      { name: 'ML Runs', href: '/console/ml/runs', icon: 'BoltIcon', description: 'Training and inference run history with metrics.' },
      { name: 'ML · Stripe Daily', href: '/console/ml/stripe/daily', icon: 'CurrencyDollarIcon', description: 'Daily Stripe revenue rollups feeding ML billing models.' },
      { name: 'ML · Stripe Transactions', href: '/console/ml/stripe/transactions', icon: 'CurrencyDollarIcon', description: 'Raw Stripe transaction stream for reconciliation and ML inputs.' },
    ],
  },
]

/** External app launcher — resolved from public env vars at module load. */
export const appLinks: AppLinkConfig[] = [
  { name: 'Public Web', href: process.env.NEXT_PUBLIC_WEB_URL, badge: '3000' },
  { name: 'Union Eyes', href: process.env.NEXT_PUBLIC_UNION_EYES_URL, badge: '3003' },
]

/**
 * Filter nav groups against a set of role grants and enabled feature flags.
 * Empty groups (after filtering) are dropped so the layout never renders an
 * empty section header.
 *
 * Both `roles` and `enabledFlags` default to "allow everything" — pass them
 * explicitly when role-aware filtering is wired up.
 */
export function filterNav(
  groups: NavGroupConfig[],
  opts: { roles?: Set<string>; enabledFlags?: Set<string> } = {},
): NavGroupConfig[] {
  const { roles, enabledFlags } = opts
  return groups
    .map(group => ({
      ...group,
      items: group.items.filter(item => {
        if (item.featureFlag && enabledFlags && !enabledFlags.has(item.featureFlag)) return false
        if (item.requiredRoles && roles) {
          return item.requiredRoles.some(r => roles.has(r))
        }
        return true
      }),
    }))
    .filter(group => group.items.length > 0)
}
