"""
Django models for notifications app.
Auto-generated by Nzila Code Generator — 2026-02-17

DO NOT EDIT manually unless you know what you're doing.
Re-run the generator to overwrite.
"""
import uuid
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.contrib.postgres.search import SearchVectorField

try:
    from pgvector.django import VectorField
except ImportError:
    VectorField = None  # pgvector not installed


class BaseModel(models.Model):
    """Abstract base with standard audit fields."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class OrganizationModel(BaseModel):
    """Abstract base for multi-organization models."""
    organization = models.ForeignKey(
        'auth_core.Organizations',
        on_delete=models.CASCADE,
        related_name='%(class)ss'
    )

    class Meta:
        abstract = True



class AlertPreferences(BaseModel):
    """Migrated from sql: 20250129000003_case_alerts.sql"""
    DIGEST_FREQUENCY_CHOICES = [('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')]

    user_id = models.UUIDField(default=uuid.uuid4, unique=True)
    email_notifications = models.BooleanField(default=False)
    in_app_notifications = models.BooleanField(default=False)
    webhook_url = models.TextField(null=True, blank=True)
    digest_frequency = models.CharField(choices=DIGEST_FREQUENCY_CHOICES, max_length=17, null=True, blank=True)
    quiet_hours_start = models.TimeField(null=True, blank=True)
    quiet_hours_end = models.TimeField(null=True, blank=True)
    notification_grouping = models.BooleanField(default=False)

    class Meta:
        db_table = 'alert_preferences'
        verbose_name = 'AlertPreferences'
        ordering = ['-created_at']