"""
DRF serializers for notifications app.
Auto-generated by Nzila Code Generator — 2026-02-17
"""
from rest_framework import serializers
from .models import (AlertPreferences)


class AlertPreferencesSerializer(serializers.ModelSerializer):
    class Meta:
        model = AlertPreferences
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']
