"""
DRF viewsets for ai_core app.
Auto-generated by Nzila Code Generator — 2026-02-17
"""
from rest_framework import viewsets, permissions, filters
from django_filters.rest_framework import DjangoFilterBackend
from .models import (AbTests, AbTestVariants, AbTestAssignments, AbTestEvents, AccessibilityAudits, AccessibilityIssues, WcagSuccessCriteria, AccessibilityTestSuites, AccessibilityUserTesting, ChatSessions, ChatMessages, KnowledgeBase, ChatbotSuggestions, ChatbotAnalytics, AiSafetyFilters, AiUsageMetrics, AiRateLimits, AiBudgets, MlPredictions, ModelMetadata)
from .serializers import (AbTestsSerializer, AbTestVariantsSerializer, AbTestAssignmentsSerializer, AbTestEventsSerializer, AccessibilityAuditsSerializer, AccessibilityIssuesSerializer, WcagSuccessCriteriaSerializer, AccessibilityTestSuitesSerializer, AccessibilityUserTestingSerializer, ChatSessionsSerializer, ChatMessagesSerializer, KnowledgeBaseSerializer, ChatbotSuggestionsSerializer, ChatbotAnalyticsSerializer, AiSafetyFiltersSerializer, AiUsageMetricsSerializer, AiRateLimitsSerializer, AiBudgetsSerializer, MlPredictionsSerializer, ModelMetadataSerializer)


class DenyAllPermission(permissions.BasePermission):
    """Fail-closed containment: unconditionally denies every request.

    Used for models with no proven legitimate consumer and no tenant
    isolation mechanism (PR #752 round 35 — AiBudgets: the Django model
    only maps `organization_id`, omitting the real physical table's NOT
    NULL monthly_limit_usd/billing_period_start/billing_period_end columns
    (db/migrations/0079_ai_cost_tracking_phase1.sql), so create() would
    violate DB constraints; the generated ModelViewSet(queryset=Model.
    objects.all(), permission_classes=[IsAuthenticated]) pattern otherwise
    exposes every organization's budget existence/id to any authenticated
    user and allows unscoped organization_id reassignment + delete. No
    real TS or Django consumer of this endpoint was found. Remove only
    once a proven legitimate consumer and organization-bound isolation
    mechanism exist for this table.
    """

    def has_permission(self, request, view):
        return False

    def has_object_permission(self, request, view, obj):
        return False


class AbTestsViewSet(viewsets.ModelViewSet):
    """API endpoint for AbTests operations."""
    queryset = AbTests.objects.all()
    serializer_class = AbTestsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['organization_id']
    search_fields = ['name', 'description', 'type', 'status']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class AbTestVariantsViewSet(viewsets.ModelViewSet):
    """API endpoint for AbTestVariants operations."""
    queryset = AbTestVariants.objects.all()
    serializer_class = AbTestVariantsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class AbTestAssignmentsViewSet(viewsets.ModelViewSet):
    """API endpoint for AbTestAssignments operations."""
    queryset = AbTestAssignments.objects.all()
    serializer_class = AbTestAssignmentsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class AbTestEventsViewSet(viewsets.ModelViewSet):
    """API endpoint for AbTestEvents operations."""
    queryset = AbTestEvents.objects.all()
    serializer_class = AbTestEventsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class AccessibilityAuditsViewSet(viewsets.ModelViewSet):
    """API endpoint for AccessibilityAudits operations."""
    queryset = AccessibilityAudits.objects.all()
    serializer_class = AccessibilityAuditsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class AccessibilityIssuesViewSet(viewsets.ModelViewSet):
    """API endpoint for AccessibilityIssues operations."""
    queryset = AccessibilityIssues.objects.all()
    serializer_class = AccessibilityIssuesSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class WcagSuccessCriteriaViewSet(viewsets.ModelViewSet):
    """API endpoint for WcagSuccessCriteria operations."""
    queryset = WcagSuccessCriteria.objects.all()
    serializer_class = WcagSuccessCriteriaSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    search_fields = ['criteria_number', 'criteria_title', 'criteria_description', 'level', 'wcag_version']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class AccessibilityTestSuitesViewSet(viewsets.ModelViewSet):
    """API endpoint for AccessibilityTestSuites operations."""
    queryset = AccessibilityTestSuites.objects.all()
    serializer_class = AccessibilityTestSuitesSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['organization_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class AccessibilityUserTestingViewSet(viewsets.ModelViewSet):
    """API endpoint for AccessibilityUserTesting operations."""
    queryset = AccessibilityUserTesting.objects.all()
    serializer_class = AccessibilityUserTestingSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class ChatSessionsViewSet(viewsets.ModelViewSet):
    """API endpoint for ChatSessions operations."""
    queryset = ChatSessions.objects.all()
    serializer_class = ChatSessionsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    search_fields = ['user_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class ChatMessagesViewSet(viewsets.ModelViewSet):
    """API endpoint for ChatMessages operations."""
    queryset = ChatMessages.objects.all()
    serializer_class = ChatMessagesSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class KnowledgeBaseViewSet(viewsets.ModelViewSet):
    """API endpoint for KnowledgeBase operations."""
    queryset = KnowledgeBase.objects.all()
    serializer_class = KnowledgeBaseSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class ChatbotSuggestionsViewSet(viewsets.ModelViewSet):
    """API endpoint for ChatbotSuggestions operations."""
    queryset = ChatbotSuggestions.objects.all()
    serializer_class = ChatbotSuggestionsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class ChatbotAnalyticsViewSet(viewsets.ModelViewSet):
    """API endpoint for ChatbotAnalytics operations."""
    queryset = ChatbotAnalytics.objects.all()
    serializer_class = ChatbotAnalyticsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class AiSafetyFiltersViewSet(viewsets.ModelViewSet):
    """API endpoint for AiSafetyFilters operations."""
    queryset = AiSafetyFilters.objects.all()
    serializer_class = AiSafetyFiltersSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['flagged', 'session_id', 'message_id']
    search_fields = ['input', 'output', 'action', 'reason']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class AiUsageMetricsViewSet(viewsets.ModelViewSet):
    """API endpoint for AiUsageMetrics operations."""
    queryset = AiUsageMetrics.objects.all()
    serializer_class = AiUsageMetricsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class AiRateLimitsViewSet(viewsets.ModelViewSet):
    """API endpoint for AiRateLimits operations."""
    queryset = AiRateLimits.objects.all()
    serializer_class = AiRateLimitsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class AiBudgetsViewSet(viewsets.ModelViewSet):
    """API endpoint for AiBudgets operations."""
    queryset = AiBudgets.objects.all()
    serializer_class = AiBudgetsSerializer
    permission_classes = [DenyAllPermission]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class MlPredictionsViewSet(viewsets.ModelViewSet):
    """API endpoint for MlPredictions operations."""
    queryset = MlPredictions.objects.all()
    serializer_class = MlPredictionsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['organization_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class ModelMetadataViewSet(viewsets.ModelViewSet):
    """API endpoint for ModelMetadata operations."""
    queryset = ModelMetadata.objects.all()
    serializer_class = ModelMetadataSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['organization_id']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']
