/**
 * Persister: takes a seeder plan ({@link AppPlanSnapshot}) and writes it
 * through a {@link DbAdapter}. All writes go through one transaction per
 * seeder run; on any failure the transaction rolls back.
 *
 * Idempotency: artifacts use the deterministic synthetic ids generated by
 * the per-app seeder (e.g. `member-1a2b3c4d`). Re-running the same profile
 * with the same seed UPSERTS in place rather than producing duplicates.
 */
import { randomUUID } from 'node:crypto'

import { assertSafeStagingOrgId } from './safety'
import type {
  DbAdapter,
  StagingSeedArtifactRow,
  StagingSeedRunRow,
} from './adapter'

export interface AppPlanEntity {
  /**
   * Logical entity bucket (e.g. `members`, `grievances`). Drives reset
   * counts and downstream native-table mappings (Phase 3B).
   */
  readonly entityType: string
  /** Synthetic rows. Each MUST have a deterministic `id` field. */
  readonly rows: ReadonlyArray<{ readonly id: string }>
}

export interface AppPlanSnapshot {
  readonly app: string
  readonly orgId: string
  readonly profile: string
  readonly seed: number
  readonly entities: ReadonlyArray<AppPlanEntity>
}

export interface PersistResult {
  readonly runId: string
  readonly status: 'ok' | 'dry-run' | 'error'
  readonly totals: Record<string, number>
  readonly durationMs: number
}

export interface PersistOptions {
  readonly command: 'seed' | 'reseed'
  readonly dryRun: boolean
  readonly now?: () => Date
}

/**
 * Persist a single app's plan. Caller is responsible for opening the
 * adapter (which itself MUST have passed the safety gate) and calling
 * {@link DbAdapter.close} when done.
 */
export async function persistAppPlan(
  adapter: DbAdapter,
  plan: AppPlanSnapshot,
  options: PersistOptions,
): Promise<PersistResult> {
  assertSafeStagingOrgId(plan.orgId)

  const startedAt = (options.now?.() ?? new Date()).toISOString()
  const startMs = (options.now?.() ?? new Date()).getTime()

  const runId = randomUUID()
  const totals: Record<string, number> = {}
  for (const entity of plan.entities) totals[entity.entityType] = entity.rows.length

  let status: PersistResult['status'] = options.dryRun ? 'dry-run' : 'ok'
  let errorMessage: string | null = null

  try {
    await adapter.withTransaction(async (tx) => {
      const runRow: StagingSeedRunRow = {
        id: runId,
        app: plan.app,
        profile: plan.profile,
        seed: plan.seed,
        command: options.command,
        dryRun: options.dryRun,
        startedAt,
        orgId: plan.orgId,
      }
      await tx.insertRun(runRow)

      if (options.dryRun) return

      for (const entity of plan.entities) {
        if (entity.rows.length === 0) continue
        const rows: StagingSeedArtifactRow[] = entity.rows.map((row) => ({
          app: plan.app,
          orgId: plan.orgId,
          entityType: entity.entityType,
          entityId: row.id,
          profile: plan.profile,
          seed: plan.seed,
          runId,
          payload: row,
        }))
        await tx.upsertArtifacts(rows)
      }
    })
  } catch (err) {
    status = 'error'
    errorMessage = (err as Error).message
  }

  // Best-effort run-finish in a separate transaction so an error during
  // artifact writes is still recorded.
  const finishedAtDate = options.now?.() ?? new Date()
  const durationMs = finishedAtDate.getTime() - startMs
  try {
    await adapter.withTransaction(async (tx) => {
      await tx.finishRun({
        runId,
        finishedAt: finishedAtDate.toISOString(),
        durationMs,
        status,
        totals,
        errorMessage,
      })
    })
  } catch {
    // If even the audit write fails (e.g. DB went away), surface the
    // original error rather than masking it with the audit failure.
  }

  if (status === 'error') {
    const err = new Error(errorMessage ?? 'staging-seed persist failed')
    ;(err as Error & { runId?: string }).runId = runId
    throw err
  }

  return { runId, status, totals, durationMs }
}

/**
 * Reset: deletes all artifacts whose org id is in the allowlist. Caller
 * MUST pre-validate every id with {@link assertSafeStagingOrgId}.
 */
export async function resetForOrgs(
  adapter: DbAdapter,
  orgIds: readonly string[],
): Promise<Record<string, number>> {
  for (const id of orgIds) assertSafeStagingOrgId(id)
  if (orgIds.length === 0) return {}
  return adapter.withTransaction((tx) => tx.deleteArtifactsForOrgs(orgIds))
}
