-- Fixup: create break_glass_activations table if it was missing from migration
-- 0004_phase2_complete (schema gap — present in 0004 snapshot but not the SQL file).
-- Uses IF NOT EXISTS so this is a no-op on databases where the table already exists.
CREATE TABLE IF NOT EXISTS "break_glass_activations" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "break_glass_system_id" uuid NOT NULL,
  "activation_type" varchar(20) NOT NULL,
  "activation_reason" text NOT NULL,
  "emergency_level" varchar(20) NOT NULL,
  "activated_at" timestamp DEFAULT now() NOT NULL,
  "resolved_at" timestamp,
  "recovery_duration" varchar(50),
  "required_signatures" integer DEFAULT 3 NOT NULL,
  "signatures_received" integer DEFAULT 0 NOT NULL,
  "signature_1_user_id" uuid,
  "signature_1_timestamp" timestamp,
  "signature_1_ip_address" varchar(45),
  "signature_2_user_id" uuid,
  "signature_2_timestamp" timestamp,
  "signature_2_ip_address" varchar(45),
  "signature_3_user_id" uuid,
  "signature_3_timestamp" timestamp,
  "signature_3_ip_address" varchar(45),
  "signature_4_user_id" uuid,
  "signature_4_timestamp" timestamp,
  "signature_4_ip_address" varchar(45),
  "signature_5_user_id" uuid,
  "signature_5_timestamp" timestamp,
  "signature_5_ip_address" varchar(45),
  "authorization_complete" boolean DEFAULT false NOT NULL,
  "authorization_completed_at" timestamp,
  "recovery_actions_log" jsonb,
  "swiss_cold_storage_accessed" boolean DEFAULT false NOT NULL,
  "cold_storage_accessed_at" timestamp,
  "incident_report_url" text,
  "lessons_learned_url" text,
  "system_updates_required" jsonb,
  "activated_by" uuid NOT NULL,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);
