"""
Admin configuration for billing app.
Auto-generated by Nzila Code Generator — 2026-02-17
"""
from django.contrib import admin
from .models import (OrganizationSubscriptions, SeatAllocations, SubscriptionInvoices)


@admin.register(OrganizationSubscriptions)
class OrganizationSubscriptionsAdmin(admin.ModelAdmin):
    list_display = ['id', 'status', 'created_at']
    search_fields = ['stripe_customer_id', 'tier', 'status', 'currency']
    ordering = ['-created_at']


@admin.register(SeatAllocations)
class SeatAllocationsAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    search_fields = ['role_in_org']
    ordering = ['-created_at']


@admin.register(SubscriptionInvoices)
class SubscriptionInvoicesAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    search_fields = ['stripe_charge_id', 'currency']
    ordering = ['-created_at']
