"""
Django models for billing app.
Auto-generated by Nzila Code Generator — 2026-02-17

DO NOT EDIT manually unless you know what you're doing.
Re-run the generator to overwrite.
"""
import uuid
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.contrib.postgres.search import SearchVectorField

try:
    from pgvector.django import VectorField
except ImportError:
    VectorField = None  # pgvector not installed


class BaseModel(models.Model):
    """Abstract base with standard audit fields."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class OrganizationModel(BaseModel):
    """Abstract base for multi-organization models."""
    organization = models.ForeignKey(
        'auth_core.Organizations',
        on_delete=models.CASCADE,
        related_name='%(class)ss'
    )

    class Meta:
        abstract = True



class OrganizationSubscriptions(BaseModel):
    """Migrated from sql: 20250129000004_organization_subscriptions.sql"""
    organization_id = models.UUIDField(null=True, blank=True)
    stripe_customer_id = models.TextField(null=True, blank=True)
    tier = models.TextField(null=True, blank=True)
    status = models.TextField(null=True, blank=True)
    seats_used = models.IntegerField(null=True, blank=True)
    billing_address = models.JSONField(default=dict, null=True, blank=True)
    currency = models.TextField(null=True, blank=True)
    billing_interval = models.TextField(null=True, blank=True)
    current_period_end = models.DateTimeField(null=True, blank=True)
    trial_start = models.DateTimeField(null=True, blank=True)
    trial_end = models.DateTimeField(null=True, blank=True)
    canceled_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'organization_subscriptions'
        verbose_name = 'OrganizationSubscriptions'
        ordering = ['-created_at']

class SeatAllocations(BaseModel):
    """Migrated from sql: 20250129000004_organization_subscriptions.sql"""
    subscription_id = models.UUIDField(null=True, blank=True)
    user_id = models.UUIDField(null=True, blank=True)
    role_in_org = models.TextField(null=True, blank=True)
    revoked_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'seat_allocations'
        verbose_name = 'SeatAllocations'
        ordering = ['-created_at']

class SubscriptionInvoices(BaseModel):
    """Migrated from sql: 20250129000004_organization_subscriptions.sql"""
    subscription_id = models.UUIDField(null=True, blank=True)
    stripe_charge_id = models.TextField(null=True, blank=True)
    amount_paid = models.IntegerField(null=True, blank=True)
    currency = models.TextField(null=True, blank=True)
    tax_amount = models.IntegerField(null=True, blank=True)
    tax_breakdown = models.JSONField(default=dict, null=True, blank=True)
    due_date = models.DateTimeField(null=True, blank=True)
    paid_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'subscription_invoices'
        verbose_name = 'SubscriptionInvoices'
        ordering = ['-created_at']