"""
URL configuration for billing app.
Auto-generated by Nzila Code Generator — 2026-02-17
"""
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

router = DefaultRouter()
router.register(r'organization-subscriptions', views.OrganizationSubscriptionsViewSet)
router.register(r'seat-allocations', views.SeatAllocationsViewSet)
router.register(r'subscription-invoices', views.SubscriptionInvoicesViewSet)

app_name = 'billing'

urlpatterns = [
    path('', include(router.urls)),
]