"""
DRF viewsets for billing app.
Auto-generated by Nzila Code Generator — 2026-02-17
"""
from rest_framework import viewsets, permissions, filters
from django_filters.rest_framework import DjangoFilterBackend
from .models import (OrganizationSubscriptions, SeatAllocations, SubscriptionInvoices)
from .serializers import (OrganizationSubscriptionsSerializer, SeatAllocationsSerializer, SubscriptionInvoicesSerializer)


class OrganizationSubscriptionsViewSet(viewsets.ModelViewSet):
    """API endpoint for OrganizationSubscriptions operations."""
    queryset = OrganizationSubscriptions.objects.all()
    serializer_class = OrganizationSubscriptionsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    search_fields = ['stripe_customer_id', 'tier', 'status', 'currency', 'billing_interval']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class SeatAllocationsViewSet(viewsets.ModelViewSet):
    """API endpoint for SeatAllocations operations."""
    queryset = SeatAllocations.objects.all()
    serializer_class = SeatAllocationsSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    search_fields = ['role_in_org']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']


class SubscriptionInvoicesViewSet(viewsets.ModelViewSet):
    """API endpoint for SubscriptionInvoices operations."""
    queryset = SubscriptionInvoices.objects.all()
    serializer_class = SubscriptionInvoicesSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    search_fields = ['stripe_charge_id', 'currency']
    ordering_fields = ['created_at', 'updated_at']
    ordering = ['-created_at']
