import type { DecisionEvidencePack, SealedDecisionEvidencePack } from './schema.js'

// ─── JSON Export ──────────────────────────────────────────────────────────────

/**
 * Serialise a sealed evidence pack as machine-readable JSON.
 * Suitable for storage, API delivery, and AI retrieval.
 */
export function exportAsJson(sealed: SealedDecisionEvidencePack): string {
  return JSON.stringify(
    {
      $schema: 'https://nzila.os/schemas/decision-evidence/v1.0.0.json',
      sealHash: sealed.sealHash,
      sealedAt: sealed.sealedAt,
      pack: sealed.pack,
    },
    null,
    2,
  )
}

// ─── Markdown Export ─────────────────────────────────────────────────────────

/**
 * Render a sealed evidence pack as a human-readable Markdown document.
 * Procurement-safe format suitable for audit, regulatory, and executive review.
 */
export function exportAsMarkdown(sealed: SealedDecisionEvidencePack): string {
  const { pack } = sealed
  const lines: string[] = []

  lines.push(`# Decision Evidence Pack`)
  lines.push(``)
  lines.push(`**Pack ID:** \`${pack.id}\``)
  lines.push(`**Organisation:** \`${pack.orgId}\``)
  lines.push(`**Classification:** ${pack.classification}`)
  lines.push(`**Sealed At:** ${pack.sealedAt ?? 'Not yet sealed'}`)
  lines.push(`**Seal Hash:** \`${sealed.sealHash}\``)
  lines.push(`**Schema Version:** ${pack.schemaVersion}`)
  lines.push(``)

  lines.push(`---`)
  lines.push(``)
  lines.push(`## Executive Summary`)
  lines.push(``)
  lines.push(pack.executiveSummary)
  lines.push(``)

  lines.push(`---`)
  lines.push(``)
  lines.push(`## Decision`)
  lines.push(``)
  lines.push(`**Title:** ${pack.decisionTitle}`)
  lines.push(``)
  lines.push(`**Outcome:** ${pack.decisionOutcome}`)
  lines.push(``)

  if (pack.timeline.length > 0) {
    lines.push(`---`)
    lines.push(``)
    lines.push(`## Decision Timeline`)
    lines.push(``)
    for (const event of pack.timeline) {
      lines.push(`- **${event.at}** — ${event.actor}: ${event.event}`)
    }
    lines.push(``)
  }

  if (pack.evidenceRefs.length > 0) {
    lines.push(`---`)
    lines.push(``)
    lines.push(`## Evidence References`)
    lines.push(``)
    lines.push(`| Ref ID | Type | Description | Captured At |`)
    lines.push(`|--------|------|-------------|-------------|`)
    for (const ref of pack.evidenceRefs) {
      lines.push(`| \`${ref.refId}\` | ${ref.refType} | ${ref.description} | ${ref.capturedAt} |`)
    }
    lines.push(``)
  }

  if (pack.alternativesRejected.length > 0) {
    lines.push(`---`)
    lines.push(``)
    lines.push(`## Alternatives Considered and Rejected`)
    lines.push(``)
    for (const alt of pack.alternativesRejected) {
      lines.push(`### ${alt.name}`)
      lines.push(``)
      lines.push(`**Rejection reason:** ${alt.reason}`)
      lines.push(``)
    }
  }

  if (pack.acceptedRisks.length > 0) {
    lines.push(`---`)
    lines.push(``)
    lines.push(`## Accepted Risks`)
    lines.push(``)
    lines.push(`| Risk | Severity | Accepted By | Mitigation Plan |`)
    lines.push(`|------|----------|-------------|-----------------|`)
    for (const risk of pack.acceptedRisks) {
      lines.push(`| ${risk.risk} | ${risk.severity}/5 | ${risk.acceptedBy} | ${risk.mitigationPlan} |`)
    }
    lines.push(``)
  }

  if (pack.mitigationPlans.length > 0) {
    lines.push(`---`)
    lines.push(``)
    lines.push(`## Mitigation Commitments`)
    lines.push(``)
    for (const plan of pack.mitigationPlans) {
      lines.push(`- **${plan.commitment}** — Owner: ${plan.owner}, Target: ${plan.targetDate ?? 'TBD'}, Status: ${plan.status}`)
    }
    lines.push(``)
  }

  if (pack.continuityImplications.length > 0) {
    lines.push(`---`)
    lines.push(``)
    lines.push(`## Continuity Implications`)
    lines.push(``)
    for (const impl of pack.continuityImplications) {
      lines.push(`- ${impl}`)
    }
    lines.push(``)
  }

  if (pack.approvers.length > 0) {
    lines.push(`---`)
    lines.push(``)
    lines.push(`## Approvers`)
    lines.push(``)
    lines.push(`| Actor | Role | Approved At | Notes |`)
    lines.push(`|-------|------|-------------|-------|`)
    for (const approver of pack.approvers) {
      lines.push(`| ${approver.actorId} | ${approver.role} | ${approver.approvedAt} | ${approver.notes} |`)
    }
    lines.push(``)
  }

  lines.push(`---`)
  lines.push(``)
  lines.push(`## Integrity`)
  lines.push(``)
  lines.push(`**Pack Hash:** \`${pack.packHash ?? 'Not computed'}\``)
  lines.push(`**Previous Pack Hash:** \`${pack.prevPackHash ?? 'Genesis'}\``)
  lines.push(``)
  lines.push(`*This document is an append-only governance artifact generated by Nzila OS.*`)

  return lines.join('\n')
}

// ─── Render policy replay table ───────────────────────────────────────────────

export function renderPolicyReplaySection(pack: DecisionEvidencePack): string {
  if (pack.policyReplayOutputs.length === 0) return ''

  const lines: string[] = []
  lines.push(`## Policy Replay`)
  lines.push(``)
  lines.push(`| Policy | Replayed At | Result | Notes |`)
  lines.push(`|--------|-------------|--------|-------|`)
  for (const replay of pack.policyReplayOutputs) {
    lines.push(`| ${replay.policyRef} | ${replay.replayedAt} | ${replay.result.toUpperCase()} | ${replay.notes} |`)
  }
  return lines.join('\n')
}
