import { readFileSync, existsSync } from 'node:fs'
import { resolve, join } from 'node:path'
import type { NextRequest } from 'next/server'

/**
 * Serves the generated OpenAPI spec for the current app.
 *
 * Usage — create `app/api/docs/openapi.json/route.ts`:
 *   import { createOpenApiHandler } from '@nzila/os-core/openapi'
 *   export const GET = createOpenApiHandler('web')
 *
 * Specs are generated by `tooling/openapi-gen` and stored in `docs/api/specs/`.
 */
export function createOpenApiHandler(appName: string) {
  return function GET(_req: NextRequest) {
    // Walk up from the app's .next dir to find the monorepo root
    const root = resolve(process.cwd(), '..', '..')
    const specPath = join(root, 'docs', 'api', 'specs', `${appName}.json`)

    if (!existsSync(specPath)) {
      return Response.json(
        { error: `OpenAPI spec not found for app "${appName}". Run: pnpm openapi:gen` },
        { status: 404 },
      )
    }

    const spec = readFileSync(specPath, 'utf-8')
    return new Response(spec, {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
        'Cache-Control': 'public, max-age=3600',
      },
    })
  }
}
