ALTER TABLE safety_policies
  ADD COLUMN policy_title varchar(500),
  ADD COLUMN policy_category varchar(100),
  ADD COLUMN policy_type varchar(100),
  ADD COLUMN policy_description text,
  ADD COLUMN purpose text,
  ADD COLUMN scope text,
  ADD COLUMN applicability text,
  ADD COLUMN responsibilities text,
  ADD COLUMN procedures text,
  ADD COLUMN definitions jsonb,
  ADD COLUMN "references" text,
  ADD COLUMN document_id uuid,
  ADD COLUMN document_url text,
  ADD COLUMN version varchar(20) DEFAULT '1.0',
  ADD COLUMN revision_history jsonb,
  ADD COLUMN effective_date date,
  ADD COLUMN review_date date,
  ADD COLUMN next_review_date date,
  ADD COLUMN expiry_date date,
  ADD COLUMN review_frequency_months integer DEFAULT 12,
  ADD COLUMN status varchar(50) DEFAULT 'draft',
  ADD COLUMN drafted_by_id uuid,
  ADD COLUMN drafted_by_name varchar(255),
  ADD COLUMN drafted_date date,
  ADD COLUMN reviewed_by_id uuid,
  ADD COLUMN reviewed_by_name varchar(255),
  ADD COLUMN reviewed_date date,
  ADD COLUMN review_comments text,
  ADD COLUMN approved_by_id uuid,
  ADD COLUMN approved_by_name varchar(255),
  ADD COLUMN approval_date date,
  ADD COLUMN approval_comments text,
  ADD COLUMN regulatory_requirement boolean DEFAULT false,
  ADD COLUMN regulatory_reference varchar(500),
  ADD COLUMN legislation_citation text,
  ADD COLUMN training_required boolean DEFAULT false,
  ADD COLUMN training_course_ids jsonb,
  ADD COLUMN communication_plan text,
  ADD COLUMN affected_employees jsonb,
  ADD COLUMN affected_departments jsonb,
  ADD COLUMN acknowledgement_required boolean DEFAULT false,
  ADD COLUMN acknowledged_by jsonb,
  ADD COLUMN related_policy_ids jsonb,
  ADD COLUMN superseded_policy_ids jsonb,
  ADD COLUMN metadata jsonb,
  ADD COLUMN tags jsonb,
  ADD COLUMN keywords jsonb,
  ADD COLUMN notes text,
  ADD COLUMN created_by uuid,
  ADD COLUMN updated_by uuid;

CREATE INDEX IF NOT EXISTS idx_policies_org ON safety_policies(organization_id);
CREATE INDEX IF NOT EXISTS idx_policies_status ON safety_policies(status);
CREATE INDEX IF NOT EXISTS idx_policies_category ON safety_policies(policy_category);
CREATE INDEX IF NOT EXISTS idx_policies_review ON safety_policies(next_review_date);
CREATE INDEX IF NOT EXISTS idx_policies_effective ON safety_policies(effective_date);
