-- Zonga test data: orgs + org_members
-- Generated by scripts/zonga-clerk-provision.mjs
-- Date: 2026-03-30T15:27:31.715Z

-- Ensure label org exists in DB
INSERT INTO orgs (id, legal_name, jurisdiction, clerk_org_id, status, created_at, updated_at)
VALUES ('33333333-3333-3333-3333-333333333333', 'Afrobeats Records', 'NG', 'org_3BeNcTQmwLkUi87WJ2wHnVruj1G', 'active', NOW(), NOW())
ON CONFLICT (id) DO UPDATE SET clerk_org_id = EXCLUDED.clerk_org_id, updated_at = NOW();

-- Ensure Nzila platform org clerk_org_id is up to date
UPDATE orgs SET clerk_org_id = 'org_3BEaESt8ZIC4XEdJ7hmmB6nu6pp', updated_at = NOW() WHERE id = '8b97760c-1122-4fdf-8721-68e20d0ab3f5';

-- Test user org memberships (delete-then-insert since no composite unique constraint)
DELETE FROM org_members WHERE org_id = '33333333-3333-3333-3333-333333333333' AND clerk_user_id = 'user_3BeNTNcKj5yvqOjyf6bw0UoiMSj';
INSERT INTO org_members (org_id, clerk_user_id, role, status, created_at, updated_at)
VALUES ('33333333-3333-3333-3333-333333333333', 'user_3BeNTNcKj5yvqOjyf6bw0UoiMSj', 'org_admin', 'active', NOW(), NOW());
DELETE FROM org_members WHERE org_id = '33333333-3333-3333-3333-333333333333' AND clerk_user_id = 'user_3BeNTY8hUfzN5H3KCeXN3TaEcl4';
INSERT INTO org_members (org_id, clerk_user_id, role, status, created_at, updated_at)
VALUES ('33333333-3333-3333-3333-333333333333', 'user_3BeNTY8hUfzN5H3KCeXN3TaEcl4', 'org_secretary', 'active', NOW(), NOW());
DELETE FROM org_members WHERE org_id = '33333333-3333-3333-3333-333333333333' AND clerk_user_id = 'user_3BeNTURDz3UTu1kleGlGuRjWYJi';
INSERT INTO org_members (org_id, clerk_user_id, role, status, created_at, updated_at)
VALUES ('33333333-3333-3333-3333-333333333333', 'user_3BeNTURDz3UTu1kleGlGuRjWYJi', 'org_creator', 'active', NOW(), NOW());
DELETE FROM org_members WHERE org_id = '33333333-3333-3333-3333-333333333333' AND clerk_user_id = 'user_3BeNTfkLptcA8UhtH6ZX9ANGpqB';
INSERT INTO org_members (org_id, clerk_user_id, role, status, created_at, updated_at)
VALUES ('33333333-3333-3333-3333-333333333333', 'user_3BeNTfkLptcA8UhtH6ZX9ANGpqB', 'org_viewer', 'active', NOW(), NOW());
DELETE FROM org_members WHERE org_id = '8b97760c-1122-4fdf-8721-68e20d0ab3f5' AND clerk_user_id = 'user_3BeNTjspeqrQym0nnRBcS4EQD0w';
INSERT INTO org_members (org_id, clerk_user_id, role, status, created_at, updated_at)
VALUES ('8b97760c-1122-4fdf-8721-68e20d0ab3f5', 'user_3BeNTjspeqrQym0nnRBcS4EQD0w', 'org_secretary', 'active', NOW(), NOW());
DELETE FROM org_members WHERE org_id = '8b97760c-1122-4fdf-8721-68e20d0ab3f5' AND clerk_user_id = 'user_3BeNTjA1LiB1OUFr3dRvXuJAx1D';
INSERT INTO org_members (org_id, clerk_user_id, role, status, created_at, updated_at)
VALUES ('8b97760c-1122-4fdf-8721-68e20d0ab3f5', 'user_3BeNTjA1LiB1OUFr3dRvXuJAx1D', 'org_viewer', 'active', NOW(), NOW());

-- Listener profiles (zonga_listeners table)
DELETE FROM zonga_listeners WHERE id = '44444444-4444-4444-4444-444444444401';
INSERT INTO zonga_listeners (id, org_id, display_name, email, country, plan, subscription_status, preferences_json, created_at, updated_at)
VALUES ('44444444-4444-4444-4444-444444444401', '33333333-3333-3333-3333-333333333333', 'FreeBeats Fan', 'listener-free@zonga-test.dev', 'NG', 'free', NULL, '{}', NOW(), NOW());
DELETE FROM zonga_listeners WHERE id = '44444444-4444-4444-4444-444444444402';
INSERT INTO zonga_listeners (id, org_id, display_name, email, country, plan, subscription_status, preferences_json, created_at, updated_at)
VALUES ('44444444-4444-4444-4444-444444444402', '33333333-3333-3333-3333-333333333333', 'PremiumBeats VIP', 'listener-premium@zonga-test.dev', 'NG', 'premium', 'active', '{}', NOW(), NOW());
