/**
 * @nzila/itsm-core — Ticket number generator
 *
 * Produces human-readable ticket numbers scoped to org.
 * Format: PREFIX-NNNN  (e.g. INC-0042, CHG-0007, PRB-0001)
 */
import type { TicketType } from './types'

const TYPE_PREFIX: Record<TicketType, string> = {
  incident: 'INC',
  service_request: 'SRQ',
  access_request: 'ACC',
  change_request: 'CHG',
  problem: 'PRB',
  procurement: 'PRC',
  vendor_escalation: 'VEN',
  security_event: 'SEC',
  project_task: 'TSK',
}

/**
 * Generates a zero-padded ticket number string.
 * @param type  — ticket type
 * @param seq   — monotonically incrementing integer (stored in DB or generated by sequence)
 */
export function generateTicketNumber(type: TicketType, seq: number): string {
  const prefix = TYPE_PREFIX[type]
  const padded = String(seq).padStart(4, '0')
  return `${prefix}-${padded}`
}

/**
 * Returns just the prefix for a given ticket type (for DB LIKE queries).
 */
export function ticketNumberPrefix(type: TicketType): string {
  return TYPE_PREFIX[type]
}
