"""
Admin configuration for auth_core app.
Auto-generated by Nzila Code Generator — 2026-02-17
"""
from django.contrib import admin
from .models import (Organizations, Profiles, Roles, Permissions, RolePermissions, UserRoles, AuditLogs)


@admin.register(Organizations)
class OrganizationsAdmin(admin.ModelAdmin):
    list_display = ['id', 'name', 'slug']
    list_filter = ['subscription_status']
    search_fields = ['name', 'slug', 'domain', 'logo_url']
    ordering = ['-created_at']


@admin.register(Profiles)
class ProfilesAdmin(admin.ModelAdmin):
    list_display = ['id']
    list_filter = ['email_verified']
    search_fields = ['first_name', 'last_name', 'display_name', 'avatar_url']
    ordering = ['-created_at']


@admin.register(Roles)
class RolesAdmin(admin.ModelAdmin):
    list_display = ['id', 'name', 'slug']
    search_fields = ['name', 'slug', 'description']
    ordering = ['-created_at']


@admin.register(Permissions)
class PermissionsAdmin(admin.ModelAdmin):
    list_display = ['id', 'name', 'slug']
    list_filter = ['is_system']
    search_fields = ['name', 'slug', 'resource']
    ordering = ['-created_at']


@admin.register(RolePermissions)
class RolePermissionsAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    ordering = ['-created_at']


@admin.register(UserRoles)
class UserRolesAdmin(admin.ModelAdmin):
    list_display = ['id']
    ordering = ['-created_at']


@admin.register(AuditLogs)
class AuditLogsAdmin(admin.ModelAdmin):
    list_display = ['id']
    search_fields = ['user_agent']
    ordering = ['-created_at']
