"""
Django models for auth_core app.
Auto-generated by Nzila Code Generator — 2026-02-17

DO NOT EDIT manually unless you know what you're doing.
Re-run the generator to overwrite.
"""

import uuid
from typing import TYPE_CHECKING

from django.contrib.postgres.fields import ArrayField
from django.contrib.postgres.search import SearchVectorField
from django.db import models

if TYPE_CHECKING:
    from pgvector.django import VectorField  # type: ignore[import-unresolved]
else:
    try:
        from pgvector.django import VectorField
    except ImportError:
        VectorField = None  # pgvector not installed


class BaseModel(models.Model):
    """Abstract base with standard audit fields."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class OrganizationModel(BaseModel):
    """Abstract base for multi-organization models."""

    organization = models.ForeignKey(
        "auth_core.Organizations", on_delete=models.CASCADE, related_name="%(class)ss"
    )

    class Meta:
        abstract = True


class Organizations(BaseModel):
    """
    Hierarchical Organizations table for multi-tenancy.
    Merged schema from Union Eyes (CLC features) + ABR Insights (subscription features).

    Source: schema-organizations.ts (UE) + 001_initial_schema.sql (ABR)
    """

    # Enum Choices
    ORGANIZATION_TYPE_CHOICES = [
        ("congress", "Congress"),
        ("federation", "Federation"),
        ("union", "Union"),
        ("local", "Local"),
        ("region", "Region"),
        ("district", "District"),
    ]

    LABOUR_SECTOR_CHOICES = [
        ("healthcare", "Healthcare"),
        ("education", "Education"),
        ("public_service", "Public Service"),
        ("trades", "Trades"),
        ("manufacturing", "Manufacturing"),
        ("transportation", "Transportation"),
        ("retail", "Retail"),
        ("hospitality", "Hospitality"),
        ("technology", "Technology"),
        ("construction", "Construction"),
        ("utilities", "Utilities"),
        ("telecommunications", "Telecommunications"),
        ("financial_services", "Financial Services"),
        ("agriculture", "Agriculture"),
        ("arts_culture", "Arts and Culture"),
        ("other", "Other"),
    ]

    ORGANIZATION_STATUS_CHOICES = [
        ("active", "Active"),
        ("inactive", "Inactive"),
        ("suspended", "Suspended"),
        ("archived", "Archived"),
    ]

    SUBSCRIPTION_STATUS_CHOICES = [
        ("active", "Active"),
        ("cancelled", "Cancelled"),
        ("past_due", "Past Due"),
        ("suspended", "Suspended"),
        ("trialing", "Trialing"),
    ]

    # Primary Key

    # Basic Information
    name = models.TextField()
    slug = models.TextField(unique=True)
    display_name = models.TextField(null=True, blank=True)
    short_name = models.TextField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    # ABR-specific: Branding
    domain = models.CharField(max_length=255, null=True, blank=True)
    logo_url = models.TextField(null=True, blank=True)

    # Hierarchy (UE-specific, optional for ABR)
    organization_type = models.CharField(
        max_length=20, choices=ORGANIZATION_TYPE_CHOICES, null=True, blank=True
    )
    parent = models.ForeignKey(
        "self",
        on_delete=models.RESTRICT,
        null=True,
        blank=True,
        related_name="children",
        db_column="parent_id",
    )
    hierarchy_path = ArrayField(
        models.TextField(),
        default=list,
        blank=True,
        help_text="Array of ancestor organization IDs from root to this node",
    )
    hierarchy_level = models.IntegerField(
        default=0, help_text="Distance from root (0 = root organization)"
    )

    # Jurisdiction & Sectors (UE-specific)
    province_territory = models.TextField(null=True, blank=True)
    sectors = ArrayField(
        models.CharField(max_length=30, choices=LABOUR_SECTOR_CHOICES),
        default=list,
        blank=True,
    )

    # Contact & Metadata
    email = models.TextField(null=True, blank=True)
    phone = models.TextField(null=True, blank=True)
    website = models.TextField(null=True, blank=True)
    address = models.JSONField(
        null=True,
        blank=True,
        help_text="Format: {street, unit, city, province, postal_code, country}",
    )

    # CLC Affiliation (UE-specific)
    clc_affiliated = models.BooleanField(
        default=False, help_text="Whether affiliated with Canadian Labour Congress"
    )
    affiliation_date = models.DateField(null=True, blank=True)
    charter_number = models.TextField(null=True, blank=True)

    # Membership Counts (cached) - UE feature
    member_count = models.IntegerField(default=0)
    active_member_count = models.IntegerField(default=0)
    last_member_count_update = models.DateTimeField(null=True, blank=True)

    # Subscription & Billing (merged UE + ABR)
    subscription_tier = models.TextField(null=True, blank=True)  # UE
    subscription_status = models.CharField(
        max_length=50,
        choices=SUBSCRIPTION_STATUS_CHOICES,
        default="active",
        null=True,
        blank=True,
    )  # ABR
    subscription_start_date = models.DateTimeField(null=True, blank=True)  # ABR
    subscription_end_date = models.DateTimeField(null=True, blank=True)  # ABR
    trial_ends_at = models.DateTimeField(null=True, blank=True)  # ABR
    stripe_subscription_id = models.CharField(
        max_length=255, null=True, blank=True
    )  # ABR
    billing_email = models.CharField(
        max_length=255, null=True, blank=True
    )  # ABR (vs UE's generic email)
    billing_contact_id = models.UUIDField(null=True, blank=True)  # UE

    # Storage & Resources (ABR-specific)
    storage_limit_gb = models.IntegerField(null=True, blank=True)

    # Settings & Features
    settings = models.JSONField(
        default=dict,
        help_text="Flexible config: {perCapitaRate, remittanceDay, fiscalYearEnd, customFields}",
    )
    features_enabled = ArrayField(models.TextField(), default=list, blank=True)
    metadata = models.JSONField(default=dict, null=True, blank=True)

    # Status & Audit
    status = models.CharField(
        max_length=20, choices=ORGANIZATION_STATUS_CHOICES, default="active"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(null=True, blank=True)  # ABR soft delete
    created_by = models.UUIDField(null=True, blank=True)

    # Legacy & Migration
    legacy_org_id = models.UUIDField(
        null=True,
        blank=True,
        db_index=True,
        db_column="legacy_tenant_id",
        help_text=(
            "Read-only. Historical ID carried over from the pre-NzilaOS system. "
            "Maps to the current Organization via external_id. "
            "Do NOT reference in new code — use organization.id or organization.external_id."
        ),
    )

    # CLC Financial Fields (UE-specific)
    clc_affiliate_code = models.CharField(max_length=20, null=True, blank=True)
    per_capita_rate = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="Default per-capita rate for remittances",
    )
    remittance_day = models.IntegerField(
        default=15,
        null=True,
        blank=True,
        help_text="Day of month for remittances (1-31)",
    )
    last_remittance_date = models.DateTimeField(null=True, blank=True)
    fiscal_year_end = models.DateField(
        null=True, blank=True, help_text="e.g., March 31"
    )

    # Clerk Integration
    clerk_organization_id = models.TextField(
        null=True,
        blank=True,
        unique=True,
        db_index=True,
        help_text="Clerk organization ID (e.g. org_2abc...) — set by webhook on organization.created",
    )

    class Meta:
        db_table = "organizations"
        verbose_name = "Organization"
        verbose_name_plural = "Organizations"
        ordering = ["name"]
        indexes = [
            models.Index(fields=["parent"], name="idx_organizations_parent"),
            models.Index(fields=["organization_type"], name="idx_organizations_type"),
            models.Index(fields=["slug"], name="idx_organizations_slug"),
            models.Index(fields=["hierarchy_level"], name="idx_org_hier_level"),
            models.Index(fields=["status"], name="idx_organizations_status"),
            models.Index(fields=["clc_affiliated"], name="idx_org_clc_affiliated"),
            models.Index(fields=["legacy_org_id"], name="idx_org_legacy_tenant"),
        ]

    def __str__(self):
        return self.name or self.slug

    def is_clc_root(self):
        """Check if this is the CLC root organization."""
        return self.organization_type == "congress" and self.parent is None

    def is_national_union(self):
        """Check if this is a national union (level 1 under CLC)."""
        return self.organization_type == "union" and self.hierarchy_level == 1

    def is_local_union(self):
        """Check if this is a local union."""
        return self.organization_type == "local"

    def is_federation(self):
        """Check if this is a federation."""
        return self.organization_type == "federation"


class OrganizationRelationships(BaseModel):
    """
    Tracks relationships between organizations beyond hierarchy.
    Examples: affiliations, mergers, splits, joint councils.

    Migrated from Drizzle schema: schema-organizations.ts (UE)
    """

    RELATIONSHIP_TYPE_CHOICES = [
        ("affiliate", "Affiliate"),
        ("federation", "Federation"),
        ("local", "Local"),
        ("chapter", "Chapter"),
        ("region", "Region"),
        ("district", "District"),
        ("joint_council", "Joint Council"),
        ("merged_from", "Merged From"),
        ("split_from", "Split From"),
    ]

    # Relationship Parties
    parent_org = models.ForeignKey(
        Organizations,
        on_delete=models.CASCADE,
        related_name="child_relationships",
        db_column="parent_org_id",
    )
    child_org = models.ForeignKey(
        Organizations,
        on_delete=models.CASCADE,
        related_name="parent_relationships",
        db_column="child_org_id",
    )

    # Relationship Type
    relationship_type = models.CharField(
        max_length=20, choices=RELATIONSHIP_TYPE_CHOICES
    )

    # Temporal Tracking
    effective_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)

    # Relationship Details
    notes = models.TextField(null=True, blank=True)
    metadata = models.JSONField(default=dict, blank=True)

    # Audit
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = "organization_relationships"
        verbose_name = "Organization Relationship"
        verbose_name_plural = "Organization Relationships"
        indexes = [
            models.Index(fields=["parent_org"], name="idx_org_relationships_parent"),
            models.Index(fields=["child_org"], name="idx_org_relationships_child"),
            models.Index(
                fields=["relationship_type"], name="idx_org_relationships_type"
            ),
        ]
        constraints = [
            models.UniqueConstraint(
                fields=[
                    "parent_org",
                    "child_org",
                    "relationship_type",
                    "effective_date",
                ],
                name="unique_org_relationship",
            )
        ]

    def __str__(self):
        return (
            f"{self.parent_org.name} → {self.child_org.name} ({self.relationship_type})"
        )


class Profiles(BaseModel):
    """Migrated from sql: 001_initial_schema.sql"""

    organization_id = models.UUIDField(null=True, blank=True)
    first_name = models.CharField(max_length=100, null=True, blank=True)
    last_name = models.CharField(max_length=100, null=True, blank=True)
    display_name = models.CharField(max_length=255, null=True, blank=True)
    avatar_url = models.TextField(null=True, blank=True)
    department = models.CharField(max_length=255, null=True, blank=True)
    employee_id = models.CharField(max_length=100, null=True, blank=True)
    timezone = models.CharField(max_length=50, null=True, blank=True)
    notification_preferences = models.JSONField(default=dict, null=True, blank=True)
    email_verified = models.BooleanField(default=False)
    onboarding_step = models.IntegerField(null=True, blank=True)
    last_activity_at = models.DateTimeField(null=True, blank=True)
    updated_at = models.DateTimeField(null=True, blank=True)
    deleted_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = "profiles"
        verbose_name = "Profiles"


class Roles(BaseModel):
    """Migrated from sql: 001_initial_schema.sql"""

    name = models.CharField(max_length=100, unique=True)
    slug = models.CharField(max_length=100, unique=True)
    description = models.TextField(null=True, blank=True)
    level = models.IntegerField(null=True, blank=True)
    updated_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = "roles"
        verbose_name = "Roles"

    def __str__(self):
        return str(self.name)


class Permissions(BaseModel):
    """Migrated from sql: 001_initial_schema.sql"""

    name = models.CharField(max_length=100, unique=True)
    slug = models.CharField(max_length=100, unique=True)
    resource = models.CharField(max_length=100)
    is_system = models.BooleanField(default=False)
    updated_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = "permissions"
        verbose_name = "Permissions"

    def __str__(self):
        return str(self.name)


class RolePermissions(BaseModel):
    """Migrated from sql: 001_initial_schema.sql"""

    role_id = models.UUIDField(null=True, blank=True)
    permission_id = models.UUIDField(null=True, blank=True)
    created_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = "role_permissions"
        verbose_name = "RolePermissions"
        constraints = [
            models.UniqueConstraint(
                fields=["role_id", "permission_id"],
                name="unique_role_permissions_role_id_permission_id",
            ),
        ]
        ordering = ["-created_at"]


class UserRoles(BaseModel):
    """Migrated from sql: 001_initial_schema.sql"""

    scope_type = models.CharField(max_length=100, null=True, blank=True)
    scope_id = models.UUIDField(null=True, blank=True)
    user_id = models.UUIDField(null=True, blank=True)
    role_id = models.UUIDField(null=True, blank=True)
    organization_id = models.UUIDField(null=True, blank=True)
    valid_until = models.DateTimeField(null=True, blank=True)
    updated_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = "user_roles"
        verbose_name = "UserRoles"
        constraints = [
            models.UniqueConstraint(
                fields=[
                    "user_id",
                    "role_id",
                    "organization_id",
                    "scope_type",
                    "scope_id",
                ],
                name="unique_user_roles_user_id_role_id_organization_id_scope_type_scope_id",
            ),
        ]


class AuditLogs(BaseModel):
    """Tamper-evident audit log with SHA-256 hash chain.

    Every write MUST call compute_content_hash() before saving.
    The chain is built by hashing:
      SHA-256(action|resource_type|resource_id|user_id|correlation_id|details|previous_hash)
    A broken chain or null content_hash indicates tampering —
    equivalent to NzilaOS computeEntryHash() invariant.
    """

    organization_id = models.UUIDField(null=True, blank=True)
    action = models.CharField(
        max_length=100,
        null=True,
        blank=True,
        help_text="Verb: create, update, delete, initiate, cancel, …",
    )
    resource_type = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        help_text="Django model class name of the affected object",
    )
    resource_id = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        help_text="PK of the affected object as string",
    )
    user_id = models.UUIDField(
        null=True, blank=True, help_text="Actor who performed the action"
    )
    ip_address = models.GenericIPAddressField(null=True, blank=True)
    user_agent = models.TextField(null=True, blank=True)
    correlation_id = models.UUIDField(
        null=True, blank=True, help_text="Ties this event to a request or workflow"
    )
    request_id = models.UUIDField(null=True, blank=True)
    details = models.JSONField(
        default=dict, null=True, blank=True, help_text="Arbitrary context payload"
    )
    changes = models.JSONField(
        default=dict,
        null=True,
        blank=True,
        help_text="Before/after diff for update events",
    )
    # ── Hash chain (INV: NzilaOS audit invariant) ───────────────────────────
    content_hash = models.CharField(
        max_length=64,
        null=True,
        blank=True,
        help_text="SHA-256 of (action|resource_type|resource_id|user_id|correlation_id|details|previous_hash)",
    )
    previous_hash = models.CharField(
        max_length=64,
        null=True,
        blank=True,
        help_text="content_hash of the immediately preceding AuditLogs record for this org. NULL for first record.",
    )

    class Meta:
        db_table = "audit_logs"
        verbose_name = "AuditLogs"
        indexes = [
            models.Index(
                fields=["organization_id", "created_at"],
                name="idx_audit_logs_org_created",
            ),
            models.Index(fields=["correlation_id"], name="idx_audit_logs_correlation"),
        ]
