/**
 * Generate governance runtime summary.
 *
 * Reads the route registry, governance contracts, and public-experience
 * registry to produce:
 *
 *   reports/governance-runtime-summary.json
 *   docs/procurement/GOVERNANCE_RUNTIME_OVERVIEW.md
 *
 * Run: `pnpm tsx scripts/generate-governance-summary.ts`
 */

import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { resolve, join } from 'path';

import { bootstrapPlatformContracts, getAllContracts } from '../lib/governance-policy/registry';
import { UE_AI_OPERATIONS } from '../lib/governance-policy/ai-governance';
import { evaluateAIAction } from '../lib/governance-policy/ai-governance';
import { PLATFORM_CONTRACTS } from '../lib/governance-policy/contracts';

bootstrapPlatformContracts();

// ── Route registry ─────────────────────────────────────────────────────────────

const routeRegistryPath = resolve(__dirname, '../reports/route-registry.json');
let routeRegistry: { routes?: unknown[] } = {};
if (existsSync(routeRegistryPath)) {
  routeRegistry = JSON.parse(require('fs').readFileSync(routeRegistryPath, 'utf-8'));
}
const routes = (routeRegistry.routes ?? []) as Array<Record<string, unknown>>;

const governedRoutes = routes.filter(
  (r) => r['governanceStatus'] !== 'ungoverned' && r['governanceStatus'] !== undefined,
);
const deprecatedRoutes = routes.filter((r) => r['governanceStatus'] === 'deprecated-warn');
const adminRoutes = routes.filter((r) =>
  Array.isArray(r['roles']) && (r['roles'] as string[]).includes('admin'),
);

// ── Contract summary ───────────────────────────────────────────────────────────

const contracts = getAllContracts();
const contractsByScope = contracts.reduce<Record<string, number>>((acc, c) => {
  acc[c.scope] = (acc[c.scope] ?? 0) + 1;
  return acc;
}, {});

// ── AI operations summary ──────────────────────────────────────────────────────

const aiSummary = UE_AI_OPERATIONS.map((op) => ({
  operationId: op.operationId,
  label: op.label,
  risk: op.risk,
  humanReviewRequired: evaluateAIAction(op).humanReviewRequired,
  auditRequired: evaluateAIAction(op).auditRequired,
}));

// ── Build summary object ───────────────────────────────────────────────────────

const summary = {
  generatedAt: new Date().toISOString(),
  version: '1.0.0',
  routes: {
    total: routes.length,
    governed: governedRoutes.length,
    deprecated: deprecatedRoutes.length,
    admin: adminRoutes.length,
  },
  contracts: {
    total: contracts.length,
    byScope: contractsByScope,
    allInShadowMode: contracts.every((c) => c.mode === 'shadow'),
  },
  aiGovernance: {
    totalOperations: aiSummary.length,
    reviewRequired: aiSummary.filter((a) => a.humanReviewRequired).length,
    auditRequired: aiSummary.filter((a) => a.auditRequired).length,
    operations: aiSummary,
  },
  publicExperience: {
    surfaceContractRegistered: contracts.some(
      (c) => c.id === 'public-experience.surface',
    ),
    federationContractRegistered: contracts.some(
      (c) => c.id === 'public-experience.federation',
    ),
  },
  governanceMode: 'shadow', // global: enforce only after full coverage confirmed
};

// ── Write JSON ─────────────────────────────────────────────────────────────────

const reportsDir = resolve(__dirname, '../reports');
mkdirSync(reportsDir, { recursive: true });

const jsonPath = join(reportsDir, 'governance-runtime-summary.json');
writeFileSync(jsonPath, JSON.stringify(summary, null, 2), 'utf-8');
console.log(`✅  governance-runtime-summary.json → ${jsonPath}`);

// ── Write Markdown (procurement overview) ─────────────────────────────────────

const procurementDir = resolve(__dirname, '../docs/procurement');
mkdirSync(procurementDir, { recursive: true });

const mdPath = join(procurementDir, 'GOVERNANCE_RUNTIME_OVERVIEW.md');

const md = `# UnionEyes — Governance Runtime Overview

> Auto-generated by \`scripts/generate-governance-summary.ts\`  
> Generated: ${summary.generatedAt}

---

## Summary

UnionEyes operates on a **closed-loop governance architecture**. Every API
route, dashboard surface, public-experience surface, and AI operation is
classified against a governance policy contract. Evaluations are logged to the
governance decision ledger.

---

## Route Governance

| Metric | Count |
|---|---|
| Total routes | ${summary.routes.total} |
| Governed routes | ${summary.routes.governed} |
| Deprecated (policy-wrapped) routes | ${summary.routes.deprecated} |
| Admin-tier routes | ${summary.routes.admin} |

All deprecated routes inherit policy governance via wrapper-level injection —
no per-route refactor required.

---

## Policy Contracts

| Metric | Value |
|---|---|
| Total registered contracts | ${summary.contracts.total} |
| Shadow mode (safe rollout) | ${summary.contracts.allInShadowMode ? 'All contracts in shadow mode' : 'Mixed modes'} |

### Contracts by scope

${Object.entries(summary.contracts.byScope)
  .map(([scope, count]) => `| ${scope} | ${count} |`)
  .join('\n')}

---

## AI Governance

| Metric | Count |
|---|---|
| Total AI operations | ${summary.aiGovernance.totalOperations} |
| Require human review | ${summary.aiGovernance.reviewRequired} |
| Require audit trail | ${summary.aiGovernance.auditRequired} |

### AI operations

| Operation | Label | Risk | Review required | Audit required |
|---|---|---|---|---|
${summary.aiGovernance.operations
  .map(
    (op) =>
      `| \`${op.operationId}\` | ${op.label} | ${op.risk} | ${op.humanReviewRequired ? '✅' : '—'} | ${op.auditRequired ? '✅' : '—'} |`,
  )
  .join('\n')}

---

## Public Experience Governance

| Contract | Registered |
|---|---|
| Public surface contract | ${summary.publicExperience.surfaceContractRegistered ? '✅' : '❌'} |
| Federation surface contract | ${summary.publicExperience.federationContractRegistered ? '✅' : '❌'} |

---

## Governance Mode

> **Current mode: ${summary.governanceMode.toUpperCase()}**

All contracts currently operate in **shadow mode**. Evaluations are logged to
the governance decision ledger but do not block production requests. Switch to
\`enforce\` mode contract-by-contract after coverage is confirmed.

---

## Architecture References

- Route registry: \`reports/route-registry.json\`
- Decision ledger: \`reports/governance-decision-ledger.json\`
- Policy contracts: \`lib/governance-policy/contracts.ts\`
- Federation inheritance: \`lib/governance-policy/inheritance.ts\`
- AI governance: \`lib/governance-policy/ai-governance.ts\`
- Public-experience binding: \`lib/public-experience/governance.ts\`
`;

writeFileSync(mdPath, md, 'utf-8');
console.log(`✅  GOVERNANCE_RUNTIME_OVERVIEW.md → ${mdPath}`);
