#!/usr/bin/env tsx
/**
 * generate-migration-manifest.ts
 *
 * Scans apps/union-eyes/db/migrations for SQL files, validates ordering
 * (no duplicate numeric prefixes), and writes a fresh MANIFEST.md.
 *
 * Usage:
 *   npx tsx apps/union-eyes/scripts/generate-migration-manifest.ts
 *   pnpm --filter @nzila/union-eyes exec tsx scripts/generate-migration-manifest.ts
 */
import * as fs from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';

const MIGRATIONS_DIR = path.resolve(__dirname, '..', 'db', 'migrations');
const MANIFEST_PATH = path.resolve(MIGRATIONS_DIR, 'MANIFEST.md');

interface MigrationEntry {
  prefix: string;
  filename: string;
  sha256: string;
  sizeKb: string;
  firstLine: string;
}

function sha256(filePath: string): string {
  const content = fs.readFileSync(filePath);
  return crypto.createHash('sha256').update(content).digest('hex');
}

function firstCommentLine(filePath: string): string {
  const lines = fs.readFileSync(filePath, 'utf-8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith('--')) return trimmed.substring(0, 80);
    if (trimmed.startsWith('--')) return trimmed.replace(/^--\s*/, '').substring(0, 80);
  }
  return '';
}

function main() {
  const files = fs.readdirSync(MIGRATIONS_DIR)
    .filter(f => f.endsWith('.sql'))
    .sort();

  const entries: MigrationEntry[] = [];
  const prefixMap = new Map<string, string[]>();
  const errors: string[] = [];

  for (const filename of files) {
    const filePath = path.join(MIGRATIONS_DIR, filename);
    const stat = fs.statSync(filePath);
    const sizeKb = (stat.size / 1024).toFixed(2);

    // Extract numeric prefix (supports 0000-style and YYYYMMDD-style)
    const numMatch = filename.match(/^(\d+)/);
    const prefix = numMatch ? numMatch[1] : filename;

    const hash = sha256(filePath);
    const shortHash = `${hash.substring(0, 8)}...${hash.substring(hash.length - 8)}`;
    const desc = firstCommentLine(filePath);

    entries.push({ prefix, filename, sha256: shortHash, sizeKb, firstLine: desc });

    const existing = prefixMap.get(prefix) ?? [];
    existing.push(filename);
    prefixMap.set(prefix, existing);
  }

  // Check for duplicate prefixes — only flag 4-digit sequential (0000-format) conflicts.
  // YYYYMMDD-style files sharing a date are intentional (alphabetical order within date);
  // they differ by description and are always uniquely identified by full filename.
  for (const [prefix, names] of prefixMap.entries()) {
    const isSequential = /^\d{4}$/.test(prefix);
    if (isSequential && names.length > 1) {
      errors.push(`DUPLICATE 4-DIGIT PREFIX ${prefix}: ${names.join(', ')}`);
    }
  }

  if (errors.length > 0) {
    console.error('\n❌  Migration manifest generation failed — resolve before regenerating:\n');
    for (const e of errors) console.error(`  • ${e}`);
    process.exit(1);
  }

  const now = new Date().toISOString();
  const repoRef = process.env.GITHUB_REPOSITORY ?? 'anungis437/nzila-os';
  const commitSha = process.env.GITHUB_SHA ?? 'local';
  const shortSha = commitSha.substring(0, 8);

  const rows = entries.map(e =>
    `| ${e.prefix} | ${e.filename} | \`${e.sha256}\` | ${e.sizeKb} KB | ${e.firstLine} |`
  ).join('\n');

  const manifest = `# Migration Manifest

**Auto-generated cryptographic verification for database migrations**

## Repository State

- **Repository:** \`${repoRef}\`
- **Branch:** main
- **Commit:** ${commitSha}
- **Short Commit:** ${shortSha}
- **Generated:** ${now}
- **Migrations Directory:** \`db/migrations\`
- **Total Migrations:** ${entries.length}

## Migration Files

| Prefix | Filename | SHA-256 Hash | Size | First Line |
|--------|----------|--------------|------|------------|
${rows}

## Verification

To verify a migration file's integrity:

\`\`\`bash
# Linux/macOS
shasum -a 256 db/migrations/<filename>.sql

# Windows (PowerShell)
Get-FileHash -Algorithm SHA256 db/migrations\\<filename>.sql
\`\`\`

Compare the output with the SHA-256 hash in this manifest.

---

*Generated by \`scripts/generate-migration-manifest.ts\`*
`;

  fs.writeFileSync(MANIFEST_PATH, manifest, 'utf-8');
  console.log(`✅  MANIFEST.md written — ${entries.length} migrations catalogued.`);
}

main();
