# Generated by Django 5.1.4 on 2026-02-18 02:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlertPreferences",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("email_notifications", models.BooleanField(default=False)),
                ("in_app_notifications", models.BooleanField(default=False)),
                ("webhook_url", models.TextField(blank=True, null=True)),
                (
                    "digest_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=17,
                        null=True,
                    ),
                ),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                ("notification_grouping", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "AlertPreferences",
                "db_table": "alert_preferences",
                "ordering": ["-created_at"],
            },
        ),
    ]
