/**
 * db/rls-storage-authority/analytics-ai.ts
 *
 * PR #752 round 9: extracted from the single-file
 * db/rls-storage-authority-manifest.ts (which exceeded the repository's
 * 8000-line hard cap at 8009 lines — see
 * tooling/contract-tests/file-size-enforcement.test.ts) into semantic
 * domain modules. This module owns: Analytics, AI/ML, insights, metrics.
 *
 * Domain boundaries were assigned mechanically by table-name keyword
 * matching against the entry's `table` field (see the one-time migration
 * script referenced in the round-9 commit message) — every entry's DATA
 * (classification, reason, privileges, authority) is unchanged from the
 * pre-split manifest; only its physical file location changed. Do not
 * hand-edit an entry's domain placement without also checking
 * db/__tests__/rls-storage-authority-registry-composition.test.ts, which
 * proves the composed registry is unaffected by which module an entry
 * lives in.
 *
 * Add NEW entries to whichever domain module most closely matches the
 * table's real subject matter; when genuinely ambiguous, prefer
 * reference-latent.ts (the catch-all) over forcing a bad fit elsewhere.
 */
import type { StorageAuthorityEntry } from './types';

export const analyticsAiEntries: StorageAuthorityEntry[] = [
  {
    table: "ai_clause_reasonings",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'aiClauseReasonings' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/ai/clause-reasoning.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "ai_copilot_sessions",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'aiCopilotSessions' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/ai/steward-copilot.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "ai_insight_reports",
    classification: "NEEDS_REVIEW",
    reason: "2 non-test reference(s) to 'aiInsightReports' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/ai/executive-insights.ts","lib/ai/financial-insights.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "ai_rate_limits",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'aiRateLimits' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "ai_usage_metrics",
    classification: "NEEDS_REVIEW",
    reason: "2 non-test reference(s) to 'aiUsageMetrics' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/ai/feedback/route.ts","lib/ai/services/cost-tracking-wrapper.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "analytics_metrics",
    classification: "NEEDS_REVIEW",
    reason: "41 non-test reference(s) to 'analyticsMetrics' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["actions/analytics-actions.ts","app/api/admin/clc/analytics/organizations/route.ts","app/api/analytics/claims/categories/route.ts","app/api/analytics/claims/route.ts","app/api/analytics/claims/stewards/route.ts","app/api/analytics/clause-stats/route.ts","app/api/analytics/comparative/route.ts","app/api/analytics/cross-org/route.ts","app/api/analytics/dashboard/route.ts","app/api/analytics/deadlines-metrics/route.ts","app/api/analytics/executive/route.ts","app/api/analytics/financial/categories/route.ts","app/api/analytics/financial/costs/route.ts","app/api/analytics/financial/outcomes/route.ts","app/api/analytics/financial/route.ts","app/api/analytics/financial/trends/route.ts","app/api/analytics/heatmap/route.ts","app/api/analytics/members/churn-risk/route.ts","app/api/analytics/members/cohorts/route.ts","app/api/analytics/members/route.ts","app/api/analytics/members/trends/route.ts","app/api/analytics/operational/bottlenecks/route.ts","app/api/analytics/operational/queues/route.ts","app/api/analytics/operational/route.ts","app/api/analytics/operational/sla/route.ts","app/api/analytics/operational/workload/route.ts","app/api/analytics/org-activity/route.ts","app/api/analytics/precedent-stats/route.ts","app/api/analytics/predictions/route.ts","app/api/analytics/refresh/route.ts","app/api/analytics/trends/route.ts","app/api/currency/convert/route.ts","app/api/metrics/route.ts","app/api/movement-insights/trends/route.ts","app/api/targets/summary/route.ts","lib/ai/insights-generator.ts","lib/api/crud-factory.ts","lib/services/lro-metrics.ts","services/financial-service/drizzle/relations.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "analytics_scheduled_reports",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'analyticsScheduledReports' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "customer_nps_surveys",
    classification: "NEEDS_REVIEW",
    reason: "RECLASSIFIED 2026-09-02 (round 7, raw-SQL LATENT-detection correction): this table was previously classified LATENT_UNREACHABLE based on a Drizzle-EXPORT-NAME-only reachability scan, which cannot find raw SQL references. A raw-SQL detection pass (see db/__tests__/rls-storage-authority-manifest-raw-sql-latent.test.ts for the detector/fixture) found real, direct raw-SQL table references (db.execute(sql`... FROM/INTO/UPDATE customer_nps_surveys ...`) or an equivalent quoted-table-name repository reference) in the file(s) listed below. Full HTTP-reachability/auth-boundary trace not yet completed.",
    supportingCapability: ["app/[locale]/dashboard/customer-success/page.tsx"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "employer_risk_scores",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'employerRiskScores' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/ai/employer-risk.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "icra_continuity_scores",
    classification: "SYSTEM_ONLY",
    reason: "ICRA_PSEUDONYMOUS_NO_LOGIN=APPROVED, ASSESSMENT_ID_AS_SOLE_BEARER_AUTHORITY=REJECTED (PR #752): the pseudonymous product model is intentional, but assessmentId alone must never authorize DB access. lib/icra/assessment-capability.ts adds a hashed, purpose-bound bearer capability; every route touching an existing assessment now verifies it before entering withSystemContext. Verified 2026-09-01 (round 7, ICRA capability architecture): only reached via withSystemContext() in the capability-gated submit routes (written alongside the maturity profile). No direct organization_id column.",
    supportingCapability: ["app/api/icra/submit/route.ts","app/api/icra/[assessmentId]/submit/route.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "SYSTEM_SCHEDULE",
    dbExecutionPrincipal: "SYSTEM_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "icra_followup_recommendations",
    classification: "SYSTEM_ONLY",
    reason: "ICRA_PSEUDONYMOUS_NO_LOGIN=APPROVED, ASSESSMENT_ID_AS_SOLE_BEARER_AUTHORITY=REJECTED (PR #752): the pseudonymous product model is intentional, but assessmentId alone must never authorize DB access. lib/icra/assessment-capability.ts adds a hashed, purpose-bound bearer capability; every route touching an existing assessment now verifies it before entering withSystemContext. Verified 2026-09-01 (round 7, ICRA capability architecture): only reached via withSystemContext() in the capability-gated submit routes. No direct organization_id column.",
    supportingCapability: ["app/api/icra/submit/route.ts","app/api/icra/[assessmentId]/submit/route.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "SYSTEM_SCHEDULE",
    dbExecutionPrincipal: "SYSTEM_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "icra_anonymized_metrics",
    classification: "LATENT_UNREACHABLE",
    reason: "Verified 2026-09-01 (round 7, ICRA capability architecture): zero non-test references to 'icraAnonymizedMetrics' anywhere in app/, actions/, lib/, or services/. No known application code path queries this table. If wired up in future for cross-org benchmark reads, prefer GLOBAL_REFERENCE_DATA (read-only, no per-org secrecy) over TENANT_RLS_REQUIRED given its anonymized/aggregate nature — re-review at that time.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "impact_metrics",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'impactMetrics' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "insight_recommendations",
    classification: "NEEDS_REVIEW",
    reason: "6 non-test reference(s) to 'insightRecommendations' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/analytics/insights/route.ts","app/api/analytics/insights/weekly-summary/route.ts","lib/ai/insights-generator.ts","services/financial-service/drizzle/relations.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "ml_predictions",
    classification: "NEEDS_REVIEW",
    reason: "13 non-test reference(s) to 'mlPredictions' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["actions/analytics-actions.ts","app/api/ml/monitoring/drift/route.ts","app/api/ml/monitoring/usage/route.ts","app/api/ml/predictions/claim-outcome/route.ts","app/api/ml/predictions/sla-breach-risk/feedback/route.ts","app/api/ml/predictions/sla-breach-risk/route.ts","app/api/ml/predictions/timeline/route.ts","app/api/ml/predictions/workload-forecast/route.ts","app/api/ml/recommendations/route.ts","lib/ai/insights-generator.ts","lib/feature-flags.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "mobile_analytics",
    classification: "NEEDS_REVIEW",
    reason: "2 non-test reference(s) to 'mobileAnalytics' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/mobile/analytics.ts","lib/mobile/mobile-engine.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "model_metadata",
    classification: "NEEDS_REVIEW",
    reason: "5 non-test reference(s) to 'modelMetadata' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/ml/predictions/churn-risk/route.ts","app/api/ml/predictions/sla-breach-risk/feedback/route.ts","app/api/ml/predictions/sla-breach-risk/route.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "page_analytics",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'pageAnalytics' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "pilot_metrics",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'pilotMetrics' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/pilot/apply/[id]/reference-profile/route.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "social_analytics",
    classification: "NEEDS_REVIEW",
    reason: "2 non-test reference(s) to 'socialAnalytics' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/social-media/analytics/route.ts","lib/social-media/social-media-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "usage_aggregates",
    classification: "NEEDS_REVIEW",
    reason: "2 non-test reference(s) to 'usageAggregates' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["services/platform-economics/billing-service.ts","services/platform-economics/usage-metering-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "usage_events",
    classification: "NEEDS_REVIEW",
    reason: "2 non-test reference(s) to 'usageEvents' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["services/platform-economics/billing-service.ts","services/platform-economics/usage-metering-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "user_engagement_scores",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'userEngagementScores' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "usage_meters",
    classification: "NEEDS_REVIEW",
    reason: "2 non-test reference(s) to 'usageMeters' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["services/platform-economics/billing-service.ts","services/platform-economics/usage-metering-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
]
