/**
 * db/rls-storage-authority/analytics-ai.ts
 *
 * PR #752 round 9: extracted from the single-file
 * db/rls-storage-authority-manifest.ts (which exceeded the repository's
 * 8000-line hard cap at 8009 lines — see
 * tooling/contract-tests/file-size-enforcement.test.ts) into semantic
 * domain modules. This module owns: Analytics, AI/ML, insights, metrics.
 *
 * Domain boundaries were assigned mechanically by table-name keyword
 * matching against the entry's `table` field (see the one-time migration
 * script referenced in the round-9 commit message) — every entry's DATA
 * (classification, reason, privileges, authority) is unchanged from the
 * pre-split manifest; only its physical file location changed. Do not
 * hand-edit an entry's domain placement without also checking
 * db/__tests__/rls-storage-authority-registry-composition.test.ts, which
 * proves the composed registry is unaffected by which module an entry
 * lives in.
 *
 * Add NEW entries to whichever domain module most closely matches the
 * table's real subject matter; when genuinely ambiguous, prefer
 * reference-latent.ts (the catch-all) over forcing a bad fit elsewhere.
 */
import type { StorageAuthorityEntry } from './types';

export const analyticsAiEntries: StorageAuthorityEntry[] = [
  {
    table: "ai_clause_reasonings",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'aiClauseReasonings' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/ai/clause-reasoning.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "ai_copilot_sessions",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'aiCopilotSessions' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/ai/steward-copilot.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "ai_insight_reports",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CLOSED (2026-09-04, round 40 SIMPLE_TENANT:org:NORMAL cohort): direct NOT NULL organization_id table, with live tenant-user routes app/api/ai/insights/[reportType]/route.ts and app/api/ai/insights/summary/route.ts reaching lib/ai/executive-insights.ts. Both routes are withRoleAuth('officer') gated; the generate path writes aiInsightReports with context.organizationId/context.userId after entitlement + AI-safety checks, and the summary path reads by eq(aiInsightReports.organizationId, context.organizationId). lib/ai/financial-insights.ts is explicitly non-persistent for this table. Minimum proven runtime DML is SELECT+INSERT, plain tenant db path, no withSystemContext.",
    supportingCapability: ["app/api/ai/insights/[reportType]/route.ts","app/api/ai/insights/summary/route.ts","lib/ai/executive-insights.ts","lib/ai/financial-insights.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "ai_rate_limits",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'aiRateLimits' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "ai_usage_metrics",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CLOSED (round 48, derived analytics and AI telemetry authority cohort): direct NOT NULL organization_id table (db/schema/domains/ml/chatbot.ts), FK to organizations. SECURITY DEFECT FOUND AND FIXED: app/api/ai/feedback/route.ts's GET handler had ZERO tenant scoping — it filtered only by requestId+operation='feedback' with no organizationId or userId predicate, so any authenticated 'member' of ANY organization could read another organization's AI feedback rows (rating, comment, userId) by supplying/guessing a query_id. Fixed by adding eq(aiUsageMetrics.organizationId, context.organizationId) to the WHERE clause and a 400 when organization context is missing; added 2 regression tests. The POST handler (insert + duplicate-check) was already correctly scoped by context.organizationId + context.userId. The lib/ai/services/cost-tracking-wrapper.ts write path (trackLLMCall -> insert) is separately confirmed DEAD CODE (round 35's ai_budgets finding applies identically here): its only production caller is lib/ai/template-engine.ts's optional-chained `.trackCost?.()`, a method CostTrackingWrapper does not have — permanent no-op. Minimum proven live runtime DML is SELECT+INSERT via the feedback route, plain tenant db path.",
    supportingCapability: ["app/api/ai/feedback/route.ts","app/api/__tests__/ai-feedback.route.test.ts","lib/ai/services/cost-tracking-wrapper.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "analytics_metrics",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CLOSED (round 48, derived analytics and AI telemetry authority cohort): direct NOT NULL organization_id table (db/schema/analytics.ts, canonical — db/schema/domains/analytics/analytics.ts is an orphan duplicate never re-exported by db/schema/index.ts). DUAL-SCHEMA FINDING (same database, not a separate boundary): services/financial-service independently declares its own 'analytics_metrics' pgTable in its own schema.ts/drizzle/schema.ts. Traced financial-service's src/db/index.ts: it lazily requires '../../../../lib/logger' (this app's own lib/ directory) at runtime and reads process.env.DATABASE_URL — the same env convention as this app, not an isolated deployment. financial-service/drizzle/0000_lucky_mole_man.sql is a 175-table 'CREATE TABLE IF NOT EXISTS' snapshot that includes 'organizations', 'members', 'claims', etc. verbatim, consistent with drizzle-kit having introspected the SAME shared production database rather than an independent one. Conclusion: this is a same-database dual Drizzle declaration (maintenance/code-hygiene duplication), not a SEPARATE_DATABASE_BOUNDARY — both declarations resolve to the identical physical table/columns. ROUTES: all per-org read/write routes (dashboard, refresh, financial/*, operational/*, members/*, etc.) use the standard crudRoutes({orgScoped:true}) factory pattern — spot-checked dashboard, refresh, admin/clc/analytics/organizations, and currency/convert, all consistently orgScoped:true. CROSS-ORG ROUTE: app/api/analytics/cross-org/route.ts requires auth.minRole='platform_lead' (a genuine NZila-platform-operations-tier role per lib/api-auth-guard.ts's ROLE_HIERARCHY doc comments, level 270, alongside app_owner/coo/cto — not a union-side role). Traced role resolution (lib/api/with-api.ts -> getUserRole -> authOrganizationUsers.role): confirmed NO live application route writes/updates authOrganizationUsers.role or organization_members.role with an arbitrary client-suppliable value (only lib/services/member-access-revocation-service.ts writes to authOrganizationUsers, and only isActive, never role) — platform-tier roles are not self-assignable via any known live mutation path today, though the architectural coupling of platform roles to a per-org membership table is noted as a design smell for a future hardening pass. CRON FINDING (non-security, product gap): financial-service's own analytics-processor.ts hourly/weekly cron jobs (hourlyAlertsJob/weeklyForecastJob) only ever process a single hardcoded test tenantId ('11111111-...') — dead/stub in production, does not write real per-org data, so no cross-tenant mixing risk exists on that path.",
    supportingCapability: ["actions/analytics-actions.ts","app/api/admin/clc/analytics/organizations/route.ts","app/api/analytics/claims/categories/route.ts","app/api/analytics/claims/route.ts","app/api/analytics/claims/stewards/route.ts","app/api/analytics/clause-stats/route.ts","app/api/analytics/comparative/route.ts","app/api/analytics/cross-org/route.ts","app/api/analytics/dashboard/route.ts","app/api/analytics/deadlines-metrics/route.ts","app/api/analytics/executive/route.ts","app/api/analytics/financial/categories/route.ts","app/api/analytics/financial/costs/route.ts","app/api/analytics/financial/outcomes/route.ts","app/api/analytics/financial/route.ts","app/api/analytics/financial/trends/route.ts","app/api/analytics/heatmap/route.ts","app/api/analytics/members/churn-risk/route.ts","app/api/analytics/members/cohorts/route.ts","app/api/analytics/members/route.ts","app/api/analytics/members/trends/route.ts","app/api/analytics/operational/bottlenecks/route.ts","app/api/analytics/operational/queues/route.ts","app/api/analytics/operational/route.ts","app/api/analytics/operational/sla/route.ts","app/api/analytics/operational/workload/route.ts","app/api/analytics/org-activity/route.ts","app/api/analytics/precedent-stats/route.ts","app/api/analytics/predictions/route.ts","app/api/analytics/refresh/route.ts","app/api/analytics/trends/route.ts","app/api/currency/convert/route.ts","app/api/metrics/route.ts","app/api/movement-insights/trends/route.ts","app/api/targets/summary/route.ts","lib/ai/insights-generator.ts","lib/api/crud-factory.ts","lib/services/lro-metrics.ts","services/financial-service/drizzle/relations.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "MIXED",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "analytics_scheduled_reports",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'analyticsScheduledReports' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "customer_nps_surveys",
    classification: "SYSTEM_ONLY",
    reason: "CLOSED (round 48, derived analytics and AI telemetry authority cohort): db/schema/analytics.ts declares organization_id NOT NULL (FK organizations, onDelete restrict) — real column exists, but reachability tracing found ZERO write path anywhere in app/, actions/, lib/, or services/ (NPS survey rows must originate out-of-band, e.g. seeding/ETL from an external survey tool). The SOLE reachable consumer is app/[locale]/dashboard/customer-success/page.tsx, gated by `await requireUser()` + `await isSystemAdmin()` (the org-independent users.isSystemAdmin column, per round 44's isSystemAdmin()-vs-hasMinRole() doctrine — redirects non-admins away) and executed under withSystemContext. This page deliberately reads CROSS-ORGANIZATION aggregate + per-respondent NPS data (respondent_name, score, feedback, category, organization name) for every organization — a legitimate genuine-platform-staff cross-org aggregate view, not a tenant-facing leak: no TENANT_USER code path reaches this table at all. Classified SYSTEM_ONLY rather than TENANT_RLS_REQUIRED because there is no live per-tenant runtime access to close around; classified over CROSS_ORG_AGGREGATE-as-an-exception because the platform-authority gate is already correct and no defect requires further exception handling.",
    supportingCapability: ["app/[locale]/dashboard/customer-success/page.tsx"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: ["SELECT"],
    invocationAuthority: "PLATFORM_ADMIN",
    dbExecutionPrincipal: "SYSTEM_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "employer_risk_scores",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CLOSED (round 48, derived analytics and AI telemetry authority cohort): direct NOT NULL organization_id table (db/schema/domains/ml/employer-risk-scores.ts), FK to organizations. CORRECTED REACHABILITY: the manifest's automated scan only found lib/ai/employer-risk.ts (an internal library with no obvious HTTP-route reference) and marked this NORMAL priority, but manual tracing found a real, live consumer the scanner missed: app/api/ai/employers/[id]/risk/route.ts (GET, withRoleAuth('steward'), feature-flag + entitlement + AI-safety gated). AI-OUTPUT-AS-AUTHORITY-EVIDENCE CHECK (round 48 doctrine): lib/ai/employer-risk.ts's calculateEmployerRisk() already correctly revalidates the path-supplied employerId against trusted DB ownership BEFORE persisting or returning any data — `db.query.employers.findFirst({ where: and(eq(employers.id, employerId), eq(employers.organizationId, organizationId)) })`, throwing if the employer does not belong to the caller's own organizationId — no cross-tenant read/write path exists. getLatestRiskScore/getRiskHistory are equally organizationId-scoped. No defect found; this is a well-designed reference implementation of the doctrine's ownership-revalidation requirement.",
    supportingCapability: ["lib/ai/employer-risk.ts","app/api/ai/employers/[id]/risk/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "icra_continuity_scores",
    classification: "SYSTEM_ONLY",
    reason: "ICRA_PSEUDONYMOUS_NO_LOGIN=APPROVED, ASSESSMENT_ID_AS_SOLE_BEARER_AUTHORITY=REJECTED (PR #752): the pseudonymous product model is intentional, but assessmentId alone must never authorize DB access. lib/icra/assessment-capability.ts adds a hashed, purpose-bound bearer capability; every route touching an existing assessment now verifies it before entering withSystemContext. Verified 2026-09-01 (round 7, ICRA capability architecture): only reached via withSystemContext() in the capability-gated submit routes (written alongside the maturity profile). No direct organization_id column.",
    supportingCapability: ["app/api/icra/submit/route.ts","app/api/icra/[assessmentId]/submit/route.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "SYSTEM_SCHEDULE",
    dbExecutionPrincipal: "SYSTEM_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "icra_followup_recommendations",
    classification: "SYSTEM_ONLY",
    reason: "ICRA_PSEUDONYMOUS_NO_LOGIN=APPROVED, ASSESSMENT_ID_AS_SOLE_BEARER_AUTHORITY=REJECTED (PR #752): the pseudonymous product model is intentional, but assessmentId alone must never authorize DB access. lib/icra/assessment-capability.ts adds a hashed, purpose-bound bearer capability; every route touching an existing assessment now verifies it before entering withSystemContext. Verified 2026-09-01 (round 7, ICRA capability architecture): only reached via withSystemContext() in the capability-gated submit routes. No direct organization_id column.",
    supportingCapability: ["app/api/icra/submit/route.ts","app/api/icra/[assessmentId]/submit/route.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "SYSTEM_SCHEDULE",
    dbExecutionPrincipal: "SYSTEM_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "icra_anonymized_metrics",
    classification: "LATENT_UNREACHABLE",
    reason: "Verified 2026-09-01 (round 7, ICRA capability architecture): zero non-test references to 'icraAnonymizedMetrics' anywhere in app/, actions/, lib/, or services/. No known application code path queries this table. If wired up in future for cross-org benchmark reads, prefer GLOBAL_REFERENCE_DATA (read-only, no per-org secrecy) over TENANT_RLS_REQUIRED given its anonymized/aggregate nature — re-review at that time.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "impact_metrics",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'impactMetrics' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "insight_recommendations",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CLOSED (round 48, derived analytics and AI telemetry authority cohort): direct NOT NULL organization_id table (db/schema/analytics.ts, canonical). DUAL-SCHEMA FINDING: services/financial-service also declares 'insight_recommendations' in its own schema.ts — same same-database conclusion as analytics_metrics (see that entry's dual-schema finding; financial-service shares this app's DATABASE_URL and lib/logger at runtime, confirmed via its src/db/index.ts). Real routes app/api/analytics/insights/route.ts and app/api/analytics/insights/weekly-summary/route.ts both use withApi's server-resolved organizationId (crudRoutes({orgScoped:true}) for the collection route; explicit `WHERE organization_id = ${organizationId}::uuid` sourced from withApi's auth context, never a client-supplied field, for the weekly-summary route). No defect found.",
    supportingCapability: ["app/api/analytics/insights/route.ts","app/api/analytics/insights/weekly-summary/route.ts","lib/ai/insights-generator.ts","services/financial-service/drizzle/relations.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "ml_predictions",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CLOSED (round 48, derived analytics and AI telemetry authority cohort): direct NOT NULL organization_id table. RESOLVED IN-APP DUPLICATE DECLARATION: db/schema/index.ts explicitly re-exports `mlPredictions` from './domains/ml' (db/schema/domains/ml/predictions.ts) as the canonical source, overriding the ambiguous `export *` from both domains/ml and domains/analytics; db/schema/analytics.ts, db/schema/domains/analytics/analytics.ts, and db/schema/ml-predictions-schema.ts are confirmed orphan duplicates (zero direct importers via '@/db/schema/ml-predictions-schema' or '@/db/schema/analytics' found by exhaustive grep). DUAL-SCHEMA FINDING: services/financial-service also declares 'ml_predictions' — same same-database conclusion as analytics_metrics. SEVERE CROSS-TENANT DEFECT FOUND AND FIXED: app/api/ml/predictions/churn-risk/route.ts (GET and POST) accepted a CLIENT-SUPPLIED organizationId (query params organizationId/orgId/organization_id/org_id on GET; request body organizationId on POST) and used it directly in a raw SQL WHERE clause / member-feature lookup / ml_predictions INSERT, OVERRIDING the caller's own authenticated organizationId. Any 'officer'-level user of one organization could read another organization's churn-risk member predictions (GET) or generate + persist churn predictions for another organization's members (POST) — a genuine cross-tenant IDOR, not merely theoretical (both handlers only require org-scoped 'officer' role, never a genuine platform authority). FIXED: removed the client-suppliable overrides entirely; both handlers now always use the withRoleAuth-resolved caller organizationId and return 400 if absent. Added 5 regression tests (app/api/__tests__/ml-churn-risk.route.test.ts) proving the query/insert now only ever contains the caller's own organizationId and never a supplied victim organizationId, for both the primary field and the orgId/organization_id/org_id aliases. Other reachable routes (sla-breach-risk, sla-breach-risk/feedback, timeline, workload-forecast) were spot-checked and already correctly use withApi's/crud-factory's server-resolved organizationId, not a client-supplied value.",
    supportingCapability: ["actions/analytics-actions.ts","app/api/ml/monitoring/drift/route.ts","app/api/ml/monitoring/usage/route.ts","app/api/ml/predictions/claim-outcome/route.ts","app/api/ml/predictions/churn-risk/route.ts","app/api/__tests__/ml-churn-risk.route.test.ts","app/api/ml/predictions/sla-breach-risk/feedback/route.ts","app/api/ml/predictions/sla-breach-risk/route.ts","app/api/ml/predictions/timeline/route.ts","app/api/ml/predictions/workload-forecast/route.ts","app/api/ml/recommendations/route.ts","lib/ai/insights-generator.ts","lib/feature-flags.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "mobile_analytics",
    classification: "CONTAINED_NO_AUTHORITY",
    reason: "CLOSED (round 48, derived analytics and AI telemetry authority cohort): db/schema/mobile-devices-schema.ts declares organization_id as NULLABLE (anonymous/pre-login mobile telemetry is a legitimate design intent for this table). NAME-COLLISION CORRECTION: the manifest's 2 supportingCapability references conflated two DIFFERENT symbols named 'mobileAnalytics' — lib/mobile/analytics.ts's export is a CLIENT-SIDE browser analytics SDK singleton (no DB access at all); the actual DB-table symbol is imported only by lib/mobile/mobile-engine.ts's MobileAnalyticsService.flushEvents(). Traced MobileAnalyticsService/mobileAnalyticsService: ZERO callers found anywhere in app/, actions/, or lib/ outside its own file and tests — fully dead code, confirmed by exhaustive grep. No real TypeScript consumer found. DJANGO SIDE IS REAL AND REACHABLE: backend/notifications/urls.py router-registers MobileAnalyticsViewSet at 'mobile-analytics'; pre-round-48 this was viewsets.ModelViewSet(queryset=MobileAnalytics.objects.all(), permission_classes=[IsAuthenticated]) with zero tenant scoping — any authenticated user of any organization could list/retrieve/mutate every organization's (and every anonymous session's) mobile analytics events. No legitimate Django consumer found either — CONTAINED: permission_classes changed to the existing DenyAllPermission (backend/notifications/views.py, already defined earlier in the file from round 45's containment batch). Classified CONTAINED_NO_AUTHORITY rather than LATENT_UNREACHABLE per the round-47 django-reachability doctrine (Django IS reachable and is being contained this round).",
    supportingCapability: ["lib/mobile/mobile-engine.ts","backend/notifications/views.py","backend/notifications/urls.py","backend/notifications/models.py"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "model_metadata",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CLOSED (round 48, derived analytics and AI telemetry authority cohort): direct NOT NULL organization_id table (db/schema/domains/ml/predictions.ts, canonical — same resolution as ml_predictions above), unique(organizationId, modelType, version). NOT a global model registry in this codebase: each organization gets its own model_metadata rows. DUAL-SCHEMA FINDING: services/financial-service also declares 'model_metadata' — same same-database conclusion as analytics_metrics. Reachable via app/api/ml/predictions/sla-breach-risk/route.ts (POST, withApi minRole='steward', reads/writes modelMetadata scoped by withApi's server-resolved organizationId, never client-supplied) and app/api/ml/predictions/sla-breach-risk/feedback/route.ts (same pattern) and app/api/ml/predictions/churn-risk/route.ts (writes a 'modelMetadata' JSON blob as prediction metadata, not the modelMetadata TABLE itself). No defect found on this table's own routes.",
    supportingCapability: ["app/api/ml/predictions/churn-risk/route.ts","app/api/ml/predictions/sla-breach-risk/feedback/route.ts","app/api/ml/predictions/sla-breach-risk/route.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "page_analytics",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'pageAnalytics' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "pilot_metrics",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CLOSED (round 48, derived analytics and AI telemetry authority cohort): direct NOT NULL organization_id table (db/schema/domains/marketing.ts), FK to organizations, plus pilotId FK to pilotApplications. Sole reachable consumer app/api/pilot/apply/[id]/reference-profile/route.ts (GET/POST) initially appeared to only check hasMinRole('steward') (an org-scoped role) with no visible organizationId comparison against the path-supplied pilot application id — further tracing found lib/pilot/pilot-ownership.ts's enforcePilotOwnership() IS called (GET, after loading the application, before returning any data) and withLockedPilotMutation(id, 'steward', ...) (POST) performs the equivalent locked/re-authorized ownership check; both already implement the round-48 AI/derived-data-authority doctrine's ownership-revalidation requirement (their own doc comments cite a prior round's 'verifiedOrganizationId ?? claimedOrganizationId — never the claim' fix). No defect found; pilot_metrics rows are only ever read/written for the caller's own verified organization.",
    supportingCapability: ["app/api/pilot/apply/[id]/reference-profile/route.ts","lib/pilot/pilot-ownership.ts","lib/pilot/pilot-mutation.ts"],
    requiredRuntimePrivileges: ["SELECT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "social_analytics",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CLOSED (round 48, derived analytics and AI telemetry authority cohort): direct NOT NULL organization_id table, FK to organizations and to socialAccounts. DUPLICATE DECLARATION FINDING (in-app, not cross-service): app/api/social-media/analytics/route.ts imports directly from 'db/schema/social-media-schema.ts' (a root-level file) rather than the canonical '@/db/schema' index path (which resolves 'social_analytics' from db/schema/domains/infrastructure/social-media.ts via domains/infrastructure/index.ts's `export * from './social-media'`). Both files declare structurally-identical columns for the same physical table name — a maintenance/code-hygiene duplicate, not a security boundary difference (drizzle only needs matching table/column metadata to build correct SQL against the one real table). Route reachability: app/api/social-media/analytics/route.ts (GET, withRoleAuth('member')) filters via eq(socialAccounts.organizationId, context.organizationId) joined against socialAnalytics.accountId — correctly org-scoped, no client-supplied organizationId override found.",
    supportingCapability: ["app/api/social-media/analytics/route.ts","lib/social-media/social-media-service.ts"],
    requiredRuntimePrivileges: ["SELECT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "usage_aggregates",
    classification: "LATENT_UNREACHABLE",
    reason: "CLOSED (round 48, derived analytics and AI telemetry authority cohort): db/schema/domains/finance/usage-metering.ts declares organization_id NOT NULL (period-level usage summaries for invoicing, FK to organizations + usageMeters + billingPeriods). Exhaustive reachability trace: services/platform-economics/usage-metering-service.ts (aggregateUsage — the only writer, correctly organizationId-scoped and uses .update() only on this table, never usage_events) has ZERO callers anywhere in app/, actions/, or lib/ outside its own package's index.ts barrel re-export; no app/api route, action, or cron (including app/api/cron/billing-lifecycle/route.ts, the natural candidate) invokes any usage-metering-service function. No Django exposure found (zero references to usage_aggregates/UsageAggregates in backend/). Verified 2026 (round 48): zero references outside db/schema/**, services/platform-economics/**, and test files.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "usage_events",
    classification: "LATENT_UNREACHABLE",
    reason: "CLOSED (round 48, derived analytics and AI telemetry authority cohort): db/schema/domains/finance/usage-metering.ts declares organization_id NOT NULL (append-only raw usage event stream, FK to organizations + usageMeters). APPEND-ONLY INVARIANT VERIFIED: services/platform-economics/usage-metering-service.ts only ever .insert()s into usage_events (with .onConflictDoNothing on idempotencyKey) — zero .update()/.delete() calls found anywhere against this table. Exhaustive reachability trace (same as usage_aggregates): the entire usage-metering-service.ts module has ZERO callers anywhere outside its own package barrel and tests; no route/action/cron reaches recordUsageEvent. No Django exposure found. Fully dead code today — do not add new callers without first re-classifying this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "usage_meters",
    classification: "LATENT_UNREACHABLE",
    reason: "CLOSED (round 48, derived analytics and AI telemetry authority cohort): db/schema/domains/finance/usage-metering.ts declares this as a GLOBAL meter-definition catalogue (code/name/meterType/unit/pricePerUnit) with NO organization_id column at all — by design a shared reference table, not tenant data. Moot regardless: exhaustive reachability trace (same as usage_aggregates/usage_events) confirms the entire usage-metering-service.ts pipeline that would read/write this table has ZERO callers anywhere in app/, actions/, lib/, or services/ outside its own package and tests, and no Django exposure exists. Fully dead code today.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "user_engagement_scores",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'userEngagementScores' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
]
