/**
 * db/rls-storage-authority/baseline-0108.ts
 *
 * PR #752 round 9: extracted from the single-file
 * db/rls-storage-authority-manifest.ts (which exceeded the repository's
 * 8000-line hard cap at 8009 lines — see
 * tooling/contract-tests/file-size-enforcement.test.ts) into semantic
 * domain modules. This module owns: 0108-baseline protected tables (the original 24-table RLS-enabled set).
 *
 * Domain boundaries were assigned mechanically by table-name keyword
 * matching against the entry's `table` field (see the one-time migration
 * script referenced in the round-9 commit message) — every entry's DATA
 * (classification, reason, privileges, authority) is unchanged from the
 * pre-split manifest; only its physical file location changed. Do not
 * hand-edit an entry's domain placement without also checking
 * db/__tests__/rls-storage-authority-registry-composition.test.ts, which
 * proves the composed registry is unaffected by which module an entry
 * lives in.
 *
 * Add NEW entries to whichever domain module most closely matches the
 * table's real subject matter; when genuinely ambiguous, prefer
 * reference-latent.ts (the catch-all) over forcing a bad fit elsewhere.
 */
import type { StorageAuthorityEntry } from './types';

export const baseline0108Entries: StorageAuthorityEntry[] = [
  {
    table: "organization_members",
    classification: "TENANT_RLS_REQUIRED",
    reason: "0108-baseline table (direct org policy, TEXT organization_id column per 0108's ue_create_direct_org_rls_policy('organization_members', 'organization_id', TRUE) call). Evidence census across 118 real (non-test, non-schema) files: confirmed .insert(organizationMembers) (8 sites), .update(organizationMembers) (5 sites), .delete(organizationMembers) (3 sites), and .from(organizationMembers)/db.query.organizationMembers (60 sites) — core membership table touched by org-management routes, invite acceptance, role updates, and offboarding, all under ordinary authenticated tenant request handling (no withSystemContext site found for this table). AUTH_OFFBOARDING_STORAGE_AUTHORITY (round 11): organization_members.status/deletedAt are the storage-side offboarding signal; TENANT_RUNTIME correctly owns both fields. AUTH_OFFBOARDING_RUNTIME_BEHAVIOR (round 11, traced not assumed): the ONLY reachable status/deletedAt writer is app/api/admin/users/[userId]/route.ts (platform-admin-gated via PLATFORM_ADMIN_USER_IDS, not ordinary tenant admin) — its PUT (active/inactive toggle) already emitted eventBus 'member.status_changed', triggering lib/events/pilot-event-listeners.ts's revokeAllUserSessions() + grievance case-access revocation; its DELETE (soft-delete) did NOT, a real defect FIXED this round (now emits the same event with newStatus:'deleted'). lib/services/member-service.ts's updateMember/deleteMember/bulkUpdateMemberStatus (which would bypass this enforcement entirely) confirmed LATENT_UNWIRED — zero real callers anywhere, matching the round-6 bulkUpdateMemberRole precedent. Regression proof: app/api/admin/users/[userId]/__tests__/route.offboarding-parity.test.ts (4 tests: non-platform-admin rejected on both PUT+DELETE; PUT emits the event; DELETE now ALSO emits it; DELETE 404s without emitting for a nonexistent member).",
    supportingCapability: ["lib/organization-utils.ts","lib/services/member-service.ts","packages/platform-auth/src/invites/service.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "organizations",
    classification: "TENANT_RLS_REQUIRED",
    reason: "0108-baseline table (direct org policy keyed on the org's own id per 0108's ue_create_direct_org_rls_policy('organizations', 'id', FALSE) call — INSERT/UPDATE/DELETE all WITH CHECK/USING (id = current_org_id)). CORRECTED 2026-09-02 (round 7): the prior entry described the round-6 census's raw .insert(organizations)/.update(organizations) hit counts as if they were all TENANT_RUNTIME operations — a DML census proves an operation EXISTS, not which principal is authorized to perform it. Re-audited every real call site by reading it directly: app/api/organizations/route.ts's POST (org creation) calls requireSystemAdmin() BEFORE any DB access (the actual authorization decision), but the parent-lookup SELECT and the INSERT then ran through withRLSContext() (tenant runtime) — under the 0108 policy above, a freshly-generated new org's id can never equal the caller's own current_org_id, so that INSERT could never legitimately succeed under enforced RLS. FIXED this round: both now run inside withSystemContext(); requireSystemAdmin() remains the sole authorization decision, evaluated first, never withSystemContext itself. Regression proof: app/api/organizations/__tests__/route.post-system-boundary.test.ts (5 tests: non-admin rejected before any context; unauthenticated rejected before requireSystemAdmin; admin creation uses withSystemContext for both lookup+insert, never withRLSContext; GET unchanged, still withRLSContext only). Other real UPDATE call sites, individually audited: app/api/organizations/[id]/route.ts and app/api/settings/organization/route.ts (withApi minRole 'admin') update only the caller's OWN org id via withRLSContext — correctly TENANT_RUNTIME; lib/services/entitlements.ts's 3 credit-tracking updates run via plain `db` under whichever tenant AI route (app/api/ai/**, app/api/voice/upload) already established withRLSContext for the caller's own org — TENANT_RUNTIME; lib/services/per-capita-calculator.ts's updateLastRemittanceDate is reachable ONLY via app/api/finance/per-capita/inbound/route.ts (withApi minRole 'officer', tenant tier) — TENANT_RUNTIME. Three writers are LATENT (zero real callers, verified by name-search): actions/admin-actions.ts's updateOrg, lib/utils/hierarchy-validation.ts's fixOrphanedOrganizations, and all 3 update sites in services/clc/clc-api-integration.ts (that whole module has zero real callers, matching the round-4 finding for clc_organization_sync_log) — none contribute to the privilege sets below. No .delete(organizations) call site found anywhere (org deactivation is soft, via status/UPDATE).",
    supportingCapability: ["app/api/organizations/route.ts","app/api/organizations/[id]/route.ts","app/api/settings/organization/route.ts","lib/services/entitlements.ts","lib/organization-utils.ts"],
    requiredRuntimePrivileges: ["SELECT","UPDATE"],
    requiredSystemPrivileges: ["SELECT","INSERT"],
    invocationAuthority: "MIXED",
    dbExecutionPrincipal: "MIXED",
    reviewPriority: "NONE",
  },
  {
    table: "grievances",
    classification: "TENANT_RLS_REQUIRED",
    reason: "0108-baseline table (direct org policy). Evidence census across 119 real files: confirmed .insert(grievances) (9 sites, grievance filing), .update(grievances) (6 sites, status/stage transitions), and .delete(grievances) (4 sites, withdrawal/cancellation) via the core grievance API routes (app/api/grievances/**), all under ordinary authenticated tenant request handling.",
    supportingCapability: ["app/api/grievances/[id]/route.ts","app/api/grievances/[id]/documents/route.ts","lib/services/case-access-service.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "claims",
    classification: "TENANT_RLS_REQUIRED",
    reason: "0108-baseline table (direct org policy). Evidence census across 202 real files: confirmed .insert(claims) (4 sites), .update(claims) (10 sites, the widest-used mutation — status/workflow transitions), and .delete(claims) (1 site) across the claims/evidence/workflow API surface (app/api/claims/**), all under ordinary authenticated tenant request handling (no withSystemContext site found for this table).",
    supportingCapability: ["app/api/claims/[id]/evidence/route.ts","app/api/claims/[id]/workflow/history/route.ts","lib/workflow-engine.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "grievance_deadlines",
    classification: "TENANT_RLS_REQUIRED",
    reason: "0108-baseline table (direct org policy) — distinct from 'claim_deadlines' (a separate, round-5-added table backing the 'deadlines' Drizzle export). MIXED: reachable via ordinary tenant deadline-management code (SELECT/INSERT/UPDATE/DELETE, TENANT_RUNTIME) AND via app/api/cron/deadline-overdue/route.ts (auth: { cron: true }, SYSTEM_SCHEDULE), whose raw SQL SELECT against grievance_deadlines (joined to deadline_reminders) runs inside withSystemContext to detect overdue deadlines — verified by reading that route's SQL directly (see the deadline_reminders/claim_deadlines entries' round-5 correction for the same route).",
    supportingCapability: ["app/api/cron/deadline-overdue/route.ts","lib/deadline-tracking-system.ts","lib/deadline-service.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: ["SELECT"],
    invocationAuthority: "MIXED",
    dbExecutionPrincipal: "MIXED",
    reviewPriority: "NONE",
  },
  {
    table: "documents",
    classification: "TENANT_RLS_REQUIRED",
    reason: "0108-baseline table (direct org policy). Evidence census across 152 real files: confirmed .insert(documents) (5 sites, upload flows), .update(documents) (5 sites, metadata/access-level edits), and .delete(documents) (1 site) across app/api/documents/** and lib/services/document-service.ts, all under ordinary authenticated tenant request handling.",
    supportingCapability: ["app/api/documents/[id]/route.ts","app/api/documents/repository/route.ts","lib/services/document-service.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "member_documents",
    classification: "LATENT_UNREACHABLE",
    reason: "0108-baseline table, but zero non-test references to the 'memberDocuments' Drizzle export exist anywhere in apps/union-eyes proper — its only other hit, services/financial-service/drizzle/schema.ts, is that separately-deployed service's OWN database (own drizzle.config.ts/DATABASE_URL — SEPARATE_DATABASE_BOUNDARY precedent, see deadline_alerts). Already RLS-protected at the DB level by 0108 regardless of this manifest entry; LATENT_UNREACHABLE describes app-code reachability only, not DB protection status. Revisit if any union-eyes code starts querying it.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "workplace_incidents",
    classification: "TENANT_RLS_REQUIRED",
    reason: "0108-baseline table (direct org policy). Reachable via crudRoutes({ readRole: 'health_safety_rep', writeRole: 'health_safety_rep' }) at app/api/health-safety/incidents/route.ts (GET+POST) and crudRoutes({ readRole: 'member', writeRole: 'admin' }) at the [id] item route (GET+PATCH+DELETE) — both tenant org-scoped role tiers, plain `db` import, no withSystemContext.",
    supportingCapability: ["app/api/health-safety/incidents/route.ts","app/api/health-safety/incidents/[id]/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "safety_inspections",
    classification: "TENANT_RLS_REQUIRED",
    reason: "0108-baseline table (direct org policy). Reachable via crudRoutes({ readRole: 'member', writeRole: 'admin' }) at both app/api/health-safety/inspections/route.ts (GET+POST) and its [id] item route (GET+PATCH+DELETE) — tenant org-scoped role tiers, plain `db` import, no withSystemContext.",
    supportingCapability: ["app/api/health-safety/inspections/route.ts","app/api/health-safety/inspections/[id]/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "hazard_reports",
    classification: "TENANT_RLS_REQUIRED",
    reason: "0108-baseline table (direct org policy). Reachable via crudRoutes({ readRole: 'health_safety_rep', writeRole: 'health_safety_rep' }) at app/api/health-safety/hazards/route.ts (GET+POST) and crudRoutes({ readRole: 'member', writeRole: 'admin' }) at its [id] item route (GET+PATCH+DELETE) — tenant org-scoped role tiers, plain `db` import, no withSystemContext.",
    supportingCapability: ["app/api/health-safety/hazards/route.ts","app/api/health-safety/hazards/[id]/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "safety_committee_meetings",
    classification: "LATENT_UNREACHABLE",
    reason: "0108-baseline table, but zero non-test references to the 'safetyCommitteeMeetings' Drizzle export exist anywhere in app/, actions/, lib/, or services/ (verified by name-search; unlike workplace_incidents/safety_inspections/hazard_reports, no health-safety route targets this table today). Already RLS-protected at the DB level by 0108 regardless of this manifest entry. Revisit if any code starts querying it.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "safety_training_records",
    classification: "NEEDS_REVIEW",
    reason: "RECLASSIFIED 2026-09-02 (round 7, raw-SQL LATENT-detection correction): this table was previously classified LATENT_UNREACHABLE based on a Drizzle-EXPORT-NAME-only reachability scan, which cannot find raw SQL references. A raw-SQL detection pass (see db/__tests__/rls-storage-authority-manifest-raw-sql-latent.test.ts for the detector/fixture) found real, direct raw-SQL table references (db.execute(sql`... FROM/INTO/UPDATE safety_training_records ...`) or an equivalent quoted-table-name repository reference) in the file(s) listed below. Full HTTP-reachability/auth-boundary trace not yet completed.",
    supportingCapability: ["app/api/health-safety/stats/route.ts","app/api/health-safety/dashboard/route.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "ppe_equipment",
    classification: "TENANT_RLS_REQUIRED",
    reason: "0108-baseline table (direct org policy). Reachable via crudRoutes({ readRole: 'member', writeRole: 'admin' }) at app/api/health-safety/ppe/route.ts — GET+POST only, no [id] item route exists, so no UPDATE/DELETE call site found; not defaulted to FULL_DML.",
    supportingCapability: ["app/api/health-safety/ppe/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "safety_audits",
    classification: "LATENT_UNREACHABLE",
    reason: "0108-baseline table, but zero non-test references to the 'safetyAudits' Drizzle export exist anywhere in app/, actions/, lib/, or services/ (verified by name-search). Already RLS-protected at the DB level by 0108 regardless of this manifest entry. Revisit if any code starts querying it.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "injury_logs",
    classification: "LATENT_UNREACHABLE",
    reason: "0108-baseline table, but zero non-test references to the 'injuryLogs' Drizzle export exist anywhere in app/, actions/, lib/, or services/ (verified by name-search). Already RLS-protected at the DB level by 0108 regardless of this manifest entry. Revisit if any code starts querying it.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "safety_policies",
    classification: "LATENT_UNREACHABLE",
    reason: "0108-baseline table, but zero non-test references to the 'safetyPolicies' Drizzle export exist anywhere in app/, actions/, lib/, or services/ (verified by name-search). Already RLS-protected at the DB level by 0108 regardless of this manifest entry. Revisit if any code starts querying it.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "corrective_actions",
    classification: "LATENT_UNREACHABLE",
    reason: "0108-baseline table. The original automated scan's two 'hits' (app/[locale]/dashboard/health-safety/hazards/page.tsx, app/api/health-safety/incidents/route.ts) are BOTH false positives — verified by reading each: incidents/route.ts's 'correctiveActions' references are a plain object field name (raw.correctiveActions, a form-field alias), not the Drizzle table export, and no import of the 'correctiveActions' table exists in either file or anywhere else in app/, actions/, lib/, or services/. Already RLS-protected at the DB level by 0108 regardless of this manifest entry. Revisit if any code starts querying the actual table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "safety_certifications",
    classification: "LATENT_UNREACHABLE",
    reason: "0108-baseline table, but zero non-test references to the 'safetyCertifications' Drizzle export exist anywhere in app/, actions/, lib/, or services/ (verified by name-search). Already RLS-protected at the DB level by 0108 regardless of this manifest entry. Revisit if any code starts querying it.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "message_threads",
    classification: "TENANT_RLS_REQUIRED",
    reason: "0108-baseline table (direct org policy — the parent for the message_* family below). Reachable via crudRoutes({ readRole: 'member', writeRole: 'steward' }) at app/api/messages/threads/route.ts (GET+POST) and its [threadId] item route (GET+POST), plus a read-only SELECT in lib/gdpr/consent-manager.ts (member's own GDPR data export, reached via app/api/gdpr/data-export/route.ts, withApiAuth). No UPDATE/DELETE call site found; not defaulted to FULL_DML.",
    supportingCapability: ["app/api/messages/threads/route.ts","app/api/messages/threads/[threadId]/route.ts","lib/gdpr/consent-manager.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "messages",
    classification: "PARENT_OWNED_RLS_REQUIRED",
    reason: "0108-baseline table, parent-owned through message_threads (thread_id) per 0108's ue_create_parent_owned_rls_policy('messages', 'thread_id') call. Reachable via crudRoutes({ readRole: 'member', writeRole: 'steward' }) at app/api/messages/threads/[threadId]/messages/route.ts (GET+POST) and, despite its 'notifications' path name, app/api/messages/notifications/route.ts also targets the 'messages' table (its own doc comment says 'CRUD collection route for messages' — a filtered view, not a different table), plus a read-only SELECT in lib/gdpr/consent-manager.ts. No UPDATE/DELETE call site found; not defaulted to FULL_DML.",
    supportingCapability: ["app/api/messages/threads/[threadId]/messages/route.ts","app/api/messages/notifications/route.ts","lib/gdpr/consent-manager.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "message_participants",
    classification: "LATENT_UNREACHABLE",
    reason: "0108-baseline table (parent-owned via message_threads), but zero non-test references to the 'messageParticipants' Drizzle export exist anywhere in apps/union-eyes proper — its only other hit, services/financial-service/drizzle/schema.ts, is that separately-deployed service's OWN database (SEPARATE_DATABASE_BOUNDARY, see member_documents). Already RLS-protected at the DB level by 0108 regardless of this manifest entry. Revisit if any union-eyes code starts querying it.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "message_read_receipts",
    classification: "PARENT_OWNED_RLS_REQUIRED",
    reason: "0108-baseline table, parent-owned via messages/message_id per 0108's ue_create_parent_owned_rls_policy('message_read_receipts', 'message_id') call. Sole real reference is lib/gdpr/consent-manager.ts's db.query.messageReadReceipts.findMany({ where: eq(messageReadReceipts.userId, userId) }) — read-only, part of a member's own GDPR data-export request (app/api/gdpr/data-export/route.ts, withApiAuth). No INSERT/UPDATE/DELETE call site found anywhere in the app; not defaulted to FULL_DML.",
    supportingCapability: ["lib/gdpr/consent-manager.ts","app/api/gdpr/data-export/route.ts"],
    requiredRuntimePrivileges: ["SELECT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "message_notifications",
    classification: "LATENT_UNREACHABLE",
    reason: "0108-baseline table (parent-owned via message_threads), but zero non-test references to the 'messageNotifications' Drizzle export exist anywhere in apps/union-eyes proper — app/api/messages/notifications/route.ts (whose URL path suggests this table) actually targets the 'messages' table instead (see that entry); its only other hit, services/financial-service/drizzle/schema.ts, is that separately-deployed service's OWN database (SEPARATE_DATABASE_BOUNDARY). Already RLS-protected at the DB level by 0108 regardless of this manifest entry. Revisit if any union-eyes code starts querying it.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "cross_org_access_log",
    classification: "LATENT_UNREACHABLE",
    reason: "0108-baseline table, explicitly modeled by 0108 as PROTECTED_NO_TENANT_ACCESS (no tenant-runtime policy at all by design — see scripts/rls-verify.ts's PROTECTED_NO_TENANT_ACCESS_TABLES). Its sole non-test reference, lib/clc/data-products.ts, has ZERO callers anywhere under app/, actions/, lib/, services/ (verified by name-search) — it is dead code today. LATENT BUG FLAGGED FOR FUTURE WIRING (not fixed here, since the module is unreachable): data-products.ts reads crossOrgAccessLog via the plain `db` import, not withSystemContext — if this module is ever wired into a live route, that read must be moved inside withSystemContext() first, matching the SYSTEM_ONLY pattern this table's own 0108 design implies (a tenant-runtime connection has no policy permitting it to see this table at all, so the query would currently return zero rows or error, not silently leak cross-tenant data).",
    supportingCapability: ["lib/clc/data-products.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
]
