/**
 * db/rls-storage-authority/claims-continuity.ts
 *
 * PR #752 round 9: extracted from the single-file
 * db/rls-storage-authority-manifest.ts (which exceeded the repository's
 * 8000-line hard cap at 8009 lines — see
 * tooling/contract-tests/file-size-enforcement.test.ts) into semantic
 * domain modules. This module owns: Claims, grievances, deadlines, bargaining, workflow.
 *
 * Domain boundaries were assigned mechanically by table-name keyword
 * matching against the entry's `table` field (see the one-time migration
 * script referenced in the round-9 commit message) — every entry's DATA
 * (classification, reason, privileges, authority) is unchanged from the
 * pre-split manifest; only its physical file location changed. Do not
 * hand-edit an entry's domain placement without also checking
 * db/__tests__/rls-storage-authority-registry-composition.test.ts, which
 * proves the composed registry is unaffected by which module an entry
 * lives in.
 *
 * Add NEW entries to whichever domain module most closely matches the
 * table's real subject matter; when genuinely ambiguous, prefer
 * reference-latent.ts (the catch-all) over forcing a bad fit elsewhere.
 */
import type { StorageAuthorityEntry } from './types';

export const claimsContinuityEntries: StorageAuthorityEntry[] = [
  {
    table: "claim_deadlines",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified 2026-09-01, corrected 2026-09-02 (round 5): direct NOT NULL organization_id column (db/schema/deadlines-schema.ts, Drizzle export 'deadlines' backing physical table 'claim_deadlines'), reachable via live HTTP routes (app/api/deadlines/route.ts, app/api/deadlines/[id]/complete/route.ts, app/api/deadlines/[id]/extend/route.ts, app/api/deadlines/overdue/route.ts, app/api/deadlines/upcoming/route.ts — all crudRoutes({ readRole: 'member', writeRole: 'steward' })) and core services (lib/deadline-tracking-system.ts, lib/deadline-service.ts), all using the plain `db` import (no withSystemContext). Round-5 correction: the previously-cited app/api/cron/deadline-overdue/route.ts does NOT touch this table — it queries `grievance_deadlines` (an existing 0108-protected table) and `deadline_reminders` only, both inside withSystemContext; that citation was a false evidence match and has been removed. No system-context path touches claim_deadlines today.",
    supportingCapability: ["app/api/deadlines/route.ts","app/api/deadlines/[id]/complete/route.ts","app/api/deadlines/[id]/extend/route.ts","app/api/deadlines/overdue/route.ts","app/api/deadlines/upcoming/route.ts","lib/deadline-tracking-system.ts","lib/deadline-service.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "deadline_reminders",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified 2026-09-01, resolved 2026-09-02 (round 5): direct NOT NULL organization_id column (db/schema/deadline-engine-schema.ts). MIXED — genuinely reached two ways: (1) lib/deadline-engine/reminder-scheduler.ts's scheduleGrievanceDeadlineReminders()/cancelGrievanceDeadlineReminders() write it via the plain `db` import (TENANT_RUNTIME), called from tenant-authenticated flows (lib/deadline-tracking-system.ts, itself reachable via the claim_deadlines API routes, member/steward-gated); (2) app/api/cron/deadline-overdue/route.ts (auth: { cron: true }, CRON_SECRET_KEY-gated — SYSTEM_SCHEDULE) reads it via a raw SQL `select ... from deadline_reminders` inside withSystemContext to check for an existing in-flight reminder before enqueuing a new one — a real SELECT-only system-context read, verified by reading the route's SQL directly; the actual write (scheduleGrievanceDeadlineReminders) happens afterward, outside withSystemContext, via the same TENANT_RUNTIME path as (1).",
    supportingCapability: ["app/api/cron/deadline-overdue/route.ts","lib/deadline-engine/reminder-scheduler.ts","lib/deadline-tracking-system.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: ["SELECT"],
    invocationAuthority: "MIXED",
    dbExecutionPrincipal: "MIXED",
    reviewPriority: "HIGH",
  },
  {
    table: "grievance_case_access_assignments",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified 2026-09-01: direct NOT NULL organization_id column (db/schema/domains/claims/grievance-lifecycle.ts), reachable via live HTTP routes app/api/grievances/[id]/access/route.ts and app/api/grievances/[id]/route.ts, and lib/services/case-access-service.ts (getEffectiveCaseAccess). Grants per-user case access within a grievance — governs who else can see privileged case material, making cross-tenant leakage here especially sensitive.",
    supportingCapability: ["app/api/grievances/[id]/access/route.ts","app/api/grievances/[id]/route.ts","lib/services/case-access-service.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "grievance_assignments",
    classification: "LATENT_UNREACHABLE",
    reason: "Manually verified 2026-09-01 (PR #752 review Item #9 audit): its only two referencing modules, lib/case-assignment-engine.ts and lib/workflow-automation-engine.ts, have no production HTTP caller — workflow-automation-engine.ts is imported only by its own test file, and case-assignment-engine.ts is imported only dynamically from within workflow-automation-engine.ts. A trust-boundary guardrail comment was added to case-assignment-engine.ts documenting this for future integrators. Revisit before either module is wired into a live route.",
    supportingCapability: ["lib/case-assignment-engine.ts","lib/workflow-automation-engine.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "deadline_reassignment_convergence",
    classification: "LATENT_UNREACHABLE",
    reason: "Manually verified 2026-09-01: written only by lib/deadline-engine/assignment-sync.ts's refreshDeadlineRemindersForGrievance(), which is re-exported from lib/deadline-engine/index.ts but has zero real (non-test) importers of that export — only its own test file and lib/reality/capability-registry.ts (documentation, not a call site) reference it. The durable-outbox retry-worker infrastructure exists but is not wired into any live route, action, or cron job today.",
    supportingCapability: ["lib/deadline-engine/assignment-sync.ts","lib/deadline-engine/index.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "deadline_alerts",
    classification: "LATENT_UNREACHABLE",
    reason: "Manually verified 2026-09-01: automated scan's 3 matches are both false positives — app/api/notifications/preferences/route.ts's 'deadlineAlerts' is an unrelated boolean notification-preference field name, not the Drizzle table export; services/financial-service/**/schema.ts's 'deadline_alerts' is a same-named table in that service's OWN separate database (services/financial-service/src/db/index.ts connects via its own process.env.DATABASE_URL and its own drizzle.config.ts — a distinct database boundary, mirroring 0108's own precedent for out-of-scope root-level /migrations/ tables). No real reference to this table's actual Drizzle export was found in the main union-eyes app.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "deadline_extensions",
    classification: "LATENT_UNREACHABLE",
    reason: "Verified 2026-09-01 (round 6, Phase-3A priority tranche + reachability-scan correction): lib/reality/capability-registry.ts is a static narrative/audit-trail data file (an array of descriptive capability-verification strings), not executable query code — it contains no database calls and its mention of 'deadline_extensions' is commentary, not a call site. No other non-test reference exists in app/, actions/, lib/, or services/. Resolves the prior entry's open question ('needs a manual check of whether it drives real query behavior') — it does not.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "deadline_rules",
    classification: "LATENT_UNREACHABLE",
    reason: "Verified 2026-09-01 (round 6, Phase-3A priority tranche + reachability-scan correction): lib/reality/capability-registry.ts is a static narrative/audit-trail data file (an array of descriptive capability-verification strings), not executable query code — it contains no database calls and its mention of 'deadline_rules' is commentary, not a call site. No other non-test reference exists in app/, actions/, lib/, or services/. Resolves the prior entry's open question ('needs a manual check of whether it drives real query behavior') — it does not.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "ai_grievance_triages",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified 2026-09-02: direct NOT NULL organization_id column (db/schema/domains/ml/ai-grievance-triage.ts). Sole listed reference lib/ai/grievance-triage.ts is confirmed reachable via live HTTP routes app/api/ai/grievances/triage/route.ts and app/api/ai/grievances/[id]/triage/route.ts — the earlier \"no obvious HTTP-route\" scan result was a false negative.",
    supportingCapability: ["lib/ai/grievance-triage.ts","app/api/ai/grievances/triage/route.ts","app/api/ai/grievances/[id]/triage/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "arbitrations",
    classification: "PARENT_OWNED_RLS_REQUIRED",
    reason: "Manually verified 2026-09-02: NO direct organization_id column (db/schema/grievance-schema.ts) — scoped only through the parent grievances row's organization_id via grievance_id (NOT NULL FK). Reachable via live HTTP routes app/api/arbitrations/route.ts, app/api/arbitrations/[id]/route.ts, app/api/finance/summary/route.ts.",
    supportingCapability: ["app/api/arbitrations/route.ts","app/api/arbitrations/[id]/route.ts","app/api/finance/summary/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "bargaining_notes",
    classification: "TENANT_RLS_REQUIRED",
    reason: "6 non-test reference(s) to 'bargainingNotes' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review). RESOLVED (round 11): app/api/bargaining-notes/[id]/route.ts uses crudRoutes({ orgScoped: true, writeRole: 'steward' }) — auto-filtered by the caller's own organizationId.",
    supportingCapability: ["app/api/bargaining-notes/[id]/route.ts","app/api/cbas/[id]/route.ts","lib/services/bargaining-notes-service.ts","services/financial-service/drizzle/relations.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "bargaining_units",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified 2026-09-02: direct NOT NULL organization_id column (db/schema/union-structure-schema.ts). Reachable via live HTTP routes app/api/units/route.ts, app/api/units/[id]/route.ts, app/api/locals/route.ts, app/api/locals/[id]/route.ts, app/api/jurisdiction/clc-compliance/route.ts, app/api/jurisdiction/validate-deadline/route.ts.",
    supportingCapability: ["app/api/units/route.ts","app/api/units/[id]/route.ts","app/api/locals/route.ts","app/api/locals/[id]/route.ts","app/api/jurisdiction/clc-compliance/route.ts","app/api/jurisdiction/validate-deadline/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "case_documents",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01, corrected 2026-09-02 (round 5): the previously-cited app/api/case-repository/[caseId]/documents/route.ts does not exist in the repo (stale scan path) — real, verified reference is app/api/documents/[id]/route.ts, which reads `db.query.caseDocuments.findFirst(...)` filtered by documentId+isImmutable (SELECT only) behind `withApi({ auth: { required: true, minRole: 'app_owner' } })` (app_owner is a tenant-org-scoped role tier, not a platform-level role) using the plain `db` import (no withSystemContext). direct organization_id column confirmed on the case_documents export.",
    supportingCapability: ["app/api/documents/[id]/route.ts"],
    requiredRuntimePrivileges: ["SELECT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "case_studies",
    classification: "GLOBAL_REFERENCE_DATA",
    reason: "5 non-test reference(s) to 'caseStudies' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review). RESOLVED (round 11): app/api/case-studies/route.ts's own doc comment confirms intent — 'GET is public (marketing pages), POST requires admin auth' — genuinely global, non-tenant marketing content (crudRoutes orgScoped:false). FOLLOW-UP FLAGGED, not fixed this round: writeRole:'admin' resolves via withApi's minRole mechanism, which checks the caller's role WITHIN THEIR OWN ORGANIZATION (see lib/api/with-api.ts) — meaning any tenant's own org-admin (not just platform marketing staff) can create/edit/delete platform-wide marketing case studies. Lower severity than the governance/organizations findings this round (content-integrity risk, not a tenant-data confidentiality breach), but the same defect CLASS as golden_shares/mission_audits pre-fix and as testimonials below — tracked for a follow-up role-list tightening.",
    supportingCapability: ["app/[locale]/(marketing)/case-studies/page.tsx","app/[locale]/(marketing)/locale-site-footer.tsx","app/api/case-studies/[slug]/route.ts","app/api/case-studies/route.ts","lib/marketing-hero-imagery.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "cba_clauses",
    classification: "TENANT_RLS_REQUIRED",
    reason: "8 non-test reference(s) to 'cbaClause' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review). RESOLVED (round 11): app/api/clauses/route.ts uses crudRoutes({ orgScoped: true, writeRole: 'steward' }) — the factory auto-filters every query by the caller's own organizationId (eq(orgCol, organizationId)), no URL-param trust involved. app/api/clauses/search/route.ts is read-only, same org-scoped pattern.",
    supportingCapability: ["app/api/ai/semantic-search/route.ts","app/api/clauses/route.ts","app/api/clauses/search/route.ts","lib/services/ai/clause-extraction-service.ts","lib/services/ai/vector-search-service.ts","lib/services/clause-intelligence.ts","lib/services/clause-service.ts","services/financial-service/drizzle/relations.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "cba_rule_set_items",
    classification: "TENANT_RLS_REQUIRED",
    reason: "2 non-test reference(s) to 'cbaRuleSetItems' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review). RESOLVED (round 11): app/api/employer-execution/payroll-runs/route.ts (minRole:'member'/'steward') explicitly filters by the caller's own organizationId via withRLSContext.",
    supportingCapability: ["app/api/employer-execution/payroll-runs/route.ts","app/api/employer-execution/replay/[runId]/route.ts"],
    requiredRuntimePrivileges: ["SELECT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "cba_rule_versions",
    classification: "TENANT_RLS_REQUIRED",
    reason: "4 non-test reference(s) to 'cbaRuleVersions' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review). RESOLVED (round 11): same employer-execution/payroll-runs/remittance-runs/replay route family as cba_rule_set_items above — org-filtered via withRLSContext.",
    supportingCapability: ["app/api/employer-execution/payroll-runs/[id]/route.ts","app/api/employer-execution/payroll-runs/route.ts","app/api/employer-execution/remittance-runs/route.ts","app/api/employer-execution/replay/[runId]/route.ts"],
    requiredRuntimePrivileges: ["SELECT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "collective_agreements",
    classification: "TENANT_RLS_REQUIRED",
    reason: "11 non-test reference(s) to 'collectiveAgreements' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review). RESOLVED (round 11): app/api/agreements/route.ts's GET (minRole:'member') explicitly filters `eq(collectiveAgreements.organizationId, organizationId)` using the caller's own resolved organizationId — but executes that query inside withSystemContext (SYSTEM_RUNTIME), an apparently unjustified RLS bypass for an ordinary tenant-scoped read (no cross-org aggregation or platform-admin action visible in this route). FOLLOW-UP FLAGGED, not fixed this round: the app-level filter is present (no immediate cross-org leak proven), but this removes RLS as a backstop for this table/route — should be re-audited to confirm withSystemContext is actually necessary here, or downgraded to withRLSContext.",
    supportingCapability: ["app/api/agreements/route.ts","app/api/search/universal/route.ts","lib/queries/platform-stats.ts","lib/services/ai/clause-extraction-service.ts","lib/services/case-knowledge-graph-service.ts","lib/services/cba-service.ts","lib/services/clause-intelligence.ts","services/case-intelligence/case-knowledge-graph-service.ts","services/financial-service/drizzle/relations.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: ["SELECT"],
    invocationAuthority: "MIXED",
    dbExecutionPrincipal: "MIXED",
    reviewPriority: "NONE",
  },
  {
    table: "claim_precedent_analysis",
    classification: "LATENT_UNREACHABLE",
    reason: "Manually verified 2026-09-01 (round 5, unresolved-duplicate-family closure): two identical-shape declarations exist within the union-eyes app (db/schema/cba-intelligence-schema.ts and db/schema/domains/agreements/intelligence.ts — IDENTICAL_OR_PROVEN_COMPATIBLE; same columns/types/nullability/defaults, the domain copy only drops the Drizzle .references() FK annotation on claim_id→claims.claim_id). Zero non-test references to the 'claimPrecedentAnalysis' Drizzle export exist anywhere in app/, actions/, lib/, or services/ within apps/union-eyes proper — no route, server action, worker, or cron path queries it. The only other repo hits (services/financial-service/src/db/schema.ts, services/financial-service/drizzle/schema.ts, and its compiled .d.ts) are a same-named table in that service's OWN separate database (services/financial-service has its own drizzle.config.ts and package.json, connecting via its own DATABASE_URL — SEPARATE_DATABASE_BOUNDARY, mirroring the deadline_alerts entry's precedent) and are out of this manifest's remit. This table has no organization_id column at all (only claim_id) — if it is ever wired into a live route, it requires PARENT_OWNED_RLS_REQUIRED through claims, not a direct tenant policy.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "external_insurance_claims",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CLOSED (2026-09-04, round 40 integration control plane tranche): direct org-scoped integration table reached only through app/api/integrations/framework/**, where withApi derives organizationId from the authenticated caller and SyncEngine receives a trusted TENANT_RUNTIME context for a registry-approved insurance provider. The currently approved claim-writing path is the Manulife adapter, which selects existing claims by organizationId/provider/externalId, then inserts or updates the claim row; other claim-writing insurance adapters remain unavailable until registered as approved providers. No generic external-insurance CRUD route or arbitrary table-sync route was created. The generated ExternalInsuranceClaimsViewSet in backend/core/views.py remains router-registered but unconditionally denied via DenyAllPermission.",
    supportingCapability: ["app/api/integrations/framework/route.ts","app/api/integrations/framework/[id]/sync/route.ts","lib/integrations/control-plane.ts","lib/integrations/sync-engine.ts","lib/integrations/adapters/insurance/manulife-adapter.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
    {
    table: "fee_settlement_lines",
    classification: "LATENT_UNREACHABLE",
    reason: "CLOSED round 57: written only inside transaction-fee-engine.ts's closeSettlementBatch(), which (like createSettlementBatch()) has zero real callers in app/, actions/ — no Django model exists for this table either. No known application code path queries this table today.",
    supportingCapability: ["services/platform-economics/transaction-fee-engine.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "grievance_approvals",
    classification: "LATENT_UNREACHABLE",
    reason: "Manually verified 2026-09-02: sole non-test reference is lib/workflow-automation-engine.ts, which is EXCLUDED from the TypeScript project (apps/union-eyes/tsconfig.json exclude list) and has zero real production callers — consistent with the existing grievance_assignments/deadline_reassignment_convergence LATENT_UNREACHABLE disposition for the same module (see docs/union-eyes/reality-remediation/28_RLS_PRIVILEGED_CALLER_AND_ORG_CONTEXT_AUDIT.md, organization-context audit table).",
    supportingCapability: ["lib/workflow-automation-engine.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "grievance_communications",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'grievanceCommunications' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "grievance_documents",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01 against LIVE staging DB (nzila-staging-db, information_schema.columns): the real table has organization_id (uuid, NOT NULL), claim_id (uuid, NOT NULL), plus 31 columns total, matching db/schema/domains/claims/workflows.ts exactly. RESOLVED (2026-09-01, same day, PR #752 review round 2): the conflicting 6-column declaration in db/schema/domains/claims/grievance-lifecycle.ts (no organization_id, wrong FK column) has been REMOVED, not just documented. Its two real production consumers were fixed: app/api/grievances/[id]/documents/route.ts's insert into it always threw (referenced columns that do not physically exist), silently breaking the whole document-upload endpoint (outer try/catch masked it as a generic 500) — the dead insert was removed, letting the real governed-documents insert succeed. app/api/grievances/[id]/route.ts's SELECT against it had the same always-throws defect (masked the same way) — replaced with the already-working governed-documents query. Both fixes are net bug fixes, not behavior regressions, since the broken paths never successfully executed against this live schema. grievance_documents no longer appears in the CONFLICTING_SCHEMA section of apps/union-eyes/schema-duplicate-table-report.txt; see docs/union-eyes/reality-remediation/27_RLS_STORAGE_SCHEMA_CANONICALIZATION.md for full detail.",
    supportingCapability: ["app/api/grievances/[id]/documents/route.ts","app/api/grievances/[id]/route.ts","lib/document-management-system.ts","db/schema/domains/claims/workflows.ts","docs/union-eyes/reality-remediation/27_RLS_STORAGE_SCHEMA_CANONICALIZATION.md"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "grievance_settlements",
    classification: "TENANT_RLS_REQUIRED",
    reason: "RECLASSIFIED 2026-09-02 (round 7, raw-SQL LATENT-detection correction): this table was previously classified LATENT_UNREACHABLE based on a Drizzle-EXPORT-NAME-only reachability scan, which cannot find raw SQL references. A raw-SQL detection pass (see db/__tests__/rls-storage-authority-manifest-raw-sql-latent.test.ts for the detector/fixture) found real, direct raw-SQL table references (db.execute(sql`... FROM/INTO/UPDATE grievance_settlements ...`) or an equivalent quoted-table-name repository reference) in the file(s) listed below. Full HTTP-reachability/auth-boundary trace not yet completed. RESOLVED (round 11): app/api/finance/summary/route.ts (minRole:'officer') executes under withRLSContext with `WHERE organization_id = ${organizationId}` (the caller's own resolved org) — real, tenant-scoped, no cross-org exposure found.",
    supportingCapability: ["app/api/finance/summary/route.ts"],
    requiredRuntimePrivileges: ["SELECT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "grievance_stages",
    classification: "LATENT_UNREACHABLE",
    reason: "Manually verified 2026-09-02: sole non-test reference is lib/workflow-automation-engine.ts (excluded from the TS project, zero real callers) — same dead module as grievance_approvals/grievance_workflows.",
    supportingCapability: ["lib/workflow-automation-engine.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
    {
    table: "grievance_timeline_events",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CORRECTED round 57 (round-56's empty tsProductionReferences list was misleading — the real caller is a raw-SQL helper, not a Drizzle-symbol import): lib/ingestion/batch-ingest.ts's ingestGrievanceBatch() is called from app/api/admin/ingest/route.ts (admin-only). organization_id NOT NULL; the raw SQL insert explicitly parameterizes `${opts.organizationId}` (the trusted request context) and separately verifies each record's own organization_id matches before insert — not client-suppliable.",
    supportingCapability: ["app/api/admin/ingest/route.ts","lib/ingestion/batch-ingest.ts"],
    requiredRuntimePrivileges: ["INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "grievance_transitions",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01 against LIVE staging DB: 18 columns, organization_id (uuid, NOT NULL) and claim_id (uuid, NOT NULL, FK to claims.claim_id) both present, matching db/schema/domains/claims/workflows.ts exactly. The other declaration (db/schema/grievance-workflow-schema.ts, 19 cols) had a phantom `version` column that does not physically exist and has been converted to a re-export of the canonical declaration (PR #752 review round 3). Round-5 correction: lib/workers/report-worker.ts and lib/workflow-automation-engine.ts have been removed from this table's evidence — verified via git grep that NEITHER file has any real (non-test) importer anywhere in app/, actions/, lib/, or services/ (lib/job-queue.ts's own doc comment confirms all of lib/workers/*.ts was orphaned by the 2026-02-19 migration to Django Celery workers, and lib/workflow-automation-engine.ts/lib/case-assignment-engine.ts only import each other with no external caller — same dead-module family as grievance_assignments/grievance_stages/grievance_workflows). Real, live evidence is app/api/claims/[id]/workflow/history/route.ts (getCurrentUser-gated, plain `db`/withRLSContext, TENANT_RUNTIME) and lib/services/case-timeline-service.ts (plain `db`, reached via lib/services/sla-calculator.ts and the services barrel, not via the dead workflow engine). Direct organization_id column makes this straightforwardly tenant-scoped. NOT YET protected by migration 0108 — actual RLS policy addition is bundled with the other already-classified-but-unprotected tables (claim_deadlines, deadline_reminders, grievance_case_access_assignments, grievance_documents) as a batch follow-up, consistent with this PR's sequencing (manifest convergence before further 0108 changes).",
    supportingCapability: ["app/api/claims/[id]/workflow/history/route.ts","lib/services/case-timeline-service.ts","db/schema/domains/claims/workflows.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "grievance_workflows",
    classification: "LATENT_UNREACHABLE",
    reason: "Manually verified 2026-09-02: sole non-test reference is lib/workflow-automation-engine.ts (excluded from the TS project, zero real callers) — same dead module as grievance_approvals/grievance_stages.",
    supportingCapability: ["lib/workflow-automation-engine.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "pension_benefit_claims",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01 (round 6, Phase-3A priority tranche): direct NOT NULL organization_id column, reachable via live HTTP route(s) app/api/pension/benefit-claims/route.ts. org-scoped pension benefit claim submission endpoint; SELECT+INSERT confirmed. Minimum runtime privilege set from confirmed DML verbs (crudRoutes handler destructuring and/or direct .insert/.update/.delete/.select call-site evidence), not defaulted to FULL_DML.",
    supportingCapability: ["app/api/pension/benefit-claims/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "settlements",
    classification: "TENANT_RLS_REQUIRED",
    reason: "10 non-test reference(s) to 'settlements' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review). RESOLVED (round 11): same route as grievance_settlements (app/api/finance/summary/route.ts, minRole:'officer', withRLSContext, org-filtered). The marketing/dashboard page citations (features/analytics, customer-success, sector-analytics, support) match the plain-English word 'settlements' in UI copy, not this physical table — not counted toward reachability.",
    supportingCapability: ["app/[locale]/(marketing)/features/analytics/page.tsx","app/[locale]/dashboard/customer-success/page.tsx","app/[locale]/dashboard/sector-analytics/page.tsx","app/[locale]/dashboard/support/page.tsx","app/api/finance/summary/route.ts","lib/queries/platform-stats.ts","lib/services/cba-intelligence/adapters/esdc-adapter.ts","lib/services/cba-intelligence/adapters/provincial-board-adapter.ts","lib/services/cba-intelligence/adapters/union-bargaining-adapter.ts","lib/services/cba-intelligence/seed-sources.ts"],
    requiredRuntimePrivileges: ["SELECT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "signature_workflows",
    classification: "CONTAINED_NO_AUTHORITY",
    reason: "CLOSED (round 50, state-machine root and fan-out cascade authority \u2014 resolves the round 45 SEPARATE_DB_ROOT ejection using the round 48 same-database precedent already established for financial-service): confirmed THREE candidate implementations all trace to dead code, not merely a dual-schema declaration conflict. (1) lib/services/signature-workflow-service.ts (744 lines) is deliberately NOT re-exported through lib/services/index.ts ('import directly from file' comment) and has zero real callers anywhere \u2014 only its own test file and this manifest reference it. (2) services/pki/workflow-engine.ts's createWorkflow() is the ONLY function that ever persists to this table (db.insert(signatureWorkflows)), and createWorkflow() itself has zero real callers; every OTHER export in that file (recordSignature, advanceWorkflow, getWorkflow, cancelWorkflow, expireOverdueWorkflows) reads from an always-empty in-memory Map (workflowStore) that only createWorkflow populates \u2014 so even though app/api/admin/pki/workflows/[id]/route.ts and app/api/admin/pki/signatures/[id]/sign/route.ts are genuinely live routes that genuinely call these functions, every call is provably dead-in-practice (would always throw 'Workflow not found' against real data). (3) The admin sign route's actual successful write path is services/pki/signature-service.ts's signDocument(), which writes to digitalSignatures (financial-service's own table), NOT signatureWorkflows. The real, live, production signature subsystem for this app is a different table entirely: lib/signature/signature-service.ts's signatureDocuments, reached via app/api/signatures/{documents,sign,audit/[documentId]}/route.ts. financial-service's own drizzle/schema.ts declaration of signatureWorkflows shares this same Postgres database (round 48 finding) so no cross-database-boundary review is required. DJANGO CONTAINMENT (this round): the Django side has a live, router-registered ModelViewSet for this table (content app: SignatureWorkflowsViewSet) and a duplicate exposure in services/api/signature_service_views.py (SignatureServiceViewSet), but there is no legitimate consumer on the TS/Next.js side per the dead-code analysis above \u2014 both were changed from IsAuthenticated to a deny-all permission class (permission_classes = [DenyAllPermission]) this round to close the gap between 'Django can technically route to it' and 'nothing should ever be allowed to'.",
    supportingCapability: ["backend/content/views.py","backend/services/api/signature_service_views.py"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "union_representation_votes",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'unionRepresentationVotes' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "wcb_claims",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01 (round 6, Phase-3A priority tranche): direct NOT NULL organization_id column, reachable via live HTTP route(s) app/api/wcb/claims/route.ts, app/api/wcb/claims/[id]/route.ts. org-scoped WCB claim CRUD routes; crudRoutes destructures GET+POST on the collection route and GET+PATCH+DELETE on the item route. Minimum runtime privilege set from confirmed DML verbs (crudRoutes handler destructuring and/or direct .insert/.update/.delete/.select call-site evidence), not defaulted to FULL_DML.",
    supportingCapability: ["app/api/wcb/claims/route.ts","app/api/wcb/claims/[id]/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "workflow_definitions",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'workflowDefinitions' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "workflow_executions",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'workflowExecutions' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "arbitration_decisions",
    classification: "GLOBAL_REFERENCE_DATA",
    reason: "11 non-test reference(s) to 'arbitrationDecisions' found (round-7 scope-expansion scan). At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review). ROUND 11 CLOSED THIS TENANT_RLS_REQUIRED CITING A DEFECT: 'app/api/arbitration/precedents/route.ts ... crudRoutes({ orgScoped: true, writeRole: 'steward' }) — auto-filtered by the caller's own organizationId' — THIS WAS FACTUALLY WRONG and is corrected here. RECLASSIFIED round 58c (enforcement-geometry investigation): db/schema/domains/agreements/intelligence.ts and its duplicate services/financial-service/src/db/schema.ts declare arbitration_decisions with NO organizationId/org_id column at all (verified both declarations directly, byte-identical column sets). lib/api/crud-factory.ts's own orgScoped guard — `const orgCol = orgScoped ? getColumn(table, 'organizationId') : undefined;` then `if (orgScoped && orgCol && organizationId)` — proves orgCol is undefined for this table, so the org filter documented in round 11 NEVER fires; every steward-authenticated caller of any organization could read/write the same shared rows. Given isPublic (boolean, default true), free-text union/employer party fields (not org FKs), and the schema's own 'Public access' section header, this is a genuinely shared, cross-tenant legal-precedent library (arbitration awards are public tribunal records), not per-tenant data — matching the manifest's own established precedent for this exact 'orgScoped is a no-op' defect shape (see wage-benchmark-rates, cpi-inflation-index, dataClassificationPolicy in reference-latent.ts, each previously reclassified/fixed under the same doctrine). DEFECT FIXED round 58D (all 5 routes: route.ts, [id]/route.ts, [id]/citations/route.ts, [id]/documents/route.ts, search/route.ts): writeRole changed from the ordinary per-tenant 'steward' (ROLE_HIERARCHY level 50) to 'content_manager' (level 208, a genuine PLATFORM_ELEVATED_ROLES member per lib/api-auth-guard.ts, never tenant-self-service-assignable — no ordinary tenant role including admin/140 or app_owner-as-tenant-role can exceed this floor). Regression test added (app/api/arbitration/precedents/__tests__/arbitration-decisions-writerole.test.ts, 5/5 passing) proving all 5 routes register writeRole:'content_manager', never 'steward'/'admin'/'app_owner'. requiredRuntimePrivileges intentionally left unchanged (SELECT/INSERT/UPDATE/DELETE) since the DB-level principal for platform-elevated writers is still union_eyes_runtime (the authorization boundary is enforced at the application role-check layer, matching the round-52 dataClassificationPolicy precedent exactly) — GLOBAL_REFERENCE_DATA classification means no RLS policy is generated (ACL-only access control), which now correctly matches real, fixed application behavior.",
    supportingCapability: ["app/api/arbitration/precedents/[id]/citations/route.ts","app/api/arbitration/precedents/[id]/documents/route.ts","app/api/arbitration/precedents/[id]/route.ts","app/api/arbitration/precedents/route.ts","app/api/arbitration/precedents/search/route.ts","app/api/arbitration/precedents/__tests__/arbitration-decisions-writerole.test.ts","lib/services/ai/precedent-matching-service.ts","lib/services/ai/vector-search-service.ts","lib/services/precedent-service.ts","lib/api/crud-factory.ts","lib/api-auth-guard.ts","services/financial-service/drizzle/relations.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "arbitration_precedents",
    classification: "TENANT_RLS_REQUIRED",
    reason: "6 non-test reference(s) to 'arbitrationPrecedents' found (round-7 scope-expansion scan). At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review). RESOLVED (round 11): app/api/precedents/[id]/route.ts uses crudRoutes({ orgScoped: true, writeRole: 'steward' }) — auto-filtered by the caller's own organizationId.",
    supportingCapability: ["app/api/ai/semantic-search/route.ts","app/api/precedents/[id]/route.ts","lib/clc/data-products.ts","services/financial-service/drizzle/relations.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "bargaining_proposals",
    classification: "TENANT_RLS_REQUIRED",
    reason: "3 non-test reference(s) to 'bargainingProposals' found (round-7 scope-expansion scan). At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review). RESOLVED (round 11): app/api/bargaining/proposals/route.ts (+ [id] item route) use crudRoutes({ orgScoped: true, writeRole: 'steward' }) — auto-filtered by the caller's own organizationId.",
    supportingCapability: ["app/api/bargaining/proposals/[id]/route.ts","app/api/bargaining/proposals/route.ts","lib/services/negotiations-service.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "bargaining_team_members",
    classification: "CONTAINED_NO_AUTHORITY",
    reason: "CLOSED round 44 (RESOLVED_PARENT_ROOT candidate; parent negotiations is closed TENANT_RLS_REQUIRED, but the child itself has no real consumer): lib/services/negotiations-service.ts's listTeamMembers has zero real callers anywhere in app/, actions/, lib/, services/ \u2014 in fact ALL 7 exports of this service module have zero real callers (git-grep-confirmed round 44), see negotiation_sessions for the full finding. DEFECT FOUND AND FIXED THIS ROUND: BargainingTeamMembersViewSet (backend/bargaining/views.py) was router-registered with queryset=Model.objects.all() + IsAuthenticated-only and NO organization filter \u2014 contained via DenyAllPermission. Satisfies CONTAINED_NO_AUTHORITY: reachable-but-denied Django, dead TS, no legitimate consumer.",
    supportingCapability: ["lib/services/negotiations-service.ts","backend/bargaining/views.py"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "cba_contacts",
    classification: "CONTAINED_NO_AUTHORITY",
    reason: "CLOSED round 43: TS SIDE — no Drizzle declaration exists anywhere in this app's own db/schema/**; the only TS references are services/financial-service's own separate dual-schema (drizzle/relations.ts, drizzle/schema.ts, src/db/schema.ts), a different deployable Node service/package (round-41/42 dual-schema precedent), not this app's Next.js runtime. DJANGO SIDE — a real model+migration exists in this app's own backend/bargaining (CbaContacts.cba -> CollectiveAgreements.organization, a genuine potential parent-owned chain), and CbaContactsViewSet was router-registered (bargaining/urls.py: 'cba-contacts') with queryset=Model.objects.all() + IsAuthenticated-only and NO organization filter of any kind, exposing every organization's CBA contacts to any authenticated user. DEFECT FOUND AND FIXED THIS ROUND: contained via DenyAllPermission — git-grep across app/, actions/, lib/, services/, components/ found zero real frontend consumers of this endpoint. Satisfies CONTAINED_NO_AUTHORITY: reachable-but-denied Django, dead/separate-service-only TS, no legitimate consumer.",
    supportingCapability: ["backend/bargaining/views.py"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "cba_footnotes",
    classification: "CONTAINED_NO_AUTHORITY",
    reason: "CLOSED round 43: TS SIDE — no Drizzle declaration exists anywhere in this app's own db/schema/**; the only TS references are services/financial-service's own separate dual-schema (drizzle/relations.ts, drizzle/schema.ts, src/db/schema.ts), a different deployable Node service/package, not this app's Next.js runtime. DJANGO SIDE — a real model+migration exists in this app's own backend/bargaining (CbaFootnotes.source_clause -> CbaClauses.cba -> CollectiveAgreements.organization, a genuine two-hop potential parent-owned chain), and CbaFootnotesViewSet was router-registered (bargaining/urls.py: 'cba-footnotes') with queryset=Model.objects.all() + IsAuthenticated-only and NO organization filter of any kind, exposing every organization's CBA footnotes to any authenticated user. DEFECT FOUND AND FIXED THIS ROUND: contained via DenyAllPermission — git-grep across app/, actions/, lib/, services/, components/ found zero real frontend consumers of this endpoint. Satisfies CONTAINED_NO_AUTHORITY: reachable-but-denied Django, dead/separate-service-only TS, no legitimate consumer.",
    supportingCapability: ["backend/bargaining/views.py"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "cba_intel_agreements",
    classification: "GLOBAL_REFERENCE_DATA",
    reason: "CLOSED round 43 (CBA_INTELLIGENCE family): db/schema/domains/cba-intelligence/** has NO organizationId/organization_id column anywhere in the entire graph (mechanically verified via grep across the whole domain folder) — cba_intel_agreements is structured metadata extracted from a PUBLIC document (db/schema/domains/cba-intelligence/index.ts docstring: 'Public Canadian CBA intelligence schemas'), rooted at cba_intel_sources (an external labour-board/government source registry with no tenant concept at all). GET /api/cba-intelligence/agreements, /agreements/[id], /agreements/export, and /benchmark/[id] (via getAgreementById) all read the SAME shared dataset for every authenticated org (minRole member+commercial_reporting entitlement, no per-org filter — by design, since there is no tenant column to filter by). Writes: createAgreement (extraction-service.ts, internal to the extraction pipeline triggered by POST /api/cba-intelligence/extraction, minRole admin) and reviewStatus mutation via review-service.ts's submitReview (POST /api/cba-intelligence/review, minRole steward) — any org's own admin/steward can mutate this platform-wide shared content (content-integrity risk, not a tenant-confidentiality breach, same accepted risk class as testimonials/case_studies, round 11).",
    supportingCapability: ["app/api/cba-intelligence/agreements/route.ts","app/api/cba-intelligence/agreements/[id]/route.ts","app/api/cba-intelligence/agreements/export/route.ts","app/api/cba-intelligence/benchmark/[id]/route.ts","app/api/cba-intelligence/extraction/route.ts","app/api/cba-intelligence/review/route.ts","lib/services/cba-intelligence/extraction-service.ts","lib/services/cba-intelligence/extraction-orchestrator.ts","lib/services/cba-intelligence/review-service.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "cba_intel_benchmark_snapshots",
    classification: "GLOBAL_REFERENCE_DATA",
    reason: "CLOSED round 43 (CBA_INTELLIGENCE family): a computed analytical aggregate over the shared public agreement dataset (db/schema/domains/cba-intelligence/benchmarks.ts's 'comparables' jsonb array legitimately spans many cba_intel_agreements rows matched by jurisdiction/sector/union filters) — not a simple single-parent child, but there is no cross-tenant risk because NO row in this entire domain has an organization column (mechanically verified). GET /api/cba-intelligence/benchmark/[id] (minRole steward) computes and optionally persists (saveBenchmarkSnapshot, ?save=true) a snapshot targeting one public agreement while comparing against others in the same public dataset; ?history=true reads prior snapshots (getBenchmarkSnapshots). No UPDATE/DELETE path exists.",
    supportingCapability: ["app/api/cba-intelligence/benchmark/[id]/route.ts","lib/services/cba-intelligence/benchmark-service.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "cba_intel_clauses",
    classification: "GLOBAL_REFERENCE_DATA",
    reason: "CLOSED round 43 (CBA_INTELLIGENCE family): no organizationId column; parent chain cba_intel_clauses -> cba_intel_agreements -> cba_intel_documents -> cba_intel_sources, a root with no tenant concept at all (public source registry, mechanically verified zero org columns across the whole domain). GET /api/cba-intelligence/agreements/[id] (via listClauses(agreementId), minRole member) reads the shared dataset for every org. Writes: createClause (extraction-service.ts, internal to the extraction pipeline via POST /api/cba-intelligence/extraction, minRole admin) and reviewStatus mutation via review-service.ts's submitReview (POST /api/cba-intelligence/review, minRole steward) — same platform-wide content-integrity risk class as testimonials/case_studies (round 11), not a tenant-confidentiality issue since there is no tenant boundary in this domain.",
    supportingCapability: ["app/api/cba-intelligence/agreements/[id]/route.ts","app/api/cba-intelligence/extraction/route.ts","app/api/cba-intelligence/review/route.ts","lib/services/cba-intelligence/extraction-service.ts","lib/services/cba-intelligence/review-service.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "cba_intel_documents",
    classification: "GLOBAL_REFERENCE_DATA",
    reason: "CLOSED round 43 (CBA_INTELLIGENCE family): no organizationId column; parent is cba_intel_sources (sourceId, cascade), a public labour-board/government source registry with no tenant concept at all (mechanically verified zero org columns across the whole domain). GET /api/cba-intelligence/documents (listDocuments, minRole member) reads the shared dataset for every org. Writes: document-service.ts's upsertDocument (internal to the ingestion pipeline via POST /api/cba-intelligence/ingestion and /ingestion/run, minRole admin) — verified internally consistent: previousVersionId is always derived from an existing row matched on the SAME sourceId+sourceUrl, never client-supplied, so the document version chain cannot be corrupted cross-source. updateDocumentStatus (extraction-orchestrator.ts) sets processingStatus during the same admin-triggered pipeline.",
    supportingCapability: ["app/api/cba-intelligence/documents/route.ts","app/api/cba-intelligence/ingestion/route.ts","app/api/cba-intelligence/ingestion/run/route.ts","lib/services/cba-intelligence/document-service.ts","lib/services/cba-intelligence/extraction-orchestrator.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "cba_intel_extraction_runs",
    classification: "GLOBAL_REFERENCE_DATA",
    reason: "CLOSED round 43 (CBA_INTELLIGENCE family): no organizationId column; parent is cba_intel_documents -> cba_intel_sources, a root with no tenant concept at all (mechanically verified zero org columns across the whole domain). GET /api/cba-intelligence/health (via health-service.ts's listExtractionRuns) reads the shared dataset for every org (minRole steward). Writes: createExtractionRun + completeExtractionRun (extraction-service.ts, internal to the extraction pipeline via POST /api/cba-intelligence/extraction, minRole admin) — getExtractionRunById is also called internally by completeExtractionRun to check current state before updating, no client-supplied cross-document risk.",
    supportingCapability: ["app/api/cba-intelligence/extraction/route.ts","app/api/cba-intelligence/health/route.ts","lib/services/cba-intelligence/extraction-service.ts","lib/services/cba-intelligence/health-service.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "cba_intel_findings",
    classification: "GLOBAL_REFERENCE_DATA",
    reason: "CLOSED round 43 (CBA_INTELLIGENCE family): no organizationId column; dual parent FKs (extractionRunId AND a redundant direct documentId) — verified internally CONSISTENT by construction: extraction-orchestrator.ts derives both from the SAME in-scope 'documentId' local variable for a single extraction run, so a finding can never reference a document different from its own extraction run's document. Root cba_intel_documents -> cba_intel_sources has no tenant concept at all (mechanically verified zero org columns across the whole domain). GET /api/cba-intelligence/review (review queue, minRole steward) reads the shared dataset for every org. Writes: createFinding/createFindingsBatch (extraction-service.ts, internal to the extraction pipeline via POST /api/cba-intelligence/extraction, minRole admin) and reviewStatus mutation via review-service.ts's submitReview (POST /api/cba-intelligence/review, minRole steward).",
    supportingCapability: ["app/api/cba-intelligence/extraction/route.ts","app/api/cba-intelligence/review/route.ts","lib/services/cba-intelligence/extraction-service.ts","lib/services/cba-intelligence/extraction-orchestrator.ts","lib/services/cba-intelligence/review-service.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "cba_intel_freshness_log",
    classification: "LATENT_UNREACHABLE",
    reason: "CLOSED round 43: git-grep-confirmed zero real (non-test, non-build-artifact) callers of BOTH freshness-service.ts's logFreshnessCheck (the sole INSERT writer) and getFreshnessHistory (the sole SELECT reader) anywhere in app/, actions/, lib/, services/, components/. The GET /api/cba-intelligence/freshness route reads a LIVE-computed overview (getFreshnessOverview -> computeSourceFreshness) that never touches this table at all. The only writer, ingestion-scheduler.ts's updateFreshnessLogs(), is called exclusively from runScheduledIngestion(), which itself has zero real callers (no cron route, no vercel.json entry, no GitHub Actions workflow wires startScheduler()/runScheduledIngestion() anywhere) — the timer-based scheduler is dead, unwired library code. No raw-SQL reference to the physical table name found outside db/migrations/** (table creation only) and this manifest. NOT a permanent disposition — must be revisited if either write or read path is wired to a real caller.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "cba_intel_ingestion_jobs",
    classification: "GLOBAL_REFERENCE_DATA",
    reason: "CLOSED round 43 (CBA_INTELLIGENCE family): no organizationId column; parent is cba_intel_sources, a root with no tenant concept at all (mechanically verified zero org columns across the whole domain). GET /api/cba-intelligence/ingestion (listIngestionJobs, minRole steward) and GET /api/cba-intelligence/health (via health-service.ts) read the shared dataset for every org. Writes: createIngestionJob (POST /api/cba-intelligence/ingestion, minRole admin, verifies referenced sourceId exists and isActive first) and startIngestionJob/completeIngestionJob/failIngestionJob/cancelIngestionJob (ingestion-service.ts, internal to the ingestion pipeline via POST /api/cba-intelligence/ingestion/run, minRole admin). The triggerType enum includes 'scheduled', but the only real invocation evidenced in this scan is the tenant-triggered admin route — the timer-based scheduler (ingestion-scheduler.ts) is unwired dead code (see cba_intel_freshness_log); do not infer MIXED/SYSTEM_SCHEDULE invocation from an inert helper.",
    supportingCapability: ["app/api/cba-intelligence/ingestion/route.ts","app/api/cba-intelligence/ingestion/run/route.ts","app/api/cba-intelligence/health/route.ts","lib/services/cba-intelligence/ingestion-service.ts","lib/services/cba-intelligence/ingestion-orchestrator.ts","lib/services/cba-intelligence/health-service.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "cba_intel_review_decisions",
    classification: "GLOBAL_REFERENCE_DATA",
    reason: "CLOSED round 51 (CBA_INTELLIGENCE family, consistent with the round-43 descendants and the round-51 cba_intel_sources root disposition): db/schema/domains/cba-intelligence/review.ts's cbaIntelReviewDecisions has no organizationId column — a polymorphic targetType/targetId (finding/agreement/wage_adjustment/clause) pointing into the SAME no-tenant-concept domain rooted at cba_intel_sources, plus a reviewerId that is only the reviewing user's id, not an org scope. Mutated via lib/services/cba-intelligence/review-service.ts's submitReview (POST /api/cba-intelligence/review, minRole steward) — the same platform-wide content-integrity risk class as the round-43 entries (any org's own steward can record a review decision against the shared dataset). No Django model exists for cba_intel_review_decisions (nothing to contain).",
    supportingCapability: ["app/api/cba-intelligence/review/route.ts","lib/services/cba-intelligence/review-service.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "cba_intel_sources",
    classification: "GLOBAL_REFERENCE_DATA",
    reason: "CLOSED round 51 (cba_intel_sources root disposition, mandatory per GLOBAL_REFERENCE_AND_SHARED_CONFIGURATION_SCOPE_AUTHORITY doctrine): CONFIRMS round 43's root assumption for the whole CBA_INTELLIGENCE family (cba_intel_agreements/clauses/documents/wage_adjustments etc., all rooted at this table) — db/schema/domains/cba-intelligence/** has NO organizationId/organization_id column anywhere in the entire domain (mechanically verified via grep), including this table itself. GET/POST /api/cba-intelligence/sources (source-registry-service.ts's listSources/createSource, minRole steward/admin) and GET/PATCH /api/cba-intelligence/sources/[id] (getSourceById/updateSource/deactivateSource, minRole steward/admin) read and write the SAME shared platform-wide source registry for every org — any org's own admin/steward can register/mutate a source, same content-integrity-not-confidentiality risk class already accepted for the round-43 descendants. lib/services/cba-intelligence/ingestion-scheduler.ts's doc-comment mentions a Vercel Cron/external-cron trigger, but that module (and freshness-service.ts, which also touches this table) has ZERO production callers anywhere (git-grep confirmed) — the 'cron' path is aspirational/unwired, not a live SYSTEM_SCHEDULE invocation; only the ordinary org-authenticated routes above actually execute against this table. No Django model exists for cba_intel_sources (nothing to contain).",
    supportingCapability: ["app/api/cba-intelligence/sources/route.ts","app/api/cba-intelligence/sources/[id]/route.ts","lib/services/cba-intelligence/source-registry-service.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "cba_intel_wage_adjustments",
    classification: "GLOBAL_REFERENCE_DATA",
    reason: "CLOSED round 43 (CBA_INTELLIGENCE family): no organizationId column; parent chain cba_intel_wage_adjustments -> cba_intel_agreements -> cba_intel_documents -> cba_intel_sources, a root with no tenant concept at all (mechanically verified zero org columns across the whole domain). GET /api/cba-intelligence/agreements/[id] (via listWageAdjustments(agreementId), minRole member) and GET /api/cba-intelligence/benchmark/[id] (benchmark-service.ts selects wage adjustments across comparable agreements, minRole steward) read the shared dataset for every org. Writes: createWageAdjustment (extraction-service.ts, internal to the extraction pipeline via POST /api/cba-intelligence/extraction, minRole admin) and reviewStatus mutation via review-service.ts's submitReview (POST /api/cba-intelligence/review, minRole steward) — same platform-wide content-integrity risk class as testimonials/case_studies (round 11), not a tenant-confidentiality issue since there is no tenant boundary in this domain.",
    supportingCapability: ["app/api/cba-intelligence/agreements/[id]/route.ts","app/api/cba-intelligence/benchmark/[id]/route.ts","app/api/cba-intelligence/extraction/route.ts","app/api/cba-intelligence/review/route.ts","lib/services/cba-intelligence/extraction-service.ts","lib/services/cba-intelligence/benchmark-service.ts","lib/services/cba-intelligence/review-service.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "cba_version_history",
    classification: "CONTAINED_NO_AUTHORITY",
    reason: "CLOSED round 43: TS SIDE — no Drizzle declaration exists anywhere in this app's own db/schema/**; the only TS references are services/financial-service's own separate dual-schema (drizzle/relations.ts, drizzle/schema.ts, src/db/schema.ts), a different deployable Node service/package, not this app's Next.js runtime. DJANGO SIDE — a real model+migration exists in this app's own backend/bargaining (CbaVersionHistory.cba -> CollectiveAgreements.organization, a genuine potential parent-owned chain), and CbaVersionHistoryViewSet was router-registered (bargaining/urls.py: 'cba-version-history') with queryset=Model.objects.all() + IsAuthenticated-only and NO organization filter of any kind, exposing every organization's CBA version history to any authenticated user. DEFECT FOUND AND FIXED THIS ROUND: contained via DenyAllPermission — git-grep across app/, actions/, lib/, services/, components/ found zero real frontend consumers of this endpoint. Satisfies CONTAINED_NO_AUTHORITY: reachable-but-denied Django, dead/separate-service-only TS, no legitimate consumer.",
    supportingCapability: ["backend/bargaining/views.py"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "claim_updates",
    classification: "TENANT_RLS_REQUIRED",
    reason: "18 non-test reference(s) to 'claimUpdates' found (round-7 scope-expansion scan). At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review). RESOLVED (round 11): app/api/cases/[caseId]/timeline/route.ts (minRole:'member') and the sibling cases/[caseId]/** routes all execute via withRLSContext — tenant-scoped, no withSystemContext site found for this table.",
    supportingCapability: ["app/api/cases/[caseId]/assign/route.ts","app/api/cases/[caseId]/export/route.ts","app/api/cases/[caseId]/notes/route.ts","app/api/cases/[caseId]/timeline/route.ts","app/api/cases/[caseId]/transition/route.ts","app/api/claims/[id]/evidence/route.ts","app/api/metrics/operational/route.ts","app/api/notifications/preferences/route.ts","app/api/workflow/transition/route.ts","lib/ai/template-engine.ts","lib/gdpr/consent-manager.ts","lib/services/case-timeline-service.ts","lib/services/claims-service.ts","lib/workflow-automation-engine.ts","lib/workflow-engine.ts","services/financial-service/drizzle/relations.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "clc_bargaining_trends",
    classification: "CONTAINED_NO_AUTHORITY",
    reason: "CLOSED round 51 (GLOBAL_REFERENCE_AND_SHARED_CONFIGURATION_SCOPE_AUTHORITY, no-org candidate universe): sole TS consumer(s) lib/services/external-data/clc-partnership-service.ts have zero production importers anywhere in app/, actions/, lib/, services/ outside their own test files (git-grep confirmed) — dead TS code, no legitimate consumer on the TypeScript side. The generated Django ViewSet(s) in backend/billing/views.py exposed queryset=Model.objects.all() + IsAuthenticated-only with NO organization filter of any kind. Contained this round via SharedDenyAllPermission in backend/billing/views.py. Satisfies CONTAINED_NO_AUTHORITY: reachable-but-denied Django, dead TS, no legitimate consumer.",
    supportingCapability: ["lib/services/external-data/clc-partnership-service.ts","backend/billing/views.py"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "deadline_reminder_executions",
    classification: "LATENT_UNREACHABLE",
    reason: "Round-7 scope-expansion scan: zero references to the 'deadlineReminderExecutions' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files via a combined ripgrep pass across app/, actions/, lib/, services/. No known application code path queries this table today. NOT yet individually checked for raw-SQL (non-Drizzle-symbol) references to the physical table name — see the raw-SQL LATENT fixture test for why that check matters before this can be treated as final.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
    {
    table: "fee_settlement_batches",
    classification: "LATENT_UNREACHABLE",
    reason: "CLOSED round 57: transaction-fee-engine.ts's createSettlementBatch()/closeSettlementBatch() (the sole writers) have zero real callers in app/, actions/ (confirmed via direct function-name search, not just filename) — no Django model exists for this table either (djangoModelFound=false in the round-57 census). No known application code path queries this table today.",
    supportingCapability: ["services/platform-economics/transaction-fee-engine.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "grievance_events",
    classification: "TENANT_RLS_REQUIRED",
    reason: "11 non-test reference(s) to 'grievanceEvents' found (round-7 scope-expansion scan). At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review). RESOLVED (round 11): app/api/grievances/route.ts and its [id]/** sub-routes execute via withRLSContext (requireEntitlement + org-scoped) — tenant-scoped, no withSystemContext site found for this table.",
    supportingCapability: ["app/api/cases/[caseId]/escalate/route.ts","app/api/grievances/[id]/assign/route.ts","app/api/grievances/[id]/convert/route.ts","app/api/grievances/[id]/documents/route.ts","app/api/grievances/[id]/priority-override/route.ts","app/api/grievances/[id]/route.ts","app/api/grievances/[id]/status/route.ts","app/api/grievances/import/route.ts","app/api/grievances/route.ts","app/api/search/universal/route.ts","lib/cognition/ue-adapter.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "grievance_responses",
    classification: "LATENT_UNREACHABLE",
    reason: "Round-7 scope-expansion scan: zero references to the 'grievanceResponses' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files via a combined ripgrep pass across app/, actions/, lib/, services/. No known application code path queries this table today. NOT yet individually checked for raw-SQL (non-Drizzle-symbol) references to the physical table name — see the raw-SQL LATENT fixture test for why that check matters before this can be treated as final.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "grievance_timeline",
    classification: "TENANT_RLS_REQUIRED",
    reason: "1 non-test reference(s) to 'grievanceTimeline' found (round-7 scope-expansion scan). At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review). RESOLVED (round 11): sole reference app/api/cases/[caseId]/timeline/route.ts (minRole:'member', withRLSContext) — same route family as claim_updates/grievance_events above.",
    supportingCapability: ["app/api/cases/[caseId]/timeline/route.ts"],
    requiredRuntimePrivileges: ["SELECT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
]
