/**
 * db/rls-storage-authority/claims-continuity.ts
 *
 * PR #752 round 9: extracted from the single-file
 * db/rls-storage-authority-manifest.ts (which exceeded the repository's
 * 8000-line hard cap at 8009 lines — see
 * tooling/contract-tests/file-size-enforcement.test.ts) into semantic
 * domain modules. This module owns: Claims, grievances, deadlines, bargaining, workflow.
 *
 * Domain boundaries were assigned mechanically by table-name keyword
 * matching against the entry's `table` field (see the one-time migration
 * script referenced in the round-9 commit message) — every entry's DATA
 * (classification, reason, privileges, authority) is unchanged from the
 * pre-split manifest; only its physical file location changed. Do not
 * hand-edit an entry's domain placement without also checking
 * db/__tests__/rls-storage-authority-registry-composition.test.ts, which
 * proves the composed registry is unaffected by which module an entry
 * lives in.
 *
 * Add NEW entries to whichever domain module most closely matches the
 * table's real subject matter; when genuinely ambiguous, prefer
 * reference-latent.ts (the catch-all) over forcing a bad fit elsewhere.
 */
import type { StorageAuthorityEntry } from './types';

export const claimsContinuityEntries: StorageAuthorityEntry[] = [
  {
    table: "claim_deadlines",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified 2026-09-01, corrected 2026-09-02 (round 5): direct NOT NULL organization_id column (db/schema/deadlines-schema.ts, Drizzle export 'deadlines' backing physical table 'claim_deadlines'), reachable via live HTTP routes (app/api/deadlines/route.ts, app/api/deadlines/[id]/complete/route.ts, app/api/deadlines/[id]/extend/route.ts, app/api/deadlines/overdue/route.ts, app/api/deadlines/upcoming/route.ts — all crudRoutes({ readRole: 'member', writeRole: 'steward' })) and core services (lib/deadline-tracking-system.ts, lib/deadline-service.ts), all using the plain `db` import (no withSystemContext). Round-5 correction: the previously-cited app/api/cron/deadline-overdue/route.ts does NOT touch this table — it queries `grievance_deadlines` (an existing 0108-protected table) and `deadline_reminders` only, both inside withSystemContext; that citation was a false evidence match and has been removed. No system-context path touches claim_deadlines today.",
    supportingCapability: ["app/api/deadlines/route.ts","app/api/deadlines/[id]/complete/route.ts","app/api/deadlines/[id]/extend/route.ts","app/api/deadlines/overdue/route.ts","app/api/deadlines/upcoming/route.ts","lib/deadline-tracking-system.ts","lib/deadline-service.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "deadline_reminders",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified 2026-09-01, resolved 2026-09-02 (round 5): direct NOT NULL organization_id column (db/schema/deadline-engine-schema.ts). MIXED — genuinely reached two ways: (1) lib/deadline-engine/reminder-scheduler.ts's scheduleGrievanceDeadlineReminders()/cancelGrievanceDeadlineReminders() write it via the plain `db` import (TENANT_RUNTIME), called from tenant-authenticated flows (lib/deadline-tracking-system.ts, itself reachable via the claim_deadlines API routes, member/steward-gated); (2) app/api/cron/deadline-overdue/route.ts (auth: { cron: true }, CRON_SECRET_KEY-gated — SYSTEM_SCHEDULE) reads it via a raw SQL `select ... from deadline_reminders` inside withSystemContext to check for an existing in-flight reminder before enqueuing a new one — a real SELECT-only system-context read, verified by reading the route's SQL directly; the actual write (scheduleGrievanceDeadlineReminders) happens afterward, outside withSystemContext, via the same TENANT_RUNTIME path as (1).",
    supportingCapability: ["app/api/cron/deadline-overdue/route.ts","lib/deadline-engine/reminder-scheduler.ts","lib/deadline-tracking-system.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: ["SELECT"],
    invocationAuthority: "MIXED",
    dbExecutionPrincipal: "MIXED",
    reviewPriority: "HIGH",
  },
  {
    table: "grievance_case_access_assignments",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified 2026-09-01: direct NOT NULL organization_id column (db/schema/domains/claims/grievance-lifecycle.ts), reachable via live HTTP routes app/api/grievances/[id]/access/route.ts and app/api/grievances/[id]/route.ts, and lib/services/case-access-service.ts (getEffectiveCaseAccess). Grants per-user case access within a grievance — governs who else can see privileged case material, making cross-tenant leakage here especially sensitive.",
    supportingCapability: ["app/api/grievances/[id]/access/route.ts","app/api/grievances/[id]/route.ts","lib/services/case-access-service.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "grievance_assignments",
    classification: "LATENT_UNREACHABLE",
    reason: "Manually verified 2026-09-01 (PR #752 review Item #9 audit): its only two referencing modules, lib/case-assignment-engine.ts and lib/workflow-automation-engine.ts, have no production HTTP caller — workflow-automation-engine.ts is imported only by its own test file, and case-assignment-engine.ts is imported only dynamically from within workflow-automation-engine.ts. A trust-boundary guardrail comment was added to case-assignment-engine.ts documenting this for future integrators. Revisit before either module is wired into a live route.",
    supportingCapability: ["lib/case-assignment-engine.ts","lib/workflow-automation-engine.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "deadline_reassignment_convergence",
    classification: "LATENT_UNREACHABLE",
    reason: "Manually verified 2026-09-01: written only by lib/deadline-engine/assignment-sync.ts's refreshDeadlineRemindersForGrievance(), which is re-exported from lib/deadline-engine/index.ts but has zero real (non-test) importers of that export — only its own test file and lib/reality/capability-registry.ts (documentation, not a call site) reference it. The durable-outbox retry-worker infrastructure exists but is not wired into any live route, action, or cron job today.",
    supportingCapability: ["lib/deadline-engine/assignment-sync.ts","lib/deadline-engine/index.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "deadline_alerts",
    classification: "LATENT_UNREACHABLE",
    reason: "Manually verified 2026-09-01: automated scan's 3 matches are both false positives — app/api/notifications/preferences/route.ts's 'deadlineAlerts' is an unrelated boolean notification-preference field name, not the Drizzle table export; services/financial-service/**/schema.ts's 'deadline_alerts' is a same-named table in that service's OWN separate database (services/financial-service/src/db/index.ts connects via its own process.env.DATABASE_URL and its own drizzle.config.ts — a distinct database boundary, mirroring 0108's own precedent for out-of-scope root-level /migrations/ tables). No real reference to this table's actual Drizzle export was found in the main union-eyes app.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "deadline_extensions",
    classification: "LATENT_UNREACHABLE",
    reason: "Verified 2026-09-01 (round 6, Phase-3A priority tranche + reachability-scan correction): lib/reality/capability-registry.ts is a static narrative/audit-trail data file (an array of descriptive capability-verification strings), not executable query code — it contains no database calls and its mention of 'deadline_extensions' is commentary, not a call site. No other non-test reference exists in app/, actions/, lib/, or services/. Resolves the prior entry's open question ('needs a manual check of whether it drives real query behavior') — it does not.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "deadline_rules",
    classification: "LATENT_UNREACHABLE",
    reason: "Verified 2026-09-01 (round 6, Phase-3A priority tranche + reachability-scan correction): lib/reality/capability-registry.ts is a static narrative/audit-trail data file (an array of descriptive capability-verification strings), not executable query code — it contains no database calls and its mention of 'deadline_rules' is commentary, not a call site. No other non-test reference exists in app/, actions/, lib/, or services/. Resolves the prior entry's open question ('needs a manual check of whether it drives real query behavior') — it does not.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "ai_grievance_triages",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified 2026-09-02: direct NOT NULL organization_id column (db/schema/domains/ml/ai-grievance-triage.ts). Sole listed reference lib/ai/grievance-triage.ts is confirmed reachable via live HTTP routes app/api/ai/grievances/triage/route.ts and app/api/ai/grievances/[id]/triage/route.ts — the earlier \"no obvious HTTP-route\" scan result was a false negative.",
    supportingCapability: ["lib/ai/grievance-triage.ts","app/api/ai/grievances/triage/route.ts","app/api/ai/grievances/[id]/triage/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "arbitrations",
    classification: "PARENT_OWNED_RLS_REQUIRED",
    reason: "Manually verified 2026-09-02: NO direct organization_id column (db/schema/grievance-schema.ts) — scoped only through the parent grievances row's organization_id via grievance_id (NOT NULL FK). Reachable via live HTTP routes app/api/arbitrations/route.ts, app/api/arbitrations/[id]/route.ts, app/api/finance/summary/route.ts.",
    supportingCapability: ["app/api/arbitrations/route.ts","app/api/arbitrations/[id]/route.ts","app/api/finance/summary/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "bargaining_notes",
    classification: "NEEDS_REVIEW",
    reason: "6 non-test reference(s) to 'bargainingNotes' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/bargaining-notes/[id]/route.ts","app/api/cbas/[id]/route.ts","lib/services/bargaining-notes-service.ts","services/financial-service/drizzle/relations.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "bargaining_units",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified 2026-09-02: direct NOT NULL organization_id column (db/schema/union-structure-schema.ts). Reachable via live HTTP routes app/api/units/route.ts, app/api/units/[id]/route.ts, app/api/locals/route.ts, app/api/locals/[id]/route.ts, app/api/jurisdiction/clc-compliance/route.ts, app/api/jurisdiction/validate-deadline/route.ts.",
    supportingCapability: ["app/api/units/route.ts","app/api/units/[id]/route.ts","app/api/locals/route.ts","app/api/locals/[id]/route.ts","app/api/jurisdiction/clc-compliance/route.ts","app/api/jurisdiction/validate-deadline/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "case_documents",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01, corrected 2026-09-02 (round 5): the previously-cited app/api/case-repository/[caseId]/documents/route.ts does not exist in the repo (stale scan path) — real, verified reference is app/api/documents/[id]/route.ts, which reads `db.query.caseDocuments.findFirst(...)` filtered by documentId+isImmutable (SELECT only) behind `withApi({ auth: { required: true, minRole: 'app_owner' } })` (app_owner is a tenant-org-scoped role tier, not a platform-level role) using the plain `db` import (no withSystemContext). direct organization_id column confirmed on the case_documents export.",
    supportingCapability: ["app/api/documents/[id]/route.ts"],
    requiredRuntimePrivileges: ["SELECT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "case_studies",
    classification: "NEEDS_REVIEW",
    reason: "5 non-test reference(s) to 'caseStudies' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/[locale]/(marketing)/case-studies/page.tsx","app/[locale]/(marketing)/locale-site-footer.tsx","app/api/case-studies/[slug]/route.ts","app/api/case-studies/route.ts","lib/marketing-hero-imagery.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "cba_clauses",
    classification: "NEEDS_REVIEW",
    reason: "8 non-test reference(s) to 'cbaClause' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/ai/semantic-search/route.ts","app/api/clauses/route.ts","app/api/clauses/search/route.ts","lib/services/ai/clause-extraction-service.ts","lib/services/ai/vector-search-service.ts","lib/services/clause-intelligence.ts","lib/services/clause-service.ts","services/financial-service/drizzle/relations.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "cba_rule_set_items",
    classification: "NEEDS_REVIEW",
    reason: "2 non-test reference(s) to 'cbaRuleSetItems' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/employer-execution/payroll-runs/route.ts","app/api/employer-execution/replay/[runId]/route.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "cba_rule_versions",
    classification: "NEEDS_REVIEW",
    reason: "4 non-test reference(s) to 'cbaRuleVersions' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/employer-execution/payroll-runs/[id]/route.ts","app/api/employer-execution/payroll-runs/route.ts","app/api/employer-execution/remittance-runs/route.ts","app/api/employer-execution/replay/[runId]/route.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "collective_agreements",
    classification: "NEEDS_REVIEW",
    reason: "11 non-test reference(s) to 'collectiveAgreements' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/agreements/route.ts","app/api/search/universal/route.ts","lib/queries/platform-stats.ts","lib/services/ai/clause-extraction-service.ts","lib/services/case-knowledge-graph-service.ts","lib/services/cba-service.ts","lib/services/clause-intelligence.ts","services/case-intelligence/case-knowledge-graph-service.ts","services/financial-service/drizzle/relations.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "claim_precedent_analysis",
    classification: "LATENT_UNREACHABLE",
    reason: "Manually verified 2026-09-01 (round 5, unresolved-duplicate-family closure): two identical-shape declarations exist within the union-eyes app (db/schema/cba-intelligence-schema.ts and db/schema/domains/agreements/intelligence.ts — IDENTICAL_OR_PROVEN_COMPATIBLE; same columns/types/nullability/defaults, the domain copy only drops the Drizzle .references() FK annotation on claim_id→claims.claim_id). Zero non-test references to the 'claimPrecedentAnalysis' Drizzle export exist anywhere in app/, actions/, lib/, or services/ within apps/union-eyes proper — no route, server action, worker, or cron path queries it. The only other repo hits (services/financial-service/src/db/schema.ts, services/financial-service/drizzle/schema.ts, and its compiled .d.ts) are a same-named table in that service's OWN separate database (services/financial-service has its own drizzle.config.ts and package.json, connecting via its own DATABASE_URL — SEPARATE_DATABASE_BOUNDARY, mirroring the deadline_alerts entry's precedent) and are out of this manifest's remit. This table has no organization_id column at all (only claim_id) — if it is ever wired into a live route, it requires PARENT_OWNED_RLS_REQUIRED through claims, not a direct tenant policy.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "external_insurance_claims",
    classification: "NEEDS_REVIEW",
    reason: "5 non-test reference(s) to 'externalInsuranceClaims' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/graphql/resolvers.ts","lib/integrations/adapters/insurance/canadalife-adapter.ts","lib/integrations/adapters/insurance/greenshield-adapter.ts","lib/integrations/adapters/insurance/ia-adapter.ts","lib/integrations/adapters/insurance/manulife-adapter.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "fee_settlement_lines",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'feeSettlementLines' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["services/platform-economics/transaction-fee-engine.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "grievance_approvals",
    classification: "LATENT_UNREACHABLE",
    reason: "Manually verified 2026-09-02: sole non-test reference is lib/workflow-automation-engine.ts, which is EXCLUDED from the TypeScript project (apps/union-eyes/tsconfig.json exclude list) and has zero real production callers — consistent with the existing grievance_assignments/deadline_reassignment_convergence LATENT_UNREACHABLE disposition for the same module (see docs/union-eyes/reality-remediation/28_RLS_PRIVILEGED_CALLER_AND_ORG_CONTEXT_AUDIT.md, organization-context audit table).",
    supportingCapability: ["lib/workflow-automation-engine.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "grievance_communications",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'grievanceCommunications' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "grievance_documents",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01 against LIVE staging DB (nzila-staging-db, information_schema.columns): the real table has organization_id (uuid, NOT NULL), claim_id (uuid, NOT NULL), plus 31 columns total, matching db/schema/domains/claims/workflows.ts exactly. RESOLVED (2026-09-01, same day, PR #752 review round 2): the conflicting 6-column declaration in db/schema/domains/claims/grievance-lifecycle.ts (no organization_id, wrong FK column) has been REMOVED, not just documented. Its two real production consumers were fixed: app/api/grievances/[id]/documents/route.ts's insert into it always threw (referenced columns that do not physically exist), silently breaking the whole document-upload endpoint (outer try/catch masked it as a generic 500) — the dead insert was removed, letting the real governed-documents insert succeed. app/api/grievances/[id]/route.ts's SELECT against it had the same always-throws defect (masked the same way) — replaced with the already-working governed-documents query. Both fixes are net bug fixes, not behavior regressions, since the broken paths never successfully executed against this live schema. grievance_documents no longer appears in the CONFLICTING_SCHEMA section of apps/union-eyes/schema-duplicate-table-report.txt; see docs/union-eyes/reality-remediation/27_RLS_STORAGE_SCHEMA_CANONICALIZATION.md for full detail.",
    supportingCapability: ["app/api/grievances/[id]/documents/route.ts","app/api/grievances/[id]/route.ts","lib/document-management-system.ts","db/schema/domains/claims/workflows.ts","docs/union-eyes/reality-remediation/27_RLS_STORAGE_SCHEMA_CANONICALIZATION.md"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "grievance_settlements",
    classification: "NEEDS_REVIEW",
    reason: "RECLASSIFIED 2026-09-02 (round 7, raw-SQL LATENT-detection correction): this table was previously classified LATENT_UNREACHABLE based on a Drizzle-EXPORT-NAME-only reachability scan, which cannot find raw SQL references. A raw-SQL detection pass (see db/__tests__/rls-storage-authority-manifest-raw-sql-latent.test.ts for the detector/fixture) found real, direct raw-SQL table references (db.execute(sql`... FROM/INTO/UPDATE grievance_settlements ...`) or an equivalent quoted-table-name repository reference) in the file(s) listed below. Full HTTP-reachability/auth-boundary trace not yet completed.",
    supportingCapability: ["app/api/finance/summary/route.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "grievance_stages",
    classification: "LATENT_UNREACHABLE",
    reason: "Manually verified 2026-09-02: sole non-test reference is lib/workflow-automation-engine.ts (excluded from the TS project, zero real callers) — same dead module as grievance_approvals/grievance_workflows.",
    supportingCapability: ["lib/workflow-automation-engine.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "grievance_timeline_events",
    classification: "NEEDS_REVIEW",
    reason: "RECLASSIFIED 2026-09-02 (round 7, raw-SQL LATENT-detection correction): this table was previously classified LATENT_UNREACHABLE based on a Drizzle-EXPORT-NAME-only reachability scan, which cannot find raw SQL references. A raw-SQL detection pass (see db/__tests__/rls-storage-authority-manifest-raw-sql-latent.test.ts for the detector/fixture) found real, direct raw-SQL table references (db.execute(sql`... FROM/INTO/UPDATE grievance_timeline_events ...`) or an equivalent quoted-table-name repository reference) in the file(s) listed below. Full HTTP-reachability/auth-boundary trace not yet completed.",
    supportingCapability: ["lib/ingestion/batch-ingest.ts","lib/ingestion/post-import-verification.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "grievance_transitions",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01 against LIVE staging DB: 18 columns, organization_id (uuid, NOT NULL) and claim_id (uuid, NOT NULL, FK to claims.claim_id) both present, matching db/schema/domains/claims/workflows.ts exactly. The other declaration (db/schema/grievance-workflow-schema.ts, 19 cols) had a phantom `version` column that does not physically exist and has been converted to a re-export of the canonical declaration (PR #752 review round 3). Round-5 correction: lib/workers/report-worker.ts and lib/workflow-automation-engine.ts have been removed from this table's evidence — verified via git grep that NEITHER file has any real (non-test) importer anywhere in app/, actions/, lib/, or services/ (lib/job-queue.ts's own doc comment confirms all of lib/workers/*.ts was orphaned by the 2026-02-19 migration to Django Celery workers, and lib/workflow-automation-engine.ts/lib/case-assignment-engine.ts only import each other with no external caller — same dead-module family as grievance_assignments/grievance_stages/grievance_workflows). Real, live evidence is app/api/claims/[id]/workflow/history/route.ts (getCurrentUser-gated, plain `db`/withRLSContext, TENANT_RUNTIME) and lib/services/case-timeline-service.ts (plain `db`, reached via lib/services/sla-calculator.ts and the services barrel, not via the dead workflow engine). Direct organization_id column makes this straightforwardly tenant-scoped. NOT YET protected by migration 0108 — actual RLS policy addition is bundled with the other already-classified-but-unprotected tables (claim_deadlines, deadline_reminders, grievance_case_access_assignments, grievance_documents) as a batch follow-up, consistent with this PR's sequencing (manifest convergence before further 0108 changes).",
    supportingCapability: ["app/api/claims/[id]/workflow/history/route.ts","lib/services/case-timeline-service.ts","db/schema/domains/claims/workflows.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "grievance_workflows",
    classification: "LATENT_UNREACHABLE",
    reason: "Manually verified 2026-09-02: sole non-test reference is lib/workflow-automation-engine.ts (excluded from the TS project, zero real callers) — same dead module as grievance_approvals/grievance_stages.",
    supportingCapability: ["lib/workflow-automation-engine.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "pension_benefit_claims",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01 (round 6, Phase-3A priority tranche): direct NOT NULL organization_id column, reachable via live HTTP route(s) app/api/pension/benefit-claims/route.ts. org-scoped pension benefit claim submission endpoint; SELECT+INSERT confirmed. Minimum runtime privilege set from confirmed DML verbs (crudRoutes handler destructuring and/or direct .insert/.update/.delete/.select call-site evidence), not defaulted to FULL_DML.",
    supportingCapability: ["app/api/pension/benefit-claims/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "settlements",
    classification: "NEEDS_REVIEW",
    reason: "10 non-test reference(s) to 'settlements' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/[locale]/(marketing)/features/analytics/page.tsx","app/[locale]/dashboard/customer-success/page.tsx","app/[locale]/dashboard/sector-analytics/page.tsx","app/[locale]/dashboard/support/page.tsx","app/api/finance/summary/route.ts","lib/queries/platform-stats.ts","lib/services/cba-intelligence/adapters/esdc-adapter.ts","lib/services/cba-intelligence/adapters/provincial-board-adapter.ts","lib/services/cba-intelligence/adapters/union-bargaining-adapter.ts","lib/services/cba-intelligence/seed-sources.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "signature_workflows",
    classification: "NEEDS_REVIEW",
    reason: "6 non-test reference(s) to 'signatureWorkflows' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/services/signature-workflow-service.ts","services/financial-service/drizzle/relations.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts","services/pki/signature-service.ts","services/pki/workflow-engine.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "union_representation_votes",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'unionRepresentationVotes' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "wcb_claims",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01 (round 6, Phase-3A priority tranche): direct NOT NULL organization_id column, reachable via live HTTP route(s) app/api/wcb/claims/route.ts, app/api/wcb/claims/[id]/route.ts. org-scoped WCB claim CRUD routes; crudRoutes destructures GET+POST on the collection route and GET+PATCH+DELETE on the item route. Minimum runtime privilege set from confirmed DML verbs (crudRoutes handler destructuring and/or direct .insert/.update/.delete/.select call-site evidence), not defaulted to FULL_DML.",
    supportingCapability: ["app/api/wcb/claims/route.ts","app/api/wcb/claims/[id]/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "workflow_definitions",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'workflowDefinitions' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "workflow_executions",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'workflowExecutions' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "arbitration_decisions",
    classification: "NEEDS_REVIEW",
    reason: "11 non-test reference(s) to 'arbitrationDecisions' found (round-7 scope-expansion scan). At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/arbitration/precedents/[id]/citations/route.ts","app/api/arbitration/precedents/[id]/documents/route.ts","app/api/arbitration/precedents/[id]/route.ts","app/api/arbitration/precedents/route.ts","app/api/arbitration/precedents/search/route.ts","lib/services/ai/precedent-matching-service.ts","lib/services/ai/vector-search-service.ts","lib/services/precedent-service.ts","services/financial-service/drizzle/relations.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "arbitration_precedents",
    classification: "NEEDS_REVIEW",
    reason: "6 non-test reference(s) to 'arbitrationPrecedents' found (round-7 scope-expansion scan). At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/ai/semantic-search/route.ts","app/api/precedents/[id]/route.ts","lib/clc/data-products.ts","services/financial-service/drizzle/relations.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "bargaining_proposals",
    classification: "NEEDS_REVIEW",
    reason: "3 non-test reference(s) to 'bargainingProposals' found (round-7 scope-expansion scan). At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/bargaining/proposals/[id]/route.ts","app/api/bargaining/proposals/route.ts","lib/services/negotiations-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "bargaining_team_members",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'bargainingTeamMembers' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/services/negotiations-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "cba_contacts",
    classification: "NEEDS_REVIEW",
    reason: "3 non-test reference(s) to 'cbaContacts' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["services/financial-service/drizzle/relations.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "cba_footnotes",
    classification: "NEEDS_REVIEW",
    reason: "3 non-test reference(s) to 'cbaFootnotes' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["services/financial-service/drizzle/relations.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "cba_intel_agreements",
    classification: "NEEDS_REVIEW",
    reason: "3 non-test reference(s) to 'cbaIntelAgreements' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/services/cba-intelligence/benchmark-service.ts","lib/services/cba-intelligence/extraction-service.ts","lib/services/cba-intelligence/review-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "cba_intel_benchmark_snapshots",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'cbaIntelBenchmarkSnapshots' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/services/cba-intelligence/benchmark-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "cba_intel_clauses",
    classification: "NEEDS_REVIEW",
    reason: "3 non-test reference(s) to 'cbaIntelClauses' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/services/cba-intelligence/benchmark-service.ts","lib/services/cba-intelligence/extraction-service.ts","lib/services/cba-intelligence/review-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "cba_intel_documents",
    classification: "NEEDS_REVIEW",
    reason: "3 non-test reference(s) to 'cbaIntelDocuments' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/services/cba-intelligence/document-service.ts","lib/services/cba-intelligence/extraction-orchestrator.ts","lib/services/cba-intelligence/freshness-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "cba_intel_extraction_runs",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'cbaIntelExtractionRuns' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/services/cba-intelligence/extraction-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "cba_intel_findings",
    classification: "NEEDS_REVIEW",
    reason: "2 non-test reference(s) to 'cbaIntelFindings' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/services/cba-intelligence/extraction-service.ts","lib/services/cba-intelligence/review-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "cba_intel_freshness_log",
    classification: "NEEDS_REVIEW",
    reason: "2 non-test reference(s) to 'cbaIntelFreshnessLog' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/services/cba-intelligence/freshness-service.ts","lib/services/cba-intelligence/ingestion-scheduler.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "cba_intel_ingestion_jobs",
    classification: "NEEDS_REVIEW",
    reason: "2 non-test reference(s) to 'cbaIntelIngestionJobs' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/services/cba-intelligence/ingestion-scheduler.ts","lib/services/cba-intelligence/ingestion-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "cba_intel_review_decisions",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'cbaIntelReviewDecisions' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/services/cba-intelligence/review-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "cba_intel_sources",
    classification: "NEEDS_REVIEW",
    reason: "4 non-test reference(s) to 'cbaIntelSources' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/services/cba-intelligence/freshness-service.ts","lib/services/cba-intelligence/ingestion-scheduler.ts","lib/services/cba-intelligence/seed-sources.ts","lib/services/cba-intelligence/source-registry-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "cba_intel_wage_adjustments",
    classification: "NEEDS_REVIEW",
    reason: "3 non-test reference(s) to 'cbaIntelWageAdjustments' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/services/cba-intelligence/benchmark-service.ts","lib/services/cba-intelligence/extraction-service.ts","lib/services/cba-intelligence/review-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "cba_version_history",
    classification: "NEEDS_REVIEW",
    reason: "3 non-test reference(s) to 'cbaVersionHistory' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["services/financial-service/drizzle/relations.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "claim_updates",
    classification: "NEEDS_REVIEW",
    reason: "18 non-test reference(s) to 'claimUpdates' found (round-7 scope-expansion scan). At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/cases/[caseId]/assign/route.ts","app/api/cases/[caseId]/export/route.ts","app/api/cases/[caseId]/notes/route.ts","app/api/cases/[caseId]/timeline/route.ts","app/api/cases/[caseId]/transition/route.ts","app/api/claims/[id]/evidence/route.ts","app/api/metrics/operational/route.ts","app/api/notifications/preferences/route.ts","app/api/workflow/transition/route.ts","lib/ai/template-engine.ts","lib/gdpr/consent-manager.ts","lib/services/case-timeline-service.ts","lib/services/claims-service.ts","lib/workflow-automation-engine.ts","lib/workflow-engine.ts","services/financial-service/drizzle/relations.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "clc_bargaining_trends",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'clcBargainingTrends' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/services/external-data/clc-partnership-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "deadline_reminder_executions",
    classification: "LATENT_UNREACHABLE",
    reason: "Round-7 scope-expansion scan: zero references to the 'deadlineReminderExecutions' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files via a combined ripgrep pass across app/, actions/, lib/, services/. No known application code path queries this table today. NOT yet individually checked for raw-SQL (non-Drizzle-symbol) references to the physical table name — see the raw-SQL LATENT fixture test for why that check matters before this can be treated as final.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "fee_settlement_batches",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'feeSettlementBatches' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["services/platform-economics/transaction-fee-engine.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "grievance_events",
    classification: "NEEDS_REVIEW",
    reason: "11 non-test reference(s) to 'grievanceEvents' found (round-7 scope-expansion scan). At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/cases/[caseId]/escalate/route.ts","app/api/grievances/[id]/assign/route.ts","app/api/grievances/[id]/convert/route.ts","app/api/grievances/[id]/documents/route.ts","app/api/grievances/[id]/priority-override/route.ts","app/api/grievances/[id]/route.ts","app/api/grievances/[id]/status/route.ts","app/api/grievances/import/route.ts","app/api/grievances/route.ts","app/api/search/universal/route.ts","lib/cognition/ue-adapter.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "grievance_responses",
    classification: "LATENT_UNREACHABLE",
    reason: "Round-7 scope-expansion scan: zero references to the 'grievanceResponses' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files via a combined ripgrep pass across app/, actions/, lib/, services/. No known application code path queries this table today. NOT yet individually checked for raw-SQL (non-Drizzle-symbol) references to the physical table name — see the raw-SQL LATENT fixture test for why that check matters before this can be treated as final.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "grievance_timeline",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'grievanceTimeline' found (round-7 scope-expansion scan). At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/cases/[caseId]/timeline/route.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
]
