/**
 * db/rls-storage-authority/communications-notifications.ts
 *
 * PR #752 round 9: extracted from the single-file
 * db/rls-storage-authority-manifest.ts (which exceeded the repository's
 * 8000-line hard cap at 8009 lines — see
 * tooling/contract-tests/file-size-enforcement.test.ts) into semantic
 * domain modules. This module owns: Messages, notifications, communications, campaigns.
 *
 * Domain boundaries were assigned mechanically by table-name keyword
 * matching against the entry's `table` field (see the one-time migration
 * script referenced in the round-9 commit message) — every entry's DATA
 * (classification, reason, privileges, authority) is unchanged from the
 * pre-split manifest; only its physical file location changed. Do not
 * hand-edit an entry's domain placement without also checking
 * db/__tests__/rls-storage-authority-registry-composition.test.ts, which
 * proves the composed registry is unaffected by which module an entry
 * lives in.
 *
 * Add NEW entries to whichever domain module most closely matches the
 * table's real subject matter; when genuinely ambiguous, prefer
 * reference-latent.ts (the catch-all) over forcing a bad fit elsewhere.
 */
import type { StorageAuthorityEntry } from './types';

export const communicationsNotificationsEntries: StorageAuthorityEntry[] = [
  {
    table: "campaigns",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01 against LIVE staging DB: 27 columns, organization_id present, matching db/schema/domains/communications/campaigns.ts. Heavily reachable (40+ real references across the communications dashboard, API routes, and webhooks), all via the canonical declaration. Round 4 (2026-09-01): re-investigated the previously-disclosed 'broken worker' defect against lib/workers/message-queue-processor.ts, which imported the stale db/schema/phase-4-messaging-schema.ts declaration. Confirmed via git grep for the module path AND every exported symbol name (processMessageQueue, processCampaignMessages, getQueueStatus) across app/, actions/, lib/, services/ that this worker had ZERO production callers - only its own test file imported it. The send-side capability is officially NOT_IMPLEMENTED (app/api/cron/process-messages/route.ts throws ApiError.notImplemented() per Wave 0 finding F-01, docs/union-eyes/reality-remediation/04_FINDINGS_AND_DISPOSITIONS.md) and never invoked this worker. Disposition: deleted the worker, its test, and the now-fully-orphaned phase-4-messaging-schema.ts (verified zero other importers of any of its 3 exports) rather than canonicalizing dead code. No live defect existed - the previous 'redesign required' framing was based on treating 'imports the stale schema' as proof of a real consumer without checking whether the importing module itself was ever invoked.",
    supportingCapability: ["app/[locale]/dashboard/communications/page.tsx","app/api/communications/campaigns/route.ts","app/api/communications/track/click/route.ts","app/api/communications/track/open/[campaignId]/[recipientId]/route.ts","app/api/communications/unsubscribe/[recipientId]/route.ts","app/api/communications/webhooks/resend/route.ts","db/schema/domains/communications/campaigns.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: ["SELECT","UPDATE"],
    invocationAuthority: "MIXED",
    dbExecutionPrincipal: "MIXED",
    reviewPriority: "HIGH",
  },
  {
    table: "chat_sessions",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CLOSED round 45 (RESOLVED_DEPENDENCY_FRONTIER_ROOT, DIRECT_ORG_TENANT_ROOT archetype, fanout 5 — highest-ranked candidate closed this round): organization_id and user_id are both NOT NULL (db/schema/domains/ml/chatbot.ts). SECURITY DEFECT FOUND AND FIXED this round: lib/ai/chatbot-service.ts's ChatSessionManager had zero ownership check on getSession(sessionId), exploitable via two real routes — app/api/chatbot/messages/route.ts's POST (sendMessage) let any authenticated user inject messages into ANY other user's/organization's session and receive AI responses generated using that org's RAG context, and app/api/chatbot/sessions/[sessionId]/messages/route.ts's GET had NO auth block at all and returned any session's full message history. Fixed: sendMessage()/getMessages() now verify session.userId === caller.userId && session.organizationId === caller.organizationId before any read/write; the messages route gained an auth block; both callers now pass organizationId. lib/ai/__tests__/chatbot-service.test.ts extended with adversarial cross-user/cross-org tests (20/20 passing). template-engine.ts's second chatSessions-adjacent AttentionMechanismEngine/UnionEyesAIController classes and the archiveSession/updateSessionTitle/deleteSession service methods have zero reachable callers (UI buttons hit non-existent routes) and remain dead in practice — not fixed further as out of scope for a dead path. No Django model exists for chat_sessions (ai_core.ChatSessions maps to it but is now contained, see below).",
    supportingCapability: ["lib/ai/chatbot-service.ts","app/api/chatbot/messages/route.ts","app/api/chatbot/sessions/route.ts","app/api/chatbot/sessions/[sessionId]/messages/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "chatbot_analytics",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'chatbotAnalytics' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "chatbot_suggestions",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'chatbotSuggestions' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "communication_analytics",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'communicationAnalytics' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "communication_channels",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'communicationChannels' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "communication_preferences",
    classification: "TENANT_RLS_REQUIRED",
    reason: "3 conflicting declarations exist for physical table 'communication_preferences' (communication-analytics-schema.ts, domains/communications/analytics.ts, domains/communications/campaigns.ts — all 17-18 cols), but the live runtime evidence is consistent: app/api/communications/unsubscribe/[recipientId]/route.ts resolves the org from the campaign, then selects/updates communicationPreferences by (organization_id, user_id), and app/api/members/[id]/preferences/route.ts exposes the same table as org-scoped CRUD. This is a tenant-scoped membership preference table and must sit behind the same org-isolation policy as campaigns/message_log rather than a broad blanket runtime grant.",
    supportingCapability: ["app/api/communications/unsubscribe/[recipientId]/route.ts","app/api/members/[id]/preferences/route.ts","db/schema/domains/communications/campaigns.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: ["SELECT","INSERT","UPDATE"],
    invocationAuthority: "MIXED",
    dbExecutionPrincipal: "MIXED",
    reviewPriority: "HIGH",
  },
  {
    table: "communication_preferences_phase4",
    classification: "CONTAINED_NO_AUTHORITY",
    reason: "CLOSED round 47 (COMMUNICATIONS_CONSENT_USER_SUBJECT_AUTHORITY cohort): re-verified the round-8 finding with a fresh git grep for 'communicationPreferencesPhase4'/'communication_preferences_phase4' across the whole TS tree — zero hits anywhere outside this manifest file itself. No canonical Drizzle declaration exists for this physical table at all (its prior TS-side mirror, db/schema/phase-4-messaging-schema.ts's communicationPreferences export, was deleted in an earlier round as confirmed dead code — see the sibling 'communication_preferences' entry). The table's ONLY reachable surface is Django's CommunicationPreferencesPhase4ViewSet (backend/notifications/models.py, db_table='communication_preferences_phase4'), which was router-registered with queryset=Model.objects.all() + IsAuthenticated-only and no organization/user filter of any kind — contained via the existing notifications-app DenyAllPermission. Satisfies CONTAINED_NO_AUTHORITY: reachable-but-denied Django, no canonical TS declaration, no legitimate consumer.",
    supportingCapability: ["backend/notifications/views.py"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
    scopeDisposition: "DECLARATION_STALE_OR_NONCANONICAL",
  },
  {
    table: "consent_records",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified via real runtime usage: app/api/consent/route.ts exposes consentRecords via crudRoutes({ orgScoped: true, readRole: 'member', writeRole: 'steward' }) — GET/POST only, no PUT/PATCH/DELETE handlers are wired (crud-factory only emits the handlers destructured by the route). app/api/communications/unsubscribe/[recipientId]/route.ts inserts consentRecords with the resolved organization_id/user_id and a consent_type of email_marketing while revoking the subscription. No UPDATE or DELETE against this table exists anywhere in production code (git grep confirmed) — the table's own doc comment ('Immutable audit log of all consent changes (CASL/GDPR requirement)') and its column set (no updatedAt) confirm this is an append-only ledger by design, not an oversight. Reads are org-scoped, not user-scoped: the route sets no crud-factory ownerColumn, so any authenticated org member (readRole 'member') can list the org's full consent history — that is the actual implemented product authority (compliance officers/stewards need to see the org's consent posture), not an accidental broad grant, so USER_RLS_REQUIRED would under-scope real reads. TENANT_RLS_REQUIRED via the native organization_id column is correct; requiredRuntimePrivilege is SELECT_INSERT, not FULL_DML.",
    supportingCapability: ["app/api/consent/route.ts","app/api/communications/unsubscribe/[recipientId]/route.ts","db/schema/domains/communications/campaigns.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: ["INSERT"],
    invocationAuthority: "MIXED",
    dbExecutionPrincipal: "MIXED",
    reviewPriority: "HIGH",
  },
  {
    table: "cookie_consents",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CLOSED round 47 (COMMUNICATIONS_CONSENT_USER_SUBJECT_AUTHORITY cohort, ANONYMOUS_SUBJECT_WITHIN_TENANT variant): organization_id NOT NULL, user_id NULLABLE (db/schema/domains/compliance/gdpr.ts — comment explicitly documents intent: 'Optional - can track anonymous users'). The real ownership key for anonymous rows is NOT user_id but the browser-generated consent_id (unique constraint), matching doctrine's guidance to find the actual subject key rather than forcing a user-only model. Sole real consumer: app/api/gdpr/cookie-consent/route.ts, explicitly documented as 'public — cookie consent must work without auth' — POST/GET accept an unauthenticated caller by design (there is no session to derive organizationId from before a cookie banner has even been accepted), so client-supplied organizationId here is an intentional, legitimate anonymous/pre-login pattern, not a trust violation. CookieConsentManager.saveCookieConsent()/getCookieConsent() (lib/gdpr/consent-manager.ts) scope every read/write by consent_id (a client-generated v4 UUID, 128 bits of entropy — not realistically guessable). MINOR FINDING, NOT FIXED (low-sensitivity, out of bounded scope): saveCookieConsent's UPDATE path unconditionally overwrites organizationId from the request body on every save, so a reused/shared consentId across differently-configured sites could relabel which org a preference-boolean row belongs to; not fixed because the stored data (essential/functional/analytics/marketing booleans, IP, user agent) carries no access-control consequence — reassigning it does not grant authority over anything sensitive.",
    supportingCapability: ["app/api/gdpr/cookie-consent/route.ts","lib/gdpr/consent-manager.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "data_aggregation_consent",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CLOSED (2026-09-04, round 40 SIMPLE_TENANT:org:NORMAL cohort): direct NOT NULL organization_id table. Live paths are server pages app/[locale]/dashboard/settings/data-sharing/page.tsx and app/[locale]/dashboard/movement-insights/page.tsx, both after requireUser(), using the authenticated user's organizationId and filtering dataAggregationConsent by organizationId. The apparent mutation helpers in lib/movement-insights/consent-manager.ts are library-only today: ConsentForm/RevokeConsentButton post to /api/consent, whose route operates on consentRecords, not dataAggregationConsent. DataAggregationConsentViewSet is separately router-registered but now unconditionally denied via Round40DenyAllPermission because it has no legitimate Django consumer. Minimum live runtime DML is SELECT only, no withSystemContext.",
    supportingCapability: ["app/[locale]/dashboard/movement-insights/page.tsx","app/[locale]/dashboard/settings/data-sharing/page.tsx","lib/movement-insights/consent-manager.ts"],
    requiredRuntimePrivileges: ["SELECT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "donation_campaigns",
    classification: "NEEDS_REVIEW",
    reason: "3 non-test reference(s) to 'donationCampaigns' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/cope/campaigns/route.ts","app/api/cope/canvassing/route.ts","app/api/cope/officials/route.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "employer_communications",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'employerCommunications' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/employers/communications/route.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "external_communication_channels",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CLOSED (2026-09-04, round 40 integration control plane tranche): direct org-scoped integration table reached only through app/api/integrations/framework/**, where withApi derives the organizationId from the authenticated caller, loads integration_configs by id+organizationId, and passes a trusted TENANT_RUNTIME execution context into SyncEngine. The only approved writers are the registered Slack/Teams communication adapters, which upsert channels under orgId/provider/externalId and select org-scoped channels while syncing messages/files/members. No generic external CRUD route or arbitrary table-sync route was created. The generated ExternalCommunicationChannelsViewSet in backend/core/views.py remains router-registered but unconditionally denied via DenyAllPermission.",
    supportingCapability: ["app/api/integrations/framework/route.ts","app/api/integrations/framework/[id]/sync/route.ts","lib/integrations/control-plane.ts","lib/integrations/sync-engine.ts","lib/integrations/adapters/communication/slack-adapter.ts","lib/integrations/adapters/communication/teams-adapter.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "external_communication_messages",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CORRECTED round 40 (structural correction): reachable via the approved Slack and Microsoft Teams adapters (lib/integrations/adapters/communication/{slack,teams}-adapter.ts), both control-plane-approved (lib/integrations/provider-policy.ts) and invoked only through app/api/integrations/framework/[id]/sync/route.ts, which is withApi-authenticated and derives organizationId from the caller before SyncEngine executes. Matches the sibling external_communication_channels/external_communication_users classification (same adapters, same reachability path); this entry was left NEEDS_REVIEW inconsistently in the prior pass.",
    supportingCapability: ["app/api/integrations/framework/route.ts","app/api/integrations/framework/[id]/sync/route.ts","lib/integrations/control-plane.ts","lib/integrations/sync-engine.ts","lib/integrations/adapters/communication/slack-adapter.ts","lib/integrations/adapters/communication/teams-adapter.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "external_communication_users",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CLOSED (2026-09-04, round 40 integration control plane tranche): direct org-scoped integration table reached only through app/api/integrations/framework/**, where withApi derives organizationId from the authenticated caller and SyncEngine receives a trusted TENANT_RUNTIME context for the approved Slack/Teams adapters. Those adapters upsert external users/members under orgId/provider/externalId; no generic external-user CRUD route or arbitrary table-sync route was created. The generated ExternalCommunicationUsersViewSet in backend/core/views.py remains router-registered but unconditionally denied via DenyAllPermission.",
    supportingCapability: ["app/api/integrations/framework/route.ts","app/api/integrations/framework/[id]/sync/route.ts","lib/integrations/control-plane.ts","lib/integrations/sync-engine.ts","lib/integrations/adapters/communication/slack-adapter.ts","lib/integrations/adapters/communication/teams-adapter.ts"],
    requiredRuntimePrivileges: ["INSERT","UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "in_app_notifications",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified 2026-09-02: direct NOT NULL organization_id column (db/schema/domains/communications/notifications.ts). Reachable via live HTTP routes app/api/notifications/route.ts, app/api/notifications/[id]/route.ts, app/api/notifications/count/route.ts, app/api/notifications/mark-all-read/route.ts, and the support-ticket notification surface (app/api/support/tickets/**).",
    supportingCapability: ["app/api/notifications/route.ts","app/api/notifications/[id]/route.ts","app/api/notifications/count/route.ts","app/api/notifications/mark-all-read/route.ts","app/api/support/tickets/route.ts","lib/services/notification-service.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "message_log",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01 against LIVE staging DB: 24 columns, organization_id present, matching db/schema/domains/communications/campaigns.ts's messageLog export. Real consumers (webhook delivery tracking, open/click pixel tracking, unsubscribe flow) already use the canonical shape correctly. Round 4 (2026-09-01): same re-investigation as 'campaigns' — lib/workers/message-queue-processor.ts's stale db/schema/phase-4-messaging-schema.ts usage (channel/body/variables/scheduledAt/externalId/nextRetryAt columns that do NOT physically exist) had ZERO production callers and has been deleted along with its test and the now-fully-orphaned phase-4-messaging-schema.ts. See 'campaigns' entry for the full reasoning.",
    supportingCapability: ["app/api/communications/track/click/route.ts","app/api/communications/track/open/[campaignId]/[recipientId]/route.ts","app/api/communications/unsubscribe/[recipientId]/route.ts","app/api/communications/webhooks/resend/route.ts","db/schema/domains/communications/campaigns.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: ["SELECT","UPDATE"],
    invocationAuthority: "MIXED",
    dbExecutionPrincipal: "MIXED",
    reviewPriority: "HIGH",
  },
  {
    table: "mobile_notifications",
    classification: "LATENT_UNREACHABLE",
    reason: "Manually verified 2026-09-02: nullable organization_id, NOT NULL user_id (db/schema/mobile-devices-schema.ts) — would otherwise be a USER_RLS_REQUIRED candidate, but its sole non-test reference is lib/mobile/mobile-engine.ts, whose MobileNotificationService export has zero callers anywhere under app/, actions/, lib/, services/, scripts/ (verified by name-search). Distinct from the separately-reachable app/api/mobile/notifications/route.ts, which reads the \"notifications\" table, not this one.",
    supportingCapability: ["lib/mobile/mobile-engine.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "newsletter_campaigns",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CLOSED round 45 (RESOLVED_DEPENDENCY_FRONTIER_ROOT, DIRECT_ORG_TENANT_ROOT archetype): organization_id NOT NULL (db/schema/domains/communications/newsletters.ts). Zero insert/update path exists anywhere in the codebase for this table (confirmed via git grep for `insert(newsletterCampaigns)`/`.update(newsletterCampaigns)` — no matches); the sole real DML is the read in app/api/billing/batch-status/[jobId]/route.ts, which verifies `eq(newsletterCampaigns.id, campaignId)` AND `eq(newsletterCampaigns.organizationId, context.organizationId)` before use. Note: app/api/communications/campaigns/** routes use a DIFFERENT `campaigns` table (crudRoutes over db/schema's `campaigns` export), not this one — confirmed by import inspection to avoid the generator-artifact-misattribution failure mode. No dual-schema conflict (services/financial-service has no newsletterCampaigns declaration).",
    supportingCapability: ["app/api/billing/batch-status/[jobId]/route.ts"],
    requiredRuntimePrivileges: ["SELECT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "newsletter_distribution_lists",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CLOSED round 45 (RESOLVED_DEPENDENCY_FRONTIER_ROOT, DIRECT_ORG_TENANT_ROOT archetype, fanout 1): organization_id NOT NULL (db/schema/domains/communications/newsletters.ts). Real CRUD consumers: app/api/communications/distribution-lists/route.ts (GET/POST) and .../[id]/route.ts (GET/PATCH/DELETE), both crudRoutes({orgScoped: true}) — unlike the round-42 orgScoped:true footgun, this table HAS its own organization_id column so the option is not a silent no-op. app/[locale]/dashboard/communications/page.tsx also reads it, scoped via `eq(newsletterDistributionLists.organizationId, orgId)` where `orgId = (await requireUser()).organizationId` (server-derived, not client-supplied). No dual-schema conflict.",
    supportingCapability: ["app/[locale]/dashboard/communications/page.tsx","app/api/communications/distribution-lists/[id]/route.ts","app/api/communications/distribution-lists/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "notification_bounces",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'notificationBounces' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "notification_delivery_log",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified 2026-09-02, resolved 2026-09-02 (round 5): direct NOT NULL organization_id column (db/schema/domains/communications/notifications.ts). MIXED — lib/services/notification-service.ts's notificationDeliveryLog INSERT executes via the plain `db` import; it is invoked both from the TENANT_USER path (app/api/dues/arrears/[id]/reminder/route.ts, steward-gated) and lib/jobs/dues-reminder-scheduler.ts (admin-invoked via app/api/admin/dues/send-reminders/route.ts, no withSystemContext of its own — stays TENANT_RUNTIME), and from lib/jobs/billing-scheduler.ts's SYSTEM_SCHEDULE path, which (per PR #752 round 4) wraps its entire cross-org operation in withSystemContext — the ALS-based `db` Proxy routes notification-service.ts's same INSERT call to SYSTEM_RUNTIME when called from inside that boundary. requiredSystemPrivileges reflects only the INSERT this table receives.",
    supportingCapability: ["lib/services/notification-service.ts","app/api/dues/arrears/[id]/reminder/route.ts","lib/jobs/dues-reminder-scheduler.ts","lib/jobs/billing-scheduler.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: ["INSERT"],
    invocationAuthority: "MIXED",
    dbExecutionPrincipal: "MIXED",
    reviewPriority: "HIGH",
  },
  {
    table: "notification_history",
    classification: "LATENT_UNREACHABLE",
    reason: "RECLASSIFIED 2026-09-02 (round 5, from TENANT_RLS_REQUIRED/MIXED): re-verified against the actual imports of lib/services/notification-service.ts — it imports only `notificationQueue`, `notificationDeliveryLog`, `notificationTemplates` from db/schema/domains/communications; `notificationHistory` appears ONLY in a doc comment ('- notificationHistory: Audit log for all notifications'), never as an actual query. Its other cited evidence, lib/workers/{cleanup,email,notification,sms}-worker.ts, has ZERO real (non-test) importers anywhere in app/, actions/, lib/, or services/ — confirmed orphaned by the 2026-02-19 Django Celery migration (see lib/job-queue.ts's own doc comment; same dead-module family as user_sessions/grievance_transitions' prior citations). No other non-test reference to the 'notificationHistory' Drizzle export exists. Resolves the prior entry's own flagged follow-up ('execution authority for the worker path not yet independently confirmed').",
    supportingCapability: ["db/schema/domains/communications/notifications.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "notification_log",
    classification: "LATENT_UNREACHABLE",
    reason: "Manually verified 2026-09-02: direct NOT NULL organization_id column (db/schema/domains/infrastructure/clc-per-capita.ts), but its sole non-test reference is services/clc/remittance-notifications.ts, whose exports (sendOverdueAlert, sendMonthlyReminder, processOverdueRemittances, etc.) have zero callers anywhere under app/, actions/, lib/, services/, scripts/ (verified by name-search). No live route, action, or cron entrypoint reaches this table today.",
    supportingCapability: ["services/clc/remittance-notifications.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "notification_queue",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified 2026-09-02, resolved 2026-09-02 (round 5): direct NOT NULL organization_id column (db/schema/domains/communications/notifications.ts). MIXED — lib/job-queue.ts is now a thin HTTP client to Django Celery (per its own doc comment, migrated 2026-02-19) and does not itself touch this table; the real DB access is lib/services/notification-service.ts's notificationQueue SELECT/INSERT/UPDATE via the plain `db` import, invoked both from the TENANT_USER path (app/api/dues/arrears/[id]/reminder/route.ts, app/api/metrics/operational/route.ts, app/api/union-eyes/queue-status/route.ts) and from lib/jobs/billing-scheduler.ts's SYSTEM_SCHEDULE path, which wraps its entire operation in withSystemContext (PR #752 round 4) — the same notification-service.ts call routes to SYSTEM_RUNTIME when invoked from inside that boundary.",
    supportingCapability: ["lib/services/notification-service.ts","app/api/dues/arrears/[id]/reminder/route.ts","app/api/metrics/operational/route.ts","app/api/union-eyes/queue-status/route.ts","lib/jobs/billing-scheduler.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: ["SELECT","INSERT","UPDATE"],
    invocationAuthority: "MIXED",
    dbExecutionPrincipal: "MIXED",
    reviewPriority: "HIGH",
  },
  {
    table: "notification_tracking",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified 2026-09-02, resolved 2026-09-02 (round 5, corrected): direct NOT NULL organization_id column (db/schema/domains/communications/notifications.ts). Re-verified lib/services/notification-service.ts's actual imports — it imports notificationQueue/notificationDeliveryLog/notificationTemplates only; `notificationTracking` is mentioned solely in a doc comment, never queried there. The ONLY real writer/reader is services/observability/realtime-alerting-service.ts (plain `db`, no withSystemContext), called from BOTH app/api/alerts/realtime/route.ts (withApi minRole member — TENANT_USER) AND app/api/cron/observability-alerts/route.ts (auth: { cron: true } — SYSTEM_SCHEDULE). invocationAuthority is genuinely MIXED, but because realtime-alerting-service.ts never escalates to withSystemContext on either path, dbExecutionPrincipal is TENANT_RUNTIME only (not MIXED) — flagged as a separate, out-of-scope latent gap: the cron-invoked sweep runs cross-org without a tenant session, through the ordinary tenant-RLS-gated connection.",
    supportingCapability: ["services/observability/realtime-alerting-service.ts","app/api/alerts/realtime/route.ts","app/api/cron/observability-alerts/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "MIXED",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "notifications",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified 2026-09-02: direct NOT NULL organization_id + user_id columns (db/schema/domains/communications/notifications.ts). Reachable via multiple live HTTP routes (app/api/notifications/route.ts, app/api/notifications/[id]/route.ts, app/api/notifications/count/route.ts, app/api/notifications/mark-all-read/route.ts, app/api/notifications/preferences/route.ts, app/api/notifications/device/route.ts, app/api/notifications/test/route.ts, app/api/mobile/notifications/route.ts) and cron routes (app/api/cron/education-reminders, overdue-notifications, process-notifications, observability-alerts). Needs the same ue_create_direct_org_rls_policy treatment as the 0108 protected set.",
    supportingCapability: ["app/api/notifications/route.ts","app/api/notifications/[id]/route.ts","app/api/notifications/count/route.ts","app/api/notifications/mark-all-read/route.ts","app/api/notifications/preferences/route.ts","app/api/notifications/device/route.ts","app/api/notifications/test/route.ts","app/api/mobile/notifications/route.ts","app/api/cron/education-reminders/route.ts","app/api/cron/overdue-notifications/route.ts","app/api/cron/process-notifications/route.ts","lib/services/notification-service.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "organizing_campaign_milestones",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'organizingCampaignMilestones' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "organizing_campaigns",
    classification: "NEEDS_REVIEW",
    reason: "18 non-test reference(s) to 'organizingCampaigns' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/organizing/assignments/[id]/route.ts","app/api/organizing/assignments/route.ts","app/api/organizing/campaigns/route.ts","app/api/organizing/card-check/route.ts","app/api/organizing/committee/route.ts","app/api/organizing/forms/generate/route.ts","app/api/organizing/labour-board/route.ts","app/api/organizing/nlrb-filings/route.ts","app/api/organizing/notes/[id]/route.ts","app/api/organizing/notes/route.ts","app/api/organizing/sequences/[id]/enroll/route.ts","app/api/organizing/sequences/[id]/route.ts","app/api/organizing/sequences/route.ts","app/api/organizing/support-percentage/route.ts","app/api/organizing/workplace-mapping/route.ts","services/financial-service/drizzle/relations.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "push_notifications",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified 2026-09-02: direct NOT NULL organization_id column (db/schema/domains/communications/push-notifications.ts). Reachable via live HTTP routes app/api/mobile/push/subscribe/route.ts and app/api/mobile/push/unsubscribe/route.ts.",
    supportingCapability: ["app/api/mobile/push/subscribe/route.ts","app/api/mobile/push/unsubscribe/route.ts","services/fcm-service.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "sms_campaigns",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CLOSED round 47 (COMMUNICATIONS_CONSENT_USER_SUBJECT_AUTHORITY cohort, DIRECT_ORG_TENANT_ROOT archetype): organization_id NOT NULL (db/schema/domains/communications/sms.ts). Real reachable paths: app/api/communications/sms/campaigns/route.ts (crudRoutes, orgScoped:true, GET/POST) and app/[locale]/dashboard/communications/page.tsx (eq(smsCampaigns.organizationId, orgId), orgId from requireUser() — trusted, server-derived). templateId/createdBy are attribution/FK references, not authority (doctrine: creator attribution != tenant authority); no route validates templateId belongs to the same org before insert — a minor cross-org FK-reference integrity nitpick, not a data-access leak (GET never joins/exposes the referenced template's content, only its own UUID). services/twilio-sms-service.ts's send/webhook/opt-out machinery (sendSms, sendBulkSms, handleTwilioWebhook, handleInboundSms, handleOptOut) is CONFIRMED DEAD CODE for this table — zero callers anywhere outside its own file and its own test; no app/api/**/twilio route exists at all (its own sendSms() references a statusCallback URL, /api/webhooks/twilio, that is not a real route in this repo). Only updateCampaignStatistics() (also dead, called only from the dead handleTwilioWebhook) would UPDATE this table — the live route only supports SELECT/INSERT.",
    supportingCapability: ["app/[locale]/dashboard/communications/page.tsx","app/api/communications/sms/campaigns/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "sms_conversations",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CLOSED round 47 (COMMUNICATIONS_CONSENT_USER_SUBJECT_AUTHORITY cohort, DIRECT_ORG_TENANT_ROOT archetype): organization_id NOT NULL (db/schema/domains/communications/sms.ts). Real reachable path: app/api/communications/sms/conversations/route.ts (crudRoutes, orgScoped:true, GET/POST) — an ordinary org-scoped CRUD surface, independent of any phone-number-matching logic (no unsafe global phone lookup here). services/twilio-sms-service.ts's handleInboundSms() (the function that would otherwise write inbound conversation rows keyed by phone number) is CONFIRMED DEAD CODE — zero callers anywhere outside its own file/test, and no app/api/**/twilio inbound webhook route exists in this repo at all. Its internal resolveOrganizationIdFromPhoneNumber() helper (matching an org's configured Twilio number against the inbound TO number, a safe org+account-scoped lookup shape) is therefore also unreachable — documented for when/if the webhook route is built, since that would be the correct pattern to reuse.",
    supportingCapability: ["app/api/communications/sms/conversations/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "sms_messages",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01 (round 6, Phase-3A priority tranche): direct NOT NULL organization_id column, reachable via live HTTP route(s) app/api/communications/sms/route.ts. org-scoped SMS message CRUD route; crudRoutes GET+POST plus confirmed UPDATE+DELETE (delivery-status update, message removal). Minimum runtime privilege set from confirmed DML verbs (crudRoutes handler destructuring and/or direct .insert/.update/.delete/.select call-site evidence), not defaulted to FULL_DML.",
    supportingCapability: ["app/api/communications/sms/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "sms_opt_outs",
    classification: "CONTAINED_NO_AUTHORITY",
    reason: "CLOSED round 47 (COMMUNICATIONS_CONSENT_USER_SUBJECT_AUTHORITY cohort): organization_id + phone_number columns would form a safe scoping key IF reachable (matching doctrine's suggested org+phone suppression-scope shape), but services/twilio-sms-service.ts's isPhoneOptedOut()/handleOptOut() — the table's only reader and writer — have ZERO callers anywhere outside their own file and its own test file. No app/api/**/route.ts, action, cron, or webhook reaches this table: sendSms()/sendBulkSms() (which call isPhoneOptedOut) are themselves dead code, and no Twilio inbound/STOP-reply webhook route exists in this repo to invoke handleOptOut(). Django's SmsOptOutsViewSet IS router-registered (backend/notifications) and was IsAuthenticated-only with no scoping — contained via DenyAllPermission this round. Satisfies CONTAINED_NO_AUTHORITY: reachable-but-denied Django, dead TS, no legitimate consumer. COMPLIANCE FINDING (product gap, not an authority defect — out of this round's bounded scope): handleInboundSms()'s STOP/UNSUBSCRIBE detection has a commented-out call to handleOptOut (`// await handleOptOut(orgId, From);`), meaning even if the dead inbound-webhook path were wired up, automatic TCPA/CASL suppression-on-STOP is not actually connected. Flagged for product follow-up; not fixed here since wiring a real Twilio inbound webhook route is a feature build, not a bounded authority fix.",
    supportingCapability: ["services/twilio-sms-service.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "sms_rate_limits",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'smsRateLimits' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "social_campaigns",
    classification: "NEEDS_REVIEW",
    reason: "2 non-test reference(s) to 'socialCampaigns' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/social-media/analytics/route.ts","app/api/social-media/campaigns/route.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "user_consents",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CLOSED round 47 (COMMUNICATIONS_CONSENT_USER_SUBJECT_AUTHORITY cohort, USER_SUBJECT_WITHIN_TENANT archetype): organization_id AND user_id both NOT NULL (db/schema/domains/compliance/gdpr.ts; db/schema/gdpr-compliance-schema.ts is an orphaned duplicate with zero importers, not investigated further). SECURITY DEFECT FOUND AND FIXED: app/api/members/[id]/consents/route.ts (crudRoutes, itemRoute:true) had orgScoped:true but NO subject scoping at all — any org member (readRole:'member') could GET any other member's consent record, and any steward (writeRole:'steward') could PATCH (or attempt DELETE) any other member's consent, i.e. exactly the 'admin forges/reads subject consent merely by administering the org' pattern this round's doctrine forbids. Also found crud-factory.ts's `ownerColumn` option was NEVER honoured on itemRoute (GET/PATCH/DELETE) handlers, only on the collection GET — a shared gap (fixed generically; verified zero other routes combine itemRoute+ownerColumn today, so this is a pure addition with no behavior change elsewhere). Fixed: route now sets ownerColumn:'userId' (restricts GET/PATCH to the record's own subject) and writeRole:'member' (ownership, not org role, is the real gate — matches lib/gdpr/consent-manager.ts's ConsentManager.withdrawConsent(userId, consentId) design intent, though that class itself has zero real callers and remains dead code). blockedPatchFields locks consentType/legalBasis/processingPurpose/consentVersion/consentText/ipAddress/userAgent/grantedAt/createdAt/userId/organizationId as immutable — only status/withdrawnAt may change via self-service PATCH, so a subject can withdraw but not rewrite their own consent history. DELETE removed entirely: it was setting status='archived', which is not a valid consent_status enum member (granted|denied|withdrawn|expired) — the handler could never have worked, and destroying a consent record would erase compliance provenance regardless. New adversarial test app/api/members/[id]/consents/__tests__/route.test.ts proves Org-A/Org-B and same-org-different-user isolation on both GET and PATCH, plus blockedPatchFields immutability (7/7 passing).",
    supportingCapability: ["app/api/members/[id]/consents/route.ts","lib/gdpr/consent-manager.ts"],
    requiredRuntimePrivileges: ["SELECT","UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "user_notification_preferences",
    classification: "NEEDS_REVIEW",
    reason: "ROUND 47 EXCEPTION (DUAL_SCHEMA archetype, ejected): services/financial-service/drizzle/schema.ts AND services/financial-service/src/db/schema.ts each declare their OWN pgTable(\"user_notification_preferences\", ...), with a genuine, actively-used consumer in that separate service — services/financial-service/src/services/notification-service.ts SELECTs/UPSERTs scoped by (tenantId, userId), not a stale/dead reference. This app's own db/schema/domains/communications/notifications.ts ALSO declares a same-named physical table independently. Per round 41-46 dual-schema doctrine, this cannot be resolved as a single authority entry without first determining which service/database genuinely owns the physical 'user_notification_preferences' table (or whether both apps unsafely share one physical table under two independently-evolving Drizzle declarations, which would be worse). SEPARATE FINDING (union-eyes side only, informational, not itself a fix trigger while DUAL_SCHEMA is unresolved): lib/workers/{email,notification,sms}-worker.ts (3 of the 10 cited references) are confirmed DEAD CODE — zero importers anywhere outside their own files, matching the exact dead-worker pattern round 46 established for lib/workers/notification-worker.ts (push_devices) and lib/workers/employer-execution/**. The real reachable union-eyes-side surfaces are app/api/messaging/preferences/route.ts, app/api/notifications/device/route.ts, app/api/notifications/preferences/route.ts, and lib/services/notification-service.ts — not independently re-verified for subject-scoping this round since the table's disposition is blocked on the dual-schema question first. Recommended next cohort: a dedicated cross-service review determining true ownership of user_notification_preferences before any authority classification can be assigned.",
    supportingCapability: ["app/api/messaging/preferences/route.ts","app/api/notifications/device/route.ts","app/api/notifications/preferences/route.ts","lib/services/notification-service.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts","services/financial-service/src/services/notification-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "band_council_consent",
    classification: "CONTAINED_NO_AUTHORITY",
    reason: "CLOSED round 51 (GLOBAL_REFERENCE_AND_SHARED_CONFIGURATION_SCOPE_AUTHORITY, no-org candidate universe): sole TS consumer(s) services/indigenous-data-service.ts, lib/services/indigenous-data-service.ts have zero production importers anywhere in app/, actions/, lib/, services/ outside their own test files (git-grep confirmed) — dead TS code, no legitimate consumer on the TypeScript side. The generated Django ViewSet(s) in backend/compliance/views.py exposed queryset=Model.objects.all() + IsAuthenticated-only with NO organization filter of any kind. Contained this round via DenyAllPermission in backend/compliance/views.py. Satisfies CONTAINED_NO_AUTHORITY: reachable-but-denied Django, dead TS, no legitimate consumer.",
    supportingCapability: ["services/indigenous-data-service.ts","lib/services/indigenous-data-service.ts","backend/compliance/views.py"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "chat_messages",
    classification: "PARENT_OWNED_RLS_REQUIRED",
    reason: "CLOSED round 45 (RESOLVED_DEPENDENCY_FRONTIER_ROOT cascade child of chat_sessions, 1-hop): no organization_id column; authority derived through session_id -> chat_sessions, which closed TENANT_RLS_REQUIRED this same round after its ownership-check IDOR was fixed. lib/ai/chatbot-service.ts's sendMessage()/getMessages() now verify the parent session's ownership (userId+organizationId) before any chatMessages read/insert; no update/delete path exists. lib/ai/template-engine.ts's reference is dead code (AttentionMechanismEngine/UnionEyesAIController have zero external callers). ai_safety_filters (a grandchild via chat_messages) is explicitly DEFERRED per the round's 1-hop cascade limit — not evaluated this round.",
    supportingCapability: ["lib/ai/chatbot-service.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "federation_campaigns",
    classification: "LATENT_UNREACHABLE",
    reason: "Round-7 scope-expansion scan: zero references to the 'federationCampaigns' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files via a combined ripgrep pass across app/, actions/, lib/, services/. No known application code path queries this table today. NOT yet individually checked for raw-SQL (non-Drizzle-symbol) references to the physical table name — see the raw-SQL LATENT fixture test for why that check matters before this can be treated as final.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "federation_communications",
    classification: "LATENT_UNREACHABLE",
    reason: "Round-7 scope-expansion scan: zero references to the 'federationCommunications' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files via a combined ripgrep pass across app/, actions/, lib/, services/. No known application code path queries this table today. NOT yet individually checked for raw-SQL (non-Drizzle-symbol) references to the physical table name — see the raw-SQL LATENT fixture test for why that check matters before this can be treated as final.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "newsletter_engagement",
    classification: "CONTAINED_NO_AUTHORITY",
    reason: "CLOSED round 47 (COMMUNICATIONS_CONSENT_USER_SUBJECT_AUTHORITY cohort): lib/engagement-scoring.ts (the sole non-test reference) has zero real callers anywhere — its entire exported API (calculateEngagementScore, calculateAllEngagementScores, getEngagementHistory, identifyReEngagementTargets, getTopEngagedMembers) is confirmed dead via git grep across app/, lib/, finding only its own test file. Django's NewsletterEngagementViewSet IS router-registered (backend/notifications) and was IsAuthenticated-only with no scoping — contained via DenyAllPermission this round. Satisfies CONTAINED_NO_AUTHORITY: reachable-but-denied Django, dead TS, no legitimate consumer. CROSS-PARENT CONSISTENCY DEFECT FOUND, NOT FIXED (dead TS code, no active exposure): calculateEngagementScore(profileId, organizationId, ...) takes an explicit organizationId parameter and correctly applies it to its smsMessages query, but its newsletterEngagement query filters ONLY by profileId + occurredAt — no organizationId predicate, and no join back through campaignId -> newsletterCampaigns.organizationId or recipientId -> newsletterRecipients -> newsletterCampaigns.organizationId to verify the engagement row's own org matches the caller's org. If this dead code were ever wired to a real route, a profile with newsletter engagement history under a DIFFERENT organization's campaigns would have that history silently aggregated into another org's engagement score — flagged for whoever revives this code to fix before shipping, per doctrine's cross-parent-consistency requirement (root(campaignId's parent) must equal root(recipientId's parent) must equal the authenticated organization).",
    supportingCapability: ["lib/engagement-scoring.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "newsletter_list_subscribers",
    classification: "NEEDS_REVIEW",
    reason: "RE-CONFIRMED round 54 (final non-voting parent-owned authority convergence \u2014 ARCHITECTURAL_REDESIGN blocker, carried forward unchanged from rounds 42/47): parent chain re-verified \u2014 list_id -> newsletterDistributionLists (CLOSED TENANT_RLS_REQUIRED round 45) and profile_id -> profiles.userId (global identity, not an authority root). The route-shape defect is STILL PRESENT and STILL not mechanically fixable this round: app/api/communications/distribution-lists/[id]/subscribers/route.ts's crud-factory itemRoute mode treats the URL's [id] segment as a SUBSCRIBER row id (eq(newsletterListSubscribers.id, id)), but the route folder places the DISTRIBUTION LIST's id in that same segment \u2014 GET/PATCH/DELETE can therefore never match a real subscriber row (fails closed \u2014 no cross-org data exposure results, confirmed safe-but-broken, not a live vulnerability). Fixing this requires a genuine product-level decision on the intended route shape (collection-list-by-listId vs item-by-subscriberId, which needs a second URL segment that does not exist today) \u2014 out of round-54's bounded-fix mandate per doctrine's ARCHITECTURAL_REDESIGN exception code (rule 54). Django NewsletterListSubscribersViewSet remains CONTAINED (DenyAllPermission, round 47). Recommended next cohort: resolve the route-shape product decision, then apply the same parent-verification pattern used for document_signers/contract_line_items this round.",
    supportingCapability: ["app/api/communications/distribution-lists/[id]/subscribers/route.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "newsletter_recipients",
    classification: "PARENT_OWNED_RLS_REQUIRED",
    reason: "CLOSED round 42 (PARENT_OWNED:parent:HIGH): no direct organization_id column; authority is derived through campaign_id -> newsletterCampaigns.organizationId (newsletterCampaigns has a direct NOT NULL organization_id, schema-clear even though its own full authority is not yet closed — narrow parent verification proven for this child per round-42 doctrine). Sole real reference app/api/billing/batch-status/[jobId]/route.ts loads the campaign first via and(eq(newsletterCampaigns.id, campaignId), eq(newsletterCampaigns.organizationId, context.organizationId)) — trusted from withRoleAuth — and only queries newsletterRecipients by that already-verified campaignId afterward. Read-only (SELECT); no insert/update/delete route exists. The second FK (profile_id -> profiles.userId) is not used for authority in this path, only as a recipient identity reference.",
    supportingCapability: ["app/api/billing/batch-status/[jobId]/route.ts"],
    requiredRuntimePrivileges: ["SELECT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "provincial_consent",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'provincialConsent' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["services/provincial-privacy-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "sms_campaign_recipients",
    classification: "CONTAINED_NO_AUTHORITY",
    reason: "CLOSED round 47 (COMMUNICATIONS_CONSENT_USER_SUBJECT_AUTHORITY cohort; also resolves the round-13 one-hop-cascade question from sms_campaigns since sms_campaigns' own real route never touches recipients at all): the sole non-test reference (lib/gdpr/consent-manager.ts's DataErasureService, a GDPR right-to-erasure class that deletes smsCampaignRecipients filtered by user_id during account erasure) has ZERO real callers anywhere — confirmed via git grep for 'DataErasureService.' across app/, actions/, lib/, services/, finding only the manager's own file and its own test. No campaign-recipients-specific route, action, cron, or webhook exists. Django's SmsCampaignRecipientsViewSet IS router-registered (backend/notifications) and was IsAuthenticated-only with no scoping — contained via DenyAllPermission this round. Satisfies CONTAINED_NO_AUTHORITY: reachable-but-denied Django, dead TS, no legitimate consumer.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "voting_notifications",
    classification: "CONTAINED_NO_AUTHORITY",
    reason: "CLOSED round 44 (RESOLVED_PARENT_ROOT candidate; parent voting_sessions is closed TENANT_RLS_REQUIRED, but the child itself has no real consumer): votingNotifications has zero real TS references anywhere in app/, actions/, lib/, services/ \u2014 only services/financial-service's own separate dual-schema declares it (a different deployable Node service, matching the round-41/42/43 dual-schema precedent). DEFECT FOUND AND FIXED THIS ROUND: VotingNotificationsViewSet (backend/unions/views.py) was router-registered with queryset=Model.objects.all() + IsAuthenticated-only and NO organization filter \u2014 contained via DenyAllPermission. Satisfies CONTAINED_NO_AUTHORITY: reachable-but-denied Django, dead/separate-service-only TS, no legitimate consumer.",
    supportingCapability: ["backend/unions/views.py"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
]
