/**
 * db/rls-storage-authority/communications-notifications.ts
 *
 * PR #752 round 9: extracted from the single-file
 * db/rls-storage-authority-manifest.ts (which exceeded the repository's
 * 8000-line hard cap at 8009 lines — see
 * tooling/contract-tests/file-size-enforcement.test.ts) into semantic
 * domain modules. This module owns: Messages, notifications, communications, campaigns.
 *
 * Domain boundaries were assigned mechanically by table-name keyword
 * matching against the entry's `table` field (see the one-time migration
 * script referenced in the round-9 commit message) — every entry's DATA
 * (classification, reason, privileges, authority) is unchanged from the
 * pre-split manifest; only its physical file location changed. Do not
 * hand-edit an entry's domain placement without also checking
 * db/__tests__/rls-storage-authority-registry-composition.test.ts, which
 * proves the composed registry is unaffected by which module an entry
 * lives in.
 *
 * Add NEW entries to whichever domain module most closely matches the
 * table's real subject matter; when genuinely ambiguous, prefer
 * reference-latent.ts (the catch-all) over forcing a bad fit elsewhere.
 */
import type { StorageAuthorityEntry } from './types';

export const communicationsNotificationsEntries: StorageAuthorityEntry[] = [
  {
    table: "campaigns",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01 against LIVE staging DB: 27 columns, organization_id present, matching db/schema/domains/communications/campaigns.ts. Heavily reachable (40+ real references across the communications dashboard, API routes, and webhooks), all via the canonical declaration. Round 4 (2026-09-01): re-investigated the previously-disclosed 'broken worker' defect against lib/workers/message-queue-processor.ts, which imported the stale db/schema/phase-4-messaging-schema.ts declaration. Confirmed via git grep for the module path AND every exported symbol name (processMessageQueue, processCampaignMessages, getQueueStatus) across app/, actions/, lib/, services/ that this worker had ZERO production callers - only its own test file imported it. The send-side capability is officially NOT_IMPLEMENTED (app/api/cron/process-messages/route.ts throws ApiError.notImplemented() per Wave 0 finding F-01, docs/union-eyes/reality-remediation/04_FINDINGS_AND_DISPOSITIONS.md) and never invoked this worker. Disposition: deleted the worker, its test, and the now-fully-orphaned phase-4-messaging-schema.ts (verified zero other importers of any of its 3 exports) rather than canonicalizing dead code. No live defect existed - the previous 'redesign required' framing was based on treating 'imports the stale schema' as proof of a real consumer without checking whether the importing module itself was ever invoked.",
    supportingCapability: ["app/[locale]/dashboard/communications/page.tsx","app/api/communications/campaigns/route.ts","app/api/communications/track/click/route.ts","app/api/communications/track/open/[campaignId]/[recipientId]/route.ts","app/api/communications/unsubscribe/[recipientId]/route.ts","app/api/communications/webhooks/resend/route.ts","db/schema/domains/communications/campaigns.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: ["SELECT","UPDATE"],
    invocationAuthority: "MIXED",
    dbExecutionPrincipal: "MIXED",
    reviewPriority: "HIGH",
  },
  {
    table: "chat_sessions",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'chatSessions' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/ai/chatbot-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "chatbot_analytics",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'chatbotAnalytics' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "chatbot_suggestions",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'chatbotSuggestions' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "communication_analytics",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'communicationAnalytics' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "communication_channels",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'communicationChannels' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "communication_preferences",
    classification: "TENANT_RLS_REQUIRED",
    reason: "3 conflicting declarations exist for physical table 'communication_preferences' (communication-analytics-schema.ts, domains/communications/analytics.ts, domains/communications/campaigns.ts — all 17-18 cols), but the live runtime evidence is consistent: app/api/communications/unsubscribe/[recipientId]/route.ts resolves the org from the campaign, then selects/updates communicationPreferences by (organization_id, user_id), and app/api/members/[id]/preferences/route.ts exposes the same table as org-scoped CRUD. This is a tenant-scoped membership preference table and must sit behind the same org-isolation policy as campaigns/message_log rather than a broad blanket runtime grant.",
    supportingCapability: ["app/api/communications/unsubscribe/[recipientId]/route.ts","app/api/members/[id]/preferences/route.ts","db/schema/domains/communications/campaigns.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: ["SELECT","INSERT","UPDATE"],
    invocationAuthority: "MIXED",
    dbExecutionPrincipal: "MIXED",
    reviewPriority: "HIGH",
  },
  {
    table: "communication_preferences_phase4",
    classification: "NEEDS_REVIEW",
    reason: "Django-owned table (backend/notifications/models.py, db_table='communication_preferences_phase4') with no remaining Drizzle/TS declaration — its only TS-side mirror (db/schema/phase-4-messaging-schema.ts's 'communicationPreferences' export) was deleted in round 4 as dead code with zero consumers (see 'campaigns' entry). Original scanner supportingCapability list included false positives from an unrelated, identically-named 'communicationPreferences' export in db/schema/communication-analytics-schema.ts (a different physical table, see 'communication_preferences' entry) — removed below pending precise per-import re-verification. Out of this round's bounded scope; full disposition (confirm no TS-side access to this table is needed, or add a canonical Drizzle declaration if it is) tracked as follow-up. PR #752 round 8: this is the ONLY manifest entry left outside the canonical DECLARED public-schema scope (verified via scripts/generate-public-schema-grant-census.ts's merged declaration universe) — classified DECLARATION_STALE_OR_NONCANONICAL below: the physical table is real (Django-owned, live in Postgres) but has zero current TypeScript/Drizzle declaration to resolve against.",
    supportingCapability: ["app/api/communications/unsubscribe/[recipientId]/route.ts","app/api/communications/webhooks/resend/route.ts","app/api/members/[id]/preferences/route.ts","lib/ml/predictive-scoring.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
    scopeDisposition: "DECLARATION_STALE_OR_NONCANONICAL",
  },
  {
    table: "consent_records",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified via real runtime usage: app/api/consent/route.ts exposes consentRecords via crudRoutes({ orgScoped: true, readRole: 'member', writeRole: 'steward' }) — GET/POST only, no PUT/PATCH/DELETE handlers are wired (crud-factory only emits the handlers destructured by the route). app/api/communications/unsubscribe/[recipientId]/route.ts inserts consentRecords with the resolved organization_id/user_id and a consent_type of email_marketing while revoking the subscription. No UPDATE or DELETE against this table exists anywhere in production code (git grep confirmed) — the table's own doc comment ('Immutable audit log of all consent changes (CASL/GDPR requirement)') and its column set (no updatedAt) confirm this is an append-only ledger by design, not an oversight. Reads are org-scoped, not user-scoped: the route sets no crud-factory ownerColumn, so any authenticated org member (readRole 'member') can list the org's full consent history — that is the actual implemented product authority (compliance officers/stewards need to see the org's consent posture), not an accidental broad grant, so USER_RLS_REQUIRED would under-scope real reads. TENANT_RLS_REQUIRED via the native organization_id column is correct; requiredRuntimePrivilege is SELECT_INSERT, not FULL_DML.",
    supportingCapability: ["app/api/consent/route.ts","app/api/communications/unsubscribe/[recipientId]/route.ts","db/schema/domains/communications/campaigns.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: ["INSERT"],
    invocationAuthority: "MIXED",
    dbExecutionPrincipal: "MIXED",
    reviewPriority: "HIGH",
  },
  {
    table: "cookie_consents",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'cookieConsents' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/gdpr/consent-manager.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "data_aggregation_consent",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CLOSED (2026-09-04, round 40 SIMPLE_TENANT:org:NORMAL cohort): direct NOT NULL organization_id table. Live paths are server pages app/[locale]/dashboard/settings/data-sharing/page.tsx and app/[locale]/dashboard/movement-insights/page.tsx, both after requireUser(), using the authenticated user's organizationId and filtering dataAggregationConsent by organizationId. The apparent mutation helpers in lib/movement-insights/consent-manager.ts are library-only today: ConsentForm/RevokeConsentButton post to /api/consent, whose route operates on consentRecords, not dataAggregationConsent. DataAggregationConsentViewSet is separately router-registered but now unconditionally denied via Round40DenyAllPermission because it has no legitimate Django consumer. Minimum live runtime DML is SELECT only, no withSystemContext.",
    supportingCapability: ["app/[locale]/dashboard/movement-insights/page.tsx","app/[locale]/dashboard/settings/data-sharing/page.tsx","lib/movement-insights/consent-manager.ts"],
    requiredRuntimePrivileges: ["SELECT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "donation_campaigns",
    classification: "NEEDS_REVIEW",
    reason: "3 non-test reference(s) to 'donationCampaigns' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/cope/campaigns/route.ts","app/api/cope/canvassing/route.ts","app/api/cope/officials/route.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "employer_communications",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'employerCommunications' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/employers/communications/route.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "external_communication_channels",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CLOSED (2026-09-04, round 40 integration control plane tranche): direct org-scoped integration table reached only through app/api/integrations/framework/**, where withApi derives the organizationId from the authenticated caller, loads integration_configs by id+organizationId, and passes a trusted TENANT_RUNTIME execution context into SyncEngine. The only approved writers are the registered Slack/Teams communication adapters, which upsert channels under orgId/provider/externalId and select org-scoped channels while syncing messages/files/members. No generic external CRUD route or arbitrary table-sync route was created. The generated ExternalCommunicationChannelsViewSet in backend/core/views.py remains router-registered but unconditionally denied via DenyAllPermission.",
    supportingCapability: ["app/api/integrations/framework/route.ts","app/api/integrations/framework/[id]/sync/route.ts","lib/integrations/control-plane.ts","lib/integrations/sync-engine.ts","lib/integrations/adapters/communication/slack-adapter.ts","lib/integrations/adapters/communication/teams-adapter.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "external_communication_messages",
    classification: "NEEDS_REVIEW",
    reason: "2 non-test reference(s) to 'externalCommunicationMessages' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/integrations/adapters/communication/slack-adapter.ts","lib/integrations/adapters/communication/teams-adapter.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "external_communication_users",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CLOSED (2026-09-04, round 40 integration control plane tranche): direct org-scoped integration table reached only through app/api/integrations/framework/**, where withApi derives organizationId from the authenticated caller and SyncEngine receives a trusted TENANT_RUNTIME context for the approved Slack/Teams adapters. Those adapters upsert external users/members under orgId/provider/externalId; no generic external-user CRUD route or arbitrary table-sync route was created. The generated ExternalCommunicationUsersViewSet in backend/core/views.py remains router-registered but unconditionally denied via DenyAllPermission.",
    supportingCapability: ["app/api/integrations/framework/route.ts","app/api/integrations/framework/[id]/sync/route.ts","lib/integrations/control-plane.ts","lib/integrations/sync-engine.ts","lib/integrations/adapters/communication/slack-adapter.ts","lib/integrations/adapters/communication/teams-adapter.ts"],
    requiredRuntimePrivileges: ["INSERT","UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "in_app_notifications",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified 2026-09-02: direct NOT NULL organization_id column (db/schema/domains/communications/notifications.ts). Reachable via live HTTP routes app/api/notifications/route.ts, app/api/notifications/[id]/route.ts, app/api/notifications/count/route.ts, app/api/notifications/mark-all-read/route.ts, and the support-ticket notification surface (app/api/support/tickets/**).",
    supportingCapability: ["app/api/notifications/route.ts","app/api/notifications/[id]/route.ts","app/api/notifications/count/route.ts","app/api/notifications/mark-all-read/route.ts","app/api/support/tickets/route.ts","lib/services/notification-service.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "message_log",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01 against LIVE staging DB: 24 columns, organization_id present, matching db/schema/domains/communications/campaigns.ts's messageLog export. Real consumers (webhook delivery tracking, open/click pixel tracking, unsubscribe flow) already use the canonical shape correctly. Round 4 (2026-09-01): same re-investigation as 'campaigns' — lib/workers/message-queue-processor.ts's stale db/schema/phase-4-messaging-schema.ts usage (channel/body/variables/scheduledAt/externalId/nextRetryAt columns that do NOT physically exist) had ZERO production callers and has been deleted along with its test and the now-fully-orphaned phase-4-messaging-schema.ts. See 'campaigns' entry for the full reasoning.",
    supportingCapability: ["app/api/communications/track/click/route.ts","app/api/communications/track/open/[campaignId]/[recipientId]/route.ts","app/api/communications/unsubscribe/[recipientId]/route.ts","app/api/communications/webhooks/resend/route.ts","db/schema/domains/communications/campaigns.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: ["SELECT","UPDATE"],
    invocationAuthority: "MIXED",
    dbExecutionPrincipal: "MIXED",
    reviewPriority: "HIGH",
  },
  {
    table: "mobile_notifications",
    classification: "LATENT_UNREACHABLE",
    reason: "Manually verified 2026-09-02: nullable organization_id, NOT NULL user_id (db/schema/mobile-devices-schema.ts) — would otherwise be a USER_RLS_REQUIRED candidate, but its sole non-test reference is lib/mobile/mobile-engine.ts, whose MobileNotificationService export has zero callers anywhere under app/, actions/, lib/, services/, scripts/ (verified by name-search). Distinct from the separately-reachable app/api/mobile/notifications/route.ts, which reads the \"notifications\" table, not this one.",
    supportingCapability: ["lib/mobile/mobile-engine.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "newsletter_campaigns",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'newsletterCampaigns' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/billing/batch-status/[jobId]/route.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "newsletter_distribution_lists",
    classification: "NEEDS_REVIEW",
    reason: "3 non-test reference(s) to 'newsletterDistributionLists' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/[locale]/dashboard/communications/page.tsx","app/api/communications/distribution-lists/[id]/route.ts","app/api/communications/distribution-lists/route.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "notification_bounces",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'notificationBounces' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "notification_delivery_log",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified 2026-09-02, resolved 2026-09-02 (round 5): direct NOT NULL organization_id column (db/schema/domains/communications/notifications.ts). MIXED — lib/services/notification-service.ts's notificationDeliveryLog INSERT executes via the plain `db` import; it is invoked both from the TENANT_USER path (app/api/dues/arrears/[id]/reminder/route.ts, steward-gated) and lib/jobs/dues-reminder-scheduler.ts (admin-invoked via app/api/admin/dues/send-reminders/route.ts, no withSystemContext of its own — stays TENANT_RUNTIME), and from lib/jobs/billing-scheduler.ts's SYSTEM_SCHEDULE path, which (per PR #752 round 4) wraps its entire cross-org operation in withSystemContext — the ALS-based `db` Proxy routes notification-service.ts's same INSERT call to SYSTEM_RUNTIME when called from inside that boundary. requiredSystemPrivileges reflects only the INSERT this table receives.",
    supportingCapability: ["lib/services/notification-service.ts","app/api/dues/arrears/[id]/reminder/route.ts","lib/jobs/dues-reminder-scheduler.ts","lib/jobs/billing-scheduler.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: ["INSERT"],
    invocationAuthority: "MIXED",
    dbExecutionPrincipal: "MIXED",
    reviewPriority: "HIGH",
  },
  {
    table: "notification_history",
    classification: "LATENT_UNREACHABLE",
    reason: "RECLASSIFIED 2026-09-02 (round 5, from TENANT_RLS_REQUIRED/MIXED): re-verified against the actual imports of lib/services/notification-service.ts — it imports only `notificationQueue`, `notificationDeliveryLog`, `notificationTemplates` from db/schema/domains/communications; `notificationHistory` appears ONLY in a doc comment ('- notificationHistory: Audit log for all notifications'), never as an actual query. Its other cited evidence, lib/workers/{cleanup,email,notification,sms}-worker.ts, has ZERO real (non-test) importers anywhere in app/, actions/, lib/, or services/ — confirmed orphaned by the 2026-02-19 Django Celery migration (see lib/job-queue.ts's own doc comment; same dead-module family as user_sessions/grievance_transitions' prior citations). No other non-test reference to the 'notificationHistory' Drizzle export exists. Resolves the prior entry's own flagged follow-up ('execution authority for the worker path not yet independently confirmed').",
    supportingCapability: ["db/schema/domains/communications/notifications.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "notification_log",
    classification: "LATENT_UNREACHABLE",
    reason: "Manually verified 2026-09-02: direct NOT NULL organization_id column (db/schema/domains/infrastructure/clc-per-capita.ts), but its sole non-test reference is services/clc/remittance-notifications.ts, whose exports (sendOverdueAlert, sendMonthlyReminder, processOverdueRemittances, etc.) have zero callers anywhere under app/, actions/, lib/, services/, scripts/ (verified by name-search). No live route, action, or cron entrypoint reaches this table today.",
    supportingCapability: ["services/clc/remittance-notifications.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "notification_queue",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified 2026-09-02, resolved 2026-09-02 (round 5): direct NOT NULL organization_id column (db/schema/domains/communications/notifications.ts). MIXED — lib/job-queue.ts is now a thin HTTP client to Django Celery (per its own doc comment, migrated 2026-02-19) and does not itself touch this table; the real DB access is lib/services/notification-service.ts's notificationQueue SELECT/INSERT/UPDATE via the plain `db` import, invoked both from the TENANT_USER path (app/api/dues/arrears/[id]/reminder/route.ts, app/api/metrics/operational/route.ts, app/api/union-eyes/queue-status/route.ts) and from lib/jobs/billing-scheduler.ts's SYSTEM_SCHEDULE path, which wraps its entire operation in withSystemContext (PR #752 round 4) — the same notification-service.ts call routes to SYSTEM_RUNTIME when invoked from inside that boundary.",
    supportingCapability: ["lib/services/notification-service.ts","app/api/dues/arrears/[id]/reminder/route.ts","app/api/metrics/operational/route.ts","app/api/union-eyes/queue-status/route.ts","lib/jobs/billing-scheduler.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: ["SELECT","INSERT","UPDATE"],
    invocationAuthority: "MIXED",
    dbExecutionPrincipal: "MIXED",
    reviewPriority: "HIGH",
  },
  {
    table: "notification_tracking",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified 2026-09-02, resolved 2026-09-02 (round 5, corrected): direct NOT NULL organization_id column (db/schema/domains/communications/notifications.ts). Re-verified lib/services/notification-service.ts's actual imports — it imports notificationQueue/notificationDeliveryLog/notificationTemplates only; `notificationTracking` is mentioned solely in a doc comment, never queried there. The ONLY real writer/reader is services/observability/realtime-alerting-service.ts (plain `db`, no withSystemContext), called from BOTH app/api/alerts/realtime/route.ts (withApi minRole member — TENANT_USER) AND app/api/cron/observability-alerts/route.ts (auth: { cron: true } — SYSTEM_SCHEDULE). invocationAuthority is genuinely MIXED, but because realtime-alerting-service.ts never escalates to withSystemContext on either path, dbExecutionPrincipal is TENANT_RUNTIME only (not MIXED) — flagged as a separate, out-of-scope latent gap: the cron-invoked sweep runs cross-org without a tenant session, through the ordinary tenant-RLS-gated connection.",
    supportingCapability: ["services/observability/realtime-alerting-service.ts","app/api/alerts/realtime/route.ts","app/api/cron/observability-alerts/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "MIXED",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "notifications",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified 2026-09-02: direct NOT NULL organization_id + user_id columns (db/schema/domains/communications/notifications.ts). Reachable via multiple live HTTP routes (app/api/notifications/route.ts, app/api/notifications/[id]/route.ts, app/api/notifications/count/route.ts, app/api/notifications/mark-all-read/route.ts, app/api/notifications/preferences/route.ts, app/api/notifications/device/route.ts, app/api/notifications/test/route.ts, app/api/mobile/notifications/route.ts) and cron routes (app/api/cron/education-reminders, overdue-notifications, process-notifications, observability-alerts). Needs the same ue_create_direct_org_rls_policy treatment as the 0108 protected set.",
    supportingCapability: ["app/api/notifications/route.ts","app/api/notifications/[id]/route.ts","app/api/notifications/count/route.ts","app/api/notifications/mark-all-read/route.ts","app/api/notifications/preferences/route.ts","app/api/notifications/device/route.ts","app/api/notifications/test/route.ts","app/api/mobile/notifications/route.ts","app/api/cron/education-reminders/route.ts","app/api/cron/overdue-notifications/route.ts","app/api/cron/process-notifications/route.ts","lib/services/notification-service.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "organizing_campaign_milestones",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'organizingCampaignMilestones' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "organizing_campaigns",
    classification: "NEEDS_REVIEW",
    reason: "18 non-test reference(s) to 'organizingCampaigns' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/organizing/assignments/[id]/route.ts","app/api/organizing/assignments/route.ts","app/api/organizing/campaigns/route.ts","app/api/organizing/card-check/route.ts","app/api/organizing/committee/route.ts","app/api/organizing/forms/generate/route.ts","app/api/organizing/labour-board/route.ts","app/api/organizing/nlrb-filings/route.ts","app/api/organizing/notes/[id]/route.ts","app/api/organizing/notes/route.ts","app/api/organizing/sequences/[id]/enroll/route.ts","app/api/organizing/sequences/[id]/route.ts","app/api/organizing/sequences/route.ts","app/api/organizing/support-percentage/route.ts","app/api/organizing/workplace-mapping/route.ts","services/financial-service/drizzle/relations.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "push_notifications",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified 2026-09-02: direct NOT NULL organization_id column (db/schema/domains/communications/push-notifications.ts). Reachable via live HTTP routes app/api/mobile/push/subscribe/route.ts and app/api/mobile/push/unsubscribe/route.ts.",
    supportingCapability: ["app/api/mobile/push/subscribe/route.ts","app/api/mobile/push/unsubscribe/route.ts","services/fcm-service.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "sms_campaigns",
    classification: "NEEDS_REVIEW",
    reason: "3 non-test reference(s) to 'smsCampaigns' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/[locale]/dashboard/communications/page.tsx","app/api/communications/sms/campaigns/route.ts","services/twilio-sms-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "sms_conversations",
    classification: "NEEDS_REVIEW",
    reason: "2 non-test reference(s) to 'smsConversations' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/communications/sms/conversations/route.ts","services/twilio-sms-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "sms_messages",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01 (round 6, Phase-3A priority tranche): direct NOT NULL organization_id column, reachable via live HTTP route(s) app/api/communications/sms/route.ts. org-scoped SMS message CRUD route; crudRoutes GET+POST plus confirmed UPDATE+DELETE (delivery-status update, message removal). Minimum runtime privilege set from confirmed DML verbs (crudRoutes handler destructuring and/or direct .insert/.update/.delete/.select call-site evidence), not defaulted to FULL_DML.",
    supportingCapability: ["app/api/communications/sms/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "sms_opt_outs",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'smsOptOuts' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["services/twilio-sms-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "sms_rate_limits",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'smsRateLimits' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "social_campaigns",
    classification: "NEEDS_REVIEW",
    reason: "2 non-test reference(s) to 'socialCampaigns' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/social-media/analytics/route.ts","app/api/social-media/campaigns/route.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "user_consents",
    classification: "NEEDS_REVIEW",
    reason: "2 non-test reference(s) to 'userConsents' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/members/[id]/consents/route.ts","lib/gdpr/consent-manager.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "user_notification_preferences",
    classification: "NEEDS_REVIEW",
    reason: "10 non-test reference(s) to 'userNotificationPreferences' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/messaging/preferences/route.ts","app/api/notifications/device/route.ts","app/api/notifications/preferences/route.ts","lib/services/notification-service.ts","lib/workers/email-worker.ts","lib/workers/notification-worker.ts","lib/workers/sms-worker.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts","services/financial-service/src/services/notification-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "band_council_consent",
    classification: "NEEDS_REVIEW",
    reason: "2 non-test reference(s) to 'bandCouncilConsent' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/services/indigenous-data-service.ts","services/indigenous-data-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "chat_messages",
    classification: "NEEDS_REVIEW",
    reason: "2 non-test reference(s) to 'chatMessages' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/ai/chatbot-service.ts","lib/ai/template-engine.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "federation_campaigns",
    classification: "LATENT_UNREACHABLE",
    reason: "Round-7 scope-expansion scan: zero references to the 'federationCampaigns' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files via a combined ripgrep pass across app/, actions/, lib/, services/. No known application code path queries this table today. NOT yet individually checked for raw-SQL (non-Drizzle-symbol) references to the physical table name — see the raw-SQL LATENT fixture test for why that check matters before this can be treated as final.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "federation_communications",
    classification: "LATENT_UNREACHABLE",
    reason: "Round-7 scope-expansion scan: zero references to the 'federationCommunications' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files via a combined ripgrep pass across app/, actions/, lib/, services/. No known application code path queries this table today. NOT yet individually checked for raw-SQL (non-Drizzle-symbol) references to the physical table name — see the raw-SQL LATENT fixture test for why that check matters before this can be treated as final.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "newsletter_engagement",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'newsletterEngagement' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/engagement-scoring.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "newsletter_list_subscribers",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'newsletterListSubscribers' found (round-7 scope-expansion scan). At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/communications/distribution-lists/[id]/subscribers/route.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "newsletter_recipients",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'newsletterRecipients' found (round-7 scope-expansion scan). At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/billing/batch-status/[jobId]/route.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "provincial_consent",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'provincialConsent' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["services/provincial-privacy-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "sms_campaign_recipients",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'smsCampaignRecipients' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/gdpr/consent-manager.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "voting_notifications",
    classification: "NEEDS_REVIEW",
    reason: "3 non-test reference(s) to 'votingNotifications' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["services/financial-service/drizzle/relations.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
]
