/**
 * db/rls-storage-authority/documents-evidence.ts
 *
 * PR #752 round 9: extracted from the single-file
 * db/rls-storage-authority-manifest.ts (which exceeded the repository's
 * 8000-line hard cap at 8009 lines — see
 * tooling/contract-tests/file-size-enforcement.test.ts) into semantic
 * domain modules. This module owns: Documents, evidence, files, uploads, templates.
 *
 * Domain boundaries were assigned mechanically by table-name keyword
 * matching against the entry's `table` field (see the one-time migration
 * script referenced in the round-9 commit message) — every entry's DATA
 * (classification, reason, privileges, authority) is unchanged from the
 * pre-split manifest; only its physical file location changed. Do not
 * hand-edit an entry's domain placement without also checking
 * db/__tests__/rls-storage-authority-registry-composition.test.ts, which
 * proves the composed registry is unaffected by which module an entry
 * lives in.
 *
 * Add NEW entries to whichever domain module most closely matches the
 * table's real subject matter; when genuinely ambiguous, prefer
 * reference-latent.ts (the catch-all) over forcing a bad fit elsewhere.
 */
import type { StorageAuthorityEntry } from './types';

export const documentsEvidenceEntries: StorageAuthorityEntry[] = [
  {
    table: "award_templates",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'awardTemplates' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/services/rewards/template-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "cms_media_library",
    classification: "NEEDS_REVIEW",
    reason: "3 non-test reference(s) to 'cmsMediaLibrary' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/storage/cleanup/route.ts","app/api/storage/usage/route.ts","app/api/upload/route.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "cms_templates",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'cmsTemplates' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "communication_templates",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'communicationTemplates' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "document_access_grants",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01, corrected 2026-09-02 (round 5 — the prior citation app/api/documents/[id]/access-grants/route.ts does not exist): direct NOT NULL organization_id column; real, verified non-test references are app/api/grievances/[id]/route.ts, app/api/grievances/[id]/documents/route.ts (both withOrganizationAuth-gated, tenant-scoped) and lib/services/document-service.ts / lib/services/document-authorization-service.ts (both plain `db` import, no withSystemContext).",
    supportingCapability: ["app/api/grievances/[id]/route.ts","app/api/grievances/[id]/documents/route.ts","lib/services/document-service.ts","lib/services/document-authorization-service.ts"],
    requiredRuntimePrivileges: ["SELECT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "document_folders",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CLOSED (2026-09-04, round 40 SIMPLE_TENANT:org:NORMAL cohort): direct NOT NULL organization_id table. Live path is app/api/documents/folders/route.ts, a legacy endpoint behind LEGACY_DOCUMENT_API_ENABLED and withRoleAuth('member' GET / 'steward' POST); both methods require the request organizationId to match context.organizationId before calling lib/services/document-service.ts. GET uses listFolders/getFolderTree with organizationId predicates; POST inserts through createFolder with the context-matched organizationId and createdBy userId. lib/documents/batch-operations-service.ts only validates target folders by id+organizationId for document operations. DocumentFoldersViewSet is separately router-registered but now unconditionally denied via Round40DenyAllPermission because it has no legitimate Django consumer. Minimum proven runtime DML for the folder table is SELECT+INSERT, no withSystemContext.",
    supportingCapability: ["app/api/documents/folders/route.ts","lib/documents/batch-operations-service.ts","lib/services/document-service.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "document_links",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01, corrected 2026-09-02 (round 5 — the prior citation app/api/documents/[id]/links/route.ts does not exist): direct NOT NULL organization_id column; real, verified non-test references are app/api/grievances/[id]/route.ts, app/api/documents/[id]/download/route.ts (both tenant-authenticated) and lib/services/document-service.ts (plain `db` import, no withSystemContext).",
    supportingCapability: ["app/api/grievances/[id]/route.ts","app/api/documents/[id]/download/route.ts","lib/services/document-service.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "document_search_index",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'documentSearchIndex' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "document_versions",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01, corrected 2026-09-02 (round 5 — the prior citation app/api/documents/[id]/versions/route.ts does not exist; real path is app/api/documents/repository/[id]/versions/route.ts): direct NOT NULL organization_id column, reachable via app/api/documents/repository/[id]/versions/route.ts, app/api/documents/repository/[id]/route.ts, app/api/documents/[id]/download/route.ts, and lib/services/document-service.ts (all plain `db` import, no withSystemContext), append-only (SELECT+INSERT confirmed, no UPDATE/DELETE).",
    supportingCapability: ["app/api/documents/repository/[id]/versions/route.ts","app/api/documents/repository/[id]/route.ts","app/api/documents/[id]/download/route.ts","lib/services/document-service.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "employer_execution_evidence_links",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01, corrected 2026-09-02 (round 5 — the prior citation app/api/employer-execution/[id]/evidence-links/route.ts does not exist): direct NOT NULL organization_id column; real, verified non-test references are app/api/employer-execution/remittance-runs/route.ts (minRole member/steward), app/api/employer-execution/replay/[runId]/route.ts (minRole steward), app/api/employer-execution/payroll-runs/[id]/route.ts — all withApi(), tenant org-scoped, plain `db` import, no withSystemContext.",
    supportingCapability: ["app/api/employer-execution/remittance-runs/route.ts","app/api/employer-execution/replay/[runId]/route.ts","app/api/employer-execution/payroll-runs/[id]/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "employer_execution_profiles",
    classification: "NEEDS_REVIEW",
    reason: "3 non-test reference(s) to 'employerExecutionProfiles' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/[locale]/dashboard/employer-execution/settings/page.tsx","app/api/employer-execution/payroll-runs/[id]/route.ts","app/api/employer-execution/remittance-runs/route.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "exit_interview_documents",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01 (round 6, Phase-3A priority tranche): direct NOT NULL organization_id column, reachable via live HTTP route(s) app/api/exit-interviews/[id]/documents/route.ts. org-scoped exit-interview document attachment endpoint; SELECT+INSERT confirmed. Minimum runtime privilege set from confirmed DML verbs (crudRoutes handler destructuring and/or direct .insert/.update/.delete/.select call-site evidence), not defaulted to FULL_DML.",
    supportingCapability: ["app/api/exit-interviews/[id]/documents/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "external_communication_files",
    classification: "NEEDS_REVIEW",
    reason: "2 non-test reference(s) to 'externalCommunicationFiles' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/integrations/adapters/communication/slack-adapter.ts","lib/integrations/adapters/communication/teams-adapter.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "external_document_files",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'externalDocumentFiles' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/integrations/adapters/documents/sharepoint-adapter.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "external_document_libraries",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CLOSED (2026-09-04, round 40 integration control plane tranche): direct org-scoped integration table reached only through app/api/integrations/framework/**, where withApi derives organizationId from the authenticated caller and SyncEngine receives a trusted TENANT_RUNTIME context for the approved SharePoint adapter. The adapter upserts libraries under orgId/provider/externalId and selects org-scoped libraries while syncing files/permissions. No external-document CRUD route or arbitrary table-sync route was created. The generated ExternalDocumentLibrariesViewSet in backend/core/views.py remains router-registered but unconditionally denied via DenyAllPermission.",
    supportingCapability: ["app/api/integrations/framework/route.ts","app/api/integrations/framework/[id]/sync/route.ts","lib/integrations/control-plane.ts","lib/integrations/sync-engine.ts","lib/integrations/adapters/documents/sharepoint-adapter.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "external_document_permissions",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'externalDocumentPermissions' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/integrations/adapters/documents/sharepoint-adapter.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "external_document_sites",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CLOSED (2026-09-04, round 40 integration control plane tranche): direct org-scoped integration table reached only through app/api/integrations/framework/**, where withApi derives organizationId from the authenticated caller and SyncEngine receives a trusted TENANT_RUNTIME context for the approved SharePoint adapter. The adapter upserts sites under orgId/provider/externalId. No external-document CRUD route or arbitrary table-sync route was created. The generated ExternalDocumentSitesViewSet in backend/core/views.py remains router-registered but unconditionally denied via DenyAllPermission.",
    supportingCapability: ["app/api/integrations/framework/route.ts","app/api/integrations/framework/[id]/sync/route.ts","lib/integrations/control-plane.ts","lib/integrations/sync-engine.ts","lib/integrations/adapters/documents/sharepoint-adapter.ts"],
    requiredRuntimePrivileges: ["INSERT","UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "icra_maturity_profiles",
    classification: "SYSTEM_ONLY",
    reason: "ICRA_PSEUDONYMOUS_NO_LOGIN=APPROVED, ASSESSMENT_ID_AS_SOLE_BEARER_AUTHORITY=REJECTED (PR #752): the pseudonymous product model is intentional, but assessmentId alone must never authorize DB access. lib/icra/assessment-capability.ts adds a hashed, purpose-bound bearer capability; every route touching an existing assessment now verifies it before entering withSystemContext. Verified 2026-09-01 (round 7, ICRA capability architecture): only reached via withSystemContext() in the capability-gated submit/profile/results/report routes. No direct organization_id column.",
    supportingCapability: ["app/api/icra/submit/route.ts","app/api/icra/[assessmentId]/submit/route.ts","app/api/icra/[assessmentId]/profile/route.ts","app/api/icra/results/[id]/route.ts","app/api/icra/report/[assessmentId]/route.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "SYSTEM_SCHEDULE",
    dbExecutionPrincipal: "SYSTEM_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "message_templates",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01, corrected 2026-09-02 (round 5 — the prior citation app/api/communications/message-templates/route.ts does not exist): direct NOT NULL organization_id column; real, verified non-test reference is app/api/communications/templates/route.ts (crudRoutes readRole member/writeRole steward), plain `db` import, no withSystemContext. (app/api/messaging/templates/route.ts is a separate 'messagingTemplates' export, out of scope for this table.)",
    supportingCapability: ["app/api/communications/templates/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "newsletter_templates",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'newsletterTemplates' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "notification_templates",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified 2026-09-02: direct NOT NULL organization_id column (db/schema/domains/communications/notifications.ts) — org-configurable templates alongside seeded system templates (isSystem flag). Reachable via lib/services/notification-service.ts, itself reachable via app/api/dues/arrears/[id]/reminder/route.ts.",
    supportingCapability: ["lib/services/notification-service.ts","app/api/dues/arrears/[id]/reminder/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "push_notification_templates",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'pushNotificationTemplates' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "report_templates",
    classification: "LATENT_UNREACHABLE",
    reason: "Verified 2026-09-01 (round 6, Phase-3A priority tranche + reachability-scan correction): reportTemplates has a real, non-duplicate union-eyes-native pgTable('report_templates', ...) declaration (db/schema/domains/analytics/reports.ts, db/schema/reports-schema.ts), but zero non-test references to it exist anywhere in app/, actions/, lib/, or services/ within apps/union-eyes proper. The original scan's supportingCapability list for this table only surfaced services/financial-service's own same-named, separately-databased table (its own drizzle.config.ts/DATABASE_URL) and MISSED the real union-eyes declaration entirely — this entry corrects that gap. No known union-eyes application code path queries this table today.",
    supportingCapability: ["db/schema/domains/analytics/reports.ts","db/schema/reports-schema.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "signature_documents",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'signatureDocuments' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/signature/signature-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "signature_templates",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'signatureTemplates' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "sms_templates",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'smsTemplates' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["services/twilio-sms-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "arbitrator_profiles",
    classification: "NEEDS_REVIEW",
    reason: "3 non-test reference(s) to 'arbitratorProfiles' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/services/precedent-service.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "document_signers",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'documentSigners' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/signature/signature-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "pending_profiles",
    classification: "NEEDS_REVIEW",
    reason: "2 non-test reference(s) to 'pendingProfilesTable' found (round-7 scope-expansion scan). At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/continuity/inheritance/route.ts","app/api/onboarding/route.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "pricing_template_modules",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'pricingTemplateModules' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["services/platform-economics/pricing-template-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "pricing_templates",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'pricingTemplates' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["services/platform-economics/pricing-template-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "profiles",
    classification: "NEEDS_REVIEW",
    reason: "4 non-test reference(s) to 'profilesTable' found (round-7 scope-expansion scan). At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/members/me/route.ts","app/api/profile/roles/route.ts","lib/payment-processor/examples/refactored-dues-payment-route.ts","lib/utils/member-data-utils.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "swiss_cold_storage",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'swissColdStorage' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["services/break-glass-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "transfer_pricing_documentation",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'transferPricingDocumentation' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["services/transfer-pricing-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
]
