/**
 * db/rls-storage-authority/documents-evidence.ts
 *
 * PR #752 round 9: extracted from the single-file
 * db/rls-storage-authority-manifest.ts (which exceeded the repository's
 * 8000-line hard cap at 8009 lines — see
 * tooling/contract-tests/file-size-enforcement.test.ts) into semantic
 * domain modules. This module owns: Documents, evidence, files, uploads, templates.
 *
 * Domain boundaries were assigned mechanically by table-name keyword
 * matching against the entry's `table` field (see the one-time migration
 * script referenced in the round-9 commit message) — every entry's DATA
 * (classification, reason, privileges, authority) is unchanged from the
 * pre-split manifest; only its physical file location changed. Do not
 * hand-edit an entry's domain placement without also checking
 * db/__tests__/rls-storage-authority-registry-composition.test.ts, which
 * proves the composed registry is unaffected by which module an entry
 * lives in.
 *
 * Add NEW entries to whichever domain module most closely matches the
 * table's real subject matter; when genuinely ambiguous, prefer
 * reference-latent.ts (the catch-all) over forcing a bad fit elsewhere.
 */
import type { StorageAuthorityEntry } from './types';

export const documentsEvidenceEntries: StorageAuthorityEntry[] = [
  {
    table: "award_templates",
    classification: "CONTAINED_NO_AUTHORITY",
    reason: "CLOSED round 54 (final non-voting parent-owned authority convergence, BLOCKER_ROOT_MICRO_COHORT \u2014 direct parent of award_history, one-hop): lib/services/rewards/template-service.ts's exported functions (listAwardTemplates/getAwardTemplate/createAwardTemplate/updateAwardTemplate/deleteAwardTemplate/recordTemplateUsage/getTemplateHistory/etc.) have ZERO real callers anywhere in app/, actions/, lib/, services/ (git-grep confirmed \u2014 not even a module-level import outside the file's own test) \u2014 fully dead TS code despite organizationId being nullable/unenforced in the schema. Django AwardTemplatesViewSet (backend/unions/views.py) was IsAuthenticated-only with queryset=Model.objects.all() and no org filter \u2014 contained via DenyAllPermission this round (same pattern as the sibling RewardWalletLedgerViewSet in the same file, round 36). No legitimate consumer found on either side.",
    supportingCapability: ["lib/services/rewards/template-service.ts","backend/unions/views.py"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "cms_media_library",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CLOSED round 56 (DIRECT_TENANT_RESOURCE archetype): organization_id NOT NULL. app/api/upload/route.ts and the storage usage/cleanup routes are crudRoutes()-backed (orgScoped:true, server-derived organizationId). uploaded_by is an audit-actor FK to profiles.",
    supportingCapability: ["app/api/storage/cleanup/route.ts","app/api/storage/usage/route.ts","app/api/upload/route.ts"],
    requiredRuntimePrivileges: ["SELECT", "INSERT", "UPDATE", "DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "cms_templates",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'cmsTemplates' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "communication_templates",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'communicationTemplates' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "document_access_grants",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01, corrected 2026-09-02 (round 5 — the prior citation app/api/documents/[id]/access-grants/route.ts does not exist): direct NOT NULL organization_id column; real, verified non-test references are app/api/grievances/[id]/route.ts, app/api/grievances/[id]/documents/route.ts (both withOrganizationAuth-gated, tenant-scoped) and lib/services/document-service.ts / lib/services/document-authorization-service.ts (both plain `db` import, no withSystemContext).",
    supportingCapability: ["app/api/grievances/[id]/route.ts","app/api/grievances/[id]/documents/route.ts","lib/services/document-service.ts","lib/services/document-authorization-service.ts"],
    requiredRuntimePrivileges: ["SELECT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "document_folders",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CLOSED (2026-09-04, round 40 SIMPLE_TENANT:org:NORMAL cohort): direct NOT NULL organization_id table. Live path is app/api/documents/folders/route.ts, a legacy endpoint behind LEGACY_DOCUMENT_API_ENABLED and withRoleAuth('member' GET / 'steward' POST); both methods require the request organizationId to match context.organizationId before calling lib/services/document-service.ts. GET uses listFolders/getFolderTree with organizationId predicates; POST inserts through createFolder with the context-matched organizationId and createdBy userId. lib/documents/batch-operations-service.ts only validates target folders by id+organizationId for document operations. DocumentFoldersViewSet is separately router-registered but now unconditionally denied via Round40DenyAllPermission because it has no legitimate Django consumer. Minimum proven runtime DML for the folder table is SELECT+INSERT, no withSystemContext.",
    supportingCapability: ["app/api/documents/folders/route.ts","lib/documents/batch-operations-service.ts","lib/services/document-service.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "document_links",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01, corrected 2026-09-02 (round 5 — the prior citation app/api/documents/[id]/links/route.ts does not exist): direct NOT NULL organization_id column; real, verified non-test references are app/api/grievances/[id]/route.ts, app/api/documents/[id]/download/route.ts (both tenant-authenticated) and lib/services/document-service.ts (plain `db` import, no withSystemContext).",
    supportingCapability: ["app/api/grievances/[id]/route.ts","app/api/documents/[id]/download/route.ts","lib/services/document-service.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "document_search_index",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'documentSearchIndex' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "document_versions",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01, corrected 2026-09-02 (round 5 — the prior citation app/api/documents/[id]/versions/route.ts does not exist; real path is app/api/documents/repository/[id]/versions/route.ts): direct NOT NULL organization_id column, reachable via app/api/documents/repository/[id]/versions/route.ts, app/api/documents/repository/[id]/route.ts, app/api/documents/[id]/download/route.ts, and lib/services/document-service.ts (all plain `db` import, no withSystemContext), append-only (SELECT+INSERT confirmed, no UPDATE/DELETE).",
    supportingCapability: ["app/api/documents/repository/[id]/versions/route.ts","app/api/documents/repository/[id]/route.ts","app/api/documents/[id]/download/route.ts","lib/services/document-service.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "employer_execution_evidence_links",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01, corrected 2026-09-02 (round 5 — the prior citation app/api/employer-execution/[id]/evidence-links/route.ts does not exist): direct NOT NULL organization_id column; real, verified non-test references are app/api/employer-execution/remittance-runs/route.ts (minRole member/steward), app/api/employer-execution/replay/[runId]/route.ts (minRole steward), app/api/employer-execution/payroll-runs/[id]/route.ts — all withApi(), tenant org-scoped, plain `db` import, no withSystemContext.",
    supportingCapability: ["app/api/employer-execution/remittance-runs/route.ts","app/api/employer-execution/replay/[runId]/route.ts","app/api/employer-execution/payroll-runs/[id]/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "employer_execution_profiles",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CLOSED round 41 (DIRECT_ORG_RUNTIME_BATCH): direct NOT NULL organization_id column (domains/employer-execution/employer-runtime-profile.ts). The only two production readers, app/api/employer-execution/payroll-runs/[id]/route.ts and app/api/employer-execution/remittance-runs/route.ts, are withApi-authenticated (minRole steward/member) and filter eq(employerExecutionProfiles.organizationId, organizationId) with organizationId sourced from the trusted withApi context, never the request body. Both reads are SELECT-only — no route inserts/updates/deletes this table; the sole INSERT reference (scripts/seed-employer-execution-marathon.ts) is an offline seed script, not HTTP-reachable. No Django model exists for this table.",
    supportingCapability: ["app/api/employer-execution/payroll-runs/[id]/route.ts","app/api/employer-execution/remittance-runs/route.ts"],
    requiredRuntimePrivileges: ["SELECT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "exit_interview_documents",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01 (round 6, Phase-3A priority tranche): direct NOT NULL organization_id column, reachable via live HTTP route(s) app/api/exit-interviews/[id]/documents/route.ts. org-scoped exit-interview document attachment endpoint; SELECT+INSERT confirmed. Minimum runtime privilege set from confirmed DML verbs (crudRoutes handler destructuring and/or direct .insert/.update/.delete/.select call-site evidence), not defaulted to FULL_DML.",
    supportingCapability: ["app/api/exit-interviews/[id]/documents/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "external_communication_files",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CORRECTED round 40 (structural correction): reachable via the approved Slack and Microsoft Teams adapters (lib/integrations/adapters/communication/{slack,teams}-adapter.ts), both control-plane-approved (lib/integrations/provider-policy.ts) and invoked only through app/api/integrations/framework/[id]/sync/route.ts, which is withApi-authenticated and derives organizationId from the caller before SyncEngine executes. Matches the sibling external_communication_channels/external_communication_users classification (same adapters, same reachability path).",
    supportingCapability: ["app/api/integrations/framework/route.ts","app/api/integrations/framework/[id]/sync/route.ts","lib/integrations/control-plane.ts","lib/integrations/sync-engine.ts","lib/integrations/adapters/communication/slack-adapter.ts","lib/integrations/adapters/communication/teams-adapter.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "external_document_files",
    classification: "CONTAINED_NO_AUTHORITY",
    reason: "CORRECTED round 40 (structural correction): sole non-test reference is lib/integrations/adapters/documents/sharepoint-adapter.ts. SharePoint has ZERO entry in lib/integrations/registry.ts and ZERO entry in lib/integrations/provider-policy.ts (the control-plane authorization boundary) \u2014 app/api/integrations/framework/** rejects it at assertKnownProvider with PROVIDER_NOT_APPROVED regardless of IntegrationFactory being able to construct the adapter class. A prior pass in this same round incorrectly classified sibling tables external_document_libraries/external_document_sites as TENANT_RLS_REQUIRED by conflating factory construction capability with actual control-plane approval; that error is corrected here and in those two entries. The generated ExternalDocumentFilesViewSet in backend/core/views.py remains router-registered but unconditionally denied via DenyAllPermission (backend/core/isolation.py) \u2014 no legitimate consumer exists for this table on either the TS or Django side.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "external_document_libraries",
    classification: "CONTAINED_NO_AUTHORITY",
    reason: "CORRECTED round 40 (structural correction): the prior TENANT_RLS_REQUIRED classification cited 'the approved SharePoint adapter' \u2014 that premise is false. SharePoint has ZERO entry in lib/integrations/registry.ts (registry.isAvailable('sharepoint') === false) and ZERO entry in lib/integrations/provider-policy.ts (the control-plane authorization boundary). app/api/integrations/framework/** rejects provider=sharepoint at assertKnownProvider with PROVIDER_NOT_APPROVED before any adapter code runs; IntegrationFactory.createInstance() being ABLE to construct a SharePointAdapter is a factory capability, not control-plane approval, and does not make this table reachable. No other production caller of the sharepoint-adapter.ts module exists. The generated ExternalDocumentLibrariesViewSet in backend/core/views.py remains router-registered but unconditionally denied via DenyAllPermission \u2014 no legitimate consumer exists for this table on either the TS or Django side.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "external_document_permissions",
    classification: "CONTAINED_NO_AUTHORITY",
    reason: "CORRECTED round 40 (structural correction): sole non-test reference is lib/integrations/adapters/documents/sharepoint-adapter.ts, which has ZERO entry in lib/integrations/registry.ts and ZERO entry in lib/integrations/provider-policy.ts \u2014 unreachable through app/api/integrations/framework/**, which rejects provider=sharepoint at assertKnownProvider before any adapter code runs. The generated ExternalDocumentPermissionsViewSet in backend/core/views.py remains router-registered but unconditionally denied via DenyAllPermission \u2014 no legitimate consumer exists for this table on either the TS or Django side.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "external_document_sites",
    classification: "CONTAINED_NO_AUTHORITY",
    reason: "CORRECTED round 40 (structural correction): the prior TENANT_RLS_REQUIRED classification cited 'the approved SharePoint adapter' \u2014 that premise is false. SharePoint has ZERO entry in lib/integrations/registry.ts (registry.isAvailable('sharepoint') === false) and ZERO entry in lib/integrations/provider-policy.ts (the control-plane authorization boundary). app/api/integrations/framework/** rejects provider=sharepoint at assertKnownProvider with PROVIDER_NOT_APPROVED before any adapter code runs; IntegrationFactory.createInstance() being ABLE to construct a SharePointAdapter is a factory capability, not control-plane approval, and does not make this table reachable. The generated ExternalDocumentSitesViewSet in backend/core/views.py remains router-registered but unconditionally denied via DenyAllPermission \u2014 no legitimate consumer exists for this table on either the TS or Django side.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "icra_maturity_profiles",
    classification: "SYSTEM_ONLY",
    reason: "ICRA_PSEUDONYMOUS_NO_LOGIN=APPROVED, ASSESSMENT_ID_AS_SOLE_BEARER_AUTHORITY=REJECTED (PR #752): the pseudonymous product model is intentional, but assessmentId alone must never authorize DB access. lib/icra/assessment-capability.ts adds a hashed, purpose-bound bearer capability; every route touching an existing assessment now verifies it before entering withSystemContext. Verified 2026-09-01 (round 7, ICRA capability architecture): only reached via withSystemContext() in the capability-gated submit/profile/results/report routes. No direct organization_id column.",
    supportingCapability: ["app/api/icra/submit/route.ts","app/api/icra/[assessmentId]/submit/route.ts","app/api/icra/[assessmentId]/profile/route.ts","app/api/icra/results/[id]/route.ts","app/api/icra/report/[assessmentId]/route.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "SYSTEM_SCHEDULE",
    dbExecutionPrincipal: "SYSTEM_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "message_templates",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01, corrected 2026-09-02 (round 5 — the prior citation app/api/communications/message-templates/route.ts does not exist): direct NOT NULL organization_id column; real, verified non-test reference is app/api/communications/templates/route.ts (crudRoutes readRole member/writeRole steward), plain `db` import, no withSystemContext. (app/api/messaging/templates/route.ts is a separate 'messagingTemplates' export, out of scope for this table.)",
    supportingCapability: ["app/api/communications/templates/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "newsletter_templates",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'newsletterTemplates' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "notification_templates",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified 2026-09-02: direct NOT NULL organization_id column (db/schema/domains/communications/notifications.ts) — org-configurable templates alongside seeded system templates (isSystem flag). Reachable via lib/services/notification-service.ts, itself reachable via app/api/dues/arrears/[id]/reminder/route.ts.",
    supportingCapability: ["lib/services/notification-service.ts","app/api/dues/arrears/[id]/reminder/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "push_notification_templates",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'pushNotificationTemplates' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "report_templates",
    classification: "LATENT_UNREACHABLE",
    reason: "Verified 2026-09-01 (round 6, Phase-3A priority tranche + reachability-scan correction): reportTemplates has a real, non-duplicate union-eyes-native pgTable('report_templates', ...) declaration (db/schema/domains/analytics/reports.ts, db/schema/reports-schema.ts), but zero non-test references to it exist anywhere in app/, actions/, lib/, or services/ within apps/union-eyes proper. The original scan's supportingCapability list for this table only surfaced services/financial-service's own same-named, separately-databased table (its own drizzle.config.ts/DATABASE_URL) and MISSED the real union-eyes declaration entirely — this entry corrects that gap. No known union-eyes application code path queries this table today.",
    supportingCapability: ["db/schema/domains/analytics/reports.ts","db/schema/reports-schema.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "signature_documents",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CLOSED round 45 (RESOLVED_DEPENDENCY_FRONTIER_ROOT, DIRECT_ORG_TENANT_ROOT archetype): organization_id NOT NULL (db/schema/domains/documents/signatures.ts). Access already gated by SignatureService.verifyDocumentAccess() (sender OR signer OR same-org member) before every read/mutate in app/api/signatures/documents/route.ts (POST, organizationId trusted-derived from the authenticated user per the round-42 fix, comment preserved in code) and app/api/signatures/documents/[id]/route.ts (GET/PATCH, both call verifyDocumentAccess before use). No dual-schema conflict for signatureDocuments itself. SEVERE ADJACENT DEFECT FOUND AND FIXED this round (in document_signers, an explicitly out-of-scope PARENT_OWNED:user:NORMAL table, fixed anyway due to severity): SignatureService.recordSignature() updated documentSigners by id alone with zero check that the authenticated caller was the actual signer \u2014 a signature-forgery IDOR allowing any authenticated user to \"sign\" on behalf of any other signer. Fixed: recordSignature() now requires the signer row's own user_id to match the caller's actorUserId (external/null-userId signers are rejected pending a dedicated token-based external-signing flow, which does not yet exist). app/api/signatures/sign/route.ts updated to pass actorUserId. New test: lib/signature/__tests__/signature-service-record-signature.test.ts (4/4 passing).",
    supportingCapability: ["lib/signature/signature-service.ts","app/api/signatures/documents/route.ts","app/api/signatures/documents/[id]/route.ts","app/api/signatures/sign/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "signature_templates",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'signatureTemplates' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
    {
    table: "sms_templates",
    classification: "CONTAINED_NO_AUTHORITY",
    reason: "CLOSED round 57: services/twilio-sms-service.ts's exported functions (getSmsTemplate, renderSmsTemplate, etc.) have ZERO real callers in app/, actions/ — dead TS. SECURITY DEFECT FOUND AND FIXED THIS ROUND: notifications.SmsTemplatesViewSet was IsAuthenticated-only with no organization filter — contained via DenyAllPermission. No legitimate consumer exists. Satisfies CONTAINED_NO_AUTHORITY.",
    supportingCapability: ["services/twilio-sms-service.ts","backend/notifications/views.py"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "arbitrator_profiles",
    classification: "CONTAINED_NO_AUTHORITY",
    reason: "CLOSED round 52 (NON_FINANCE_SCOPE_EXCEPTION_REMEDIATION, DIRECTORY_PROFILE family): db/schema/domains/agreements/intelligence.ts's arbitratorProfiles has no organizationId column \u2014 a global arbitrator-statistics directory (decision counts, success rates, award amounts, specializations, contactInfo/biography/credentials) with no per-union private evaluation/rate fields found (field-by-field review per round-52 doctrine section 33: all fields describe the arbitrator's own public professional profile/reputation, not any tenant's private data about them \u2014 no sensitive-internal or commercial-rate field exists to split out). REACHABILITY: lib/services/precedent-service.ts's getArbitratorProfile/updateArbitratorStats/getTopArbitrators (the ONLY code touching this table) have ZERO production callers anywhere (git-grep confirmed) \u2014 the real routes (app/api/precedents/route.ts, app/api/precedents/search/route.ts) only import listPrecedents/searchPrecedents/createPrecedent/getPrecedentStatistics/getMostCitedPrecedents/getPrecedentsByIssueType, which touch the separate arbitrationDecisions table, never arbitratorProfiles. Dead TS code. NOTE: services/financial-service/{drizzle,src/db}/schema.ts also declare a same-named table \u2014 that is a SEPARATE deployable package/database boundary (round-48 precedent), out of scope for this app's manifest. Django: backend/bargaining/views.py ArbitratorProfilesViewSet was a separate unscoped IsAuthenticated-only surface with no legitimate consumer \u2014 contained via DenyAllPermission. Satisfies CONTAINED_NO_AUTHORITY: reachable-but-denied Django, dead TS, no legitimate consumer.",
    supportingCapability: ["lib/services/precedent-service.ts","backend/bargaining/views.py"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "document_signers",
    classification: "PARENT_OWNED_RLS_REQUIRED",
    reason: "CLOSED round 54 (final non-voting parent-owned authority convergence): no organization_id column; authority derived through documentId -> signatureDocuments, CLOSED round 45 TENANT_RLS_REQUIRED (organization_id NOT NULL). RESOLVED_PARENT_READY: every reachable operation independently proven safe. INSERT: SignatureService.createSignatureRequest() (app/api/signatures/documents/route.ts POST) creates the parent signatureDocuments row first with a trusted organizationId (derived from the authenticated user, never client body per the round-42 fix), then inserts documentSigners rows scoped to that just-created document.id \u2014 no client-suppliable parent-injection surface exists. SELECT: findFirst/findMany calls in verifyDocumentAccess()/getUserDocuments()/checkCompletion() are all scoped by an already-verified documentId or by the caller's own userId. UPDATE: recordSignature() (app/api/signatures/sign/route.ts) requires the signer row's own userId to match the authenticated actorUserId (round-45 signature-forgery IDOR fix, re-verified unchanged this round); syncDocumentStatus() (reached only via getDocumentStatus(), itself only reached after app/api/signatures/documents/[id]/route.ts's GET/PATCH call verifyDocumentAccess()) updates rows scoped to the already access-verified documentId. No DELETE path exists anywhere. sendReminder(signerId) has zero real callers (dead code) \u2014 flagged, not fixed, since unreachable. Django DocumentSignersViewSet already CONTAINED round 45 (Round40DenyAllPermission) with no legitimate consumer. No raw-SQL references found.",
    supportingCapability: ["lib/signature/signature-service.ts","app/api/signatures/documents/route.ts","app/api/signatures/documents/[id]/route.ts","app/api/signatures/sign/route.ts","backend/content/views.py"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "pending_profiles",
    classification: "GLOBAL_REFERENCE_DATA",
    reason: "CLOSED round 52 (NON_FINANCE_SCOPE_EXCEPTION_REMEDIATION, PRE_AUTH_IDENTITY family): db/schema/domains/member/pending-profiles.ts's pendingProfilesTable has no organizationId AND no user_id column \u2014 a genuine pre-signup identity anchor keyed by a unique email, before any user account or org membership exists (round-52 doctrine section 41: cannot be USER_RLS_REQUIRED until a trustworthy user identity actually exists). DEFECT FOUND AND FIXED THIS ROUND: both real routes (app/api/onboarding/route.ts and its exact-duplicate alias app/api/continuity/inheritance/route.ts) used crudRoutes({orgScoped:true, readRole:'member', writeRole:'steward'}) \u2014 orgScoped is a no-op since the table has no org column, so ANY authenticated member of ANY organization could list EVERY pre-signup user's email, Whop membership id, and billing-cycle data via the collection GET. Fixed: readRole raised to 'support_agent' (a genuine PLATFORM_ELEVATED_ROLES member, see lib/api-auth-guard.ts) on both routes \u2014 matching the round-51/52 feature_flags/data_classification_policy precedent. writeRole left at 'steward' (an ordinary org role) since POST only creates a new pre-signup row and exposes no other user's data. Regression tests added: app/api/onboarding/__tests__/route.test.ts (new) and app/api/__tests__/continuity-inheritance.route.test.ts (updated) both assert readRole:'support_agent', never 'member'. RESIDUAL NOTE (documented, not fixed \u2014 unreachable in production): actions/pending-profiles-actions.ts (getPendingProfileByEmailAction/getUnclaimedPendingProfilesAction/markPendingProfileAsClaimedAction/deletePendingProfileAction) and actions/whop-actions.ts's claimPendingProfile all have ZERO real callers anywhere (git-grep confirmed \u2014 only test files invoke claimPendingProfile); claimPendingProfile itself is otherwise well-authorized (verifies authedUserId===userId, rejects claiming an already-claimed profile by a different user, optional token check) but relies on email alone to locate the target row, which round-52 doctrine section 42 flags as insufficient standalone authority \u2014 harmless today only because the whole call path is dead code. Django: backend/auth_core/views.py PendingProfilesViewSet was a separate unscoped IsAuthenticated-only surface with no legitimate consumer \u2014 contained via DenyAllPermission.",
    supportingCapability: ["app/api/continuity/inheritance/route.ts","app/api/onboarding/route.ts","app/api/onboarding/__tests__/route.test.ts","backend/auth_core/views.py"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "MIXED",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "pricing_template_modules",
    classification: "LATENT_UNREACHABLE",
    reason: "CLOSED (round 50, state-machine root and fan-out cascade authority): child of pricing_templates via templateId FK, same services/platform-economics/pricing-template-service.ts (611 lines). Exhaustive grep across app/, actions/, lib/, services/ confirms ZERO real callers of any exported function that touches this table (createTemplate, getTemplate, listTemplates, updateTemplate, addTemplateModule, instantiateTemplate, seedDefaultTemplates, seedGtmTemplates) outside the service file itself and its own barrel re-export in services/platform-economics/index.ts (not a real usage). No Django exposure found.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "pricing_templates",
    classification: "LATENT_UNREACHABLE",
    reason: "CLOSED (round 50, state-machine root and fan-out cascade authority): services/platform-economics/pricing-template-service.ts (611 lines) exports createTemplate, getTemplate, listTemplates, updateTemplate, addTemplateModule, instantiateTemplate(organizationId,...) (its only tenant-touching function, creates subscriptionPlans+orgSubscriptions from a template), seedDefaultTemplates, seedGtmTemplates. Exhaustive grep across app/, actions/, lib/, services/ confirms ZERO real callers of any of these functions outside the service file itself and a barrel re-export in services/platform-economics/index.ts (not a real usage). No organizationId column on the table itself (genuine platform/global config, not tenant-owned) and no Django exposure. Root of the pricing_template_modules/pricing_discount_rules/pricing_regional_deployments cascade, all closed identically this round.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "profiles",
    classification: "USER_RLS_REQUIRED",
    reason: "CLOSED round 56 (USER_PRIVATE_RESOURCE archetype, identity root — treated per rule 19 as a security root): profilesTable is a per-user SaaS billing/subscription profile (Stripe/Whop membership, credits, no organization_id column at all) with NATIVE PostgreSQL RLS already enabled directly in the schema (db/schema/domains/member/profiles.ts: `ALTER TABLE ... ENABLE ROW LEVEL SECURITY` + an \"own profile only\" policy keyed on `current_setting('app.current_user_id')`, set via withRLSContext()). app/api/members/me/route.ts is crudRoutes()-backed with orgScoped:true, which is a no-op for this table (no organization_id column) — the real enforcement is the table's own native RLS policy, not the API layer. REVIEWED, NOT CHANGED: the route does not additionally restrict writes to the caller's own row at the API layer (no ownerColumn), meaning a steward could in principle create/update another user's profile row through this route; native RLS still prevents a non-privileged member from reading anyone else's row. Flagged for a future tranche to confirm whether steward-managed profile writes are an intended capability.",
    supportingCapability: ["app/api/members/me/route.ts","app/api/profile/roles/route.ts","lib/payment-processor/examples/refactored-dues-payment-route.ts","lib/utils/member-data-utils.ts"],
    requiredRuntimePrivileges: ["SELECT", "INSERT", "UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "swiss_cold_storage",
    classification: "CONTAINED_NO_AUTHORITY",
    reason: "CLOSED round 51 (GLOBAL_REFERENCE_AND_SHARED_CONFIGURATION_SCOPE_AUTHORITY, no-org candidate universe): sole TS consumer(s) services/break-glass-service.ts, services/force-majeure-integration.ts have zero production importers anywhere in app/, actions/, lib/, services/ outside their own test files (git-grep confirmed) — dead TS code, no legitimate consumer on the TypeScript side. The generated Django ViewSet(s) in backend/compliance/views.py exposed queryset=Model.objects.all() + IsAuthenticated-only with NO organization filter of any kind. Contained this round via DenyAllPermission in backend/compliance/views.py. Satisfies CONTAINED_NO_AUTHORITY: reachable-but-denied Django, dead TS, no legitimate consumer.",
    supportingCapability: ["services/break-glass-service.ts","services/force-majeure-integration.ts","backend/compliance/views.py"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
    {
    table: "transfer_pricing_documentation",
    classification: "CONTAINED_NO_AUTHORITY",
    reason: "CLOSED round 57: same dead TransferPricingService class as bank_of_canada_rates. SECURITY DEFECT FOUND AND FIXED THIS ROUND: billing.TransferPricingDocumentationViewSet was IsAuthenticated-only with no organization filter — contained via SharedDenyAllPermission. No legitimate consumer exists. Satisfies CONTAINED_NO_AUTHORITY.",
    supportingCapability: ["services/transfer-pricing-service.ts","backend/billing/views.py"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
]
