/**
 * db/rls-storage-authority/finance.ts
 *
 * PR #752 round 9: extracted from the single-file
 * db/rls-storage-authority-manifest.ts (which exceeded the repository's
 * 8000-line hard cap at 8009 lines — see
 * tooling/contract-tests/file-size-enforcement.test.ts) into semantic
 * domain modules. This module owns: Billing, payments, dues, payroll, pension, finance.
 *
 * Domain boundaries were assigned mechanically by table-name keyword
 * matching against the entry's `table` field (see the one-time migration
 * script referenced in the round-9 commit message) — every entry's DATA
 * (classification, reason, privileges, authority) is unchanged from the
 * pre-split manifest; only its physical file location changed. Do not
 * hand-edit an entry's domain placement without also checking
 * db/__tests__/rls-storage-authority-registry-composition.test.ts, which
 * proves the composed registry is unaffected by which module an entry
 * lives in.
 *
 * Add NEW entries to whichever domain module most closely matches the
 * table's real subject matter; when genuinely ambiguous, prefer
 * reference-latent.ts (the catch-all) over forcing a bad fit elsewhere.
 */
import type { StorageAuthorityEntry } from './types';

export const financeEntries: StorageAuthorityEntry[] = [
  {
    table: "account_mappings",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'accountMappings' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["services/clc/chart-of-accounts.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "ai_budgets",
    classification: "NEEDS_REVIEW",
    reason: "2 non-test reference(s) to 'aiBudgets' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/ai/services/cost-tracking-wrapper.ts","lib/ai/services/rate-limiter.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "bank_accounts",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'bankAccounts' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "bank_reconciliation",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'bankReconciliation' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "bank_reconciliations",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'bankReconciliations' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "billing_accounts",
    classification: "NEEDS_REVIEW",
    reason: "3 non-test reference(s) to 'billingAccounts' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/payments/webhooks/stripe/route.ts","app/api/pilot/apply/[id]/commercial-transition/route.ts","services/platform-economics/billing-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "billing_adjustments",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'billingAdjustments' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "billing_invoices",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'billingInvoices' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "billing_payments",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'billingPayments' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "billing_periods",
    classification: "NEEDS_REVIEW",
    reason: "4 non-test reference(s) to 'billingPeriods' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/billing/send-batch/route.ts","app/api/dues/billing-cycle/route.ts","services/platform-economics/allocation-engine.ts","services/platform-economics/billing-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "billing_subscriptions",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'billingSubscriptions' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/dues/billing-cycle/route.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "budget_pool",
    classification: "NEEDS_REVIEW",
    reason: "RECLASSIFIED 2026-09-02 (round 7, raw-SQL LATENT-detection correction): this table was previously classified LATENT_UNREACHABLE based on a Drizzle-EXPORT-NAME-only reachability scan, which cannot find raw SQL references. A raw-SQL detection pass (see db/__tests__/rls-storage-authority-manifest-raw-sql-latent.test.ts for the detector/fixture) found real, direct raw-SQL table references (db.execute(sql`... FROM/INTO/UPDATE budget_pool ...`) or an equivalent quoted-table-name repository reference) in the file(s) listed below. Full HTTP-reachability/auth-boundary trace not yet completed.",
    supportingCapability: ["lib/ai/financial-insights.ts","app/api/finance/summary/route.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "chart_of_accounts",
    classification: "NEEDS_REVIEW",
    reason: "2 non-test reference(s) to 'chartOfAccounts' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/services/general-ledger-service.ts","services/clc/chart-of-accounts.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "clc_remittance_mapping",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'clcRemittanceMapping' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "cost_centers",
    classification: "NEEDS_REVIEW",
    reason: "RECLASSIFIED 2026-09-02 (round 7, raw-SQL LATENT-detection correction): this table was previously classified LATENT_UNREACHABLE based on a Drizzle-EXPORT-NAME-only reachability scan, which cannot find raw SQL references. A raw-SQL detection pass (see db/__tests__/rls-storage-authority-manifest-raw-sql-latent.test.ts for the detector/fixture) found real, direct raw-SQL table references (db.execute(sql`... FROM/INTO/UPDATE cost_centers ...`) or an equivalent quoted-table-name repository reference) in the file(s) listed below. Full HTTP-reachability/auth-boundary trace not yet completed.",
    supportingCapability: ["services/platform-economics/finance-outputs.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "donation_receipts",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'donationReceipts' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "donations",
    classification: "NEEDS_REVIEW",
    reason: "32 non-test reference(s) to 'donations' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["services/clc/chart-of-accounts.ts","services/clc/compliance-reports.ts","services/financial-service/IMPLEMENTATION_COMPLETE.md","services/financial-service/STRIPE_INTEGRATION_COMPLETE.md","services/financial-service/STRIPE_TESTING.md","services/financial-service/TESTING_STATUS.md","services/financial-service/WEEK_12_TESTING_ISSUES.md","services/financial-service/add-missing-tables.sql","services/financial-service/add-missing-tables.ts","services/financial-service/check-donations.ts","services/financial-service/check-tables.ts","services/financial-service/drizzle/0000_lucky_mole_man.sql","services/financial-service/drizzle/meta/0000_snapshot.json","services/financial-service/drizzle/schema.ts","services/financial-service/setup-stripe-testing.ps1","services/financial-service/src/db/schema.ts","services/financial-service/src/index.ts","services/financial-service/src/middleware/idempotency.ts","services/financial-service/src/routes/analytics.ts","services/financial-service/src/routes/donations.ts","services/financial-service/src/routes/payments.ts","services/financial-service/src/services/burn-rate-predictor.ts","services/financial-service/src/services/payment-processing.ts","services/financial-service/src/services/reconciliation-engine.ts","services/financial-service/start-webhook-listener.ps1","services/financial-service/test-analytics.ps1","services/financial-service/test-donations.ps1","services/financial-service/test-payments-quick.ps1","services/financial-service/test-payments-simple.ps1","services/financial-service/test-payments.ps1","services/financial-service/test-webhook-locally.ps1","services/financial-service/validate-setup.ps1"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "dues_assignments",
    classification: "NEEDS_REVIEW",
    reason: "RECLASSIFIED 2026-09-02 (round 7, raw-SQL LATENT-detection correction): this table was previously classified LATENT_UNREACHABLE based on a Drizzle-EXPORT-NAME-only reachability scan, which cannot find raw SQL references. A raw-SQL detection pass (see db/__tests__/rls-storage-authority-manifest-raw-sql-latent.test.ts for the detector/fixture) found real, direct raw-SQL table references (db.execute(sql`... FROM/INTO/UPDATE dues_assignments ...`) or an equivalent quoted-table-name repository reference) in the file(s) listed below. Full HTTP-reachability/auth-boundary trace not yet completed.",
    supportingCapability: ["lib/report-executor.ts","app/[locale]/dashboard/data-source/page.tsx"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "dues_policies",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'duesPolicies' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "dues_rates",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'duesRates' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "dues_transactions",
    classification: "NEEDS_REVIEW",
    reason: "25 non-test reference(s) to 'duesTransactions' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/members/dues/route.ts","lib/dues-calculation-engine.ts","lib/jobs/dues-reminder-scheduler.ts","lib/jobs/failed-payment-retry.ts","lib/payment-processor/IMPLEMENTATION_GUIDE.md","lib/payment-processor/README.md","lib/payment-processor/examples/refactored-dues-payment-route.ts","lib/reality/capability-registry.ts","lib/services/billing-cycle-service.ts","lib/services/dues-notifications.ts","lib/services/payment-service.ts","services/financial-service/SCHEMA_ANALYSIS.md","services/financial-service/drizzle/relations.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts","services/financial-service/src/jobs/arrears-management-workflow.ts","services/financial-service/src/jobs/dues-calculation-workflow.ts","services/financial-service/src/jobs/payment-collection-workflow.ts","services/financial-service/src/routes/analytics.ts","services/financial-service/src/routes/arrears.ts","services/financial-service/src/routes/dues-transactions.ts","services/financial-service/src/routes/remittances.ts","services/financial-service/src/services/arrears-detection.ts","services/financial-service/src/services/payment-processing.ts","services/financial-service/src/services/reconciliation-engine.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "employer_payroll_adjustments",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'employerPayrollAdjustments' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "employer_payroll_run_items",
    classification: "NEEDS_REVIEW",
    reason: "5 non-test reference(s) to 'employerPayrollRunItems' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/[locale]/dashboard/employer-execution/payroll-runs/[id]/page.tsx","app/api/employer-execution/payroll-runs/[id]/route.ts","app/api/employer-execution/payroll-runs/route.ts","app/api/employer-execution/remittance-runs/route.ts","app/api/employer-execution/replay/[runId]/route.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "employer_payroll_runs",
    classification: "NEEDS_REVIEW",
    reason: "7 non-test reference(s) to 'employerPayrollRuns' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/[locale]/dashboard/employer-execution/payroll-runs/[id]/page.tsx","app/[locale]/dashboard/employer-execution/payroll-runs/page.tsx","app/api/employer-execution/payroll-runs/[id]/route.ts","app/api/employer-execution/payroll-runs/route.ts","app/api/employer-execution/remittance-runs/route.ts","app/api/employer-execution/replay/[runId]/route.ts","lib/workers/employer-execution/process-payroll-run.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "employer_remittance_run_items",
    classification: "NEEDS_REVIEW",
    reason: "2 non-test reference(s) to 'employerRemittanceRunItems' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/employer-execution/remittance-runs/[id]/route.ts","app/api/employer-execution/remittance-runs/route.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "employer_remittance_runs",
    classification: "NEEDS_REVIEW",
    reason: "5 non-test reference(s) to 'employerRemittanceRuns' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/[locale]/dashboard/employer-execution/remittance-runs/[id]/page.tsx","app/[locale]/dashboard/employer-execution/remittance-runs/page.tsx","app/api/employer-execution/remittance-runs/[id]/route.ts","app/api/employer-execution/remittance-runs/route.ts","lib/workers/employer-execution/process-remittance-run.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "employer_remittances",
    classification: "NEEDS_REVIEW",
    reason: "12 non-test reference(s) to 'employerRemittances' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/dues/dashboard/route.ts","app/api/dues/exceptions/route.ts","app/api/dues/reconciliation/queue/route.ts","app/api/dues/remittances/[id]/route.ts","app/api/dues/remittances/route.ts","app/api/dues/remittances/upload/route.ts","lib/services/dashboard-kpi-service.ts","lib/services/payroll-integration-service.ts","services/financial-service/drizzle/relations.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts","services/financial-service/src/routes/remittances.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "entitlement_usage_log",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'entitlementUsageLog' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["services/platform-economics/contract-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "erp_invoices",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'erpInvoices' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "financial_periods",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'financialPeriods' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/finance/summary/route.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "gl_account_mappings",
    classification: "NEEDS_REVIEW",
    reason: "RECLASSIFIED 2026-09-02 (round 7, raw-SQL LATENT-detection correction): this table was previously classified LATENT_UNREACHABLE based on a Drizzle-EXPORT-NAME-only reachability scan, which cannot find raw SQL references. A raw-SQL detection pass (see db/__tests__/rls-storage-authority-manifest-raw-sql-latent.test.ts for the detector/fixture) found real, direct raw-SQL table references (db.execute(sql`... FROM/INTO/UPDATE gl_account_mappings ...`) or an equivalent quoted-table-name repository reference) in the file(s) listed below. Full HTTP-reachability/auth-boundary trace not yet completed.",
    supportingCapability: ["services/platform-economics/finance-outputs.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "gl_transaction_log",
    classification: "LATENT_UNREACHABLE",
    reason: "Manually verified 2026-09-02: sole non-test reference lib/services/general-ledger-service.ts has zero callers anywhere under app/, actions/, lib/, services/, scripts/ (verified by name-search).",
    supportingCapability: ["lib/services/general-ledger-service.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "gl_trial_balance",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'glTrialBalance' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/services/general-ledger-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "payment_cycles",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'paymentCycles' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "payment_disputes",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'paymentDisputes' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "payment_methods",
    classification: "NEEDS_REVIEW",
    reason: "3 non-test reference(s) to 'paymentMethods' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/dues/payment-methods/route.ts","lib/payment-processor/processors/stripe-processor.ts","lib/utils/autopay-utils.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "payment_plans",
    classification: "NEEDS_REVIEW",
    reason: "4 non-test reference(s) to 'paymentPlans' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/dues/payment-plans/route.ts","app/api/finance/summary/route.ts","lib/ai/financial-insights.ts","lib/api/index.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "payments",
    classification: "NEEDS_REVIEW",
    reason: "95 non-test reference(s) to 'payments' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/[locale]/dashboard/admin/dues/page.tsx","app/[locale]/dashboard/admin/dues/payments/[id]/page.tsx","app/[locale]/dashboard/admin/dues/payments/page.tsx","app/[locale]/dashboard/billing-admin/page.tsx","app/[locale]/dashboard/clc/page.tsx","app/[locale]/dashboard/dues/pay/[transactionId]/page.tsx","app/[locale]/dashboard/finance/invoices/[id]/page.tsx","app/api/admin/dues/overview/route.ts","app/api/admin/payments/retry-failed/route.ts","app/api/finance/invoices/[id]/payments/route.ts","app/api/finance/per-capita/inbound/route.ts","app/api/finance/summary/route.ts","app/api/icra/checkout/route.ts","app/api/payments/checkout/create/route.ts","app/api/payments/webhooks/paypal/route.ts","app/api/payments/webhooks/stripe/route.ts","app/api/portal/dues/balance/route.ts","app/api/portal/dues/pay/route.ts","app/api/whop/unauthenticated-checkout/route.ts","app/api/workbook/checkout/route.ts","lib/ai/role-templates.ts","lib/api-auth-guard.ts","lib/api/deprecation.ts","lib/feature-flags.ts","lib/gdpr/consent-manager.ts","lib/integrations/README.md","lib/integrations/adapters/accounting/PHASE_3_COMPLETE.md","lib/integrations/adapters/accounting/freshbooks-adapter.ts","lib/integrations/adapters/accounting/freshbooks-client.ts","lib/integrations/adapters/accounting/quickbooks-adapter.ts","lib/integrations/adapters/accounting/quickbooks-client.ts","lib/integrations/adapters/accounting/sage-intacct-adapter.ts","lib/integrations/adapters/accounting/sage-intacct-client.ts","lib/integrations/adapters/accounting/sync-utils.ts","lib/integrations/adapters/accounting/wave-adapter.ts","lib/integrations/adapters/accounting/wave-client.ts","lib/integrations/adapters/accounting/xero-adapter.ts","lib/integrations/adapters/accounting/xero-client.ts","lib/integrations/registry.ts","lib/jobs/dues-reminder-scheduler.ts","lib/jobs/failed-payment-retry.ts","lib/middleware/auth-middleware.ts","lib/notification-templates/dues-notifications.ts","lib/observability/metrics.ts","lib/payment-processor/IMPLEMENTATION_GUIDE.md","lib/payment-processor/README.md","lib/payment-processor/processors/paypal-processor.ts","lib/payment-processor/processors/square-processor.ts","lib/payment-processor/processors/stripe-processor.ts","lib/payment-processor/processors/whop-processor.ts","lib/public-routes.ts","lib/rate-limiter.ts","lib/reality/capability-registry.ts","lib/receipt-generator.ts","lib/services/feature-flags-service.ts","lib/services/financial-email-service.ts","lib/services/payment-notifications.ts","lib/services/payment-service.ts","lib/services/payroll-integration-service.ts","lib/services/strike-fund-tax-service.ts","lib/stripe-elements.ts","lib/stripe.ts","lib/ui-tooltips.ts","services/clc/compliance-reports.ts","services/financial-service/REMITTANCE_PROCESSING.md","services/financial-service/SCHEMA_ANALYSIS.md","services/financial-service/STRIPE_INTEGRATION_COMPLETE.md","services/financial-service/STRIPE_TESTING.md","services/financial-service/TESTING_STATUS.md","services/financial-service/WEEK_12_TESTING_ISSUES.md","services/financial-service/WEEK_5_6_IMPLEMENTATION.md","services/financial-service/add-missing-tables.sql","services/financial-service/src/db/schema-platform-economics.ts","services/financial-service/src/db/schema.ts","services/financial-service/src/index.ts","services/financial-service/src/jobs/arrears-management-workflow.ts","services/financial-service/src/jobs/payment-collection-workflow.ts","services/financial-service/src/jobs/stipend-processing-workflow.ts","services/financial-service/src/middleware/idempotency.ts","services/financial-service/src/routes/donations.ts","services/financial-service/src/routes/payments.ts","services/financial-service/src/routes/remittances.ts","services/financial-service/src/services/arrears-detection.ts","services/financial-service/src/services/financial-reports.ts","services/financial-service/src/services/financial-reports.ts.broken","services/financial-service/src/services/payment-processing.ts","services/financial-service/src/services/reconciliation-engine.ts","services/financial-service/test-arrears.ps1","services/financial-service/test-donations.ps1","services/financial-service/test-payments-quick.ps1","services/financial-service/test-payments-simple.ps1","services/financial-service/test-payments.ps1","services/platform-economics/billing-service.ts","services/platform-economics/reconciliation-service.ts","services/whiplash-prevention-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "payroll_deductions",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'payrollDeductions' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/dues/deductions/route.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "pension_contributions",
    classification: "NEEDS_REVIEW",
    reason: "5 non-test reference(s) to 'pensionContributions' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/pension/contributions/route.ts","lib/ai/pension-intelligence.ts","services/financial-service/drizzle/relations.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "pension_plans",
    classification: "NEEDS_REVIEW",
    reason: "6 non-test reference(s) to 'pensionPlans' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/pension/plans/[id]/route.ts","app/api/pension/plans/route.ts","lib/ai/pension-intelligence.ts","services/financial-service/drizzle/relations.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "pension_t4a_records",
    classification: "NEEDS_REVIEW",
    reason: "2 non-test reference(s) to 'pensionT4aRecords' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/pension/t4a/route.ts","app/api/tax/t4a/route.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "pension_trustee_meetings",
    classification: "NEEDS_REVIEW",
    reason: "5 non-test reference(s) to 'pensionTrusteeMeetings' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/pension/trustee-meetings/[id]/route.ts","app/api/pension/trustee-meetings/route.ts","services/financial-service/drizzle/relations.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "pension_trustees",
    classification: "NEEDS_REVIEW",
    reason: "5 non-test reference(s) to 'pensionTrustees' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/pension/trustees/[id]/route.ts","app/api/pension/trustees/route.ts","services/financial-service/drizzle/relations.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "per_capita_remittances",
    classification: "NEEDS_REVIEW",
    reason: "24 non-test reference(s) to 'perCapitaRemittances' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/[locale]/dashboard/clc/page.tsx","app/[locale]/dashboard/clc/staff/page.tsx","app/[locale]/dashboard/federation/page.tsx","app/api/arrears/case/[memberId]/route.ts","app/api/arrears/cases/route.ts","app/api/arrears/create-payment-plan/route.ts","app/api/arrears/escalate/[caseId]/route.ts","app/api/arrears/log-contact/route.ts","app/api/arrears/resolve/[caseId]/route.ts","app/api/healthwelfare/plans/route.ts","app/api/tax/cope/receipts/route.ts","app/api/tax/cra/export/route.ts","app/api/tax/rl-1/generate/route.ts","app/api/tax/slips/route.ts","app/api/tax/t106/route.ts","lib/graphql/resolvers.ts","services/clc/compliance-reports.ts","services/clc/per-capita-calculator.ts","services/clc/remittance-audit.ts","services/clc/remittance-export.ts","services/clc/remittance-notifications.ts","services/financial-service/drizzle/relations.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "platform_cost_ledger_entries",
    classification: "NEEDS_REVIEW",
    reason: "3 non-test reference(s) to 'platformCostLedgerEntries' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/reality/capability-registry.ts","services/platform-economics/allocation-engine.ts","services/platform-economics/ledger-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "platform_invoices",
    classification: "NEEDS_REVIEW",
    reason: "4 non-test reference(s) to 'platformInvoices' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/dues/late-fees/route.ts","app/api/pilot/apply/[id]/commercial-transition/route.ts","services/platform-economics/billing-service.ts","services/platform-economics/reconciliation-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "platform_payments",
    classification: "NEEDS_REVIEW",
    reason: "4 non-test reference(s) to 'platformPayments' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/payments/webhooks/stripe/route.ts","lib/reality/capability-registry.ts","services/platform-economics/billing-service.ts","services/platform-economics/reconciliation-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "reconciliation_exceptions",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'reconciliationExceptions' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["services/platform-economics/reconciliation-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "reconciliation_runs",
    classification: "NEEDS_REVIEW",
    reason: "2 non-test reference(s) to 'reconciliationRuns' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/reconciliation/bank/route.ts","services/platform-economics/reconciliation-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "remittance_exceptions",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'remittanceExceptions' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/services/payroll-integration-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "remittance_line_items",
    classification: "NEEDS_REVIEW",
    reason: "7 non-test reference(s) to 'remittanceLineItems' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/dues/dashboard/route.ts","app/api/dues/exceptions/route.ts","app/api/dues/reconciliation/auto-match/route.ts","app/api/dues/reconciliation/match/route.ts","app/api/dues/reconciliation/queue/route.ts","app/api/dues/reconciliation/reject/route.ts","lib/services/payroll-integration-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "reward_budget_envelopes",
    classification: "NEEDS_REVIEW",
    reason: "3 non-test reference(s) to 'rewardBudgetEnvelopes' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["app/[locale]/dashboard/admin/rewards/analytics/page.tsx","lib/services/rewards/budget-service.ts","lib/services/rewards/export-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "reward_wallet_ledger",
    classification: "NEEDS_REVIEW",
    reason: "5 non-test reference(s) to 'rewardWalletLedger' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["app/[locale]/dashboard/admin/rewards/analytics/page.tsx","lib/services/rewards/export-service.ts","lib/services/rewards/notification-service.ts","lib/services/rewards/wallet-service.ts","lib/utils/rewards-stats-utils.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "social_accounts",
    classification: "NEEDS_REVIEW",
    reason: "4 non-test reference(s) to 'socialAccounts' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/social-media/accounts/route.ts","app/api/social-media/analytics/route.ts","app/api/social-media/posts/route.ts","lib/social-media/social-media-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "subscription_events_log",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified 2026-09-02: direct NOT NULL organization_id column (db/schema/domains/finance/dunning.ts). Reachable via services/platform-economics/subscription-lifecycle-service.ts, which is called from app/api/billing/credits/check-expired/route.ts. The sibling reference services/platform-economics/dunning-service.ts has zero independent callers but shares the same table via the reachable lifecycle service.",
    supportingCapability: ["services/platform-economics/subscription-lifecycle-service.ts","app/api/billing/credits/check-expired/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "union_dues_receipts",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'unionDuesReceipts' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "union_dues_year_end",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'unionDuesYearEnd' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "account_balance_reconciliation",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'accountBalanceReconciliation' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["services/whiplash-prevention-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "billing_terms",
    classification: "LATENT_UNREACHABLE",
    reason: "Round-7 scope-expansion scan: zero references to the 'billingTerms' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files via a combined ripgrep pass across app/, actions/, lib/, services/. No known application code path queries this table today. NOT yet individually checked for raw-SQL (non-Drizzle-symbol) references to the physical table name — see the raw-SQL LATENT fixture test for why that check matters before this can be treated as final.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "budget_reservations",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'budgetReservations' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/services/rewards/budget-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "clc_chart_of_accounts",
    classification: "NEEDS_REVIEW",
    reason: "2 non-test reference(s) to 'clcChartOfAccounts' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "federation_remittances",
    classification: "LATENT_UNREACHABLE",
    reason: "Round-7 scope-expansion scan: zero references to the 'federationRemittances' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files via a combined ripgrep pass across app/, actions/, lib/, services/. No known application code path queries this table today. NOT yet individually checked for raw-SQL (non-Drizzle-symbol) references to the physical table name — see the raw-SQL LATENT fixture test for why that check matters before this can be treated as final.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "payment_allocations",
    classification: "NEEDS_REVIEW",
    reason: "3 non-test reference(s) to 'paymentAllocations' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/integrations/adapters/accounting/sync-utils.ts","services/platform-economics/billing-service.ts","services/platform-economics/reconciliation-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "payment_classification_policy",
    classification: "LATENT_UNREACHABLE",
    reason: "Round-7 scope-expansion scan: zero references to the 'paymentClassificationPolicy' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files via a combined ripgrep pass across app/, actions/, lib/, services/. No known application code path queries this table today. NOT yet individually checked for raw-SQL (non-Drizzle-symbol) references to the physical table name — see the raw-SQL LATENT fixture test for why that check matters before this can be treated as final.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "payment_routing_rules",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'paymentRoutingRules' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["services/whiplash-prevention-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "platform_invoice_line_items",
    classification: "NEEDS_REVIEW",
    reason: "2 non-test reference(s) to 'platformInvoiceLineItems' found (round-7 scope-expansion scan). At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/pilot/apply/[id]/commercial-transition/route.ts","services/platform-economics/billing-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "reconciliation_matches",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'reconciliationMatches' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["services/platform-economics/reconciliation-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "remittance_approvals",
    classification: "NEEDS_REVIEW",
    reason: "2 non-test reference(s) to 'remittanceApprovals' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["app/[locale]/dashboard/clc/staff/page.tsx","services/clc/remittance-audit.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "rl1_tax_slips",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'rl1TaxSlips' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["services/tax-slip-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "separated_payment_transactions",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'separatedPaymentTransactions' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["services/whiplash-prevention-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "strike_fund_disbursements",
    classification: "NEEDS_REVIEW",
    reason: "3 non-test reference(s) to 'strikeFundDisbursements' found (round-7 scope-expansion scan). At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/strike-fund/dashboard/route.ts","lib/services/strike-fund-tax-service.ts","services/tax-slip-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "stripe_connect_accounts",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'stripeConnectAccounts' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["services/whiplash-prevention-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "subscription_plans",
    classification: "NEEDS_REVIEW",
    reason: "3 non-test reference(s) to 'subscriptionPlans' found (round-7 scope-expansion scan). At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/pilot/apply/[id]/commercial-transition/route.ts","services/platform-economics/billing-service.ts","services/platform-economics/pricing-template-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "t4a_tax_slips",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 't4aTaxSlips' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["services/tax-slip-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "tax_year_end_processing",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'taxYearEndProcessing' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["services/tax-slip-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
]
