/**
 * db/rls-storage-authority/finance.ts
 *
 * PR #752 round 9: extracted from the single-file
 * db/rls-storage-authority-manifest.ts (which exceeded the repository's
 * 8000-line hard cap at 8009 lines — see
 * tooling/contract-tests/file-size-enforcement.test.ts) into semantic
 * domain modules. This module owns: Billing, payments, dues, payroll, pension, finance.
 *
 * Domain boundaries were assigned mechanically by table-name keyword
 * matching against the entry's `table` field (see the one-time migration
 * script referenced in the round-9 commit message) — every entry's DATA
 * (classification, reason, privileges, authority) is unchanged from the
 * pre-split manifest; only its physical file location changed. Do not
 * hand-edit an entry's domain placement without also checking
 * db/__tests__/rls-storage-authority-registry-composition.test.ts, which
 * proves the composed registry is unaffected by which module an entry
 * lives in.
 *
 * Add NEW entries to whichever domain module most closely matches the
 * table's real subject matter; when genuinely ambiguous, prefer
 * reference-latent.ts (the catch-all) over forcing a bad fit elsewhere.
 */
import type { StorageAuthorityEntry } from './types';

export const financeEntries: StorageAuthorityEntry[] = [
  {
    table: "account_mappings",
    classification: "GLOBAL_REFERENCE_DATA",
    reason: "Manually verified (2026-09-04, finance.ts round 1): organization_id column exists but is NULLABLE (db/schema/domains/financial/chart-of-accounts.ts) — null rows are shared/global transaction-type-to-GL-account templates, non-null rows are per-org overrides. Only consumer is services/clc/chart-of-accounts.ts, reachable via app/api/admin/clc/analytics/* routes (all gated by withRoleAuth('admin')) and app/api/finance/per-capita/inbound/route.ts / app/api/cron/monthly-per-capita/route.ts. Uses the plain `db` import (no withSystemContext), so dbExecutionPrincipal is TENANT_RUNTIME despite the platform-admin-level invocation.",
    supportingCapability: ["services/clc/chart-of-accounts.ts"],
    requiredRuntimePrivileges: ["SELECT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "PLATFORM_ADMIN",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "ai_budgets",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified (2026-09-04, finance.ts round 1): organization_id column present (db/schema/domains/ml/chatbot.ts). Reachable via lib/ai/services/rate-limiter.ts and lib/ai/services/cost-tracking-wrapper.ts, both invoked from tenant-facing routes (app/api/social-media/posts, /accounts, /campaigns, /analytics, app/api/chatbot/messages) as an AI-usage cost/rate guard per organization.",
    supportingCapability: ["lib/ai/services/cost-tracking-wrapper.ts","lib/ai/services/rate-limiter.ts"],
    requiredRuntimePrivileges: ["SELECT", "INSERT", "UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "bank_accounts",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'bankAccounts' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "bank_reconciliation",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'bankReconciliation' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "bank_reconciliations",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'bankReconciliations' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "billing_accounts",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified (2026-09-04, finance.ts round 1): direct NOT NULL, UNIQUE organization_id column (db/schema/domains/finance/platform-billing.ts). Reachable via app/api/payments/webhooks/stripe/route.ts (Stripe webhook, signature-verified, resolves the org from webhook metadata via resolveBillingAccountId(organizationId), executes part of its logic under withSystemContext()) and app/api/pilot/apply/[id]/commercial-transition/route.ts (locked pilot control-plane code — referenced here only as a supportingCapability, not reopened by this pass).",
    supportingCapability: ["app/api/payments/webhooks/stripe/route.ts","app/api/pilot/apply/[id]/commercial-transition/route.ts","services/platform-economics/billing-service.ts"],
    requiredRuntimePrivileges: ["SELECT", "INSERT", "UPDATE"],
    requiredSystemPrivileges: ["SELECT"],
    invocationAuthority: "MIXED",
    dbExecutionPrincipal: "MIXED",
    reviewPriority: "NONE",
  },
  {
    table: "billing_adjustments",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'billingAdjustments' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "billing_invoices",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'billingInvoices' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "billing_payments",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'billingPayments' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "billing_periods",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified (2026-09-04, finance.ts round 1): direct NOT NULL organization_id column (db/schema/domains/finance/platform-billing.ts). Reachable via app/api/dues/billing-cycle/route.ts (minRole 'officer', `where(eq(billingPeriods.organizationId, organizationId))`) and app/api/billing/send-batch/route.ts.",
    supportingCapability: ["app/api/billing/send-batch/route.ts","app/api/dues/billing-cycle/route.ts","services/platform-economics/allocation-engine.ts","services/platform-economics/billing-service.ts"],
    requiredRuntimePrivileges: ["SELECT", "INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "billing_subscriptions",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified (2026-09-04, finance.ts round 1): direct NOT NULL organization_id column — this is the 'legacy billing (console / CFO dashboard)' billingSubscriptions table in db/schema/domains/finance/platform-billing.ts, distinct from org_subscriptions used by the pilot commercial-transition flow. Reachable via app/api/dues/billing-cycle/route.ts (minRole 'officer', `where(eq(billingSubscriptions.organizationId, organizationId))`).",
    supportingCapability: ["app/api/dues/billing-cycle/route.ts"],
    requiredRuntimePrivileges: ["SELECT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "budget_pool",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified (2026-09-04, finance.ts round 1): direct NOT NULL organization_id column (varchar; db/schema/domains/infrastructure/awards.ts). Reachable via app/api/finance/summary/route.ts (minRole 'officer', org-required) and lib/ai/financial-insights.ts.",
    supportingCapability: ["lib/ai/financial-insights.ts","app/api/finance/summary/route.ts"],
    requiredRuntimePrivileges: ["SELECT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "chart_of_accounts",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified (2026-09-04, finance.ts round 1): FLAG — this table name has TWO conflicting schema-file definitions that both resolve to the same physical table: db/schema/domains/finance/accounting.ts's chartOfAccounts (organization_id NOT NULL, exported via the main @/db/schema barrel, consumer lib/services/general-ledger-service.ts which itself has zero route callers) and db/schema/domains/financial/chart-of-accounts.ts's chartOfAccounts (organization_id NULLABLE — null rows are CLC-standard national templates shared across all orgs, non-null rows are per-org customizations; consumed directly by services/clc/chart-of-accounts.ts). The latter IS reachable, via the same app/api/admin/clc/analytics/* routes (withRoleAuth('admin')) and app/api/finance/exports/route.ts (org-scoped, requireEntitlement-gated) documented for account_mappings/gl_account_mappings. This dual-definition should be consolidated in a future pass; until then this entry covers the reachable (financial/chart-of-accounts.ts) semantics.",
    supportingCapability: ["lib/services/general-ledger-service.ts","services/clc/chart-of-accounts.ts"],
    requiredRuntimePrivileges: ["SELECT", "INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "MIXED",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "clc_remittance_mapping",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'clcRemittanceMapping' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "cost_centers",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CORRECTED (2026-09-04, finance.ts round 1): the round-7 raw-SQL detection pass found this table referenced in services/platform-economics/finance-outputs.ts but could not trace reachability. Same finding as gl_account_mappings: finance-outputs.ts IS reachable via app/api/finance/exports/route.ts (organizationId required, requireEntitlement-gated). Direct NOT NULL organization_id column (db/schema/domains/finance/accounting.ts).",
    supportingCapability: ["services/platform-economics/finance-outputs.ts"],
    requiredRuntimePrivileges: ["SELECT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "donation_receipts",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'donationReceipts' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "donations",
    classification: "SEPARATE_DATABASE_BOUNDARY",
    reason: "Manually verified (2026-09-04, finance.ts round 1): direct NOT NULL organization_id column exists in this app's own schema (db/schema/domains/infrastructure/cms.ts), but the only real application-code consumer is services/financial-service/** — a separate Node service/package with its own build output and routes (services/financial-service/src/routes/donations.ts, dist/**), not this Next.js app's request-handling runtime. No route/action under app/api/ or actions/ in the union-eyes app itself queries this table directly.",
    supportingCapability: ["services/clc/chart-of-accounts.ts","services/clc/compliance-reports.ts","services/financial-service/IMPLEMENTATION_COMPLETE.md","services/financial-service/STRIPE_INTEGRATION_COMPLETE.md","services/financial-service/STRIPE_TESTING.md","services/financial-service/TESTING_STATUS.md","services/financial-service/WEEK_12_TESTING_ISSUES.md","services/financial-service/add-missing-tables.sql","services/financial-service/add-missing-tables.ts","services/financial-service/check-donations.ts","services/financial-service/check-tables.ts","services/financial-service/drizzle/0000_lucky_mole_man.sql","services/financial-service/drizzle/meta/0000_snapshot.json","services/financial-service/drizzle/schema.ts","services/financial-service/setup-stripe-testing.ps1","services/financial-service/src/db/schema.ts","services/financial-service/src/index.ts","services/financial-service/src/middleware/idempotency.ts","services/financial-service/src/routes/analytics.ts","services/financial-service/src/routes/donations.ts","services/financial-service/src/routes/payments.ts","services/financial-service/src/services/burn-rate-predictor.ts","services/financial-service/src/services/payment-processing.ts","services/financial-service/src/services/reconciliation-engine.ts","services/financial-service/start-webhook-listener.ps1","services/financial-service/test-analytics.ps1","services/financial-service/test-donations.ps1","services/financial-service/test-payments-quick.ps1","services/financial-service/test-payments-simple.ps1","services/financial-service/test-payments.ps1","services/financial-service/test-webhook-locally.ps1","services/financial-service/validate-setup.ps1"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "dues_assignments",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified (2026-09-04, finance.ts round 1): no direct HTTP CRUD route for this table (the automated scan's original file citations were the only real evidence, not app/api/members/dues/route.ts which actually queries duesTransactions, a different table). Real consumers: (1) lib/report-executor.ts — a tenant-facing ad-hoc report engine backing app/api/reports/execute/route.ts and app/api/reports/datasources/route.ts, both of which construct `new ReportExecutor(organizationId)` from the authenticated caller's own organization context (TENANT_USER, org-scoped); (2) app/[locale]/dashboard/data-source/page.tsx, a platform-level admin health dashboard gated by hasMinRole('integration_manager') that runs a raw `SELECT COUNT(*) FROM dues_assignments` under withSystemContext() — cross-org by design, but only exposes a row COUNT, not row-level data. Both paths verified directly (not merely cited).",
    supportingCapability: ["lib/report-executor.ts","app/[locale]/dashboard/data-source/page.tsx"],
    requiredRuntimePrivileges: ["SELECT"],
    requiredSystemPrivileges: ["SELECT"],
    invocationAuthority: "MIXED",
    dbExecutionPrincipal: "MIXED",
    reviewPriority: "NONE",
  },
  {
    table: "dues_policies",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'duesPolicies' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "dues_rates",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'duesRates' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "dues_transactions",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified (2026-09-04, finance.ts round 1): direct NOT NULL organization_id column (db/schema/dues-finance-schema.ts / dues.ts). Reachable via app/api/members/dues/route.ts, a crudRoutes-based collection route with orgScoped: true, readRole: 'member', writeRole: 'steward'. Caller organizationId is resolved from the authenticated session, not client-supplied.",
    supportingCapability: ["app/api/members/dues/route.ts","lib/dues-calculation-engine.ts","lib/jobs/dues-reminder-scheduler.ts","lib/jobs/failed-payment-retry.ts","lib/payment-processor/IMPLEMENTATION_GUIDE.md","lib/payment-processor/README.md","lib/payment-processor/examples/refactored-dues-payment-route.ts","lib/reality/capability-registry.ts","lib/services/billing-cycle-service.ts","lib/services/dues-notifications.ts","lib/services/payment-service.ts","services/financial-service/SCHEMA_ANALYSIS.md","services/financial-service/drizzle/relations.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts","services/financial-service/src/jobs/arrears-management-workflow.ts","services/financial-service/src/jobs/dues-calculation-workflow.ts","services/financial-service/src/jobs/payment-collection-workflow.ts","services/financial-service/src/routes/analytics.ts","services/financial-service/src/routes/arrears.ts","services/financial-service/src/routes/dues-transactions.ts","services/financial-service/src/routes/remittances.ts","services/financial-service/src/services/arrears-detection.ts","services/financial-service/src/services/payment-processing.ts","services/financial-service/src/services/reconciliation-engine.ts"],
    requiredRuntimePrivileges: ["SELECT", "INSERT", "UPDATE", "DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "employer_payroll_adjustments",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'employerPayrollAdjustments' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "employer_payroll_run_items",
    classification: "PARENT_OWNED_RLS_REQUIRED",
    reason: "Manually verified (2026-09-04, finance.ts round 1): no direct organization_id column; scopes through employer_payroll_runs.organization_id via the runId FK. Reachable via app/api/employer-execution/payroll-runs/route.ts and app/api/employer-execution/payroll-runs/[id]/route.ts, both gated on the parent run's org.",
    supportingCapability: ["app/[locale]/dashboard/employer-execution/payroll-runs/[id]/page.tsx","app/api/employer-execution/payroll-runs/[id]/route.ts","app/api/employer-execution/payroll-runs/route.ts","app/api/employer-execution/remittance-runs/route.ts","app/api/employer-execution/replay/[runId]/route.ts"],
    requiredRuntimePrivileges: ["SELECT", "INSERT", "UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "employer_payroll_runs",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified (2026-09-04, finance.ts round 1): direct NOT NULL organization_id column (db/schema/domains/employer-execution/employer-payroll-runs.ts). Reachable via app/api/employer-execution/payroll-runs/route.ts (GET minRole 'member', POST minRole 'steward'), which filters `where(eq(employerPayrollRuns.organizationId, organizationId))` using the resolved caller context. Also read by lib/workers/employer-execution/process-payroll-run.ts (background worker, org-scoped by the run record it's given).",
    supportingCapability: ["app/[locale]/dashboard/employer-execution/payroll-runs/[id]/page.tsx","app/[locale]/dashboard/employer-execution/payroll-runs/page.tsx","app/api/employer-execution/payroll-runs/[id]/route.ts","app/api/employer-execution/payroll-runs/route.ts","app/api/employer-execution/remittance-runs/route.ts","app/api/employer-execution/replay/[runId]/route.ts","lib/workers/employer-execution/process-payroll-run.ts"],
    requiredRuntimePrivileges: ["SELECT", "INSERT", "UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "employer_remittance_run_items",
    classification: "PARENT_OWNED_RLS_REQUIRED",
    reason: "Manually verified (2026-09-04, finance.ts round 1): no direct organization_id column; scopes through employer_remittance_runs.organization_id via the runId FK. Reachable via the same employer-execution/remittance-runs routes as its parent.",
    supportingCapability: ["app/api/employer-execution/remittance-runs/[id]/route.ts","app/api/employer-execution/remittance-runs/route.ts"],
    requiredRuntimePrivileges: ["SELECT", "INSERT", "UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "employer_remittance_runs",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified (2026-09-04, finance.ts round 1): direct NOT NULL organization_id column (db/schema/domains/employer-execution/employer-remittance-runs.ts). Reachable via app/api/employer-execution/remittance-runs/route.ts (GET minRole 'member', POST minRole 'steward'), filters `where(eq(employerRemittanceRuns.organizationId, organizationId))`.",
    supportingCapability: ["app/[locale]/dashboard/employer-execution/remittance-runs/[id]/page.tsx","app/[locale]/dashboard/employer-execution/remittance-runs/page.tsx","app/api/employer-execution/remittance-runs/[id]/route.ts","app/api/employer-execution/remittance-runs/route.ts","lib/workers/employer-execution/process-remittance-run.ts"],
    requiredRuntimePrivileges: ["SELECT", "INSERT", "UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "employer_remittances",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified (2026-09-04, finance.ts round 1): direct NOT NULL organization_id column (db/schema/dues-finance-schema.ts). Reachable via app/api/dues/remittances/route.ts (GET minRole 'member', POST minRole 'steward'), filters `where(eq(employerRemittances.organizationId, organizationId))`.",
    supportingCapability: ["app/api/dues/dashboard/route.ts","app/api/dues/exceptions/route.ts","app/api/dues/reconciliation/queue/route.ts","app/api/dues/remittances/[id]/route.ts","app/api/dues/remittances/route.ts","app/api/dues/remittances/upload/route.ts","lib/services/dashboard-kpi-service.ts","lib/services/payroll-integration-service.ts","services/financial-service/drizzle/relations.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts","services/financial-service/src/routes/remittances.ts"],
    requiredRuntimePrivileges: ["SELECT", "INSERT", "UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "entitlement_usage_log",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CORRECTED (2026-09-04, finance.ts round 1): the original scan found only an internal-library reference (services/platform-economics/contract-service.ts) with no HTTP-reachability hint. Independently verified this IS reachable: contract-service.ts's recordEntitlementUsage() is called from app/api/grievances/route.ts, app/api/grievances/[id]/documents/route.ts, app/api/voice/upload/route.ts, app/api/ai/classify/route.ts, and app/api/ai/summarize/route.ts — all of which resolve organizationId from the authenticated request context (e.g. grievances/route.ts calls `requireEntitlement(organizationId, 'grievance_case_suite')`). Organization_id column present (db/schema/domains/finance/contracts.ts).",
    supportingCapability: ["services/platform-economics/contract-service.ts"],
    requiredRuntimePrivileges: ["SELECT", "INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "erp_invoices",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'erpInvoices' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "financial_periods",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified (2026-09-04, finance.ts round 1): direct NOT NULL organization_id column (db/schema/dues-finance-schema.ts). Reachable via app/api/finance/summary/route.ts (minRole 'officer', requires organizationId, raw-SQL predicates `WHERE organization_id = ${organizationId}` throughout).",
    supportingCapability: ["app/api/finance/summary/route.ts"],
    requiredRuntimePrivileges: ["SELECT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "gl_account_mappings",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CORRECTED (2026-09-04, finance.ts round 1): the round-7 raw-SQL detection pass found this table referenced in services/platform-economics/finance-outputs.ts but could not trace HTTP reachability. Independently verified: finance-outputs.ts's exportGlJournal() IS reachable via app/api/finance/exports/route.ts, which requires `organizationId` from the caller, gates on `requireEntitlement(organizationId, 'financial_intelligence_suite', userId)`, and calls `exportGlJournal(organizationId, periodId)`. Direct NOT NULL organization_id column (db/schema/domains/finance/accounting.ts).",
    supportingCapability: ["services/platform-economics/finance-outputs.ts"],
    requiredRuntimePrivileges: ["SELECT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "gl_transaction_log",
    classification: "LATENT_UNREACHABLE",
    reason: "Manually verified 2026-09-02: sole non-test reference lib/services/general-ledger-service.ts has zero callers anywhere under app/, actions/, lib/, services/, scripts/ (verified by name-search).",
    supportingCapability: ["lib/services/general-ledger-service.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "gl_trial_balance",
    classification: "LATENT_UNREACHABLE",
    reason: "Manually verified (2026-09-04, finance.ts round 1): only consumer is lib/services/general-ledger-service.ts, which has zero callers anywhere under app/api/ or actions/ (confirmed via full-repo grep for the service file name and its exported function names) — an internal library not yet wired to any route.",
    supportingCapability: ["lib/services/general-ledger-service.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "payment_cycles",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'paymentCycles' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "payment_disputes",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'paymentDisputes' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "payment_methods",
    classification: "LATENT_UNREACHABLE",
    reason: "CORRECTED (2026-09-04, finance.ts round 1): the original scan's 3 cited references (app/api/dues/payment-methods/route.ts, lib/payment-processor/processors/stripe-processor.ts, lib/utils/autopay-utils.ts) are ALL false positives — every one of them is a `stripe.paymentMethods.*` Stripe SDK call (attach/detach/list/retrieve), not an import of this Drizzle table. A precise grep for `import ... paymentMethods ... from '@/db...'` across app/api/, lib/, services/, actions/ (excluding schema/tests) returns zero hits. The app persists Stripe's own payment-method objects directly rather than caching them in this local table, which appears to be dead/unused schema.",
    supportingCapability: ["app/api/dues/payment-methods/route.ts","lib/payment-processor/processors/stripe-processor.ts","lib/utils/autopay-utils.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "payment_plans",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified (2026-09-04, finance.ts round 1): direct NOT NULL organization_id column (db/schema/dues-finance-schema.ts). Reachable via app/api/dues/payment-plans/route.ts (GET minRole 'officer' `where(eq(paymentPlans.organizationId, organizationId))`; POST minRole 'steward').",
    supportingCapability: ["app/api/dues/payment-plans/route.ts","app/api/finance/summary/route.ts","lib/ai/financial-insights.ts","lib/api/index.ts"],
    requiredRuntimePrivileges: ["SELECT", "INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "payments",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified (2026-09-04, finance.ts round 1): direct NOT NULL organization_id column (db/schema/domains/finance/payments.ts). Reachable via services/platform-economics/reconciliation-service.ts's runReconciliation(), called from app/api/reconciliation/process/route.ts (minRole 'admin'/'officer') and app/api/dues/reconcile/route.ts (minRole 'admin'), both of which require organizationId non-null before invoking the service and pass it through as a mandatory filter.",
    supportingCapability: ["app/[locale]/dashboard/admin/dues/page.tsx","app/[locale]/dashboard/admin/dues/payments/[id]/page.tsx","app/[locale]/dashboard/admin/dues/payments/page.tsx","app/[locale]/dashboard/billing-admin/page.tsx","app/[locale]/dashboard/clc/page.tsx","app/[locale]/dashboard/dues/pay/[transactionId]/page.tsx","app/[locale]/dashboard/finance/invoices/[id]/page.tsx","app/api/admin/dues/overview/route.ts","app/api/admin/payments/retry-failed/route.ts","app/api/finance/invoices/[id]/payments/route.ts","app/api/finance/per-capita/inbound/route.ts","app/api/finance/summary/route.ts","app/api/icra/checkout/route.ts","app/api/payments/checkout/create/route.ts","app/api/payments/webhooks/paypal/route.ts","app/api/payments/webhooks/stripe/route.ts","app/api/portal/dues/balance/route.ts","app/api/portal/dues/pay/route.ts","app/api/whop/unauthenticated-checkout/route.ts","app/api/workbook/checkout/route.ts","lib/ai/role-templates.ts","lib/api-auth-guard.ts","lib/api/deprecation.ts","lib/feature-flags.ts","lib/gdpr/consent-manager.ts","lib/integrations/README.md","lib/integrations/adapters/accounting/PHASE_3_COMPLETE.md","lib/integrations/adapters/accounting/freshbooks-adapter.ts","lib/integrations/adapters/accounting/freshbooks-client.ts","lib/integrations/adapters/accounting/quickbooks-adapter.ts","lib/integrations/adapters/accounting/quickbooks-client.ts","lib/integrations/adapters/accounting/sage-intacct-adapter.ts","lib/integrations/adapters/accounting/sage-intacct-client.ts","lib/integrations/adapters/accounting/sync-utils.ts","lib/integrations/adapters/accounting/wave-adapter.ts","lib/integrations/adapters/accounting/wave-client.ts","lib/integrations/adapters/accounting/xero-adapter.ts","lib/integrations/adapters/accounting/xero-client.ts","lib/integrations/registry.ts","lib/jobs/dues-reminder-scheduler.ts","lib/jobs/failed-payment-retry.ts","lib/middleware/auth-middleware.ts","lib/notification-templates/dues-notifications.ts","lib/observability/metrics.ts","lib/payment-processor/IMPLEMENTATION_GUIDE.md","lib/payment-processor/README.md","lib/payment-processor/processors/paypal-processor.ts","lib/payment-processor/processors/square-processor.ts","lib/payment-processor/processors/stripe-processor.ts","lib/payment-processor/processors/whop-processor.ts","lib/public-routes.ts","lib/rate-limiter.ts","lib/reality/capability-registry.ts","lib/receipt-generator.ts","lib/services/feature-flags-service.ts","lib/services/financial-email-service.ts","lib/services/payment-notifications.ts","lib/services/payment-service.ts","lib/services/payroll-integration-service.ts","lib/services/strike-fund-tax-service.ts","lib/stripe-elements.ts","lib/stripe.ts","lib/ui-tooltips.ts","services/clc/compliance-reports.ts","services/financial-service/REMITTANCE_PROCESSING.md","services/financial-service/SCHEMA_ANALYSIS.md","services/financial-service/STRIPE_INTEGRATION_COMPLETE.md","services/financial-service/STRIPE_TESTING.md","services/financial-service/TESTING_STATUS.md","services/financial-service/WEEK_12_TESTING_ISSUES.md","services/financial-service/WEEK_5_6_IMPLEMENTATION.md","services/financial-service/add-missing-tables.sql","services/financial-service/src/db/schema-platform-economics.ts","services/financial-service/src/db/schema.ts","services/financial-service/src/index.ts","services/financial-service/src/jobs/arrears-management-workflow.ts","services/financial-service/src/jobs/payment-collection-workflow.ts","services/financial-service/src/jobs/stipend-processing-workflow.ts","services/financial-service/src/middleware/idempotency.ts","services/financial-service/src/routes/donations.ts","services/financial-service/src/routes/payments.ts","services/financial-service/src/routes/remittances.ts","services/financial-service/src/services/arrears-detection.ts","services/financial-service/src/services/financial-reports.ts","services/financial-service/src/services/financial-reports.ts.broken","services/financial-service/src/services/payment-processing.ts","services/financial-service/src/services/reconciliation-engine.ts","services/financial-service/test-arrears.ps1","services/financial-service/test-donations.ps1","services/financial-service/test-payments-quick.ps1","services/financial-service/test-payments-simple.ps1","services/financial-service/test-payments.ps1","services/platform-economics/billing-service.ts","services/platform-economics/reconciliation-service.ts","services/whiplash-prevention-service.ts"],
    requiredRuntimePrivileges: ["SELECT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "payroll_deductions",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified (2026-09-04, finance.ts round 1): direct NOT NULL organization_id column (db/schema/dues-finance-schema.ts). Reachable via app/api/dues/deductions/route.ts (GET minRole 'member'), dual-scoped by BOTH organizationId AND userId (`where(and(organizationId = ..., userId = ...))`) — a member can only see their own deductions within their own org.",
    supportingCapability: ["app/api/dues/deductions/route.ts"],
    requiredRuntimePrivileges: ["SELECT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "pension_contributions",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified (2026-09-04, finance.ts round 1): direct NOT NULL organization_id column (db/schema/domains/finance/pension.ts). Reachable via app/api/pension/contributions/route.ts (GET minRole 'member', POST minRole 'steward'), org-scoped with an optional additional memberId filter.",
    supportingCapability: ["app/api/pension/contributions/route.ts","lib/ai/pension-intelligence.ts","services/financial-service/drizzle/relations.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: ["SELECT", "INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "pension_plans",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified (2026-09-04, finance.ts round 1): direct NOT NULL organization_id column (db/schema/domains/finance/pension.ts). Reachable via app/api/pension/plans/route.ts (GET minRole 'member', POST minRole 'steward'), filters `where(eq(pensionPlans.organizationId, organizationId!))`.",
    supportingCapability: ["app/api/pension/plans/[id]/route.ts","app/api/pension/plans/route.ts","lib/ai/pension-intelligence.ts","services/financial-service/drizzle/relations.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: ["SELECT", "INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "pension_t4a_records",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CORRECTED (2026-09-04, finance.ts round 1): an earlier automated research pass claimed the routes for this table 'do not exist'. Independently verified this is FALSE — both app/api/pension/t4a/route.ts and app/api/tax/t4a/route.ts exist and are reachable (GET minRole 'member' filters `where(eq(pensionT4aRecords.organizationId, organizationId!))`, optionally combined with memberId; POST minRole 'steward' inserts with organizationId from the resolved caller context). Direct NOT NULL organization_id column (db/schema/domains/finance/pension.ts).",
    supportingCapability: ["app/api/pension/t4a/route.ts","app/api/tax/t4a/route.ts"],
    requiredRuntimePrivileges: ["SELECT", "INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "pension_trustee_meetings",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified (2026-09-04, finance.ts round 1): direct NOT NULL organization_id column (db/schema/domains/finance/pension.ts). Reachable via app/api/pension/trustee-meetings/route.ts (GET minRole 'member', filters `where(eq(pensionTrusteeMeetings.organizationId, organizationId!))`; POST minRole 'steward') and app/api/pension/trustee-meetings/[id]/route.ts.",
    supportingCapability: ["app/api/pension/trustee-meetings/[id]/route.ts","app/api/pension/trustee-meetings/route.ts","services/financial-service/drizzle/relations.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: ["SELECT", "INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "pension_trustees",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified (2026-09-04, finance.ts round 1): direct NOT NULL organization_id column (db/schema/domains/finance/pension.ts). Reachable via app/api/pension/trustees/route.ts (GET minRole 'member', filters `where(eq(pensionTrustees.organizationId, organizationId!))`; POST minRole 'steward') and app/api/pension/trustees/[id]/route.ts.",
    supportingCapability: ["app/api/pension/trustees/[id]/route.ts","app/api/pension/trustees/route.ts","services/financial-service/drizzle/relations.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: ["SELECT", "INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "per_capita_remittances",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified (2026-09-04, finance.ts round 1): direct NOT NULL organization_id column (db/schema/clc-per-capita-schema.ts; multi-org shape with fromOrganizationId/toOrganizationId). Reachable via TWO distinct paths: (1) tenant-facing crudRoutes at app/api/tax/rl-1/generate/route.ts and app/api/arrears/create-payment-plan/route.ts with orgScoped: true, readRole: 'member', writeRole: 'steward'; (2) CLC-national dashboards (app/[locale]/dashboard/clc/page.tsx, dashboard/clc/staff/page.tsx, dashboard/federation/page.tsx) and services/clc/* reporting helpers, which are platform-staff-facing and intentionally cross-affiliate. MIXED invocation authority reflects both legitimate paths.",
    supportingCapability: ["app/[locale]/dashboard/clc/page.tsx","app/[locale]/dashboard/clc/staff/page.tsx","app/[locale]/dashboard/federation/page.tsx","app/api/arrears/case/[memberId]/route.ts","app/api/arrears/cases/route.ts","app/api/arrears/create-payment-plan/route.ts","app/api/arrears/escalate/[caseId]/route.ts","app/api/arrears/log-contact/route.ts","app/api/arrears/resolve/[caseId]/route.ts","app/api/healthwelfare/plans/route.ts","app/api/tax/cope/receipts/route.ts","app/api/tax/cra/export/route.ts","app/api/tax/rl-1/generate/route.ts","app/api/tax/slips/route.ts","app/api/tax/t106/route.ts","lib/graphql/resolvers.ts","services/clc/compliance-reports.ts","services/clc/per-capita-calculator.ts","services/clc/remittance-audit.ts","services/clc/remittance-export.ts","services/clc/remittance-notifications.ts","services/financial-service/drizzle/relations.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: ["SELECT", "INSERT", "UPDATE"],
    requiredSystemPrivileges: ["SELECT"],
    invocationAuthority: "MIXED",
    dbExecutionPrincipal: "MIXED",
    reviewPriority: "NONE",
  },
  {
    table: "platform_cost_ledger_entries",
    classification: "TENANT_RLS_REQUIRED",
    reason: "CORRECTED (2026-09-04, finance.ts round 1): the original scan cited only internal-library references (services/platform-economics/allocation-engine.ts, ledger-service.ts) with no HTTP-reachability hint. Independently verified this IS reachable: ledger-service.ts's appendLedgerEntry() and allocation-engine.ts's runAllocation()/getAllocationRun() are called from app/api/dues/ledger/route.ts, app/api/finance/simulation/route.ts, app/api/finance/allocation/route.ts, and app/api/finance/allocation/run/route.ts. Organization_id column present (db/schema/domains/finance/platform-ledger.ts).",
    supportingCapability: ["lib/reality/capability-registry.ts","services/platform-economics/allocation-engine.ts","services/platform-economics/ledger-service.ts"],
    requiredRuntimePrivileges: ["SELECT", "INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "platform_invoices",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified (2026-09-04, finance.ts round 1): direct NOT NULL organization_id column (db/schema/domains/finance/platform-billing.ts). Reachable via app/api/dues/late-fees/route.ts (minRole 'officer', `where(eq(platformInvoices.organizationId, organizationId))`) and services/platform-economics/reconciliation-service.ts (org-scoped when organizationId is supplied, always is from its two callers — see 'payments' entry).",
    supportingCapability: ["app/api/dues/late-fees/route.ts","app/api/pilot/apply/[id]/commercial-transition/route.ts","services/platform-economics/billing-service.ts","services/platform-economics/reconciliation-service.ts"],
    requiredRuntimePrivileges: ["SELECT", "INSERT", "UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "platform_payments",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified (2026-09-04, finance.ts round 1): direct NOT NULL organization_id column (db/schema/domains/finance/platform-billing.ts). Reachable via app/api/payments/webhooks/stripe/route.ts (Stripe webhook, signature-verified, org resolved from webhook metadata, part of the flow runs under withSystemContext()) and services/platform-economics/reconciliation-service.ts (org-scoped, see 'payments' entry).",
    supportingCapability: ["app/api/payments/webhooks/stripe/route.ts","lib/reality/capability-registry.ts","services/platform-economics/billing-service.ts","services/platform-economics/reconciliation-service.ts"],
    requiredRuntimePrivileges: ["SELECT", "INSERT", "UPDATE"],
    requiredSystemPrivileges: ["SELECT", "INSERT"],
    invocationAuthority: "MIXED",
    dbExecutionPrincipal: "MIXED",
    reviewPriority: "NONE",
  },
  {
    table: "reconciliation_exceptions",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified (2026-09-04, finance.ts round 1): organization_id column present (db/schema/domains/finance/reconciliation.ts). Written by services/platform-economics/reconciliation-service.ts's runReconciliation() (`organizationId: pmt.organizationId` when inserting an unmatched-payment exception), called only from routes that require organizationId non-null — app/api/reconciliation/process/route.ts, app/api/dues/reconcile/route.ts.",
    supportingCapability: ["services/platform-economics/reconciliation-service.ts"],
    requiredRuntimePrivileges: ["SELECT", "INSERT", "UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "reconciliation_runs",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified (2026-09-04, finance.ts round 1): organization_id column present (db/schema/domains/finance/reconciliation.ts). Created by services/platform-economics/reconciliation-service.ts's runReconciliation() with `organizationId: input.organizationId`, called only from routes requiring organizationId non-null (see reconciliation_exceptions), plus read via app/api/reconciliation/bank/route.ts.",
    supportingCapability: ["app/api/reconciliation/bank/route.ts","services/platform-economics/reconciliation-service.ts"],
    requiredRuntimePrivileges: ["SELECT", "INSERT", "UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "remittance_exceptions",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified (2026-09-04, finance.ts round 1): direct NOT NULL organization_id column (db/schema/dues-finance-schema.ts). System-generated queue populated by lib/services/payroll-integration-service.ts (an org-scoped background reconciliation helper, not a direct HTTP route); no ordinary tenant CRUD route was found, consistent with this being a backend-generated exception queue rather than user-authored data.",
    supportingCapability: ["lib/services/payroll-integration-service.ts"],
    requiredRuntimePrivileges: ["SELECT", "INSERT", "UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "WORKER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "remittance_line_items",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified (2026-09-04, finance.ts round 1): direct NOT NULL organization_id column (db/schema/dues-finance-schema.ts). Reachable via app/api/dues/exceptions/route.ts (minRole 'steward') and the app/api/dues/reconciliation/* routes. FLAG: the exceptions-route query joins remittanceLineItems to employerRemittances and does not repeat an explicit organizationId predicate on remittanceLineItems itself in the WHERE clause — a code comment asserts DB-level RLS enforces isolation. This table needs the standard ue_create_direct_org_rls_policy treatment (hence TENANT_RLS_REQUIRED, not a lesser classification); until that policy is confirmed live, the app-layer join is the only enforcement and should be verified/tested explicitly rather than assumed.",
    supportingCapability: ["app/api/dues/dashboard/route.ts","app/api/dues/exceptions/route.ts","app/api/dues/reconciliation/auto-match/route.ts","app/api/dues/reconciliation/match/route.ts","app/api/dues/reconciliation/queue/route.ts","app/api/dues/reconciliation/reject/route.ts","lib/services/payroll-integration-service.ts"],
    requiredRuntimePrivileges: ["SELECT", "UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "reward_budget_envelopes",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified (2026-09-04, finance.ts round 1): direct NOT NULL org_id column (db/schema/domains/infrastructure/rewards.ts). Reachable via lib/services/rewards/budget-service.ts / export-service.ts, called from actions/rewards-actions.ts (org resolved via withRLSContext, see budget_reservations) and app/[locale]/dashboard/admin/rewards/analytics/page.tsx (platform-admin analytics view).",
    supportingCapability: ["app/[locale]/dashboard/admin/rewards/analytics/page.tsx","lib/services/rewards/budget-service.ts","lib/services/rewards/export-service.ts"],
    requiredRuntimePrivileges: ["SELECT", "INSERT", "UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "MIXED",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "reward_wallet_ledger",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified (2026-09-04, finance.ts round 1): direct NOT NULL org_id column (db/schema/domains/infrastructure/rewards.ts). Reachable via app/api/rewards/wallet/route.ts and lib/services/rewards/{wallet-service,export-service,notification-service}.ts, plus lib/utils/rewards-stats-utils.ts.",
    supportingCapability: ["app/[locale]/dashboard/admin/rewards/analytics/page.tsx","lib/services/rewards/export-service.ts","lib/services/rewards/notification-service.ts","lib/services/rewards/wallet-service.ts","lib/utils/rewards-stats-utils.ts"],
    requiredRuntimePrivileges: ["SELECT", "INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "social_accounts",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified (2026-09-04, finance.ts round 1): direct NOT NULL organization_id column (db/schema/domains/infrastructure/social-media.ts — filed under finance.ts only because the original scan's table-name keyword match hit 'accounts'; the table itself is unrelated to billing/payments). Reachable via app/api/social-media/accounts/route.ts, which filters `where(eq(socialAccounts.organizationId, organizationId))` and explicitly rejects cross-org access with `if (organizationId !== account.organizationId)` on item-level operations.",
    supportingCapability: ["app/api/social-media/accounts/route.ts","app/api/social-media/analytics/route.ts","app/api/social-media/posts/route.ts","lib/social-media/social-media-service.ts"],
    requiredRuntimePrivileges: ["SELECT", "INSERT", "UPDATE", "DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "subscription_events_log",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified 2026-09-02: direct NOT NULL organization_id column (db/schema/domains/finance/dunning.ts). Reachable via services/platform-economics/subscription-lifecycle-service.ts, which is called from app/api/billing/credits/check-expired/route.ts. The sibling reference services/platform-economics/dunning-service.ts has zero independent callers but shares the same table via the reachable lifecycle service.",
    supportingCapability: ["services/platform-economics/subscription-lifecycle-service.ts","app/api/billing/credits/check-expired/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "union_dues_receipts",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'unionDuesReceipts' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "union_dues_year_end",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'unionDuesYearEnd' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "account_balance_reconciliation",
    classification: "LATENT_UNREACHABLE",
    reason: "Manually verified (2026-09-04, finance.ts round 1): part of the whiplash-prevention compliance schema (db/schema/domains/compliance/whiplash.ts). Only consumer is services/whiplash-prevention-service.ts, which has zero callers anywhere under app/api/ or actions/ (same finding as stripe_connect_accounts / payment_routing_rules / separated_payment_transactions).",
    supportingCapability: ["services/whiplash-prevention-service.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "billing_terms",
    classification: "LATENT_UNREACHABLE",
    reason: "Round-7 scope-expansion scan: zero references to the 'billingTerms' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files via a combined ripgrep pass across app/, actions/, lib/, services/. No known application code path queries this table today. NOT yet individually checked for raw-SQL (non-Drizzle-symbol) references to the physical table name — see the raw-SQL LATENT fixture test for why that check matters before this can be treated as final.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "budget_reservations",
    classification: "PARENT_OWNED_RLS_REQUIRED",
    reason: "Manually verified (2026-09-04, finance.ts round 1): no direct organization_id column; scopes through budget_pool.organization_id via the poolId FK (db/schema/domains/infrastructure/awards.ts). Reachable via lib/services/rewards/budget-service.ts (reserveBudget/confirmBudgetReservation/etc.), called from actions/rewards-actions.ts, which resolves the caller's own organization via `withRLSContext({ organizationId: resolvedOrgId })` and explicitly does not trust auth()'s raw orgId claim for Entra-backed sessions.",
    supportingCapability: ["lib/services/rewards/budget-service.ts"],
    requiredRuntimePrivileges: ["SELECT", "INSERT", "UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "clc_chart_of_accounts",
    classification: "SEPARATE_DATABASE_BOUNDARY",
    reason: "Manually verified (2026-09-04, finance.ts round 1): no organization_id column (db/schema/clc-per-capita-schema.ts — a national/cross-affiliate chart of accounts by design). The only real consumers are services/financial-service/** files (drizzle/schema.ts, src/db/schema.ts) — a separate Node service/package, not this Next.js app's own request-handling runtime. Not to be confused with the reachable services/clc/chart-of-accounts.ts's chartOfAccounts/accountMappings (see chart_of_accounts / account_mappings entries), which is a different table pair entirely.",
    supportingCapability: ["services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "federation_remittances",
    classification: "LATENT_UNREACHABLE",
    reason: "Round-7 scope-expansion scan: zero references to the 'federationRemittances' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files via a combined ripgrep pass across app/, actions/, lib/, services/. No known application code path queries this table today. NOT yet individually checked for raw-SQL (non-Drizzle-symbol) references to the physical table name — see the raw-SQL LATENT fixture test for why that check matters before this can be treated as final.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "payment_allocations",
    classification: "PARENT_OWNED_RLS_REQUIRED",
    reason: "Manually verified (2026-09-04, finance.ts round 1): no direct organization_id column; scopes through platform_payments/platform_invoices via the paymentId/invoiceId FKs. Reachable via services/platform-economics/reconciliation-service.ts (`select().from(paymentAllocations).where(inArray(paymentAllocations.paymentId, paymentIds))` where paymentIds were already fetched org-scoped in the same transaction), called only from routes that require organizationId — see 'payments' entry.",
    supportingCapability: ["lib/integrations/adapters/accounting/sync-utils.ts","services/platform-economics/billing-service.ts","services/platform-economics/reconciliation-service.ts"],
    requiredRuntimePrivileges: ["SELECT", "INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "payment_classification_policy",
    classification: "LATENT_UNREACHABLE",
    reason: "Round-7 scope-expansion scan: zero references to the 'paymentClassificationPolicy' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files via a combined ripgrep pass across app/, actions/, lib/, services/. No known application code path queries this table today. NOT yet individually checked for raw-SQL (non-Drizzle-symbol) references to the physical table name — see the raw-SQL LATENT fixture test for why that check matters before this can be treated as final.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "payment_routing_rules",
    classification: "LATENT_UNREACHABLE",
    reason: "Manually verified (2026-09-04, finance.ts round 1): part of the whiplash-prevention compliance schema (db/schema/domains/compliance/whiplash.ts). Only consumer is services/whiplash-prevention-service.ts, which has zero callers anywhere under app/api/ or actions/ (same finding as stripe_connect_accounts).",
    supportingCapability: ["services/whiplash-prevention-service.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "platform_invoice_line_items",
    classification: "PARENT_OWNED_RLS_REQUIRED",
    reason: "Manually verified (2026-09-04, finance.ts round 1): no direct organization_id column; scopes through platform_invoices.organization_id via the invoiceId FK. Reachable via app/api/pilot/apply/[id]/commercial-transition/route.ts (locked pilot control-plane, referenced only) and, indirectly, wherever platformInvoices are created/read (see that entry).",
    supportingCapability: ["app/api/pilot/apply/[id]/commercial-transition/route.ts","services/platform-economics/billing-service.ts"],
    requiredRuntimePrivileges: ["SELECT", "INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "reconciliation_matches",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified (2026-09-04, finance.ts round 1): organization_id column present (db/schema/domains/finance/reconciliation.ts). Written by services/platform-economics/reconciliation-service.ts's runReconciliation() when a payment is matched to an invoice, called only from routes requiring organizationId non-null (see reconciliation_exceptions).",
    supportingCapability: ["services/platform-economics/reconciliation-service.ts"],
    requiredRuntimePrivileges: ["SELECT", "INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "remittance_approvals",
    classification: "SYSTEM_ONLY",
    reason: "Manually verified (2026-09-04, finance.ts round 1): no direct organization_id column (scopes only via remittanceId -> perCapitaRemittances FK). The ONLY consumer is app/[locale]/dashboard/clc/staff/page.tsx, a CLC (Canadian Labour Congress) national staff dashboard: access is gated by checkCLCStaffAccess(userId, orgId) (requires a 'clc_staff'/'clc_executive'-class role, not self-service grantable), and the query itself runs inside withSystemContext() with no organizationId filter — `db.select(...).from(remittanceApprovals).where(eq(remittanceApprovals.status, 'pending'))`. This is a deliberate cross-affiliate national-governance view (same 'Model A' pattern as other CLC dashboards in this registry), not a bug. Per the PERMANENT INVARIANT in types.ts, dbExecutionPrincipal stays SYSTEM_RUNTIME even though the invoking human role is platform-level, never TENANT_RUNTIME.",
    supportingCapability: ["app/[locale]/dashboard/clc/staff/page.tsx","services/clc/remittance-audit.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: ["SELECT", "UPDATE"],
    invocationAuthority: "PLATFORM_ADMIN",
    dbExecutionPrincipal: "SYSTEM_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "rl1_tax_slips",
    classification: "LATENT_UNREACHABLE",
    reason: "Manually verified (2026-09-04, finance.ts round 1): no organization_id column (userId-only, federal/provincial tax-slip shape). An earlier automated pass conflated this table with the separate, genuinely-reachable pension_t4a_records table and its /api/pension/t4a and /api/tax/t4a routes — those routes are backed by pensionT4aRecords, NOT rl1_tax_slips. The real (and only) code path touching rl1TaxSlips is services/tax-slip-service.ts (TaxSlipService.generateRL1Slips), consumed only by lib/api/tax-slip-service-api.ts, which itself has zero callers anywhere under app/api/ or actions/ (confirmed via full-repo grep for both the service class name and the api wrapper's exported functions). app/api/tax/rl-1/generate/route.ts — despite its name — is actually a generic crudRoutes wrapper around perCapitaRemittances, not this table.",
    supportingCapability: ["services/tax-slip-service.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "separated_payment_transactions",
    classification: "LATENT_UNREACHABLE",
    reason: "Manually verified (2026-09-04, finance.ts round 1): part of the whiplash-prevention compliance schema (db/schema/domains/compliance/whiplash.ts). Only consumer is services/whiplash-prevention-service.ts, which has zero callers anywhere under app/api/ or actions/ (same finding as stripe_connect_accounts).",
    supportingCapability: ["services/whiplash-prevention-service.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "strike_fund_disbursements",
    classification: "NEEDS_REVIEW",
    reason: "CONFIRMED REAL CROSS-ORG DATA LEAK, NOT YET FIXED (2026-09-04, finance.ts round 1 — left OPEN, not closed): this table has NO organization_id column at all (db/schema/domains/finance/taxes.ts, also duplicated verbatim in the legacy db/schema/strike-fund-tax-schema.ts, which app/api/strike-fund/dashboard/route.ts imports directly instead of the canonical domains/finance/taxes.ts copy — both resolve to the same physical 'strike_fund_disbursements' table name, so this is a code-duplication concern, not itself the security bug). The security bug: app/api/strike-fund/dashboard/route.ts requires organizationId from the caller (`if (!organizationId) throw ApiError.badRequest(...)`) implying the intent was to scope the response to the caller's own union, but the actual balance query at line ~37 is `SUM(payment_amount) ... WHERE taxYear = currentYear` with NO organizationId predicate at all (there is no column to filter on) — so the returned total strike-fund balance is SUMMED ACROSS EVERY ORGANIZATION on the platform for that tax year and shown to any authenticated member (minRole: 'member') of ANY org. The same gap exists in lib/services/strike-fund-tax-service.ts's getYearlyStrikePay(), processYearEndTaxSlips(), and isMemberInQuebec() — all filter by userId and/or taxYear only. FIX REQUIRES (deferred to a dedicated remediation round, not attempted in this classification pass): (1) resolving which organization each historical disbursement actually belongs to (no reliable backfill key exists today — userId alone does not disambiguate cross-org membership), (2) adding an organization_id column via migration, (3) updating all four query sites above to filter by it, (4) deduplicating the legacy db/schema/strike-fund-tax-schema.ts copy in favour of the canonical domains/finance/taxes.ts one, (5) a dedicated cross-tenant regression test (see board_packets in governance.ts for the precedent). Left as NEEDS_REVIEW / reviewPriority HIGH — deliberately NOT marked TENANT_RLS_REQUIRED, which would misrepresent this as already scoped.",
    supportingCapability: ["app/api/strike-fund/dashboard/route.ts","lib/services/strike-fund-tax-service.ts","services/tax-slip-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "stripe_connect_accounts",
    classification: "LATENT_UNREACHABLE",
    reason: "Manually verified (2026-09-04, finance.ts round 1): part of the 'whiplash prevention' strike-fund payment-separation compliance schema (db/schema/domains/compliance/whiplash.ts). Only consumer is services/whiplash-prevention-service.ts, which has zero callers anywhere under app/api/ or actions/ (confirmed via full-repo grep for the service file and its exported class name) — the compliance module exists but is not yet wired into any route.",
    supportingCapability: ["services/whiplash-prevention-service.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "subscription_plans",
    classification: "GLOBAL_REFERENCE_DATA",
    reason: "Manually verified (2026-09-04, finance.ts round 1): no organization_id column by design — a shared platform-wide catalog of pricing/plan definitions (db/schema/domains/finance/platform-billing.ts), referenced by org_subscriptions and read (never written) by tenant-facing and pilot-transition code alike. No cross-tenant exposure risk since the data is intentionally identical for every caller.",
    supportingCapability: ["app/api/pilot/apply/[id]/commercial-transition/route.ts","services/platform-economics/billing-service.ts","services/platform-economics/pricing-template-service.ts"],
    requiredRuntimePrivileges: ["SELECT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "MIXED",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "t4a_tax_slips",
    classification: "LATENT_UNREACHABLE",
    reason: "Manually verified (2026-09-04, finance.ts round 1): no organization_id column (userId-only, federal CRA tax-slip shape). Same disposition as rl1_tax_slips: the only code path is services/tax-slip-service.ts (TaxSlipService.generateT4ASlips) -> lib/api/tax-slip-service-api.ts, which has zero callers under app/api/ or actions/ (confirmed via full-repo grep). Not to be confused with the separate, genuinely-reachable pension_t4a_records table backing /api/pension/t4a and /api/tax/t4a.",
    supportingCapability: ["services/tax-slip-service.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "tax_year_end_processing",
    classification: "LATENT_UNREACHABLE",
    reason: "Manually verified (2026-09-04, finance.ts round 1): no organization_id column (global year-end state keyed only by tax_year). Only code path is services/tax-slip-service.ts (TaxSlipService.processYearEnd / completeYearEndProcessing) -> lib/api/tax-slip-service-api.ts, which has zero callers under app/api/ or actions/ (confirmed via full-repo grep).",
    supportingCapability: ["services/tax-slip-service.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
]
