/**
 * db/rls-storage-authority/governance.ts
 *
 * PR #752 round 9: extracted from the single-file
 * db/rls-storage-authority-manifest.ts (which exceeded the repository's
 * 8000-line hard cap at 8009 lines — see
 * tooling/contract-tests/file-size-enforcement.test.ts) into semantic
 * domain modules. This module owns: Governance (bylaws, board, committees, elections, reserved matters).
 *
 * Domain boundaries were assigned mechanically by table-name keyword
 * matching against the entry's `table` field (see the one-time migration
 * script referenced in the round-9 commit message) — every entry's DATA
 * (classification, reason, privileges, authority) is unchanged from the
 * pre-split manifest; only its physical file location changed. Do not
 * hand-edit an entry's domain placement without also checking
 * db/__tests__/rls-storage-authority-registry-composition.test.ts, which
 * proves the composed registry is unaffected by which module an entry
 * lives in.
 *
 * Add NEW entries to whichever domain module most closely matches the
 * table's real subject matter; when genuinely ambiguous, prefer
 * reference-latent.ts (the catch-all) over forcing a bad fit elsewhere.
 */
import type { StorageAuthorityEntry } from './types';

export const governanceEntries: StorageAuthorityEntry[] = [
  {
    table: "board_packet_templates",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'boardPacketTemplates' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "board_packets",
    classification: "NEEDS_REVIEW",
    reason: "3 non-test reference(s) to 'boardPackets' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/governance/board-packets/[id]/route.ts","app/api/governance/board-packets/route.ts","lib/services/board-packet-generator.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "committee_action_items",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'committeeActionItems' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/services/committee-workspace-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "committee_documents",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'committeeDocuments' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/services/committee-workspace-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "committee_intelligence_snapshots",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'committeeIntelligenceSnapshots' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/services/committee-workspace-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "committee_meetings",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'committeeMeetings' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/services/committee-workspace-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "committees",
    classification: "NEEDS_REVIEW",
    reason: "30 non-test reference(s) to 'committees' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/[locale]/(marketing)/conventions/page.tsx","app/[locale]/(marketing)/governance/page.tsx","app/[locale]/(marketing)/pricing/page.tsx","app/[locale]/dashboard/committees/[id]/committee-workspace.tsx","app/[locale]/dashboard/committees/committees-page.tsx","app/[locale]/dashboard/committees/page.tsx","app/[locale]/dashboard/organizational-topology/page.tsx","app/api/cnesst/hs-committees/[id]/route.ts","app/api/cnesst/hs-committees/route.ts","app/api/committees/[id]/action-items/[itemId]/route.ts","app/api/committees/[id]/action-items/route.ts","app/api/committees/[id]/documents/route.ts","app/api/committees/[id]/intelligence/route.ts","app/api/committees/[id]/meetings/[meetingId]/attendance/route.ts","app/api/committees/[id]/meetings/[meetingId]/minutes/route.ts","app/api/committees/[id]/meetings/[meetingId]/route.ts","app/api/committees/[id]/meetings/route.ts","app/api/committees/[id]/route.ts","app/api/committees/route.ts","lib/icra/adaptation/adaptivePassageLibrary.ts","lib/icra/contradictions/contradictionSignalPairs.ts","lib/icra/modalities-v2/registry.ts","lib/icra/questions.ts","lib/icra/scoring.ts","lib/institutional-legitimacy.ts","lib/oci/benchmark/sectorBaselines.ts","lib/oci/benchmark/stewardshipBurdenPatterns.ts","lib/services/committee-workspace-service.ts","lib/workbook/engines/continuityTopologyMapper.ts","services/platform-economics/entitlement-guard.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "congress_memberships",
    classification: "LATENT_UNREACHABLE",
    reason: "Manually verified 2026-09-02: direct organization_id-shaped data (db/schema/domains/data/congress.ts). Sole union-eyes reference is lib/auth/hierarchy-access-control.ts, which has zero callers anywhere under app/, actions/, lib/, services/, scripts/ (verified by name-search) — despite the filename suggesting a core auth module, it is not wired into any real authorization path today. The only other reference is services/financial-service/** — a separately deployed service.",
    supportingCapability: ["lib/auth/hierarchy-access-control.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "governance_bylaws",
    classification: "LATENT_UNREACHABLE",
    reason: "RESOLVED (round 8, governance family review): the original citation list was a FALSE POSITIVE — every listed file matches the plain-English word 'bylaws' (marketing copy, ICRA questionnaire text, tooltips, role templates), not the actual 'bylaws' Drizzle export (db/schema/domains/governance/bylaws.ts, physical table governance_bylaws) or a raw-SQL reference to it. app/api/governance/bylaws/route.ts's own doc comment says it is 'Sourced from the knowledge base using governance/bylaws document types' — it queries `knowledgeBase`, not this table. Verified zero '.from(bylaws)'/'.insert(bylaws)'/etc. call sites and zero raw-SQL 'FROM/INTO/UPDATE governance_bylaws' references anywhere outside __tests__/**.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "governance_policies",
    classification: "TENANT_RLS_REQUIRED",
    reason: "RESOLVED (round 8, governance family review): both citing routes are real. app/api/governance/policies/rules/route.ts's GET (withApi minRole:'steward') reads `governancePolicies` filtered by `eq(governancePolicies.organizationId, organizationId!)` via plain `db`; its POST (minRole:'admin') inserts via withRLSContext, values include organizationId explicitly. app/api/governance/policy-templates/route.ts's GET (minRole:'officer') filters the same way; its POST (minRole:'admin') inserts via withRLSContext with organizationId + an audit-log entry. No UPDATE/DELETE call site found; not defaulted to FULL_DML.",
    supportingCapability: ["app/api/governance/policies/rules/route.ts","app/api/governance/policy-templates/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "governance_signatories",
    classification: "LATENT_UNREACHABLE",
    reason: "RESOLVED (round 8, governance family review): another FALSE POSITIVE, same shape as 'governance_bylaws'. app/api/governance/signatories/route.ts's own doc comment says 'Canonical signatories feed for the governance dashboard' but it actually queries `organizationMembers` filtered to SIGNATORY_ROLES (president/vice_president/secretary_treasurer/officer/chief_steward) — it never references the 'governanceSignatories' Drizzle export or a raw-SQL 'governance_signatories' reference. Verified zero real reachability anywhere outside __tests__/**.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "HIGH",
  },
  {
    table: "icra_governance_flags",
    classification: "SYSTEM_ONLY",
    reason: "ICRA_PSEUDONYMOUS_NO_LOGIN=APPROVED, ASSESSMENT_ID_AS_SOLE_BEARER_AUTHORITY=REJECTED (PR #752): the pseudonymous product model is intentional, but assessmentId alone must never authorize DB access. lib/icra/assessment-capability.ts adds a hashed, purpose-bound bearer capability; every route touching an existing assessment now verifies it before entering withSystemContext. Verified 2026-09-01 (round 7, ICRA capability architecture): only reached via withSystemContext() in the capability-gated submit routes. No direct organization_id column.",
    supportingCapability: ["app/api/icra/submit/route.ts","app/api/icra/[assessmentId]/submit/route.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "SYSTEM_SCHEDULE",
    dbExecutionPrincipal: "SYSTEM_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "joint_hs_committees",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified 2026-09-02: direct NOT NULL organization_id column (db/schema/domains/health-safety/cnesst-schema.ts). Reachable via live HTTP routes app/api/cnesst/hs-committees/route.ts, app/api/cnesst/hs-committees/[id]/route.ts.",
    supportingCapability: ["app/api/cnesst/hs-committees/route.ts","app/api/cnesst/hs-committees/[id]/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "ue_governance_job_cancellation_audit_event",
    classification: "LATENT_UNREACHABLE",
    reason: "Verified 2026-09-01 (round 6, Phase-3A priority tranche + reachability-scan correction): jobCancellationAuditEvent has a real, org-scoped (organization_id NOT NULL) pgTable declaration in db/schema/gate-13-job-cancellation-governance.ts (exported via the domains barrel), but zero non-test references to it exist anywhere in app/, actions/, lib/, or services/ within apps/union-eyes proper. The original scan's supportingCapability list only surfaced services/financial-service's own same-named table (its own separate database) and MISSED the real union-eyes declaration — this entry corrects that gap. financial-service's copy is out of this manifest's remit (SEPARATE_DATABASE_BOUNDARY); union-eyes' own copy is simply unused today.",
    supportingCapability: ["db/schema/gate-13-job-cancellation-governance.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "ue_governance_job_cancellation_request",
    classification: "LATENT_UNREACHABLE",
    reason: "Verified 2026-09-01 (round 6, Phase-3A priority tranche + reachability-scan correction): jobCancellationRequest has a real, org-scoped (organization_id NOT NULL) pgTable declaration in db/schema/gate-13-job-cancellation-governance.ts (exported via the domains barrel), but zero non-test references to it exist anywhere in app/, actions/, lib/, or services/ within apps/union-eyes proper (only financial-service's own separately-databased same-named table is actively used, out of this manifest's remit). Corrects a gap in the original scan, which only surfaced the financial-service reference.",
    supportingCapability: ["db/schema/gate-13-job-cancellation-governance.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "ue_governance_job_execution_state",
    classification: "LATENT_UNREACHABLE",
    reason: "Verified 2026-09-01 (round 6, Phase-3A priority tranche + reachability-scan correction): jobExecutionState has a real, org-scoped (organization_id NOT NULL) pgTable declaration in db/schema/gate-13-job-cancellation-governance.ts (exported via the domains barrel), but zero non-test references to it exist anywhere in app/, actions/, lib/, or services/ within apps/union-eyes proper (only financial-service's own separately-databased same-named table is actively used, out of this manifest's remit). Corrects a gap in the original scan, which only surfaced the financial-service reference.",
    supportingCapability: ["db/schema/gate-13-job-cancellation-governance.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "ue_governance_job_reconciliation_pass",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'jobReconciliationPass' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "board_packet_distributions",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'boardPacketDistributions' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/services/board-packet-generator.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "board_packet_sections",
    classification: "LATENT_UNREACHABLE",
    reason: "Round-7 scope-expansion scan: zero references to the 'boardPacketSections' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files via a combined ripgrep pass across app/, actions/, lib/, services/. No known application code path queries this table today. NOT yet individually checked for raw-SQL (non-Drizzle-symbol) references to the physical table name — see the raw-SQL LATENT fixture test for why that check matters before this can be treated as final.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "committee_meeting_attendees",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'committeeMeetingAttendees' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/services/committee-workspace-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "committee_memberships",
    classification: "NEEDS_REVIEW",
    reason: "2 non-test reference(s) to 'committeeMemberships' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "conflict_review_committee",
    classification: "LATENT_UNREACHABLE",
    reason: "Round-7 scope-expansion scan: zero references to the 'conflictReviewCommittee' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files via a combined ripgrep pass across app/, actions/, lib/, services/. No known application code path queries this table today. NOT yet individually checked for raw-SQL (non-Drizzle-symbol) references to the physical table name — see the raw-SQL LATENT fixture test for why that check matters before this can be treated as final.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "council_elections",
    classification: "NEEDS_REVIEW",
    reason: "3 non-test reference(s) to 'councilElections' found (round-7 scope-expansion scan). At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/elections/[id]/route.ts","app/api/elections/[id]/vote/route.ts","app/api/elections/route.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "golden_shares",
    classification: "SYSTEM_ONLY",
    reason: "RESOLVED (round 8, governance family review; caller authority FIXED round 11): app/api/governance/golden-share/route.ts's GET+POST both execute entirely under withSystemContext, querying/inserting a SINGLE platform-wide Class-B share certificate row with NO organization_id filter at all (a global cooperative-governance construct, not tenant-shaped data). Round 8 flagged that both handlers gated on `auth: { minRole: 'admin' }` \u2014 an ORDINARY per-organization role tier (level 140 per lib/api-auth-guard.ts's ROLE_HIERARCHY), meaning any tenant's own org-admin could read/mutate this platform-wide record; confirmed as a real defect (lib/middleware/admin-auth.ts's own hasGoldenSharePrivileges() comment admits 'restricted to admins until council membership mapping is added' \u2014 an acknowledged placeholder, not intended production authority). FIXED round 11: both handlers now require `auth: { roles: ['clc_staff', 'clc_executive', 'system_admin'] }` (the same national/platform allow-list established in round 5's CLC dashboard and round 8's institutional topology fix) instead of `minRole`. Proven via app/api/governance/__tests__/governance-platform-authority-boundary.test.ts (real withApi(), not mocked \u2014 Org A/B negative proof: role 'admin'/'member' -> 403, never reaches withSystemContext; clc_staff/clc_executive/system_admin -> 200) plus a permanent allow-list regression guard. hasGoldenSharePrivileges() itself remains LATENT_UNWIRED (zero real callers, confirmed via grep) and was not modified \u2014 not in the reachable runtime surface.",
    supportingCapability: ["app/api/governance/golden-share/route.ts","app/api/governance/dashboard/route.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: ["SELECT","INSERT"],
    invocationAuthority: "PLATFORM_ADMIN",
    dbExecutionPrincipal: "SYSTEM_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "governance_events",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'governanceEvents' found (round-7 scope-expansion scan). At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/governance/telemetry/route.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "mission_audits",
    classification: "SYSTEM_ONLY",
    reason: "RESOLVED (round 8, governance family review; caller authority FIXED round 11): same shape as 'golden_shares' \u2014 app/api/governance/mission-audits/route.ts's GET+POST execute entirely under withSystemContext against a platform-wide audit-results table (audit_year/auditor_firm/etc.), NO organization_id filter. FIXED round 11: both handlers now require `auth: { roles: ['clc_staff', 'clc_executive', 'system_admin'] }` instead of `minRole: 'admin'` \u2014 proven by the same governance-platform-authority-boundary.test.ts negative proof and allow-list regression guard covering this file.",
    supportingCapability: ["app/api/governance/mission-audits/route.ts","app/api/governance/dashboard/route.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: ["SELECT","INSERT"],
    invocationAuthority: "PLATFORM_ADMIN",
    dbExecutionPrincipal: "SYSTEM_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "reserved_matter_votes",
    classification: "SYSTEM_ONLY",
    reason: "RESOLVED (round 8, governance family review; caller authority FIXED round 11): same shape as 'golden_shares'/'mission_audits'. app/api/governance/reserved-matters/route.ts (GET+POST), its [id]/route.ts PATCH (Class A vote tally), and its [id]/class-b-vote/route.ts POST (Class B council vote) all execute entirely under withSystemContext against a platform-wide reserved-matter-votes table, NO organization_id filter. FIXED round 11: all four handlers now require `auth: { roles: ['clc_staff', 'clc_executive', 'system_admin'] }` instead of `minRole: 'admin'` \u2014 proven by the same governance-platform-authority-boundary.test.ts negative proof and allow-list regression guard covering all three route files.",
    supportingCapability: ["app/api/governance/reserved-matters/[id]/class-b-vote/route.ts","app/api/governance/reserved-matters/[id]/route.ts","app/api/governance/reserved-matters/route.ts","app/api/governance/dashboard/route.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: ["SELECT","INSERT","UPDATE"],
    invocationAuthority: "PLATFORM_ADMIN",
    dbExecutionPrincipal: "SYSTEM_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "workbook_governance_lineage_entries",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'workbookGovernanceLineageEntries' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/workbook-pdf/loadWorkbookModules.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
]
