/**
 * db/rls-storage-authority/integrations-workers.ts
 *
 * PR #752 round 9: extracted from the single-file
 * db/rls-storage-authority-manifest.ts (which exceeded the repository's
 * 8000-line hard cap at 8009 lines — see
 * tooling/contract-tests/file-size-enforcement.test.ts) into semantic
 * domain modules. This module owns: Integrations, webhooks, workers, jobs, queues, sync.
 *
 * Domain boundaries were assigned mechanically by table-name keyword
 * matching against the entry's `table` field (see the one-time migration
 * script referenced in the round-9 commit message) — every entry's DATA
 * (classification, reason, privileges, authority) is unchanged from the
 * pre-split manifest; only its physical file location changed. Do not
 * hand-edit an entry's domain placement without also checking
 * db/__tests__/rls-storage-authority-registry-composition.test.ts, which
 * proves the composed registry is unaffected by which module an entry
 * lives in.
 *
 * Add NEW entries to whichever domain module most closely matches the
 * table's real subject matter; when genuinely ambiguous, prefer
 * reference-latent.ts (the catch-all) over forcing a bad fit elsewhere.
 */
import type { StorageAuthorityEntry } from './types';

export const integrationsWorkersEntries: StorageAuthorityEntry[] = [
  {
    table: "api_integrations",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'apiIntegrations' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/extensions/[id]/route.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "clc_sync_log",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Manually verified 2026-09-02: direct NOT NULL organization_id column (db/schema/clc-sync-schema.ts). Reachable via live HTTP routes app/api/clc/sync/route.ts, app/api/clc/dashboard/route.ts, app/api/clc/remittances/route.ts.",
    supportingCapability: ["app/api/clc/sync/route.ts","app/api/clc/dashboard/route.ts","app/api/clc/remittances/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "clc_webhook_log",
    classification: "LATENT_UNREACHABLE",
    reason: "Manually verified 2026-09-02: sole non-test reference services/clc/clc-api-integration.ts has zero callers anywhere under app/, actions/, lib/, services/, scripts/ (verified by name-search).",
    supportingCapability: ["services/clc/clc-api-integration.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "employer_timesheet_batches",
    classification: "NEEDS_REVIEW",
    reason: "4 non-test reference(s) to 'employerTimesheetBatches' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/[locale]/dashboard/employer-execution/timesheets/page.tsx","app/api/employer-execution/payroll-runs/route.ts","app/api/employer-execution/timesheets/route.ts","lib/workers/employer-execution/process-timesheet-validation.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "erp_connectors",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'erpConnectors' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "external_accounts",
    classification: "NEEDS_REVIEW",
    reason: "7 non-test reference(s) to 'externalAccounts' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/external-data/lrb/route.ts","app/api/external-data/route.ts","lib/integrations/adapters/accounting/freshbooks-adapter.ts","lib/integrations/adapters/accounting/quickbooks-adapter.ts","lib/integrations/adapters/accounting/sage-intacct-adapter.ts","lib/integrations/adapters/accounting/sync-utils.ts","lib/integrations/adapters/accounting/xero-adapter.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "external_benefit_coverage",
    classification: "NEEDS_REVIEW",
    reason: "2 non-test reference(s) to 'externalBenefitCoverage' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/integrations/adapters/insurance/greenshield-adapter.ts","lib/integrations/adapters/insurance/sunlife-adapter.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "external_benefit_dependents",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'externalBenefitDependents' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/integrations/adapters/insurance/sunlife-adapter.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "external_benefit_enrollments",
    classification: "NEEDS_REVIEW",
    reason: "2 non-test reference(s) to 'externalBenefitEnrollments' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/integrations/adapters/insurance/greenshield-adapter.ts","lib/integrations/adapters/insurance/sunlife-adapter.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "external_benefit_plans",
    classification: "NEEDS_REVIEW",
    reason: "2 non-test reference(s) to 'externalBenefitPlans' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/integrations/adapters/insurance/greenshield-adapter.ts","lib/integrations/adapters/insurance/sunlife-adapter.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "external_benefit_utilization",
    classification: "NEEDS_REVIEW",
    reason: "2 non-test reference(s) to 'externalBenefitUtilization' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/integrations/adapters/insurance/ia-adapter.ts","lib/integrations/adapters/insurance/manulife-adapter.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "external_calendar_attendees",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'externalCalendarAttendees' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "external_calendar_connections",
    classification: "NEEDS_REVIEW",
    reason: "10 non-test reference(s) to 'externalCalendarConnections' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/calendar-sync/connections/[id]/route.ts","app/api/calendar-sync/connections/[id]/sync/route.ts","app/api/calendar-sync/connections/route.ts","app/api/calendar-sync/google/callback/route.ts","app/api/calendar-sync/microsoft/callback/route.ts","app/api/cron/calendar-sync/route.ts","lib/external-calendar-sync/google-calendar-service.ts","lib/external-calendar-sync/microsoft-calendar-service.ts","services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "external_calendar_events",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'externalCalendarEvents' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "external_calendar_recurring_patterns",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'externalCalendarRecurringPatterns' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "external_calendars",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'externalCalendars' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "external_customers",
    classification: "NEEDS_REVIEW",
    reason: "6 non-test reference(s) to 'externalCustomers' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/integrations/adapters/accounting/freshbooks-adapter.ts","lib/integrations/adapters/accounting/quickbooks-adapter.ts","lib/integrations/adapters/accounting/sage-intacct-adapter.ts","lib/integrations/adapters/accounting/sync-utils.ts","lib/integrations/adapters/accounting/wave-adapter.ts","lib/integrations/adapters/accounting/xero-adapter.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "external_departments",
    classification: "NEEDS_REVIEW",
    reason: "3 non-test reference(s) to 'externalDepartments' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/integrations/adapters/hris/adp-adapter.ts","lib/integrations/adapters/hris/bamboohr-adapter.ts","lib/integrations/adapters/hris/workday-adapter.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "external_employees",
    classification: "NEEDS_REVIEW",
    reason: "5 non-test reference(s) to 'externalEmployees' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/integrations/adapters/hris/WORKDAY_USAGE.md","lib/integrations/adapters/hris/adp-adapter.ts","lib/integrations/adapters/hris/bamboohr-adapter.ts","lib/integrations/adapters/hris/sync-utils.ts","lib/integrations/adapters/hris/workday-adapter.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "external_insurance_beneficiaries",
    classification: "NEEDS_REVIEW",
    reason: "3 non-test reference(s) to 'externalInsuranceBeneficiaries' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/integrations/adapters/insurance/canadalife-adapter.ts","lib/integrations/adapters/insurance/ia-adapter.ts","lib/integrations/adapters/insurance/manulife-adapter.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "external_insurance_policies",
    classification: "NEEDS_REVIEW",
    reason: "4 non-test reference(s) to 'externalInsurancePolicies' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/graphql/resolvers.ts","lib/integrations/adapters/insurance/canadalife-adapter.ts","lib/integrations/adapters/insurance/ia-adapter.ts","lib/integrations/adapters/insurance/manulife-adapter.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "external_invoices",
    classification: "NEEDS_REVIEW",
    reason: "7 non-test reference(s) to 'externalInvoices' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/billing/invoices/route.ts","lib/integrations/adapters/accounting/freshbooks-adapter.ts","lib/integrations/adapters/accounting/quickbooks-adapter.ts","lib/integrations/adapters/accounting/sage-intacct-adapter.ts","lib/integrations/adapters/accounting/sync-utils.ts","lib/integrations/adapters/accounting/wave-adapter.ts","lib/integrations/adapters/accounting/xero-adapter.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "external_lms_completions",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'externalLmsCompletions' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/integrations/adapters/lms/linkedin-learning-adapter.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "external_lms_courses",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'externalLmsCourses' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/integrations/adapters/lms/linkedin-learning-adapter.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "external_lms_enrollments",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'externalLmsEnrollments' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/integrations/adapters/lms/linkedin-learning-adapter.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "external_lms_learners",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'externalLmsLearners' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/integrations/adapters/lms/linkedin-learning-adapter.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "external_lms_progress",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'externalLmsProgress' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/integrations/adapters/lms/linkedin-learning-adapter.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "external_payments",
    classification: "NEEDS_REVIEW",
    reason: "6 non-test reference(s) to 'externalPayments' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/integrations/adapters/accounting/freshbooks-adapter.ts","lib/integrations/adapters/accounting/quickbooks-adapter.ts","lib/integrations/adapters/accounting/sage-intacct-adapter.ts","lib/integrations/adapters/accounting/sync-utils.ts","lib/integrations/adapters/accounting/wave-adapter.ts","lib/integrations/adapters/accounting/xero-adapter.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "external_pension_beneficiaries",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'externalPensionBeneficiaries' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "external_pension_contributions",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'externalPensionContributions' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "external_pension_estimates",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'externalPensionEstimates' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "external_pension_plans",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'externalPensionPlans' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "external_pension_service_credits",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'externalPensionServiceCredits' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "external_positions",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'externalPositions' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/integrations/adapters/hris/workday-adapter.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "webhook_deliveries",
    classification: "LATENT_UNREACHABLE",
    reason: "Verified 2026-09-01 against LIVE staging DB: 26 columns, no organization_id — tenancy (if any) can only flow through webhook_id (NOT NULL, FK to a webhooks/integration record) or the nullable subscription_id. Two schema-conflicting declarations exist: db/schema/domains/infrastructure/integrations.ts (10 cols, webhook_id-keyed, references integrationWebhooks) and db/schema/integration-schema.ts (19 cols, subscription_id-keyed, references webhookSubscriptions) — BOTH are individually column-accurate against live (not stale/wrong, just different partial views), suggesting two historically-separate integration delivery flows share this one physical table. git grep across app/, lib/, services/ (excluding tests) found ZERO real production consumers of 'webhookDeliveries' from EITHER declaration — the earlier scan's 'app/api/extensions/[id]/route.ts' bypass flag was a false positive from the pre-fix scanner (that route only imports the unrelated 'apiIntegrations' export from the same integration-schema.ts module path). Given zero reachability, NOT canonicalized in this pass (doing so would require product-level judgment about which delivery flow, if either, is still current) — disposition is LATENT_UNREACHABLE, consistent with 'prove the disposition rather than mechanically canonicalize every historical module.' The schema conflict remains tracked in the fingerprint ratchet.",
    supportingCapability: ["db/schema/domains/infrastructure/integrations.ts","db/schema/integration-schema.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NORMAL",
  },
  {
    table: "ingestion_batches",
    classification: "NEEDS_REVIEW",
    reason: "4 non-test reference(s) to 'ingestionBatches' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/admin/ingest/retry/route.ts","app/api/grievances/import/route.ts","lib/ingestion/batch-ingest.ts","lib/ingestion/migration-metrics.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "integration_api_keys",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'integrationApiKeys' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/integrations/api-keys/route.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "integration_configs",
    classification: "NEEDS_REVIEW",
    reason: "3 non-test reference(s) to 'integrationConfigs' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/integrations/README.md","lib/integrations/adapters/hris/WORKDAY_USAGE.md","lib/integrations/factory.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "integration_partners",
    classification: "NEEDS_REVIEW",
    reason: "RECLASSIFIED 2026-09-02 (round 7, raw-SQL LATENT-detection correction): this table was previously classified LATENT_UNREACHABLE based on a Drizzle-EXPORT-NAME-only reachability scan, which cannot find raw SQL references. A raw-SQL detection pass (see db/__tests__/rls-storage-authority-manifest-raw-sql-latent.test.ts for the detector/fixture) found real, direct raw-SQL table references (db.execute(sql`... FROM/INTO/UPDATE integration_partners ...`) or an equivalent quoted-table-name repository reference) in the file(s) listed below. Full HTTP-reachability/auth-boundary trace not yet completed.",
    supportingCapability: ["app/[locale]/dashboard/integrations/page.tsx"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "integration_sync_log",
    classification: "LATENT_UNREACHABLE",
    reason: "Manually verified 2026-09-02: sole non-test reference lib/integrations/sync-engine.ts has zero callers anywhere under app/, actions/, lib/, services/, scripts/ (verified by name-search).",
    supportingCapability: ["lib/integrations/sync-engine.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "integration_sync_schedules",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'integrationSyncSchedules' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/integrations/adapters/hris/WORKDAY_USAGE.md"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "integration_webhooks",
    classification: "NEEDS_REVIEW",
    reason: "RECLASSIFIED 2026-09-02 (round 7, raw-SQL LATENT-detection correction): this table was previously classified LATENT_UNREACHABLE based on a Drizzle-EXPORT-NAME-only reachability scan, which cannot find raw SQL references. A raw-SQL detection pass (see db/__tests__/rls-storage-authority-manifest-raw-sql-latent.test.ts for the detector/fixture) found real, direct raw-SQL table references (db.execute(sql`... FROM/INTO/UPDATE integration_webhooks ...`) or an equivalent quoted-table-name repository reference) in the file(s) listed below. Full HTTP-reachability/auth-boundary trace not yet completed.",
    supportingCapability: ["app/[locale]/dashboard/integrations/page.tsx"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "job_classifications",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'jobClassifications' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "job_postings",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'jobPostings' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "job_saved",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'jobSaved' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "mobile_sync_queue",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'mobileSyncQueue' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/mobile/mobile-engine.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "stripe_webhook_events",
    classification: "LATENT_UNREACHABLE",
    reason: "CORRECTED 2026-09-01 (round 7): the round-6 entry was itself a false classification — its verification grep only matched single-line `pgTable('stripe_webhook_events'` declarations and missed the real, multi-line declarations at db/schema/domains/finance/payments.ts and db/schema/financial-payments-schema.ts (both carry an organization_id-indexed 'orgIdx'). A repo-wide, multi-line-aware search (scripts/rls-storage-reachability-audit.ts) confirms these ARE real union-eyes-native declarations, but zero non-test references to 'stripeWebhookEvents' exist anywhere in app/, actions/, lib/, or services/ (excluding financial-service, which separately declares a same-named table in its own database, used by its own payment-processing/reconciliation-engine). Correct disposition is therefore LATENT_UNREACHABLE, not SEPARATE_DATABASE_BOUNDARY.",
    supportingCapability: ["db/schema/domains/finance/payments.ts","db/schema/financial-payments-schema.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "sync_jobs",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'syncJobs' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/integrations/sync-engine.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "webhook_events",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'webhookEvents' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/integrations/webhook-router.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "webhook_subscriptions",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'webhookSubscriptions' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "external_data_sync_log",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'externalDataSyncLog' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/services/external-data/wage-enrichment-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "foreign_workers",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'foreignWorkers' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["services/lmbp-immigration-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "ingestion_records",
    classification: "NEEDS_REVIEW",
    reason: "5 non-test reference(s) to 'ingestionRecords' found (round-7 scope-expansion scan). At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/admin/ingest/retry/route.ts","app/api/grievances/import/route.ts","lib/ingestion/batch-ingest.ts","lib/ingestion/fuzzy-dedup.ts","lib/ingestion/migration-metrics.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "integration_sync_logs",
    classification: "LATENT_UNREACHABLE",
    reason: "Round-7 scope-expansion scan: zero references to the 'integrationSyncLogs' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files via a combined ripgrep pass across app/, actions/, lib/, services/. No known application code path queries this table today. NOT yet individually checked for raw-SQL (non-Drizzle-symbol) references to the physical table name — see the raw-SQL LATENT fixture test for why that check matters before this can be treated as final.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "lrb_sync_log",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'lrbSyncLog' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/services/external-data/lrb-unified-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "signature_webhooks_log",
    classification: "LATENT_UNREACHABLE",
    reason: "Round-7 scope-expansion scan: zero references to the 'signatureWebhooksLog' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files via a combined ripgrep pass across app/, actions/, lib/, services/. No known application code path queries this table today. NOT yet individually checked for raw-SQL (non-Drizzle-symbol) references to the physical table name — see the raw-SQL LATENT fixture test for why that check matters before this can be treated as final.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "webhook_receipts",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'webhookReceipts' found (round-7 scope-expansion scan). At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["lib/services/rewards/webhook-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
]
