/**
 * db/rls-storage-authority/organizations-membership.ts
 *
 * PR #752 round 9: extracted from the single-file
 * db/rls-storage-authority-manifest.ts (which exceeded the repository's
 * 8000-line hard cap at 8009 lines — see
 * tooling/contract-tests/file-size-enforcement.test.ts) into semantic
 * domain modules. This module owns: Organizations, membership, invites, roles, hierarchy.
 *
 * Domain boundaries were assigned mechanically by table-name keyword
 * matching against the entry's `table` field (see the one-time migration
 * script referenced in the round-9 commit message) — every entry's DATA
 * (classification, reason, privileges, authority) is unchanged from the
 * pre-split manifest; only its physical file location changed. Do not
 * hand-edit an entry's domain placement without also checking
 * db/__tests__/rls-storage-authority-registry-composition.test.ts, which
 * proves the composed registry is unaffected by which module an entry
 * lives in.
 *
 * Add NEW entries to whichever domain module most closely matches the
 * table's real subject matter; when genuinely ambiguous, prefer
 * reference-latent.ts (the catch-all) over forcing a bad fit elsewhere.
 */
import type { StorageAuthorityEntry } from './types';

export const organizationsMembershipEntries: StorageAuthorityEntry[] = [
  {
    table: "clc_organization_sync_log",
    classification: "SYSTEM_ONLY",
    reason: "Manually verified 2026-09-02, corrected 2026-09-02 (round 4 review): organization_id is NULLABLE (\"Nullable for batch sync operations\" per db/schema/clc-sync-audit-schema.ts) — cross-affiliate CLC federation sync audit log, not a per-tenant-partitionable resource. Reachable via app/[locale]/dashboard/clc/staff/page.tsx; that route is gated by app/[locale]/dashboard/clc/layout.tsx's server-side requireUser()+hasMinRole(\"clc_staff\") check restricting /dashboard/clc/* to CLC Staff (role 180) and above. Round-4 correction: request-level PLATFORM_ADMIN authorization does not by itself justify union_eyes_runtime DB access to a SYSTEM_ONLY table — getCLCOperationalMetrics() previously queried this table via the ordinary db import despite the role gate; fixed to run inside withSystemContext(), so dbExecutionPrincipal is SYSTEM_RUNTIME (not TENANT_RUNTIME) and requiredRuntimePrivileges is [] (union_eyes_runtime gets nothing; only union_eyes_system needs SELECT). services/clc/clc-api-integration.ts (the other listed reference) has zero independent callers.",
    supportingCapability: ["app/[locale]/dashboard/clc/staff/page.tsx","app/[locale]/dashboard/clc/layout.tsx"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: ["SELECT"],
    invocationAuthority: "PLATFORM_ADMIN",
    dbExecutionPrincipal: "SYSTEM_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "external_pension_members",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'externalPensionMembers' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "icra_organizations",
    classification: "SYSTEM_ONLY",
    reason: "ICRA_PSEUDONYMOUS_NO_LOGIN=APPROVED, ASSESSMENT_ID_AS_SOLE_BEARER_AUTHORITY=REJECTED (PR #752): the pseudonymous product model is intentional, but assessmentId alone must never authorize DB access. lib/icra/assessment-capability.ts adds a hashed, purpose-bound bearer capability; every route touching an existing assessment now verifies it before entering withSystemContext. Verified 2026-09-01 (round 7, ICRA capability architecture): a pseudonymous org-context record created only via withSystemContext() from app/api/icra/start/route.ts — conceptually distinct from a Union Eyes tenant organization (organizations table); no direct route reads or updates it independently of assessment creation.",
    supportingCapability: ["app/api/icra/start/route.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "SYSTEM_SCHEDULE",
    dbExecutionPrincipal: "SYSTEM_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "job_applications",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'jobApplications' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "member_addresses",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'memberAddresses' found. No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["services/tax-slip-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "member_arrears",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01 (round 6, Phase-3A priority tranche): direct NOT NULL organization_id column, reachable via live HTTP route(s) app/api/members/[id]/arrears/route.ts. org-scoped member arrears endpoint; SELECT+UPDATE confirmed (arrears status/amount recalculation). Minimum runtime privilege set from confirmed DML verbs (crudRoutes handler destructuring and/or direct .insert/.update/.delete/.select call-site evidence), not defaulted to FULL_DML.",
    supportingCapability: ["app/api/members/[id]/arrears/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "member_breaks",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01 (round 6, Phase-3A priority tranche): direct NOT NULL organization_id column, reachable via live HTTP route(s) app/api/members/[id]/breaks/route.ts. org-scoped member-breaks CRUD route; crudRoutes destructures GET+POST+PATCH+DELETE. Minimum runtime privilege set from confirmed DML verbs (crudRoutes handler destructuring and/or direct .insert/.update/.delete/.select call-site evidence), not defaulted to FULL_DML.",
    supportingCapability: ["app/api/members/[id]/breaks/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "member_certifications",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01 (round 6, Phase-3A priority tranche): direct NOT NULL organization_id column, reachable via live HTTP route(s) app/api/education/certifications/route.ts. org-scoped certification CRUD route; crudRoutes destructures GET+POST only (no PATCH/DELETE exposed). Minimum runtime privilege set from confirmed DML verbs (crudRoutes handler destructuring and/or direct .insert/.update/.delete/.select call-site evidence), not defaulted to FULL_DML.",
    supportingCapability: ["app/api/education/certifications/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "member_consents",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'memberConsents' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "member_contact_preferences",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'memberContactPreferences' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "member_dues_issues",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01 (round 6, Phase-3A priority tranche): direct NOT NULL organization_id column, reachable via live HTTP route(s) app/api/members/[id]/dues-issues/route.ts. org-scoped dues-issue flagging endpoint; SELECT+INSERT confirmed. Minimum runtime privilege set from confirmed DML verbs (crudRoutes handler destructuring and/or direct .insert/.update/.delete/.select call-site evidence), not defaulted to FULL_DML.",
    supportingCapability: ["app/api/members/[id]/dues-issues/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "member_dues_ledger",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01 (round 6, Phase-3A priority tranche): direct NOT NULL organization_id column, reachable via live HTTP route(s) app/api/dues/balance/route.ts, app/api/dues/deductions/route.ts. org-scoped, append-only dues ledger; SELECT+INSERT confirmed across the dues balance/deduction routes, no UPDATE/DELETE detected (ledger entries are immutable). Minimum runtime privilege set from confirmed DML verbs (crudRoutes handler destructuring and/or direct .insert/.update/.delete/.select call-site evidence), not defaulted to FULL_DML.",
    supportingCapability: ["app/api/dues/balance/route.ts","app/api/dues/deductions/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "member_employment",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01 (round 6, Phase-3A priority tranche): direct NOT NULL organization_id column, reachable via live HTTP route(s) app/api/members/[id]/employment/route.ts. org-scoped member employment CRUD item route; crudRoutes destructures GET+PATCH+DELETE (no POST — employment record created elsewhere). Minimum runtime privilege set from confirmed DML verbs (crudRoutes handler destructuring and/or direct .insert/.update/.delete/.select call-site evidence), not defaulted to FULL_DML.",
    supportingCapability: ["app/api/members/[id]/employment/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "member_employment_details",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'memberEmploymentDetails' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "member_history_events",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01 (round 6, Phase-3A priority tranche): direct NOT NULL organization_id column, reachable via live HTTP route(s) app/api/members/[id]/history/route.ts. org-scoped member history endpoint; SELECT+UPDATE+DELETE confirmed (event correction/removal). Minimum runtime privilege set from confirmed DML verbs (crudRoutes handler destructuring and/or direct .insert/.update/.delete/.select call-site evidence), not defaulted to FULL_DML.",
    supportingCapability: ["app/api/members/[id]/history/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "member_jurisdiction_preferences",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01, corrected 2026-09-02 (round 5 — the prior citation app/api/members/[id]/jurisdiction-preferences/route.ts does not exist): direct NOT NULL organization_id column; real, verified non-test reference is app/api/precedents/jurisdiction-preferences/route.ts (withApi, minRole member for GET/PUT), plain `db` import, no withSystemContext.",
    supportingCapability: ["app/api/precedents/jurisdiction-preferences/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "member_leaves",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'memberLeaves' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "member_relationship_scores",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'memberRelationshipScores' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "member_segments",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01 (round 6, Phase-3A priority tranche): direct NOT NULL organization_id column, reachable via live HTTP route(s) app/api/members/segments/route.ts. org-scoped member-segment management route; crudRoutes GET+POST plus confirmed UPDATE+DELETE in production code (segment membership recalculation/removal). Minimum runtime privilege set from confirmed DML verbs (crudRoutes handler destructuring and/or direct .insert/.update/.delete/.select call-site evidence), not defaulted to FULL_DML.",
    supportingCapability: ["app/api/members/segments/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "org_entitlements",
    classification: "NEEDS_REVIEW",
    reason: "3 non-test reference(s) to 'orgEntitlements' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/entitlements/route.ts","services/platform-economics/contract-service.ts","services/platform-economics/entitlement-guard.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "org_subscriptions",
    classification: "NEEDS_REVIEW",
    reason: "8 non-test reference(s) to 'orgSubscriptions' found. At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/billing/send-batch/route.ts","app/api/billing/subscriptions/[id]/route.ts","app/api/billing/subscriptions/route.ts","app/api/pilot/apply/[id]/commercial-transition/route.ts","services/platform-economics/billing-service.ts","services/platform-economics/dunning-service.ts","services/platform-economics/pricing-template-service.ts","services/platform-economics/subscription-lifecycle-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "organization_benchmark_snapshots",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'organizationBenchmarkSnapshots' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "organization_billing_config",
    classification: "SYSTEM_ONLY",
    reason: "Corrected 2026-09-02 (independent review of the 2026-09-01 batch): the only identified live root is POST /api/admin/billing-cycles/trigger-scheduled, which requires platform_lead and calls BillingScheduler.manualTrigger(). BillingScheduler.getOrganizationsForBilling() deliberately enumerates organization_billing_config across ALL organizations to build the scheduled billing run — this is bounded privileged/system execution, not ordinary tenant authority, even though the table itself carries a NOT NULL organization_id (db/schema/domains/finance/billing-config.ts). Fixed: getOrganizationsForBilling() now runs inside withSystemContext() (was: plain db). The platform_lead role check in the route remains the request-facing authorization; withSystemContext is only the execution mechanism, never treated as authorization itself. Regression test: lib/jobs/__tests__/billing-scheduler.test.ts asserts withSystemContext is used and the ordinary db connection is never touched for this query; the route's existing 401/403 tests (app/api/__tests__/admin-billing-cycles-trigger-scheduled.route.test.ts) already prove a non-platform_lead caller is rejected before any DB access.",
    supportingCapability: ["lib/jobs/billing-scheduler.ts","app/api/admin/billing-cycles/trigger-scheduled/route.ts","lib/db/with-rls-context.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: ["SELECT"],
    invocationAuthority: "PLATFORM_ADMIN",
    dbExecutionPrincipal: "SYSTEM_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "organization_contacts",
    classification: "LATENT_UNREACHABLE",
    reason: "Manually verified 2026-09-02: sole non-test reference is services/clc/remittance-notifications.ts, whose exports have zero callers anywhere under app/, actions/, lib/, services/, scripts/ (verified by name-search, see notification_log finding above — same dead file).",
    supportingCapability: ["services/clc/remittance-notifications.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "organization_sharing_settings",
    classification: "LATENT_UNREACHABLE",
    reason: "Manually verified 2026-09-02: direct NOT NULL organization_id column (db/schema/domains/infrastructure/sharing.ts; duplicated verbatim at db/schema/sharing-permissions-schema.ts, a pre-consolidation leftover per db/schema/index.ts's \"Migration Status: COMPLETE — eliminating 18 duplicates\" note — the domains/** copy is canonical). Sole union-eyes reference is lib/clc/data-products.ts, which has zero callers anywhere under app/, actions/, lib/, services/, scripts/ (verified by name-search). The only other reference is services/financial-service/** — a separately deployed service, not part of union-eyes' own request handling.",
    supportingCapability: ["lib/clc/data-products.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "pension_members",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01 (round 6, Phase-3A priority tranche): direct NOT NULL organization_id column, reachable via live HTTP route(s) app/api/pension/members/route.ts. org-scoped pension member enrollment endpoint; SELECT+INSERT confirmed. Minimum runtime privilege set from confirmed DML verbs (crudRoutes handler destructuring and/or direct .insert/.update/.delete/.select call-site evidence), not defaulted to FULL_DML.",
    supportingCapability: ["app/api/pension/members/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "role_tenure_history",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'roleTenureHistory' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "duplicate_group_members",
    classification: "NEEDS_REVIEW",
    reason: "2 non-test reference(s) to 'duplicateGroupMembers' found (round-7 scope-expansion scan). At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/admin/duplicates/route.ts","lib/ingestion/fuzzy-dedup.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "federation_memberships",
    classification: "LATENT_UNREACHABLE",
    reason: "Round-7 scope-expansion scan: zero references to the 'federationMemberships' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files via a combined ripgrep pass across app/, actions/, lib/, services/. No known application code path queries this table today. NOT yet individually checked for raw-SQL (non-Drizzle-symbol) references to the physical table name — see the raw-SQL LATENT fixture test for why that check matters before this can be treated as final.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "gss_applications",
    classification: "NEEDS_REVIEW",
    reason: "1 non-test reference(s) to 'gssApplications' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["services/lmbp-immigration-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "indigenous_member_data",
    classification: "NEEDS_REVIEW",
    reason: "2 non-test reference(s) to 'indigenousMemberData' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/services/indigenous-data-service.ts","services/indigenous-data-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "member_location_consent",
    classification: "NEEDS_REVIEW",
    reason: "3 non-test reference(s) to 'memberLocationConsent' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["lib/services/geofence-privacy-service.ts","lib/services/location-tracking-service.ts","services/geofence-privacy-service.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "organization_sharing_grants",
    classification: "NEEDS_REVIEW",
    reason: "2 non-test reference(s) to 'organizationSharingGrants' found (round-7 scope-expansion scan). No obvious HTTP-route/action/cron/webhook reference found in this scan; likely internal-library-only, but exact reachability not yet traced.",
    supportingCapability: ["services/financial-service/drizzle/schema.ts","services/financial-service/src/db/schema.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "NORMAL",
  },
  {
    table: "pilot_applications",
    classification: "NEEDS_REVIEW",
    reason: "10 non-test reference(s) to 'pilotApplications' found (round-7 scope-expansion scan). At least one reference is under an app/api/**/route.ts, actions/, cron, or webhook path (RUNTIME-REACHABLE HINT — prioritize this table for manual review).",
    supportingCapability: ["app/api/pilot/apply/[id]/artifacts/route.ts","app/api/pilot/apply/[id]/commercial-transition/route.ts","app/api/pilot/apply/[id]/commercialization-timeline/route.ts","app/api/pilot/apply/[id]/intelligence/route.ts","app/api/pilot/apply/[id]/package-export/route.ts","app/api/pilot/apply/[id]/proposal/route.ts","app/api/pilot/apply/[id]/reference-profile/route.ts","app/api/pilot/apply/[id]/route.ts","app/api/pilot/apply/route.ts","lib/pilot/pilot-ownership.ts"],
    requiredRuntimePrivileges: "TBD",
    requiredSystemPrivileges: "TBD",
    invocationAuthority: "TBD",
    dbExecutionPrincipal: "TBD",
    reviewPriority: "HIGH",
  },
  {
    table: "applications",
    classification: "LATENT_UNREACHABLE",
    reason: "PR #752 round 8: db/schema-applications.ts's Multi-App Discriminator registry — declared in a sibling file OUTSIDE db/schema/** (SCHEMA_ROOT's walk never visited it; see scripts/generate-public-schema-grant-census.ts's ADDITIONAL_PUBLIC_SCHEMA_FILES for the census-completeness fix). Only real reference is a FK column (organizations.appId references(() => applications.id) in db/schema-organizations.ts) and its barrel re-export in db/index.ts. Zero '.from(applications)'/'.insert(applications)'/'.update(applications)'/'.delete(applications)' call sites and zero raw-SQL 'FROM/INTO/UPDATE applications' references found across app/, actions/, lib/, services/ outside __tests__/**.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "org_configurations",
    classification: "TENANT_RLS_REQUIRED",
    reason: "PR #752 round 8: db/schema-organizations.ts, another sibling file outside SCHEMA_ROOT's walk (same census-completeness fix as 'applications'). Two independent write paths found: (1) lib/representation/protocol-service.ts's getRepresentationProtocol/saveRepresentationProtocol/resetRepresentationProtocol — REAL, reachable via app/api/admin/representation-protocol/route.ts (withAdminAuth, org-scoped, organizationId taken from the authenticated caller's own context) and consumed read-only by lib/case-assignment-engine.ts. Uses plain `db` with organizationId as an app-level WHERE/values filter, NOT wrapped in withRLSContext — no DB-level RLS session var is set on this path today, a latent gap tracked here (not fixed this round; org_configurations was never 0108-protected and has no RLS policy yet, hence TENANT_RLS_REQUIRED rather than an already-closed classification). (2) actions/admin-actions.ts's getSystemConfigs/updateSystemConfig — LATENT_UNWIRED: actions/admin-actions.ts has zero real importers anywhere in app/lib/actions/services/components (confirmed via grep), matching the round-5 lib/workers/** dead-code precedent; not counted toward required privileges.",
    supportingCapability: ["app/api/admin/representation-protocol/route.ts","lib/representation/protocol-service.ts","lib/case-assignment-engine.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "org_usage",
    classification: "LATENT_UNREACHABLE",
    reason: "PR #752 round 8: db/schema-organizations.ts (sibling-file census fix, see 'applications'). Only reference is actions/admin-actions.ts's getSystemStats — that whole module (actions/admin-actions.ts) has zero real importers anywhere in app/lib/actions/services/components (confirmed via grep, no barrel/indirect import found either), matching the round-5 lib/workers/** dead-code precedent. Zero raw-SQL references found either.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "organization_relationships",
    classification: "SYSTEM_ONLY",
    reason: "PR #752 round 8: db/schema-organizations.ts (sibling-file census fix, see 'applications'). Two paths found: (1) db/queries/organization-queries.ts's createOrganizationRelationship/getOrganizationRelationships (withRLSContext-wrapped, tenant-scoped by parentOrgId/childOrgId) — LATENT_UNWIRED, zero real callers found anywhere outside that file itself. (2) lib/organizational-topology/source.ts's getInstitutionalGraph() — REAL, reads ALL organization_relationships with no per-org filter (a national/cross-affiliate topology view), consumed by 3 dashboard pages (organizational-topology, organizational-chronology, organizational-observability). Found and fixed a REAL cross-org exposure bug this round: those 3 pages were gated only by requireUser() (any authenticated user, any role) — restricted to clc_staff/clc_executive/system_admin via the new lib/organizational-topology/access.ts, mirroring the round-5 CLC-dashboard precedent (see lib/auth/__tests__/clc-national-role-boundary.test.ts). getInstitutionalGraph() itself was also moved from plain `db` to withSystemContext so the DB-level boundary matches that app-level authority rather than relying on ordinary tenant-RLS routing to happen to permit a cross-org read.",
    supportingCapability: ["app/[locale]/dashboard/organizational-topology/page.tsx","app/[locale]/dashboard/organizational-chronology/page.tsx","app/[locale]/dashboard/organizational-observability/page.tsx","lib/organizational-topology/source.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: ["SELECT"],
    invocationAuthority: "PLATFORM_ADMIN",
    dbExecutionPrincipal: "SYSTEM_RUNTIME",
    reviewPriority: "NONE",
  },
]
