/**
 * db/rls-storage-authority/organizations-membership.ts
 *
 * PR #752 round 9: extracted from the single-file
 * db/rls-storage-authority-manifest.ts (which exceeded the repository's
 * 8000-line hard cap at 8009 lines — see
 * tooling/contract-tests/file-size-enforcement.test.ts) into semantic
 * domain modules. This module owns: Organizations, membership, invites, roles, hierarchy.
 *
 * Domain boundaries were assigned mechanically by table-name keyword
 * matching against the entry's `table` field (see the one-time migration
 * script referenced in the round-9 commit message) — every entry's DATA
 * (classification, reason, privileges, authority) is unchanged from the
 * pre-split manifest; only its physical file location changed. Do not
 * hand-edit an entry's domain placement without also checking
 * db/__tests__/rls-storage-authority-registry-composition.test.ts, which
 * proves the composed registry is unaffected by which module an entry
 * lives in.
 *
 * Add NEW entries to whichever domain module most closely matches the
 * table's real subject matter; when genuinely ambiguous, prefer
 * reference-latent.ts (the catch-all) over forcing a bad fit elsewhere.
 */
import type { StorageAuthorityEntry } from './types';

export const organizationsMembershipEntries: StorageAuthorityEntry[] = [
  {
    table: "clc_organization_sync_log",
    classification: "SYSTEM_ONLY",
    reason: "Manually verified 2026-09-02, corrected 2026-09-02 (round 4 review): organization_id is NULLABLE (\"Nullable for batch sync operations\" per db/schema/clc-sync-audit-schema.ts) — cross-affiliate CLC federation sync audit log, not a per-tenant-partitionable resource. Reachable via app/[locale]/dashboard/clc/staff/page.tsx; that route is gated by app/[locale]/dashboard/clc/layout.tsx's server-side requireUser()+hasMinRole(\"clc_staff\") check restricting /dashboard/clc/* to CLC Staff (role 180) and above. Round-4 correction: request-level PLATFORM_ADMIN authorization does not by itself justify union_eyes_runtime DB access to a SYSTEM_ONLY table — getCLCOperationalMetrics() previously queried this table via the ordinary db import despite the role gate; fixed to run inside withSystemContext(), so dbExecutionPrincipal is SYSTEM_RUNTIME (not TENANT_RUNTIME) and requiredRuntimePrivileges is [] (union_eyes_runtime gets nothing; only union_eyes_system needs SELECT). services/clc/clc-api-integration.ts (the other listed reference) has zero independent callers.",
    supportingCapability: ["app/[locale]/dashboard/clc/staff/page.tsx","app/[locale]/dashboard/clc/layout.tsx"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: ["SELECT"],
    invocationAuthority: "PLATFORM_ADMIN",
    dbExecutionPrincipal: "SYSTEM_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "external_pension_members",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'externalPensionMembers' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "icra_organizations",
    classification: "SYSTEM_ONLY",
    reason: "ICRA_PSEUDONYMOUS_NO_LOGIN=APPROVED, ASSESSMENT_ID_AS_SOLE_BEARER_AUTHORITY=REJECTED (PR #752): the pseudonymous product model is intentional, but assessmentId alone must never authorize DB access. lib/icra/assessment-capability.ts adds a hashed, purpose-bound bearer capability; every route touching an existing assessment now verifies it before entering withSystemContext. Verified 2026-09-01 (round 7, ICRA capability architecture): a pseudonymous org-context record created only via withSystemContext() from app/api/icra/start/route.ts — conceptually distinct from a Union Eyes tenant organization (organizations table); no direct route reads or updates it independently of assessment creation.",
    supportingCapability: ["app/api/icra/start/route.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "SYSTEM_SCHEDULE",
    dbExecutionPrincipal: "SYSTEM_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "job_applications",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'jobApplications' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "member_addresses",
    classification: "LATENT_UNREACHABLE",
    reason: "Resolved 2026-09-02 (round 17): its sole non-test reference, services/tax-slip-service.ts's TaxSlipService.generateT4ASlips()/generateRL1Slips()/getMemberTaxInfo(), has ZERO real callers anywhere under app/, actions/, lib/, services/ (verified by exact-name search for the class and both static method names). The only file matching a loose 'TaxSlipService' substring search, lib/api/tax-slip-service-api.ts, is an unrelated auto-generated Django-REST-proxy boilerplate client (calls /api/finance/tax-slip-service/ over HTTP, never imports the real class) — the same false-positive-reference class discovered this round for gss_applications (see that entry); both trace back to one of 5 near-identical lib/api/*-service-api.ts boilerplate files.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "member_arrears",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01 (round 6, Phase-3A priority tranche): direct NOT NULL organization_id column, reachable via live HTTP route(s) app/api/members/[id]/arrears/route.ts. org-scoped member arrears endpoint; SELECT+UPDATE confirmed (arrears status/amount recalculation). Minimum runtime privilege set from confirmed DML verbs (crudRoutes handler destructuring and/or direct .insert/.update/.delete/.select call-site evidence), not defaulted to FULL_DML.",
    supportingCapability: ["app/api/members/[id]/arrears/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "member_breaks",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01 (round 6, Phase-3A priority tranche): direct NOT NULL organization_id column, reachable via live HTTP route(s) app/api/members/[id]/breaks/route.ts. org-scoped member-breaks CRUD route; crudRoutes destructures GET+POST+PATCH+DELETE. Minimum runtime privilege set from confirmed DML verbs (crudRoutes handler destructuring and/or direct .insert/.update/.delete/.select call-site evidence), not defaulted to FULL_DML.",
    supportingCapability: ["app/api/members/[id]/breaks/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "member_certifications",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01 (round 6, Phase-3A priority tranche): direct NOT NULL organization_id column, reachable via live HTTP route(s) app/api/education/certifications/route.ts. org-scoped certification CRUD route; crudRoutes destructures GET+POST only (no PATCH/DELETE exposed). Minimum runtime privilege set from confirmed DML verbs (crudRoutes handler destructuring and/or direct .insert/.update/.delete/.select call-site evidence), not defaulted to FULL_DML.",
    supportingCapability: ["app/api/education/certifications/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "member_consents",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'memberConsents' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "member_contact_preferences",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'memberContactPreferences' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "member_dues_issues",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01 (round 6, Phase-3A priority tranche): direct NOT NULL organization_id column, reachable via live HTTP route(s) app/api/members/[id]/dues-issues/route.ts. org-scoped dues-issue flagging endpoint; SELECT+INSERT confirmed. Minimum runtime privilege set from confirmed DML verbs (crudRoutes handler destructuring and/or direct .insert/.update/.delete/.select call-site evidence), not defaulted to FULL_DML.",
    supportingCapability: ["app/api/members/[id]/dues-issues/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "member_dues_ledger",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01 (round 6, Phase-3A priority tranche): direct NOT NULL organization_id column, reachable via live HTTP route(s) app/api/dues/balance/route.ts, app/api/dues/deductions/route.ts. org-scoped, append-only dues ledger; SELECT+INSERT confirmed across the dues balance/deduction routes, no UPDATE/DELETE detected (ledger entries are immutable). Minimum runtime privilege set from confirmed DML verbs (crudRoutes handler destructuring and/or direct .insert/.update/.delete/.select call-site evidence), not defaulted to FULL_DML.",
    supportingCapability: ["app/api/dues/balance/route.ts","app/api/dues/deductions/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "member_employment",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01 (round 6, Phase-3A priority tranche): direct NOT NULL organization_id column, reachable via live HTTP route(s) app/api/members/[id]/employment/route.ts. org-scoped member employment CRUD item route; crudRoutes destructures GET+PATCH+DELETE (no POST — employment record created elsewhere). Minimum runtime privilege set from confirmed DML verbs (crudRoutes handler destructuring and/or direct .insert/.update/.delete/.select call-site evidence), not defaulted to FULL_DML.",
    supportingCapability: ["app/api/members/[id]/employment/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "member_employment_details",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'memberEmploymentDetails' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "member_history_events",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01 (round 6, Phase-3A priority tranche): direct NOT NULL organization_id column, reachable via live HTTP route(s) app/api/members/[id]/history/route.ts. org-scoped member history endpoint; SELECT+UPDATE+DELETE confirmed (event correction/removal). Minimum runtime privilege set from confirmed DML verbs (crudRoutes handler destructuring and/or direct .insert/.update/.delete/.select call-site evidence), not defaulted to FULL_DML.",
    supportingCapability: ["app/api/members/[id]/history/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "member_jurisdiction_preferences",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01, corrected 2026-09-02 (round 5 — the prior citation app/api/members/[id]/jurisdiction-preferences/route.ts does not exist): direct NOT NULL organization_id column; real, verified non-test reference is app/api/precedents/jurisdiction-preferences/route.ts (withApi, minRole member for GET/PUT), plain `db` import, no withSystemContext.",
    supportingCapability: ["app/api/precedents/jurisdiction-preferences/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "member_leaves",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'memberLeaves' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "member_relationship_scores",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'memberRelationshipScores' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "member_segments",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01 (round 6, Phase-3A priority tranche): direct NOT NULL organization_id column, reachable via live HTTP route(s) app/api/members/segments/route.ts. org-scoped member-segment management route; crudRoutes GET+POST plus confirmed UPDATE+DELETE in production code (segment membership recalculation/removal). Minimum runtime privilege set from confirmed DML verbs (crudRoutes handler destructuring and/or direct .insert/.update/.delete/.select call-site evidence), not defaulted to FULL_DML.",
    supportingCapability: ["app/api/members/segments/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "org_entitlements",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Resolved 2026-09-02 (round 17): direct NOT NULL organization_id column (db/schema/domains/finance/contracts.ts). app/api/entitlements/route.ts (GET) filters by the withApi-resolved organizationId, plain db, no RLS today. services/platform-economics/entitlement-guard.ts's requireEntitlement()/checkEntitlement() (SELECT only) are called with the caller's own resolved organizationId across dozens of feature-gated routes (grievances/cases/documents/AI/finance/billing/etc). services/platform-economics/contract-service.ts's real reachable function, createContract() (called from app/api/contracts/route.ts POST, minRole:'admin', context-resolved organizationId, never body-supplied), does NOT itself touch orgEntitlements — only activateContract()/terminateContract() do (INSERT/UPDATE, both correctly scoped by the contract's own organizationId), but BOTH have zero real callers anywhere (confirmed by exact function-name search) — contracts are created but never activated/terminated in the live app today, a product-completeness gap, not a security one (documented, not fixed — out of this round's bounded scope). Recorded privileges reflect only the CONFIRMED-reachable SELECT path.",
    supportingCapability: ["app/api/entitlements/route.ts","services/platform-economics/entitlement-guard.ts","app/api/contracts/route.ts"],
    requiredRuntimePrivileges: ["SELECT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "org_subscriptions",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Resolved 2026-09-02 (round 17): direct NOT NULL organization_id column (db/schema/domains/finance/platform-billing.ts). app/api/billing/subscriptions/route.ts GET/POST both org-scoped (minRole 'member'/'steward', context-resolved organizationId). services/platform-economics/subscription-lifecycle-service.ts's pauseSubscription/resumeSubscription/expireTrials/getTrialsEndingSoon were already hardened in round 3 (require + WHERE-enforce an explicit organizationId param, closing a prior cross-org pause/resume IDOR). Confirmed still correct this round; also re-confirmed processAutoRenewals() remains a documented, deliberately cross-org global renewal sweep with ZERO production callers (per its own doc comment, added round 3) — must run under withSystemContext if ever wired to a cron, never exposed tenant-facing; unchanged, not a live gap.",
    supportingCapability: ["app/api/billing/subscriptions/route.ts","services/platform-economics/subscription-lifecycle-service.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "organization_benchmark_snapshots",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'organizationBenchmarkSnapshots' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "organization_billing_config",
    classification: "SYSTEM_ONLY",
    reason: "Corrected 2026-09-02 (independent review of the 2026-09-01 batch): the only identified live root is POST /api/admin/billing-cycles/trigger-scheduled, which requires platform_lead and calls BillingScheduler.manualTrigger(). BillingScheduler.getOrganizationsForBilling() deliberately enumerates organization_billing_config across ALL organizations to build the scheduled billing run — this is bounded privileged/system execution, not ordinary tenant authority, even though the table itself carries a NOT NULL organization_id (db/schema/domains/finance/billing-config.ts). Fixed: getOrganizationsForBilling() now runs inside withSystemContext() (was: plain db). The platform_lead role check in the route remains the request-facing authorization; withSystemContext is only the execution mechanism, never treated as authorization itself. Regression test: lib/jobs/__tests__/billing-scheduler.test.ts asserts withSystemContext is used and the ordinary db connection is never touched for this query; the route's existing 401/403 tests (app/api/__tests__/admin-billing-cycles-trigger-scheduled.route.test.ts) already prove a non-platform_lead caller is rejected before any DB access.",
    supportingCapability: ["lib/jobs/billing-scheduler.ts","app/api/admin/billing-cycles/trigger-scheduled/route.ts","lib/db/with-rls-context.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: ["SELECT"],
    invocationAuthority: "PLATFORM_ADMIN",
    dbExecutionPrincipal: "SYSTEM_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "organization_contacts",
    classification: "LATENT_UNREACHABLE",
    reason: "Manually verified 2026-09-02: sole non-test reference is services/clc/remittance-notifications.ts, whose exports have zero callers anywhere under app/, actions/, lib/, services/, scripts/ (verified by name-search, see notification_log finding above — same dead file).",
    supportingCapability: ["services/clc/remittance-notifications.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "organization_sharing_settings",
    classification: "LATENT_UNREACHABLE",
    reason: "Manually verified 2026-09-02: direct NOT NULL organization_id column (db/schema/domains/infrastructure/sharing.ts; duplicated verbatim at db/schema/sharing-permissions-schema.ts, a pre-consolidation leftover per db/schema/index.ts's \"Migration Status: COMPLETE — eliminating 18 duplicates\" note — the domains/** copy is canonical). Sole union-eyes reference is lib/clc/data-products.ts, which has zero callers anywhere under app/, actions/, lib/, services/, scripts/ (verified by name-search). The only other reference is services/financial-service/** — a separately deployed service, not part of union-eyes' own request handling.",
    supportingCapability: ["lib/clc/data-products.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "pension_members",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Verified 2026-09-01 (round 6, Phase-3A priority tranche): direct NOT NULL organization_id column, reachable via live HTTP route(s) app/api/pension/members/route.ts. org-scoped pension member enrollment endpoint; SELECT+INSERT confirmed. Minimum runtime privilege set from confirmed DML verbs (crudRoutes handler destructuring and/or direct .insert/.update/.delete/.select call-site evidence), not defaulted to FULL_DML.",
    supportingCapability: ["app/api/pension/members/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "role_tenure_history",
    classification: "LATENT_UNREACHABLE",
    reason: "Zero references to the 'roleTenureHistory' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files, and migrations via git grep across app/, actions/, lib/, services/ (scan: 2026-09-01, corrected pass with test-file exclusion). No known application code path queries this table.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "duplicate_group_members",
    classification: "PARENT_OWNED_RLS_REQUIRED",
    reason: "Resolved 2026-09-02 (round 17): no own organization_id column; parent-owned through group_id -> duplicate_groups (which does have a direct NOT NULL organization_id, db/schema/ingestion-schema.ts). app/api/admin/duplicates/route.ts (minRole:'admin') always verifies the parent duplicate_groups row belongs to the caller's context organizationId before reading (GET) or updating (POST) its members — SELECT confirmed. lib/ingestion/fuzzy-dedup.ts's scanBatchForDuplicates(organizationId, ...), called from app/api/admin/ingest/route.ts (minRole:'admin', context-resolved organizationId, with an explicit record-organization-mismatch guard already in place), inserts group + member rows scoped to that same organizationId — INSERT confirmed.",
    supportingCapability: ["app/api/admin/duplicates/route.ts","lib/ingestion/fuzzy-dedup.ts","app/api/admin/ingest/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "federation_memberships",
    classification: "LATENT_UNREACHABLE",
    reason: "Round-7 scope-expansion scan: zero references to the 'federationMemberships' Drizzle export found outside db/schema/**, __tests__/**, .test./.spec./.stories. files via a combined ripgrep pass across app/, actions/, lib/, services/. No known application code path queries this table today. NOT yet individually checked for raw-SQL (non-Drizzle-symbol) references to the physical table name — see the raw-SQL LATENT fixture test for why that check matters before this can be treated as final.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "gss_applications",
    classification: "LATENT_UNREACHABLE",
    reason: "Resolved 2026-09-02 (round 17): scoped by employer_id (a companies/profiles foreign-worker-employer entity — a different tenancy boundary than union-eyes' own organizations table, per its own column comment), not organizationId, so this is out-of-model for tenant RLS regardless. Its sole non-test reference, services/lmbp-immigration-service.ts's LmbpImmigrationService (createGssApplication/getGssApplication/updateGssApplication/etc.), has ZERO real callers anywhere under app/, actions/, lib/, services/ (verified by class-name + method-name search). The only file matching a loose substring search, lib/api/lmbp-immigration-service-api.ts, is an unrelated auto-generated Django-REST-proxy boilerplate client (identical pattern to member_addresses' tax-slip-service-api.ts false positive above) — confirmed there are exactly 5 such lib/api/*-service-api.ts files in the repo (certification-management, governance, lmbp-immigration, signature, tax-slip), each a candidate false-positive-reference source for any table whose only other 'reference' is one of them.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "indigenous_member_data",
    classification: "LATENT_UNREACHABLE",
    reason: "Resolved 2026-09-02 (round 17): OCAP\u00ae-governed sensitive cultural/identity data, userId-keyed (no organizationId column at all — band_council_id is a distinct concept from union-eyes' organizations). Both cited files' IndigenousDataService classes (lib/services/indigenous-data-service.ts, and a second independent implementation at services/indigenous-data-service.ts importing the legacy duplicate schema db/schema/indigenous-data-schema.ts) have ZERO real callers anywhere under app/, actions/, lib/, services/ (verified by class-name search across the whole tree, including the lib/services/index.ts barrel export). If ever wired up, this table's sensitivity means it needs its own OCAP-respecting access model (band-council/individual consent per its own schema columns), not merely ordinary tenant RLS — documented here for the next engineer, not designed in this round since nothing reaches it today.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "member_location_consent",
    classification: "USER_RLS_REQUIRED",
    reason: "Resolved 2026-09-02 (round 17): userId-keyed (no organizationId column — real-time strike/event location tracking consent is an individual opt-in under Quebec Law 25, not org data). The manifest's own scan evidence cited only service files, missing the real, live HTTP routes: app/api/location/consent/route.ts (POST grant / GET check / DELETE revoke, services/geofence-privacy-service.ts's GeofencePrivacyService). REAL BUG FOUND+FIXED this round: all 3 handlers took `userId` directly from the client (POST body / GET+DELETE query string) with no verification against the authenticated caller — any authenticated user could forge another user's consent grant, read another user's private opt-in status, or revoke another user's legitimately-needed safety consent. Fixed: userId is now always resolved server-side via getCurrentUser() (lib/api-auth-guard.ts), never accepted from the request; regression test app/api/__tests__/location-consent.route.test.ts. This table needs a dedicated user-scoped (not org-scoped) RLS policy design if DB-level enforcement is ever added; currently enforced only at the app layer. POLICY-EXPANSION PREREQUISITE (round 18, recorded now rather than rediscovered during migration generation): today the service queries this table through the ordinary `db` import with no transaction/session-variable scoping at all (no `withRLSContext`/`withSystemContext`, no `set_config`) — acceptable ONLY because the 87-table RLS policy-expansion migration remains blocked/unimplemented and this table has no policy to enforce yet. Once a USER_RLS policy is built for this table (e.g. `USING (user_id = current_setting('app.current_user_id'))`), GeofencePrivacyService's requestLocationConsent/hasValidConsent/revokeLocationConsent must be moved inside a transaction that calls `set_config('app.current_user_id', <caller's own id>, true)` BEFORE querying — the same shape as withRLSContext's org-scoped set_config, but keyed by user id instead of org id. Do not add this table to the migration until that transaction wiring exists; otherwise every self-service consent request would silently return zero rows once RLS is enabled.",
    supportingCapability: ["app/api/location/consent/route.ts","services/geofence-privacy-service.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "NONE",
  },
  {
    table: "organization_sharing_grants",
    classification: "LATENT_UNREACHABLE",
    reason: "Resolved 2026-09-02 (round 17): union-eyes' own canonical declaration (db/schema/domains/infrastructure/sharing.ts, direct grantor/grantee organization_id columns) has ZERO real non-test references anywhere under app/, actions/, lib/, services/ (excluding services/financial-service/**) — confirmed by exact-symbol search. Its only citations are inside services/financial-service/** — a separately deployed Node service (own package.json/drizzle.config.ts/server entrypoint, per round-11's established precedent) with its OWN independent schema declaration of the same physical table name; not part of union-eyes' own request handling and out of scope for this registry's reachability question.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "pilot_applications",
    classification: "TENANT_RLS_REQUIRED",
    reason: "Round 17 resolved this table; round 18 corrected dbExecutionPrincipal from TENANT_RUNTIME to MIXED (three authority modes: public unauthenticated INSERT, same-org steward SELECT/UPDATE/DELETE, platform system_admin+ cross-org SELECT/UPDATE) and moved platform-tier reads onto withSystemContext(). Round 19 closed three remaining trust-boundary gaps the round-18 review found: (1) AUTHORIZE-BEFORE-ELEVATE ORDERING — the round-18 collection GET called withSystemContext() first and relied on the generated crudRoutes handler's OWN internal auth check (buried inside withApi), so an unauthenticated/under-authorized request still opened a system-principal connection before being rejected; fixed by adding an explicit hasMinRole('system_admin') check in app/api/pilot/apply/route.ts BEFORE withSystemContext() is ever called. (2) RECORD-EXISTENCE ORACLE — lib/pilot/pilot-ownership.ts's withPilotOwnership() (wrapping app/api/pilot/apply/[id]/route.ts's GET/PATCH/DELETE) performed its system-scoped ownership-lookup BEFORE any auth check at all, so an unauthenticated caller's response differed (404 vs. an auth failure further downstream) depending on whether an arbitrary pilot id existed \u2014 a cross-tenant existence oracle, plus an unconditional system-principal SELECT triggered by requests that were never going to be allowed to proceed. Fixed: withPilotOwnership() now takes an explicit minRole option (default 'steward', matching [id]/route.ts's own crudRoutes config) and calls hasMinRole(minRole) FIRST, uniformly rejecting with 403 regardless of id existence, before touching the database at all. (3) CLAIMED VS. VERIFIED OWNERSHIP \u2014 responses.organizationId (the JSONB field this table's ownership model reads) is an unauthenticated client assertion from the public POST body, never server-attested identity; renamed the accessor from getPilotOwnerOrganizationId to getPilotClaimedOrganizationId with an explicit doc comment establishing that provenance. It remains acceptable to use for the LOW-STAKES same-org self-service access-control gate (a submitter can only ever act on the exact org they themselves claimed \u2014 no cross-tenant read is possible since a real member of that org must independently match the same claim), but app/api/pilot/apply/[id]/commercial-transition/route.ts \u2014 which creates REAL commercialContracts/billingAccounts/orgSubscriptions/platformInvoices keyed by that claim \u2014 now REQUIRES an independent platform-tier decision (authorizePilotAccess(...).reason === 'platform', i.e. system_admin+), not same-org self-service, before executing; same-org actors are correctly authorized elsewhere (viewing/editing their own submitted application) but can no longer self-provision billing records off their own unverified claim. Also made the public POST explicitly governed rather than public-by-omission: added to config/public-api-routes.ts + lib/public-routes.ts + zod schema validation + IP rate-limiting (5/hr), and added scripts/lib/api-route-governance-scanner.ts (a per-EXPORT, not per-file, static governance checker) plus scripts/__tests__/pilot-apply-per-export-governance.test.ts, which contains a hardcoded regression fixture proving the checker catches the EXACT original bug class (a crudRoutes-wrapped GET hiding a bare, wrapper-less POST in the same file) and asserts the whole app/api/pilot/** tree is now fully per-export governed. Round 20 closed the remaining trust-boundary gap the round-19 review found: 'platform review' proved WHO could approve a commercial transition, never that the CLAIMED organization was actually the real organization behind the application \u2014 commercial-transition still resolved billing off responses.organizationId (the unauthenticated claim), so a malicious public submitter could set responses.organizationId to a victim org's real id, and a legitimate platform reviewer approving the transition would still misattribute real billing/contract records to that victim. FIX: added a server-controlled `verified_organization_id`/`verified_by`/`verified_at` column set (Django migration backend/content/migrations/0002_pilotapplications_verified_organization.py \u2014 pilot_applications is a Django-canonical business entity per docs/categories/platform-and-operations/architecture/orm-governance/master-orm-governance-index.md, so the Drizzle schema addition in db/schema/domains/marketing.ts is a TYPE MIRROR only, not the migration source; validated via `manage.py makemigrations --check --dry-run` + `manage.py check`, both clean, no live DB available in this environment to actually apply it). New `getPilotVerifiedOrganizationId()` accessor (lib/pilot/pilot-ownership.ts) reads ONLY this column; new `bindPilotOrganization()` is the ONLY function permitted to write it, fails closed (404) if the target organization does not exist, runs under withSystemContext(). New platform-only endpoint POST /api/pilot/apply/[id]/verify-organization (system_admin+ before any DB access, matching the round-19 auth-ordering pattern) is the ONLY way to bind a pilot to a verified org \u2014 the public intake POST cannot set these fields (not in its zod schema, not in its insert values). commercial-transition/route.ts now reads ONLY getPilotVerifiedOrganizationId(application), never responses.organizationId, and returns 409 if the organization has not yet been verified \u2014 a platform reviewer's authorization decision no longer implicitly re-uses the submitter's own unverified claim as billing identity. Also replaced the round-19 in-memory (lib/rate-limit.ts, per-process Map, IP+User-Agent keyed) rate limiter on the public POST with the Redis/Upstash-backed, fail-closed lib/rate-limiter.ts's checkRateLimit() (new RATE_LIMITS_PER_IP.PILOT_APPLY preset, 5/hr) \u2014 the same distributed primitive already used for other public/abuse-prone endpoints, correctly shared across instances/restarts. Corrected scripts/lib/api-route-governance-scanner.ts: `rateLimit(`/`verifyTurnstileToken(` were REMOVED from AUTH_ESTABLISHING_IDENTIFIERS (rate limiting and anti-bot challenges are abuse controls, not authentication \u2014 a route calling ONLY rateLimit() before an unguarded sensitive operation must still be classified UNGOVERNED) and moved to a new, separate ABUSE_CONTROL_IDENTIFIERS list checked via `hasAbuseControl()`, used ONLY for an additive assertion on already-allowlisted public exports (\"this public route also has a rate-limit/anti-bot control\"), never as an alternate path to \"governed\". Two new regression fixtures in scripts/__tests__/pilot-apply-per-export-governance.test.ts prove a rate-limit-only (or checkRateLimit/Turnstile-only) handler is still flagged ungoverned. Eventual RLS design (not built this round \u2014 the 87-table policy-expansion migration remains blocked pending NEEDS_REVIEW=0): once verified_organization_id exists as a real column (not JSONB), the eventual tenant RLS policy can reference it directly (`verified_organization_id = current_setting('app.current_org_id')::uuid`) rather than the fragile JSONB-path expression originally sketched in round 18/19, plus an explicit system-role policy (`TO union_eyes_system`, unconditional) for platform operations \u2014 this classification's MIXED dbExecutionPrincipal already reflects that eventual split. A live-DB proof that withSystemContext actually reaches the system connection, and that the Django migration applies cleanly, requires a real Postgres instance (rls:verify --mode=full / manage.py migrate), not available in this environment; the source-level correctness (correct auth ordering, correct wrapper on the correct decision branch, migration matches model per makemigrations --check) is the property asserted by this round's regression tests. Round 21 closed two further gaps an independent live-repo review found: (1) SERVER-CONTROLLED FIELDS WERE NOT SERVER-WRITE-ONLY \u2014 the generic PATCH on app/api/pilot/apply/[id]/route.ts (crudRoutes with no blockedPatchFields) let a same-org steward set verifiedOrganizationId/verifiedBy/verifiedAt directly, bypassing both the platform-only verify-organization endpoint and bindPilotOrganization() entirely; fixed by adding blockedPatchFields: ['verifiedOrganizationId','verifiedBy','verifiedAt','status','reviewedAt','approvedAt'] (status/reviewedAt/approvedAt are also exclusively FSM-governed by commercial-transition, not arbitrary steward-editable fields), backed by a new exported, directly-unit-tested stripBlockedPatchFields() helper in lib/api/crud-factory.ts. (2) UNBOUNDED REBIND LIFECYCLE \u2014 bindPilotOrganization() previously overwrote an existing binding unconditionally, permitting Org A verified -> financial activity begins -> silently rebound to Org B -> subsequent commercial transitions misattributed to Org B; fixed by making the bind immutable (idempotent no-op for the SAME org, 409 for a DIFFERENT org) and adding a separate, deliberately-friction-ful rebindPilotOrganization() correction primitive (app/api/pilot/apply/[id]/rebind-organization/route.ts, system_admin+ only) that requires a non-empty audit reason and refuses to proceed when a commercialContracts row already exists for the pilot unless the caller explicitly passes acknowledgeFinancialArtifacts=true (which does NOT itself migrate those rows \u2014 a deliberate, logged, audited correction, not silent reattribution). Also corrected the RED-TEAM-ORG-011 static ratchet in security/redteam/ue-org-scope-fuzz.test.ts: its stale getPilotOwnerOrganizationId marker (renamed in round 19) is fixed, and it now recognizes platform CONTROL-PLANE pilot routes (verify-organization, rebind-organization) as requiring a canonical platform-admin guard (hasMinRole('system_admin') / PILOT_PLATFORM_ACCESS_MIN_LEVEL) instead of a same-org OWNERSHIP marker, since same-org self-service was never the correct model for those two routes. Separately, confirmed the demo deployment profile (DJANGO_SKIP_MIGRATIONS=true per .github/workflows/deploy-union-eyes.yml) does not automatically apply this table's migrations; added backend/content/management/commands/check_pilot_schema.py as an explicit, narrowly-scoped preflight ops can run against any environment before serving pilot traffic there. Round 22 closed four further bounded gaps an independent review found directly inside this trust boundary: (1) MUTABLE CLAIMED-ORG FIELD \u2014 responses.organizationId (the JSONB claim getPilotClaimedOrganizationId reads for ordinary same-org access) was not protected by round 21's blockedPatchFields (a flat top-level-key list can't reach a nested JSONB subfield) \u2014 a same-org steward could pass the ownership pre-check on Org A's row, then PATCH responses.organizationId to Org B, transferring subsequent same-org access with no platform involvement at all. Fixed via a new crud-factory beforeUpdate hook (mirrors the existing beforeCreate pattern) wired to a new exported, directly-unit-tested preserveClaimedOrganizationOnPatch(), which forces the claimed organizationId back to the row's existing value on every PATCH regardless of what the client sends, while leaving every other responses subfield ordinarily editable. (2) INCOMPLETE FINANCIAL-ARTIFACT CENSUS \u2014 rebindPilotOrganization() only checked commercialContracts, but commercial-transition's invoice_issued/subscription_active branches (reachable via allowSkip) can each create a real platformInvoices/orgSubscriptions row independently of contract_sent, so a pilot could carry a real invoice or subscription with no contract and rebind would proceed without acknowledgeFinancialArtifacts. Fixed via a new pilotHasFinancialArtifacts() helper checking all three tables by their shared metadata->>pilotApplicationId marker. (3) NO CONCURRENCY GUARD \u2014 bindPilotOrganization/rebindPilotOrganization performed read-then-update with no row lock, so two concurrent verifications for different orgs (or a rebind racing a concurrent commercial-transition creating a financial artifact) could both observe stale state; last writer wins. Fixed: both functions now take SELECT ... FOR UPDATE on the pilot row inside withSystemContext's real transaction, and commercial-transition's monetization transaction takes the same lock before creating any artifact, so all three now serialize against each other. (4) BROKEN GENERIC DELETE \u2014 the shared factory's DELETE soft-deletes by writing status='archived' whenever a status column exists, but round 21 made pilot status exclusively FSM-governed by commercial-transition, and pilot_status has no 'archived' value at all \u2014 the exported DELETE handler both violated the new FSM rule and would fail against the enum if ever invoked. Fixed by removing the DELETE export entirely (405 by default); a real archive/close action belongs in the commercial-transition FSM, not a generic soft-delete. Also corrected overstated language from round 21: rebindPilotOrganization's logging is a structured logger.warn call, not yet a durable audit_logs row \u2014 doc comments now say \"logged for traceability,\" not \"audited.\" Round 23 closed three further gaps a deeper live-source review found directly inside this trust boundary: (1) LOCKED TOO LATE \u2014 commercial-transition previously loaded the application, derived verifiedOrganizationId/responses/fromState, and validated the FSM transition BEFORE entering the transaction that locks the row, then used those pre-lock values inside the lock \u2014 so a rebind that committed between the initial read and the lock being acquired left the transition using a stale verified-org/commercial-state snapshot. Fixed: the row is now re-SELECTed with FOR UPDATE as the FIRST statement inside the transaction, and verifiedOrganizationId, responses, fromState, and the proposal are ALL derived from that locked read; a new CommercialTransitionRejected error class lets expected rejections (404/409/400) discovered after locking roll back the transaction and still return the exact intended HTTP response. The earlier pre-lock read is now only a cheap existence + role-tier check, never a source of financial or FSM decisions. (2) RESPONSES REMAINED A MIXED-TRUST STORE \u2014 round 22 protected only responses.organizationId from steward PATCH, leaving responses.commercialState (drives FSM validation), responses.subscriptionPlanId (selects the billing plan on activation), commercialTransitionHistory, pilotIntelligence, qualification/opportunity scores, artifact-version metadata, and commercialMonetization all editable \u2014 contradicting round 21's claim that commercial state is FSM-controlled. Fixed: preserveClaimedOrganizationOnPatch was generalized into preserveServerOwnedResponsesFields, which restores ALL server-owned responses keys (organizationId plus the full commercial/scoring/artifact list above) to their existing values on every PATCH, while leaving every other responses key ordinarily editable. (3) TENANT AUTHORIZATION STILL FOLLOWED THE CLAIM AFTER VERIFICATION/REBIND \u2014 the ownership pre-check loaded only responses and authorized via getPilotClaimedOrganizationId, never verifiedOrganizationId, so after a platform rebind moved the authoritative owner from Org A to Org B, Org A stewards still passed the tenant ownership check and Org B stewards did not \u2014 the rebind changed financial identity but not tenant authorization. Fixed: a new getPilotEffectiveOrganizationId () (verifiedOrganizationId ?? claimedOrganizationId) is now the ONLY value application-layer ownership checks use (enforcePilotOwnership/withPilotOwnership, and loadPilotApplicationForOwnershipCheck now also selects verifiedOrganizationId to make this possible); once a verified owner exists it is authoritative everywhere, including after a rebind. The eventual tenant RLS policy for this table must encode the SAME effective-owner rule (COALESCE(verified_organization_id, (responses->>'organizationId')::uuid) = current_setting(...)), not the claim-only JSONB expression sketched in earlier rounds. Round 24 was structural rather than another field-by-field patch: (1) PUBLIC-CREATE PROVENANCE BYPASS \u2014 the public intake POST's responses: z.record(z.unknown()) schema let an unauthenticated applicant seed a brand-new row with the SAME reserved keys rounds 22-23 protected on UPDATE (commercialState, subscriptionPlanId, qualification scores, artifact metadata, ...), and the PATCH-time protection then faithfully preserved that attacker-seeded value forever \u2014 protecting an update is meaningless if creation was never sanitized. Fixed by extracting a SINGLE canonical registry (lib/pilot/responses-authority.ts's RESERVED_RESPONSES_KEYS) used by BOTH the public POST (sanitizeResponsesForPublicCreate strips every reserved key except organizationId, the intentionally untrusted claim) and the PATCH path, so there is exactly one place to update when a new governed route starts writing a new responses key. (2) INCOMPLETE REGISTRY \u2014 round 23's list missed reference-profile/route.ts's 4 reference-version keys (pilotReferenceVersions, latestPilotReferenceVersionId, latestPilotReferenceChecksum, latestPilotReferenceUpdatedAt) entirely \u2014 verified via a full-repo inventory of every '.update(pilotApplications)' call site this round; all 4 now reserved. championScore/activityScore deliberately remain unreserved \u2014 verified no route ever WRITES them (only reads, as optional bounded-impact scoring inputs with a computed fallback when absent), so reserving them would remove the only way they can ever be set; documented as a deliberate decision, not an oversight. (3) PATCH COULD STILL REVERT FRESHLY COMMITTED SERVER STATE \u2014 the round 22/23 beforeUpdate hook read the current row, copied reserved values into the merged object, then replaced the WHOLE responses column \u2014 a lost-update race if commercial-transition committed a reserved-key change between that read and this PATCH's write (the PATCH would silently revert it). Fixed by replacing the read-copy-write model with an atomic JSONB MERGE: crudRoutes() gained a mergeJsonColumns option (lib/api/crud-factory.ts) that locks the row FOR UPDATE, strips reserved keys from the client's responses fragment (never reading or reproducing their current values), and issues 'responses || fragment' rather than a full-column replace \u2014 a concurrent write to any key absent from the fragment can never be reverted, because the PATCH's SQL never mentions that key at all. Round 25 closed 4 structural gaps the reviewer found in this model: (1) the merge helper silently fell back to a full-column REPLACE for a non-object responses value (e.g. an array or null) \u2014 buildMergeSetValues() now throws via validateMergeJsonColumnValues() for any mergeJsonColumns value that is not a plain object, closing a direct reserved-state destruction primitive; (2) intelligence/artifacts/reference-profile's POST handlers ran an UNLOCKED read-modify-write on the whole responses column \u2014 a server-writer-vs-server-writer race against commercial-transition's own locked write \u2014 now rewritten onto a new withLockedPilotMutation() primitive (lib/pilot/pilot-mutation.ts) that locks the row FOR UPDATE, re-authorizes the effective owner under that SAME lock, and merges only the specific keys each route owns (pilotIntelligence; the 4 artifact-version fields; the 4 reference-version fields), never the whole column; (3) the generic CRUD PATCH's ownership pre-check ran on an unlocked read BEFORE crud-factory's own row lock \u2014 a concurrent platform rebind could move ownership in that gap \u2014 closed via a new lockedAuthCheck CrudOptions hook that re-evaluates authorizePilotAccess against the row the SAME transaction just locked; (4) commercial-transition derived real contract/invoice amounts from applicant-supplied member_count (steward-PATCH-editable) and selected a subscription plan via an ambiguous \"any active plan\" fallback since responses.subscriptionPlanId had no governed writer \u2014 both replaced by a platform-approved commercial-terms snapshot (verified_member_count, verified_pilot_amount, verified_subscription_plan_id, commercial_terms_approved_by/at columns; lib/pilot/commercial-terms-authority.ts's approveCommercialTerms, the ONLY writer, gated behind system_admin+ like verify-organization/rebind-organization) that every financial-artifact-creating transition (contract_sent, invoice_issued, subscription_active) now requires before proceeding. Round 26 closed lifecycle/governance defects an independent review found in round 25's own delivery: (1) ORM AUTHORITY DOCTRINE VIOLATION \u2014 round 25 added the 5 commercial-terms columns via a standalone raw SQL file in apps/union-eyes/db/migrations/, which is BOTH a frozen, read-only historical Drizzle lineage (db/migrations/.lineage-frozen \u2014 new files there are explicitly prohibited per db/migrations/LINEAGE-FROZEN.md) AND a violation of this table's own Django-canonical authority (this table is a Django-canonical business entity per docs/categories/platform-and-operations/architecture/orm-governance/master-orm-governance-index.md; Drizzle's marketing.ts is a TYPE MIRROR only). Fixed: deleted the standalone SQL file; added the 5 fields to Django's PilotApplications model (backend/content/models.py) and a real Django migration (backend/content/migrations/0003_pilotapplications_commercial_terms.py), validated via `manage.py makemigrations --check --dry-run` + `manage.py check` (both clean for this table; a small set of PRE-EXISTING, unrelated drift in other Django apps \u2014 auth_core, content/documents-rename, core, services, unions \u2014 remains exactly as it was before this round, confirmed unchanged, not silently fixed as part of this round). (2) STALE DEMO SCHEMA PREFLIGHT \u2014 backend/content/management/commands/check_pilot_schema.py still only checked the 3 round-21 verified-organization columns, so it could report success on a database where every round-25 commercial-transition call to a financial-artifact-creating state would 500 on \"column does not exist\"; expanded to check all 8 columns across both migrations, with a column-to-migration map so a failure names the exact migration(s) still needed. (3) COMMERCIAL TERMS APPROVED BUT NOT LIFECYCLE-BOUND \u2014 approveCommercialTerms() previously allowed re-approval with DIFFERENT values indefinitely, even after a contract/invoice/subscription had already been created from a prior approval \u2014 an authoritative-state/ledger-state divergence with no record of which approval produced which artifact. Fixed: exported the existing pilotHasFinancialArtifacts() census (lib/pilot/pilot-ownership.ts, previously private) and made approveCommercialTerms() refuse ANY further approval (409, even with identical values) once a real financial artifact exists for the pilot, checked AFTER the SAME row lock used for the write (TOCTOU-safe against a concurrent commercial-transition). (4) TERMS SURVIVED ORGANIZATION REBIND \u2014 rebindPilotOrganization() changed verifiedOrganizationId/verifiedBy/verifiedAt but left a prior organization's approved commercial terms intact, so commercial-transition could create the NEW organization's financial artifacts from an approval made under the PREVIOUS organization's context. Fixed: rebind now unconditionally clears verifiedMemberCount/verifiedPilotAmount/verifiedSubscriptionPlanId/commercialTermsApprovedBy/commercialTermsApprovedAt whenever the verified organization actually changes (never for the idempotent same-org no-op path), forcing fresh approval under the new organization's context before any further financial-artifact-creating transition. Also closed two smaller financial-hardening gaps: pilotAmount is now validated on its NORMALIZED (toFixed(2)-rounded) value \u2014 at least $0.01 and within numeric(12,2) bounds \u2014 not the raw pre-rounding input (a raw value like 0.001 was previously positive but normalized to \"0.00\"); and commercial-transition's subscription_active branch now revalidates the approved plan's isActive status inside the SAME locked transaction at ACTIVATION time, not just at approval time, staging the activation only (never silently proceeding) if the plan has since been deactivated. Round 27 closed 3 further lifecycle gaps an independent review found in round 26's own delivery: (1) TERMS APPROVABLE BEFORE ORGANIZATION VERIFICATION \u2014 round 26 correctly cleared commercial terms on rebindPilotOrganization (an already-verified org changing to a different one), but approveCommercialTerms() never checked verifiedOrganizationId at all, so terms could be approved while the pilot's organization was still NULL (never yet verified), then bindPilotOrganization() (the first-time NULL -> org bind, a SEPARATE function from rebind) could bind it afterward with the pre-existing approval never evaluated in that organization's context. Fixed: approveCommercialTerms() now loads verifiedOrganizationId inside its own locked pilot read and returns 409 if absent, closing the gap for the FIRST bind the same way round 26 closed it for rebinds. (2) ACKNOWLEDGED POST-ARTIFACT REBIND CREATED A PERMANENT DEAD END \u2014 rebindPilotOrganization() still permitted an organization change after financial artifacts existed via an acknowledgeFinancialArtifacts=true escape hatch, which then unconditionally cleared the pilot's commercial terms (round 26) \u2014 but round 26 ALSO made approveCommercialTerms() refuse EVERY further approval once any financial artifact exists. Combined, an acknowledged rebind cleared the terms and then made re-approving them permanently impossible, since the pre-existing artifact is never deleted. Fixed: removed the acknowledgeFinancialArtifacts escape hatch entirely \u2014 rebindPilotOrganization() now unconditionally refuses (409, no override) once any real financial artifact exists; a post-artifact organization correction requires a dedicated financial-correction workflow that does not exist yet, not this function with an acknowledgement flag. (3) FINANCIAL ARTIFACTS DID NOT CARRY THE APPROVAL THAT PRODUCED THEM \u2014 commercialContracts/platformInvoices/orgSubscriptions metadata recorded only { source, pilotApplicationId }, so once an organization correction cleared the pilot row's own terms (round 26), a previously-created contract or invoice could no longer prove which approved commercial snapshot produced it. Fixed: new buildCommercialTermsSnapshot() (lib/pilot/commercialization-wave1.ts, reusing the SAME deterministic DJB2-style checksum already used for artifact/reference version records) builds an immutable { verifiedOrganizationId, verifiedMemberCount, verifiedPilotAmount, verifiedSubscriptionPlanId, commercialTermsApprovedBy, commercialTermsApprovedAt } snapshot plus a commercialTermsFingerprint hash, stamped into the metadata of every commercialContracts / platformInvoices / platformInvoiceLineItems / orgSubscriptions row CREATED (not merely updated) by commercial-transition \u2014 the pilot row's own terms remain the CURRENT authoritative snapshot; each artifact's stamped snapshot is the HISTORICAL one in effect at the moment that specific artifact was created, and the two are expected to diverge over time after any correction, which is exactly what this makes provable.",
    supportingCapability: ["app/api/pilot/apply/route.ts","lib/pilot/pilot-ownership.ts","app/api/pilot/apply/[id]/route.ts","app/api/pilot/apply/[id]/commercial-transition/route.ts","app/api/pilot/apply/[id]/verify-organization/route.ts","app/api/pilot/apply/[id]/rebind-organization/route.ts","app/api/pilot/apply/[id]/artifacts/route.ts","app/api/pilot/apply/[id]/intelligence/route.ts","app/api/pilot/apply/[id]/commercialization-timeline/route.ts","app/api/pilot/apply/[id]/package-export/route.ts","app/api/pilot/apply/[id]/proposal/route.ts","app/api/pilot/apply/[id]/reference-profile/route.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE"],
    requiredSystemPrivileges: ["SELECT","UPDATE"],
    invocationAuthority: "MIXED",
    dbExecutionPrincipal: "MIXED",
    reviewPriority: "NONE",
  },
  {
    table: "applications",
    classification: "LATENT_UNREACHABLE",
    reason: "PR #752 round 8: db/schema-applications.ts's Multi-App Discriminator registry — declared in a sibling file OUTSIDE db/schema/** (SCHEMA_ROOT's walk never visited it; see scripts/generate-public-schema-grant-census.ts's ADDITIONAL_PUBLIC_SCHEMA_FILES for the census-completeness fix). Only real reference is a FK column (organizations.appId references(() => applications.id) in db/schema-organizations.ts) and its barrel re-export in db/index.ts. Zero '.from(applications)'/'.insert(applications)'/'.update(applications)'/'.delete(applications)' call sites and zero raw-SQL 'FROM/INTO/UPDATE applications' references found across app/, actions/, lib/, services/ outside __tests__/**.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "org_configurations",
    classification: "TENANT_RLS_REQUIRED",
    reason: "PR #752 round 8: db/schema-organizations.ts, another sibling file outside SCHEMA_ROOT's walk (same census-completeness fix as 'applications'). Two independent write paths found: (1) lib/representation/protocol-service.ts's getRepresentationProtocol/saveRepresentationProtocol/resetRepresentationProtocol — REAL, reachable via app/api/admin/representation-protocol/route.ts (withAdminAuth, org-scoped, organizationId taken from the authenticated caller's own context) and consumed read-only by lib/case-assignment-engine.ts. Uses plain `db` with organizationId as an app-level WHERE/values filter, NOT wrapped in withRLSContext — no DB-level RLS session var is set on this path today, a latent gap tracked here (not fixed this round; org_configurations was never 0108-protected and has no RLS policy yet, hence TENANT_RLS_REQUIRED rather than an already-closed classification). (2) actions/admin-actions.ts's getSystemConfigs/updateSystemConfig — LATENT_UNWIRED: actions/admin-actions.ts has zero real importers anywhere in app/lib/actions/services/components (confirmed via grep), matching the round-5 lib/workers/** dead-code precedent; not counted toward required privileges.",
    supportingCapability: ["app/api/admin/representation-protocol/route.ts","lib/representation/protocol-service.ts","lib/case-assignment-engine.ts"],
    requiredRuntimePrivileges: ["SELECT","INSERT","UPDATE","DELETE"],
    requiredSystemPrivileges: [],
    invocationAuthority: "TENANT_USER",
    dbExecutionPrincipal: "TENANT_RUNTIME",
    reviewPriority: "HIGH",
  },
  {
    table: "org_usage",
    classification: "LATENT_UNREACHABLE",
    reason: "PR #752 round 8: db/schema-organizations.ts (sibling-file census fix, see 'applications'). Only reference is actions/admin-actions.ts's getSystemStats — that whole module (actions/admin-actions.ts) has zero real importers anywhere in app/lib/actions/services/components (confirmed via grep, no barrel/indirect import found either), matching the round-5 lib/workers/** dead-code precedent. Zero raw-SQL references found either.",
    supportingCapability: [],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: [],
    invocationAuthority: "NONE",
    dbExecutionPrincipal: "NONE",
    reviewPriority: "NONE",
  },
  {
    table: "organization_relationships",
    classification: "SYSTEM_ONLY",
    reason: "PR #752 round 8: db/schema-organizations.ts (sibling-file census fix, see 'applications'). Two paths found: (1) db/queries/organization-queries.ts's createOrganizationRelationship/getOrganizationRelationships (withRLSContext-wrapped, tenant-scoped by parentOrgId/childOrgId) — LATENT_UNWIRED, zero real callers found anywhere outside that file itself. (2) lib/organizational-topology/source.ts's getInstitutionalGraph() — REAL, reads ALL organization_relationships with no per-org filter (a national/cross-affiliate topology view), consumed by 3 dashboard pages (organizational-topology, organizational-chronology, organizational-observability). Found and fixed a REAL cross-org exposure bug this round: those 3 pages were gated only by requireUser() (any authenticated user, any role) — restricted to clc_staff/clc_executive/system_admin via the new lib/organizational-topology/access.ts, mirroring the round-5 CLC-dashboard precedent (see lib/auth/__tests__/clc-national-role-boundary.test.ts). getInstitutionalGraph() itself was also moved from plain `db` to withSystemContext so the DB-level boundary matches that app-level authority rather than relying on ordinary tenant-RLS routing to happen to permit a cross-org read.",
    supportingCapability: ["app/[locale]/dashboard/organizational-topology/page.tsx","app/[locale]/dashboard/organizational-chronology/page.tsx","app/[locale]/dashboard/organizational-observability/page.tsx","lib/organizational-topology/source.ts"],
    requiredRuntimePrivileges: [],
    requiredSystemPrivileges: ["SELECT"],
    invocationAuthority: "PLATFORM_ADMIN",
    dbExecutionPrincipal: "SYSTEM_RUNTIME",
    reviewPriority: "NONE",
  },
]
