/**
 * Seed data for Nzila HQ.
 *
 * Realistic but synthetic. Powers the Phase 1 demo and underpins all integration
 * tests until per-app authoritative data sources are wired up. The shape exactly
 * matches the canonical types in `@nzila/hq-domain`.
 *
 * Editing rules:
 * - Keep deterministic IDs (no random) so snapshots stay stable.
 * - Keep timestamps relative to `NOW` so date math in dashboards renders sensibly.
 */
import 'server-only'
import type {
  Contact,
  Document,
  HqUser,
  Meeting,
  Opportunity,
  Organization,
  StrategicEvent,
  Task,
  Venture,
} from '@nzila/hq-domain'

export const NOW = '2026-04-28T12:00:00.000Z'

const D = (offsetDays: number, hour = 9): string => {
  const base = new Date(NOW).getTime() + offsetDays * 86_400_000 + (hour - 9) * 3_600_000
  return new Date(base).toISOString()
}

export const USERS: readonly HqUser[] = [
  { id: 'user-founder', fullName: 'Aubert Nungisa', role: 'founder', email: 'aubert@nzila.io' },
  { id: 'user-president', fullName: 'P. Mosele', role: 'president', email: 'president@nzila.io' },
  { id: 'user-ops', fullName: 'M. Okafor', role: 'ops-lead', email: 'ops@nzila.io' },
  {
    id: 'user-partnerships',
    fullName: 'L. Achebe',
    role: 'partnerships',
    email: 'partners@nzila.io',
  },
  { id: 'user-finance', fullName: 'D. Tremblay', role: 'finance', email: 'finance@nzila.io' },
] as const

export const VENTURES: readonly Venture[] = [
  {
    id: 'v-union-eyes',
    slug: 'union-eyes',
    name: 'Union Eyes',
    mission: 'Member-owned union intelligence platform — case timelines, evidence, representation.',
    icp: 'Mid-to-large public-sector unions in Canada (5k+ members).',
    ownerUserId: 'user-founder',
    secondOwnerUserId: 'user-ops',
    stage: 'go-to-market',
    monthlyRecurringRevenueCents: 18_500_00,
    pipelineValueCents: 420_000_00,
    weightedPipelineCents: 165_000_00,
    pilotsLive: 2,
    blockers: ['Awaiting founder sign-off on CUPE master agreement'],
    next30Days: [
      'Close CUPE Local 4400 pilot conversion',
      'Ship case-timeline auto-summary',
      'Hire second account exec',
    ],
    confidence: 'high',
    consoleAppId: 'union-eyes',
    externalLinks: { console: '/integrations/console' },
    createdAt: D(-540),
    updatedAt: D(-1),
  },
  {
    id: 'v-zonga',
    slug: 'zonga',
    name: 'Zonga',
    mission: 'Operator-grade growth OS for African SMB exporters.',
    icp: 'Logistics + agri SMBs in West Africa, $1M–$25M revenue.',
    ownerUserId: 'user-ops',
    secondOwnerUserId: 'user-founder',
    stage: 'pilot',
    monthlyRecurringRevenueCents: 4_200_00,
    pipelineValueCents: 180_000_00,
    weightedPipelineCents: 54_000_00,
    pilotsLive: 1,
    blockers: ['Lagos partner contract in legal review'],
    next30Days: ['Onboard Rock Nations pilot', 'Close Lagos partner MoU'],
    confidence: 'medium',
    consoleAppId: 'zonga',
    externalLinks: {},
    createdAt: D(-360),
    updatedAt: D(-2),
  },
  {
    id: 'v-first-stone',
    slug: 'first-stone',
    name: 'First Stone',
    mission: 'Founder-grade strategy assistant for early-stage CEOs.',
    icp: 'Pre-seed → Series A founders, technical or domain expert.',
    ownerUserId: 'user-founder',
    secondOwnerUserId: null,
    stage: 'incubating',
    monthlyRecurringRevenueCents: 0,
    pipelineValueCents: 35_000_00,
    weightedPipelineCents: 7_000_00,
    pilotsLive: 0,
    blockers: ['No second owner', 'Founder is sole sales contact'],
    next30Days: ['Validate ICP with 10 founder interviews'],
    confidence: 'low',
    consoleAppId: null,
    externalLinks: {},
    createdAt: D(-90),
    updatedAt: D(-3),
  },
  {
    id: 'v-veridian-care',
    slug: 'veridian-care',
    name: 'Veridian Care',
    mission: 'Compliance + care coordination for community health networks.',
    icp: 'Multi-clinic primary care groups (10–100 sites).',
    ownerUserId: 'user-president',
    secondOwnerUserId: 'user-ops',
    stage: 'pilot',
    monthlyRecurringRevenueCents: 9_800_00,
    pipelineValueCents: 250_000_00,
    weightedPipelineCents: 82_000_00,
    pilotsLive: 1,
    blockers: [],
    next30Days: ['Sign first paid customer', 'Complete SOC 2 readiness review'],
    confidence: 'high',
    consoleAppId: 'veridian-care',
    externalLinks: {},
    createdAt: D(-300),
    updatedAt: D(-1),
  },
  {
    id: 'v-flow',
    slug: 'flow',
    name: 'Flow',
    mission: 'Workflow + governance fabric powering all Nzila ventures.',
    icp: 'Internal — platform layer.',
    ownerUserId: 'user-ops',
    secondOwnerUserId: 'user-president',
    stage: 'scaling',
    monthlyRecurringRevenueCents: 0,
    pipelineValueCents: 0,
    weightedPipelineCents: 0,
    pilotsLive: 0,
    blockers: [],
    next30Days: ['Land org-picker hardening', 'Cut v2.4 release'],
    confidence: 'high',
    consoleAppId: 'flow',
    externalLinks: {},
    createdAt: D(-720),
    updatedAt: D(0),
  },
  {
    id: 'v-agrimo',
    slug: 'agrimo',
    name: 'Agrimo',
    mission: 'Agronomy + financing rails for cooperative farms.',
    icp: 'Cooperative farms in Quebec & Ontario, 50–500 members.',
    ownerUserId: 'user-partnerships',
    secondOwnerUserId: 'user-founder',
    stage: 'incubating',
    monthlyRecurringRevenueCents: 0,
    pipelineValueCents: 60_000_00,
    weightedPipelineCents: 9_000_00,
    pilotsLive: 0,
    blockers: ['Partnership with cooperative federation pending'],
    next30Days: ['Founder intro call with UPA Québec'],
    confidence: 'low',
    consoleAppId: 'agrimo',
    externalLinks: {},
    createdAt: D(-150),
    updatedAt: D(-5),
  },
] as const

export const ORGANIZATIONS: readonly Organization[] = [
  {
    id: 'org-cupe',
    name: 'CUPE',
    kind: 'customer',
    ventureRelevance: ['union-eyes'],
    ownerUserId: 'user-founder',
    trustScore: 82,
    notes: 'Strategic anchor account. Master agreement under negotiation.',
    createdAt: D(-400),
  },
  {
    id: 'org-cupe-4400',
    name: 'CUPE Local 4400',
    kind: 'customer',
    ventureRelevance: ['union-eyes'],
    ownerUserId: 'user-ops',
    trustScore: 88,
    notes: 'Active pilot — converting to paid this quarter.',
    createdAt: D(-220),
  },
  {
    id: 'org-rock-nations',
    name: 'Rock Nations',
    kind: 'partner',
    ventureRelevance: ['zonga'],
    ownerUserId: 'user-ops',
    trustScore: 71,
    notes: 'Lagos-based logistics partner. Pilot underway.',
    createdAt: D(-180),
  },
  {
    id: 'org-ms-celebrations',
    name: 'MS Celebrations',
    kind: 'buyer',
    ventureRelevance: ['zonga'],
    ownerUserId: 'user-founder',
    trustScore: 64,
    notes: 'Champion buyer — needs second owner; founder is sole contact.',
    createdAt: D(-160),
  },
  {
    id: 'org-upa',
    name: 'UPA Québec',
    kind: 'partner',
    ventureRelevance: ['agrimo'],
    ownerUserId: 'user-partnerships',
    trustScore: 55,
    notes: 'Federation of agricultural producers. Early conversations.',
    createdAt: D(-90),
  },
  {
    id: 'org-praxis-cap',
    name: 'Praxis Capital',
    kind: 'investor',
    ventureRelevance: ['union-eyes', 'veridian-care'],
    ownerUserId: 'user-founder',
    trustScore: 68,
    notes: 'Followed last round. Quarterly update cadence.',
    createdAt: D(-500),
  },
  {
    id: 'org-westhaven',
    name: 'Westhaven Health Network',
    kind: 'prospect',
    ventureRelevance: ['veridian-care'],
    ownerUserId: 'user-president',
    trustScore: 60,
    notes: 'In proposal stage — strong fit.',
    createdAt: D(-120),
  },
] as const

export const CONTACTS: readonly Contact[] = [
  {
    id: 'c-cupe-1',
    organizationId: 'org-cupe',
    fullName: 'J. Tremblay',
    title: 'Director of Member Services',
    email: 'jtremblay@cupe.example',
    phone: null,
    ownerUserId: 'user-founder',
    warmIntroPath: [],
    lastInteractionAt: D(-3),
    nextStep: 'Send revised pricing for master agreement',
  },
  {
    id: 'c-cupe-4400-1',
    organizationId: 'org-cupe-4400',
    fullName: 'A. Lavoie',
    title: 'President',
    email: 'a.lavoie@cupe4400.example',
    phone: null,
    ownerUserId: 'user-ops',
    warmIntroPath: ['user-founder'],
    lastInteractionAt: D(-2),
    nextStep: 'Confirm pilot conversion',
  },
  {
    id: 'c-rock-1',
    organizationId: 'org-rock-nations',
    fullName: 'O. Adebayo',
    title: 'COO',
    email: 'o.adebayo@rocknations.example',
    phone: null,
    ownerUserId: 'user-ops',
    warmIntroPath: [],
    lastInteractionAt: D(-7),
    nextStep: 'Pilot kick-off',
  },
  {
    id: 'c-ms-1',
    organizationId: 'org-ms-celebrations',
    fullName: 'M. Salim',
    title: 'Founder',
    email: 'm.salim@mscelebrations.example',
    phone: null,
    ownerUserId: 'user-founder',
    warmIntroPath: [],
    lastInteractionAt: null,
    nextStep: null,
  },
  {
    id: 'c-praxis-1',
    organizationId: 'org-praxis-cap',
    fullName: 'R. Khoury',
    title: 'Partner',
    email: 'r.khoury@praxis.example',
    phone: null,
    ownerUserId: 'user-founder',
    warmIntroPath: [],
    lastInteractionAt: D(-14),
    nextStep: 'Send Q2 update deck',
  },
  {
    id: 'c-westhaven-1',
    organizationId: 'org-westhaven',
    fullName: 'S. Patel',
    title: 'CIO',
    email: 's.patel@westhaven.example',
    phone: null,
    ownerUserId: 'user-president',
    warmIntroPath: ['user-founder'],
    lastInteractionAt: D(-5),
    nextStep: 'Walk through SOC 2 evidence',
  },
] as const

export const OPPORTUNITIES: readonly Opportunity[] = [
  {
    id: 'op-cupe-master',
    ventureSlug: 'union-eyes',
    organizationId: 'org-cupe',
    name: 'CUPE master agreement',
    stage: 'negotiation',
    estimatedValueCents: 240_000_00,
    probability: 0.55,
    ownerUserId: 'user-founder',
    nextAction: 'Send revised pricing',
    daysStale: 4,
    blockers: ['Founder approval on discount tier'],
    expectedCloseAt: D(28),
    founderTouchRequired: true,
  },
  {
    id: 'op-cupe-4400',
    ventureSlug: 'union-eyes',
    organizationId: 'org-cupe-4400',
    name: 'CUPE Local 4400 pilot conversion',
    stage: 'pilot',
    estimatedValueCents: 36_000_00,
    probability: 0.85,
    ownerUserId: 'user-ops',
    nextAction: 'Confirm conversion',
    daysStale: 2,
    blockers: [],
    expectedCloseAt: D(14),
    founderTouchRequired: false,
  },
  {
    id: 'op-rock-nations',
    ventureSlug: 'zonga',
    organizationId: 'org-rock-nations',
    name: 'Rock Nations Lagos pilot',
    stage: 'pilot',
    estimatedValueCents: 18_000_00,
    probability: 0.6,
    ownerUserId: 'user-ops',
    nextAction: 'Pilot kick-off',
    daysStale: 7,
    blockers: ['Partner contract in legal review'],
    expectedCloseAt: D(21),
    founderTouchRequired: false,
  },
  {
    id: 'op-ms-celebrations',
    ventureSlug: 'zonga',
    organizationId: 'org-ms-celebrations',
    name: 'MS Celebrations onboarding',
    stage: 'proposal',
    estimatedValueCents: 24_000_00,
    probability: 0.4,
    ownerUserId: 'user-founder',
    nextAction: 'Re-engage champion',
    daysStale: 21,
    blockers: ['Founder is only contact'],
    expectedCloseAt: D(45),
    founderTouchRequired: true,
  },
  {
    id: 'op-westhaven',
    ventureSlug: 'veridian-care',
    organizationId: 'org-westhaven',
    name: 'Westhaven Health proposal',
    stage: 'proposal',
    estimatedValueCents: 144_000_00,
    probability: 0.45,
    ownerUserId: 'user-president',
    nextAction: 'Walk through SOC 2 evidence',
    daysStale: 5,
    blockers: [],
    expectedCloseAt: D(60),
    founderTouchRequired: false,
  },
  {
    id: 'op-praxis-followon',
    ventureSlug: 'union-eyes',
    organizationId: 'org-praxis-cap',
    name: 'Praxis follow-on conversation',
    stage: 'qualified',
    estimatedValueCents: 0,
    probability: 0.2,
    ownerUserId: 'user-founder',
    nextAction: 'Send Q2 update deck',
    daysStale: 14,
    blockers: [],
    expectedCloseAt: null,
    founderTouchRequired: true,
  },
  {
    id: 'op-upa-intro',
    ventureSlug: 'agrimo',
    organizationId: 'org-upa',
    name: 'UPA Québec intro',
    stage: 'lead',
    estimatedValueCents: 60_000_00,
    probability: 0.15,
    ownerUserId: 'user-partnerships',
    nextAction: 'Founder intro call',
    daysStale: 3,
    blockers: ['Founder availability'],
    expectedCloseAt: D(90),
    founderTouchRequired: true,
  },
] as const

export const TASKS: readonly Task[] = [
  {
    id: 't-cupe-pricing',
    title: 'Approve CUPE master pricing tier',
    context: 'Discount cap for >10k members. Operator team has prepared two scenarios.',
    queue: 'founder-decisions',
    ownerUserId: 'user-founder',
    dueAt: D(2),
    status: 'open',
    ventureSlug: 'union-eyes',
    opportunityId: 'op-cupe-master',
  },
  {
    id: 't-westhaven-soc2',
    title: 'Approve SOC 2 evidence package for Westhaven',
    context: 'Veridian Care evidence pack complete. Awaiting founder/president sign-off.',
    queue: 'founder-decisions',
    ownerUserId: 'user-president',
    dueAt: D(3),
    status: 'open',
    ventureSlug: 'veridian-care',
    opportunityId: 'op-westhaven',
  },
  {
    id: 't-zonga-legal',
    title: 'Resolve Lagos partner legal review',
    context: 'Rock Nations contract requires jurisdiction clause adjustment.',
    queue: 'operator-actions',
    ownerUserId: 'user-ops',
    dueAt: D(5),
    status: 'in-progress',
    ventureSlug: 'zonga',
    opportunityId: 'op-rock-nations',
  },
  {
    id: 't-cupe-4400-followup',
    title: 'Confirm CUPE 4400 conversion call',
    context: 'Schedule conversion confirmation with A. Lavoie.',
    queue: 'partner-followups',
    ownerUserId: 'user-ops',
    dueAt: D(1),
    status: 'open',
    ventureSlug: 'union-eyes',
    opportunityId: 'op-cupe-4400',
  },
  {
    id: 't-praxis-update',
    title: 'Send Q2 update deck to Praxis',
    context: 'Quarterly investor cadence. Deck draft is in /documents.',
    queue: 'partner-followups',
    ownerUserId: 'user-founder',
    dueAt: D(7),
    status: 'open',
    ventureSlug: null,
    opportunityId: 'op-praxis-followon',
  },
  {
    id: 't-finance-mrr-recon',
    title: 'Reconcile April MRR across ventures',
    context: 'Stripe + manual invoices. Variance vs. dashboard expected.',
    queue: 'finance-review',
    ownerUserId: 'user-finance',
    dueAt: D(4),
    status: 'open',
    ventureSlug: null,
    opportunityId: null,
  },
  {
    id: 't-flow-incident',
    title: 'Investigate Flow staging deploy regression',
    context: 'Container Apps health check intermittent on canada-staging.',
    queue: 'product-escalations',
    ownerUserId: 'user-ops',
    dueAt: D(2),
    status: 'open',
    ventureSlug: 'flow',
    opportunityId: null,
  },
  {
    id: 't-firststone-icp',
    title: 'Run 10 founder interviews for First Stone ICP',
    context: 'Validate target ICP before further build.',
    queue: 'operator-actions',
    ownerUserId: 'user-founder',
    dueAt: D(21),
    status: 'open',
    ventureSlug: 'first-stone',
    opportunityId: null,
  },
  {
    id: 't-agrimo-intro',
    title: 'Founder intro call with UPA Québec',
    context: 'Agrimo entry — no other warm path established.',
    queue: 'founder-decisions',
    ownerUserId: 'user-founder',
    dueAt: D(10),
    status: 'open',
    ventureSlug: 'agrimo',
    opportunityId: 'op-upa-intro',
  },
] as const

export const DOCUMENTS: readonly Document[] = [
  {
    id: 'doc-praxis-q2',
    ventureSlug: null,
    title: 'Praxis Q2 Update Deck',
    category: 'investor',
    url: 'https://example.invalid/decks/praxis-q2',
    ownerUserId: 'user-founder',
    updatedAt: D(-5),
  },
  {
    id: 'doc-cupe-master',
    ventureSlug: 'union-eyes',
    title: 'CUPE Master Agreement Term Sheet v3',
    category: 'term-sheet',
    url: 'https://example.invalid/term-sheets/cupe-master-v3',
    ownerUserId: 'user-founder',
    updatedAt: D(-2),
  },
  {
    id: 'doc-veridian-onepager',
    ventureSlug: 'veridian-care',
    title: 'Veridian Care One-Pager',
    category: 'one-pager',
    url: 'https://example.invalid/one-pagers/veridian-care',
    ownerUserId: 'user-president',
    updatedAt: D(-10),
  },
  {
    id: 'doc-zonga-pricing',
    ventureSlug: 'zonga',
    title: 'Zonga Pricing Sheet (West Africa)',
    category: 'pricing',
    url: 'https://example.invalid/pricing/zonga-wa',
    ownerUserId: 'user-ops',
    updatedAt: D(-7),
  },
  {
    id: 'doc-westhaven-proposal',
    ventureSlug: 'veridian-care',
    title: 'Westhaven Health Proposal',
    category: 'proposal',
    url: 'https://example.invalid/proposals/westhaven',
    ownerUserId: 'user-president',
    updatedAt: D(-3),
  },
] as const

export const MEETINGS: readonly Meeting[] = [
  {
    id: 'm-cupe-followup',
    title: 'CUPE master agreement walkthrough',
    startsAt: D(2, 14),
    ventureSlug: 'union-eyes',
    organizationId: 'org-cupe',
    attendees: ['user-founder', 'user-ops'],
    briefingNotes: 'Bring revised pricing tiers and reference customer list.',
  },
  {
    id: 'm-westhaven',
    title: 'Westhaven SOC 2 walkthrough',
    startsAt: D(5, 10),
    ventureSlug: 'veridian-care',
    organizationId: 'org-westhaven',
    attendees: ['user-president', 'user-ops'],
    briefingNotes: 'Lead with evidence pack; have CIO walk through controls.',
  },
  {
    id: 'm-board',
    title: 'Q2 Board prep',
    startsAt: D(12, 9),
    ventureSlug: null,
    organizationId: null,
    attendees: ['user-founder', 'user-president', 'user-finance'],
    briefingNotes: 'Pull monthly portfolio review + dependency trend.',
  },
] as const

export const STRATEGIC_EVENTS: readonly StrategicEvent[] = [
  {
    id: 'ev-cupe-mtg',
    kind: 'meeting',
    title: 'CUPE walkthrough',
    occursAt: D(2, 14),
    ventureSlug: 'union-eyes',
  },
  {
    id: 'ev-westhaven-mtg',
    kind: 'meeting',
    title: 'Westhaven SOC 2 walkthrough',
    occursAt: D(5, 10),
    ventureSlug: 'veridian-care',
  },
  {
    id: 'ev-flow-release',
    kind: 'launch',
    title: 'Flow v2.4 release',
    occursAt: D(9, 16),
    ventureSlug: 'flow',
  },
  { id: 'ev-board', kind: 'board', title: 'Q2 Board prep', occursAt: D(12, 9), ventureSlug: null },
  {
    id: 'ev-praxis-update',
    kind: 'review',
    title: 'Praxis quarterly update',
    occursAt: D(15, 11),
    ventureSlug: 'union-eyes',
  },
  {
    id: 'ev-cupe-4400-renewal',
    kind: 'renewal',
    title: 'CUPE 4400 conversion deadline',
    occursAt: D(14, 17),
    ventureSlug: 'union-eyes',
  },
] as const

/** Previous-month studio MRR snapshot, used by automation rule MRR_DROP_MOM. */
export const PREVIOUS_MONTH_MRR_CENTS = 33_500_00
