"""
Admin configuration for core app.
Auto-generated by Nzila Code Generator — 2026-02-17
"""
from django.contrib import admin
from .models import (CourseModules, CourseVersions, CourseDiscussions, LearningPaths, LearningPathEnrollments, EvidenceBundlePdfs, CaseOutcomes, OutcomePredictions, PredictionModels, Questions, QuestionOptions, QuestionPools, PoolQuestions, QuizQuestions, QuizResponses, CertificateTemplates, Certificates, DigitalBadges, Skills, CourseSkills, LessonSkills, QuestionSkills, UserSkills, SkillValidations, SkillPrerequisites, CourseWorkflowReviews, CourseWorkflowHistory, ContentQualityChecklists, InstructorProfiles, CourseInstructors, InstructorAnalytics, InstructorCommunications, InstructorEarnings, SsoProviders, EnterpriseSessions, IdentityProviderMapping, SsoLoginAttempts, ResourcePermissions, PermissionOverrides, RoleHierarchy, PermissionCache, ComplianceReports, AuditLogExports, AuditLogsArchive, TribunalCasesRaw, IngestionJobs, IngestionErrors, AchievementCategories, AchievementProgress, UserStreaks, PointsSources, PointsTransactions, RewardsCatalog, UserRewards, Leaderboards, LeaderboardEntries, UserProfilesExtended, UserFollows, StudyBuddies, UserActivityFeed, UserGroups, GroupMembers, DiscussionForums, ForumPosts, AiInteractionLogs, StripeWebhookEvents, AiUsageDaily, AiQuota, CanliiIngestionRuns, CanliiApiRequests, CanliiDailyQuotas, OrgOffboardingRequests, DataExportContents, OffboardingAuditLog)


@admin.register(CourseModules)
class CourseModulesAdmin(admin.ModelAdmin):
    list_display = ['id', 'slug', 'created_at']
    search_fields = ['slug', 'description']
    ordering = ['-created_at']


@admin.register(CourseVersions)
class CourseVersionsAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    list_filter = ['change_type']
    search_fields = ['change_type']
    ordering = ['-created_at']


@admin.register(CourseDiscussions)
class CourseDiscussionsAdmin(admin.ModelAdmin):
    list_display = ['id']
    list_filter = ['discussion_type', 'is_pinned', 'is_instructor_question', 'is_flagged']
    search_fields = ['discussion_type']
    ordering = ['-created_at']


@admin.register(LearningPaths)
class LearningPathsAdmin(admin.ModelAdmin):
    list_display = ['id', 'slug', 'created_at']
    list_filter = ['required_tier']
    search_fields = ['slug', 'description', 'short_description', 'thumbnail_url']
    ordering = ['-created_at']


@admin.register(LearningPathEnrollments)
class LearningPathEnrollmentsAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    list_filter = ['certificate_issued']
    search_fields = ['certificate_id']
    ordering = ['-created_at']


@admin.register(EvidenceBundlePdfs)
class EvidenceBundlePdfsAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    search_fields = ['storage_path', 'file_name']
    ordering = ['-created_at']


@admin.register(CaseOutcomes)
class CaseOutcomesAdmin(admin.ModelAdmin):
    list_display = ['id']
    search_fields = ['case_complexity', 'respondent_type', 'tribunal_name', 'adjudicator_name']
    ordering = ['-created_at']


@admin.register(OutcomePredictions)
class OutcomePredictionsAdmin(admin.ModelAdmin):
    list_display = ['id']
    search_fields = ['model_type']
    ordering = ['-created_at']


@admin.register(PredictionModels)
class PredictionModelsAdmin(admin.ModelAdmin):
    list_display = ['id']
    search_fields = ['model_name', 'model_type', 'features_used', 'deployment_notes']
    ordering = ['-created_at']


@admin.register(Questions)
class QuestionsAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    search_fields = ['question_type', 'difficulty_level', 'question_text', 'question_html']
    ordering = ['-created_at']


@admin.register(QuestionOptions)
class QuestionOptionsAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    search_fields = ['option_text', 'option_html', 'feedback']
    ordering = ['-created_at']


@admin.register(QuestionPools)
class QuestionPoolsAdmin(admin.ModelAdmin):
    list_display = ['id', 'name', 'created_at']
    search_fields = ['name', 'description', 'tags']
    ordering = ['-created_at']


@admin.register(PoolQuestions)
class PoolQuestionsAdmin(admin.ModelAdmin):
    list_display = ['id']
    ordering = ['-created_at']


@admin.register(QuizQuestions)
class QuizQuestionsAdmin(admin.ModelAdmin):
    list_display = ['id']
    list_filter = ['is_required']
    search_fields = ['not']
    ordering = ['-created_at']


@admin.register(QuizResponses)
class QuizResponsesAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    list_filter = ['flagged']
    ordering = ['-created_at']


@admin.register(CertificateTemplates)
class CertificateTemplatesAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    list_filter = ['is_active', 'requires_approval']
    search_fields = ['description', 'template_type', 'logo_url', 'body_template']
    ordering = ['-created_at']


@admin.register(Certificates)
class CertificatesAdmin(admin.ModelAdmin):
    list_display = ['id', 'status', 'created_at']
    search_fields = ['certificate_type', 'status', 'recipient_name', 'description']
    ordering = ['-created_at']


@admin.register(DigitalBadges)
class DigitalBadgesAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    list_filter = ['recipient_hashed']
    search_fields = ['description', 'image_url', 'issuer_url', 'issuer_email']
    ordering = ['-created_at']


@admin.register(Skills)
class SkillsAdmin(admin.ModelAdmin):
    list_display = ['id', 'name', 'slug', 'created_at']
    list_filter = ['is_active']
    search_fields = ['name', 'slug', 'description', 'category']
    ordering = ['-created_at']


@admin.register(CourseSkills)
class CourseSkillsAdmin(admin.ModelAdmin):
    list_display = ['id']
    search_fields = ['proficiency_level', 'primary']
    ordering = ['-created_at']


@admin.register(LessonSkills)
class LessonSkillsAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    search_fields = ['proficiency_level', 'primary']
    ordering = ['-created_at']


@admin.register(QuestionSkills)
class QuestionSkillsAdmin(admin.ModelAdmin):
    list_display = ['id']
    search_fields = ['primary']
    ordering = ['-created_at']


@admin.register(UserSkills)
class UserSkillsAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    search_fields = ['validation_status']
    ordering = ['-created_at']


@admin.register(SkillValidations)
class SkillValidationsAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    ordering = ['-created_at']


@admin.register(SkillPrerequisites)
class SkillPrerequisitesAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    list_filter = ['is_mandatory']
    search_fields = ['required_proficiency', 'primary']
    ordering = ['-created_at']


@admin.register(CourseWorkflowReviews)
class CourseWorkflowReviewsAdmin(admin.ModelAdmin):
    list_display = ['id']
    list_filter = ['is_blocking']
    search_fields = ['decision']
    ordering = ['-created_at']


@admin.register(CourseWorkflowHistory)
class CourseWorkflowHistoryAdmin(admin.ModelAdmin):
    list_display = ['id']
    search_fields = ['to_status', 'reason', 'notes']
    ordering = ['-created_at']


@admin.register(ContentQualityChecklists)
class ContentQualityChecklistsAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    list_filter = ['accessibility_captions', 'accessibility_transcripts', 'accessibility_keyboard_nav', 'accessibility_screen_reader']
    search_fields = ['notes']
    ordering = ['-created_at']


@admin.register(InstructorProfiles)
class InstructorProfilesAdmin(admin.ModelAdmin):
    list_display = ['id']
    list_filter = ['display_on_public_profile']
    search_fields = ['headline', 'twitter_url', 'website_url', 'expertise_areas']
    ordering = ['-created_at']


@admin.register(CourseInstructors)
class CourseInstructorsAdmin(admin.ModelAdmin):
    list_display = ['id']
    list_filter = ['is_primary', 'is_active']
    search_fields = ['responsibilities']
    ordering = ['-created_at']


@admin.register(InstructorAnalytics)
class InstructorAnalyticsAdmin(admin.ModelAdmin):
    list_display = ['id']
    list_filter = ['period_type']
    search_fields = ['period_type', 'currency']
    ordering = ['-created_at']


@admin.register(InstructorCommunications)
class InstructorCommunicationsAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    list_filter = ['is_draft']
    search_fields = ['subject', 'message']
    ordering = ['-created_at']


@admin.register(InstructorEarnings)
class InstructorEarningsAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    search_fields = ['currency', 'payout_reference', 'notes']
    ordering = ['-created_at']


@admin.register(SsoProviders)
class SsoProvidersAdmin(admin.ModelAdmin):
    list_display = ['id']
    list_filter = ['is_default']
    search_fields = ['azure_client_id', 'azure_client_secret', 'saml_sso_url', 'saml_slo_url']
    ordering = ['-created_at']


@admin.register(EnterpriseSessions)
class EnterpriseSessionsAdmin(admin.ModelAdmin):
    list_display = ['id']
    search_fields = ['user_agent', 'device_id', 'revoke_reason']
    ordering = ['-created_at']


@admin.register(IdentityProviderMapping)
class IdentityProviderMappingAdmin(admin.ModelAdmin):
    list_display = ['id']
    search_fields = ['unlink_reason']
    ordering = ['-created_at']


@admin.register(SsoLoginAttempts)
class SsoLoginAttemptsAdmin(admin.ModelAdmin):
    list_display = ['id']
    search_fields = ['failure_reason', 'error_code', 'user_agent']
    ordering = ['-created_at']


@admin.register(ResourcePermissions)
class ResourcePermissionsAdmin(admin.ModelAdmin):
    list_display = ['id']
    search_fields = ['or']
    ordering = ['-created_at']


@admin.register(PermissionOverrides)
class PermissionOverridesAdmin(admin.ModelAdmin):
    list_display = ['id']
    search_fields = ['review_notes']
    ordering = ['-created_at']


@admin.register(RoleHierarchy)
class RoleHierarchyAdmin(admin.ModelAdmin):
    list_display = ['id']
    ordering = ['-created_at']


@admin.register(PermissionCache)
class PermissionCacheAdmin(admin.ModelAdmin):
    list_display = ['id']
    ordering = ['-created_at']


@admin.register(ComplianceReports)
class ComplianceReportsAdmin(admin.ModelAdmin):
    list_display = ['id']
    list_filter = ['report_type', 'format']
    search_fields = ['report_type', 'format', 'file_url']
    ordering = ['-created_at']


@admin.register(AuditLogExports)
class AuditLogExportsAdmin(admin.ModelAdmin):
    list_display = ['id']
    list_filter = ['export_type', 'format', 'approval_required']
    search_fields = ['export_type', 'format', 'file_url', 'encryption_key_id']
    ordering = ['-created_at']


@admin.register(AuditLogsArchive)
class AuditLogsArchiveAdmin(admin.ModelAdmin):
    list_display = ['id']
    search_fields = ['like']
    ordering = ['-created_at']


@admin.register(TribunalCasesRaw)
class TribunalCasesRawAdmin(admin.ModelAdmin):
    list_display = ['id']
    search_fields = ['case_title', 'citation', 'tribunal_province', 'respondent']
    ordering = ['-created_at']


@admin.register(IngestionJobs)
class IngestionJobsAdmin(admin.ModelAdmin):
    list_display = ['id']
    search_fields = ['source_system']
    ordering = ['-created_at']


@admin.register(IngestionErrors)
class IngestionErrorsAdmin(admin.ModelAdmin):
    list_display = ['id']
    list_filter = ['is_retryable']
    search_fields = ['error_type', 'error_stack', 'resolution_notes']
    ordering = ['-created_at']


@admin.register(AchievementCategories)
class AchievementCategoriesAdmin(admin.ModelAdmin):
    list_display = ['id', 'name', 'slug', 'created_at']
    list_filter = ['is_active']
    search_fields = ['name', 'slug', 'description', 'icon']
    ordering = ['-created_at']


@admin.register(AchievementProgress)
class AchievementProgressAdmin(admin.ModelAdmin):
    list_display = ['id']
    ordering = ['-created_at']


@admin.register(UserStreaks)
class UserStreaksAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    ordering = ['-created_at']


@admin.register(PointsSources)
class PointsSourcesAdmin(admin.ModelAdmin):
    list_display = ['id', 'name', 'slug', 'created_at']
    list_filter = ['requires_verification', 'is_active']
    search_fields = ['name', 'slug', 'description', 'category']
    ordering = ['-created_at']


@admin.register(PointsTransactions)
class PointsTransactionsAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    list_filter = ['is_admin_adjustment', 'is_reversed']
    search_fields = ['transaction_type', 'source_type', 'description', 'admin_note']
    ordering = ['-created_at']


@admin.register(RewardsCatalog)
class RewardsCatalogAdmin(admin.ModelAdmin):
    list_display = ['id', 'name', 'slug', 'created_at']
    list_filter = ['is_available']
    search_fields = ['name', 'slug', 'description', 'image_url']
    ordering = ['-created_at']


@admin.register(UserRewards)
class UserRewardsAdmin(admin.ModelAdmin):
    list_display = ['id', 'status', 'created_at']
    search_fields = ['status', 'redemption_code', 'delivery_status', 'notes']
    ordering = ['-created_at']


@admin.register(Leaderboards)
class LeaderboardsAdmin(admin.ModelAdmin):
    list_display = ['id', 'name', 'slug', 'created_at']
    list_filter = ['is_active', 'is_public']
    search_fields = ['name', 'slug', 'description', 'leaderboard_type']
    ordering = ['-created_at']


@admin.register(LeaderboardEntries)
class LeaderboardEntriesAdmin(admin.ModelAdmin):
    list_display = ['id']
    ordering = ['-created_at']


@admin.register(UserProfilesExtended)
class UserProfilesExtendedAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    list_filter = ['show_achievements', 'show_progress', 'show_activity']
    search_fields = ['bio', 'tagline', 'location', 'timezone']
    ordering = ['-created_at']


@admin.register(UserFollows)
class UserFollowsAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    list_filter = ['notify_on_activity', 'notify_on_achievements', 'is_active']
    search_fields = ['follow_type']
    ordering = ['-created_at']


@admin.register(StudyBuddies)
class StudyBuddiesAdmin(admin.ModelAdmin):
    list_display = ['id', 'status', 'created_at']
    list_filter = ['can_message']
    search_fields = ['status', 'shared_goals']
    ordering = ['-created_at']


@admin.register(UserActivityFeed)
class UserActivityFeedAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    list_filter = ['is_pinned']
    search_fields = ['activity_type', 'activity_title', 'activity_description', 'related_type']
    ordering = ['-created_at']


@admin.register(UserGroups)
class UserGroupsAdmin(admin.ModelAdmin):
    list_display = ['id', 'name', 'slug', 'created_at']
    list_filter = ['is_featured', 'is_active']
    search_fields = ['name', 'slug', 'description', 'group_type']
    ordering = ['-created_at']


@admin.register(GroupMembers)
class GroupMembersAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    list_filter = ['is_active', 'notifications_enabled']
    search_fields = ['role']
    ordering = ['-created_at']


@admin.register(DiscussionForums)
class DiscussionForumsAdmin(admin.ModelAdmin):
    list_display = ['id', 'name', 'slug', 'created_at']
    list_filter = ['is_locked', 'is_active']
    search_fields = ['name', 'slug', 'description', 'forum_type']
    ordering = ['-created_at']


@admin.register(ForumPosts)
class ForumPostsAdmin(admin.ModelAdmin):
    list_display = ['id', 'title', 'created_at']
    list_filter = ['is_pinned', 'is_locked', 'is_featured', 'is_solved']
    search_fields = ['title', 'content', 'content_format', 'post_type']
    ordering = ['-created_at']


@admin.register(AiInteractionLogs)
class AiInteractionLogsAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    list_filter = ['contains_legal_advice_warning']
    search_fields = ['session_id', 'interaction_type', 'response', 'model']
    ordering = ['-created_at']


@admin.register(StripeWebhookEvents)
class StripeWebhookEventsAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    search_fields = ['id']
    ordering = ['-created_at']


@admin.register(AiUsageDaily)
class AiUsageDailyAdmin(admin.ModelAdmin):
    list_display = ['id']
    ordering = ['-created_at']


@admin.register(AiQuota)
class AiQuotaAdmin(admin.ModelAdmin):
    list_display = ['id']
    list_filter = ['send_warnings']
    search_fields = ['alert_slack_webhook']
    ordering = ['-created_at']


@admin.register(CanliiIngestionRuns)
class CanliiIngestionRunsAdmin(admin.ModelAdmin):
    list_display = ['id', 'status']
    list_filter = ['exceeded_rate_limit', 'kill_switch_active']
    search_fields = ['status', 'trigger_source']
    ordering = ['-created_at']


@admin.register(CanliiApiRequests)
class CanliiApiRequestsAdmin(admin.ModelAdmin):
    list_display = ['id']
    list_filter = ['success', 'rate_limited']
    ordering = ['-created_at']


@admin.register(CanliiDailyQuotas)
class CanliiDailyQuotasAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    list_filter = ['limit_exceeded']
    ordering = ['-created_at']


@admin.register(OrgOffboardingRequests)
class OrgOffboardingRequestsAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    search_fields = ['reason', 'export_file_path', 'export_download_url', 'stripe_subscription_id']
    ordering = ['-created_at']


@admin.register(DataExportContents)
class DataExportContentsAdmin(admin.ModelAdmin):
    list_display = ['id']
    ordering = ['-created_at']


@admin.register(OffboardingAuditLog)
class OffboardingAuditLogAdmin(admin.ModelAdmin):
    list_display = ['id', 'created_at']
    search_fields = ['actor_role', 'user_agent', 'error_message']
    ordering = ['-created_at']
