"""
Django models for core app.
Auto-generated by Nzila Code Generator — 2026-02-17

DO NOT EDIT manually unless you know what you're doing.
Re-run the generator to overwrite.
"""
import uuid
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.contrib.postgres.search import SearchVectorField

try:
    from pgvector.django import VectorField
except ImportError:
    VectorField = None  # pgvector not installed


class BaseModel(models.Model):
    """Abstract base with standard audit fields."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class OrganizationModel(BaseModel):
    """Abstract base for multi-organization models."""
    organization = models.ForeignKey(
        'auth_core.Organizations',
        on_delete=models.CASCADE,
        related_name='%(class)ss'
    )

    class Meta:
        abstract = True



class CourseModules(BaseModel):
    """Migrated from sql: 017_courses_enhancement_phase1.sql"""
    module_number = models.IntegerField(null=True, blank=True)
    course_id = models.UUIDField(null=True, blank=True)
    slug = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    sort_order = models.IntegerField(null=True, blank=True)
    unlock_requirements = models.JSONField(default=dict, null=True, blank=True)
    resources = models.JSONField(default=dict, null=True, blank=True)

    class Meta:
        db_table = 'course_modules'
        verbose_name = 'CourseModules'
        constraints = [
            models.UniqueConstraint(fields=['course_id', 'slug'], name='unique_course_modules_course_id_slug'),
            models.UniqueConstraint(fields=['course_id', 'module_number'], name='unique_course_modules_course_id_module_number'),
        ]
        ordering = ['-created_at']

    def __str__(self):
        return str(self.slug)

class CourseVersions(BaseModel):
    """Migrated from sql: 017_courses_enhancement_phase1.sql"""
    version_number = models.IntegerField(null=True, blank=True)
    CHANGE_TYPE_CHOICES = [('major', 'Major'), ('minor', 'Minor'), ('patch', 'Patch'), ('regulatory', 'Regulatory')]

    course_id = models.UUIDField(null=True, blank=True)
    change_type = models.CharField(choices=CHANGE_TYPE_CHOICES, max_length=50, null=True, blank=True)
    published_at = models.DateTimeField(null=True, blank=True)
    retired_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'course_versions'
        verbose_name = 'CourseVersions'
        constraints = [
            models.UniqueConstraint(fields=['course_id', 'version_number'], name='unique_course_versions_course_id_version_number'),
        ]
        ordering = ['-created_at']

class CourseDiscussions(BaseModel):
    """Migrated from sql: 017_courses_enhancement_phase1.sql"""
    DISCUSSION_TYPE_CHOICES = [('question', 'Question'), ('discussion', 'Discussion'), ('announcement', 'Announcement'), ('reply', 'Reply')]

    course_id = models.UUIDField(null=True, blank=True)
    lesson_id = models.UUIDField(null=True, blank=True)
    parent_id = models.UUIDField(null=True, blank=True)
    discussion_type = models.CharField(choices=DISCUSSION_TYPE_CHOICES, max_length=50, null=True, blank=True)
    is_pinned = models.BooleanField(default=False)
    is_instructor_question = models.BooleanField(default=False)
    replies_count = models.IntegerField(null=True, blank=True)
    views_count = models.IntegerField(null=True, blank=True)
    marked_as_answer_at = models.DateTimeField(null=True, blank=True)
    marked_by = models.UUIDField(null=True, blank=True)
    is_flagged = models.BooleanField(default=False)
    is_locked = models.BooleanField(default=False)
    updated_at = models.DateTimeField(null=True, blank=True)
    deleted_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'course_discussions'
        verbose_name = 'CourseDiscussions'

class LearningPaths(BaseModel):
    """Migrated from sql: 017_courses_enhancement_phase1.sql"""
    REQUIRED_TIER_CHOICES = [('free', 'Free'), ('professional', 'Professional'), ('enterprise', 'Enterprise')]

    slug = models.CharField(max_length=200, unique=True)
    description = models.TextField(null=True, blank=True)
    short_description = models.CharField(max_length=500, null=True, blank=True)
    thumbnail_url = models.TextField(null=True, blank=True)
    cover_image_url = models.TextField(null=True, blank=True)
    target_audience = models.TextField(null=True, blank=True)
    career_outcomes = models.TextField(null=True, blank=True)
    estimated_hours = models.IntegerField(null=True, blank=True)
    category = models.CharField(max_length=100, null=True, blank=True)
    tags = models.JSONField(default=dict, null=True, blank=True)
    required_tier = models.CharField(choices=REQUIRED_TIER_CHOICES, max_length=50, null=True, blank=True, default='free')
    certificate_description = models.TextField(null=True, blank=True)
    ce_credits_total = models.DecimalField(max_digits=4, decimal_places=1, null=True, blank=True)
    completions_count = models.IntegerField(null=True, blank=True)
    average_rating = models.DecimalField(max_digits=3, decimal_places=2, null=True, blank=True)
    meta_description = models.TextField(null=True, blank=True)

    class Meta:
        db_table = 'learning_paths'
        verbose_name = 'LearningPaths'
        ordering = ['-created_at']

    def __str__(self):
        return str(self.slug)

class LearningPathEnrollments(BaseModel):
    """Migrated from sql: 017_courses_enhancement_phase1.sql"""
    user_id = models.UUIDField(null=True, blank=True)
    learning_path_id = models.UUIDField(null=True, blank=True)
    progress_percentage = models.IntegerField(null=True, blank=True)
    courses_total = models.IntegerField(null=True, blank=True)
    current_course_id = models.UUIDField(null=True, blank=True)
    certificate_issued = models.BooleanField(default=False)
    certificate_id = models.CharField(max_length=100, null=True, blank=True, unique=True)
    last_accessed_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'learning_path_enrollments'
        verbose_name = 'LearningPathEnrollments'
        constraints = [
            models.UniqueConstraint(fields=['user_id', 'learning_path_id'], name='unique_learning_path_enrollments_user_id_learning_path_id'),
        ]
        ordering = ['-created_at']

class EvidenceBundlePdfs(BaseModel):
    """Migrated from sql: 020_evidence_bundles_tracking.sql"""
    case_id = models.UUIDField(null=True, blank=True)
    storage_path = models.TextField(null=True, blank=True)
    file_name = models.TextField(null=True, blank=True)
    file_size = models.BigIntegerField(null=True, blank=True)
    created_by = models.UUIDField(null=True, blank=True)
    created_at = models.DateTimeField(null=True, blank=True)
    accessed_count = models.IntegerField(null=True, blank=True)
    last_accessed_at = models.DateTimeField(null=True, blank=True)
    metadata = models.JSONField(default=dict, null=True, blank=True)

    class Meta:
        db_table = 'evidence_bundle_pdfs'
        verbose_name = 'EvidenceBundlePdfs'
        ordering = ['-created_at']

class CaseOutcomes(BaseModel):
    """Migrated from sql: 20250108000004_create_outcome_prediction.sql"""
    case_id = models.UUIDField(null=True, blank=True)
    case_complexity = models.CharField(max_length=50, null=True, blank=True)
    respondent_type = models.CharField(max_length=100, null=True, blank=True)
    tribunal_name = models.CharField(max_length=255, null=True, blank=True)
    adjudicator_name = models.CharField(max_length=255, null=True, blank=True)
    updated_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'case_outcomes'
        verbose_name = 'CaseOutcomes'
        constraints = [
            models.UniqueConstraint(fields=['case_id'], name='unique_case_outcomes_case_id'),
        ]

class OutcomePredictions(BaseModel):
    """Migrated from sql: 20250108000004_create_outcome_prediction.sql"""
    model_version = models.CharField(max_length=100, null=True, blank=True)
    case_id = models.UUIDField(null=True, blank=True)
    model_type = models.CharField(max_length=50)
    feature_importance = models.JSONField(default=dict, null=True, blank=True)
    validated_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'outcome_predictions'
        verbose_name = 'OutcomePredictions'
        constraints = [
            models.UniqueConstraint(fields=['case_id', 'model_version'], name='unique_outcome_predictions_case_id_model_version'),
        ]

class PredictionModels(BaseModel):
    """Migrated from sql: 20250108000004_create_outcome_prediction.sql"""
    model_name = models.CharField(max_length=255)
    model_type = models.CharField(max_length=50)
    training_date = models.DateTimeField(null=True, blank=True)
    training_duration_seconds = models.IntegerField(null=True, blank=True)
    precision_score = models.FloatField(null=True, blank=True)
    f1_score = models.FloatField(null=True, blank=True)
    auc_roc = models.FloatField(null=True, blank=True)
    features_used = models.TextField(null=True, blank=True)
    deployed_at = models.DateTimeField(null=True, blank=True)
    deployment_notes = models.TextField(null=True, blank=True)
    created_by = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'prediction_models'
        verbose_name = 'PredictionModels'

class Questions(BaseModel):
    """Migrated from sql: 20250115000003_quiz_system.sql"""
    course_id = models.UUIDField(null=True, blank=True)
    lesson_id = models.UUIDField(null=True, blank=True)
    question_type = models.TextField(null=True, blank=True)
    difficulty_level = models.TextField(null=True, blank=True)
    question_text = models.TextField(null=True, blank=True)
    question_html = models.TextField(null=True, blank=True)
    time_limit_seconds = models.IntegerField(null=True, blank=True)
    tags = models.TextField(null=True, blank=True)
    created_by = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'questions'
        verbose_name = 'Questions'
        ordering = ['-created_at']

class QuestionOptions(BaseModel):
    """Migrated from sql: 20250115000003_quiz_system.sql"""
    question_id = models.UUIDField()
    option_text = models.TextField(null=True, blank=True)
    option_html = models.TextField(null=True, blank=True)
    feedback = models.TextField(null=True, blank=True)
    metadata = models.JSONField(default=dict, null=True, blank=True)
    created_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'question_options'
        verbose_name = 'QuestionOptions'
        ordering = ['-created_at']

class QuestionPools(BaseModel):
    """Migrated from sql: 20250115000003_quiz_system.sql"""
    course_id = models.UUIDField(null=True, blank=True)
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    tags = models.TextField(null=True, blank=True)
    created_by = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'question_pools'
        verbose_name = 'QuestionPools'
        ordering = ['-created_at']

    def __str__(self):
        return str(self.name)

class PoolQuestions(BaseModel):
    """Migrated from sql: 20250115000003_quiz_system.sql"""
    pool_id = models.UUIDField(null=True, blank=True)
    question_id = models.UUIDField(null=True, blank=True)
    weight = models.IntegerField(null=True, blank=True)

    class Meta:
        db_table = 'pool_questions'
        verbose_name = 'PoolQuestions'

class QuizQuestions(BaseModel):
    """Migrated from sql: 20250115000003_quiz_system.sql"""
    quiz_id = models.UUIDField()
    question_id = models.UUIDField(null=True, blank=True)
    question_pool_id = models.UUIDField(null=True, blank=True)
    points = models.IntegerField(null=True, blank=True)
    is_required = models.BooleanField(default=False)
    not_field = models.TextField(null=True, blank=True)

    class Meta:
        db_table = 'quiz_questions'
        verbose_name = 'QuizQuestions'

class QuizResponses(BaseModel):
    """Migrated from sql: 20250115000003_quiz_system.sql"""
    attempt_id = models.UUIDField()
    question_id = models.UUIDField()
    answer_data = models.JSONField(default=dict, null=True, blank=True)
    points_earned = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    points_possible = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    time_spent_seconds = models.IntegerField(null=True, blank=True)
    flagged = models.BooleanField(default=False)
    graded_by = models.UUIDField(null=True, blank=True)
    created_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'quiz_responses'
        verbose_name = 'QuizResponses'
        ordering = ['-created_at']

class CertificateTemplates(BaseModel):
    """Migrated from sql: 20250115000004_certificates.sql"""
    description = models.TextField(null=True, blank=True)
    template_type = models.TextField(null=True, blank=True)
    logo_url = models.TextField(null=True, blank=True)
    body_template = models.TextField(null=True, blank=True)
    signature_fields = models.JSONField(default=dict, null=True, blank=True)
    is_active = models.BooleanField(default=False)
    requires_approval = models.BooleanField(default=False)

    class Meta:
        db_table = 'certificate_templates'
        verbose_name = 'CertificateTemplates'
        ordering = ['-created_at']

class Certificates(BaseModel):
    """Migrated from sql: 20250115000004_certificates.sql"""
    course_id = models.UUIDField(null=True, blank=True)
    quiz_attempt_id = models.UUIDField(null=True, blank=True)
    template_id = models.UUIDField(null=True, blank=True)
    certificate_type = models.TextField(null=True, blank=True)
    status = models.TextField(null=True, blank=True)
    recipient_name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    issue_date = models.DateField(null=True, blank=True)
    expiry_date = models.DateField(null=True, blank=True)
    ce_hours = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    regulatory_body = models.CharField(max_length=100, null=True, blank=True)
    provincial = models.TextField(null=True, blank=True)
    pdf_file_path = models.TextField(null=True, blank=True)
    thumbnail_url = models.TextField(null=True, blank=True)
    approved_at = models.DateTimeField(null=True, blank=True)
    approval_notes = models.TextField(null=True, blank=True)
    revoked_at = models.DateTimeField(null=True, blank=True)
    revocation_reason = models.TextField(null=True, blank=True)

    class Meta:
        db_table = 'certificates'
        verbose_name = 'Certificates'
        ordering = ['-created_at']

class DigitalBadges(BaseModel):
    """Migrated from sql: 20250115000004_certificates.sql"""
    user_id = models.UUIDField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    image_url = models.TextField(null=True, blank=True)
    issuer_url = models.TextField(null=True, blank=True)
    issuer_email = models.CharField(max_length=255, null=True, blank=True)
    issuer_image_url = models.TextField(null=True, blank=True)
    recipient_hashed = models.BooleanField(default=False)
    issued_on = models.DateTimeField(null=True, blank=True)
    expires_on = models.DateTimeField(null=True, blank=True)
    revocation_reason = models.TextField(null=True, blank=True)
    metadata = models.JSONField(default=dict, null=True, blank=True)

    class Meta:
        db_table = 'digital_badges'
        verbose_name = 'DigitalBadges'
        ordering = ['-created_at']

class Skills(BaseModel):
    """Migrated from sql: 20250115000006_skills_validation.sql"""
    name = models.CharField(max_length=255)
    slug = models.CharField(max_length=255, unique=True)
    description = models.TextField(null=True, blank=True)
    category = models.CharField(max_length=100)
    importance_weight = models.DecimalField(max_digits=3, decimal_places=2, null=True, blank=True)
    expiry_months = models.IntegerField(null=True, blank=True)
    is_active = models.BooleanField(default=False)

    class Meta:
        db_table = 'skills'
        verbose_name = 'Skills'
        ordering = ['-created_at']

    def __str__(self):
        return str(self.name)

class CourseSkills(BaseModel):
    """Migrated from sql: 20250115000006_skills_validation.sql"""
    course_id = models.UUIDField(null=True, blank=True)
    skill_id = models.UUIDField(null=True, blank=True)
    proficiency_level = models.TextField(null=True, blank=True)
    primary = models.TextField(null=True, blank=True)

    class Meta:
        db_table = 'course_skills'
        verbose_name = 'CourseSkills'

class LessonSkills(BaseModel):
    """Migrated from sql: 20250115000006_skills_validation.sql"""
    lesson_id = models.UUIDField(null=True, blank=True)
    skill_id = models.UUIDField(null=True, blank=True)
    proficiency_level = models.TextField(null=True, blank=True)
    weight = models.DecimalField(max_digits=3, decimal_places=2, null=True, blank=True)
    created_at = models.DateTimeField(null=True, blank=True)
    primary = models.TextField(null=True, blank=True)

    class Meta:
        db_table = 'lesson_skills'
        verbose_name = 'LessonSkills'
        ordering = ['-created_at']

class QuestionSkills(BaseModel):
    """Migrated from sql: 20250115000006_skills_validation.sql"""
    question_id = models.UUIDField(null=True, blank=True)
    skill_id = models.UUIDField(null=True, blank=True)
    weight = models.DecimalField(max_digits=3, decimal_places=2, null=True, blank=True)
    primary = models.TextField(null=True, blank=True)

    class Meta:
        db_table = 'question_skills'
        verbose_name = 'QuestionSkills'

class UserSkills(BaseModel):
    """Migrated from sql: 20250115000006_skills_validation.sql"""
    user_id = models.UUIDField()
    skill_id = models.UUIDField()
    proficiency_score = models.DecimalField(max_digits=5, decimal_places=2)
    validation_status = models.TextField(null=True, blank=True)
    validated_at = models.DateTimeField(null=True, blank=True)
    expires_at = models.DateTimeField(null=True, blank=True)
    passed_assessments = models.IntegerField(null=True, blank=True)
    failed_assessments = models.IntegerField(null=True, blank=True)
    average_quiz_score = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    best_quiz_score = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    last_practiced_at = models.DateTimeField(null=True, blank=True)
    last_validated_at = models.DateTimeField(null=True, blank=True)
    courses_completed = models.IntegerField(null=True, blank=True)
    lessons_completed = models.IntegerField(null=True, blank=True)

    class Meta:
        db_table = 'user_skills'
        verbose_name = 'UserSkills'
        constraints = [
            models.UniqueConstraint(fields=['user_id', 'skill_id'], name='unique_user_skills_user_id_skill_id'),
        ]
        ordering = ['-created_at']

class SkillValidations(BaseModel):
    """Migrated from sql: 20250115000006_skills_validation.sql"""
    user_id = models.UUIDField()
    skill_id = models.UUIDField()
    user_skill_id = models.UUIDField(null=True, blank=True)
    course_id = models.UUIDField(null=True, blank=True)
    lesson_id = models.UUIDField(null=True, blank=True)
    score = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    correct_answers = models.IntegerField(null=True, blank=True)
    time_spent_seconds = models.IntegerField(null=True, blank=True)
    validated_by = models.UUIDField(null=True, blank=True)
    metadata = models.JSONField(default=dict, null=True, blank=True)
    validated_at = models.DateTimeField(null=True, blank=True)
    expires_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'skill_validations'
        verbose_name = 'SkillValidations'
        ordering = ['-created_at']

class SkillPrerequisites(BaseModel):
    """Migrated from sql: 20250115000006_skills_validation.sql"""
    skill_id = models.UUIDField(null=True, blank=True)
    prerequisite_skill_id = models.UUIDField(null=True, blank=True)
    required_proficiency = models.TextField(null=True, blank=True)
    is_mandatory = models.BooleanField(default=False)
    order_index = models.IntegerField(null=True, blank=True)
    created_at = models.DateTimeField(null=True, blank=True)
    primary = models.TextField(null=True, blank=True)

    class Meta:
        db_table = 'skill_prerequisites'
        verbose_name = 'SkillPrerequisites'
        ordering = ['-created_at']

class CourseWorkflowReviews(BaseModel):
    """Migrated from sql: 20250115000007_course_workflow.sql"""
    course_id = models.UUIDField(null=True, blank=True)
    version_id = models.UUIDField(null=True, blank=True)
    assigned_by = models.UUIDField(null=True, blank=True)
    decision = models.TextField(null=True, blank=True)
    quality_score = models.IntegerField(null=True, blank=True)
    completed_at = models.DateTimeField(null=True, blank=True)
    due_date = models.DateTimeField(null=True, blank=True)
    is_blocking = models.BooleanField(default=False)
    course = models.DateTimeField(null=True, blank=True)
    updated_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'course_workflow_reviews'
        verbose_name = 'CourseWorkflowReviews'

class CourseWorkflowHistory(BaseModel):
    """Migrated from sql: 20250115000007_course_workflow.sql"""
    course_id = models.UUIDField(null=True, blank=True)
    to_status = models.TextField(null=True, blank=True)
    reason = models.TextField(null=True, blank=True)
    notes = models.TextField(null=True, blank=True)
    metadata = models.JSONField(default=dict, null=True, blank=True)

    class Meta:
        db_table = 'course_workflow_history'
        verbose_name = 'CourseWorkflowHistory'

class ContentQualityChecklists(BaseModel):
    """Migrated from sql: 20250115000007_course_workflow.sql"""
    course_id = models.UUIDField(null=True, blank=True)
    version_id = models.UUIDField(null=True, blank=True)
    accessibility_captions = models.BooleanField(default=False)
    accessibility_transcripts = models.BooleanField(default=False)
    accessibility_keyboard_nav = models.BooleanField(default=False)
    accessibility_screen_reader = models.BooleanField(default=False)
    bilingual_en_available = models.BooleanField(default=False)
    bilingual_fr_available = models.BooleanField(default=False)
    video_quality_standards = models.BooleanField(default=False)
    video_audio_clarity = models.BooleanField(default=False)
    video_encoding_correct = models.BooleanField(default=False)
    mobile_responsive = models.BooleanField(default=False)
    cross_browser_tested = models.BooleanField(default=False)
    learning_objectives_clear = models.BooleanField(default=False)
    assessments_valid = models.BooleanField(default=False)
    content_accurate = models.BooleanField(default=False)
    references_cited = models.BooleanField(default=False)
    regulatory_compliance = models.BooleanField(default=False)
    privacy_compliant = models.BooleanField(default=False)
    copyright_cleared = models.BooleanField(default=False)
    completed_items = models.IntegerField(null=True, blank=True)
    completion_percentage = models.IntegerField(null=True, blank=True)
    notes = models.TextField(null=True, blank=True)

    class Meta:
        db_table = 'content_quality_checklists'
        verbose_name = 'ContentQualityChecklists'
        constraints = [
            models.UniqueConstraint(fields=['course_id', 'version_id'], name='unique_content_quality_checklists_course_id_version_id'),
        ]
        ordering = ['-created_at']

class InstructorProfiles(BaseModel):
    """Migrated from sql: 20250115000008_instructor_portal.sql"""
    user_id = models.UUIDField(null=True, blank=True, unique=True)
    headline = models.CharField(max_length=200, null=True, blank=True)
    previous_roles = models.JSONField(default=dict, null=True, blank=True)
    twitter_url = models.TextField(null=True, blank=True)
    website_url = models.TextField(null=True, blank=True)
    expertise_areas = models.TextField(null=True, blank=True)
    approved_by = models.UUIDField(null=True, blank=True)
    approved_at = models.DateTimeField(null=True, blank=True)
    notification_preferences = models.JSONField(default=dict, null=True, blank=True)
    display_on_public_profile = models.BooleanField(default=False)
    cover_image_url = models.TextField(null=True, blank=True)
    video_intro_url = models.TextField(null=True, blank=True)
    updated_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'instructor_profiles'
        verbose_name = 'InstructorProfiles'

class CourseInstructors(BaseModel):
    """Migrated from sql: 20250115000008_instructor_portal.sql"""
    role = models.CharField(max_length=100, null=True, blank=True)
    course_id = models.UUIDField(null=True, blank=True)
    instructor_id = models.UUIDField(null=True, blank=True)
    is_primary = models.BooleanField(default=False)
    responsibilities = models.TextField(null=True, blank=True)
    removed_at = models.DateTimeField(null=True, blank=True)
    is_active = models.BooleanField(default=False)

    class Meta:
        db_table = 'course_instructors'
        verbose_name = 'CourseInstructors'
        constraints = [
            models.UniqueConstraint(fields=['course_id', 'instructor_id', 'role'], name='unique_course_instructors_course_id_instructor_id_role'),
        ]

class InstructorAnalytics(BaseModel):
    """Migrated from sql: 20250115000008_instructor_portal.sql"""
    period_start = models.DateTimeField(null=True, blank=True)
    PERIOD_TYPE_CHOICES = [('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')]

    instructor_id = models.UUIDField(null=True, blank=True)
    period_end = models.DateField(null=True, blank=True)
    period_type = models.CharField(choices=PERIOD_TYPE_CHOICES, max_length=20)
    new_students = models.IntegerField(null=True, blank=True)
    active_students = models.IntegerField(null=True, blank=True)
    lessons_delivered = models.IntegerField(null=True, blank=True)
    total_watch_minutes = models.IntegerField(null=True, blank=True)
    avg_completion_rate = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    total_questions_answered = models.IntegerField(null=True, blank=True)
    avg_response_time_hours = models.DecimalField(max_digits=8, decimal_places=2, null=True, blank=True)
    certificates_issued = models.IntegerField(null=True, blank=True)
    currency = models.CharField(max_length=3, null=True, blank=True)
    ratings = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'instructor_analytics'
        verbose_name = 'InstructorAnalytics'
        constraints = [
            models.UniqueConstraint(fields=['instructor_id', 'period_start', 'period_end', 'period_type'], name='unique_instructor_analytics_instructor_id_period_start_period_end_period_type'),
        ]

class InstructorCommunications(BaseModel):
    """Migrated from sql: 20250115000008_instructor_portal.sql"""
    instructor_id = models.UUIDField(null=True, blank=True)
    course_id = models.UUIDField(null=True, blank=True)
    subject = models.CharField(max_length=500, null=True, blank=True)
    message = models.TextField(null=True, blank=True)
    sent_at = models.DateTimeField(null=True, blank=True)
    is_draft = models.BooleanField(default=False)
    delivered_count = models.IntegerField(null=True, blank=True)
    read_count = models.IntegerField(null=True, blank=True)
    failed_count = models.IntegerField(null=True, blank=True)

    class Meta:
        db_table = 'instructor_communications'
        verbose_name = 'InstructorCommunications'
        ordering = ['-created_at']

class InstructorEarnings(BaseModel):
    """Migrated from sql: 20250115000008_instructor_portal.sql"""
    instructor_id = models.UUIDField(null=True, blank=True)
    course_id = models.UUIDField(null=True, blank=True)
    enrollment_id = models.UUIDField(null=True, blank=True)
    platform_fee = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    net_amount = models.DecimalField(max_digits=10, decimal_places=2)
    currency = models.CharField(max_length=3, null=True, blank=True)
    payout_date = models.DateField(null=True, blank=True)
    payout_reference = models.CharField(max_length=200, null=True, blank=True)
    notes = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'instructor_earnings'
        verbose_name = 'InstructorEarnings'
        ordering = ['-created_at']

class SsoProviders(BaseModel):
    """Migrated from sql: 20250116000001_enterprise_sso_auth.sql"""
    slug = models.SlugField(max_length=255, null=True, blank=True)
    organization_id = models.UUIDField(null=True, blank=True)
    is_default = models.BooleanField(default=False)
    azure_client_id = models.CharField(max_length=255, null=True, blank=True)
    azure_client_secret = models.TextField(null=True, blank=True)
    saml_sso_url = models.TextField(null=True, blank=True)
    saml_slo_url = models.TextField(null=True, blank=True)
    oidc_client_id = models.CharField(max_length=255, null=True, blank=True)
    oidc_client_secret = models.TextField(null=True, blank=True)
    oidc_token_endpoint = models.TextField(null=True, blank=True)
    oidc_userinfo_endpoint = models.TextField(null=True, blank=True)
    oidc_jwks_uri = models.TextField(null=True, blank=True)
    updated_at = models.DateTimeField(null=True, blank=True)
    last_sync_at = models.DateTimeField(null=True, blank=True)
    deleted_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'sso_providers'
        verbose_name = 'SsoProviders'
        constraints = [
            models.UniqueConstraint(fields=['organization_id', 'slug'], name='unique_sso_providers_organization_id_slug'),
        ]

class EnterpriseSessions(BaseModel):
    """Migrated from sql: 20250116000001_enterprise_sso_auth.sql"""
    organization_id = models.UUIDField(null=True, blank=True)
    sso_provider_id = models.UUIDField(null=True, blank=True)
    user_agent = models.TextField(null=True, blank=True)
    device_id = models.CharField(max_length=255, null=True, blank=True)
    expires_at = models.DateTimeField(null=True, blank=True)
    last_activity_at = models.DateTimeField(null=True, blank=True)
    revoked_at = models.DateTimeField(null=True, blank=True)
    revoke_reason = models.CharField(max_length=255, null=True, blank=True)
    updated_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'enterprise_sessions'
        verbose_name = 'EnterpriseSessions'

class IdentityProviderMapping(BaseModel):
    """Migrated from sql: 20250116000001_enterprise_sso_auth.sql"""
    provider_user_id = models.CharField(max_length=255, null=True, blank=True)
    sso_provider_id = models.UUIDField(null=True, blank=True)
    linked_at = models.DateTimeField(null=True, blank=True)
    unlinked_at = models.DateTimeField(null=True, blank=True)
    unlink_reason = models.TextField(null=True, blank=True)
    login_count = models.IntegerField(null=True, blank=True)
    updated_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'identity_provider_mapping'
        verbose_name = 'IdentityProviderMapping'
        constraints = [
            models.UniqueConstraint(fields=['sso_provider_id', 'provider_user_id'], name='unique_identity_provider_mapping_sso_provider_id_provider_user_id'),
        ]

class SsoLoginAttempts(BaseModel):
    """Migrated from sql: 20250116000001_enterprise_sso_auth.sql"""
    sso_provider_id = models.UUIDField(null=True, blank=True)
    user_id = models.UUIDField(null=True, blank=True)
    failure_reason = models.TextField(null=True, blank=True)
    error_code = models.CharField(max_length=100, null=True, blank=True)
    user_agent = models.TextField(null=True, blank=True)
    location = models.JSONField(default=dict, null=True, blank=True)

    class Meta:
        db_table = 'sso_login_attempts'
        verbose_name = 'SsoLoginAttempts'

class ResourcePermissions(BaseModel):
    """Migrated from sql: 20250116000002_advanced_rbac.sql"""
    scope_id = models.UUIDField(null=True, blank=True)
    or_field = models.TextField(null=True, blank=True)
    granted_at = models.DateTimeField(null=True, blank=True)
    revoked_at = models.DateTimeField(null=True, blank=True)
    revoked_by = models.UUIDField(null=True, blank=True)
    metadata = models.JSONField(default=dict, null=True, blank=True)
    updated_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'resource_permissions'
        verbose_name = 'ResourcePermissions'

class PermissionOverrides(BaseModel):
    """Migrated from sql: 20250116000002_advanced_rbac.sql"""
    organization_id = models.UUIDField(null=True, blank=True)
    approved_at = models.DateTimeField(null=True, blank=True)
    effective_until = models.DateTimeField(null=True, blank=True)
    last_reviewed_at = models.DateTimeField(null=True, blank=True)
    reviewed_by = models.UUIDField(null=True, blank=True)
    review_notes = models.TextField(null=True, blank=True)
    next_review_date = models.DateField(null=True, blank=True)
    updated_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'permission_overrides'
        verbose_name = 'PermissionOverrides'

class RoleHierarchy(BaseModel):
    """Migrated from sql: 20250116000002_advanced_rbac.sql"""
    parent_role_id = models.UUIDField(null=True, blank=True)
    child_role_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'role_hierarchy'
        verbose_name = 'RoleHierarchy'
        constraints = [
            models.UniqueConstraint(fields=['parent_role_id', 'child_role_id'], name='unique_role_hierarchy_parent_role_id_child_role_id'),
        ]

class PermissionCache(BaseModel):
    """Migrated from sql: 20250116000002_advanced_rbac.sql"""
    organization_id = models.UUIDField(null=True, blank=True)
    resource_id = models.UUIDField(null=True, blank=True)
    expires_at = models.DateTimeField(null=True, blank=True)
    cache_version = models.IntegerField(null=True, blank=True)
    updated_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'permission_cache'
        verbose_name = 'PermissionCache'

class ComplianceReports(BaseModel):
    """Migrated from sql: 20250116000003_audit_logs_enhancement.sql"""
    REPORT_TYPE_CHOICES = [('access_control', 'Access Control'), ('data_access', 'Data Access'), ('authentication', 'Authentication'), ('authorization_changes', 'Authorization Changes'), ('security_incidents', 'Security Incidents'), ('user_activity', 'User Activity'), ('admin_actions', 'Admin Actions'), ('compliance_summary', 'Compliance Summary'), ('custom', 'Custom')]
    FORMAT_CHOICES = [('pdf', 'Pdf'), ('csv', 'Csv'), ('json', 'Json'), ('xlsx', 'Xlsx')]

    report_type = models.CharField(choices=REPORT_TYPE_CHOICES, max_length=100)
    period_end = models.DateTimeField(null=True, blank=True)
    format = models.CharField(choices=FORMAT_CHOICES, max_length=50, default='pdf')
    file_url = models.TextField(null=True, blank=True)
    events_by_category = models.JSONField(default=dict, null=True, blank=True)
    events_by_severity = models.JSONField(default=dict, null=True, blank=True)
    anomalies_detected = models.IntegerField(null=True, blank=True)
    findings = models.JSONField(default=dict, null=True, blank=True)
    next_run_at = models.DateTimeField(null=True, blank=True)
    generated_at = models.DateTimeField(null=True, blank=True)
    expires_at = models.DateTimeField(null=True, blank=True)
    updated_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'compliance_reports'
        verbose_name = 'ComplianceReports'

class AuditLogExports(BaseModel):
    """Migrated from sql: 20250116000003_audit_logs_enhancement.sql"""
    EXPORT_TYPE_CHOICES = [('full', 'Full'), ('filtered', 'Filtered'), ('compliance', 'Compliance'), ('investigation', 'Investigation')]
    FORMAT_CHOICES = [('json', 'Json'), ('csv', 'Csv'), ('xlsx', 'Xlsx'), ('syslog', 'Syslog')]

    export_type = models.CharField(choices=EXPORT_TYPE_CHOICES, max_length=50)
    period_end = models.DateTimeField(null=True, blank=True)
    format = models.CharField(choices=FORMAT_CHOICES, max_length=50, default='json')
    file_url = models.TextField(null=True, blank=True)
    file_size_bytes = models.BigIntegerField(null=True, blank=True)
    total_records = models.IntegerField(null=True, blank=True)
    encryption_key_id = models.CharField(max_length=255, null=True, blank=True)
    approved_by = models.UUIDField(null=True, blank=True)
    approved_at = models.DateTimeField(null=True, blank=True)
    approval_required = models.BooleanField(default=False)
    approval_reason = models.TextField(null=True, blank=True)
    last_downloaded_at = models.DateTimeField(null=True, blank=True)
    downloaded_by = models.UUIDField(null=True, blank=True)
    deleted_at = models.DateTimeField(null=True, blank=True)
    updated_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'audit_log_exports'
        verbose_name = 'AuditLogExports'

class AuditLogsArchive(BaseModel):
    """Migrated from sql: 20250116000003_audit_logs_enhancement.sql"""
    like = models.TextField(null=True, blank=True)

    class Meta:
        db_table = 'audit_logs_archive'
        verbose_name = 'AuditLogsArchive'

class TribunalCasesRaw(BaseModel):
    """Migrated from sql: 20250116000004_ingestion_pipeline.sql"""
    case_title = models.TextField(null=True, blank=True)
    citation = models.CharField(max_length=500, null=True, blank=True)
    tribunal_province = models.CharField(max_length=50, null=True, blank=True)
    decision_date = models.DateField(null=True, blank=True)
    filing_date = models.DateField(null=True, blank=True)
    respondent = models.TextField(null=True, blank=True)
    pdf_url = models.TextField(null=True, blank=True)
    remedies = models.JSONField(default=dict, null=True, blank=True)
    review_notes = models.TextField(null=True, blank=True)
    promoted_case_id = models.UUIDField(null=True, blank=True)
    promoted_at = models.DateTimeField(null=True, blank=True)
    promoted_by = models.UUIDField(null=True, blank=True)
    updated_at = models.DateTimeField(null=True, blank=True)
    reviewed_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'tribunal_cases_raw'
        verbose_name = 'TribunalCasesRaw'

class IngestionJobs(BaseModel):
    """Migrated from sql: 20250116000004_ingestion_pipeline.sql"""
    source_system = models.CharField(max_length=100)
    source_config = models.JSONField(default=dict, null=True, blank=True)
    started_at = models.DateTimeField(null=True, blank=True)
    completed_at = models.DateTimeField(null=True, blank=True)
    duration_seconds = models.IntegerField(null=True, blank=True)
    high_confidence_count = models.IntegerField(null=True, blank=True)
    error_details = models.JSONField(default=dict, null=True, blank=True)
    updated_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'ingestion_jobs'
        verbose_name = 'IngestionJobs'

class IngestionErrors(BaseModel):
    """Migrated from sql: 20250116000004_ingestion_pipeline.sql"""
    raw_case_id = models.UUIDField(null=True, blank=True)
    error_type = models.CharField(max_length=100, null=True, blank=True)
    error_stack = models.TextField(null=True, blank=True)
    request_payload = models.JSONField(default=dict, null=True, blank=True)
    response_data = models.JSONField(default=dict, null=True, blank=True)
    is_retryable = models.BooleanField(default=False)
    retry_count = models.IntegerField(null=True, blank=True)
    resolved_at = models.DateTimeField(null=True, blank=True)
    resolution_notes = models.TextField(null=True, blank=True)

    class Meta:
        db_table = 'ingestion_errors'
        verbose_name = 'IngestionErrors'

class AchievementCategories(BaseModel):
    """Migrated from sql: 20250116000005_migrate_gamification_schema.sql"""
    name = models.CharField(max_length=100, unique=True)
    slug = models.CharField(max_length=100, unique=True)
    description = models.TextField(null=True, blank=True)
    icon = models.CharField(max_length=100, null=True, blank=True)
    color = models.CharField(max_length=50, null=True, blank=True)
    sort_order = models.IntegerField(null=True, blank=True)
    is_active = models.BooleanField(default=False)

    class Meta:
        db_table = 'achievement_categories'
        verbose_name = 'AchievementCategories'
        ordering = ['-created_at']

    def __str__(self):
        return str(self.name)

class AchievementProgress(BaseModel):
    """Migrated from sql: 20250116000005_migrate_gamification_schema.sql"""
    user_id = models.UUIDField(null=True, blank=True)
    achievement_id = models.UUIDField(null=True, blank=True)
    current_progress = models.IntegerField(null=True, blank=True)
    target_progress = models.IntegerField(null=True, blank=True)
    progress_percentage = models.IntegerField(null=True, blank=True)
    last_updated_at = models.DateTimeField(null=True, blank=True)
    started_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'achievement_progress'
        verbose_name = 'AchievementProgress'
        constraints = [
            models.UniqueConstraint(fields=['user_id', 'achievement_id'], name='unique_achievement_progress_user_id_achievement_id'),
        ]

class UserStreaks(BaseModel):
    """Migrated from sql: 20250116000005_migrate_gamification_schema.sql"""
    user_id = models.UUIDField(null=True, blank=True, unique=True)
    current_streak = models.IntegerField(null=True, blank=True)
    longest_streak = models.IntegerField(null=True, blank=True)
    last_activity_date = models.DateField(null=True, blank=True)
    streak_start_date = models.DateField(null=True, blank=True)
    total_active_days = models.IntegerField(null=True, blank=True)

    class Meta:
        db_table = 'user_streaks'
        verbose_name = 'UserStreaks'
        ordering = ['-created_at']

class PointsSources(BaseModel):
    """Migrated from sql: 20250116000005_migrate_gamification_schema.sql"""
    name = models.CharField(max_length=200)
    slug = models.CharField(max_length=200, unique=True)
    description = models.TextField(null=True, blank=True)
    points_amount = models.IntegerField(null=True, blank=True)
    points_multiplier = models.DecimalField(max_digits=3, decimal_places=2, null=True, blank=True)
    max_daily_occurrences = models.IntegerField(null=True, blank=True)
    max_total_occurrences = models.IntegerField(null=True, blank=True)
    requires_verification = models.BooleanField(default=False)
    cooldown_minutes = models.IntegerField(null=True, blank=True)
    category = models.CharField(max_length=100, null=True, blank=True)
    is_active = models.BooleanField(default=False)

    class Meta:
        db_table = 'points_sources'
        verbose_name = 'PointsSources'
        ordering = ['-created_at']

    def __str__(self):
        return str(self.name)

class PointsTransactions(BaseModel):
    """Migrated from sql: 20250116000005_migrate_gamification_schema.sql"""
    user_id = models.UUIDField(null=True, blank=True)
    transaction_type = models.CharField(max_length=50)
    points_amount = models.IntegerField(null=True, blank=True)
    balance_after = models.BigIntegerField(null=True, blank=True)
    source_type = models.CharField(max_length=100)
    source_id = models.UUIDField(null=True, blank=True)
    points_source_id = models.UUIDField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    context_data = models.JSONField(default=dict, null=True, blank=True)
    multiplier_applied = models.DecimalField(max_digits=3, decimal_places=2, null=True, blank=True)
    created_by = models.UUIDField(null=True, blank=True)
    is_admin_adjustment = models.BooleanField(default=False)
    admin_note = models.TextField(null=True, blank=True)
    is_reversed = models.BooleanField(default=False)
    reversed_at = models.DateTimeField(null=True, blank=True)
    reversed_by = models.UUIDField(null=True, blank=True)
    created_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'points_transactions'
        verbose_name = 'PointsTransactions'
        ordering = ['-created_at']

class RewardsCatalog(BaseModel):
    """Migrated from sql: 20250116000005_migrate_gamification_schema.sql"""
    name = models.CharField(max_length=200)
    slug = models.CharField(max_length=200, unique=True)
    description = models.TextField(null=True, blank=True)
    image_url = models.TextField(null=True, blank=True)
    icon = models.CharField(max_length=100, null=True, blank=True)
    badge_color = models.CharField(max_length=50, null=True, blank=True)
    points_cost = models.IntegerField(null=True, blank=True)
    original_price_cad = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    reward_type = models.CharField(max_length=100)
    reward_config = models.JSONField(default=dict, null=True, blank=True)
    delivery_method = models.CharField(max_length=100, null=True, blank=True)
    is_available = models.BooleanField(default=False)
    stock_quantity = models.IntegerField(null=True, blank=True)
    max_per_user = models.IntegerField(null=True, blank=True)
    min_level = models.IntegerField(null=True, blank=True)
    required_achievements = models.UUIDField(null=True, blank=True)
    available_from = models.DateTimeField(null=True, blank=True)
    available_until = models.DateTimeField(null=True, blank=True)
    times_redeemed = models.IntegerField(null=True, blank=True)
    created_by = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'rewards_catalog'
        verbose_name = 'RewardsCatalog'
        ordering = ['-created_at']

    def __str__(self):
        return str(self.name)

class UserRewards(BaseModel):
    """Migrated from sql: 20250116000005_migrate_gamification_schema.sql"""
    user_id = models.UUIDField(null=True, blank=True)
    reward_id = models.UUIDField(null=True, blank=True)
    points_spent = models.IntegerField(null=True, blank=True)
    status = models.CharField(max_length=50, null=True, blank=True)
    redemption_code = models.CharField(max_length=100, null=True, blank=True)
    delivery_status = models.CharField(max_length=100, null=True, blank=True)
    delivery_details = models.JSONField(default=dict, null=True, blank=True)
    fulfilled_at = models.DateTimeField(null=True, blank=True)
    fulfilled_by = models.UUIDField(null=True, blank=True)
    notes = models.TextField(null=True, blank=True)
    redeemed_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'user_rewards'
        verbose_name = 'UserRewards'
        ordering = ['-created_at']

class Leaderboards(BaseModel):
    """Migrated from sql: 20250116000005_migrate_gamification_schema.sql"""
    name = models.CharField(max_length=200)
    slug = models.CharField(max_length=200, unique=True)
    description = models.TextField(null=True, blank=True)
    leaderboard_type = models.CharField(max_length=100)
    metric_type = models.CharField(max_length=100)
    time_period = models.CharField(max_length=50, null=True, blank=True)
    start_date = models.DateTimeField(null=True, blank=True)
    end_date = models.DateTimeField(null=True, blank=True)
    organization_id = models.UUIDField(null=True, blank=True)
    is_active = models.BooleanField(default=False)
    is_public = models.BooleanField(default=False)
    prize_pool = models.JSONField(default=dict, null=True, blank=True)

    class Meta:
        db_table = 'leaderboards'
        verbose_name = 'Leaderboards'
        ordering = ['-created_at']

    def __str__(self):
        return str(self.name)

class LeaderboardEntries(BaseModel):
    """Migrated from sql: 20250116000005_migrate_gamification_schema.sql"""
    leaderboard_id = models.UUIDField(null=True, blank=True)
    user_id = models.UUIDField(null=True, blank=True)
    rank = models.IntegerField(null=True, blank=True)
    score = models.BigIntegerField(null=True, blank=True)
    additional_metrics = models.JSONField(default=dict, null=True, blank=True)
    updated_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'leaderboard_entries'
        verbose_name = 'LeaderboardEntries'
        constraints = [
            models.UniqueConstraint(fields=['leaderboard_id', 'user_id'], name='unique_leaderboard_entries_leaderboard_id_user_id'),
        ]

class UserProfilesExtended(BaseModel):
    """Migrated from sql: 20250116000006_gamification_social.sql"""
    user_id = models.UUIDField(null=True, blank=True, unique=True)
    bio = models.TextField(null=True, blank=True)
    tagline = models.CharField(max_length=300, null=True, blank=True)
    location = models.CharField(max_length=200, null=True, blank=True)
    timezone = models.CharField(max_length=100, null=True, blank=True)
    linkedin_url = models.TextField(null=True, blank=True)
    twitter_handle = models.CharField(max_length=100, null=True, blank=True)
    github_username = models.CharField(max_length=100, null=True, blank=True)
    cover_image_url = models.TextField(null=True, blank=True)
    company = models.CharField(max_length=200, null=True, blank=True)
    industry = models.CharField(max_length=100, null=True, blank=True)
    years_of_experience = models.IntegerField(null=True, blank=True)
    interests = models.TextField(null=True, blank=True)
    skill_tags = models.TextField(null=True, blank=True)
    preferred_learning_time = models.CharField(max_length=50, null=True, blank=True)
    study_pace = models.CharField(max_length=50, null=True, blank=True)
    show_achievements = models.BooleanField(default=False)
    show_progress = models.BooleanField(default=False)
    show_activity = models.BooleanField(default=False)
    total_lessons_completed = models.IntegerField(null=True, blank=True)
    total_quiz_attempts = models.IntegerField(null=True, blank=True)
    total_study_time_minutes = models.BigIntegerField(null=True, blank=True)
    following_count = models.IntegerField(null=True, blank=True)
    posts_count = models.IntegerField(null=True, blank=True)
    helpful_answers_count = models.IntegerField(null=True, blank=True)
    custom_badges = models.JSONField(default=dict, null=True, blank=True)
    last_active_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'user_profiles_extended'
        verbose_name = 'UserProfilesExtended'
        ordering = ['-created_at']

class UserFollows(BaseModel):
    """Migrated from sql: 20250116000006_gamification_social.sql"""
    follower_id = models.UUIDField(null=True, blank=True)
    following_id = models.UUIDField(null=True, blank=True)
    follow_type = models.CharField(max_length=50, null=True, blank=True)
    notify_on_activity = models.BooleanField(default=False)
    notify_on_achievements = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)

    class Meta:
        db_table = 'user_follows'
        verbose_name = 'UserFollows'
        constraints = [
            models.UniqueConstraint(fields=['follower_id', 'following_id'], name='unique_user_follows_follower_id_following_id'),
        ]
        ordering = ['-created_at']

class StudyBuddies(BaseModel):
    """Migrated from sql: 20250116000006_gamification_social.sql"""
    user_id = models.UUIDField(null=True, blank=True)
    buddy_id = models.UUIDField(null=True, blank=True)
    match_score = models.IntegerField(null=True, blank=True)
    match_criteria = models.JSONField(default=dict, null=True, blank=True)
    matched_at = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=50, null=True, blank=True)
    accepted_at = models.DateTimeField(null=True, blank=True)
    ended_at = models.DateTimeField(null=True, blank=True)
    study_schedule = models.JSONField(default=dict, null=True, blank=True)
    shared_goals = models.TextField(null=True, blank=True)
    target_courses = models.UUIDField(null=True, blank=True)
    last_interaction_at = models.DateTimeField(null=True, blank=True)
    sessions_completed = models.IntegerField(null=True, blank=True)
    can_message = models.BooleanField(default=False)

    class Meta:
        db_table = 'study_buddies'
        verbose_name = 'StudyBuddies'
        constraints = [
            models.UniqueConstraint(fields=['user_id', 'buddy_id'], name='unique_study_buddies_user_id_buddy_id'),
        ]
        ordering = ['-created_at']

class UserActivityFeed(BaseModel):
    """Migrated from sql: 20250116000006_gamification_social.sql"""
    user_id = models.UUIDField(null=True, blank=True)
    activity_type = models.CharField(max_length=100)
    activity_title = models.TextField(null=True, blank=True)
    activity_description = models.TextField(null=True, blank=True)
    related_type = models.CharField(max_length=100, null=True, blank=True)
    related_id = models.UUIDField(null=True, blank=True)
    related_data = models.JSONField(default=dict, null=True, blank=True)
    thumbnail_url = models.TextField(null=True, blank=True)
    likes_count = models.IntegerField(null=True, blank=True)
    comments_count = models.IntegerField(null=True, blank=True)
    shares_count = models.IntegerField(null=True, blank=True)
    visibility = models.CharField(max_length=50, null=True, blank=True)
    is_pinned = models.BooleanField(default=False)

    class Meta:
        db_table = 'user_activity_feed'
        verbose_name = 'UserActivityFeed'
        ordering = ['-created_at']

class UserGroups(BaseModel):
    """Migrated from sql: 20250116000006_gamification_social.sql"""
    name = models.CharField(max_length=200)
    slug = models.CharField(max_length=200, unique=True)
    description = models.TextField(null=True, blank=True)
    group_type = models.CharField(max_length=50)
    category = models.CharField(max_length=100, null=True, blank=True)
    cover_image_url = models.TextField(null=True, blank=True)
    avatar_url = models.TextField(null=True, blank=True)
    privacy_level = models.CharField(max_length=50, null=True, blank=True)
    join_policy = models.CharField(max_length=50, null=True, blank=True)
    max_members = models.IntegerField(null=True, blank=True)
    members_count = models.IntegerField(null=True, blank=True)
    is_featured = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    created_by = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'user_groups'
        verbose_name = 'UserGroups'
        ordering = ['-created_at']

    def __str__(self):
        return str(self.name)

class GroupMembers(BaseModel):
    """Migrated from sql: 20250116000006_gamification_social.sql"""
    group_id = models.UUIDField(null=True, blank=True)
    user_id = models.UUIDField(null=True, blank=True)
    role = models.CharField(max_length=50, null=True, blank=True)
    joined_at = models.DateTimeField(null=True, blank=True)
    invited_by = models.UUIDField(null=True, blank=True)
    is_active = models.BooleanField(default=False)
    left_at = models.DateTimeField(null=True, blank=True)
    notifications_enabled = models.BooleanField(default=False)
    posts_count = models.IntegerField(null=True, blank=True)
    last_activity_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'group_members'
        verbose_name = 'GroupMembers'
        constraints = [
            models.UniqueConstraint(fields=['group_id', 'user_id'], name='unique_group_members_group_id_user_id'),
        ]
        ordering = ['-created_at']

class DiscussionForums(BaseModel):
    """Migrated from sql: 20250116000006_gamification_social.sql"""
    name = models.CharField(max_length=200)
    slug = models.CharField(max_length=200, unique=True)
    description = models.TextField(null=True, blank=True)
    forum_type = models.CharField(max_length=50, null=True, blank=True)
    parent_forum_id = models.UUIDField(null=True, blank=True)
    group_id = models.UUIDField(null=True, blank=True)
    course_id = models.UUIDField(null=True, blank=True)
    icon = models.CharField(max_length=100, null=True, blank=True)
    cover_image_url = models.TextField(null=True, blank=True)
    display_order = models.IntegerField(null=True, blank=True)
    is_locked = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    topics_count = models.IntegerField(null=True, blank=True)
    posts_count = models.IntegerField(null=True, blank=True)
    last_post_at = models.DateTimeField(null=True, blank=True)
    last_post_by = models.UUIDField(null=True, blank=True)
    created_by = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'discussion_forums'
        verbose_name = 'DiscussionForums'
        ordering = ['-created_at']

    def __str__(self):
        return str(self.name)

class ForumPosts(BaseModel):
    """Migrated from sql: 20250116000006_gamification_social.sql"""
    forum_id = models.UUIDField(null=True, blank=True)
    parent_post_id = models.UUIDField(null=True, blank=True)
    author_id = models.UUIDField(null=True, blank=True)
    title = models.CharField(max_length=500, null=True, blank=True)
    content = models.TextField(null=True, blank=True)
    content_format = models.CharField(max_length=50, null=True, blank=True)
    post_type = models.CharField(max_length=50, null=True, blank=True)
    tags = models.TextField(null=True, blank=True)
    is_pinned = models.BooleanField(default=False)
    is_locked = models.BooleanField(default=False)
    is_featured = models.BooleanField(default=False)
    views_count = models.IntegerField(null=True, blank=True)
    replies_count = models.IntegerField(null=True, blank=True)
    likes_count = models.IntegerField(null=True, blank=True)
    is_solved = models.BooleanField(default=False)
    solved_by_post_id = models.UUIDField(null=True, blank=True)
    solved_at = models.DateTimeField(null=True, blank=True)
    last_reply_at = models.DateTimeField(null=True, blank=True)
    last_reply_by = models.UUIDField(null=True, blank=True)
    attachments = models.JSONField(default=dict, null=True, blank=True)
    edited_at = models.DateTimeField(null=True, blank=True)
    edited_by = models.UUIDField(null=True, blank=True)
    deleted_at = models.DateTimeField(null=True, blank=True)
    deleted_by = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'forum_posts'
        verbose_name = 'ForumPosts'
        ordering = ['-created_at']

    def __str__(self):
        return str(self.title)

class AiInteractionLogs(BaseModel):
    """Migrated from sql: 20250130000001_ai_interaction_logs.sql"""
    organization_id = models.UUIDField(null=True, blank=True)
    user_id = models.UUIDField(null=True, blank=True)
    session_id = models.TextField(null=True, blank=True)
    interaction_type = models.TextField(null=True, blank=True)
    response = models.TextField(null=True, blank=True)
    model = models.TextField(null=True, blank=True)
    tokens_used = models.IntegerField(null=True, blank=True)
    flags = models.TextField(null=True, blank=True)
    verified_sources = models.TextField(null=True, blank=True)
    contains_legal_advice_warning = models.BooleanField(default=False)
    reviewed_by = models.UUIDField(null=True, blank=True)
    reviewed_at = models.DateTimeField(null=True, blank=True)
    review_notes = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'ai_interaction_logs'
        verbose_name = 'AiInteractionLogs'
        ordering = ['-created_at']

class StripeWebhookEvents(BaseModel):
    """Migrated from sql: 20260128000007_stripe_webhook_idempotency.sql"""
    processed_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'stripe_webhook_events'
        verbose_name = 'StripeWebhookEvents'
        ordering = ['-created_at']

class AiUsageDaily(BaseModel):
    """Migrated from sql: 20260203_ai_usage_tracking.sql"""
    organization_id = models.UUIDField(null=True, blank=True)
    date = models.DateField(null=True, blank=True)
    gpt35_requests = models.IntegerField(null=True, blank=True)
    claude_requests = models.IntegerField(null=True, blank=True)
    embedding_requests = models.IntegerField(null=True, blank=True)
    gpt4_output_tokens = models.BigIntegerField(null=True, blank=True)
    gpt35_input_tokens = models.BigIntegerField(null=True, blank=True)
    gpt35_output_tokens = models.BigIntegerField(null=True, blank=True)
    claude_input_tokens = models.BigIntegerField(null=True, blank=True)
    claude_output_tokens = models.BigIntegerField(null=True, blank=True)
    embedding_tokens = models.BigIntegerField(null=True, blank=True)
    gpt35_cost_cents = models.IntegerField(null=True, blank=True)
    claude_cost_cents = models.IntegerField(null=True, blank=True)
    embedding_cost_cents = models.IntegerField(null=True, blank=True)
    total_cost_cents = models.IntegerField(null=True, blank=True)
    updated_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'ai_usage_daily'
        verbose_name = 'AiUsageDaily'

class AiQuota(BaseModel):
    """Migrated from sql: 20260203_ai_usage_tracking.sql"""
    organization_id = models.UUIDField(null=True, blank=True)
    daily_gpt35_limit = models.IntegerField(null=True, blank=True)
    daily_claude_limit = models.IntegerField(null=True, blank=True)
    daily_embedding_limit = models.IntegerField(null=True, blank=True)
    send_warnings = models.BooleanField(default=False)
    alert_slack_webhook = models.TextField(null=True, blank=True)
    updated_at = models.DateTimeField(null=True, blank=True)
    created_by = models.UUIDField(null=True, blank=True)
    updated_by = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'ai_quota'
        verbose_name = 'AiQuota'

class CanliiIngestionRuns(BaseModel):
    """Migrated from sql: 20260203_canlii_ingestion_tracking.sql"""
    completed_at = models.DateTimeField(null=True, blank=True)
    status = models.TextField(null=True, blank=True)
    successful_requests = models.IntegerField(null=True, blank=True)
    failed_requests = models.IntegerField(null=True, blank=True)
    rate_limited_requests = models.IntegerField(null=True, blank=True)
    max_request_duration_ms = models.IntegerField(null=True, blank=True)
    avg_request_duration_ms = models.IntegerField(null=True, blank=True)
    total_duration_ms = models.IntegerField(null=True, blank=True)
    cases_updated = models.IntegerField(null=True, blank=True)
    cases_created = models.IntegerField(null=True, blank=True)
    cases_skipped = models.IntegerField(null=True, blank=True)
    error_occurred_at = models.DateTimeField(null=True, blank=True)
    exceeded_rate_limit = models.BooleanField(default=False)
    kill_switch_active = models.BooleanField(default=False)
    trigger_source = models.TextField(null=True, blank=True)
    updated_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'canlii_ingestion_runs'
        verbose_name = 'CanliiIngestionRuns'

class CanliiApiRequests(BaseModel):
    """Migrated from sql: 20260203_canlii_ingestion_tracking.sql"""
    ingestion_run_id = models.UUIDField(null=True, blank=True)
    response_time_ms = models.IntegerField(null=True, blank=True)
    success = models.BooleanField(default=False)
    rate_limited = models.BooleanField(default=False)
    retry_after_seconds = models.IntegerField(null=True, blank=True)
    suggested = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'canlii_api_requests'
        verbose_name = 'CanliiApiRequests'

class CanliiDailyQuotas(BaseModel):
    """Migrated from sql: 20260203_canlii_ingestion_tracking.sql"""
    date = models.DateField(null=True, blank=True)
    successful_requests = models.IntegerField(null=True, blank=True)
    failed_requests = models.IntegerField(null=True, blank=True)
    rate_limited_requests = models.IntegerField(null=True, blank=True)
    limit_exceeded = models.BooleanField(default=False)
    limit_exceeded_at = models.DateTimeField(null=True, blank=True)
    peak_requests_per_second = models.DecimalField(max_digits=5, decimal_places=2)
    successful_runs = models.IntegerField(null=True, blank=True)
    failed_runs = models.IntegerField(null=True, blank=True)

    class Meta:
        db_table = 'canlii_daily_quotas'
        verbose_name = 'CanliiDailyQuotas'
        ordering = ['-created_at']

class OrgOffboardingRequests(BaseModel):
    """Migrated from sql: 20260203_org_offboarding.sql"""
    organization_id = models.UUIDField(null=True, blank=True)
    requested_at = models.DateTimeField(null=True, blank=True)
    reason = models.TextField(null=True, blank=True)
    export_completed_at = models.DateTimeField(null=True, blank=True)
    export_file_path = models.TextField(null=True, blank=True)
    export_download_url = models.TextField(null=True, blank=True)
    stripe_cancellation_completed_at = models.DateTimeField(null=True, blank=True)
    stripe_subscription_id = models.TextField(null=True, blank=True)
    stripe_cancelled_at = models.DateTimeField(null=True, blank=True)
    access_revocation_completed_at = models.DateTimeField(null=True, blank=True)
    users_disabled_count = models.IntegerField(null=True, blank=True)
    sessions_invalidated_count = models.IntegerField(null=True, blank=True)
    error_occurred_at = models.DateTimeField(null=True, blank=True)
    retry_count = models.IntegerField(null=True, blank=True)
    completed_by = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'org_offboarding_requests'
        verbose_name = 'OrgOffboardingRequests'
        ordering = ['-created_at']

class DataExportContents(BaseModel):
    """Migrated from sql: 20260203_org_offboarding.sql"""
    offboarding_request_id = models.UUIDField(null=True, blank=True)
    total_files = models.IntegerField(null=True, blank=True)
    total_size_bytes = models.BigIntegerField(null=True, blank=True)
    courses_exported = models.IntegerField(null=True, blank=True)
    enrollments_exported = models.IntegerField(null=True, blank=True)
    progress_records_exported = models.IntegerField(null=True, blank=True)
    quiz_attempts_exported = models.IntegerField(null=True, blank=True)
    certificates_exported = models.IntegerField(null=True, blank=True)
    achievements_exported = models.IntegerField(null=True, blank=True)
    ai_usage_exported = models.IntegerField(null=True, blank=True)
    billing_records_exported = models.IntegerField(null=True, blank=True)
    audit_logs_exported = models.IntegerField(null=True, blank=True)

    class Meta:
        db_table = 'data_export_contents'
        verbose_name = 'DataExportContents'

class OffboardingAuditLog(BaseModel):
    """Migrated from sql: 20260203_org_offboarding.sql"""
    offboarding_request_id = models.UUIDField(null=True, blank=True)
    actor_role = models.TextField(null=True, blank=True)
    user_agent = models.TextField(null=True, blank=True)
    error_message = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'offboarding_audit_log'
        verbose_name = 'OffboardingAuditLog'
        ordering = ['-created_at']
