"""
DRF serializers for core app.
Auto-generated by Nzila Code Generator — 2026-02-17
"""
from rest_framework import serializers
from .models import (CourseModules, CourseVersions, CourseDiscussions, LearningPaths, LearningPathEnrollments, EvidenceBundlePdfs, CaseOutcomes, OutcomePredictions, PredictionModels, Questions, QuestionOptions, QuestionPools, PoolQuestions, QuizQuestions, QuizResponses, CertificateTemplates, Certificates, DigitalBadges, Skills, CourseSkills, LessonSkills, QuestionSkills, UserSkills, SkillValidations, SkillPrerequisites, CourseWorkflowReviews, CourseWorkflowHistory, ContentQualityChecklists, InstructorProfiles, CourseInstructors, InstructorAnalytics, InstructorCommunications, InstructorEarnings, SsoProviders, EnterpriseSessions, IdentityProviderMapping, SsoLoginAttempts, ResourcePermissions, PermissionOverrides, RoleHierarchy, PermissionCache, ComplianceReports, AuditLogExports, AuditLogsArchive, TribunalCasesRaw, IngestionJobs, IngestionErrors, AchievementCategories, AchievementProgress, UserStreaks, PointsSources, PointsTransactions, RewardsCatalog, UserRewards, Leaderboards, LeaderboardEntries, UserProfilesExtended, UserFollows, StudyBuddies, UserActivityFeed, UserGroups, GroupMembers, DiscussionForums, ForumPosts, AiInteractionLogs, StripeWebhookEvents, AiUsageDaily, AiQuota, CanliiIngestionRuns, CanliiApiRequests, CanliiDailyQuotas, OrgOffboardingRequests, DataExportContents, OffboardingAuditLog)


class CourseModulesSerializer(serializers.ModelSerializer):
    class Meta:
        model = CourseModules
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class CourseVersionsSerializer(serializers.ModelSerializer):
    class Meta:
        model = CourseVersions
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class CourseDiscussionsSerializer(serializers.ModelSerializer):
    class Meta:
        model = CourseDiscussions
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class LearningPathsSerializer(serializers.ModelSerializer):
    class Meta:
        model = LearningPaths
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class LearningPathEnrollmentsSerializer(serializers.ModelSerializer):
    class Meta:
        model = LearningPathEnrollments
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class EvidenceBundlePdfsSerializer(serializers.ModelSerializer):
    class Meta:
        model = EvidenceBundlePdfs
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class CaseOutcomesSerializer(serializers.ModelSerializer):
    class Meta:
        model = CaseOutcomes
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class OutcomePredictionsSerializer(serializers.ModelSerializer):
    class Meta:
        model = OutcomePredictions
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class PredictionModelsSerializer(serializers.ModelSerializer):
    class Meta:
        model = PredictionModels
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class QuestionsSerializer(serializers.ModelSerializer):
    class Meta:
        model = Questions
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class QuestionOptionsSerializer(serializers.ModelSerializer):
    class Meta:
        model = QuestionOptions
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class QuestionPoolsSerializer(serializers.ModelSerializer):
    class Meta:
        model = QuestionPools
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class PoolQuestionsSerializer(serializers.ModelSerializer):
    class Meta:
        model = PoolQuestions
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class QuizQuestionsSerializer(serializers.ModelSerializer):
    class Meta:
        model = QuizQuestions
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class QuizResponsesSerializer(serializers.ModelSerializer):
    class Meta:
        model = QuizResponses
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class CertificateTemplatesSerializer(serializers.ModelSerializer):
    class Meta:
        model = CertificateTemplates
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class CertificatesSerializer(serializers.ModelSerializer):
    class Meta:
        model = Certificates
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class DigitalBadgesSerializer(serializers.ModelSerializer):
    class Meta:
        model = DigitalBadges
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class SkillsSerializer(serializers.ModelSerializer):
    class Meta:
        model = Skills
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class CourseSkillsSerializer(serializers.ModelSerializer):
    class Meta:
        model = CourseSkills
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class LessonSkillsSerializer(serializers.ModelSerializer):
    class Meta:
        model = LessonSkills
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class QuestionSkillsSerializer(serializers.ModelSerializer):
    class Meta:
        model = QuestionSkills
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class UserSkillsSerializer(serializers.ModelSerializer):
    class Meta:
        model = UserSkills
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class SkillValidationsSerializer(serializers.ModelSerializer):
    class Meta:
        model = SkillValidations
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class SkillPrerequisitesSerializer(serializers.ModelSerializer):
    class Meta:
        model = SkillPrerequisites
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class CourseWorkflowReviewsSerializer(serializers.ModelSerializer):
    class Meta:
        model = CourseWorkflowReviews
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class CourseWorkflowHistorySerializer(serializers.ModelSerializer):
    class Meta:
        model = CourseWorkflowHistory
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class ContentQualityChecklistsSerializer(serializers.ModelSerializer):
    class Meta:
        model = ContentQualityChecklists
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class InstructorProfilesSerializer(serializers.ModelSerializer):
    class Meta:
        model = InstructorProfiles
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class CourseInstructorsSerializer(serializers.ModelSerializer):
    class Meta:
        model = CourseInstructors
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class InstructorAnalyticsSerializer(serializers.ModelSerializer):
    class Meta:
        model = InstructorAnalytics
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class InstructorCommunicationsSerializer(serializers.ModelSerializer):
    class Meta:
        model = InstructorCommunications
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class InstructorEarningsSerializer(serializers.ModelSerializer):
    class Meta:
        model = InstructorEarnings
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class SsoProvidersSerializer(serializers.ModelSerializer):
    class Meta:
        model = SsoProviders
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class EnterpriseSessionsSerializer(serializers.ModelSerializer):
    class Meta:
        model = EnterpriseSessions
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class IdentityProviderMappingSerializer(serializers.ModelSerializer):
    class Meta:
        model = IdentityProviderMapping
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class SsoLoginAttemptsSerializer(serializers.ModelSerializer):
    class Meta:
        model = SsoLoginAttempts
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class ResourcePermissionsSerializer(serializers.ModelSerializer):
    class Meta:
        model = ResourcePermissions
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class PermissionOverridesSerializer(serializers.ModelSerializer):
    class Meta:
        model = PermissionOverrides
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class RoleHierarchySerializer(serializers.ModelSerializer):
    class Meta:
        model = RoleHierarchy
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class PermissionCacheSerializer(serializers.ModelSerializer):
    class Meta:
        model = PermissionCache
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class ComplianceReportsSerializer(serializers.ModelSerializer):
    class Meta:
        model = ComplianceReports
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class AuditLogExportsSerializer(serializers.ModelSerializer):
    class Meta:
        model = AuditLogExports
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class AuditLogsArchiveSerializer(serializers.ModelSerializer):
    class Meta:
        model = AuditLogsArchive
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class TribunalCasesRawSerializer(serializers.ModelSerializer):
    class Meta:
        model = TribunalCasesRaw
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class IngestionJobsSerializer(serializers.ModelSerializer):
    class Meta:
        model = IngestionJobs
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class IngestionErrorsSerializer(serializers.ModelSerializer):
    class Meta:
        model = IngestionErrors
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class AchievementCategoriesSerializer(serializers.ModelSerializer):
    class Meta:
        model = AchievementCategories
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class AchievementProgressSerializer(serializers.ModelSerializer):
    class Meta:
        model = AchievementProgress
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class UserStreaksSerializer(serializers.ModelSerializer):
    class Meta:
        model = UserStreaks
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class PointsSourcesSerializer(serializers.ModelSerializer):
    class Meta:
        model = PointsSources
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class PointsTransactionsSerializer(serializers.ModelSerializer):
    class Meta:
        model = PointsTransactions
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class RewardsCatalogSerializer(serializers.ModelSerializer):
    class Meta:
        model = RewardsCatalog
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class UserRewardsSerializer(serializers.ModelSerializer):
    class Meta:
        model = UserRewards
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class LeaderboardsSerializer(serializers.ModelSerializer):
    class Meta:
        model = Leaderboards
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class LeaderboardEntriesSerializer(serializers.ModelSerializer):
    class Meta:
        model = LeaderboardEntries
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class UserProfilesExtendedSerializer(serializers.ModelSerializer):
    class Meta:
        model = UserProfilesExtended
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class UserFollowsSerializer(serializers.ModelSerializer):
    class Meta:
        model = UserFollows
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class StudyBuddiesSerializer(serializers.ModelSerializer):
    class Meta:
        model = StudyBuddies
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class UserActivityFeedSerializer(serializers.ModelSerializer):
    class Meta:
        model = UserActivityFeed
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class UserGroupsSerializer(serializers.ModelSerializer):
    class Meta:
        model = UserGroups
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class GroupMembersSerializer(serializers.ModelSerializer):
    class Meta:
        model = GroupMembers
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class DiscussionForumsSerializer(serializers.ModelSerializer):
    class Meta:
        model = DiscussionForums
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class ForumPostsSerializer(serializers.ModelSerializer):
    class Meta:
        model = ForumPosts
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class AiInteractionLogsSerializer(serializers.ModelSerializer):
    class Meta:
        model = AiInteractionLogs
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class StripeWebhookEventsSerializer(serializers.ModelSerializer):
    class Meta:
        model = StripeWebhookEvents
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class AiUsageDailySerializer(serializers.ModelSerializer):
    class Meta:
        model = AiUsageDaily
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class AiQuotaSerializer(serializers.ModelSerializer):
    class Meta:
        model = AiQuota
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class CanliiIngestionRunsSerializer(serializers.ModelSerializer):
    class Meta:
        model = CanliiIngestionRuns
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class CanliiApiRequestsSerializer(serializers.ModelSerializer):
    class Meta:
        model = CanliiApiRequests
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class CanliiDailyQuotasSerializer(serializers.ModelSerializer):
    class Meta:
        model = CanliiDailyQuotas
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class OrgOffboardingRequestsSerializer(serializers.ModelSerializer):
    class Meta:
        model = OrgOffboardingRequests
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class DataExportContentsSerializer(serializers.ModelSerializer):
    class Meta:
        model = DataExportContents
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class OffboardingAuditLogSerializer(serializers.ModelSerializer):
    class Meta:
        model = OffboardingAuditLog
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']
