"""
URL configuration for auth_core app.
Auto-generated by Nzila Code Generator — 2026-02-17
"""

from django.urls import include, path
from rest_framework.routers import DefaultRouter

from . import views

router = DefaultRouter()
router.register(r"international-addresses", views.InternationalAddressesViewSet)
router.register(r"country-address-formats", views.CountryAddressFormatsViewSet)
router.register(r"address-validation-cache", views.AddressValidationCacheViewSet)
router.register(r"address-change-history", views.AddressChangeHistoryViewSet)
router.register(r"feature-flags", views.FeatureFlagsViewSet)
router.register(
    r"organization-sharing-settings", views.OrganizationSharingSettingsViewSet
)
router.register(r"cross-org-access-log", views.CrossOrgAccessLogViewSet)
router.register(r"organization-sharing-grants", views.OrganizationSharingGrantsViewSet)
router.register(r"user-uuid-mapping", views.UserUuidMappingViewSet)
router.register(r"pending-profiles", views.PendingProfilesViewSet)
router.register(r"profiles", views.ProfilesViewSet)
router.register(r"users", views.UsersViewSet)
router.register(r"organization-users", views.OrganizationUsersViewSet)
router.register(r"user-sessions", views.UserSessionsViewSet)
router.register(r"oauth-providers", views.OauthProvidersViewSet)
router.register(r"member-contact-preferences", views.MemberContactPreferencesViewSet)
router.register(r"member-employment-details", views.MemberEmploymentDetailsViewSet)
router.register(r"member-consents", views.MemberConsentsViewSet)
router.register(r"member-history-events", views.MemberHistoryEventsViewSet)
router.register(r"organization-members", views.OrganizationMembersViewSet)
router.register(r"sso-providers", views.SsoProvidersViewSet)
router.register(r"scim-configurations", views.ScimConfigurationsViewSet)
router.register(r"sso-sessions", views.SsoSessionsViewSet)
router.register(r"scim-events-log", views.ScimEventsLogViewSet)
router.register(r"mfa-configurations", views.MfaConfigurationsViewSet)

app_name = "auth_core"

urlpatterns = [
    path("", include(router.urls)),
    # Clerk authentication endpoints
    path("me/", views.me, name="me"),
    path("profile/", views.member_profile, name="member_profile"),
    path("webhooks/auth/", views.auth_webhook, name="auth_webhook"),
    path(
        "webhooks/clerk/", views.auth_webhook, name="clerk_webhook"
    ),  # backward compat
    path("live/", views.liveness_check, name="liveness_check"),
    path("ready/", views.readiness_check, name="readiness_check"),
    path("health/", views.health_check, name="health_check"),
]
