/**
 * Leadership Report Export Utilities
 *
 * PDF board summary and CSV detail export for leadership metrics.
 * Client-side generation for immediate download.
 *
 * @module components/leadership/leadership-export
 */

"use client";

import * as React from "react";
import { Download, FileText, Table2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";

// ─── Types ────────────────────────────────────────────────────

export interface ExportableMetrics {
  title: string;
  generatedAt: string;
  organizationName?: string;
  kpi: Record<string, string | number>;
  employerRows: Array<Record<string, string | number>>;
  stewardRows: Array<Record<string, string | number>>;
}

export interface LeadershipExportProps {
  metrics: ExportableMetrics;
  onExportStarted?: (format: "pdf" | "csv") => void;
}

// ─── CSV Generation ───────────────────────────────────────────

function toCSV(headers: string[], rows: Array<Record<string, string | number>>): string {
  const headerLine = headers.join(",");
  const lines = rows.map((row) =>
    headers
      .map((h) => {
        const val = String(row[h] ?? "");
        return val.includes(",") || val.includes('"')
          ? `"${val.replace(/"/g, '""')}"`
          : val;
      })
      .join(",")
  );
  return [headerLine, ...lines].join("\n");
}

function downloadBlob(content: string, filename: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

// ─── PDF-style summary (HTML → print) ─────────────────────────

function generatePrintableSummary(metrics: ExportableMetrics): string {
  const kpiRows = Object.entries(metrics.kpi)
    .map(([k, v]) => `<tr><td style="padding:4px 8px;border:1px solid #ddd">${k}</td><td style="padding:4px 8px;border:1px solid #ddd;text-align:right;font-weight:bold">${v}</td></tr>`)
    .join("");

  return `<!DOCTYPE html>
<html><head><title>${metrics.title}</title>
<style>
  body{font-family:system-ui,sans-serif;padding:40px;max-width:800px;margin:0 auto}
  h1{font-size:24px;color:#1a1a2e}
  h2{font-size:16px;color:#444;margin-top:32px}
  table{border-collapse:collapse;width:100%;margin-top:8px}
  th{background:#f4f4f5;padding:6px 8px;border:1px solid #ddd;text-align:left;font-size:12px}
  td{padding:4px 8px;border:1px solid #ddd;font-size:12px}
  .meta{color:#666;font-size:12px;margin-top:4px}
  .footer{margin-top:40px;padding-top:16px;border-top:1px solid #ddd;font-size:10px;color:#888}
  @media print{body{padding:20px}h1{font-size:20px}}
</style></head><body>
<h1>${metrics.title}</h1>
<p class="meta">${metrics.organizationName ?? ""} — Generated ${metrics.generatedAt}</p>

<h2>Key Performance Indicators</h2>
<table>${kpiRows}</table>

<h2>Employer Summary</h2>
<table>
<tr>${metrics.employerRows.length > 0 ? Object.keys(metrics.employerRows[0]).map(h => `<th>${h}</th>`).join("") : ""}</tr>
${metrics.employerRows.map(r => `<tr>${Object.values(r).map(v => `<td>${v}</td>`).join("")}</tr>`).join("")}
</table>

<h2>Steward Workload</h2>
<table>
<tr>${metrics.stewardRows.length > 0 ? Object.keys(metrics.stewardRows[0]).map(h => `<th>${h}</th>`).join("") : ""}</tr>
${metrics.stewardRows.map(r => `<tr>${Object.values(r).map(v => `<td>${v}</td>`).join("")}</tr>`).join("")}
</table>

<div class="footer">This report is confidential. Generated by UnionEyes for internal use only.</div>
</body></html>`;
}

// ─── Component ────────────────────────────────────────────────

export function LeadershipExport({ metrics, onExportStarted }: LeadershipExportProps) {
  const handleCSV = () => {
    onExportStarted?.("csv");

    // KPI sheet
    const kpiCSV = toCSV(
      ["Metric", "Value"],
      Object.entries(metrics.kpi).map(([k, v]) => ({ Metric: k, Value: v }))
    );

    // Employer sheet
    const empHeaders = metrics.employerRows.length > 0 ? Object.keys(metrics.employerRows[0]) : [];
    const empCSV = toCSV(empHeaders, metrics.employerRows);

    // Steward sheet
    const stewHeaders = metrics.stewardRows.length > 0 ? Object.keys(metrics.stewardRows[0]) : [];
    const stewCSV = toCSV(stewHeaders, metrics.stewardRows);

    const combined = [
      "# KPI Summary",
      kpiCSV,
      "",
      "# Employer Grievances",
      empCSV,
      "",
      "# Steward Workload",
      stewCSV,
    ].join("\n");

    downloadBlob(
      combined,
      `leadership-report-${new Date().toISOString().slice(0, 10)}.csv`,
      "text/csv;charset=utf-8;"
    );
  };

  const handlePDF = () => {
    onExportStarted?.("pdf");
    const html = generatePrintableSummary(metrics);
    const printWindow = window.open("", "_blank");
    if (printWindow) {
      printWindow.document.write(html);
      printWindow.document.close();
      printWindow.focus();
      printWindow.print();
    }
  };

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" size="sm">
          <Download className="h-3.5 w-3.5 mr-1.5" />
          Export
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem onClick={handlePDF}>
          <FileText className="h-3.5 w-3.5 mr-2" />
          PDF Board Summary
        </DropdownMenuItem>
        <DropdownMenuItem onClick={handleCSV}>
          <Table2 className="h-3.5 w-3.5 mr-2" />
          CSV Detail Export
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
